### ISSUE TITLE
Server to Server - share shared file via link

### ISSUE THREAD

**Issue by hc42** [owncloud/core#10101]
Hello,
I have tried to share a local shared file via a link to an other instance. This didn't work at all.

To reproduce:
1. User A@server1 share file or folder to user B@server1
2. User B@server1 share the shared file via link to user C@server2
3. User C@server2 download the file via server2 (gets zip file)
4. User C extract downloaded file and gets empty folder?

Can you confirm this?

**Comment by enoch85** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/8.0/developer_manual/). :)

Thank you!
