### ISSUE TITLE
Case sensitive problem still exist in OC7 shared folder when using with a desktop client?

### ISSUE THREAD

**Issue by KKyang** [owncloud/core#10126]
### System Configuration
**OS:** Ubuntu 14.04 LTS with desktop environment
**Server:** Apache 2.4.7
**PHP version:** 5.5.9
**Database:** MySQL
**OwnCloud:** 7.0.0 update from 6.0.4

### Step to Reproduce
There's a shared folder named "Application". What's inside are folder "Legacy", "Analysis".
1. User A change "Legacy", "Analysis" to "legacy", and "analysis from browser.
2. User A change "Application" to "application"  from browser.
3. User B open the desktop client and start syncing

### Actual Behaviour
User B deleted whole "application" folder and what's inside. Then create only "Application" and "Analysis" cause user B did not sync folder "Legacy" before. (I found all the deleted folders in the trashbin.) Folder "legacy" is deleted and was found in trashbin and cannot be restored. (Cause "application" has been renamed back to "Application")

### Expect Behaviour
The client side should change its local "Application" to "application"

### OwnCloud Log
The following log is when I try to restore the folder in the trashbin.
```
Debug	OC\Files\Cache\Scanner	!!! No reuse of etag for 'Application/Analysis' !!! cache: Array ( [fileid] => 69775 [storage] => home::XXXX [path] => Application/Analysis [parent] => 69752 [name] => Analysis [mimetype] => httpd/unix-directory [mimepart] => httpd [size] => 544627 [mtime] => 1407060694 [storage_mtime] => 1407060694 [encrypted] => [unencrypted_size] => 0 [etag] => 53de0ad6c8459 [permissions] => 31 [displayname_owner] => XXX [uid_owner] => XXX ) data: Array ( [mimetype] => httpd/unix-directory [mtime] => 1407060698 [size] => -1 [etag] => 53de0adb197ca [storage_mtime] => 1407060698 [permissions] => 31 [parent] => 69752 ) 	2014-08-03T10:11:39+00:00
```

**Comment by enoch85** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/8.0/developer_manual/). :)

Thank you!
