### ISSUE TITLE
[7.0.1] Share with group shares back to original user

### ISSUE THREAD

**Issue by ser72** [owncloud/core#10265]
**Expected behavior**
All users in the group other than the owner gets the share

**Actual behavior**
Owner gets the share

**Steps**
User A in Group Admin shares folder with User B 
User B reshares folder with group Admin
User A gets the file as a share to them:

![capture](https://cloud.githubusercontent.com/assets/5174383/3845423/57b26256-1e52-11e4-836f-dc70ab90cec6.PNG)

**Comment by enoch85** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/5.0/developer_manual/). :)

Thank you!
