### ISSUE TITLE
Updating ownCloud to version 7.0.1, this may take a while.

### ISSUE THREAD

**Issue by the-ab** [owncloud/core#10329]
update from last stable version 6 to new version 7

An exception occurred while executing 'CREATE INDEX oc_0cb45f6d43d2c ON `oc_oc_appconfig_a11a5d2bc90e7` (`appid`)': SQLSTATE[42000]: Syntax error or access violation: 1142 INDEX command denied to user 'web1'@'localhost' for table 'oc_oc_appconfig_a11a5d2bc90e7'

-----
 starting upgrade from 6.0.4.1 to 7.0.1.1 

Simulated database structure update failed (exception 'OC\DB\MigrationException' with message 'An exception occurred while executing 'CREATE INDEX oc_f51dc601cec34 ON `oc_oc_appconfig_87c1e4c3412a7` (`appid`)': SQLSTATE[42000]: Syntax error or access violation: 1142 INDEX command denied to user 'web1'@'localhost' for table 'oc_oc_appconfig_87c1e4c3412a7'' in /var/www/web1/html/cloud/sync/lib/private/db/migrator.php:117 Stack trace: #0 /var/www/web1/html/cloud/sync/lib/private/db/migrator.php(75): OC\DB\Migrator->checkTableMigrate(Object(Doctrine\DBAL\Schema\Table)) #1 /var/www/web1/html/cloud/sync/lib/private/db/mdb2schemamanager.php(111): OC\DB\Migrator->checkMigrate(Object(Doctrine\DBAL\Schema\Schema)) #2 /var/www/web1/html/cloud/sync/lib/private/db.php(337): OC\DB\MDB2SchemaManager->simulateUpdateDbFromStructure('/var/www/web1/h...') #3 /var/www/web1/html/cloud/sync/lib/private/updater.php(186): OC_DB::simulateUpdateDbFromStructure('/var/www/web1/h...') #4 /var/www/web1/html/cloud/sync/lib/private/updater.php(137): OC\Updater->doUpgrade('7.0.1.1', '6.0.4.1') #5 /var/www/web1/html/cloud/sync/core/ajax/update.php(35): OC\Updater->upgrade() #6 {main}) 

-------
every big update my server broken!
do not ask me what and where, I can not so good english and me it's too much work to occupy me with this error

**Comment by enoch85** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/5.0/developer_manual/). :)

Thank you!
