### ISSUE TITLE
"No file chosen" extra tooltip on upload button

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#10389]
### Steps to reproduce.
1. Open the files app in the web UI
2. Move the mouse over the "Upload button" until it shows a hand cursor, then leave it there

### Expected result
Only one tooltip

### Actual result
Two tooltips:
![nofilechosen](https://cloud.githubusercontent.com/assets/277525/3903958/d89d24f8-22d2-11e4-831d-a01928c87c7c.png)

Chrome shows "No files chosen" and Firefox shows "No files selected".
I suspect it might be the native file upload input box that is somehow hidden behind the button.

### Versions
ownCloud 7.0.1
Chromium 36 and Firefox 31

CC @stephane84 @requist if you'd like to have a look.

**Comment by enoch85** [comment]
@jancborchardt You think you can take a look at this?

**Comment by jancborchardt** [comment]
@luckydonald @vgezer @enoch85 any update on this? I’d be happy if one of you can fix this and prepare a pull request.

**Comment by MorrisJobke** [comment]
The fix for the title is already in master and the additional tooltip is browser specific and there seems to be no way to remove it. 

https://stackoverflow.com/questions/1084925/input-type-file-show-only-button <- they only remove the text beside the input, but not the actual tooltip. Therefore I would close this as "not fixable".

**Comment by luckydonald** [comment]
Using a label tag like outlined [above](https://github.com/owncloud/core/issues/10389#issuecomment-52390976) didn't do the trick?

**Comment by MorrisJobke** [comment]
@luckydonald No, this is already in place :(
