### ISSUE TITLE
When Admin sets user quota to “0” (zero), creation of  new TXT file should be disabled.

### ISSUE THREAD

**Issue by farson2003** [owncloud/core#10455]
When Admin sets user quota to “0” (zero), user can still create  TXT messages with the native Owncloud TXT editor. 
A quota of “0” should –following typical logic- completely disable the creation of any new file, at least in my opinion.

**Comment by PVince81** [comment]
We're past feature freeze, moving to 9.0

@MTRichards @cmonteroluque

**Comment by PVince81** [comment]
Thinking of this, I see two different cases here:
1) when admin explicitly sets the quota to zero with the intention of making an account read-only
and
2) when the quota is non-zero but there are zero bytes available

Do we want to prevent the creation of empty files for both cases or only the explicit case 1) ?

**Comment by PVince81** [comment]
an alternative would be to introduce a checkbox "read-only" for read-only accounts. The advantage of this is that the read-only nature is more explicit and also makes it possible to have proper error messages "Account is read-only" instead of "Insufficient space". The read-only nature could be achieved on permissions level.

**Comment by PVince81** [comment]
@IljaN is there a ticket to document the new "read-only" feature in core ?

**Comment by PVince81** [comment]
Please use the guest app feature which makes it possible to have read-only accounts.
