### ISSUE TITLE
Stuck at initial encryption / no oc_encryption database table

### ISSUE THREAD

**Issue by 1pilo** [owncloud/core#10482]
My owncloud 7.0.1 is stuck at initial encryption after updating from 6.0.4

I tried to solve the problem with the hint at the german board: https://forum.owncloud.org/viewtopic.php?f=21&t=20172

However my owncloud database has no oc_encryption table.

Here's the list of tables:
+------------------------------+
| Tables_in_owncloud           |
+------------------------------+
| oc_activity                  |
| oc_activity_mq               |
| oc_appconfig                 |
| oc_clndr_calendars           |
| oc_clndr_objects             |
| oc_clndr_repeat              |
| oc_clndr_share_calendar      |
| oc_clndr_share_event         |
| oc_contacts_addressbooks     |
| oc_contacts_cards            |
| oc_contacts_cards_properties |
| oc_documents_invite          |
| oc_documents_member          |
| oc_documents_op              |
| oc_documents_revisions       |
| oc_documents_session         |
| oc_file_map                  |
| oc_filecache                 |
| oc_files_trash               |
| oc_gallery_sharing           |
| oc_group_admin               |
| oc_group_user                |
| oc_groups                    |
| oc_jobs                      |
| oc_locks                     |
| oc_lucene_status             |
| oc_mimetypes                 |
| oc_permissions               |
| oc_pictures_images_cache     |
| oc_preferences               |
| oc_privatedata               |
| oc_properties                |
| oc_share                     |
| oc_share_external            |
| oc_storages                  |
| oc_users                     |
| oc_vcategory                 |
| oc_vcategory_to_object       |
+------------------------------+

Any solutions?

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/5.0/developer_manual/). :)

Thank you!
