### ISSUE TITLE
Thumbnails not regenerated when reverting to an earlier version of a file

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#10559]
### Steps to reproduce
0.  Make sure the Versions app is enabled
1. Create a new document (click on "new"->text file from the "files" view)
2. Enter some basic text; save; close
3. Validate that the thumbnail next to the file is accurate
4.  Edit the file a second time
5.  Validate that the thumbnail changed as expected. 
6.  Highlight the file, select "versions", select previous version
7.  The thumbnail did not revert

I see this with both FF and chrome. I cleared the cache to ensure that this isn't a caching issue.

![p1](https://cloud.githubusercontent.com/assets/8480343/3986469/218e3580-289b-11e4-8733-7545f25bdb37.PNG)

![p2](https://cloud.githubusercontent.com/assets/8480343/3986476/2fd18e76-289b-11e4-8d8f-e236bc3cf5a4.PNG)

### Expected behaviour

The thumbnail should revert too

### Actual behaviour

The thumbnail reflects the earlier version

### Server configuration

**ownCloud version:** (see ownCloud admin page)

ownCloud 7.0.1 (daily) Build:2014-08-20T03:18:51+00:00

**Comment by oparoz** [comment]
@schiesbn @PVince81 Has the missing hook been added to OC8?

**Comment by schiesbn** [comment]
@georgehrke I think you are right. We didn't noticed this until now because no other app had to listen to a revert event.

OC\Filesystem doesn't trigger a hook on revert because to operation happens outside of ```data/<user>/files```. This means that we most likely need a versions related hook. I would suggest to just emit a hook here https://github.com/owncloud/core/blob/master/apps/files_versions/lib/storage.php#L273 with all the information you need.

This could be also interesting for the activity app cc @nickvergessen

**Comment by schiesbn** [comment]
BTW, sorry that it took me so long to response to this issue. Feel free to ping me on IRC, Jabber or E-Mail the next time you need a answer and I don't reply in time to a github issue.

**Comment by nickvergessen** [comment]
Well activity app is unaffected, since it always displayes the current preview.

**Comment by SergioBertolinSG** [comment]
Please note, not only the thumbnail but the big previewed picture.

**Comment by SergioBertolinSG** [comment]
Fixed in last master.
