### ISSUE TITLE
Pull Internal Username earlier in the LDAP / AD Wizard

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#10583]
By default, when you connect to the LDAP / AD Wizard, the UUID is pulled. The problem here is that rarely do people want to see their UUID in the username list in ownCloud...
![skitch](https://cloud.githubusercontent.com/assets/1818977/4002183/35672aec-296a-11e4-825f-35c367415ab8.png)

Can we pull the "Internal Username Attribute" earlier in the setup wizard? That way fewer users will accidentally create a UUID based setup, look at the user management page, and see UUIDs and be lost on how to fix it.

**Comment by MorrisJobke** [comment]
@karlitschek @MTRichards @blizzz postpone to 8.1?

**Comment by butonic** [comment]
Closing because UUID is the only unique attribute. With e.g., samaccountname, userprincipalname, or email  admins WILL run into problems. Even to the best of the of admins we saw ldap admins decide changing the samaccountname from a generated x12345 string to first name.lastname. UUID is the only sane attribute. If admins want a readable string in the data folder they can use the home folder naming rule attribute but be aware that it might create collisions.
