### ISSUE TITLE
Debian config file path organisation

### ISSUE THREAD

**Issue by time2ride** [owncloud/core#10751]
Hi,
I suggest to change some paths in the Debian package:
* /var/www/owncloud folder should be changed to /usr/share/owncloud as suggested in #6388
/etc/owncloud/apache.conf (see below):
```
Alias /owncloud /usr/share/owncloud
<Directory /usr/share/owncloud/>
  AllowOverride All
</Directory>
```
* Default data dir should be set to something like /srv/owncloud
```
root@debian-wheezy:/etc/owncloud# l /srv/
total 0
drwxrwx--- 1 www-data www-data 130 Aug 30 01:00 owncloud
```
* All config files should be placed under /etc/owncloud/ and linked to from the according places (e.g. phpmyadmin organizes its configfiles this way):
```
root@debian-wheezy:/etc/owncloud# l
total 24
-rw-r--r-- 1 root     root       306 Aug 30 00:34 apache.conf
-rw-r----- 1 www-data www-data   451 Aug 30 00:03 config.php
-rw-r--r-- 1 www-data www-data 14499 Aug 26 12:18 config.sample.php
root@debian-wheezy:/etc/owncloud# l /etc/apache2/conf.d/
total 28
...
lrwxrwxrwx 1 root root   26 Aug 30 01:07 owncloud.conf -> ../../owncloud/apache.conf
lrwxrwxrwx 1 root root   28 Aug 27 17:27 phpmyadmin.conf -> ../../phpmyadmin/apache.conf
...
root@debian-wheezy:/etc/owncloud# l /usr/share/owncloud/config/
total 12
lrwxrwxrwx 1 root     root      24 Aug 30 00:55 config.php -> /etc/owncloud/config.php
lrwxrwxrwx 1 root     root      31 Aug 30 00:55 config.sample.php -> /etc/owncloud/config.sample.php
-rw-r--r-- 1 www-data www-data 221 Aug 26 12:17 .htaccess
```
This would yield a debian conform config structure and make owncloud easier to administer on those systems.
What do you think about that?

**Comment by jnweiger** [comment]
@time2ride Thanks for sharing! I will look into this for owncloud 8.

For data I am undecided. /var/lib/owncloud/data has been suggested elsewhere.

**Comment by jnweiger** [comment]
Not done for ownCloud 8. Sorry.

**Comment by jnweiger** [comment]
I've basically given up on proper filesystem hierarchy standards. Our ownCloud installation instructions clearly say to install the code in the web-server space. This applies to Tar/Zip archive installations and also to packages, to maintain consistency. 

Also, asserting proper upgrade behaviour for all our user scenarios is a real challenge, if we move the code and everything to the 'proper' location. 

the issue is well known and explored by now as an enhancement. I don't see it happen. Sorry.
