### ISSUE TITLE
Use binary files for encryption instead of base64 encoded ones

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#10831]
Currently encrypted files produce a 33% size increase, because a 6126 bytes block produces a 8192 bytes encrypted block.
Also the encrypted file is stored in an ASCII format which seems to be base64.

We should look into switching to a binary format, if possible, to hopefully reduce the size of encrypted files.

The new header that was added for AES-256 can be reused to specify a new flag that tells whether the encrypted file is in binary format or the old ascii format.

@schiesbn what do you think ?

**Comment by PVince81** [comment]
Could be implemented as a separate encryption module.

**Comment by Hunter-Github** [comment]
Raised at [IT Security StackExchange](https://security.stackexchange.com/questions/117068/why-would-an-encrypted-file-be-35-larger-than-an-unencrypted-one).

**Comment by tyzoid** [comment]
It seems odd to be imposing a premium on space where none would otherwise exist. This also has other minor effects, such as on the OwnCloud Linux Client showing the raw value during upload, then jumps up to the "correct" value of usage once the sync finishes. From the perspective of both an administrator and user, it can be annoying: the quotas that are assigned count the base-64 encoded data on disk, rather than the data the user actually wants to store.

**Comment by PVince81** [comment]
The quota as implemented in ownCloud takes care of the unencrypted file size, not the encrypted one.
But if you have FS-level quotas then those would apply on the encoded data, yes.

Is the raw upload value bug still there ?

I think this issue also applies to master key encryption.

cc @pmaier1

**Comment by tyzoid** [comment]
@PVince81 When I wrote my comment, there was no disk quota in use. The client was counting encrypted, base64 data as 'used'.

**Comment by karakayasemi** [comment]
Fixed with https://github.com/owncloud/encryption/pull/224
