### ISSUE TITLE
Detect legacy storage + datadir change

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#10897]
Context is here: https://github.com/owncloud/core/pull/7539

Whenever a setup has the following:
1) legacy storages in the format "local::$datadir/$user/"
2) the admin decides to move the data dir

Something will clearly go wrong.

Some repair routine is provided in OC 8 here https://github.com/owncloud/core/pull/7539 but that one can only work if the admin has NOT moved the data dir.

I suggest to add some code to detect whether the datadir has been changed before the update, and then show a warning or block the update.

This can be achieved as follows:
1) Save the datadir value in `oc_appconfig` or alternatively in a separate entry in `config.php`
2) Whenever an update is run, and the datadir doesn't match the entry in the database, then check whether legacy storages exist. If yes, show a warning.

The purpose is mostly to avoid breakage.

What do you think ? @karlitschek @icewind1991

**Comment by PVince81** [comment]
Since OC 7 is EOL'd soon and only accepts security fixes, this can be closed.

As soon as people update to 8.0 their database will (hopefully) be fixed and this case cannot happen any more. Closing.

**Comment by c-holtermann** [comment]
I just wanted to update and stumbled into this open knife. I went the update path from <5 and moved my data. Shares don't work correctly. Now I'm tying to clean my database with phpAdmin. Please don't leave open holes like that. I never really got a warning message about duplicate storages.

**Comment by c-holtermann** [comment]
It was not possible for me to update to 8.x before moving the data. I had to change to another server because there was no adequate php version for updating. Finally after the sixth or so attempt to move and upgrade I manually changed the rows in oc_storage from local::/x/y/z to home::z. This worked. All other attempts lead to duplicate entries, chaos and frustration. Cleaning these duplicates up without loosing shares was too complicated. So I had to return to the data from 7.x multiple times.
