### ISSUE TITLE
Error during update

### ISSUE THREAD

**Issue by kaffeeringe** [owncloud/core#10913]
I manually updated from 6.0.0 to 7.0.2 and got this error message:

An exception occurred while executing 'DROP TABLE `oc_files_versions`': SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'oc_files_versions'

**Comment by DeepDiver1975** [comment]
> The update code should probably try and detect whether the table exists before trying to remove it.

yes - seems to be the case that we missed this part

**Comment by PVince81** [comment]
I cannot verify/test this because: the fix is in OC 8 but the issue appears when upgrading from OC 6 to OC 7 with missing trashbin/versions where the code is only triggered with a version check.

If I delete the version check when upgrading from OC 7 to OC 8 with missing `trashsize` table in the code it will call `dropTable` but doesn't fail. So the fix works as expected in case future apps are trying to drop non-existing tables.

I don't think this issue is critical enough to justify a backport (the code changes https://github.com/owncloud/core/pull/12695 are non-trivial) CC @karlitschek 

Closing.
