### ISSUE TITLE
[stable7] Link incorrectly escaped in error message

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11464]
![escapederrormessage](https://cloud.githubusercontent.com/assets/277525/4544906/da80e9d2-4e36-11e4-9728-2efcf37ce2b7.png)

@LukasReschke did you happen to add too much escaping ? :wink:

**Comment by MorrisJobke** [comment]
This specific error message is nowadays handled differently:

![bildschirmfoto von 2015-08-26 09-22-52](https://cloud.githubusercontent.com/assets/245432/9487669/2d4703ea-4bd4-11e5-8f61-43ef7ad7d10f.png)

This is because it is very early in the request handling phase. 

Issue is therefore fixed. If there happens something similiar for another error message, please create a new ticket that lists the message.
