### ISSUE TITLE
Restore owncloud causes data loss

### ISSUE THREAD

**Issue by sirio81** [owncloud/core#11621]
This isn't exactly a bug, but a side effect of restoring a backup of owncloud.

I made a test:
- created a new user, configured the client and synced its files
- poweroff owncloud, lvm snap
- restart owncloud, add some more files and wait them to sync
- shutdhow owncloud, roll back of the snaphot (lvmconvert --merge).
- start owncloud

The client removes the files added after the snapshot.

This is because the client has the entry of these file but server side they are missing so it "thinks" the files have been deleted.

This behaviour is not documented
http://doc.owncloud.org/server/6.0/admin_manual/maintenance/restore.html

I've been testing with ownlcoud 6.0.5 but it shouldn't be different on the other versions either.

What do you think about that?

**Comment by LukasReschke** [comment]
@carlaschroder *ping*

**Comment by carlaschroder** [comment]
OK, sorry, finally had time to look at this...my reaction is "well of course restoring a previous snapshot loses everything that happened after the snapshot was made." Do people really not understand this?

**Comment by tflidd** [comment]
@carlaschroder On the server side this is clear for everyone. But the client could be expected to recognize that it holds a newer version of a file than on the server. Or that it holds files that are not yet on the server.
Imagine a server is set back to the backup before the week-end. Someone was working on some documents during the week-end. The next startup of his system (with the probably autostarting owncloud client) will just delete all work he's done over the week-end!
So the admin must be aware of this situation and - in case of restoring a backup - he can warn all users that they should start their system without network connection and backup their data first.

**Comment by MorrisJobke** [comment]
> @carlaschroder On the server side this is clear for everyone. But the client could be expected to recognize that it holds a newer version of a file than on the server. Or that it holds files that are not yet on the server.

This should be recognized. cc @guruz Or am I wrong?

**Comment by MorrisJobke** [comment]
@tflidd @sirio81 Or did you only restore the data dir and kept the database as before? Then there is the old data dir and the new database which cause trouble and is unsupported.

Please reopen this if it was a full backup restore and the clients fail to handle this properly.

**Comment by awnz** [comment]
> @carlaschroder: my reaction is "well of course restoring a previous snapshot loses everything that happened after the snapshot was made." Do people really not understand this?

Having just encountered this situation in real life (fat-fingers partially deleted the owncloud folder, needed to go to 18 hour old backup for folder and DB) I was really hoping that this wouldn't be the case.

I think the restore documentation (at *1) should give a warning not to restart ownCloud servers after a restore until users have been contacted and instructed to manually make a safe copy anything they've made/changed in the time since the backup was taken.

Even better would be a feature to set a "restored-from" value on the server side, have the server pass that to sync clients, at which point the sync clients will re-upload rather then download or delete any file with a modification time newer than the restore time.

*1: https://doc.owncloud.org/server/latest/admin_manual/maintenance/restore.html

**Comment by PVince81** [comment]
There should already be a "restored-from" value on the server side since 9.1. @guruz do you remember the ticket/PR number ?

**Comment by awnz** [comment]
Oh - cool :) ... I wish I'd upgraded before my disaster! :P

Do you think it's possible to upgrade then set that value? What client version is that supported from? (I presume it would need support at both ends)
