### ISSUE TITLE
[Ask Feature] A sharing setting

### ISSUE THREAD

**Issue by adan89lion** [owncloud/core#11648]
If there's a setting about download limits of shared files will be great.

Example:

When I set download limit to 18, after the 18th person download the file will expired sharing.
This feature seems great for posting stuff on forum by limiting peoples to download.

This idea was came from Pydio's sharing settings.

**Comment by jancborchardt** [comment]
Sounds like a pretty arbitrary metric. How would that be useful? Since when you post it, the first 18 to download it would be completely random. Would you count opening the file as well, since people can take screenshots? Would we need to identify individual users or just every time the URL is opened?

Sorry – but there’s just too many questions for such a small edge-case feature to be cleared up. That would be way too confusing. Closing until there’s a real-world usecase. :)
