### ISSUE TITLE
Sharing a file does set while to rw for short time

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#11707]
When sharing a file via the sharing button to other users the file is automatically shared with "can edit" permissions. - While permissions can be changed then in the next window within a short timeframe the receiving user has permissions to edit the shared file which is an unexpected behaviour.

We should make sure that always the least permissive permissions are set per default and/or make this editable within the same step.

@jancborchardt Your opinion?

\cc @guruz @ogoffart

**Comment by MorrisJobke** [comment]
@LukasReschke @jancborchardt @schiesbn @PVince81 So the default permission should be read-only?

@karlitschek Is this still topic of 8.0? Otherwise move this to the 8.1 milestone and I will have a look later on this.

**Comment by LukasReschke** [comment]
Yes. 

I'd vouch for 8.1. Nothing did explode in the past due to that and as we're already in the beta let's keep it that way.

**Comment by jancborchardt** [comment]
I’d vouch for 8.1 if anything as well. 

> So the default permission should be read-only?

I’m really not too fond about that. We didn’t have real problems in practice before because of this. And I think we would get more complaints about people not noticing sharing is read-only by default and others can’t edit it.

**Comment by LukasReschke** [comment]
Well - fact is that we do it differently than anybody else and this really a problem in serious environments. You simply don't want to have it that way.

So we either set it to read-only or we come up with a proper sharing popup dialog (as does Dropbox or Google Drive) but the current solution is a mess at best.

**Comment by LukasReschke** [comment]
The current approach can be kinda compared to creating a user and give it admin rights per default and then have a small timeframe where the user has administrative privileges.

A best practise is to obey the least-privilege principle: Give the user only what he needs at start and if he needs more give him more permissions. 

Honestly, if you want to have a file editable we have the checkbox right there in the sharing dropdown and doing it this way would not result in potentially unintentional behaviour.

**Comment by karlitschek** [comment]
Hmm. I see pros and cons for both options. I would leave it as it is for now because we are in feature freeze and no one complained about the current behavior -> 8.1

**Comment by jancborchardt** [comment]
Yeah, good call for now.

@DeepDiver1975 we should sit together on the sharing dialog when coworking next.

**Comment by MorrisJobke** [comment]
Will be addressed together with the new sharing dialog: #3224

**Comment by PVince81** [comment]
I don't think so. The new sharing dialog will be in the sidebar but still won't have a "save" button or anything that would delay the saving of the RW option.

**Comment by rullzer** [comment]
So what do we want to do here. I agree actually that allowing destructive behaviour by default is bad! Maybe when switching to the sidebar we can do this at the same time?

**Comment by cmonteroluque** [comment]
@DeepDiver1975 @PVince81 we need a decision

**Comment by PVince81** [comment]
Something that comes in mind is having a green check mark symbol like :white_check_mark: when the changes are saved.
Whenever the user changes something in the share dialog, the symbol disappears or becomes grey.
If the user stops making changes within the next 2-3 seconds, the symbol becomes a spinner and saves the changes.
This proposed behavior would be similar to the external storage admin page.

A similar paradigm could be used in other places where auto-save is used.

What do you think ?

**Comment by rullzer** [comment]
@PVince81 that does not solve the problem. Basically it comes down to what we want as defaults. I still vote for read only.

**Comment by rullzer** [comment]
@PVince81 I think while what you describe sounds nice. It won't make things easier. Instant changes seems best in the sharing dialog. Since if a user keeps making changes and they are only saved after a period of inactivity then we must make sure that all those changes can happen. Probabaly it adds more problems then it solves...

**Comment by PVince81** [comment]
Note that the "make changes after a delay" is already implemented in other places like the user management page where user deletion happens after a delay or when closing the window, leaving time for the user to undo changes. A similar mechanism could be used to make sure the last dirty data is getting saved.

**Comment by rullzer** [comment]
Agreed... but it won't be possible to do it everywhere in the sidebar... for example. if you want to share with link. Then it won't be instant but you have to wait for the timeout. before you can set the expiration date etc.

And to only have it on some but not all options seems weird.

But lets get back to the Read Only vs Read-Write topic ;)

**Comment by MorrisJobke** [comment]
I also think that making read-only the default and read-write an opt-in is the way to go. cc @owncloud/designers

**Comment by PVince81** [comment]
> Then it won't be instant but you have to wait for the timeout. before you can set the expiration date etc.

@rullzer true.

Right, for link shares read-only is also the default.

**Comment by jancborchardt** [comment]
Could we have a background timeout of like 7 seconds where the share is already shared, but de facto read-only? When nothing is done after that timeout, the setting which is set at that point (default read-write) will be set.

Do you understand what I mean? So basically the UX doesn’t change, it’s just that if you share with someone and then directly uncheck the »can edit« checkbox, it really never is read-write, because of the 7 second grace period. (Similar to undo)

**Comment by MorrisJobke** [comment]
> Do you understand what I mean? So basically the UX doesn’t change, it’s just that if you share with someone and then directly uncheck the »can edit« checkbox, it really never is read-write, because of the 7 second grace period. (Similar to undo)

That's some really weird behaviour o.O Why not switch to read-only?

**Comment by jancborchardt** [comment]
Because that’s a full-on switch in default functionality we had since forever. Also, read-write is the normal default for collaboration.

**Comment by MorrisJobke** [comment]
> Also, read-write is the normal default for collaboration.

But not for sharing something with you. I often just want to send around images or documents the other person shouldn't change ;)

**Comment by jancborchardt** [comment]
Of course, but that’s possible with a simple click.

Please be aware that we are talking about doing a major UX change (changing a default) simply because of an issue not really visible to people. That’s not how we usually do things.

**Comment by MorrisJobke** [comment]
> Of course, but that’s possible with a simple click.

Yep. I just say, that it would be better to actively need to enable that another person can delete your data instead of have this the default. I think that the current way is a bad way of handling this. Even if it was the case for all the previous versions (which isn't really an argument). Keeping broken stuff, because people are used to it doesn't sound good :(

**Comment by jancborchardt** [comment]
We did it that way because that’s the default in Dropbox and Google Drive as well.

Changing the default just because of a technical issue that would take some time to fix is also not really an argument.

**Comment by MorrisJobke** [comment]
> Changing the default just because of a technical issue that would take some time to fix is also not really an argument.

It's not really a technical problem, but a problem what you expect as a user. I for myself don't expect that it will share by default with all permissions. I always want to increase the level of permissions and don't want to decrease a default that grants everything.

**Comment by MorrisJobke** [comment]
And introducing more weird behaviour (after some seconds it will get write access) is even more counter-intuitive. And even if google drive and dropbox does it like that ... I don't care about them. I care about our product.

**Comment by schiesbn** [comment]
I thought we already agreed some weeks ago that min permissions by default is the way to go. Sad thing is that we defer it back than because of the feature freeze and now we are again in feature freeze. ;)

I would really avoid all this magic with waiting some seconds, etc. People really don't understand it and what do we do if something happens in between, network error, admin decides to enable maintenance mode and perform a update, etc... that's all way to complicated both from a user perspective and from a implementation point of view.

I would suggest to go to read-only by default for oC9.0 with sharing 2.0, with sharing 2.0 some stuff will change anyhow (e.g. how re-share works). If we really think that people need different default we could also think about a setting for the default share permission as config.php switch for people who really need it. But at the end I doubt that this will be necessary.

**Comment by LukasReschke** [comment]
Minimal permissions are the way to go. We're an enterprise grade solution and there is no way that we can ship insecure defaults.

If a CFO shares some sensitive data with some users there is now the risk:
1. That the user is not aware that users may edit it
2. That it is editable while the CFO has not manually changed it

This is a totally unacceptable behaviour from a security point of view.

> We did it that way because that’s the default in Dropbox and Google Drive as well.

That's not entirely true. They have both realized that insecure defaults are only harming their users.

They both offer to change the permissions _BEFORE_ the share is created and  _PROMINENTLY_ display a checkbox:

![2015-09-25_11-17-12_01](https://cloud.githubusercontent.com/assets/878997/10097103/fc9fbfe2-6376-11e5-8052-a58cec9f3811.png)
![2015-09-25_11-18-11](https://cloud.githubusercontent.com/assets/878997/10097111/1f465272-6377-11e5-821b-b53b0c18ca66.png)

No other solution is doing it our way. It is just an entirely wrong, insecure and unexpected behaviour.

> Please be aware that we are talking about doing a major UX change (changing a default) simply because of an issue not really visible to people. That’s not how we usually do things.

I honestly could not care less. Everybody else is doing it different and we need to change this. This is a security risk and we need to fix it.

> I would suggest to go to read-only by default for oC9.0 with sharing 2.0.
:+1:

cc @cmonteroluque

**Comment by LukasReschke** [comment]
… and now I'm out to my weekend. Until tuesday :speak_no_evil: :see_no_evil: :hear_no_evil:

**Comment by cmonteroluque** [comment]
@LukasReschke since you will be reading this... :). I happen to agree 100% with your position. I am not sure I would call it a security hole (after all, we're making it obvious) but it is poor behavior and I concur that the fact that other solutions do it (or may have done it before) is not enough to justify it.

Of course, the pity is that we're now in feature-freeze for 8.2 (sadder if you look at the history of this issue). So, I make a proposal for consideration:
1. keep it as it is for 8.2 (not a regression)
2. make this mandatory for 9.0 
3. (and possibly include a pop up or another mechanism to ask for the proper permissions)

@MTRichards @karlitschek This isn't exactly in the priority list today but I think it's been long enough in coming and I think there's a reasonable push for a better solution

**Comment by MTRichards** [comment]
Sure, but I have other items of similar size that are more important from my perspective...let's discuss. I'll add this so it is not lost.

**Comment by jancborchardt** [comment]
Well, ok. Just saying that my proposed solution above with the timeout also works …
Interaction which involves a save button is quite cumbersome. @LukasReschke your call but we need to talk about this for 9.0 if easy sharing really is a focus of our product.

> And introducing more weird behaviour (after some seconds it will get write access) is even more counter-intuitive.

@MorrisJobke Did you even read it? It’s completely behind the scenes.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Did you even read it? It’s completely behind the scenes.

Yep, I did. But hiding this behaviour doesn't make it easier or better. In our case the sharing is still an opt-out and not an opt-in. You know how often you read the stuff when you tick a checkbox ;) - "TOS;DR"

**Comment by rullzer** [comment]
so... 9.0 it is?

**Comment by rullzer** [comment]
Ok, so what are the permissions we actually want (since I'm touching the OCS Share API anyway)?

No destructive permissions is what we agreed on. But should resharing be enabled by default? @MTRichards @LukasReschke

**Comment by LukasReschke** [comment]
Good question. Technically not that evil since you could anyways reshare it by downloading the file and creating a new one.

@MTRichards Your call.

**Comment by MTRichards** [comment]
I would have resharing off by default, then possible to check the box to reshare.

**Comment by jancborchardt** [comment]
I’d say let’s not overextend the limitations too much. We are currently at editing and resharing by default. Making it view-only and restricting sharing by default goes against what ownCloud is for: collaboration and sharing.

This is not only a security question and not just something where we can lightly switch defaults. It’s a significant change in core UX (if we do so) and we need to properly think about how to make it as seamless as possible while having it secure.

**Comment by AnrDaemon** [comment]
Speaking of initial share permissions, there can't be "one size fits all".
The initial set of permissions is share object- and purpose-specific.

If my workflow mandates read-only shared calendar events and read-write project documentation, nothing stops another administrator from having requirements of a diametral opposite.

To make my post explicit: The initial set of sharing permissions must be configurable per shared object type.
Else noone will be using application that require constant fiddling, instead of just working.

**Comment by rullzer** [comment]
After some more thinking I think I also kind of agree with @jancborchardt. People share data because they want to share it. And sharing is non destructive behaviour so that is all fine. Also with Sharing 2.0  the owner can see everybody that has access. So that is fine then.

So can we agree that default share permissions should be READ + SHARE?

**Comment by rullzer** [comment]
@AnrDaemon well we would have to think if that is something we want. Because that explodes quickly (users wanting READ+WRITE permissions on one dir by default and READ only on others etc). I makes sense to have sane defaults here.

People are also using solutions from other providers that also have limited permissions by default.

**Comment by AnrDaemon** [comment]
"One dir" is not "one object type". I can imagine people confusing cloud storage for their average file system, but it is not the one.
It has a purpose and limitations.
Something you describe could be a good idea for external scripting. But not a default behavior.

**Comment by butonic** [comment]
Well what are "sane" defaults? Secure defaults? Usable defaults? I am with @LukasReschke here. Users might forget limiting permissions to readonly, then their data migt get modified, deleted, reshared. Data loss is not an option and a disaster for any end user ... or customer for that matter.

**Comment by AnrDaemon** [comment]
> Well what are "sane" defaults?

Sane defaults are the defaults that administrator set for this object type.

Administrator. Not developer.

What users may or may not forget, is not yours to call. You can't hold everyone's hand in the world. There's roughly 3 billion internet users in the world, and you only have two hands.

If you are going to intentionally create administration headache, you are limiting the potential of your product, and encouraging its users to look for alternatives.

**Comment by MTRichards** [comment]
Most important is to cover the most likely scenario with the defaults. 

Resharing should be off by default. That should be an act of commission - you want someone to get a copy of a copy, therefore you turn on resharing. Otherwise, it should be off.

Editing should be on, that is why you share with someone more often than not. Delete should be off inside edit, so we don't have people losing data by accident.

That covers the most likely path for most users, and then the others can configure at the time of share.

**Comment by AnrDaemon** [comment]
@MTRichards , I think we're leaning to discuss apples and oranges.
Nobody question the necessity of the installation defaults.
What I'm saying is that the installation defaults shouldn't have a final say in each instance of the application.
The administrator of an instance must be able to set defaults of an object to suit the workflow of their organization, which will save their users time and effort and require less administrative intervention over the lifetime of an application. See my example above.

**Comment by MTRichards** [comment]
Sure, I understand - I needed to clarify the defaults, which I did.

As for the issue of defaults, and being able to change them in a config switch or something, this is tricky. Every time we add a config file option, we increase the test matrix, complicate the code, and make it harder to maintain. We also increase confusion, the number of support cases, and make it harder for an admin to easily get what they want out of ownCloud. Eventually we will get bogged down and unusable. We have a TON of these sorts of cases out there, just look at the sample config file - it is daunting and awesome at the same time. 

So the question becomes balance - to balance the needs of most against the needs of few and come up with the right answer. In this situation, if a read only folder is needed more than a read/write folder - I am just not yet convinced that there are enough use cases or need to warrant a switch. Are there use cases? You bet. Are there enough to warrant the addition of these switches? Not convinced.

**Comment by karlitschek** [comment]
@AnrDaemon There might be a way for you to override this default with a custom theme or app. But unfortunately we have to limit the number of configuration options as @MTRichards said. In a lot of cases we have to look at what 95% or all users want and what 95% or all other sync and share solutions out there do. And this is RW. We really understand the desire and need for an non standard behavior. 
But this can and should be done by a patch, or theme or app. ownCloud is open source after all which means it is possible. But this doesn't man that we can do config options for every non standard use-case because this would kill our software in the long run.
Thanks a lot for your understanding.

**Comment by rullzer** [comment]
So it seems we are still devided what the default behaviour has to be. As I think we have seen all possible combinations of. READ/WRITE/SHARE come along here. And for each combination there are very valid use cases.

If we would eventually move to 'simpler' permissions (https://github.com/owncloud/core/issues/12970) so only can edit and can share. Maybe the approach from @LukasReschke in https://github.com/owncloud/core/issues/11707#issuecomment-60094752 is best.

So next to the input field for the sharee you have a dropdown menu where you can select the behaviour your want.

**Comment by karlitschek** [comment]
I actually think that the current behavior is fine because it is the most common behavior and it also the same that all our competitors do. Which means that this is also what users expect.
Let's close this for now.

**Comment by LukasReschke** [comment]
> I actually think that the current behavior is fine because it is the most common behavior and it also the same that all our competitors do.

It's not really, see https://github.com/owncloud/core/issues/11707#issuecomment-143167865

**Comment by LukasReschke** [comment]
All others: Set to "edit" per default _BUT_ allow changing this _BEFORE_ sharing. Thus not setting potential insecure defaults.
We: Set to "edit" per default and do not allow changing this until the files have already been shared.

**Comment by butonic** [comment]
I see two possible solutions:
1. Add a confirmation button. Clicking it creates the share. Might need UI rework to make it look appealing and less confusing.
2. Change defaults to readonly. Adding a share then does not need a confirmation action. Creating a writable share needs an extra click on the corresponding checkbox.

Hope this clarifies that it is not the defaults that are wrong, but the moment we create the share.

**Comment by ogoffart** [comment]
The security issue is this one:  imagine a funny student who configured his client to automatically delete all new share. The proffessor want to share a folder containing the assignement data and instruction with all the students (the students group)  When he does so, he better be quick to remove the write permission before it's too late and all the data is gone.

**Comment by MorrisJobke** [comment]
> The security issue is this one: imagine a funny student who configured his client to automatically delete all new share. The proffessor want to share a folder containing the assignement data and instruction with all the students (the students group) When he does so, he better be quick to remove the write permission before it's too late and all the data is gone.

:see_no_evil: That's a weird scenario.

**Comment by AnrDaemon** [comment]
Weird, may be.
But I've seen people doing that "because it is too much spam".

**Comment by jancborchardt** [comment]
> configured his client to automatically delete all new share.

Well – this should simply result in that person unsharing the share from themselves, right? Not in deleting all the files.

**Comment by guruz** [comment]
> Well – this should simply result in that person unsharing the share from themselves, right? Not in deleting all the files.

Not if the student is fast enough with deleting before the professor sets R-only.

I still think it is a security issue.

**Comment by LukasReschke** [comment]
> I still think it is a security issue.

:+1:

**Comment by PVince81** [comment]
It is now possible to set default sharing permissions since OC 10.0.3, closing.
