### ISSUE TITLE
In public view, Download button does not change upon navigation 

### ISSUE THREAD

**Issue by osamak** [owncloud/core#11769]
In ownCloud 7.0.2's public view (i.e. link-shared directories), the Download button at the top right corner does not change upon navigation.  So if the parent directory is 10GBs, the user will always download that rather than the specific directory they are currently in.

**Comment by oparoz** [comment]
It's a regression.
The endpoints, `public.php` or `s/token/download`, can take file and path arguments and send a zip of the current path only, but the button is now broken.

**Comment by DeepDiver1975** [comment]
> It's a regression.
> The endpoints, public.php or s/token/download, can take file and path arguments and send a zip of the current path only, but the button is now broken.

scheduling for 8.0 because of this - THX @oparoz for testing

**Comment by oparoz** [comment]
This is my fix proposal, but I'm having second thoughts.
https://github.com/owncloud/core/pull/13332

Maybe that button should not even exist in filelist view since it's really easy from anywhere, as mentioned by @PVince81, to tick the "select all" button and to have an archive of everything we see.

It makes sense to have it in the gallery (and it already selects the current album in the new master) or when looking at individual files.
Thoughts @owncloud/designers ?

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by osamak** [comment]
I think removing it is a wise choice. The interface is not expected to have buttons that just duplicate an existing function.

**Comment by jancborchardt** [comment]
No, sorry – we didn’t have the button before and people were confused as to how to download everything.
