### ISSUE TITLE
Migrate config.php to proper config format or move config to DB

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#11843]
Currently the ownCloud config is stored within `config/config.php` within a PHP array, the files has to be r/w.

While this is a pragmatic solution there are several problems with that:
1. The file has to be writable
2. The file is in an executable format

From a security PoV it is desirable to make the whole ownCloud folder read-only, if an attacker gained read-only access to the FS he cannot escalate his privileges further. (which might be handy in combination with the server-side encryption app)

Furthermore, using PHP to store the config means that an attacker can execute any arbitrary PHP code as soon as he gained full FS access of the ownCloud folder.

Therefore I'd recommend one of the following approaches:
1. Migrate config.php to YAML (or JSON or whatever)
   - Pro: File is not executable
   - Pro: Would still be easy to modify with a terminal
   - Contra: File would still be writeable and allow other attack vectors
   - Contra: Improper protection allows access to config
2. Migrate config values to DB and only store DB credentials within config.php
   - Pro: Attacker cannot read any config data in case the DB is not reachable from outside
   - Pro: Makes it possible to make config.php read-only
   - Contra: Not that easy to modify configuration values with a terminal.
     - Can be fixed with using console commands as pointed out below.

**Comment by butonic** [comment]
From a deployment perspective having a minimal config is desirable. Optimally, only the db config should be necessary. The rest should be stored in the db. This makes administration of several web servers a lot easier, because only the db connection needs to be specified. Then the file would contain maybe five settings related to the database. We could go so far as to only store the DSN (Data Source Name) in a config file: http://doctrine.readthedocs.org/en/latest/en/manual/introduction-to-connections.html Something like `mysql://user@unix(/path/to/socket)/pear` or `pgsql://user:pass@tcp(localhost:5555)/pear`.

**Comment by karlitschek** [comment]
Hmmm. In my opinion everything that is "system configuration" should be in the config file. this makes automatic deployment and setup, remote configuration, config diff and other things a lot easier. This is best practices for most unix services for a long time.
Everything that is user config or data should go into the database.
The config file (over-)write problem are a bug in our code. This has to be fixed by us.
The config file format is a tricky question. the benefit of a .php file is that it will never be readable via the browser.
Maybe we switch to a different config file format but keep it a .php file with a "<?php exit; " in the first line.

**Comment by PVince81** [comment]
The alternative would be to only have read-only values in the config.php and move all read-write settings to the database. This means that everything that can be configured in the admin page (ex: mail settings) must go to the database. This would solve the overwrite issue.

Or if we still want to go the "everything in the DB except the DB settings" route, then we can provide a CLI tool `./occ deploy-config configfilewithupdatedsettings` that will import/update the settings into the database.
We wanted to move the external storage settings from mount.json into the DB too at some point, and had the same discussion with @MTRichards about providing a way to deploy from the CLI.

I'm not sure it is worth to spend an additional man-month to try and fight against (the absence of) windows proper file locking... that man-month could be spent to implement the suggestion above.

**Comment by PVince81** [comment]
and then if you really want the config settings updates to auto-deploy to the DB, you could have process that observes that "configfilewithupdatesettings" whenever it has changed and use that CLI tool to auto-import them, which gives you almost the same admin experience you had before.

**Comment by DeepDiver1975** [comment]
For most of the configuration setting they are fine to stay in the config file as we have it today as they are basic system setup and will not change during regular operations.

With a few exception they are already kind of read-only.

Issues start as soon as we write to the config file - e.g. because of the admin changes some setting in the admin page.
This is a critical circumstance in a distributed environment because the write operation will be executed only on ONE web server on the cluster. Other config files will remain unchanged.

On the other hand in a single web server setup (which is the most common setup in the the non-enterprise world) changing the config via the web is almost required because accessing the files on the web server might not be that easy (thinking about web hosters where one gets ftp access only).

This is a circumstance we need to have an answer to. 

## Proposal:
1. Introduce a deployment mode switch (deployment.mode = {single, cluster})
2. In case the mode is 'single' we allow changing the configuration via the web browser
3. In case the mode is 'cluster' the config file is read only and changes have to be done to the files directly

Furthermore we closely review any write operations to the system config and reevaluate if this is the right approach.

**Comment by cmonteroluque** [comment]
@MTRichards @karlitschek I'd love to catch up on this for a later release (either way, explicitly or implicitly make a decision)

**Comment by MTRichards** [comment]
Definitely worthy of a discussion, there are (as usual) preferences for people based on their use case and deployment scenario...and preferred deployment tools.

**Comment by karlitschek** [comment]
Yes. A lot of scenarios and cases to consider. Happy to discuss.

**Comment by jerrac** [comment]
I'd love to see a read-only configuration file that I can template with a config management tool like Ansible. 

I would say that some of the stuff in the config file should only be in the config file, and some should only be in the database.

Like the data dir path would only be in the file, while the mail settings would be in the db.

Installs would have the user make the file rw, then ro after the install was complete.

**Comment by jnweiger** [comment]
With overwrite.cli.url we need a writable .htaccess too.  9.0.1 offers shortend URLs by means of adding a rewrite rule to .htaccess like this

```
ErrorDocument 403 /owncloud/core/templates/403.php
ErrorDocument 404 /owncloud/core/templates/404.php
<IfModule mod_rewrite.c>
  RewriteRule . index.php [PT,E=PATH_INFO:$1]
  RewriteBase /owncloud
  <IfModule mod_env.c>
    SetEnv front_controller_active true
    <IfModule mod_dir.c>
      DirectorySlash off
    </IfModule>
  </IfModule>
</IfModule>
```

This feature needs a review for improved hardening.

**Comment by PVince81** [comment]
@butonic @DeepDiver1975 reopen the discussion about having a read-only config.php and move all non-database options to the database ?

**Comment by DeepDiver1975** [comment]
> @butonic @DeepDiver1975 reopen the discussion about having a read-only config.php and move all non-database options to the database ?

absolutly :heavy_plus_sign: :100:

**Comment by butonic** [comment]
➕  💯 for readonly config

cc @cdamken @felixboehm @pako81 @michaelstingl @dercorn @Kawohl @CaptionF @RealRancor @tflidd

**Comment by butonic** [comment]
cc @pmaier1

**Comment by PVince81** [comment]
- [ ] decide what format to use for config (JSON, YAML, ...)
- [ ] find out what settings are currently writable by OC and must be moved to the database
    - [ ] mail settings
    - [ ] trusted domains (when accessing from another domain, a popup suggests this)
    - [ ] ...
- [ ] move them to the database from the code's perspective
- [ ] implement migration/repair step for moving the config to the database
- [ ] adjust release scripts / makefiles ?

**Comment by butonic** [comment]
9.2?

**Comment by PVince81** [comment]
even if the whole thing isn't complete by 9.2, we can still start working on first migrating the read-write settings.

**Comment by ppaysant** [comment]
Hi,
config.php is an easy way to store config at install time. You get  the app source files, put them in [owncloud]/apps/, copy/paste the conf proposed in the readme inside the config.php, adapt it quickly to your context, then reload the UI in your browser. 

This "copy/paste/adapt" thing is the point.

If the conf must be stored inside the DB, won't it be more difficult for the admin, to set the config options for his apps ? 
For instance, if the app must have in conf a multi dimensionnal array of contact emails, that seems easier to create that array in a php file than in a db field.  (Look at https://github.com/CNRS-DSI-Dev/user_files_migrate configuration section of README for an example of a conf I'm speaking of).

A JSON file or a YAML file could be an alternative to the php one, but a **file** seems very usefull IMHO.

**Comment by felixboehm** [comment]
A file needs to be transferred to every webserver in a scaleout, while the db is just there.
A file config should only contain informations needed on install, then being readonly, write other configs to DB.

**Comment by PVince81** [comment]
@ppaysant there is a command `occ config:*` to modify database settings. But it might not work with multi-dimensional array. Maybe such arrays need to be converted to a flat list instead.

**Comment by PVince81** [comment]
@ppaysant to give more context, the reason for this idea is because currently ownCloud also updates config.php which requires this file to be writable. The idea is to have at least all read-write settings in the database and the read-only ones **could** stay in config.php if needed.

**Comment by nickvergessen** [comment]
> But it might not work with multi-dimensional array

This was fixed for 10

**Comment by PVince81** [comment]
backlog for now, need to schedule time for this

**Comment by felixheidecke** [comment]
Classic case of _too long didn't read_ … 😝  I vote for JSON because **JavaScript!!**
