### ISSUE TITLE
Make undo deletion work again

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#119]
**Short: We need »undo delete« for files again.**

---

You have an ownCloud server and it syncs to your desktop.

Now when you delete a file via the web interface, it doesn’t really get deleted, because you get the opportunity to undo that (like Gmail, [better than a modal asking you for confirmation, which no one reads and just confirms](http://www.alistapart.com/articles/neveruseawarning)).

**The problem here is that you expect it to be deleted, and thus also removed from your local synced folder. This doesn’t happen immediately though because the file is not removed in the backend.**

@MTRichards and I discussed a solution for this: When you delete a file in the web interface, the deletion should take place after the 7 seconds undo time, or after performing the next navigation action (whatever comes first). The file should be visibly (but fake) removed from the list instantly, and instantly reappear on undo.

**Comment by MorrisJobke** [comment]
As this is just a UX enhancement (shortcut for going to trashbin, search the file just deleted and restore it) I will move this to 8.1

**Comment by jancborchardt** [comment]
Ok – I hope this makes it into 8.1 then finally. Undo is not »just a UX enhancement« but a very basic form of error prevention and a forgiving system.

**Comment by MorrisJobke** [comment]
@jancborchardt Yes, but fully out of scope of a feature freeze period ;)

**Comment by brantje** [comment]
Would a setTimeout do the trick? Like ```setTimeou( deletenFn, 7000)```

**Comment by MorrisJobke** [comment]
@brantje Keep in mind, that someone is closing the tab/browsing to another app ;)

**Comment by brantje** [comment]
On close tab, delete file?

**Comment by PVince81** [comment]
There is already similar code in the user management page, you might want to have a look.
Basically: close tab or timeout of 7s would both trigger the deletion.

**Comment by brantje** [comment]
I might look at this, this weekend, but do not pin the issue on me, yet ;).

**Comment by DeepDiver1975** [comment]
@Julian1998 shown some interest in fixing this ..... let's

**Comment by jancborchardt** [comment]
@DeepDiver1975 would indeed be great if someone under your »mentorship« can do it. ;)

**Comment by DeepDiver1975** [comment]
@jancborchardt let's see what we can do :wink:

**Comment by Shamim-Capgemini** [comment]
Guys,

test a  real world scenario for large scale users. 

Create folder with 22G of data. Share it with a dozen people. 

Then try the delete.

As long as you can:
1. avoid accidental deletes
2. retain sharing on "undo"

We're good. Until then, I'll stick with what I have. Someone mentioned a "OK" "Cancel" think - not sure where that is at.

**Comment by nickvergessen** [comment]
UI proposal:
![undo-idea](https://cloud.githubusercontent.com/assets/213943/6709340/e6880398-cd78-11e4-8275-a30dd28a4918.png)

**Comment by jancborchardt** [comment]
@nickvergessen we’re already working on it. The way it will look like is:
* file immediately vanishes (ideally with a slide animation)
* yellow notification shows up top saying: »Document.txt deleted. **Undo**«
* notification stays for 7 seconds, then the actual deletion takes place

**Comment by PVince81** [comment]
- if the user deletes another file before 7 seconds (or performs another action), the actual action/deletion is performed too

**Comment by PVince81** [comment]
@DeepDiver1975 not sure if your code handles this too ? (see previous comment)

**Comment by Shamim-Capgemini** [comment]
How does a user cancel the operation?

**Comment by jancborchardt** [comment]
@Shamim-Capgemini By clicking **Undo**, of course. (What I bolded above.)

And yeah, @PVince81 what you said.

**Comment by jancborchardt** [comment]
@MTRichards can you please set this on the roadmap of 9.1? This is quite an important function to prevent people either losing data or needing to dig into the deleted files, and it just keeps getting pushed back.

**Comment by MTRichards** [comment]
Ok. We will evaluate it when we fill 9.1, but I see no reason at this time to push it back yet again.

**Comment by jancborchardt** [comment]
Hey @watermark since you worked on the [delete confirmation app](https://apps.owncloud.com/content/show.php/Delete+Confirmations?content=169968), would you like to implement this undo delete feature here so we can have the proper functionality in core? :)

**Comment by watermark** [comment]
@jancborchardt My extra curricular time is pretty full, so I don't believe I'll have time to address this.  For my uses, we have to disable the "deleted files" app anyway, so this undo functionality wouldn't be of use for any of my installs.  For "deleted files" to be useful for us, it would have to move to some type of system where deleted files from external storage didn't count towards the quota of the user that deleted it.  Additionally, last I checked, "deleted files" uses a "copy" instead of a "move", which also made it difficult to use.

**Comment by jancborchardt** [comment]
@watermark just to be clear though: This has nothing to do with the »deleted files« app. It’s simply a mechanism like »undo send« of Gmail and »undo deletion« of Google Drive etc to defer deletion for a few seconds in case it was a mistake.

It’s a more elegant solution than a popup since popups are often clicked away. Also, the popup makes every real deletion an annoying 2-click process.

**Comment by PVince81** [comment]
We're past feature freeze for 9.1 and there wasn't enough time to work on this.

@MTRichards again something to be scheduled, maybe for 9.2

CC @cmonteroluque

**Comment by MTRichards** [comment]
check, ok.

**Comment by Shamim-Capgemini** [comment]
@watermark I'm not sure why elegant is expected to be coincident with "more usable". Yes, a popup requires multiple clicks. But a popup used to make a non-desirable activity more difficult is not a bad choice per se. Should we remove seals/locks on ALL airplane doors because it makes it harder to open to go skydiivng? 

Sometimes, the ELEGANT is the WRONG choice for the AUDIENCE but NOT the AUTHOR. I feel is is not responsible for a committee to foist one scenario or another when both are clearly possible. With "delete and allow undo for a few seconds" there are many edge cases not covered.. What happens if it is not caught in time? What happens if the user looks away? We are making way too many assumptions on WHAT the BEST solution is.

I strongly advocate giving the users a choice since it works differently for different groups.

For the record, since i IMPLEMENTED the delete popup by hand in v6 and v7 for my consituents (140+ enterprise users, hundreds of Gigs of data stored), I have not had a SINGLE instance of:
1. Accidental deletes
2. No complaints on the two step delete
3. No requests to restore any files 
4. No questions on how to restore shares from deleted files

I would consider this ample evidence for a need for both. The "elegant" solution for those that have a simple scenario or users that pay attention, or a "delete popup" for those users that need that level of hand-holding.

Thank you.

**Comment by Shamim-Capgemini** [comment]
Take home message: please don't take our ability to CHOOSE if want a popup away just because it's annoying to a particular audience to have to click twice to delete.

**Comment by watermark** [comment]
@Shamim-Capgemini You're preaching to the wrong guy.  I've had a similar experience as you (100+ users), and I implemented a plugin to do the popup as well.  You should probably discuss your point of view with @jancborchardt.

**Comment by Shamim-Capgemini** [comment]
@watermark You are right. We're in the same boat.

@jancborchardt Please see my comment above.

**Comment by hodyroff** [comment]
@watermark Like the delete question app. Do you have a chance to update to 9.1 and soon to 10.0? Would be happy to recommend to customers once in a while ... Or would you just like to implement this for Core? Would happily take it as an Admin setting function. Please do a PR in that case and link to it here.

However this one original was about something else and doesn't seem to work easily with external file systems. Closing.
