### ISSUE TITLE
409 conflict - my data got deleted! What happened?

### ISSUE THREAD

**Issue by arjones85** [owncloud/core#11901]
Windows 7 owncloud client on a desktop and a laptop, Owncloud itself is hosted on a CentOS 6 VM.

Last night I started syncing all of my data from my Dropbox account to my brand new Owncloud 7 setup via the Windows client on my lapotop. While the files were syncing I renamed two top level folders because I realized I wanted to have the folder capitalized. No big deal I figured, it would finish syncing then see the rename request and process it next.

I woke up this morning to the following errors in the activity log on the laptop:

Attention, possible case sensitivity clash with C:\Users\Russell\ownCloud\photos
Attention, possible case sensitivity clash with C:\Users\Russell\ownCloud]\documents

Well crap, alright. Looking on the server showed that about 80 pictures got uploaded to my new "Photos" (with a capital P) folder, and the rest in the "photos" folder before it choked. I renamed it and the Documents folder via the Windows client on the laptop back to have all lower case letters, and ownCloud started moving files around. By the time it was done it looked like everything was fine. I then renamed it back with capital letters, the client got busy moving files around again, and as best I could tell it was fine.

Then, about 2 minutes later when things seemed to be quiet the client on my laptop popped up with "Documents\Tax Returns has been deleted".

What?!

Looking at it, it seemed like the client on my desktop was responsible. It has the following errors recorded in the activity log:

9:38 AM   Documents/Tax Returns    Deleted
9:38 AM   Documents/receipts   409 conflict
9:38 AM   Documents/Tax Returns  409 conflict
9:38 AM   Documents/Dart Service Manual   409 conflict

The laptop does not have any 409 conflict errors recorded.

What the heck happened here? Not getting a very warm and fuzzy feeling about this. Any help would be appreciated, hopefully I don't have to make sure all of my clients are all done syncing before performing additional functions on my data!

Thanks!

**Comment by frnzltje** [comment]
Hi All. 

I am using ownCloud 7.0.4 (stable) since past weekend on my CentOS VM. Before I was using ownCloud 6. I have two laptops: one Windows 8.1, one Ubuntu. I was using ownCloud client 1.5 on my Ubuntu machine. The Windows machine is using the latest client (it automatically updates).

Yesterday I noticed a conflict when I tried to copy/rename two files. Then I noticed everything had been removed by the client. Fortunately the server keeps deleted files - which you can restore through the web interface-, otherwise I would have lost some files. Today the client again decided to remove a (apparently random) selection of files & folders. After which I've upgraded the client on my Ubuntu machine to v1.7.1.
At this moment log window of both clients is empty.

Up until this week (after the upgrade) I did not have this problem, everything was running perfectly.

I'm not sure what exactly is happening, but this kindof is a thing.

**Comment by frnzltje** [comment]
So, it happened again. 

I started with a clean install of both ownCloud server AND the clients on all of my devices. Latest stable of everything. Server version was installed through the repository.
I re-uploaded my files. It started syncing again. Everything was looking okish*. 
I shut my laptop down yesterday evening. After everything was synced.
This morning I started my laptop up again. The first thing the ownCloud client decides to do is to remove a random selection of my files. What I noticed is that it did not remove all files it said it was removing. 

I kept the activity log. I'd rather not post it publicly, but feel free to contact me if you need insight into what happened. 

This is horrible.

For now I'm going to try to work with another client (webdav), because the current situation is unworkable. Or maybe downgrade the server.

*) during upload sync, it appeared as if it was not getting a full list of modified files. When you press pause and resume afterwards (when the client is idle) it will re-scan the directories. I did this several times and it kept finding files to be downloaded. One at a time. 
What also happened is: I put a bunch of files in a folder. Decided to move them to another folder. The client did not recognise this action. It downloaded the files back to the original location I put them (and uploaded the files from the new location). I tried deleting the files at the original location, however the client kept downloading the files.

**Comment by DeepDiver1975** [comment]
@arjones85 @frnzltje @fleish while the symptoms look identical - each issue seems to be different.

Please open individual issues following the https://github.com/owncloud/core/blob/master/CONTRIBUTING.md - especially the use of https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Furthermore as the client is involved we need client logs as well: http://doc.owncloud.org/desktop/1.7/troubleshooting.html

Thanks a lot for your help!

**Comment by dragotin** [comment]
@frnzltje please open a new issue with the issue template as mentioned above and try to find as many logfiles as you can: Server access_log and owncloud.log, and also the file ```.owncloudsync.log``` from the sync directory. Thanks!
