### ISSUE TITLE
Can't detect existing file

### ISSUE THREAD

**Issue by Tony-HSU** [owncloud/core#12044]
OS: Mac OS X 10.10
Server: 7.0.2
Client: 1.7.0
![2014-11-08 11 03 05](https://cloud.githubusercontent.com/assets/3013707/4963029/4f81548a-66f4-11e4-8d50-c72c8d02a2d5.png)
this file is really exist in the right path, but my owncloud client can't find it...
-rw-r--r--   1 tonypottera  staff    22K  1 21  2014 交換生3台大財金所碩三梁允綺.docx

**Comment by dragotin** [comment]
As filezilla as an alternative WebDAV client also sees this problem I doubt it is a client problem. Reopening.

**Comment by PVince81** [comment]
Isn't that the general problem that the Mac uses a slightly different encoding ? Maybe there is a piece of code (client or PHP) that mixes up / messes up with such encoding.

**Comment by PVince81** [comment]
@Tony-HSU are you still seeing this with 8.2.2 ?

Did you upload these files directly to "data" without going through ownCloud ? (this is not supported by the way). Make sure to always go through ownCloud so the file names can get internally normalized.

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/9.0/developer_manual/). :)

Thank you!
