### ISSUE TITLE
Asynchronous PUT

### ISSUE THREAD

**Issue by ogoffart** [owncloud/core#12097]
This is a feature required to have reliable upload of big files.  Sometimes, the server might take a while to assemble chunks or to put them in their final destination, and the client times out which causes the file to be downloaded again.
( https://github.com/owncloud/mirall/issues/2074 )

The solution to this problem is Asynchronous PUT via a poll URL.
This is already implemented on the client and will be part of the 1.8 release.
It is working successfully in a proprietary deployment (with a custom app on the server).

The client send with the PUT a "OC-Async:1" header, indicating it supports that feature. 
The idea is that, for the last chunk, if the server has reason to believe that assembling the chunk may take more than a few seconds, it may return "202 Try LAter" instead of the usual "201 Created". Also in the response there is a header "OC-Finish-Poll" with a path to the poll url.
Example:  `OC-Finish-Poll: /remote.php/poll?pollId=123456`

The client will then query this URL, which can write some spaces on the wire to avoid timeout, and when it is finaly finished, it can leave the JSON with "etag", and "fileid" property incase of success, or an "error" property in case of failure.  

```
{ "etag": "123456789" , "fileid": "987654321" } 
```

**Comment by risingfish** [comment]
I'm a little late to the conversation, but I just started using owncloud last month. I don't know this has ever been discussed for owncloud, but setting up a job queue using platform like beanstalkd (http://kr.github.io/beanstalkd/) would help facilitate async server requests. Uploaded files could be shuttled off to a temp storage area, and chunking/comparing/etc. could be triggered as part of of the upload, a cron job, or an ajax request.

**Comment by kubco2** [comment]
Two milestone versions was released( since source issue) for server and client, and this is still not solved :-( although the solution exists...

Big files are not only HD movies, but for example MS outlook pst files or another databases(which can be backed up by copying backup to owncloud folder), iso images, or encrypted containers.

The worst issue with this issue is that it make loop of syncing same file forever, make traffic(mobile internet users will be not happy)

**Comment by ogoffart** [comment]
I allowed myself to change the tag from Enhancement to bug, since it is really a bug from the client perspective that big files cannot be uploaded.  (This is reported a lot in the client).

Really, we need to find a solution to this problem.  This (that the client already implement) or something else.

**Comment by acornspaul** [comment]
I wholeheartedly support fixing this bug/enhancement the correct way, but until that happens I think it should be better documented that you can update the timeout setting in the owncloud.cfg to give your large files more time to complete.   

I have a 42GB file that the client times-out while it is being reconstituted from chunks and then the client would go into a loop.   Setting the timeout to 1200s instead of 300s fixed this for me.

Just add timeout=1200 to the [General] section of the owncloud.cfg in the C:\Users\[userid]\AppData\Local\ownCloud directory on Windows clients and then restart the client.

(In my opinion, this issue and the lack of an abilty to only sync file changes are the only two major deficiencies of Owncloud.)

**Comment by PVince81** [comment]
Is this still valid as per the file chunking NG concept ? (which I think is a variation of this)

**Comment by guruz** [comment]
The final chunk (or whatever finalization happens) might still take ages if there is something going on with slow storage backend or any network failure..

**Comment by ogoffart** [comment]
even in the non chunking case, it might be usefull if we want apps to process the file before accepting it  (antivirus comes in mind, or upload to external storage that takes time)

**Comment by DeepDiver1975** [comment]
@icewind1991 did some research in this area with respect to external storage as demoed some days back

**Comment by PVince81** [comment]
@DeepDiver1975 does https://github.com/owncloud/core/pull/20118 cover a bit of that ?

**Comment by PVince81** [comment]
@DeepDiver1975 obsoleted by new chunking ? Or do we still want to have a go at real async upload ?

**Comment by dragotin** [comment]
IIRC it will be much better with the new chunking but not solved in principle. Once we can breath we should think about an async solution.

**Comment by PVince81** [comment]
Note that in the case of external storage uploads, the connection might stall for a while where all bytes consumed by PHP, no response sent yet. This happens when the file is uploaded from temp storage to the exernal storage.

This kind of situation is a good example where async put would be useful for the client to check for completion.

CC @mmattel

**Comment by dragotin** [comment]
@PVince81 I couldn't agree more, thanks! Let's take the opportunity to do things right :-)

**Comment by butonic** [comment]
I don't know if any decision was made how to tackle async put, yet. I had this idea: we could allow the client to create the file without uploading any chunks, yet. It could even show in the file listing, but trying to download it will give a `423 Locked`, `416 Requested range not satisfiable` or even `503 Service Unavailable` until all chunks have arrived.

Revealing a file in the filelist would even allow the client to discover chunks that have already been uploaded so downloads can start as soon as the first chunk is available.

This approach could even lead to deduplication if we stored the file changs by their hash and stored them that way. An easy enough task for object storage based installations. A path towards that could be https://github.com/owncloud/core/pull/17638, a file based objectstorage.

Our local storage is not supposed to be accessed outside of owncloud ... so why not move ahead and store files in a way that makes our uploads easier.

@DeepDiver1975 @dragotin I'd like to discuss this with you two.

**Comment by DeepDiver1975** [comment]
Before diving into further discussions - any async operation requires a proper background processing sub system. We are aiming to get this implemented for 9.1.

Once in place we can think/discuss about the next steps in this area

**Comment by dragotin** [comment]
...and how we combine that with our new chunking, which should not be a problem, but to consider.

**Comment by PVince81** [comment]
@butonic 

> Revealing a file in the filelist 

need to take care of the case where files get overwritten, might still need part files... The advantage of part files is that it reduces the time window of locking, else the file might be locked during an hour long upload.

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/24509 for more generic async file operations (also DELETE, etc).

**Comment by kubco2** [comment]
What about this please?

**Comment by micbar** [comment]
This topic will be adressed in ownCloud infinite scale.
