### ISSUE TITLE
External Storage: Sub folder group sharing broken

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#12106]
When I share a root folder, in this case a folder called WND, a windows network drive, with the group USERS. This group has members user1, 2, 3, 4, 5 and user6

When I, as the owner of the folder, click into the windows network drive, I should then be able to click on share for a sub folder and see "shared WND with group users". Instead, I see a list of the members of the group in sub folders, and the word FALSE instead of the name of the shared folder. See screenshot.
![untitled](https://cloud.githubusercontent.com/assets/1818977/4994184/86a95dbc-6984-11e4-9f4c-a9e63d58cd2d.png)

**Comment by Xenopathic** [comment]
@schiesbn What's the status of this?

**Comment by DeepDiver1975** [comment]
@schiesbn can you please have a look if time permits - THX

**Comment by schiesbn** [comment]
Proposed a fix https://github.com/owncloud/core/pull/17225.

I could only reproduce the issue partially. I can't see a list of all users but only the group, maybe this was already fixed. But I could reproduce the issue that the path isn't resolved correctly. This is fixed with the PR above.

Note: I tested it with a sftp external storage because I don't have a WND, But the behavior should be the same, independent from the external storage.
