### ISSUE TITLE
Double log at logging failure

### ISSUE THREAD

**Issue by Aurelien-** [owncloud/core#12151]
Hello,

When a login fails, it is reported twice in the log file:

Warning	core	Login failed: 'user' (Remote IP: '1.1.1.1', X-Forwarded-For: '')	2014-11-12T23:26:28+01:00
Warning	core	Login failed: 'user' (Remote IP: '1.1.1.1', X-Forwarded-For: '')       2014-11-12T23:26:27+01:00

I'm using owncloud server 7.0.2 from debian package.

Thanks,

**Comment by MorrisJobke** [comment]
I’m closing this issue _for now_ because of inactivity.

@Aurelien-  we can always reopen it though! :) Please clarify the steps to reproduce this using the issue template.
If you need any help, please ask on our [developer mailing list](http://mailman.owncloud.org/mailman/listinfo/devel) and join our IRC channel at #owncloud-dev (freenode network).
