### ISSUE TITLE
Server got issues with new folders that being renamed immediatly

### ISSUE THREAD

**Issue by kaplandani** [owncloud/core#12267]
I am not sure yet what's the final outcome, but I'm seeing many of these errors in the server log.
Server is owncloud 7.0.3 (upgrade from 7.0.2) on a centos 7 machine
client is 1.7 beta (still beta, going soon for the stable one, but I don't think it's a client issue).

Warning	Encryption library	No share key found for user "username" for file "New Folder"
Warning	Encryption library	No share keys found for "/Docs/A Path containing the New Folder"
Error	core	unable to rename, file is not writable : files_encryption/share-keys/Docs/A path containing a new Folder/

I guess what happened someone opened a new folder, than renamed it. 
I saw this happens twice in the log today.(another triplet)

**Comment by PVince81** [comment]
@kaplandani did you see any futher issues with 7.0.7 or 8.0.5 ?

**Comment by kaplandani** [comment]
I'm currnetly on 8.0.4 (reverted back from 8.1 that was broken). 
I will check the log during next week and report back.

**Comment by PVince81** [comment]
@kaplandani any news ?

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/9.0/developer_manual/). :)

Thank you!
