### ISSUE TITLE
Move versioning and trashbin functionalities to actual interfaces on the storage level.

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#12274]
As of today we are facing storage backends (e.g. SWIFT) which come with their own versioning/trash functionality.

We need to have the possibility to respect these functions and give developers the proper handle to implement/integrate these mechanisms.

Proposed Steps:
- [ ] Introduce new interface VersionHandler which is attached to the Storage
- [ ] Move actual local filesystem versioning/trashbin code to an local file system implementation
- [ ] Versioning and trash app will continue to exist as the front end part working on the storage backend interfaces
- [ ] Expose and respect backend capabilities on storage level

@schiesbn @icewind1991 @PVince81 @karlitschek please share your comments and ideas - THX

**Comment by PVince81** [comment]
@labkode as discussed

**Comment by PVince81** [comment]
For trashbin:

The way I see it is that by default every storage would have a hidden ".trashbin" folder (external storage, received shares, etc).

**Comment by PVince81** [comment]
Hmm, also before we can decide on a "trashbin Webdav API" for public access, we need to sort out whether we still want this "per storage" trashbin because it would influence the format of the endpoint as it might need an extra "storage id" argument.

**Comment by labkode** [comment]
@PVince81 the trashbin functionality should be delegated to the storage as an interface to implement, as you mentioned, one could use the default implementation in its own storage.
I would also like to see a version functionality at the same level.

My ideal storage would be the one that can handle itself data, metadata, versions and trashbin without relying on hooks from a top level app like it is the case with the current files_trashbin and files_versions app.

What do you think?

**Comment by PVince81** [comment]
@labkode my concern at the moment is mostly about the UI and the current app.
Is the "Deleted files" view in the web UI a view of the trashbin from **all** storages ? Or do we get rid of this view and display deleted files differently ?

Also what about external storages like SMB, do we store files in a hidden folder ".trash" there ? If not, we'd need a fallback like "use the default trashbin in the data folder" instead.

**Comment by PVince81** [comment]
Regarding versions, there are even more concerns.
If versions are implemented differently per storage, differently not only where the versions are stored but also their behavior. For example the Dropbox storage versions could be based on Dropbox' versions API. The trouble with different behaviors is that it will break the user experience, because versions would behave differently between storages.

This would be even more complex when moving files between storages, because moving files also carry their versions. It means that versions would need to be converted from the local format to the Dropbox format for example. This is too complex.

So maybe we should restrict the spec to "allow storages to store trashed files and versions in a different location" instead of "allow storages to do whatever they want with trashed files and versions" ? Basically having a more specific use case.

Would be good to get more information about the intended use case for this extensibility.
Is it about:
- different behavior for trash/versions for each storage ? (IMO no go due to above reasons)
- a different storage location/format for trash/versions but with same behavior (ex: retention) ? (better)
- ... something else ?

**Comment by PVince81** [comment]
- or is it simply about getting rid of hooks/storage wrappers, basically tech debt ?

**Comment by PVince81** [comment]
Another possibility is to make it possible to have a custom trash/versions handler that can be specified in config.php, basically an alternative backend. The frontend would stay the same. The backend would not be storage dependent, but if needed the backend itself could decide to behave differently based on storage implementations.

Or simply write a new trashbin/versions app that implement the same APIs if the frontend is not important ?

**Comment by PVince81** [comment]
The spec might have changed a bit, can you update ?
