### ISSUE TITLE
occ should verify that it is run as web server user

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#12307]
To my understanding occ should verify that it is run as webserver user. Otherwise we might run into problems as soon as an action creates files which may then have the file permissions.

Also I think I remember some bug reports about data being gone when executed as the wrong user. - Can we somehow easily check whether the user is the web-server user? I can't think of an easy way to do that though.

Or am I completely missing something? - At least we should document that somehow or ensure that we don't mess with files.

@icewind1991 

@jnfrmarks As discussed.

**Comment by smatthie** [comment]
At one point I messed up my file_cache table because I wasn't ware I was running occ under the wrong user, so I support the idea that there should at least be a warning.

Also, would it be possible to run occ via the web interface, e.g. in the admin section? Similar to how you can run cron as a webcron job. this would ensure it's running as the correct user, and also just generally make it easier for administrators.

**Comment by derkostka** [comment]
so i updated Tod oc8 beta 1 and am now unable to run occ, because the www-data user has "no log in" set, for good reason i suppose ...

what's the workaround if I an logged in as root and need to run .occ for maintenance ? 
Ubuntu prohibits www-data user (Apache) to run shell commands by default I guess .. 
thanks !

**Comment by MorrisJobke** [comment]
I always use `sudo -u www-data php occ ...` ;)

**Comment by derkostka** [comment]
okay ;) I should get some sleep, tried su and failed badly ...
