### ISSUE TITLE
[7.0.3] Group administrator can't add users to the goup

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#12349]
### Expected behaviour

An administrator (from a group) add users to that group even if the is not part of it
### Actual behaviour

An administrator (from a group) can't add users to that group even if the is not part of it
### Steps to reproduce
1. I have an user who is administrator from many groups: admin, customers, sales, etc. 
2. The uses belongs to the groups: admin, sales, etc.. (NOT customers)
3. Log in as that user and try to include a user to customers ...... and the field does not appear.
### Server configuration

**ownCloud version:** 
7.0.3

**Updated from an older ownCloud or fresh install:**
Upgraded from 6

**Comment by PVince81** [comment]
Works for me in 8.1.3, my steps:

1. Create a user "user1" 
1. Add "user1" to a new group "group1"
1. Create a user "subadmin"
1. Make "subadmin" a subadmin of "group1" (but NOT a member of it)
1. Login as "subadmin"
1. Create a new user "user2"

See that "user2" is automatically added to the group "group1".

Or did I miss something @cdamken ?

**Comment by butonic** [comment]
> Group admins are not supposed to add new users to their groups.

Hmmm what is their use case then? For most enterprise customers this is the exact use case
1. Create a user "user1"
2. Create a user "subadmin"
3. Make "subadmin" a subadmin and member of a new group "group1"
4. Login as "subadmin"
5. add user "user1" to "group1" <- currently not possible

Actually, user1 typically comes from ldap. Furthermore, they don't want subadmins to manage quota. They subamins should be able to self manage group membership to lift the burden from admins.

cc @felixboehm

**Comment by PVince81** [comment]
Note that for some use cases it might be better to just use the custom groups app: https://marketplace.owncloud.com/apps/customgroups

**Comment by cdamken** [comment]
There is this PR: https://github.com/owncloud/core/pull/31337

@hodyroff Which is the functionality from a group admin if it's not adding and removing users to their groups

**Comment by phil-davis** [comment]
I believe that PR #31337 does fix this up to provide the correct control. A subadmin cannot "pull" other users into the group(s) that they "control". That ensures that a subadmin cannot "take control" of other users on the system.

If the subadmin  has multiple groups under their "control" then they are able to switch group membership of users between the set of groups that they "control". They can put those users into multgiple of their groups, but not into other groups. That seems reasonable to me - the subadmin has been delegated "admin control" of all the users in those groups.

The subadmin cannot add users to other groups - that is good, because otherwise the subadmin could get access to files of any other group by creating a new user in the subadmin's group, then adding that user to some other group, then logging in as that user.

The subadmin cannot remove a user from the last group of that user - i.e. the subadmin cannot "lose control" of a user. That helps keep things more tidy, the subadmin cannot create a long list of users and then "set them adrift" as independent users on the system. 

So I think this issue could be closed - subadmin works "as it should" nowadays.
