### ISSUE TITLE
Error Number 1060

### ISSUE THREAD

**Issue by jphartzenberg** [owncloud/core#12455]
I get the below error on the owncloud client. "An internal error number 1060 happened. 500 Internal Server Error".
![owncloud error 26-11-2014](https://cloud.githubusercontent.com/assets/7986391/5201529/14fd3a9a-757c-11e4-8840-1b92090df619.png)

**Comment by MorrisJobke** [comment]
@jphartzenberg Setting up a new server and migrating the data will most propably fix this issue.

I’m closing this pull request _for now_ because of inactivity.

@jphartzenberg  we can always reopen it though! :) Please add more information.
If you need any help, please ask on our [developer mailing list](http://mailman.owncloud.org/mailman/listinfo/devel) and join our IRC channel at #owncloud-dev (freenode network).
