### ISSUE TITLE
Error: Destination file exists (Syncing WoW settings files)

### ISSUE THREAD

**Issue by GnaXi** [owncloud/core#12517]
I've set up a couple of folders from the game World of Warcraft to be automatically synced, to be able to keep my settings on a couple of computers. I used to do this with Dropbox, but since I have Owncloud running, I thought that I might as well use it for the job.
But, a bunch of files are now being downloaded every 5 minutes, even though there are no change to them.
Here's a picture that shows exactly what's happening. This is just 10 minutes of log. The log goes on for hours.
![download](https://cloud.githubusercontent.com/assets/1616448/5237234/6148abfc-7877-11e4-8798-ede963ea316b.png)

I can remove the files and resync them, which will work for a couple of hours and then it starts again.

This is on a Windows 8 (64-bit) and the latest version of both Owncloud (7.0.3) and Client (1.7.0)
If at all interesting, the setup looks like this:
![setup](https://cloud.githubusercontent.com/assets/1616448/5237240/d2bc36f0-7877-11e4-9736-19ccad59aea5.png)

**Comment by tflidd** [comment]
I got the same error like @GnaXi in his comment https://github.com/owncloud/core/issues/12517#issuecomment-65027741

Here it is a OC-client 1.7.1 on OS X Mavericks. This user hasn’t synced to OC for a very long time. In the meantime I had to rebuilt the filecache-table, so the client downloaded all files again.

With two files it did fail with this message “destination file exists". Error in the client log:
````
02-13 20:03:09:268 0x104c06050 socketapi.cpp:382 void Mirall::SocketApi::command_RETRIEVE_FILE_STATUS(const QString &, SocketType *) "/Users/adminpc/ownCloud/folder/file.PDF"
````
No errors on server side (already in debug mode). I use encryption, but file-key and the shared key for user are present.

Then I de-selected the folder where the files are located from the sync (choose what to sync) and the client threw an error that it couldn’t delete these files. So I looked into the filesystem, and voila:
````
7890109    0 drwxr-xr-x   5 adminpc  staff   170B Dec 18 14:00 folder_normal_1
2217802    0 drwxr-xr-x  19 adminpc  staff   646B Feb 13 12:42 folder_normal_2
2193433    0 drwxrwxrwx   4 adminpc  staff   136B Feb 13 20:15 folder
````
folder_normal_1 and 2 are just folders that don’t make any problems. Our folder has chmod 777. A look inside the folder:
````
2193435  80 -rwxrwxrwx   1 adminpc  staff    39K Jan 27  2011 file2.pdf
2193443 160 -rwxrwxrwx   1 adminpc  staff    77K Nov  7  2012 file.PDF
````
Two files the client can’t delete, both chmod 777. Then I paused the sync client and moved the files manually to the trash bin. Then I started the sync-process again, the client was happy. Then I selected the problematic folder again and now:
````
7890109    0 drwxr-xr-x   5 adminpc  staff   170B Dec 18 14:00 folder_normal_1
2217802    0 drwxr-xr-x  19 adminpc  staff   646B Feb 13 12:42 folder_normal_2
8551277    0 drwxr-xr-x  19 adminpc  staff   646B Feb 13 20:21 folder
````
chmod changed, and the files:
````
8551278    80 -rw-r--r--   1 adminpc  staff    39K Jan 27  2011 file2.pdf
8551297   160 -rw-r--r--   1 adminpc  staff    77K Nov  7  2012 file.PDF
````
as well.

I can’t reproduce this. Setting any folder and a file to chmod 777 doesn’t block the client. I can even edit this file on the web interface and it gets synced without problems.

Since the last sync of the client there has been at least one update on the server (now 7.0.4, before 7.0.3 or earlier) and the client (now 1.7.1, before 1.7.0 or earlier). Possible that’s still from June/July with OC 6.

Server: Ubuntu 14.04, Apache 2.4, mod_php, encr_module (https://github.com/owncloud/core/issues/12725#issuecomment-73253435).

**Comment by PVince81** [comment]
I wonder if this has something to do with deletion issues.
There were reports that when the trashbin is full, files sometimes cannot be automatically deleted.

**Comment by dragotin** [comment]
that was because the deletion request timed out.

**Comment by PVince81** [comment]
Ok, maybe the trashbin is taking too much time to auto-expire stuff, similar to https://github.com/owncloud/core/issues/13974

**Comment by tflidd** [comment]
I only un-selected some folders on the oc-client. All files stayed on the server, there was no copying/deleting/moving files on server-side!

**Comment by moscicki** [comment]
@dragotin: this looks to me as a pure client problem. We have this issue  (Destination file exists) now reported by a user on MacOSX for a handful of files (out of 40K). Could this be related to special files in HFS+ (bundles/packages whatever it is called)? Some affected paths: Music/iTunes/iTunes Library.itl

**Comment by moscicki** [comment]
![image](https://cloud.githubusercontent.com/assets/621965/6731557/ee32536e-ce45-11e4-92ff-04fbf1b87079.png)

![image](https://cloud.githubusercontent.com/assets/621965/6731564/fc9e8526-ce45-11e4-84b9-745bcdf799d6.png)

**Comment by dragotin** [comment]
maybe. Added this to the 1.8.1 milestone of the client, lets see what we can find out.

**Comment by PVince81** [comment]
Is this still happening with 8.0.5 or 8.1 with sync client 1.8.4 ?

**Comment by PVince81** [comment]
Please try again with 8.1.3 and sync client 2.0.1.
If the problem still happens, please reopen.
Thanks.
