### ISSUE TITLE
Redesign / revamp folder share permissions

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12970]
Currently the folder share permissions are the following:
1) For files: can share, can edit
2) For folders: can share, can edit, can create, can update, can delete

I'm not sure what the original design decision was to have create, update and delete as separate permissions, but these case require additional code paths and also additional testing time (which often seems to be missed). And I'm not sure whether the advantage of having separate permissions justifies the extra work / code paths / qa required to make it work.

I suggest to merge the folder permissions and limit them to the following: can share, can edit.
Get rid of "can create, can update, can delete".

What do you think ?

@owncloud/designers @MTRichards @karlitschek @craigpg

**Comment by PVince81** [comment]
One of the confusion is also: in what situations is a "rename" allowed ?
- Create ? (a rename somewhat creates a new file)
- Update ? (a rename updates the file name)

**Comment by jancborchardt** [comment]
Rename belongs to the update permission, that’s most understandable.

**Comment by PVince81** [comment]
Here is an "overview" in test code form of how the permissions work at the moment, it's quite messy:
https://github.com/owncloud/smashbox/blob/master/lib/oc-tests/test_sharePermissions.py#L77

**Comment by rullzer** [comment]
Yes please this needs to be simplified. Also from a webdav persepctive (and in 9.0 that will most likely also be used for the webend). 

I would really like if we could properly follow the webdav spec. So there are only moves. No renames. 

Examples of weird behaviour:
* It is very counter intuitive that if I only have update permissions I can rename a file. But can't move it to a subfolder.
* Also if I have create and delete permissions I can't rename (thus move in the same folder) a file. But I can move it to a different folder. And then move it back with a different name.
* What do update permission on a directory mean? Can I update the contents (if so that would probabaly mean create and delete as well). But no that is not the case.

All in all I think that if the devs that work with ownCloud every day can't understand what is happening when it is a sign that this needs to be fixed.

**Comment by MTRichards** [comment]
Pulling in the conversation from over in documentation (how did it get there?):
https://github.com/owncloud/documentation/issues/1920#issuecomment-163941766

Ok, so we have the proposed simplification of the UI:
1) a simple user can edit or not, and can share or not.
2) resharing is collapsed into the owners share view
3) automatic notification emails sent by default, with a config setting to turn these notifications off in extreme cases

This should remove the "notify by email" option for internal users when something is shared.

**Comment by MTRichards** [comment]
@jancborchardt pulling the conversation here from the documentation repository.
https://github.com/owncloud/documentation/issues/1920#issuecomment-163941766

**Comment by rullzer** [comment]
Yes please! I must say I like this very much.

@MTRichards with notifications you mean the activity e-mails that are send now already?

**Comment by MTRichards** [comment]
Yes, the emails we send from activity. That was vague, typing too fast. :/

**Comment by butonic** [comment]
can we also set the default to the minimal set of permissions, eg read only? users might forget to change permissions and unintendedly allow modification or resharing of their data. or make this a config option (globally and per user). we have customers fearing for their data...

**Comment by rullzer** [comment]
@butonic see that descussion in https://github.com/owncloud/core/issues/11707

**Comment by MTRichards** [comment]
Copied over from #11707 :

Most important is to cover the most likely scenario with the defaults.
Resharing should be off by default. That should be an act of commission - you want someone to get a copy of a copy, therefore you turn on resharing. Otherwise, it should be off (and off by default).

Editing should be on, that is why you share with someone more often than not. Delete should be off inside edit, so we don't have people losing data by accident.

That covers the most likely path for most users, and then the others can be configured at the time of share.

**Comment by karlitschek** [comment]
Hmmm. I think RW is the most common use-case so I think it should be default. This is also how all the competitors I'm aware of of do it. read only is some kind of special case in my opinion especially considering that our desktop clients don't handles this in a great way at the moment. Users can change shared files locally but then the upload while syncing fails which is sometimes a bit confusing for people. 
So I vote for RW as default as it is today.

**Comment by jancborchardt** [comment]
Totally agree with @karlitschek. Also, resharing (that is, »sharing«) should be _on_ by default, as it makes little sense to restrict this from the outset. ownCloud is about sharing, after all.

**Comment by butonic** [comment]
then we should still give admins the possibility to change the defaults when they are more conservative. As happens with customers ...

**Comment by MTRichards** [comment]
What I would like to avoid is yet more config settings and potential for confusion, more support calls, etc.

If we have a customer that is looking for it, certainly we can entertain this concept. BUT I would rather not be adding more config options for something as small as checkboxes in a menu.

**Comment by jancborchardt** [comment]
Even if the request should indeed come, that should be a config.php setting at most, not exposed in the admin settings.
