### ISSUE TITLE
.htaccess incopatible with PHP-FPM

### ISSUE THREAD

**Issue by svecpetr** [owncloud/core#13066]
in owncloud root directory is .htaccess, but this file is incopatible with using Apache2 with PHP-FPM via FastCGI

you use declaration `<IFModule mod_fcgid.c>`

but no declaration for `<IfModule mod_fastcgi.c>`

**Comment by mmattel** [comment]
documentation regarding .htaccess and .user.ini at (already merged):
owncloud/documentation#856 (document that in case of php-fpm configurations, .user.ini must be used instead of .htaccess)

If there is anything to be documented regarding the ``-pass-header Authorization`` component, please describe the issue in more detail respectively create a issue in the documentation tracker as sugested by @RealRancor

**Comment by castarco** [comment]
Hello, I think my problem maybe is related with this one. I'm doing a clean install of Owncloud (via DEB packages, using APT) 8.0.2 on Ubuntu 14.04, using Apache 2.4 and PHP-FPM.

When I go to the initial page, the install process continues, it asks me for user, password, db connection data, and so on. I introduce all the data, click the button to continue and then, the problem appears. Owncloud cries because there is no .htaccess file in the directory (why? the packages could contain it). I refresh the page and the same form appears, BUT, the previously created user hasn't been erased. I'm stuck at this installation step.

If I try to manually create an .htaccess file the problem doesn't disappear.

**Comment by PVince81** [comment]
Closing as the php-fpm setup has been documented.

For support about environment issues, see https://owncloud.org/support/ or go to http://central.owncloud.org/.
