### ISSUE TITLE
Problem in 8 alpha 1 with user_webdavauth and user creation

### ISSUE THREAD

**Issue by canepan** [owncloud/core#13081]
I installed the new alpha 1, executed the wizard and enabled the user_webdavauth app.
Now, when trying to create a new user, I get a dialog saying:
> Error creating user
> 
> Unable to create user.

**Comment by canepan** [comment]
I do not have this problem with 7.x (using 7.0.4 now)

Nicola

**Comment by RealRancor** [comment]
Hi,

> I do not have this problem with 7.x (using 7.0.4 now)

maybe because you didn't have enabled this in OC7? Because the same happens if you have enabled the user_webdavauth in OC7. For this we have an extra FAQ thread at the forums:

https://forum.owncloud.org/viewtopic.php?f=17&t=20221

containing a description.

A general question:

Are you authenticating your users against an external webdav server?

**Comment by LukasReschke** [comment]
Fixed according to ML. User error.
