### ISSUE TITLE
owncloud 7 on ubuntu 14.04 server with nginx 1.6.2 webserver loading aap page problem

### ISSUE THREAD

**Issue by tabatabaei** [owncloud/core#13137]
i install owncloud 7.0.4 in ubuntu server 14.04 with nginx this config 
http://doc.owncloud.org/server/7.0/admin_manual/installation/configuration_nginx.html
but i can't see page 
https://mydomain/index.php/settings/apps?installed
and show this page 
504 Gateway Time-out
nginx/1.6.2

i refresh 3 or more this url  maybe show  page 

i install owncloud to another server with this config only work in chorme browser an show login page in other browser ???!!!!!!!!!!
but i can't see this url 
https://mydomain/index.php/settings/apps?installed

**Comment by Xenopathic** [comment]
nginx is timing out waiting for PHP-FPM to respond, because loading the list of apps is a very resource heavy process and takes a long time, especially on less powerful hardware. You need to set `fastcgi_read_timeout` in `nginx.conf` (or associated files) to a higher value, perhaps 300? At the same time you should increase the maximum PHP execution time by setting `max_execution_time` in `php.ini`.

If after the above steps you still cannot get it to work, please read the [contribution guidelines](CONTRIBUTING.md) so that we can help you.

**Comment by tabatabaei** [comment]
tnax
i run owncloud in to different system 
system 1 - 1Gb ram 1 cpu 1.6
system 2 - 10 Gb ram 8 core of xenon cpu 2690
both of them is virtual 1- virtual box , 2 proxmox 
in system 1 my problem solvet when max_execution_time to 300 
and not worket on system 2 when i upper max_execution_time to 3000
i install nginx because user less memory and proccess 
when page is loading i monitor the cpu and memory that enough 
system 2 only load first page in old firefox ?!!!!!! 

sockt is better or tcp ???
;listen = /var/run/php5-fpm.sock
or
listen = 127.0.0.1:9000

**Comment by Xenopathic** [comment]
You also need to increase `fastcgi_read_timeout`, since that 504 Gateway Timeout is nginx complaining that PHP is taking too long.

Neither UNIX socket or TCP socket is fundementally better, but if you use TCP remember to block the port in your firewall, or else anyone can send queries directly to PHP without the restrictions provided by your web server.

**Comment by tabatabaei** [comment]
i can't find fastcgi_read_timeout  in php.ini 
i dont have any firewall, i use local network 
how can i test anyone can send queries directly to PHP without the restrictions provided by your web server.
my local network dont access the internet

**Comment by Xenopathic** [comment]
Please read my original response - you need to set `fastcgi_read_timeout` in `nginx.conf`. You can find this information in the nginx documentation.

**Comment by tabatabaei** [comment]
tanks 
set fastcgi_read_timeout 300s; 
and dont show this page 
504 Gateway Time-out
nginx/1.6.2
but very slow work and dont open in my ubuntu desktop firefox 32 only show first page

**Comment by tabatabaei** [comment]
tanks i set domain and config owncloud config file and solved

**Comment by DeepDiver1975** [comment]
> tanks i set domain and config owncloud config file and solved

case closed? THX

**Comment by MorrisJobke** [comment]
Please reopen if this isn't fixed
