### ISSUE TITLE
Share key not always created if sharing while uploading to an encrypted folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13144]
### Steps to reproduce
1. Enable encryption
2. Setup two users "user1" and "user2"
3. Login as "user1"
4. Create a folder "pics"
5. Setup the sync client for "user1"
6. Copy a lot of pictures into the **local** folder "pics" for "user1"
7. While the sync client is uploading, share "pics" with "user2"
8. Try opening all pics with "user2"

### Expected result
"user2" can read all pics

### Actual result
If the timing is right, one picture will be broken and miss the share key for "user2".
The code that creates the share keys during upload races against the code that uploads pictures.

Note: this happened on my own private server and since it's a race condition it might be difficult to reproduce.

### Versions
ownCloud 7.0.4

CC @schiesbn @dttpy as discussed

**Comment by schiesbn** [comment]
The problem seems to be that we create the new share keys in a pre-hook when a file/folder was shared. On one hand this makes sense because we want to create first all encryption keys before the share gets visible to the users. But in this case it is a problem. All files which get written to the folder while the pre-hook still runs will not be encrypted for the new recipient because the new share will neither be recogniced during the upload (because it will only be written to the share table once the pre-hook was finished) nor will be the file be in the list of files for the pre-hook to create the new share keys (because the list gets created at the beginning of the hook).

Probably we need to create some intermediate state where a share gets already written to the share table but gets only mounted once all hooks are finished.

**Comment by PVince81** [comment]
@schiesbn do you think the new approach from enc 2.0 will fix it ?
If not, this will need to be covered somehow by transactional locking, maybe through https://github.com/owncloud/core/issues/17243
