### ISSUE TITLE
I am not able to sync from owncloud Andriod app, please help

### ISSUE THREAD

**Issue by deepakpatiyal** [owncloud/core#13163]

**Comment by deepakpatiyal** [comment]
Please help

**Comment by MorrisJobke** [comment]
@deepakpatiyal Can you please fill out the issue template (I already wrote that in your previous issue https://github.com/owncloud/core/issues/13146#issuecomment-69014110) Until you provide this information we can nothing do for you, as we don't know what could cause this. I will again close this ticket as it is useless. 

Please open a new issue with all the information, otherwise we will close this too.
