### ISSUE TITLE
file name changed after reshare

### ISSUE THREAD

**Issue by dttpy** [owncloud/core#13213]
### Steps to reproduce
1. log in with admin account
2. create a user "user1"
3. sort "admin" into a group "admin"
4. log in with "user1"
5. create a folder "permission"
6. share the folder "permission" with admin, but with only "change" permission
7. go into "permission" and create a text file "per2.txt"
8. share the file "per2.txt" with admin(group) with no permission (read-only)
9. log in with admin
10. log in with user1
11. stop to share folder "permission" with admin
12. log in with admin

### Expected behaviour
Step 9:
There should be a shared folder "permission" and a shared file "per2.txt" in the file list
Step 12:
There should be a file "per2.txt", which is shared by user1

### Actual behaviour
Step 9:
There is a shared folder "permission" and a shared file named "permission(2)" in the file list
Step 12:
There is a file "permission(2)", which is shared by user1

### Server configuration
**Operating system:** Ubuntu 13.10

**Web server:** apache 2.4.6 (Ubuntu)

**Database:** SQLite

**PHP version:** 5.5.3-1ubuntu2.3

**ownCloud version:** 7.0.4 & master

**Updated from an older ownCloud or fresh install:** owncloud 7.0.3

**List of activated apps:** standard apps of owncloud

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
$CONFIG = array (
  'instanceid' => 'oc6d9cda6e26',

  'datadirectory' => '/var/ocdata/.../owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => '0',
  'trusted_domains' => 
  array (
    0 => '192.168.1.80',
  ),

);
```

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes

### Client configuration
**Browser:** firefox 34.0.5

**Operating system:** ubuntu 13.10

**Comment by dttpy** [comment]
@PVince81 @schiesbn

**Comment by PVince81** [comment]
@schiesbn that's the one I told you about last week where grouping of shares mixes up file names

**Comment by butonic** [comment]
merging with #14724. adding description here for better reproducability:
### Steps to reproduce
1. Create a user *test* in group *testgroup*
2. share `/testfolder` ro with *testgroup*
3. share `/testfolder/subfolder` rw with *test*

### Expected behaviour
*test* receives `/testfolder` with ro permissions and `/testfolder/subfolder` with rw permissions

### Actual behaviour
*test* receives `/testfolder` with ro permissions and a second `/testfolder (2)` with rw permissions with the content of `/testfolder/subfolder`

### Acceptable, but unintuitive solution
*test* receives `/testfolder` with ro permissions and `/subfolder` with rw permissions
behavior needs to be documented

### Related
https://github.com/owncloud/core/issues/4579

**Comment by PVince81** [comment]
Still observed on 8.1 alpha2 (I hoped that some of the sharing fixes covered it, but they didn't)

**Comment by karlitschek** [comment]
@schiesbn Would be great if you could look into that. :-)

**Comment by PVince81** [comment]
or @rullzer the new sharing master, if you want to dig deep :wink:

**Comment by rullzer** [comment]
@butonic I see how your expected behaviour could be expected. But I think you acceptable approach makes more sense. Since it really is a different share and else we need a way to better show the available permissions within a directory.

I'll crate a unit test to verify that behaviour. And then make sure everything works as expected. Hopefully we can get this into 8.1!

**Comment by rullzer** [comment]
I started on the unit test. However just sharing a subfolder already fails in the unit tests. Which means something is probably not right in the unit test setup. 

Unit test at: https://github.com/rullzer/core/blob/fix_13213/tests/lib/share/share.php#L392-L416

Error:
'''
1) Test_Share::testRwShareWithUserWithinRoShareWithGroup
Undefined index: path

/home/roeland/owncloud/core/apps/files_sharing/lib/share/folder.php:42
/home/roeland/owncloud/core/lib/private/share/share.php:1819
/home/roeland/owncloud/core/lib/private/share/share.php:642
/home/roeland/owncloud/core/lib/public/share.php:261
/home/roeland/owncloud/core/tests/lib/share/share.php:410
'''

Seems the unit test should not touch app/files_sharing at all!
Maybe this sounds familiar to somebody (@schiesbn ?). Else I'll dive into it in more detail tomorrow.

**Comment by karlitschek** [comment]
@schiesbn Can you have a look?

**Comment by PVince81** [comment]
@rullzer @schiesbn any update ?

**Comment by cmonteroluque** [comment]
@rullzer ping :)
