### ISSUE TITLE
LDAP login must have username all lowercase on LDAP server

### ISSUE THREAD

**Issue by powerstorm42** [owncloud/core#13346]
If I have a LDAP user "Test" on the server then this user cannot login through LDAP (tried test, Test, etc.)
However, if the LDAP username is "test" then the user can login using both test and Test.
It looks like the username is converted to lowercase and then a case-sensitive match is done, but it should be a case-insensitive match. I tried this with the "case-insensitive server (Windows)" both on and off.

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
Can't reproduce, works fine for me with stable7 and OpenLDAP.

@powerstorm42 please complete your issue report according to the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by blizzz** [comment]
Closed for inactivity. If you continue to see this misbehaviour and have more information, please reopen.

**Comment by vmuth** [comment]
in owncloud 9.0 the checkbox "Case insensitive LDAP Server" does not exist any more because owncloud does not need any tweaks any more. However, with OSX OpenDirectory this issue still exists. I have OSX "El Capitan" with OpenDirectory and now the same problem occours when user "Test" (in OpenDirectory) tries to log into owncloud (I tried to log in as "Test", "test", "TEST")
