### ISSUE TITLE
Renaming folder not updating under other accounts

### ISSUE THREAD

**Issue by smsipes** [owncloud/core#13400]
When I update a folder name under one account that update doesn't take effect in the rest of the other accounts. However the old folder names for the other accounts remained intact and usable, there is no data lossed. How do I get the other accounts to update with the new directory name?

We have a fresh install, version 7.0.4-16.1. 

OS - Linux
PHP Version - php version 5.4.34
DB - MySQL

**Comment by PVince81** [comment]
Can you describe the folder more in detail ?
Is it a folder that you have shared with other users ?
If you rename it locally or the users share the folder itself, it's only local.
This is because we allow users to freely rename and move the shared folder inside their own home as it suits them (people like to oragnize their shares differently).

Only renaming/changing the contents affects everyone.

Let us know if it is that case or something different.

**Comment by smsipes** [comment]
The folder is:

·         At the main root level

·         shared with others.

·         Not local to the owner or any other shared users

The change was made within the browser as the owner. Looking through the backend as far as I can tell everything has been updated correctly but if I log in as a shared user the directory name still shows up as the old name. I am able to go into that directory and access everything just fine.

Please let me know if I can provide more information.

**Comment by DeepDiver1975** [comment]
this is by design - the name of a shared folder is kept constant on the share receiver
