### ISSUE TITLE
Delete multiple items from the trashbin is not possible

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#13431]
* delete a file from the trashbin
* hover over the delete column for another item

# expected bahaviour

* trash bin icon is visible and clickable

# actual behaviour

* trash bin icon is not visible nor is the table cell clickable until the loading spinner of the previous deleted file is gone (actually the whole row is gone)

cc @PVince81 @schiesbn

**Comment by MorrisJobke** [comment]
I'm on 7.0.4 - with Firefox

**Comment by MorrisJobke** [comment]
not only the trashbin icon disappears. Also the checkbox in the first column disappears.

**Comment by Sugaroverdose** [comment]
Can't reproduce this on 7.0.4.2 with ff34

**Comment by PVince81** [comment]
@MorrisJobke ah yes, I see.
I think this was by design to avoid multiple actions messing up. There's code that disables all file actions during delete.

We can look into making parallel deletion supported for better UX.
Note that this means a user could first delete a file into a subdir, and while it's being deleted, the user could quickly go out of the folder and delete the folder itself. So the backend PHP code needs to allow for the deletion of non-existing files (already deleted by another operation).

**Comment by MorrisJobke** [comment]
Can't reproduce anymore -> seems to be fixed in the meantime
