### ISSUE TITLE
Cannot configure email

### ISSUE THREAD

**Issue by notfrombrooklyn** [owncloud/core#13482]
I have Owncloud 7.0.4.

When I try to send a test mail to my email (after configuration), I get this error:
Cannot modify header information - headers already sent by (output started at /var/www/3rdparty/phpmailer/phpmailer/class.smtp.php:181) at /var/www/lib/private/appframework/app.php

**Comment by karlitschek** [comment]
@nickvergessen

**Comment by nickvergessen** [comment]
You don't have the actual output of the page, do you?
```php
    /**
     * Output debugging info via a user-selected method.
     * @param string $str Debug string to output
     * @return void
     */
    protected function edebug($str)
    {
        switch ($this->Debugoutput) {
....
            case 'echo':
            default:
                echo gmdate('Y-m-d H:i:s')."\t".trim($str)."\n";
        }
    }
```
The problem is, this is in 3rdparty code, and something is printing debug information.
Without knowing which debug information it's printing, we can't really help.

@karlitschek I don't think it's a showstopper, I think it tends to be a misconfiguration somewhere.
Also he says it's oC 7.0.4 so not blocking 8.0 really

**Comment by notfrombrooklyn** [comment]
Is where a way to know what is trying to print debug information? A debyg log or something?

**Comment by DeepDiver1975** [comment]
@notfrombrooklyn as workaround you can set 'mail_smtpdebug' to false in your config/config.php

**Comment by DeepDiver1975** [comment]
@nickvergessen we should set $Debugoutput in phpmailer to error_log - default is 'echo' which will break any installation as soon as 'mail_smtpdebug' is enabled

**Comment by DeepDiver1975** [comment]
no showstopper from my pov - but an easy to fix issue - @nickvergessen if time permits
