### ISSUE TITLE
S2S share and local name collision

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#13603]
### Steps to reproduce

1. As UserA create and share a folder cia public link
2. As UserB (on the same instance) visit public link and use the "Add to owncloud" feature
3. As UserA share the folder with UserB locally

### Expected
UserB has to folders _Test_ (from the s2s feature) and _Test (2)_ (from the local share)

### Actual
UserB has only _Test_ (from the s2s feature)
The local share is missing, although the share is actually there, it just uses the same name and therefor only one entry is displayed.

If you turn around step 2 and 3 everything works as intended, so S2S checks both tables for collisions, but normal sharing does not.

@DeepDiver1975 please rate 8.0

**Comment by karlitschek** [comment]
@schiesbn

**Comment by schiesbn** [comment]
The check for collisions doesn't happen on db level but on file system level. Maybe at the point where the collision check happens the s2s share isn't mounted. But this would be quite bad because this would mean that most likely other external storage are also not mounted at this point in time and could create collisions too.

@nickvergessen do you think you have some time to investigate into this direction. I'm currently working on some other s2s issues.

**Comment by nickvergessen** [comment]
Okay yeah seems like for my s2s share no file is created therefor the view reports that the folder name _Test_ can be used because there is no conflict.
