### ISSUE TITLE
use appframework for preview system

### ISSUE THREAD

**Issue by georgehrke** [owncloud/core#13610]
Migrate preview.png, etc ... to appframework.

Subtasks:
- [ ] Add a proper previewController
- [ ] Preview / Image Response types (require stream based responses)

**Comment by oparoz** [comment]
How will this work when we have to call several methods one after the other? We can't make REST calls for that as it would hurt performance badly.

**Comment by georgehrke** [comment]
@oparoz I'm not sure what you are referring to. What several methods do we have to call one after another?

**Comment by oparoz** [comment]
A Typical sequence
```
isMimeSupported()
getPreview()
valid()
width()
height()
isCached()
```
It's currently useful to be able to get an object so that we can call these methods.
I guess all the returned values could be included in the reply we get from the controller, if that reply was to include the values of all the public methods.

Sometimes we also use
```
resource()
```
But I guess it could be a separate call and not be too problematic as long as the Image class stays in core.

**Comment by oparoz** [comment]
- [ ] Move mimetypes.list.php to a text file in /config https://github.com/owncloud/core/issues/15384

**Comment by PVince81** [comment]
Move to 9.0 as we're past feature-freeze ?

**Comment by georgehrke** [comment]
see https://github.com/owncloud/core/pull/18675#issuecomment-136646122

I guess we can close this issue.

**Comment by cmonteroluque** [comment]
moved to 9.0

**Comment by PVince81** [comment]
Past feature freeze, move to 9.1

**Comment by PVince81** [comment]
obsolete by DAV preview route: https://github.com/owncloud/core/pull/29319
