### ISSUE TITLE
Authentification Problem WebDAV, CalDAV (Lightning)

### ISSUE THREAD

**Issue by crti** [owncloud/core#1364]
Everytime after an update (over integrated updater) I encounter the same problem with Thunderbird Lightning not authenticating anymore. 
You can find discussion, description and solution here
http://forum.owncloud.org/viewtopic.php?f=3&t=1894

Basically I have to edit manually these two files everytime after update to fix the problem: 

.htaccess (replacing)
>     RewriteRule .* - [env=REMOTE_USER:%{HTTP:Authorization},last]

/lib/base.php (adding)
> //authentification fix (Lightning CalDAV etc.)
> if (isset($_SERVER['REDIRECT_REMOTE_USER']) && preg_match('/Basic\s+(.*)$/i', $_SERVER['REDIRECT_REMOTE_USER'], $matches))
>    {
>    list($name, $password) = explode(':', base64_decode($matches[1]));
>    $_SERVER['PHP_AUTH_USER'] = strip_tags($name);
>    $_SERVER['PHP_AUTH_PW'] = strip_tags($password);
>    }

I would appreciate if this could be integrated/fixed in core files. Thank you.

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/5.0/developer_manual/). :)

Thank you!
