### ISSUE TITLE
Static url prefix for CDN

### ISSUE THREAD

**Issue by ondrejsika** [owncloud/core#13649]
Add config option for serve static files from other domain.

**Comment by DeepDiver1975** [comment]
pull requests on this is very much welcome.

@LukasReschke any requirements to add from a sec pov? THX

**Comment by tunisiano187** [comment]
I'm interested withthis feature too...

**Comment by TylerTemp** [comment]
👍 Looking for this too...

**Comment by xZero707** [comment]
Can't wait

**Comment by DeepDiver1975** [comment]
To all who are interested in this feature: contribute!

**Comment by PVince81** [comment]
Just thought of this and it is likely not possible. The reason is that there is a lot (too much) resource location magic which might in some setups not have a proper URL to path mapping. The resource locator magic exists because:
- apps can be stored in multiple folders, even some outside of the OC root, but their URL still maps to "apps/$appName/some-resource"
- themes can override any resource (CSS, JS, PHP, ...) so their path also need to be overwritten somehow

If we could normalize the above to not require any magic any more not overriding, it would be a different story.
