### ISSUE TITLE
User Management Using LDAP: Search String by Last Name

### ISSUE THREAD

**Issue by degrb** [owncloud/core#13737]
This is in related to: https://github.com/owncloud/core/issues/8959

Search for LDAP users is still done by the x? scheme. That is, if I'm looking for an LDAP user "John Smith", I have to search for "Jo..." instead of e.g. "Smith".

I would be useful if you could do ?x? style searches for LDAP users too.

It would also come in handy if LDAP searches included the "User name" column (not just the "Full name" column, as is the case now).

**Comment by MorrisJobke** [comment]
@degrb I guess this was removed to improve the performance of the search. Or am I wrong, @blizzz ?

**Comment by blizzz** [comment]
@degrb please have a look at the User Search Attributes, it is all documented: http://doc.owncloud.org/server/7.0/admin_manual/configuration/auth_ldap.html#directory-settings

Just add sn, fn, employeeNumber or whatever you want and everything will be taken into account. When you have seperate first and last name there, you can even look for "Smi Joh" and "John Smith" will be found.

And you can still do searches with wild cards in the beginning by just typing "*smith" to find "John Smith" if only the display name attribute is used as search attribute (default). But be aware that this is slow and thus must be triggered manually. But this will not be the default for performance reasons. Since it is possible to add many attributes for the search and in 99% of all cases people do not start to type in the middle of a name, it also just does not make sense to have this expensive type of search as default :)
