### ISSUE TITLE
[7.0.4] sendfile colides with base.php

### ISSUE THREAD

**Issue by klondi** [owncloud/core#13738]
Looking at the logs I found a few lines as follows:

```
Cannot modify header information - headers already sent by (output started at /owncloud/lib/private/template/base.php:108) at /owncloud/lib/private/files.php#169
```

I suspect this is related to the use of xsendfile and maybe asset-pipeline.enabled as I have both enabled. The version is 7.0.4.2 according to the config file from the portage tree in Gentoo.

For the record following the advice for large file sending I have set output_buffering = 0 as recommeneded on http://doc.owncloud.org/server/7.0/admin_manual/configuration/big_file_upload_configuration.html which seems to be part of the cause of the problem.

**Comment by MorrisJobke** [comment]
@LukasReschke Didn't you introduced the xsendfile stuff?

**Comment by LukasReschke** [comment]
Nope. But we have such problems in the code quite a few times – this is basically caused by us mixing old legacy stuff with new fancy appframework stuff.

That's the reason for workarounds such as https://github.com/owncloud/core/blob/723f2a1cba27345e3cba2c43887a974813402299/apps/files_sharing/lib/controllers/sharecontroller.php#L253-L256

**Comment by Xenopathic** [comment]
Please retry with oC 8.1.1 and reopen if you are still seeing the issues

**Comment by klondi** [comment]
Seems 8.1.1 has fixed this :)
