### ISSUE TITLE
L10N script fails to extract strings from JS files when using string concatenation

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/core#13924]
See https://github.com/owncloud/news/issues/719

The following code fails to be translated although its perfectly fine js
```js
t('news', 'a' +
              'string');
```

This makes it impossible to wrap longer strings. I think its due to the reason that we are using Python mode when parsing js files. In Python the above code would throw a SyntaxError so I guess that's the reason why it's parsed incorrectly.

Any ideas? We really need to go for something that can parse JS properly and the perl file is at least for me unreadable. Can we port that to something that can actually be edited by more than 2 people?

@PVince81 @jakobsack @DeepDiver1975 @MorrisJobke @LEDfan @georgehrke @nickvergessen @butonic

**Comment by DeepDiver1975** [comment]
Any new tool is welcome as long as the behavior is unchanged - the new tools has to generate the same output.

I see options for a new tool: add this 
- [ ] as console command to occ
- [ ] as command to ocdev

**Comment by MorrisJobke** [comment]
@DeepDiver1975 I read some time ago about how github deploys new refactored code. And this time we can do it the same way:

They simply execute the old and the new path in parallel and can therefore check if the output is the exact same. Once all this is verified over some time we can switch over to the new code. This also verifies that we don't break anything ;)

I would vote for writing this in PHP, because everyone here can write and read PHP code. Also every app developer can do this. ;)

**Comment by jakobsack** [comment]
AS you can see in https://github.com/owncloud/core/blob/master/l10n/l10n.pl#L123 we use xgettext for extracting the strings. Maybe it is possible to fix the bug by changing some arguments.

**Comment by DeepDiver1975** [comment]
http://savannah.gnu.org/forum/forum.php?forum_id=7641

looks like JavaScript is now supported - have to update gettext on the server .....

**Comment by DeepDiver1975** [comment]
... okay - on day ... :speak_no_evil:

**Comment by PVince81** [comment]
Moving to 8.2

**Comment by DeepDiver1975** [comment]
> Moving to 8.2

yes - thx

**Comment by PVince81** [comment]
Moving again

**Comment by nickvergessen** [comment]
Fixed via https://github.com/owncloud/administration/issues/71
