### ISSUE TITLE
Last login in usermanagement always shows a few seconds on all users

### ISSUE THREAD

**Issue by einmalacht** [owncloud/core#14005]
i updated the OC from 7.xx to 8 and all works very well but
Last login in usermanagement always shows a few seconds on all users

**Comment by DeepDiver1975** [comment]
This is because we are passing the timestamp as text to the ctor of moment().
Furthermore seconds as of the unix timestamp are not valid - milliseconds are requested.

@MorrisJobke @LukasReschke @blizzz @PVince81 anyone please take care of this.

As discusses many times: we shall not communicate unix timestamps but iso-8601 strings to fight timezone issues and allow easier debugging. THX

**Comment by DeepDiver1975** [comment]
#14262 and #14261 got merged

will be fixed in 8.0.1 and 8.1
