### ISSUE TITLE
Remove Tasks from app list in OwnCloud 8

### ISSUE THREAD

**Issue by koehn** [owncloud/core#14063]
Tasks 0.5 is incompatible with OC8 and shouldn't be included as an installable app until it's updated. 

https://github.com/owncloud/tasks/issues/132#issuecomment-73735887

**Comment by MorrisJobke** [comment]
cc @karlitschek

**Comment by raimund-schluessler** [comment]
For me the task app is not shown in an "installable app" list until I manually copy it to the apps folder. So where do you want to remove it from? If you copy it manually you can just use the latest master which works with oC8.

Maybe I am wrong and not aware of an automatism to show apps from the app store, but as the task app in the appstore currently doesnt have an ocsid (also because it is not yet compatible) it shouldn't be proposed to use, shouldn't it?

**Comment by koehn** [comment]
For me the Tasks 0.5 app showed up in the "Not Enabled" list. I enabled it and then discovered it didn't work.

**Comment by raimund-schluessler** [comment]
Did you upgrade from oC7 and was it installed there before?

**Comment by koehn** [comment]
Yes and no; it was installed in oc6 but disappeared when I upgraded to oc7.

**Comment by raimund-schluessler** [comment]
So it was still present on your filesystem?

**Comment by koehn** [comment]
I don't know. I had to `apt-get remove owncloud` in order to upgrade it to oc8; I don't know if there was an old tasks app there (how long has tasks 0.5 been available?).

**Comment by raimund-schluessler** [comment]
Tasks 0.5 has been available since 10 Nov 2014.

**Comment by karlitschek** [comment]
The tasks app is currently not "approved" in the appstore. So it can only show up in the list if someone manually put it into the apps folder. 
@raimund-schluessler Do you want to have admin rights to that you can approve the tasks app? This requires that it works seamlessly.

**Comment by raimund-schluessler** [comment]
Hm, I would like to see it been approved, but as this is my code, I am not sure, if I am the wright one to approve the app.

**Comment by karlitschek** [comment]
@raimund-schluessler Well. This is not really about reviewing your code. But more a level of trust so that you can publish the tasks app yourself. :-) You should noe be able to set the app to "approved" if you edit the app on apps.owncloud.com. The app will then showup on the apps pages of all owncloud. Please make sure that your set the required min and required max fields correctly.
Let me know if you have any questions.

**Comment by MorrisJobke** [comment]
This isn't an issue of the core nor of the packages -> close
