### ISSUE TITLE
addVendorScript is missing from OCP::Util

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#14111]
According to the [doc](http://doc.owncloud.org/server/8.0/developer_manual/app/init.html),  `appinfo/app.php` is still the location where apps can add scripts which will be used in the Files app.

Whereas templates can use `script` and `vendor_script`, this can only use `\OCP\Util::addScript`.

`addVendorScript()` should be added to `\OCP\Util`

**Comment by DeepDiver1975** [comment]
The reason for keeping addVendorScript out of OCP::Util was that we think vendor_script to be used in templates is enough. Let me know if this is not enough. THX

**Comment by oparoz** [comment]
Any app which needs to augment the Files app's GUI is likely to require 3rd party tools as they move away from their reliance on core OC JS functions.

Per example, Gallery+ needs to load at least one vendor script and there may be more needed in the future.

Using a standard "vendor" folder could help manage dependencies better in the future by not loading the same libs several times.

**Comment by DeepDiver1975** [comment]
understood - well in this case I'm willing to accept a PR to fix this. Thanks a lot!

**Comment by oparoz** [comment]
OK.
Just checking with @Raydiation and @PVince81 that this doesn't go against any forthcoming changes.

**Comment by rullzer** [comment]
@oparoz any progress on this? As it would help in #4774 as well

**Comment by oparoz** [comment]
I need to hear back from @Raydiation and @PVince81 because I know that nobody is happy with the way scripts are loaded in `appinfo/app.php` .
There is no point in introducing something which should not be used from my pov.

**Comment by Raydiation** [comment]
My take on this is that addVendorScript is basically not really useful. I'd try to contain it as best as possible and maybe deprecate it @MorrisJobke. There are two usescases: 

* Reusing core JavaScript vendor libraries
* Loading JavaScript libs from your appid/vendor directory

The first one should be highly discouraged since it ties apps to specific libs in core. An app should be self contained and also ship its own tested JS libs, otherwise we will get tons of breakage like we use to when we drop/upgrade a js lib in core.

The second one is kinda meh. The top vendor folder should in my opinion be reserved for php libs. If you take a look at any decent web framework, they all use a separate directory for js, css, images etc. Usually that folder is called static, public or assets. That way you can take very easily configure your webserver to only serve stuff from that directory and also mark the directory as non executable.

ownCloud apps use the top directory directly to store those assets in, like js, img and css which sometimes leads to purely cosmetic problems if you are using bundled js and css libs.

My current solution is to just drop the stuff into the js folder and use relative paths like **style('news', '../js/vendor/bootstrap/css/bootstrap.css')** or minify it into a single file using grunt cssmin

We could however easily modify the js, css and img loader to allow people to store things in an assets directory, like:

* appid/
 * appinfo/
 * assets/
   * js/
    * img/
    * css 

However this is really just a cosmetic change @DeepDiver1975

**Comment by PVince81** [comment]
Moving the discussion / potential API additions to 9.0
