### ISSUE TITLE
WebDAV access still slow with OC8

### ISSUE THREAD

**Issue by hostingnuggets** [owncloud/core#14140]
This is more of a generic and perduring issue but WebDAV access is still horribly slow with ownCloud8. Checking the web server's access log file shows that files are still accessed sequentially one after the other and if lucky  at a rate 1 or 2 files per second. As an example uncompressing a tar.gz file of 43 kByteswith 150 source code files takes like 2 minutes, this is insane. On the other hand copying one single big file is fine. I know this is not entirely ownCloud's fault but also the way the WebDAV protocol has been built. Nevertheless is it not possible for ownCloud to find some workaround to make WebDAV file access more responsive? At this stage it is simply useless and I wonder why you even bother enabling this feature.

For these tests I have used Mac OS X Finder as well as davfs2 and gvfs on Linux and on the same network (LAN). Mac OS X finder being the worst in terms of speed (no surprise here) and gvfs being the "fastest". I am using nginx 1.6, PHP-FPM 5.5, PostgreSQL 9.1 and Debian 7 on the server side. I also tried to add two more CPU cores, totaling to 4 cores on the server but this does not make any difference in terms of WebDAV speed. While doing file activity using WebDAV the php-fpm process uses only around 10-15% of CPU so the server is this is definitely not the bottleneck. It is also a standard install with the default nginx configuration file as documented in the official OC v8 documentation.

Any ideas or comments on how to improve this?

**Comment by shoeper** [comment]
Problem IMHO seem to be SQL queries. And I'm wondering why owncloud is still so slow. I've tried 5.0 when it was out and still same problems are there. The main features have not been improved enough but many new features have been implemented.
I'm a single user and restartet SQL Server after few small tweaks. After 5 hours I had about 2 million queries (Had to fix some FS permissions problems) with only 50k files (ok 2TB data - but 50k files isn't much).
On the other hand it seems like that client was improved enough, so that one doesn't loose data all time.

**Comment by LukasReschke** [comment]
We're aware of potential performance problems and will tackle them. With ownCloud 8.0 we improved the performance already quite a lot and with ownCloud 8.1 we will mainly concentrate on performance and see how we can improve this.

Closing this here since the issue tracker is used to track specific bugs and not for generic meta-issues. :smile:

**Comment by hostingnuggets** [comment]
Thanks Lukas for your feedback. May I stress the fact that this performance issue with WebDAV should really be set to high priority. Although many many people have written about this issue since now quite a few years, nothing noticeable has been undertaken. Instead of adding tons of new features which hardly any "normal" user or installation requires I would rather see improvements in the core of OC such as performance and stability. 

I am looking forward to test OC 8.1.

**Comment by shoeper** [comment]
@hostingnuggets that's also my impression.

**Comment by hostingnuggets** [comment]
@shoeper as well as many more owncloud users. A simple search for "owncloud webdav slow" shows that there are many frustrated owncloud users since many years. By the way you must be right regarding the SQL queries being a major performance hit as I read many forum posts also mentioning too many SQL queries for single file access. It gets even worse for files which are shared. So I am really impatient on seeing improvements in version 8.1.

**Comment by gentooza** [comment]
yeah!
I reported it a year ago, and I continue waiting xd [(issue 13795)](https://github.com/owncloud/core/issues/13795)

the worst is there is no questions, proposals, or work with the community as they simply close issues talking about future work solving the issue :-s (at least it's my impression)
it seems owncloud could be a more community friendly focused project

cheers
