### ISSUE TITLE
Owncloud says no space left

### ISSUE THREAD

**Issue by shoeper** [owncloud/core#14174]
### Expected behaviour
18GB storage are free (from a bit more than 2 TB) so everything should just work.

### Actual behaviour
Owncloud says no space left and it couldn't sync anymore (Ihr Speicher ist voll, daher können keine Dateien mehr aktualisiert oder synchronisiert werden!). Problem seems to be that owncloud just calculates how much percent of the space are used and 99.5% equal to hundret %.

### Server configuration
**Operating system:** Debian (Wheezy) 3.2.65-1+deb7u1 x86_64

**Web server:** Nginx 1.2.1

**Database:** 5.5.41-0+wheezy1

**PHP version:** PHP 5.4.36-0+deb7u3

**ownCloud version:** ownCloud 8.0 (stable)

**Updated from an older ownCloud or fresh install:** no

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 8.1

**Comment by PVince81** [comment]
@shoeper can you run this query:
`select * from oc_filecache fc, oc_storages s where fc.storage=s.numeric_id and path = 'files'` ?

ownCloud is using that size value to find out how full your storage is, maybe it is wrong.

**Comment by PVince81** [comment]
I assume you didn't set a quota in the users page ?

**Comment by shoeper** [comment]
Yep I didn't. String in CSV format:
`"94438","1","files","45b963397aa40d4a0063e0d85e4fe7a1","1","files","2","1","2229545583852","1424748271","1424123063","0","0","54ebeeef88d9f","31","home::Sven","1"`

**Comment by PVince81** [comment]
2229545583852/1024/1024/1024/1024=2,0277598958746 TB

So it looks like it believes that your storage is full.
Can you have a look at the subfolders and see if any might have a wrong value ?

Someone had a similar issue here https://github.com/owncloud/core/issues/14298
Unfortunately running `./occ files:scan --all` doesn't fix the sizes, so you might need to fiddle manually by touching files in those folders to retrigger size calculation.

**Comment by shoeper** [comment]
How does owncloud determine how much space I've got?

**Comment by PVince81** [comment]
If you didn't use a quota then it calls PHP's `disk_free_space()` and substract the size of your "files" folder (as per the DB query above)

**Comment by shoeper** [comment]
Does it call disk_free_space() only for data/ or for each users subfolder?

**Comment by PVince81** [comment]
It looks like it would call that function on the folder of a given file: https://github.com/owncloud/core/blob/master/lib/private/files/storage/local.php#L250

For a given user the path would be "/" which would either be the data dir itself or the subfolder. I'm not 100% sure. Does it make a difference in your setup ?

**Comment by shoeper** [comment]
Yes, my personal folder is a mount point and its subfolders contain also some mountpoints.

**Comment by PVince81** [comment]
Can you try running this: https://github.com/owncloud/core/issues/14732#issuecomment-77789946
Do you use LVM partitions ? (see linked ticket)

**Comment by shoeper** [comment]
Have commented on the other issue already. Works for me.
I'm using a ZFS pool.

**Comment by PVince81** [comment]
Ah yes, it was you. Cool, thanks :smile:

**Comment by reinhard089** [comment]
Hai,
i do have the same problem but your solution will not work for me.

the result from the select:
<pre>|      2 |       1 | files | 45b963397aa40d4a0063e0d85e4fe7a1 |      1 | files |        2 |        1 | 1602039219180 | 1442090564 |         0 |                0 | 55f48e4437f7d |    1434487549 |          31 | home::lochner      |          1 |</pre>
=> 1602039219180  ~ 1.5 TB

my df -h:
<pre>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        46G  3.4G   41G   8% /
udev            993M  4.0K  993M   1% /dev
tmpfs           201M  748K  200M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none           1002M   36M  967M   4% /run/shm
/dev/sdb1       1.8T  1.5T  248G  86% /DATA
/dev/sda1       224M   93M  119M  44% /boot
/dev/sda5       9.2G  3.8G  5.0G  44% /var
</pre>

shows the the /DATA is 1.8 TB large and just 1.5 TB used!
![screen1](https://cloud.githubusercontent.com/assets/1872805/9833698/58f163c0-59a1-11e5-8ed2-847e300ef7fd.PNG)
my "personal" page within owncloud tells me: "You have used 1.5 TB of the available 1.5 TB"
in my "users" page i used QUOTA for my user "2TB"

the /DATA is linked into the /var/www/owncloud/data/USER/files/

i've installed owncloud on a ubuntu 12.04, owncloud 8.1 (error since v6)

<pre> php -r "echo disk_free_space('/var/www/owncloud/data/USER/')/1024/1024/1024;"
4.9112091064453</pre>

does anyone know what to do?
