### ISSUE TITLE
Office can't handle pathnames with # in it (WebDAV).

### ISSUE THREAD

**Issue by HontoNoRoger** [owncloud/core#14212]
Hello!

Unfortunately the Microsoft Office products can't open files when there's a # somewhere in the path name.
It just reads the path till the # and thinks the rest is an URL anchor location, cutting the rest from the query.
Is there a workaround for this problem?

Tested with Office 2010 on both OwnCloud 7 and 8 while opening a file over WebDAV with a # in the path.

**Comment by DeepDiver1975** [comment]
hmmm - url encoding issue - @LukasReschke

**Comment by LukasReschke** [comment]
That is a won't fix for me. This is a known issue with Office 2010 and if we encode it here this will break other well-behaving clients.

According to the MS forums this will be fixed with 2013. Didn't test since I don't have any MS Windows Office.

Ref https://issues.alfresco.com/jira/browse/ACE-3646 and https://social.technet.microsoft.com/Forums/office/en-US/f692d36c-cf95-44c7-a1aa-8ab2f1913c3c/office-2010-hash-in-webdav-url?forum=officeitproprevious
