### ISSUE TITLE
It shows less GB than I have

### ISSUE THREAD

**Issue by carmilso** [owncloud/core#14269]
In the section "Personal" It shows how much memory you have spent and how much memory you have but instead of showing 32GB it shows 9.8GB and all data are being saved at an usb mounted at /media/owncloud

**Comment by enoch85** [comment]
@karlospv94 Are you the only user on the system, or do you have other users on your server as well?

**Comment by karlospv94** [comment]
There are two more users with 2 GB both of them

**Comment by enoch85** [comment]
@karlospv94 I have seen this behaviour before, and as an admin you see the space that's "left" for you. So, if you have i.e. 10 GB total on your server, and the other users are using 5 GB, you will only see 5 GB free space.

Could that be the issue here?

**Comment by karlospv94** [comment]
But the problem is that I really have 32 GB and the other two usera have only assigned 2 GB, so I would have 28 GB left. There're few files yet

**Comment by enoch85** [comment]
@karlospv94 Please use the issue template found here: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by karlitschek** [comment]
@PVince81 do you have an idea what the problem here might be?

**Comment by RealRancor** [comment]
Additionally to the issue template an output of:

``
df
``

entered into your console could be also useful.

**Comment by karlospv94** [comment]
### Steps to reproduce
1. Enter in section "Personal" being admin.
2. It shows: "You have used 12.2 MB of the available 9.8 GB". 
3. http://i.imgur.com/mpw16Ps.png

### Expected behaviour
It should show "You have used 12.2 MB of the available 32 GB"

### Actual behaviour
It shows I have 9.8 GB instead of 32 GB

### Server configuration
**Operating system**: Raspbian (Raspberry)

**Web server:**

**Database:** SQLite

**PHP version:** Apache 2

**ownCloud version:** (see ownCloud admin page) 8.0

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** Default apps

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'xxxxxxxxxxxxxxxxxxxx',
  ),
  'datadirectory' => '/media/owncloud/',
  'overwrite.cli.url' => 'https://xxxxxxxxxxxxxxxxxxxx',
  'dbtype' => 'sqlite3',
  'version' => '8.0.0.7',
  'installed' => true,
  'forceSSLforSubdomains' => true,
  'forcessl' => true,
);

```

**Are you using external storage, if yes which one:** yes: /media/owncloud

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu 14.04

### Logs
#### Web server error log
 Error 	PHP 	PHP Startup: Unable to load dynamic library '/usr/lib/php5/20100525+lfs/mysql.so' - /usr/lib/php5/20100525+lfs/mysql.so: cannot open shared object file: No such file or directory at Unknown#0 	2015-02-17T08:52:49+00:00 
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```




sudo fdisk -l:

Disk /dev/mmcblk0: 15.6 GB, 15560867840 bytes
4 heads, 16 sectors/track, 474880 cylinders, total 30392320 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x000c45c9

        Device Boot      Start         End      Blocks   Id  System
/dev/mmcblk0p1            8192      122879       57344    c  W95 FAT32 (LBA)
/dev/mmcblk0p2          122880    30392319    15134720   83  Linux

Disk /dev/sda: 31.5 GB, 31466323968 bytes
31 heads, 31 sectors/track, 63951 cylinders, total 61457664 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0xa7968933

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *        2048    61457663    30727808    7  HPFS/NTFS/exFAT



sudo df:

S. fitxers     1K-blocs   En ús  Lliures  %Ús Muntat a
rootfs         14831072 3923724 10254492  28% /
/dev/root      14831072 3923724 10254492  28% /
devtmpfs         242988       0   242988   0% /dev
tmpfs             49452     244    49208   1% /run
tmpfs              5120       0     5120   0% /run/lock
tmpfs             98900       0    98900   0% /run/shm
/dev/mmcblk0p1    57288   14720    42568  26% /boot

**Comment by PVince81** [comment]
@karlospv94 from df it looks like you only have 10254492 free space, which would be 10254492/1024/1024=9,7794456481934 (about 9.8 GB) free. This is the value that ownCloud reads.

Maybe this is a misunderstanding in the UI or a translation issue (if you're not using OC in English). 9.8 GB would be the free space, not total space.

**Comment by karlospv94** [comment]
Yeah. I suppose that It would let me to upload 32 GB if I tried but it's strange to being showing the free space in the SD instead of the USB

**Comment by rullzer** [comment]
@karlospv94 did you create that partition from scratch? Or did you extend it later on? Because it 14831072 / 1024 / 1024 = 14.1GB

Which is about right if you tell us that two other people are using 2GB each and some overhead.

So probably ownCloud reports the amount of free space correctly but you filesystem just does not occupy the whole partition.

**Comment by karlospv94** [comment]
I simply mounted the usb of 32GB at /media/owncloud and when I used ownCloud for the first time, I tried to write all data at this address. In fact, at index.php it shows "'datadirectory' => '/media/owncloud/',"

**Comment by PVince81** [comment]
@carmilso is this still happening with OC 8.2.2 ?

**Comment by enoch85** [comment]
@PVince81 Now the quota are "unlimited" or nothing instead (client). @carmilso Are you still experiencing this?
