### ISSUE TITLE
Permission to upload

### ISSUE THREAD

**Issue by biobeo** [owncloud/core#14352]
My 1TB server just got used. I bought a new 2TB Hard Disk yesterday. Now why should I do JBOD or RAID where I can just add external storage and point that new partition with ftp... It's a save of time and money. Thanks to OwnCloud Dev Team.

But Now I need an application which will only allow users to upload on the external storage instead of uploading on the main storage cause it's just few more gigs left. The Upload Permission option should be like this:

Allow users to upload on main storage -- Yes / No

Allow users to upload on external storage -- (List of external storage) check and un-check

**Comment by shoeper** [comment]
Don't think it is possible. If it is correct me, please.
I'd just move all data to the new drive.

Alternatively you could use ZFS. Create a pool on the new drive copy all data on it and afterwards add your old drive to the pool. But be warned drives aren'taren't too reliable. Even better would be another 2TB drive for raid 0
- if the data is at least a bit important.

**Comment by biobeo** [comment]
The risk is still the same for maximum users on earth who are using just one hard disk. If that fails data is lost. :)

**Comment by shoeper** [comment]
Sure, just wanted to mention that because many people learn it the hard way.
And raid 0 is of course no backup but it gives at least the chance to keep data after single drive failure.

To give you some more details relating ZFS. It is possible to add more drives to your pool later on without having to move old data. Furthermore ZFS has an internal integrity check and software raid 0. Only drawback I found out so far is that it has no mechanism to defragment your drive. But so far I can't tell you how important it would be.

**Comment by PVince81** [comment]
You can easily achieve this by having the admin mount the external storage only for themselves, then share the mount point with the users and remove the "can edit" permission. This even makes it possible to select which users have write access and who doesn't.

The same applies for the main storage.

**Comment by PVince81** [comment]
Closing as there is an alternative solution for this very specific scenario. No need for additional options for that.
