### ISSUE TITLE
Handlebars requires `eval`

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14404]
Needs research how we can integrate precompilation into our dev process: https://github.com/wycats/handlebars.js/blob/3133af2a210a15223f441d75aa795f3e44bab3dd/FAQ.md#L17
# Approach 1

Disable CSP when DEBUG mode is enabled and build the templates using Jenkins.

Pro:
- Not much changes for developers required

Contra:
- We're not testing the real deployment scenario, so CSP would be disabled and developers might do things that are forbidden with CSP which screws up on real live instances.
  - … however we might be able to configure JSHint and Scrutinizer to detect this.
# Approach 2

We tell the developers to execute Handlebars precompiler manually everytime they did a change.

Pro:
- No changes on CI environment required.

Contra:
- Needs to run `handlebars --extension=tmpl tags.tmpl -f tags.tmpl.js` before seeing the changes.
- Artifacts in GIT.
# … your approach …

**Comment by LukasReschke** [comment]
@Raydiation told me that we maybe could use grunt…

**Comment by MorrisJobke** [comment]
> @Raydiation told me that we maybe could use grunt…

Or Make or Bash or PHP ;)

**Comment by LukasReschke** [comment]
But that wouldn't be a fancy tool for web 3.0 hipster :(

**Comment by Raydiation** [comment]
Well, since we should probably also use it for JS development it just makes sense to also let it do that.

The News app watches js, templates and css https://github.com/owncloud/news/blob/master/js/Gruntfile.js#L125

If any file changes, the stuff is minimized and the page is then refreshed using live reload. How does that sound ;D?

**Comment by Raydiation** [comment]
You may want to run jshint for instance while developing

cc @PVince81

**Comment by DeepDiver1975** [comment]
> You may want to run jshint for instance while developing

not really - my IDE shows this inline ;-)

**Comment by DeepDiver1975** [comment]
bäääh - I really don't like to have build artifacts in git (minizied and generated stuff)

**Comment by Raydiation** [comment]
@DeepDiver1975 ok, another thing: what about wrapping your stuff in a function to not pollute the global namespace :D? http://markdalgleish.com/2011/03/self-executing-anonymous-functions/

Running Unittests on file save?

I doubt we can handle everything through the asset pipeline.

**Comment by LukasReschke** [comment]
Lets add some options in the top post for easier discussion later…

**Comment by PVince81** [comment]
I guess it might be possible to configure JSHint to detect uses of eval + Function (and scrutiinizer).
If we find a way to catch that early it might work ?

**Comment by LukasReschke** [comment]
Yes. That might indeed be a possibility. Remains the question how we handle the real life deployment scenario :see_no_evil:

**Comment by PVince81** [comment]
with proper QA ? :wink:

**Comment by LukasReschke** [comment]
I meant more like:

- How can Jenkins detect what needs to get compiled?
  - A possibility might be to say that all handlebar templates needs to be in "js/templates" and Jenkins then runs on that.
- We need to include the Handlebar templates in all outputs to ensure that nothing gets mixed up here (`<script src="js/templates/tagtemplates.js">`) 
- We need to use `Handlebars.template['tagtemplate']` instead of `Handlebars.compile($string)` in our JS. This means either a IF / ELSE block or some helper method for that?

**Comment by PVince81** [comment]
We can provide a helper method `OC.getTemplate(appName, templateName)` which will return the compiled template if available, or fallback to dynamic compiling.

**Comment by PVince81** [comment]
Also we need to consider that the templates are app-specific and also they must be themable (possibility to override the template source from a theme)

**Comment by DeepDiver1975** [comment]
> I doubt we can handle everything through the asset pipeline.

well - all I can say is: assetic has a processor for handlebar templates.

**Comment by PVince81** [comment]
Moving to 8.2.
Still need to find a good way how to include handlebars.

**Comment by PVince81** [comment]
Instead of grunt, we could just add a command `./occ build-templates`. Could be used by apps too if they choose to use it. (similar to the discussion regarding mimetypes here: https://github.com/owncloud/core/pull/16724#issuecomment-115204703

Regarding the asset pipeline, if it does support handlebars then it's nice. But from what I understand it's not enabled by default ?

**Comment by PVince81** [comment]
@LukasReschke Jenkins-compiled templates will not help with JS unit tests because the Karma running also needs to preload them before running the tests, which is only possible when precompiled.
(unless we make karma also precompile its own version of the templates as per solution 2 here https://github.com/owncloud/core/issues/12848#issuecomment-131152609)

Note, I added more stuff here: https://github.com/owncloud/core/issues/12848#issuecomment-131152609

**Comment by PVince81** [comment]
Still haven't found a good way to make Handlebars work with our project restrictions (no build scripts) and unit tests. Moving to 9.0

**Comment by PVince81** [comment]
Requires https://github.com/owncloud/core/issues/26006 to compile JS template thanks to the new Makefile

**Comment by PVince81** [comment]
and also needs porting all the existing handlebar templates to precompiled templates
