### ISSUE TITLE
share inside share

### ISSUE THREAD

**Issue by ckruetze** [owncloud/core#14428]
Shares inside of shares are confusing.

First I'm not sure if this is a bug or a feature request. Also this is most critical for the ownCloud client and for that I would call it a bug.

How to reproduce
Version 8 running on Ubuntu 14.04

Take the following folders

```
+ Products
| + International
| | - Product A
| | - Product B
| + Local
...
```

Product A is a folder with several GB of stuff in it.
Some users get to see everything, they are in a group that has the share "Products", other only have the share "International" or "Local" and a third group of users have access only to a share "Product A" for example. No problem up to now.

But now there are some users that are in several groups. And they suddenly have "Products" "International" and "Product A" as a share.

The problems
- ownCloud client run out of disk space since they suddenly store huge amounts of data 3 times.
- ownCloud client slow synchronisation waste of bandwidth (the same file gets copied 3 times)
- webDAV access, clients and web interface confusing layout. 3 ways to access one folder
- web interface slow and confusing search results (files listed 3 times)

I think shares inside other shares should be hidden if they have the same permissions.
Alternatively it could also be a global options, since there might be users who would actually want the same content multiple times.

**Comment by blizzz** [comment]
@schiesbn

**Comment by PVince81** [comment]
This is first a design issue. So far the current behavior is by design but I agree that it isn't convenient due to the waste of space.

The question is, whenever someone has access to multiple folders, how to choose the right one to keep and the ones to hide ?
Also, will it cause confusion for the users who share one of those folders explicitly (the ones that get hidden) and the recipient is wondering why it didn't appear ?

**Comment by PVince81** [comment]
CC @owncloud/designers

**Comment by PVince81** [comment]
also would be good to know what @MTRichards thinks

**Comment by MTRichards** [comment]
This would be where selective sync could help a lot. Of course, it is not perfect since it does require the user to un-select the duplicate files. Most people probably won't know to do that.

At some level, it would be good for the server to recognize the same ETags in a share, and thus not duplicate the files that are shared in yet another shared folder. This is similar to the problem we solved where a folder is shared to the same person 2 or 3 or 4 times, and the folder shows up duplicated. This we collapse down to one folder with the highest permissions.

I don't view this as a high priority item, but definitely a nice to have.

**Comment by PVince81** [comment]
Thanks @MTRichards.

There is another dimension, the first one is the permissions, but the second one is the "parent" relationship. So maybe the folder with the highest position in the hierarchy should be kept. If children are available too, hide them.

**Comment by MTRichards** [comment]
Yes, that would be a reasonable approach.  Also, something to consider, there may be a use case for duplicating the files, so a switch would be a good idea.

**Comment by ckruetze** [comment]
@PVince81 
> There is another dimension, the first one is the permissions, but the second one is the "parent" relationship. So maybe the folder with the highest position in the hierarchy should be kept. If children are available too, hide them.

This is a solution I would love. Since the user still has access to all data but less clutter.

Also this is more then a client problem. See the original message. It also confuses users in the Web Interface.
We actually had a situation where a file was found twice and the user thought to delete a "useless" copy since one was enough without realising that it is one file displayed in two shares.

**Comment by PVince81** [comment]
Some steps have been provided in another ticket to reproduce the permission conflict issue: https://github.com/owncloud/core/issues/13891#issue-56541349
