### ISSUE TITLE
Permissions Denied in MappedLocal.php

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14513]
@nickvergessen in the forum we already got 12 reports about this issue: https://forum.owncloud.org/viewtopic.php?f=31&t=26421&p=79700

The reports claim that replacing the oC 8 mappedlocal.php with the oC7 one everything will work, there is also some more technical debug stuff happening there.

Would be awesome if you could take a look at this. (might be a duplicate though this issue)

**Comment by nickvergessen** [comment]
Okay, the problem seems to be the files_locking app.

We can either:
1. Revert the `isLocal()` change in the MappedLocal, although I'd say that is the wrong way.
2. Do not add the wrapper, if the storage is **not** MappedLocal in https://github.com/owncloud/files_locking/blob/master/lib/lockingwrapper.php#L202 and officially unsupport it (check with the app dependencies, etc.
3. Waste more time and try to fix the locking on windows yet again :see_no_evil: 

Note: 1. is just a fake fix, and basically means we unsupport files locking on windows aswell, as it just ignores the locking wrapper then and never uses it.


In order to fix the problem in time for `8.0.1` I'd say 1. and 2. are the options to go.
Would be nice to get your opinion on that @DeepDiver1975
