### ISSUE TITLE
Moving existing data folder to a new location : official procedure ?

### ISSUE THREAD

**Issue by mhow2** [owncloud/core#14522]
What is the of official way of moving an existing OC data to another folder/path ?
I doesn't seems stated in the documentation... 
There is a FAQ entry in the forum : https://forum.owncloud.org/viewtopic.php?f=17&t=7118 but it doesn't speak about possible database issue.

And personally (but I'm not the only one) I got trouble with path stored in oc_storages tables after moving the data folder, I spent time on tweaking the database by hand (and it's always no advised to alter software database by hand...).

This is a common task of OC usage. Please could you clarify, either the FAQ or the documentation. Thanks.

**Comment by nickvergessen** [comment]
Official procedure for Windows: **NOT SUPPORTED** - since it would break the files mapper

**Comment by wshadow** [comment]
Had this issue a month ago when I moved my owncloud (7) to a new server. Since the absolute path(s) or md5 hashes thereof are stored in the DB I had to manually edit the database dump. So unless the relevant table and code got changed in owncloud 8 the official procedure for this is likely to be "NOT SUPPORTED" for any platform. But from experience I can tell that it is possible to do manually; just make sure to have a backup and some time to do the modifications without breaking stuff.

**Comment by PVince81** [comment]
Starting with OC 8 there is a repair step that converts the oc_filecache entries to the "home::" format, so the problem with absolute paths should disappear. From this version on you should be able to move the data directory in another location and just adjust config.php.

Maybe something could be added in the documentation @carlaschroder

**Comment by nickvergessen** [comment]
Nothing to do in core anymore + there is an issue in the doc repo => closing

**Comment by carlaschroder** [comment]
shiny new manual page, please review 
https://github.com/owncloud/documentation/pull/1588
