### ISSUE TITLE
Detect (unsupported?) ngx_pagespeed on NginX

### ISSUE THREAD

**Issue by ghost** [owncloud/core#14604]
Hi,

mod_pagespeed on Apache is not supported by ownCloud: https://github.com/owncloud/core/pull/6637 , https://github.com/owncloud/core/pull/6675
I'm not sure but the same is probably also valid for the ngx_pagespeed module on NginX.

**Comment by RealRancor** [comment]
The module can't be disabled from .htaccess like in Apache but it is adding the header:

``X-Page-Speed: 1.9.32.1-4238``

to all responses. Is this something which could be checked in ownCloud?

**Comment by Xenopathic** [comment]
I'd suggest we simply document this as unsupported, and leave it at that. An admin should know what web server modules they have enabled, and whether they conflict with the applications installed on their server. As far as mod_pagespeed for Apache, we only disable it in .htaccess, but don't explicitly check for anything. Since we don't provide any sort of default nginx configuration I think the best we can do is just a documentation note.

cc @carlaschroder

**Comment by RealRancor** [comment]
Documentation could be a first step. It won't catch users/admins which don't look at the docs but its a start.

Will create a PR for the documentation in the next few days.

Btw. we have a default NginX config at the docs.

**Comment by Xenopathic** [comment]
@RealRancor That sounds like a good plan.

By 'default', I mean a packaged configuration, aka like we have the .htaccess for Apache. We don't explicitly package an nginx configuration, and admins must look at the docs for it.

**Comment by karlitschek** [comment]
sounds good. But experience tells us that not everyone reads the documentation. So sometimes autodetection and warnings is also a good idea :-)

**Comment by RealRancor** [comment]
Ref for the documentation part: https://github.com/owncloud/documentation/pull/992

But from my experience i agree with @karlitschek that most of the users are just skipping the documentation.

**Comment by PVince81** [comment]
Move to 9.0?
