### ISSUE TITLE
limit log size

### ISSUE THREAD

**Issue by joernhees** [owncloud/core#14649]
as mentioned in #13953 8.0.0 has some issues with logging on shared webspace. In my case all free space was consumed by it.

maybe it would be useful if the log by default never exceeds let's say 10 MB?

**Comment by karlitschek** [comment]
already possible. Please see the option log_rotate_size in config.php

**Comment by joernhees** [comment]
doesn't seem to be a sane default then...

**Comment by joernhees** [comment]
@karlitschek please reopen this... I don't think logs should ever be able to grow to a size of 220 GB as reported by others in #13953 if you don't explicitly ask for unlimited sizes.

It's great that there is an ability to limit it, but this issue was more about sane defaults...

**Comment by karlitschek** [comment]
Well this specific problem with fast growing logfiles is addressed by the linked issues. In general ownCloud shouldn´t rotate logs by default because this can confuse external log handling tools. Just look at samba, apache, postfix and other tools. Internal log roation can be switch on as mentioned but this shouldn't be the default.
