### ISSUE TITLE
A new hackathon?

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#14678]
Hi all,

A few months ago ownCloud arranged a meet-up for people who wanted to help with solving bugs. That was a great iniative, and if I remeber correct, the bug count dropped with several hundreds.

I have noticed the last couple of weeks (especially after the ownCloud 8
release) that the issue count is close to stunning 1700 bugs!

As I see it there are two ways to solve this:
1. Hire(?) more devs to be able to take care of all the issue reports that people contribute with. This will be needed anyway in the future, because more users means more reported issues.
2. Arrange a new meet-up and invite everyone who wants to come and spend a weekend to solve bugs, and close issue that are not relevant anymore.

The issue count should decrease instead of growing as ownCloud become more and more stable. Don't you think?

So, what should we do about it?

**Comment by strehlst** [comment]
Guten Tag,
ich bin bis zum 5. März nicht per E-Mail erreichbar.

Freundliche Grüße
Steven Strehl

**Comment by karlitschek** [comment]
Good point. @jospoortvliet @DeepDiver1975  Should we arrange a new bug closing event?

**Comment by jancborchardt** [comment]
While I agree on this, please never ever use the @ owncloud/developer handle! It mentions about 250 people and sends each an email for every new reply.

Meanwhile, everyone of us can go through the [least recently updated issues](https://github.com/owncloud/core/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc) and look for outdated ones, closing them. I prepared a [canned reply](https://gist.github.com/jancborchardt/6155185#clean-up-inactive-issues) for that as well.

**Comment by enoch85** [comment]
@jancborchardt Sorry, not a member of the mailing-list and I thought that this was the best way to reach out to people. 

@karlitschek Will ownCloud hire more devs in the nearby future?

**Comment by karlitschek** [comment]
Let´s close this because this spams too many people :-)
Can we move this to the mailinglist?
Yes. We try to hire more developers :-)

**Comment by DeepDiver1975** [comment]
> I have noticed the last couple of weeks (especially after the ownCloud 8
> release) that the issue count is close to stunning 1700 bugs!

Well - to be precise: 1700 issues

620 of them are enhancements, ideas on how to improve core or ideas on new apps - https://github.com/owncloud/core/labels/Enhancement - this number will constantly grow

817 might be bugs - https://github.com/owncloud/core/labels/bug :

81 are in the status of 'needs-info' where we try to help users with their issues - but more input is required - https://github.com/owncloud/core/labels/needs%20info

95 bugs have been put to the backlog because they are really no that critical - https://github.com/owncloud/core/issues?q=is%3Aopen+label%3Abug+milestone%3Abacklog

124 are technical dept - areas where we devs want to improve the code base - https://github.com/owncloud/core/labels/technical%20debt

Yes the bug count will increase and looking at this only can be frustrating.

Looking at the pulse is the way to go - as long as we close more bugs and pull request then being opened: we do it right - https://github.com/owncloud/core/pulse/monthly

**Comment by enoch85** [comment]
@DeepDiver1975 Thanks for that perspective.

@karlitschek Would be nice if we could move it to the mailing-list, yes. :)

**Comment by Stoyicker** [comment]
@karlitschek Just to confirm, which mailing list has this been moved to?

**Comment by karlitschek** [comment]
Non so far as I know of. I suggest that someone posts this to https://mailman.owncloud.org/mailman/listinfo/devel

**Comment by enoch85** [comment]
@karlitschek @Stoyicker I tried to post it but it got hold up for review because I´m not a member of the devel mailinglist.

**Comment by jospoortvliet** [comment]
So I mailed ;-)
