### ISSUE TITLE
[OC6.0.4] data cache directory needs to be cleaned up

### ISSUE THREAD

**Issue by gig13** [owncloud/core#14718]
**Expected behavior**
The owncloud server data directory will not grow out of control for users.

**Actual behavior**
The cache directory for a user is 2.7 TB, while the actual files directory is only 31 GB.

**Steps to reproduce**
Trying to reproduce with stable 6.0.4

**Server Configuration**
OC6.0.4
Red Hat 6.6

@MorrisJobke

**Comment by MorrisJobke** [comment]
cc @icewind1991 For what is this cache dir used? Only thumbnails?

**Comment by PVince81** [comment]
The $datadir/$user/cache folder is used for chunks. There is GC code already but needs to be put into a cron/background job: #14646 

@gig13 is that the folder you were talking about ?

**Comment by PVince81** [comment]
If that "cache" folder gets full it means there are a lot of aborted uploads, maybe something to look into.

**Comment by gig13** [comment]
@PVince81 @MorrisJobke 
Yes, the $datadir/$user/cache folder is overloaded with thousands of files.
Can i manually delete all of the files under the cache directory for that user? Are there only certain files that I can delete?

php version
/opt/rh/php54/root/usr/bin/php -v PHP 5.4.16 (cli) (built: Feb  4 2014 08:10:51) Copyright (c) 1997-2013 The PHP Group Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

Database type and version
[root@llowncloud mysql]# rpm -q mysql
mysql-5.1.73-3.el6_5.x86_64

**Comment by PVince81** [comment]
These files are usually only temporary. They are chunked file (the word "chunk" is used in their names) and are used during uploads. If an upload has aborted, they will usually stay.

Currently in OC 6 the logic is that they get cleant the next time the user logs in. But if the user NEVER logs in (because of session cookies / keepalive) then the cleaning code will never be run.

If you decide to delete all the files there is a slight risk that it will break currently running upload jobs.
What you can do is find all chunk files that are older than a day or so and delete them. (a cron job could be made with such command)

In the future that cleanup should be cleant up by OC background jobs.

**Comment by gig13** [comment]
@PVince81 
Thanks for the feedback. Directory clean out commencing!

**Comment by PVince81** [comment]
Closed as duplicate of https://github.com/owncloud/core/issues/14646
