### ISSUE TITLE
File handling in admin: Also write to .user.ini

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#14748]
Hi,

it seems that the "file handling" input box in the admin backend to set a specific upload size is currently only writing to the .htaccess file: https://github.com/owncloud/core/blob/v8.0.0/lib/private/files.php#L217-L273

As newer OC versions are also shipping a .user.ini for other environments like fcgi the function probably could be extended to also write to this file.

**Comment by shoeper** [comment]
I'd also recommend to set 1MB larger value for max post size than for max upload size. When both have the same values uploading a file with the exact value will fail because the headers also need some bytes.

Furthermore a warning stating that it can take up to user_ini.cache_ttl seconds till the new value is taking effect, when user ini is used would be nice.
