### ISSUE TITLE
update available message overshadows app controls

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/core#14811]
The yellow "update is available..." in the top of the screen overlaps the controls space given to the Documents app.
Screenshot:
![image](https://cloud.githubusercontent.com/assets/639487/6602773/19645286-c81e-11e4-9e5f-48a1ab77dcce.png)

**Comment by MorrisJobke** [comment]
cc @VicDeo @jancborchardt

**Comment by deMattin** [comment]
Is there a way to deactivate this notification?
It might be ok, that it comes up but now I know it and if I don't want to upgrade (now), I don't need this any more and it's only in the way.
In my case it's not neccessary at all because I only update from the suse repo.

An enhancement could be, that this notification would go away itself after lets say 20 seconds.

**Comment by MorrisJobke** [comment]
This can be used for the temporary show: https://github.com/owncloud/core/blob/f668ed25fe2997f54085982352df36630a4e1efa/core/js/js.js#L800

Maybe @Xenopathic or @rullzer want to have a look at this :)

**Comment by jancborchardt** [comment]
@rullzer @Xenopathic any updates here? Would be cool to only show the update notification temporarily.

**Comment by jancborchardt** [comment]
Probably even good as polish for 8.1

**Comment by MorrisJobke** [comment]
Fix is in #16017
