### ISSUE TITLE
"-1B" Size Reported in Total Directory Size

### ISSUE THREAD

**Issue by mwhohmann** [owncloud/core#14853]
![sreen](https://cloud.githubusercontent.com/assets/11449486/6630751/de598960-c8f2-11e4-8643-c82943c19b2d.png)
SMB/CIFS Connections newly created are still counting size, notated as, "Pending."  Here we have two connections, one to an empty directory, and one to a very large directory.  The total between the two is being reported as "-1B" or -1 Bytes.

My proposed fix...

IF any directory is still calculating size, report "Pending" as the sum at the bottom.  Could also fail back to Zero.

**Comment by karlitschek** [comment]
@PVince81 what do you think?

**Comment by PVince81** [comment]
@mwhohmann what version of ownCloud are you using ?

**Comment by mwhohmann** [comment]
@PVince81 This is 8.0.2.0

**Comment by PVince81** [comment]
It says -1 because the value of "Pending" is actually the size "-1".
The bug here is that the value should be removed from the total calculation.

Another idea, to combine with your suggestion, would be to show the actual size (without -1) but add "(pending)" behind it.

For example: "12 MB (pending)" instead.

**Comment by PVince81** [comment]
The calculation is done in this class: https://github.com/owncloud/core/blob/master/apps/files/js/filesummary.js#L101

Tagging as junior job as it shouldn't be too hard to make the change.

**Comment by MorrisJobke** [comment]
Fix is in #15254
