### ISSUE TITLE
SQLSTATE[HY000]: General error: 5 cannot rollback transaction - SQL statements in progress

### ISSUE THREAD

**Issue by feschi55** [owncloud/core#14911]
and now?

**Comment by Zotzi** [comment]
Gleicher Fehler - same error, need help...

Aktualisiere ownCloud auf Version 8.0.2. Dies könnte eine Weile dauern.
Wartungsmodus eingeschaltet
Datenbank-Schemenaktualisierung geprüft
Datenbank-Schemenaktualisierung für Apps geprüft
Datenbank aktualisiert
SQLSTATE[HY000]: General error: 5 cannot rollback transaction - SQL statements in progress

**Comment by ollyphobie** [comment]
Ich auch - Me too

- SQLSTATE[HY000]: General error: 5 cannot rollback transaction - SQL statements in progress

**Comment by PVince81** [comment]
Please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by ollyphobie** [comment]
?? didn't understand what i should do with this?
Verstehe nicht?

**Comment by ollyphobie** [comment]
Sorry! I don't know what i should do with this???? No plan how open an *.md file.
I still wanted to update from 7 to 8 automaticly in your update center. And suddenly this. 

Aktualisiere ownCloud auf Version 8.0.2. Dies könnte eine Weile dauern.
Wartungsmodus eingeschaltet
Datenbank-Schemenaktualisierung geprüft
Datenbank-Schemenaktualisierung für Apps geprüft
Datenbank aktualisiert
SQLSTATE[HY000]: General error: 5 cannot rollback transaction - SQL statements in progress


And now - nothing works
Pleas help

Am 16.03.2015 um 10:51 schrieb Vincent Petry <notifications@github.com>:

**Comment by PVince81** [comment]
Just open this file in your web browser: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
Copy paste the text into a github comment and fill in the fields.
(die Datei einfach im Web-Browser öffnen, den Inhalt kopieren und in einen Github-Kommentar einfügen, dann die Felder ausfüllen)

Since you are three people having the issue, if at least two of you would provide the info it would be enough.

So this happens during an update ?

**Comment by ollyphobie** [comment]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
try to update over update center from V.7.0.4.2 to V8.0.2

### Actual behaviour
Aktualisiere ownCloud auf Version 8.0.2. Dies könnte eine Weile dauern.
Wartungsmodus eingeschaltet
Datenbank-Schemenaktualisierung geprüft
Datenbank-Schemenaktualisierung für Apps geprüft
Datenbank aktualisiert
SQLSTATE[HY000]: General error: 5 cannot rollback transaction - SQL statements in progress


### Server configuration
**Operating system**:

**Web server:** 

**Database:** MSQL

**PHP version:** 5.5

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:** update from V.7.0.4.2 to V8.0.2

**List of activated apps:** 

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
<?php
$CONFIG = array (
  'instanceid' =>'' ,
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'ofdcloud.de',
    1 => 'www.ofdcloud.de',
  ),
  'datadirectory' => '/home/www/web25/html/owncloud/data',
  'overwrite.cli.url' => 'https://ofdcloud.de/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'mail@ofd-websitestory.de',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'ofd-websitestory.de',
  'theme' => '',
  'maintenance' => false,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
run: sqlite3 data/owncloud.db
then execute:  select * from oc_appconfig where appid='user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Chrome 41.0.2272.89 (64-bit), Firefox


**Operating system:** OSX 10.9.5

### Logs
#### Web server error log
SQLSTATE[HY000]: General error: 5 cannot rollback transaction - SQL statements in progress
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
{"reqId":"8b2ebc9ce1d2949be169d96e252f32d0","remoteAddr":"82.212.58.36","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1230","level":3,"time":"2015-03-16T10:31:39+00:00"}
{"reqId":"8b2ebc9ce1d2949be169d96e252f32d0","remoteAddr":"82.212.58.36","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1233","level":3,"time":"2015-03-16T10:31:39+00:00"}
{"reqId":"c43cf537a791724895cb9532694dc6db","remoteAddr":"82.212.58.36","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1230","level":3,"time":"2015-03-16T11:45:20+00:00"}
{"reqId":"c43cf537a791724895cb9532694dc6db","remoteAddr":"82.212.58.36","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1233","level":3,"time":"2015-03-16T11:45:20+00:00"}
{"reqId":"6b8df75b3f03040777d1e7b581fe696e","remoteAddr":"82.212.58.36","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1230","level":3,"time":"2015-03-16T11:45:25+00:00"}
{"reqId":"6b8df75b3f03040777d1e7b581fe696e","remoteAddr":"82.212.58.36","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1233","level":3,"time":"2015-03-16T11:45:25+00:00"}
{"reqId":"89c6420e5762fe543021dd9d49c9c592","remoteAddr":"82.212.58.36","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1230","level":3,"time":"2015-03-16T11:48:49+00:00"}
{"reqId":"89c6420e5762fe543021dd9d49c9c592","remoteAddr":"82.212.58.36","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1233","level":3,"time":"2015-03-16T11:48:49+00:00"}
{"reqId":"704cae19780512cdfdbf72139c356bb2","remoteAddr":"82.212.58.36","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1230","level":3,"time":"2015-03-16T11:49:29+00:00"}
{"reqId":"704cae19780512cdfdbf72139c356bb2","remoteAddr":"82.212.58.36","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1233","level":3,"time":"2015-03-16T11:49:29+00:00"}
{"reqId":"aaca20cd4d9a396dfd80cf3d670afbb0","remoteAddr":"82.212.58.36","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1230","level":3,"time":"2015-03-16T11:53:32+00:00"}
{"reqId":"aaca20cd4d9a396dfd80cf3d670afbb0","remoteAddr":"82.212.58.36","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1233","level":3,"time":"2015-03-16T11:53:32+00:00"}
{"reqId":"3631fe5084e09818af3750a04a19c4f9","remoteAddr":"82.212.58.36","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1230","level":3,"time":"2015-03-16T12:01:30+00:00"}
{"reqId":"3631fe5084e09818af3750a04a19c4f9","remoteAddr":"82.212.58.36","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1233","level":3,"time":"2015-03-16T12:01:30+00:00"}
{"reqId":"04e52c8dcb1ac34d4f3279b97d1e3533","remoteAddr":"82.212.58.36","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1230","level":3,"time":"2015-03-16T12:01:47+00:00"}
{"reqId":"04e52c8dcb1ac34d4f3279b97d1e3533","remoteAddr":"82.212.58.36","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1233","level":3,"time":"2015-03-16T12:01:47+00:00"}
{"reqId":"a9b89cb18f86ec7f1bde4aabbec99932","remoteAddr":"82.212.58.36","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1230","level":3,"time":"2015-03-16T12:02:16+00:00"}
{"reqId":"a9b89cb18f86ec7f1bde4aabbec99932","remoteAddr":"82.212.58.36","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1233","level":3,"time":"2015-03-16T12:02:16+00:00"}
{"reqId":"faf8b539eef410202acf55148c873a86","remoteAddr":"82.212.58.36","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1230","level":3,"time":"2015-03-16T12:13:30+00:00"}
{"reqId":"faf8b539eef410202acf55148c873a86","remoteAddr":"82.212.58.36","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/www\/web25\/html\/owncloud\/lib\/private\/app.php#1233","level":3,"time":"2015-03-16T12:13:30+00:00"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Hmmmm, that error in your log seem to be related to an app that might be missing a description, possibly a third party app. The code in question is here: https://github.com/owncloud/core/blob/stable8/lib/private/app.php#L1230

Do you mind posting the list of enabled apps ?
You can retrieve it using the command `sudo -uwwwrun ./occ app:list` (replace "wwwrun" with the name of the web server user)

The database upgrade issue could also be caused by third party apps, so it would be good to know if you guys have the same enabled apps.

**Comment by joschal** [comment]
I suffer from the same bug. Neither an upgrade to v8.0.2 nor v8.0 works. I have no third party apps installed.
I'm on a shared linux hoster, so I can't shut down the web server while upgrading. Might the problem be caused by that? As far as i can recall upgrades to v6.0 and v7.0 worked just fine.

**Comment by ollyphobie** [comment]
if have also no third party apps installed. 
So, please - how can i get forward or back to the backup version???????? I have no time to look hours and hours for that stuff. It calls an UPDATE CENTER. So , please it's your turn that the upgrade will be work fine. Or give me SIMPLE ORDER what can i do. Step by Step. Thank you.

**Comment by Zotzi** [comment]
Gibt es schon eine Lösung zu dem Problem? Gerne auch eine Erklärung wie ich wieder zum alten Stand zurück komme...

**Comment by PVince81** [comment]
Before the problem can be fixed, it needs to be understood and reproducible.

It would be useful if @Zotzi, @joschal and @feschi55 would also post their owncloud.log (and environment) so we can see if it's the same error as @ollyphobie and hopefully find a way to reproduce it. Also tell us how you upgraded. Did you: Manually replace the code ? Use the updater app in the admin settings ? Update from RPM/DEBs ?

We can only tell you how to roll back to the previous state if you tell us more about your environment (as requested by the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md)

**Comment by ollyphobie** [comment]
Hey! I updated by the updater app in the admin settings. 
Greats. 

schauspieler & sänger
Oliver Fobe-Dörr

Kriegsstr.146 
76133 Karlsruhe

Fon:	+49 (0)176 608 147 80
Web	:www.ofobe.de
Mail:	webmaster@ofobe.de



> Am 18.03.2015 um 13:35 schrieb Vincent Petry <notifications@github.com>:
> 
> updater app in the admin settings

**Comment by viper1vip** [comment]
Hi, did you find the solution of the problem?
I also try today the updata of owncloud and after few minutes the communication show up:
SQLSTATE[HY000]: General error: 5 cannot rollback transaction - SQL statements in progress

**Comment by PVince81** [comment]
Unfortunately no, cannot reproduce the issue. Need more details/clues about the environment/setup in which this happens. If everybody could use the issue template we might be able to find what you all have in common.

Also important: whether you're using MySQL or MariaDB (there are differences)

**Comment by viper1vip** [comment]
How to back to the previous version without loosing data and configurayion - using manually updata?

**Comment by PVince81** [comment]
Restore your backup of the database and the "data" and "config" directories. And delete the other directories and replace them with the code from the previous ownCloud version.
Downgrading is not supported.

Before you do, can you check/post your "oc_storages" table ?
There aren't many places in the code that use transactions, but one of them is the legacy storage repair.

**Comment by viper1vip** [comment]
I just update my PHP from 5.4.28 to 5.5.23 version and reload the login page ow OC and after I click instal updata od OC I received this communication:
Could not automatically fix legacy storage "local::/home/admin/domains/XXXXXX.pl/public_html/site/owncloud/data/user/" => "home::user" because they both have data.

So it looks like changing PHP I solve the problem but now I do not really understand this message?

**Comment by viper1vip** [comment]
How to manually delete the bogus "local::$olddatadir/$user" entry ? I mean where can I find this entry? I mean somewhere on server where is located the OC or in the mysql database?

**Comment by joschal** [comment]
### Steps to reproduce
Upgrade from v7.0.4 to v8.0/v8.0.2 by replacing everything in he owncloud-directory but /data and the config file

### Actual behaviour
Same error message as everyone
```SQLSTATE[HY000]: General error: 5 cannot rollback transaction - SQL statements in progress```

### Server configuration
I'm on a shared host, so I just have limited rights. I can't control the web server.
**Operating system**: CentOS

**Web server:** Apache/2.2.15

**Database:** SQLite

**PHP version:** 5.5.5

**ownCloud version:** 7.0.4

**Updated from an older ownCloud or fresh install:** Updated since 5.x

**List of activated apps:** none

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xx',
  'passwordsalt' => 'xx',
  'datadirectory' => '/var/www/.../html/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'forcessl' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'www....de',
  ),
  'secret' => 'xx',
);
```

**Are you using encryption:** no


### Client configuration
Safari 8.0.4
ownCloud for iOS 3.4.0

### Logs

#### ownCloud log (data/owncloud.log)
```
{"app":"core","message":"Login failed: user xx , wrong password, IP:set log_authfailip=tr$
{"app":"core","message":"Login failed: user xx , wrong password, IP:set log_authfailip=tr$
{"app":"core","message":"Login failed: user xx , wrong password, IP:set log_authfailip=tr$
{"app":"core","message":"Login failed: user xx , wrong password, IP:set log_authfailip=tr$
{"app":"core","message":"Login failed: user xx , wrong password, IP:set log_authfailip=tr$
{"app":"core","message":"Login failed: user xx , wrong password, IP:set log_authfailip=tr$
{"app":"core","message":"Login failed: user xx , wrong password, IP:set log_authfailip=tr$
{"app":"core","message":"Login failed: user xx , wrong password, IP:set log_authfailip=tr$
{"app":"core","message":"Login failed: user xx , wrong password, IP:set log_authfailip=tr$
{"app":"PHP","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 43200 b$
{"app":"PHP","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 43200 b$
{"app":"core","message":"Login failed: user 'xx' , wrong password, IP:set log_authfailip=tru$
{"app":"core","message":"Login failed: user 'xx' , wrong password, IP:set log_authfailip=tru$
{"app":"core","message":"Login failed: user xx , wrong password, IP:set log_authfailip=tr$
{"app":"core","message":"Login failed: user xx , wrong password, IP:set log_authfailip=tr$
{"app":"PHP","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 43200 b$
{"app":"core","message":"Login failed: user 'xx' , wrong password, IP:set log_authfailip=true $
{"app":"core","message":"Login failed: user 'xx' , wrong password, IP:set log_authfailip=true $
{"app":"core","message":"Login failed: user 'xx' , wrong password, IP:set log_authfailip=tru$
{"app":"PHP","message":"filemtime(): stat failed for \/var\/www\/virtual\/xx\/html\/owncloud\/da$
{"app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>$
{"app":"index","message":"Exception: Kontakt nicht gefunden [404]","level":4,"time":"2014-02-16T21:$
{"app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>$
{"app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>$
{"app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>$
{"app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>$
{"app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>$
{"app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>$
{"app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>$
{"app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>$
{"app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>$
{"app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>$
{"app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>$
{"app":"updater","message":"Something went wrong for apps. Rolling back.","level":3,"time":"2014-02$
{"app":"updater","message":"Unable to move \/var\/www\/virtual\/xx\/html\/owncloud\/data\/update$
{"app":"PHP","message":"Array to string conversion at \/var\/www\/virtual\/xx\/html\/owncloud\/a$
{"app":"PHP","message":"Array to string conversion at \/var\/www\/virtual\/xx\/html\/owncloud\/a$
{"app":"PHP","message":"Array to string conversion at \/var\/www\/virtual\/xx\/html\/owncloud\/a$
{"app":"PHP","message":"Array to string conversion at \/var\/www\/virtual\/xx\/html\/owncloud\/a$
{"app":"PHP","message":"Array to string conversion at \/var\/www\/virtual\/xx\/html\/owncloud\/a$
{"app":"Encryption library","message":"Could not get migration status for xx, no record found$
{"app":"Encryption library","message":"symmetrically encryption failed, no content given.","level":$
{"app":"Encryption library","message":"private key exists but public key is missing for \"xx\$
```

**Comment by PVince81** [comment]
@joschal thanks for the details. In your case I see some memory issues. Are you able to increase the allowed memory size for PHP ? (this could cause unpredictable side effects)

Also I see "Something went wrong for apps." which seems to be from the updater app @VicDeo

**Comment by joschal** [comment]
The PHP  memory limit is set to 128M.
I didn't use the updater app to the time of the logfile above. I just tried it, and it didn't work either.

**Comment by VicDeo** [comment]
I guess this is MySQL and not Updater specific.

## If you come to this issue from google
**Please post exact DB type and version.**
Please *do NOT post* another mindless +1, it is completely useless.

**Comment by joschal** [comment]
I use SQLite3.

**Comment by VicDeo** [comment]
mmm... 
@joschal are you able to execute sql queries on your db?

**Comment by ollyphobie** [comment]
I have canceled all and installed new 8.0.2.

Ready


Am 24.03.2015 um 15:30 schrieb VicDeo <notifications@github.com>:

**Comment by Alienmaster** [comment]
### Steps to reproduce
1. install owncloud 6.0 on an QNAP TS-669 Pro owncloud via Appstore
2. solve the problems to make the update happen (change one fileprivilegs)
3. update PHP 5.2 to PHP 5.5.21 via Appstore
4. try to update version 7.0.4 to 8.0.2 -> error

### Expected behaviour
Update progress

### Actual behaviour
Wartungsmodus eingeschaltet 
Aktualisierung des Datenbankschemas wurde überprüft
Aktualisierung des Datenbankschemas für Apps wurde überprüft
Datenbank aktualisiert
SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress

### Server configuration
**Operating system**: QNAP Firmware 4.1.3

**Web server:** Apache 2.2x

**Database:** sqlite3

**PHP version:** 5.5.21

**ownCloud version:** now 8.0.2

**Updated from an older ownCloud or fresh install:** update

**List of activated apps:** none (as i know)

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc7e22e11f11',
  'passwordsalt' => '123',
  'trusted_domains' => 
  array (
    0 => '192.168.0.111',
  ),
  'datadirectory' => '/share/MD0_DATA/.qpkg/owncloud/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => '123',
);

**Are you using external storage, if yes which one:** nope

**Are you using encryption:** SSL

**Are you using an external user-backend, if yes which one:** nope

### Client configuration
**Browser:** Chrome

**Operating system:** 7 x64

### Logs

#### ownCloud log (data/owncloud.log)
{"reqId":"ab5a088a094c1c58fe44f33df98e33ea","remoteAddr":"192.168.0.60","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/share\/MD0_DATA\/.qpkg\/owncloud\/owncloud\/lib\/private\/app.php#1230","level":3,"time":"2015-03-31T07:46:29+00:00"}
{"reqId":"ab5a088a094c1c58fe44f33df98e33ea","remoteAddr":"192.168.0.60","app":"PHP","message":"Invalid argument supplied for foreach() at \/share\/MD0_DATA\/.qpkg\/owncloud\/owncloud\/lib\/private\/app.php#1233","level":3,"time":"2015-03-31T07:46:29+00:00"}

**Comment by joschal** [comment]
@VicDeo No, I can't.

**Comment by KPrinz** [comment]
Hi, I have the exact same issue as Alienmaster!

Qnap 4.1.3 (Intel) with PHP 5.5.21 qpkg
Coming from 7.0.4 to 8.0.2 using online updater

<?php
$CONFIG = array (
  'instanceid' => '*',
  'passwordsalt' => '*',
  'trusted_domains' => 
  array (
    0 => '*HOSTNAME*',
    1 => '*IP*',
  ),
  'overwritewebroot' => '/owncloud',
  'datadirectory' => '/share/CACHEDEV1_DATA/.qpkg/owncloud/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'forcessl' => false,
  'theme' => '',
  'maintenance' => false,
  'secret' => '*',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'domain.tld',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'owncloud',
  'mail_smtppassword' => '*',
  'mail_smtphost' => '10.0.2.1',
  'mail_smtpport' => '587',
  'ldapIgnoreNamingRules' => false,
);


Logs

ownCloud log (data/owncloud.log)

{"reqId":"2f66eb81f60e6bed687fec344c9eff8a","remoteAddr":"10.0.2.xx","host":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/share\/CACHEDEV1_DATA\/.qpkg\/owncloud\/owncloud\/lib\/private\/app.php#1230","level":3,"time":"2015-04-10T10:54:32+00:00"}
{"reqId":"2f66eb81f60e6bed687fec344c9eff8a","remoteAddr":"10.0.2.xx","host":"PHP","message":"Invalid argument supplied for foreach() at \/share\/CACHEDEV1_DATA\/.qpkg\/owncloud\/owncloud\/lib\/private\/app.php#1233","level":3,"time":"2015-04-10T10:54:32+00:00"}

**Comment by KPrinz** [comment]
#14398 seems to be the same issue. 
If anyone needs some SQL queries run on the db, I'll volunteer.

**Comment by VicDeo** [comment]
@KPrinz according to your log, files were not replaced properly. Please manually replace everything except `config`, `data` and `theme` directories with files from OC8 package https://download.owncloud.org/community/owncloud-8.0.2.tar.bz2

**Comment by VicDeo** [comment]
@KPrinz after that please post a result for this query: `SELECT appid FROM oc_appconfig WHERE configkey='enabled' AND  configvalue='yes';`

**Comment by KPrinz** [comment]
@VicDeo , replaced all files as requested, ran SQL, here is the result:
appid
files_videoviewer
contacts
files_pdfviewer
updater
gallery
activity
files_trashbin
files_texteditor
files_sharing
search_lucene
files_versions
calendar
files
firstrunwizard
documents

**Comment by KPrinz** [comment]
currently, after QNAP FW upgrade I get a maintenance page. owncloud has stopped logging

**Comment by manaaaaa** [comment]
i Had the same Problems.

I fixed it myway : 

i installed it directly with this instructions :
http://wiki.qnap.com/wiki/Category:OwnCloud

**Comment by joschal** [comment]
Might there be a solution to the problem or do i have to start a completely new ownCloud instance and transfer all my data manualy to the new one?

**Comment by palto42** [comment]
Just tried with the new version 8.0.3 but get the same SQL error message as reported above. I'm using Owncloud on a Qnap TS-212 firmware version 4.1.3 with PHP 5.5.21

**Comment by KPrinz** [comment]
Updating ownCloud to version 8.0.3, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress

**Comment by palto42** [comment]
Next trial, still no success :(
First I successfully upgraded to OC 7.0.6
Then I upgraded to OC 8.0.4 and got the same error again:
SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress

**Comment by PVince81** [comment]
Are you still seeing this in 8.2.2 or 9.0 RC1 ?

Please reopen if you do. Thanks.
