### ISSUE TITLE
[Suggestion] When deleting user accounts, add a confirmation dialog (prompt) - or amend the tooltip

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/core#14945]
As an admin, when I delete a user account, I wish to have a prompt "Do you really want to delete that user?" 

I do know when having successfully used the "delete user" funtion, that the last action could be reversed (made undone) afterwards, but the warning could be overlooked, and the "undo" message is not known before you actually press the delete user (basket icon) button.

So perhaps it may be wise, either to show a prompt dialog "Do you really want to delete that user?" or to amend the tooltip which is shown on the delete button (basket icon) to "Delete user account. Attention: no prompt is shown, but you can make the deletion undone."

I do not insist to have one of the two improvements, I just want to shortly express that I was surprised that such an important action (user account deletion) is done so quickly, and without any user confirmation. If you regard my suggestion as minor, or unimportant, pls. feel free to close it.

**Comment by nickvergessen** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Sorry but undo is a better solution to this problem. Let me list the reasons of why we do undo instead of a dialog:

Firstly, it would make deleting multiple users a pain. Continually clicking »confirm« is stupid and desensitizes towards the popup. It will result in just mindlessly clicking »confirm«.

> the warning could be overlooked

Popups are even more overlooked and clicked »confirm« on. See See [Never Use a Warning When you Mean Undo](http://alistapart.com/article/neveruseawarning) and [Nobody Reads your Dialog Boxes](http://ignorethecode.net/blog/2008/10/31/nobody-reads/).

> the "undo" message is not known before you actually press the delete user (basket icon) button.

The confirmation dialog is not known either.


I hope that explains the reasoning.
