### ISSUE TITLE
PHP default_charset check behaves differently between webUI and autoconfig

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#14966]
### Steps to reproduce

1. Install master
2. complete configuration via webUI --> all is well
3. install master
4. complete configuration using autoconfig --> get error

### Expected behaviour

The behaviour should be consistent, regardless of which is correct

### Actual behaviour

The autoconfig installation fails due to :

```

root@ubuntu-14-lts:/var/www/html/owncloud# php -f index.php
PHP setting "default_charset" is not set to "'UTF-8'".
Adjusting this setting in php.ini will make ownCloud run again

Writing to database failed{"reqId":"gkAc1PACFr4dSKD52PdU","remoteAddr":"","app":"PHP","message":"touch(): Unable to create file \/var\/www\/html\/owncloud\/data\/owncloud.log because No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/log\/owncloud.php#48","level":3,"time":"2015-03-17T17:09:46+00:00"}

```

Follow on questions:

Is the php setting check new with master?  Is there any upgrade impact? 

### Server configuration

Ubuntu 14.04
PHP 5.5.9
MySQL DB

$OC_Version = array(8,1,0,0);
$OC_VersionString = '8.1 pre alpha';
$OC_Channel = 'daily';
$OC_Build = '2015-03-17T03:27:24+00:00 fc0aa0b6ae8897aea7666a36de2350106eb9999c';

**Comment by LukasReschke** [comment]
Your CLI PHP uses another php.ini which has the wrong value set - the web interface gets a corrected value via the .htaccess file. Not much we can do except to fix the php.ini of the cli :)

**Comment by jnfrmarks** [comment]
Did we improve the php checks in master? I hadn't seen this before.

**Comment by LukasReschke** [comment]
> Did we improve the php checks in master? I hadn't seen this before.

Yes. – You can see the current checks at https://github.com/owncloud/core/blob/ebb834d879f10ea24b8cf032f6f0000076843195/lib/private/util.php#L580-L606 - `ini` defines the checks for the PHP settings.

In Apache we try to override some using the .htaccess, in CLI that's not possible and users have to adjust the CLI.

**Comment by VincentvgNn** [comment]
@LukasReschke 
I separately installed OC 8.0.2 and OC 7.0.2 at a hosting company. An auto-installer "Installatron" did the job for me.
Since OC8 I get an eror message as shown in issue #14216 .
I cannot access and change the php.ini file. And I would have to do that at 2 hosting companies.
From phpinfo I can find that the default_charset is set to "no value" at both companies.
In the OC .htaccess file there is a line "AddDefaultCharset utf-8".
In the .user.ini file there is nothing about the charset.

Is my error message related to the issue and improvement as described here?
How can I solve it?

Thanks.

**Comment by VincentvgNn** [comment]
@LukasReschke 
For the time being I solved by it editing the .htaccess file.
In issue #15044 I described the problem and the solution and I asked how to get this into the new automatic software distributions.
