### ISSUE TITLE
Accessibility - possibly remove `tabindex=-1` on first link to index.php

### ISSUE THREAD

**Issue by Volker-E** [owncloud/core#15013]
I don't know why the `tabindex` attribute is set to `-1` on the logo index link in layout.user.php? 
It makes this pretty important link inaccessible to keyboard usage (especially in Screen Readers). 

I'd suggest removing it. In case it got in there for visual reasons, like not having a dotted outline around, there are accessible ways to deal with that. For example, by including an explicit `#owncloud:focus {}` rule.

**Comment by Volker-E** [comment]
Read further: http://www.paciellogroup.com/blog/2014/08/using-the-tabindex-attribute/

**Comment by jancborchardt** [comment]
Good question actually. I think I added it because there wasn’t any feedback and it always links back to files. Wasn’t really thinking there, because that is actually very useful if you are _not_ in Files.

We would need to:
* remove it again, except when in the files app – because then it’s useless.
* also add visual feedback when tab-focusing the logo. Like reducing the opacity – but please only for tab-focus, not for mouse-hover.

**Comment by jancborchardt** [comment]
I’d go with closing this issue since the apps menu is more important to be accessed than having a specific link back to files in the way.
