### ISSUE TITLE
on installation screen change lable from database password to user password

### ISSUE THREAD

**Issue by charlessteiner** [owncloud/core#15074]
may save some people a little confusion. Tiny edit for a polished product

#### so the four fields should read
database user
user password (currently  'database password')
database name
database host

**Comment by DeepDiver1975** [comment]
What would that help? This field shall hold the password of the user to be used to connect to the database. So it's the database password. I see no source for confusion. THX

**Comment by charlessteiner** [comment]
clarification. the password is a user password not a database password.  

Help maybe nothing. But it's correct.

**Comment by DeepDiver1975** [comment]
so the ultra correct naming would be 'database user password'

**Comment by DeepDiver1975** [comment]
summoning @jancborchardt on UX related topic

**Comment by charlessteiner** [comment]
I'm not philosophize about why something should be called what it is. 

If I'm not mistaken: databases do not have passwords, users do.

**Comment by jancborchardt** [comment]
Here’s the thing:
* »user password« would create more confusion since people might think it would be their ownCloud user password
* »database user password« would indeed be the most correct one, but it’s seriously too long
* we didn’t have any confusion so far with »database password« so let’s not change it based on hypothesis.
