### ISSUE TITLE
Cannot share files with LDAP users via the provisioning api

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15086]
### Steps to reproduce

1. Install owncloud
2. configure ldap 
3. log in as an ldap user and create a file
4. share the file with another ldap user using the provisioning api

### Expected behaviour

The file is properly shared

### Actual behaviour

The share fails with a message that the ldap user does not exsit

```
jennifer@ubuntu-14-client:~/smashbox/results/test_shareFile$ curl -u abagail_kuhic:secret --data "path=TEST_FILE_USER_SHARE.dat&shareType=0&shareWith=abagail_kuhlman_iii&permissions=31" http://abagail_kuhic:secret@x.x.x.x/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>403</statuscode>
  <message>Sharing 628 failed, because the user abagail_kuhlman_iii does not exist</message>
 </meta>
 <data/>
</ocs>
```

Same command but sharing with a local user

```
jennifer@ubuntu-14-client:~/smashbox/results/test_shareFile$ curl -u abagail_kuhic:secret --data "path=TEST_FILE_USER_SHARE.dat&shareType=0&shareWith=user1&permissions=31" http://abagail_kuhic:secret@x.x.x.x/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <id>72</id>
 </data>
</ocs>


```

### Server configuration

Ubuntu 14.04
PHP 5.5.9
MySQL DB

ownCloud Enterprise Edition 8.1 pre alpha (daily) Build:2015-03-19T03:27:00+00:00 fe8002a7db0ccfec3a96def4f889c265b52ace53

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
Works for me with current master:

```
$ curl -u zombie4:zombie4 --data "path=session.diff&shareType=0&shareWith=zombie5&permissions=31" http://zombie4:zombie4@zara.owncloud.bzoc/master/ocs/v1.php/apps/files_sharing/api/v1/shares
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <id>70</id>
 </data>
</ocs>
```

Is abagail_kuhlman_iii a valid username? Do you see it on the Users page?

**Comment by DeepDiver1975** [comment]
i have this reproduced locally .... @blizzz

**Comment by DeepDiver1975** [comment]
in my case zombie295 is the login name - where as the uid is the ldap uuid - in this setup th user cannot be detected. @blizzz we need the login-to-uuid hook to make this work?

**Comment by blizzz** [comment]
I was able to reproduce it too – with a user who did not login yet, after a hint in https://github.com/owncloud/core/issues/15115#issue-63725705

@DeepDiver1975 this can indeed add up as well.

**Comment by blizzz** [comment]
Lion part of the problem is: if we share to a user, we need to know the username. This is fine with the share dialogue, because it requires a search, which returns the displaynames and usernames. With the share API however, this does not happen. You specify the username. If the target user is not known to ownCloud, sharing to the provided name will always fail. 

I am not sure there is a good way to solve it from our side. Triggering a search prior to the sharing action will not work, as the username is not necessarily searchable in LDAP.

This can be done by the share API user. It must be made sure that all desired users are being fetched to ownCloud in advance. Either force a bulk read, or do a search on demand with values that will definitely return the desired user. 

The username provided in shareWith really must be the username and not the loginname. Technically you do not know the username in advance (practically it will work most likely with LDAP, if you avoid name collisions that would create different usernames).

One may think we should fetch all LDAP users immediately. Since we are never notified of new users pulling is unreliable and will not solve this issue.

**Comment by blizzz** [comment]
A prior call to https://doc.owncloud.org/server/8.0/admin_manual/configuration_user/user_provisioning_api.html#users-getusers will make this probably work. Furthermore, this should also return the username, so can really rely on it. Note that LDAP search attributes should be configured properly and you should search using a unique value (uid respectively samaccountname) and double check the returned result(s), especially when more than one value is returned (eg. looking for userAccount22 would return also data for userAccount227). But this will be the proper way to do the search. You could add a specific getUser https://doc.owncloud.org/server/8.0/admin_manual/configuration_user/user_provisioning_api.html#users-getuser request first, if you think you know the username, to avoid searching if not necessary.

**Comment by scopus777** [comment]
Sorry for pushing this rather old post but we are facing this issue at the moment. We want to share files by using the provisioning api. We have the username but unfortunately the api expects the LDAP uuid. The prior call mentioned by @blizzz does not help because we don't get the necessary information about the user we want to share the file with. Is there any other workaround?
