### ISSUE TITLE
MPO support

### ISSUE THREAD

**Issue by plberd** [owncloud/core#15124]
What are the chances of adding MPO (Multi Picture Object) support on Owncloud?
MPO files are usually 3D images taken with Fujifilm 3D cammeras or some 3D smartphones. They are basically 2 jpeg files concatenated. Most linux applications treat them as jpeg files and show them as a single image (the first image, usually the left one) ignoring the rest of the file.
I usually add an MPO line to the mimetypes.list.php as `'mpo' => array('image/jpeg', null),`.
And it used to work well:
- it generates thumbnails based on the left eye image (which is great)
- the Pictures app showed the left eye image when I clicked on an MPO file.

With OC8 I started having some troubles:
- Pictures app doesn't work anymore (the viewer works, but not the galley app ui). I quits silently without showing any result, not even normal jpegs. When I remove the mime type and rescan all files, it works again.
- Gallery+ app doesn't even show the image in the viewer. And they told me it's related to some exceptions from core.

So here I am. Does anyone know if adding real support for MPO files would be possible?

Thanks

**Comment by DeepDiver1975** [comment]
@oparoz can you comment on this? THX

**Comment by oparoz** [comment]
That's the reason I created PR https://github.com/owncloud/core/pull/15088

@plberd - With the new media types, Gallery+ should be able to show those files just fine. I've tested with both JPS and MPO files.
If you understand patches, you should be able to merge the changes into oC8. If you only change ` lib/private/mimetypes.list.php`, it only works for files you upload after that. In order to convert existing files, you need to use `lib/repair/repairmimetypes.php` and the `occ` tool to update the medita type of existing files.

**Comment by DeepDiver1975** [comment]
case closed then - fixed with https://github.com/owncloud/core/pull/15088
