### ISSUE TITLE
Ext storage status must not appear for empty row

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15162]
### Steps
1. Allow "SFTP" for users
2. Mount SFTP storage as personal sstorage
3. Go to the second empty row, type something in the mountpoint field
4. Exit the field

### Expected result
No status for empty row

### Actual result
![extstatus](https://cloud.githubusercontent.com/assets/277525/6808502/894a8f76-d254-11e4-8223-b687ecd155e3.png)

Note: it is also possible to make the status appear without typing anything in the empty row, probably by just entering/tabbing in the fields (happened to me once)

### Versions
OC 8.1 master

@Xenopathic can you have a look ?

**Comment by Xenopathic** [comment]
Ah, this is the bug that #14904 was going to fix. The 'keyup' event triggers in the context of the next row when using tab, so the status of the next row (in this case the selectBackend row) gets updated instead of the real row.

We need to come to a conclusion as to what we are doing in that PR. Do we want to use 'input', screw the (minor) consequences with IE 8, or have to use a combination of other events?

**Comment by PVince81** [comment]
This was fixed by a recent PR of @Xenopathic https://github.com/owncloud/core/pull/15180
