### ISSUE TITLE
External Storage mounted but not synced

### ISSUE THREAD

**Issue by taieb92** [owncloud/core#15217]
<h1> External Storage datas not downloaded to the server</h1>

<h2>Steps to reproduce</h2>

1. Enable External Storage app
2. Add another owncloud server as an external storage
3. Disable networking

<h2>Expected behavior</h2>

The external storage folder is synced with the actual owncloud server, and the datas still available after the connection is down

<h2>Actual behavior</h2>

The external storage is synced with the client but not accecible from the server when the cnnection is down

**Comment by Xenopathic** [comment]
The external storage mounting of another ownCloud server does not synchronise data between the servers - it only acts as another external storage for use by clients and in the web interface. There could be hundreds of GBs of data on the remote oC server, but not enough space on the local server, which is why we don't do that.
