### ISSUE TITLE
Investigate recommendations/documentation about nginx' new fastcgi_request_buffering parameter

### ISSUE THREAD

**Issue by guruz** [owncloud/core#15276]
http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_request_buffering

You probably want to have this _disabled_ to have the request land at the PHP earlier and therefore process earlier and avoid sync client timeouts.

CC @carlaschroder @josh4trunks

**Comment by DeepDiver1975** [comment]
hmm ... maybe more a documentation issue?

**Comment by carlaschroder** [comment]
I don't know what this is in reference to-- I need links to relevant doc pages and specific sections. If it's for the dev manual, then that's for someone else.

**Comment by arabesc** [comment]
Here is the link to the doc: [Uploading big files > 512MB](https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html#configuring-php).
I've got the issue #21570 due to [```upload_tmp_dir```](https://secure.php.net/manual/en/ini.core.php#ini.upload-tmp-dir)/[```fastcgi_request_buffering```](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_request_buffering) interaction.

**Comment by carlaschroder** [comment]
Nginx docs have moved to the doc Wiki; closing.

**Comment by guruz** [comment]
I modified https://github.com/owncloud/documentation/wiki/ownCloud-9.x-nginx-config and https://github.com/owncloud/documentation/wiki/ownCloud-8.x-nginx-config

FYI @PVince81 this allows upload chunk streaming on nginx too.

**Comment by guruz** [comment]
FYI also @gig13 @butonic in case there is anyone using nginx as a webserver for oC. (I know it's not officially supported, but customers might still use it)

(not as a load balancer, if load balancer one would want ```proxy_request_buffering``` set to ```off```).

**Comment by carlaschroder** [comment]
Thanks @guruz. Nginx is popular with oC users.
