### ISSUE TITLE
Improve apps management with new app trust levels

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15274]
Changes required in ownCloud core:
* [x] Add setting to »Enable experimental apps« – (add settings widget in the bottom left)
* [x] Add level tags to all apps: Official, Approved, Experimental
* [x] Short explanation popover for the tags
* [x] Put apps inside the categories, sorted by level
* [x] Headers inbetween the levels when scrolling, big warning header for experimental apps
* [x] Sort apps (especially experimental ones)
* [x] Enable button for experimental says »Enable experimental app« (could be yellow)

For reference, the levels:
1. Official (previously »Recommended«)
2. Approved (previously untagged)
3. Experimental (previously not shown in the apps mgmt at all)

cc @LukasReschke @karlitschek

**Comment by LukasReschke** [comment]
I will do the required server changes in core. - Self assigning.

**Comment by jospoortvliet** [comment]
Remember - over time (doesn't have to be done in the first incarnation) we should provide these to users to give them an indication of trustworthyness of apps:

## Trust indications
These can be made visible to the user so he/she can build a relationship with the developer(s) and build trust in the application. Goes for all apps but especially relevant for the approved and unapproved apps (lowest two levels).

* ownCloud app store level
* Author(s) information:
 * name, picture, github account link, social media links, blog
 * other apps by author
* how many ppl contributed
* how long app has been maintained
* release cadence (activity)
* bugs solved/open/...
* comments from other users
* number of downloads
* ratings (minimum nr of ratings, ordered by rating, ...)
* flagged

**Comment by jancborchardt** [comment]
Comments, download numbers and rating are probably the best metric. These are also common from other app stores.

**Comment by LukasReschke** [comment]
@karlitschek I took a look at the OCS API, I think the easiest would be if we ownCloud server sends the `filter=approved` and if no filter is sent it just returns any application. A request to `/v1/content/data?version=8x0x0x1&categories=922&sortmode=new&page=0&pagesize=100` would then for example return also all not approved apps, while with a `&filter=approved` it only returns officials and approved ones.

Regarding the trust level, I see that there is a `approved` field in the returned XML, however, it seems to be 0 in all cases? – Can we reuse this one to indicate the app level or create a new field having an integer? – I'd expect something like that:

- 0 => Totally untrusted code
- 100 => Approved code
- 200 => Official app

Please let me know once we have something sorted out so that I can get some real life code. Would also be awesome to have an category where already a not approved app is in and also an approved / official one so that we can ensure proper testing.

**Comment by LukasReschke** [comment]
I uploaded an early WIP code to allow @jancborchardt to help styling this thing. It basically does nothing at the moment but has the styles applied and I refactored the whole OCS Client code and added unit tests for it…

See https://github.com/owncloud/core/pull/15314

:warning:

**Comment by DeepDiver1975** [comment]
But this is out of scope for 8.1 - we freeze tomorrow -> 8.2

Please focus on 8.1 related issues - THX

**Comment by LukasReschke** [comment]
> But this is out of scope for 8.1 - we freeze tomorrow -> 8.2
> Please focus on 8.1 related issues - THX

Well - as per @karlitschek we want this for 8.1 ;-)

**Comment by karlitschek** [comment]
@DeepDiver1975 please send all the blaming for this into my direction :-)

**Comment by jancborchardt** [comment]
Link https://github.com/owncloud/core/pull/15314

**Comment by karlitschek** [comment]
@LukasReschke This is now implemented.
The return values in the approved field are as recommended by you.

But I would recommend to use a different filter approach for backward compatibility reasons. If you use the current query (no additional parameter) then you get the current result (only approved apps).
But you can pass an approved=all parameter and then you get all, event the unapproved ones.
Does this make sense?

**Comment by LukasReschke** [comment]
> Does this make sense?

Sure. That works for me as well. Let me implement some magic then so that we can do some testing and hopefully get this in.

**Comment by oparoz** [comment]
> Comments, download numbers and rating are probably the best metric. These are also common from other app stores.

There is a problem with the way rating works. It currently starts at 50%, so a new app is immediately regarded as being average. If I see an app with 3/5 stars on the Play store, I simply avoid it.

**Comment by LukasReschke** [comment]
Some changes are at https://github.com/owncloud/core/pull/15314 - a next step from my PoV would be to  check all applications to ensure that they are still at the right level.

i.e. for my "Bookmarks" is not a central application and is also not really maintained, we can downrate this to "Approved" and just ensure a proper communication of that in a blog post or so when we release 8.1 – we might also add a few other applications to the Approved state so that the app store does not look that empty. (some categories show nothing without enabled experimental mode)

**Comment by jospoortvliet** [comment]
@oparoz we should indeed consider the rating unreliable unless there have been 5 or more votes... Not sure how to implement that in practice though.

@LukasReschke :+1: on those thoughs, yes.

**Comment by jancborchardt** [comment]
I agree with @oparoz – when an app hasn’t been rated yet it should receive _no rating_, not 3 out of 5 stars already. Only when there have been ~5 votes (as @jospoortvliet suggested) should the stars be shown at all.

**Comment by oparoz** [comment]
There is another label missing in the app store: IE compatibility
oC is supposed to be compatible with IE, so users will expect things to work on this browser and they should be able to filter out apps which simply won't work.
An app should not get the "official" tag if it's not compatible with IE as it would degrade the user experience and create unnecessary support tickets.

**Comment by karlitschek** [comment]
@oparoz I´m not sure this makes sense. The mission of ownCloud is to provide the best possible user experience for the users. IE is still used by 25% of all users out there. I think good ownCloud apps have to support IE at least in a basic way. Not supporting it and just tag it as "not compatible" is the wrong direction if we care about our users.

**Comment by oparoz** [comment]
@karlitschek - The only app which ships with oC 8.0 is broken for a lot of users and does not work at all on IE. News, a popular app in the app store does not support IE. I'm sure there are more examples.
So the current situation is that oC is not compatible and people only find out when trying to use or install apps which isn't a great user experience.
Even if the team manages to keep core a 100% compatible, apps are required to get the most of oC and supporting IE requires resources which may not be available to app developers, so many apps may not support it, even though it's not explicitly mentioned.
I think it would help users if app devs were "forced" to indicate whether or not they support a specific browser. Official apps should support the 3 major browsers.
Filtering the app store by browser would clearly indicate to users which app should work and reported bugs should be fixed in order to be able to claim compatibility or the official or approved label would be removed.
This all sounds quite strict, but oC is used via a web GUI and a set of minimum requirements has to be set and enforced or the experience will slowly degrade over months.
And if I look at various IE market share trackers, I think it's more at 15% than 25%, but it really depends on the market segment.

**Comment by oparoz** [comment]
I just wanted to add that to be featured in the app store is a nice incentive to be approved, so there is a good opportunity to enforce some "code" criteria.

**Comment by jospoortvliet** [comment]
I do agree with Frank - an app can't become part of core if it doesn't work on a fourth or a 6th of user systems...

**Comment by LukasReschke** [comment]
So we drop the Gallery app? :see_no_evil:

**Comment by oparoz** [comment]
I think the app ships with core so that people can see previews of their files and that works fine (for the most part), so maybe you just need to fork it, disable the menu item and change the description to say that it's a slideshow app. It's a bit of a hack, but Pictures is unmaintained and imho degrading oC's image when people get frustrated because it doesn't show anything and bugs are not fixed.

**Comment by jancborchardt** [comment]
Sorry but we’re not doing the same stupid thing we did with Calendar and Contacts in 8.0 and just drop apps from the release which were there before.

We need to look forward, and the right plan of action is already being discussed in https://github.com/owncloud/gallery/issues/151 – replacing the old Gallery app with @oparoz’s Galleryplus.

So let’s not veer off the topic here.

**Comment by DeepDiver1975** [comment]
closing this issue as we implemented and merged this for 8.1

**Comment by karlitschek** [comment]
@LukasReschke No we fix it instead :-)
