### ISSUE TITLE
Error occurs when the share link checkbox is unchecked and checked

### ISSUE THREAD

**Issue by Norahy** [owncloud/core#15368]
1. Share a file via link and password or use an already shared file
2. Unshare the same file by unhooking the  checkbox
3. Directly share it again -> First error: the password placeholder shows the wrong placeholder (*****)    instead of "Choose your password"
4. Unshare it again (without leaving the dropdown menue) --> Second error:  "Error while unsharing"

It seems like the password which was set with the initial share is not deleted after unsharing it.

**Comment by karlitschek** [comment]
@schiesbn can you have a look?

**Comment by PVince81** [comment]
or @rullzer

**Comment by schiesbn** [comment]
@Norahy which ownCloud version? I tried it with 8.0.2 but couldn't reproduce it.

**Comment by rullzer** [comment]
This might be a problem from the js point. As I could not reproduce it as well.

I think if you directly click afterwards. The share is not yet unshared. So bad things happen since you see old info. Of course that would show wrong data and deleting it would result in an error since it is already unshared.

@Norahy can you confirm it does not happen if you wait a few seconds?

**Comment by Norahy** [comment]
It's version 8.0.2, and it still happens if I wait a few seconds.

**Comment by rullzer** [comment]
@Norahy ok so I still can't reproduce this (not on master and not on 8.0.2).

Could you fill in the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md 
Maybe that sheds some light.

**Comment by rullzer** [comment]
Aaaah you need to enable enforced passwords. Indeed strange. I'll look into it and hopefully I can come up with a not to invasive fix.

**Comment by rullzer** [comment]
So, I think I found the issue. Both had to do with elements not being properly reset.

- The *** showing was a result of that begin modified after a password was enter initially.
- The error was because the link was still set, so the code taught it had to unshare a file.

I'll prepare a PR later tonight that should fix this.
We should really move to the new share model (#5873) :)

**Comment by rullzer** [comment]
A fix is available in #15639. 
@Norahy could you test it?

**Comment by Norahy** [comment]
Works perfectly, thanks!!
