### ISSUE TITLE
external storage (Dropbox) cannot delete/change files using Client

### ISSUE THREAD

**Issue by qnxor** [owncloud/core#15406]
- latest stable server 8.0.2-8 on Ubuntu, Apache 2.4.12
- latest client 1.8.0-2
- one external storage folder on Dropbox, encrypted
- the above folder is shared with another user
- neither of us can delete any files that we add when using the desktop client (Windows and Linux) ... the client says "Not allowed to remove, restoring".

**Comment by PVince81** [comment]
@LukasReschke is that what you were seeing ?

**Comment by PVince81** [comment]
It seems Dropbox doesn't work properly in v8.0.2.
This fix https://github.com/owncloud/core/pull/14946 in the upcoming 8.0.3 that should hopefully make it work.

I tried the following on v8.0.3RC1:
1. Mount Dropbox as system-wide mount point
2. Enable encryption
3. Logout then login again
4. Setup the sync client for this user
5. Wait for sync
6. Create a local folder "encryptthis"
7. Put a bunch of pictures in that folder
8. Wait for sync
9. Delete local folder "encryptthis"
10. Wait for sync

The folder is deleted properly.
It is very likely that your issue was related to https://github.com/owncloud/core/pull/14946.

Please try again with 8.0.3 after it's out
