### ISSUE TITLE
security problem whith remote.php

### ISSUE THREAD

**Issue by Battant** [owncloud/core#15625]
Hello,

Step to reproduce

1. go to : http://yourowncloud/remote.php/webdav
Result : any persone that know this adresse can access to all owncloud server files
The directory shown is /
Expend : A username // password dialog
Confoguration :+1: 
php 5.4 is actived
owncloud 8 server
mysql
more info at : https://www.kreativmedia.ch/

Client configuration : mac os 10.10 windows 7 64 bit and ubuntu 14.04 LTS 64 bit

Could you fix this security problem ?

Best regards

Battant

**Comment by Battant** [comment]
Précis 
go to : http://yourowncloud/remote.php/web Fromage a web browser.
Best regards
Battant

**Comment by karlitschek** [comment]
Your browser will ask for username and password when go to this url before showing you any files. Most browsers cache this information after you have entered them once. Please go to this url with a different browser. Then you will see that you need infact authenticate to see the files.
This is the expected behavior for an WebDAV endpoint.

**Comment by Battant** [comment]
This issus can be close

On mac os, safari and firefox ask usernname and passwerd.

Best regards

Battant
