### ISSUE TITLE
Blank text file previews

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15634]
### Steps to reproduce:
1. Checkout git master (1a2475227b6777e016ec931ddae533437bfbb2dd)
2. Setup OC from scratch
3. Upload a text file

### Expected result
Text file has preview

### Actual result
Text file preview is blank/white.
Other previews work fine.

### Versions
openSUSE Factory
php5-5.6.7-1.1.x86_64
apache2-2.4.12-2.1.x86_64
ImageMagick-6.9.0.9-1.1.x86_64

Breaking commit: 6c327f8331617652ef0b268d51edc6a23624e33c (about max preview size)

@georgehrke @oparoz please have a look

**Comment by nickvergessen** [comment]
yeah "makes sense" in terms of that commit "breaking" the previews.
actually it's not empty (depends on the number of lines text you posted).
you can see that on the 2048-2048-max.png it contains the lines of text in the top left. The 36*36 just shrinks that one which reduces it the part of the text to 1 pixel. together with the white space between the letters makes the file almost completly white, otherwise you'd see 1 line of black pixels

**Comment by nickvergessen** [comment]
Btw, I assume some other previews suffer from the same problem? (office, pdf, ...?)

**Comment by oparoz** [comment]
This actually stems from a problem with Text previews. I'm still looking for the ticket where this is discussed.

**Comment by oparoz** [comment]
Here you go: https://github.com/owncloud/core/issues/11469

**Comment by oparoz** [comment]
And there is zero problem with office documents because everything is converted to PDF and ImageMagick understands that format.

**Comment by oparoz** [comment]
My position is that we should fix the font size for the thumbnails and then add an exception here:
https://github.com/owncloud/core/blob/master/apps/files_sharing/js/public.js#L104-L117
so that text is simply printed in a div instead of trying to generate a preview.

**Comment by oparoz** [comment]
https://github.com/owncloud/core/issues/15652 implements a text preview of text files which are publicly shared.
