### ISSUE TITLE
Improve punctuation in UI

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15642]
### Steps to reproduce

1. Install 8.0.3 complete
2. Navigate throughout the UI

### Expected behaviour

Punctuation should be correct on titles

### Actual behaviour

There are areas where we only capitalize the first word in a title, such as:

 
![p311](https://cloud.githubusercontent.com/assets/8480343/7160635/5317f2da-e358-11e4-8f47-a0a223add6eb.PNG)

and,

![p312](https://cloud.githubusercontent.com/assets/8480343/7160636/54ddf114-e358-11e4-8fd0-843befb13479.PNG)

These are only a couple of areas, there are others too.

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.0.3 RC1 (testing)

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
In the Files sidebar at least I deliberately only uppercased the first letter because »Shared with you« is way more legible than »Shared With You« etc.

So I would rather have the capitalization in a way that only the first word is capitalized. And when it’s a brand name like »Windows Network Drive« (and »Federated Cloud Sharing« I guess)?

Your screenshot is also a bit outdated since »Security & setup warnings« and »Mail templates« already has the correct lowercase version.
