### ISSUE TITLE
[enc2] Restore encrypted file from trash breaks the file + versions

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15640]
### Steps to reproduce
1. Enable encryption 2.0 + default encryption modul
2. Log out then log in again
3. Create a text file
4. Edit it and save multiple times to create versions
5. Delete the file to trash
6. Restore the file
7. Download the file itself
8. Download any version of the file

### Expected result
File + versions can be downloaded

### Actual result
Download gives a broken file (garbage)

### Versions
ownCloud git master (1a2475227b6777e016ec931ddae533437bfbb2dd)

@schiesbn @th3fallen @DeepDiver1975

**Comment by PVince81** [comment]
This works on stable8, so technically a regression

**Comment by schiesbn** [comment]
It looks like the sorting of the storage wrappers doesn't work as expected. The trashbin has priority 1 and the encryption wrapper priority 2. So the trashbin should always come first, but when I debug this issue it the encryption wrapper will be called first on delete.

I'm not sure if I understand the storage wrapping process correctly. But it seems like the problem is this method: https://github.com/owncloud/core/blob/master/lib/private/files/mount/mountpoint.php#L214

````
public function wrapStorage($wrapper) {
    $storage = $this->getStorage();
    // storage can be null if it couldn't be initialized
    if ($storage != null) { 
        $this->storage = $wrapper($this->mountPoint, $storage, $this);
    }
}
````

The first line ````$storage = $this->getStorage();```` will call https://github.com/owncloud/core/blob/master/lib/private/files/storage/storagefactory.php#L92 which does the re-ordering of the already applied storage wrappers. Then we add the new wrapper at the top ````$this->storage = $wrapper($this->mountPoint, $storage, $this);```` independent from his priority. So the last wrapper will always be the first because after that the method which sort the wrappers will never be called again. @icewind1991 can you comment on it? Do I miss something?

**Comment by PVince81** [comment]
Or did you guys understand the priorities in reverse ? I found this code that sorts the storages: https://github.com/owncloud/core/blob/722e50a112579d851b958a21cf26c2e85a4ce5c2/lib/private/files/storage/storagefactory.php#L94

**Comment by PVince81** [comment]
Right, if wrappers are added afterwards there is no insert sort.

**Comment by schiesbn** [comment]
The priorities should be correct, according to the phpdoc and the code you mentioned. The storage with the lowest number should be first.
https://github.com/owncloud/core/blob/master/lib/private/files/storage/storagefactory.php#L45
https://github.com/owncloud/core/blob/722e50a112579d851b958a21cf26c2e85a4ce5c2/lib/private/files/storage/storagefactory.php#L94

**Comment by schiesbn** [comment]
@icewind1991 can I ask you to have a look at this? I'm not sure what's the right place to fix it. Thanks!

**Comment by schiesbn** [comment]
@icewind1991 Thanks for taking care of it!
