### ISSUE TITLE
[enc2] Admin UX: after update, show notification to hint at migration

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15669]
### Steps
1. Setup stable8 / OC 8.0
2. Enable encryption
3. Upload files
4. Upgrade to master / 8.1
5. Download a file

### Expected result
After the update, a notification must appear for the admin that says "Please go to the admin page to configure the new encryption" or something about the migration.
Also: whenever a file action before the admin did the migration, return 403 or a proper error message.

### Actual result
No hint. The admin believes that everything is fine but cannot download files.

@schiesbn @jancborchardt @th3fallen @DeepDiver1975

**Comment by PVince81** [comment]
Or make sure that proper exceptions / error messages are logged/shown whenever files are accessed.

**Comment by jancborchardt** [comment]
This needs to be fixed for 8.1, right?

**Comment by schiesbn** [comment]
That's not that easy because after upgrade the old encryption is no longer there. So the old encryption can't issue such a warning. The new one is not yet enabled so the new encryption also can't detect the state of the system and issue a warning. 

I think this can only be solved by the upgrade documentation where we explain that if you use encryption you have to enable "server-side encryption" and the "ownCloud default encryption module" after upgrade. After the admin perform this steps he will get proper notifications about further upgrade steps.

**Comment by karlitschek** [comment]
So I think we need an upgrade script that detects if the old encryption was enabled and then enables the new one.
@schiesbn What do you think?

**Comment by PVince81** [comment]
Closing as duplicate of https://github.com/owncloud/core/issues/16177
