### ISSUE TITLE
  Folderlink missing after un-sharing folder (SMB)

### ISSUE THREAD

**Issue by directict** [owncloud/core#15798]
Dear,

when un-sharing an SMB folder who is mounted on owncloud server (the folder becomes unavailable for the users ofcourse and local data is removed from the client, that is OK)
but when enabling the share again, the Folderlinks made on that specific share are gone...

is this expected behaviour?

i am currently testing what happends when you reboot the file server hosting the SMB shares...

UPDATE:
when i shutdown the fileserver (NAS) the links are gone as well when booting back-up.

this problem should be fixed somehow? i hope it's fixed in 8.1 ?

**Comment by PVince81** [comment]
I'd say it is expected behavior that if you unmount an external storage, all links associated with it are gone.

But in your case you seem to be talking about temporarily shutting down the storage ?
Currently this isn't properly supported, but would be good to have a way to temporarily disable an unavailable storage without losing any cache/share info, see: https://github.com/owncloud/core/issues/13531.

In your case the SMB share should then become unavailable and OC would have to throw StorageNotAvailableException (this is not yet the case, needs to be added: https://github.com/owncloud/core/issues/11792)

CC @Xenopathic @icewind1991

**Comment by directict** [comment]
Dear Vincent,

thanks for the reply, well yes, i am not un-mounting the shares in owncloud, i meant un-sharing on the NAS/Windows FileServer (same as shutting down the device, the share becomes unavailable) . Owncloud gives the RED status and the share is gone for the users meaning the file links are gone also, so now when we reboot our storage or have maintenance we have to shutdown Owncloud as well.

so if i understood correctly there is comming an feature that allows to save the status of the remote storage (smb in my case).

Regards,
Gert-Jan Slot

**Comment by Xenopathic** [comment]
Ah, so on storage backend failure all shares are lost? This seems bad... we definitely need to make failure handling (and by extension, exception handling) a priority for oC 8.2.

**Comment by directict** [comment]
Yes indeed Xenopathic, imagine a file server outage during night... all clients will drop data and all folder links missing.. this would be a disaster, my colleague is making a temp work-around with a script that will shutdown the owncloud server as soon as the SMB mount becomes unavailable.

(btw, how often does Owncloud checks the shares? only when you are in the admin page, or is it the same when a user tries to access an external storage smb?)

regards,
Gert-Jan Slot

**Comment by PVince81** [comment]
Storage unavailability has been added in 9.0 (might be 8.2 too).

Please try again with v9.0.1.
