### ISSUE TITLE
admin should not be able to select ldap groups for users

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15818]
### Steps to reproduce

1. Install 8.1 enterprise
2. Configure LDAP
3. Navigate to the admin page
4. Click on the groups drop down for the admin user (or any local user)
5. Select the ldap group configured in 2 above

### Expected behaviour

The group should be greyed out

### Actual behaviour

The admin can select the group but when the page is refreshed or the user goes to their personal page, the group isn't there and there's not info on the UI for the user as to why.

![p324](https://cloud.githubusercontent.com/assets/8480343/7284143/7de51f36-e909-11e4-9e8b-a59fb9ee75dd.PNG)

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by karlitschek** [comment]
@blizzz What do you think?

**Comment by MorrisJobke** [comment]
Should groups be restricted to a backend?

**Comment by blizzz** [comment]
@MorrisJobke user and group backends are isolated from each other. For instance it is and should be possible to assign LDAP users to local groups. What we currently do not check however is whether the group backend is able to add users to a group. With LDAP this is not the case, because we do not write to LDAP.
