### ISSUE TITLE
Can't  change quota for LDAP users

### ISSUE THREAD

**Issue by Hoper** [owncloud/core#15966]
OwnCloud 8.0.2 (stable)  (MySQL)
Ubuntu 14.04
Settings LDAP
The quota default = 5 000 000 000
It's OK
I am doing for one user quota = 10 000 000 000 
From some time the quota come back to default 5 000 000 000 
I can't change quota for LDAPs users.

**Comment by mape2k** [comment]
Same issue here on OC 8.0.2 with LDAP.

Maybe there is just no decision/configuration possibility which value have the precedence. Commonly the quota will be set with an ldap attribute, so this is not an issue.

IMHO user quota should be used if user quota is set, default quota is set and ldap attribute is not used.

**Comment by mape2k** [comment]
After some investigation of the source code i believe this is a more of a config issue.

Based on Hopers example:
Setting quota in ldap plugin to 5GB leads to reset the user quota to 5GB. The "reset" happens after 24h because the ldap plugin syncs the ldap information with local preferences table. So if you set user quota to 10 GB the setting will survive a maximum of 24 hours. This "reset" only applies if the default quota in the ldap plugin is set. If this value is empty this will not happen!

The better IMHO is to leave this value empty and use OC user quota settings. So set user quota to 5GB (in the users administration the gearwheel down left) and let the user quota be "default". For the user who needs more you can set the quota in user list to 10GB. These settings will remain.

IMHO there should be some information in ldap plugin config dialog about this behaviour.

Hoper, i hope this helps.

**Comment by blizzz** [comment]
> The better IMHO is to leave this value empty and use OC user quota settings. So set user quota to 5GB (in the users administration the gearwheel down left) and let the user quota be "default". For the user who needs more you can set the quota in user list to 10GB. These settings will remain.

Yes. Or define a quota attribute in LDAP and manage quota in LDAP. It is not intended to mix "local" quota management and LDAP one, you decide for either of those.
