### ISSUE TITLE
server to server checkbox checkable even if a module is not enabled

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15986]
### Steps to reproduce

1. Install 8.1
2. Navigate to admin page
3. click "server to server encryption" checkbox
4. get module not enabled message
5. navigate to apps page
6. enable a module
7. navigate back to the admin page
8. see that server to server encryption is enabled with the module present

### Expected behaviour

The checkbox should not be present or checkable if there isn't a module enabled

### Actual behaviour

The checkbox remains checked.  This means that once the module is enabled, encryption is now happening.  

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 alpha 2 (daily) Build:2015-04-30T03:08:25+00:00 4209757d61685346b9b3eb476035b4e86597ed64

### Browser Configuration

Chrome

@MTRichards

**Comment by karlitschek** [comment]
@schiesbn

**Comment by jancborchardt** [comment]
The problem is on a higher level (I really don’t understand this complexity with the modules). This:

> 3. click "server to server encryption" checkbox
> 4. get module not enabled message

… should never happen. It’s stupid I have to manually then move to the apps page again and enable a module.

If I install encryption, of course I just want to use it which means the default module should probably be installed by default. Otherwise it’s just cumbersome.

**Comment by karlitschek** [comment]
I agree with @jancborchardt Can you look into that @schiesbn ?

**Comment by karlitschek** [comment]
Discussion is over there: https://github.com/owncloud/core/issues/16021
