### ISSUE TITLE
User asked to enable encryption keys when server side encryption is not enabled

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15989]
### Steps to reproduce

1. Install 8.1
2. Enable ownCloud default encryption module
3. Log out
4. Log back in

### Expected behaviour

User should not be asked to initialize encryption keys

### Actual behaviour

User is asked to initialize encryption keys

![p338](https://cloud.githubusercontent.com/assets/8480343/7419708/f03d4a36-ef44-11e4-911d-5b9ef222193b.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 alpha 2 (daily) Build:2015-04-30T03:08:25+00:00 4209757d61685346b9b3eb476035b4e86597ed64

### Browser Configuration

Chrome

**Comment by karlitschek** [comment]
@schiesbn

**Comment by karlitschek** [comment]
@schiesbn ping

**Comment by schiesbn** [comment]
I would say this behavior is correct. If the app is enabled we want to have valid private/public keys. Even if the encryption app is not enabled in the admin settings because even in this case the encryption module will be used to read already encrypted files, so it should check that it is initialized correctly and warn the user if not.
