### ISSUE TITLE
Can the UI encryption configuration bits be closer together on the screen?

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15987]
### Steps to reproduce

1. Install 8.1
2. Enable an encryption module
3. Navigate to admin page

### Expected behaviour

The encryption configuration UI bits should all be near each other

### Actual behaviour

The encryption configuration UI bits are spread out

![p337](https://cloud.githubusercontent.com/assets/8480343/7418793/9c7204ce-ef3e-11e4-8dec-9e65fbb90bff.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 alpha 2 (daily) Build:2015-04-30T03:08:25+00:00 4209757d61685346b9b3eb476035b4e86597ed64

**Comment by karlitschek** [comment]
@schiesbn

**Comment by jancborchardt** [comment]
Yes, we should move them together as we did with the Sharing and Federated Sharing settings as well. Also the basic encryption should only be named »Basic encryption module«.

Server-side encryption should be moved _above_ the Basic encryption module.

cc @nickvergessen because he worked on moving some other settings together.

**Comment by jancborchardt** [comment]
Oh and ideally it should open as one section, just like Sharing and Federated sharing does.

**Comment by karlitschek** [comment]
https://github.com/owncloud/core/issues/16021
