### ISSUE TITLE
OCP\AppFramework\Controller::buildResponse() indicates wrong return type

### ISSUE THREAD

**Issue by dagan** [owncloud/core#16011]
```php
/**
 * Serializes and formats a response
 * @param mixed $response the value that was returned from a controller and
 * is not a Response instance
 * @param string $format the format for which a formatter has been registered
 * @throws \DomainException if format does not match a registered formatter
 * @return Response
 * @since 7.0.0
 */
public function buildResponse($response, $format='json') {
```
https://github.com/owncloud/core/blob/master/lib/public/appframework/controller.php#L132-L141

The PHPDoc indicates the return type is ```OCP\AppFramework\Response```, which is not a defined typed. The actual return type is ```OCP\AppFramework\Http\Response```.

**Comment by LukasReschke** [comment]
`OCP\AppFramework\Http\Response` is embedded as use statement in https://github.com/owncloud/core/blob/aa0d439ed9c38389a4508e95a0dd00fa857a5bf8/lib/public/appframework/controller.php#L37 thus compliant PHPDoc should be able to resolve this. I suspect that you refer to stable8 were this is not the case since this seems to have been added with https://github.com/owncloud/core/commit/7644950b48b094bfe5675348aefb7cf5747d325b – please always refer to the version you are using. Thanks.

**Comment by LukasReschke** [comment]
cc @MorrisJobke

**Comment by dagan** [comment]
@LukasReschke You are correct.

**Comment by LukasReschke** [comment]
Fix is at https://github.com/owncloud/core/pull/16012
