### ISSUE TITLE
LDAP wizard configuration; User Display Name field should be not displayName,  but displayname (lowercase) or cn

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16030]
## Steps to reproduce
1. In assisted mode configure a complete LDAP configuration using active directory.
2. Click on advanced tab

### Expected behaviour
Data about User Display Name field should be displayname (lowercase) or cn

### Actual behaviour
The value shown is displayName with capital N. This wrong behaviour seems to appear only using Active Directory.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
What makes you assume there is something wrong with that?

**Comment by davitol** [comment]
The test plan says the value should be displayname instead of displayName

**Comment by karlitschek** [comment]
@jnfrmarks Can you clarify?

**Comment by jnfrmarks** [comment]
@davitol  Can you clarify?

**Comment by davitol** [comment]
When there's a right configuration the displayname value is set in lowercase, but when the status is configuration incorrect, it is set as displayName in Uppercase in the Advanced tab

**Comment by rperezb** [comment]
This problem was that with the version: OC 8.1 alpha 2 the displayName was automatically filled in and in some cases the name included Upper Case, in these cases, it was not possible to connect to the open LDAP. Indeed, on the test plan (used in previous versions) it was included the info that the displayName should not contain uppercase
However, on the version OC 8.1 beta1, no matter whether the displayNames includes uppercase or not, this is working just fine. It would be possible that this could be related to the fix of this issue: https://github.com/owncloud/core/issues/16147
This is not closed yet because @davitol wants to do some extra tests.

**Comment by davitol** [comment]
Tthere is no difference between displayName, displayname  and DiSpLaYnAmE. With  capital N it is the default value. Detected attributes are always in lower case. displayName  with capital N either means that auto-detection was not run
