### ISSUE TITLE
Move the LDAP "configuration active" checkbox to another place

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16059]
I'm having several LDAP configurations and it's difficult to know what configurations are active from the wizard. You need to access to each one and move to the advanced tab.

I think it might be better to move the "configuration active" checkbox to the server tab in order to reduce the clicks we need to do to know if the configuration is active or not.

In addition, it might be even better if we can know the same information somehow with just the select. For example, if we click the select and the background color of an option is green, then the configuration is active; if it's red, the configuration is inactive. Color codes might not be a good choice due to different implementations in the browsers, but it gives an idea.

@blizzz @jancborchardt

**Comment by blizzz** [comment]
Instead of putting it onto the server tab, I would prefer to add an indicator to the status bar. Thus, you will see the activation state on any tab.  Another advantage: you will see immediately, if auto-activiation was done. And actually, we can make it clickable, then we can get rid of the setting in advanced indeed.

Also, I like the idea about the configuration chooser. However, I'd prefer just an italic "active" label next to the host name. Color codes are not clear enough. People could think that the connected LDAP server is offline or has an configuration issue.

**Comment by blizzz** [comment]
cc @cdamken

**Comment by PVince81** [comment]
moved to grouped UX ticket: https://github.com/owncloud/user_ldap/issues/69
