### ISSUE TITLE
Introduce "conflicts" metadata entry for apps?

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16073]
As the app catalogue grows, we're bound to see several apps trying to tackle the same problems and there will be incompatibilities.

What do you think about introducing a "conflicts" entry in info.xml?

```
<conflicts>
    <dashboard min-version="*" max-version="*"/>
    <oc_dashboard min-version="8.0.0" max-version="8.0.3"/>
</conflicts>
```

It could become a pain for app devs to track every app which conflicts with their own, but changing one line in one file will probably take less time than having to reply to the same support issues over and over.

@Raydiation

**Comment by Bugsbane** [comment]
Seems like a logical necessity to me. I mean, we already have multiple gallery apps, video playback apps and music streaming apps, and there are already conflicts.

**Comment by DeepDiver1975** [comment]
I see no reason why there should not be multiple apps if the same kind.
we better address the conflicts individually.

**Comment by oparoz** [comment]
@DeepDiver1975 - The problem is that if you want to have a large eco system, people are going to provide various apps doing the same things.

Apps should be self-contained, but any app can register file actions and that's going to be a problem when several apps compete for the same actions.
As mentioned in the OP, it can be a pain point to track all those conflicts, but it takes much less time than having to answer the same support request over and over.

**Comment by DeepDiver1975** [comment]
> you want to have a large eco system, people are going to provide various apps doing the same things.

Is there an app conflict setting in iOS, Android or and other system? no - why should we have one.

regarding conflicting file actions - this is where we need to enhance the files app to allow multiple file actions in conjunction with a default user selection - just like any other system does out there.

**Comment by oparoz** [comment]
> Is there an app conflict setting in iOS, Android or and other system? no - why should we have one.

For the same reason every fresh app by unknown developers is labelled as experimental and dangerous. ownCloud apps have much more power and can bring the whole system down and even make permanent damage. There is no sandbox preventing that from happening.

You're right though, conflicting file actions are better fixed the way you explained it, but there can be other, more serious issues.

**Comment by DeepDiver1975** [comment]
> ownCloud apps have much more power and can bring the whole system down and even make permanent damage. There is no sandbox preventing that from happening.

sure - but a conflict entry will not protect against that



> but there can be other, more serious issues.

I'm really convinced that me should address these issues and fix them properly instead of such a conflict mechanism.

Conflicts are very much known and necessary in e.g. linux packaging, because there are dependencies between packages. But there is no such concept in ownCloud - by design - we don't want app dependencies and therefore don't want/need conflict declarations

**Comment by Bugsbane** [comment]
I don't think that anyone is arguing against having multiple apps able to do the same things. A system that can let users choose which app to use when 2 can do the same thing like in Android would be a good solution.

My main issue at the moment is having things like my whole ownCloud install break and cease to start up because I had both pictures and gallery installed. I don't think anyone would claim this was a Good Thing(tm)
