### ISSUE TITLE
»Encryption module« naming

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16080]
On a fresh install from the zipfile there’s 2 strange apps:
* »dummy encryption module« – all lowercase and looks like it was forgotten to remove
* »ownCloud Default Encryption Module« with a very long name

What is the »dummy encryption module«? And can we rename »ownCloud Default Encryption Module« to »Default encryption module« (note the fixed capitalization as well) to have the brand name show up less in the UI?

@schiesbn

**Comment by MTRichards** [comment]
Thinking...
In the future, we may well have more than 1 ownCloud encryption module with different algorithms, or different behaviors. Are the descriptors that might make sense here, such as "Default AES 256 Encryption" module?

If not, then I like "Default encryption module."

**Comment by jancborchardt** [comment]
Either way, there will only be one default one, right? So we should call it »Default encryption module«.

@schiesbn it’s provided by the ownCloud community, like most other apps. But we don’t call them »ownCloud <appname>« anywhere. This encryption module is the only one which does that.

**Comment by schiesbn** [comment]
In this case I would just name it "Default encryption module". The idea putting some more information in the name like "Default AES 256 Encryption" is tempting but the encryption module allows you to configure the Cipher, AES 256 is just the default.

**Comment by schiesbn** [comment]
@jancborchardt do you want to create a pull request with the name change?

**Comment by DeepDiver1975** [comment]
hmm .. seriously: what does default mean in this context? Wild thinking: in case we come up with a different  enc module for 8.3 which we want to be used  instead of the existing - what would it's name be like? "Default Next-generation Encryption" ??

Seriously - there is no "Default Contacts" or "Default Calendar" - why should there be a "Default Encryption Module" .... basically just because we are no creative enough to find a cool name - right?

**Comment by jancborchardt** [comment]
Well – I still think if it’s the default module then it shouldn’t be its own app and also enabled by default with encryption. Any new module can still replace it then.

**Comment by schiesbn** [comment]
As said before, I also like the idea from @MTRichards to add some more context in the name, but AES256 doesn't really fit here because it can be changed. How about something like "openSSL based encryption module"? But on the other hand this might be to technical...

**Comment by jancborchardt** [comment]
Come on, review and merge https://github.com/owncloud/core/pull/16085 already – any further detail naming enhancements we can do later. ;)

**Comment by MTRichards** [comment]
I would put openSSL in the app description, as well as AES 256 with a comment about being able to replace this algorithm with something else.

Question: Do we completely replace this encryption module if we implement a different key store, for example, even if we use the same algorithm for the encryption - OR - do we leave this one enabled, and simply add another app to intercept and handle key management (so have 2 apps enabled in that case)?

We should consider giving it a version number...like 2.0, for example. that will help us keep people working on our encryption, and then a new algorithm that is incompatible would be 3.0, an update would be 2.1...
@jnfrmarks

**Comment by schiesbn** [comment]
> Do we completely replace this encryption module if we implement a different key store

Using a different key storage would replace the complete encryption module. Although depending on the changes it might be possible to derive some of the classes for the new module from the existing module.

**Comment by schiesbn** [comment]
> We should consider giving it a version number

The encryption module has a version like every ownCloud app: https://github.com/owncloud/core/blob/master/apps/encryption/appinfo/version

**Comment by MTRichards** [comment]
>The encryption module has a version like every ownCloud app: https://github.com/owncloud/core/blob/master/apps/encryption/appinfo/version

Sure, understand - but that is system level version, and a higher version number is always assumed to be an upgrade or improvement of that mechanism. If you have three encryption apps, each has a different version thread, completely disconnected from each other.

What I mean is in the name of the app, if we don't have descriptive names, we need something that differentiates the apps when looking in the admin panel. The more I write though, the more I think we need a descriptive name rather than just a number.

The more I think about it, the more I come back to a descriptive name:
- Default encryption module (today)
- Default encryption with key store integration
- Default encryption with SSO support
- RSA encryption with integrated key store
- etc

We always refer to the module included in ownCloud as the Default encryption module so users always know that this is what they are using, and the newer one is just and update - and there is built in migration.

Any other apps get a different name that explains the difference so that an admin knows what is being used.

**Comment by schiesbn** [comment]
Ok, now I get it... I agree, makes totally sense.

**Comment by schiesbn** [comment]
fix was merged
