### ISSUE TITLE
Full name in personal settings is wrongly set by default to be the username

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16082]
On a fresh installation from the zipfile, for some reason the »Full name« in the personal settings is wrongly prefilled with the username. This should not happen.

@DeepDiver1975 @MorrisJobke

**Comment by MorrisJobke** [comment]
What else should be there prefilled?

**Comment by jancborchardt** [comment]
I thought it should not be prefilled, as it’s not the full name. I do wonder though because that’s probably better than nothing still … what do you think @owncloud/designers?

**Comment by PVince81** [comment]
Still happening on master (8.2 beta)

**Comment by stefan-niedermann** [comment]
should be empty and not prefilled. username != full name. if the user wants to set a full name, he can do this. i think in the very most cases the username is not identical to the full name, what means a prefilling is nonsense as the user has to delete first the "full name" and enter his real full name.

**Comment by jancborchardt** [comment]
This didn’t happen before. Who can please fix this @DeepDiver1975 @PVince81 @MorrisJobke?

**Comment by schiesbn** [comment]
@jancborchardt what do you mean with "This didn’t happen before." exactly? I just tried oC8.0 and oC8.1 and there we also show the uid. 

Technically speaking this also makes sense. Because the "Full name" is what we call "Display Name" internally. It's the name which is displayed to others, e.g. "userX shared file foo with you". If a display name is defined we show the display name, if not we show the uid. That's why I think it makes sense to show the uid in this field if no display name was specified. This way you see under which name you will be visible to others. Btw, we have the same behavior in the user management.

**Comment by jancborchardt** [comment]
Hmm … right. I guess that’s correct @schiesbn, thank you for the clarification.
