### ISSUE TITLE
Renaming an encrypted file in the external storage backend make the file download corrupted

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16178]
### Steps to reproduce
1. Having encryption enabled, upload a file to an external storage through OC
2. Check that the file is encrypted in the storage backend
3. Rename the file directly in the backend
4. Check that the file is also renamed in OC
5. Download the file

### Expected behaviour
The file is downloaded decrypted

### Actual behaviour
The file is downloaded corrupted

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
- encryption
- files_external

### Notes
Checked with dropbox backend, but it's likely to happen in any external storage.

The downloaded file is different than the one stored in the backend. It's not the "encrypted" version of the original file.

**Comment by jvillafanez** [comment]
@jnfrmarks to be prioritized. Looks like a complex issue to be ready for 8.1

**Comment by jnfrmarks** [comment]
@jvillafanez 

Can you please confirm if this works correctly without encryption enabled - I'm curious about if the file is corrupted regardless of the state of encryption.

**Comment by jvillafanez** [comment]
I've uploaded another file without any encryption module active, renamed it in the same backend, and it downloads correctly the same file.

**Comment by jvillafanez** [comment]
I think the main problem is that OC cannot detect if the file has been renamed in the backend. From the OC point of view, the "old" file has been deleted and a new file has appeared. Due to it's a new file, we cannot assume that the file has been encrypted by OC (at least in a safe way).

My guess is that the encryption module tries to decrypt the file, but with a wrong / missing key, because the key to decrypt the original file isn't "pointing" to the new file, an the new file doesn't have a key associated.

**Comment by schiesbn** [comment]
@jvillafanez Your last description is correct. We have no way to detect that a file was renamed in the external storage. For ownCloud this is a new file. The file header indicates that it is encrypted but we wont find the corresponding encryption keys because they are still named like the original file.

That's not something we can fix and if you use a external storage with encryption it doesn't make any sense to access the files directly because only ownCloud can read it. If people still mess up their files then there is not much we can do about it.
