### ISSUE TITLE
after update - wrong config link in apache

### ISSUE THREAD

**Issue by berni123** [owncloud/core#16189]
Neue Version der Konfigurationsdatei /etc/apache2/conf-available/owncloud.conf wird installiert ...
[....] Restarting web server: apache2[Fri May 08 08:33:27 2015] [warn] The Alias directive in /etc/apache2/conf.d/owncloud.conf.old at line 1 will probably never match because it overlaps an earlier Alias.
 ... waiting [Fri May 08 08:33:28 2015] [warn] The Alias directive in /etc/apache2/conf.d/owncloud.conf.old at line 1 will probably never match because it overlaps an earlier Alias.

root@fabienne2:~# ls -al /etc/apache2/conf.d/owncloud.conf*
lrwxrwxrwx 1 root root 31 Mai  8 08:33 /etc/apache2/conf.d/owncloud.conf -> ../conf-available/owncloud.conf
lrwxrwxrwx 1 root root 31 Mär 27 10:53 /etc/apache2/conf.d/owncloud.conf.old -> ../conf-available/owncloud.conf

removing: owncloud.conf.old  fixes it

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by RealRancor** [comment]
Hi,

where is the owncloud.conf.old coming from? Did you created this yourself sometime in the past?

**Comment by berni123** [comment]
Right. The upgrade script does the copying. But it's a double symlink to the same file - so its the wrong directory: I think it should be a backup of conf-available/owncloud.conf in that directory

**Comment by jnweiger** [comment]
Do we know what dpkg-divert does? I'd assume it takes care of creating backups already?
If so, the second line is obsolete.

**Comment by deMattin** [comment]
I also have this issue for long time on any update with suse repo (with Debian 7, Apache 2.2).
The update generates a backup (.old) of the symlink file in `conf.d` folder and no backup file in `conf-available` folder.
It simply works the other way round as it should.

I don't know, what the https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.0/owncloud/debian.owncloud-config-apache.preinst?expand=1 exactly does, but  maybe there only has 
```
f=/etc/apache2/conf-available/owncloud.conf; test -e $f && dpkg-divert $f || true
f=/etc/apache2/conf.d/owncloud.conf;         test -f $f && mv $f $f.old   || true
```
to be changed to:
```
f=/etc/apache2/conf-available/owncloud.conf; test -f $f && mv $f $f.old   || true
f=/etc/apache2/conf.d/owncloud.conf;         test -e $f && dpkg-divert $f || true
```
??

**Comment by jnweiger** [comment]
@deMattin your suggestion looks good to me. I still have no clear idea, what the dkg-divert line actually does, and what would break if we remove it. Leaving it as is.

Applied suggested fix to https://build.opensuse.org/package/view_file/isv:ownCloud:community:testing/owncloud/

**Comment by jnweiger** [comment]
Please reopen, if the issue persists

**Comment by jnweiger** [comment]
@deMattin FYI:  I had to revisit the suggested code. No more dpkg-divert, no more mv. Both can lead to errors during unattended online update. I've changed that all to a simple cp. in the conf-available folder.

**Comment by deMattin** [comment]
I think, that is a good solution for the conf-available (renaming old and copying new config). because this way it should work, as one expects it.
And `cp` should simply overwrite, if the file already exists.

I also think, that this is the reason and correct useage for this separate conf-available and conf.d folders.
conf.d: the link, that's once set (to a named conf-available file)
conf-available: (some) config files, that can be updated or can hold backups or different (inactive) versions of config files to switch them fast just by renaming them.

We'll see, if it works for the next and future updates ... ;)

**Comment by jnweiger** [comment]
@deMattin thanks for confirming!

**Comment by deMattin** [comment]
Today there has been the update to Owncloud 8.0.4 on Suse Repository.
The Issue is still there - in folder `conf.d` there's been made a backup of the link and the config file `owncloud.conf` in `conf-available` has no backup:

![image](https://cloud.githubusercontent.com/assets/5565503/8025208/69b1761e-0d4d-11e5-88a8-4d00d7e45f2e.png)

![image](https://cloud.githubusercontent.com/assets/5565503/8025212/77d453ce-0d4d-11e5-924e-7daf08589fc9.png)

I don't understand anything about packeting but is it possible, that the lines we have been talking about:
```
f=/etc/apache2/conf-available/owncloud.conf; test -f $f && mv $f $f.old   || true
f=/etc/apache2/conf.d/owncloud.conf;         test -e $f && dpkg-divert $f || true
```
are only for testing and that the executed commands are somewhere else (later)?
Or is the fix for updating to oC 8.1 and not implemented in this update to 8.0.4?

**Comment by jnweiger** [comment]
@deMattin You are right. This is addressed in upcomming 8.1 only.
https://build.opensuse.org/package/view_file/isv:ownCloud:community:testing/owncloud/debian.owncloud-config-apache.preinst?expand=1

**Comment by berni123** [comment]
Why don't you fix it in 8.0.x ? It should be no problem to remove this ugly bug. Each update runs into this wrong link ...

**Comment by deMattin** [comment]
I can confirm, that it works now the right way with the suse repository upgrade to 8.1 (Debian7, Apache 2.2):

1. in `/conf-available` the backup is done: `owncloud.conf.old`
2. in `/conf-available` a new conf is created: `owncloud.conf`
4. symlink `owncloud.conf` in `/conf.d` remains active
3. no wrong symlink `owncloud.conf.old` in `/conf.d` any more

( I upgraded from 8.0.4 to 8.1 via `apt-get`)

**Comment by jnweiger** [comment]
@deMattin thanks for confirming!
