### ISSUE TITLE
Recovered file shared as sharer can't be decrypted by sharee

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16199]
### Steps to reproduce

1. Enable encryption app.
2. Enable encryption module in admin page.
3. Relogin.
4. Create a user1.
5. Upload a file. 
6. Share file with user1
7. Remove file
8. Recover file from trashbin.
9. Login with user1 (Relogin if there is a warning about keys. PR pending).
10. Open file.

### Expected behaviour
user1 can open file.

### Actual behaviour
user1 can't decrypt file.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Updated from 8.0.3

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
```
### Client configuration

**browser**
Chrome 41

**Comment by MorrisJobke** [comment]
cc @th3fallen @schiesbn

**Comment by schiesbn** [comment]
I can reproduce it, unfortunately I don't see a quick solution. The problem is the following:

At this point in the encryption storage wrapper we want to update the share keys: https://github.com/owncloud/core/blob/master/lib/private/files/storage/wrapper/encryption.php#L239

But at this point in time the file cache has two entries, one for the file in the trash bin and one for the restored file and the file in the trash bin has the fileId we want to check. But because we run the key-update for the target we will check the shares for the wrong fileId and won't find them. 

Any idea how we could resolve this intermediate state of the file cache? Maybe @icewind1991 ?

**Comment by icewind1991** [comment]
Maybe have a way to pass either the source path or file id to the `update` method and get the list of users using that

**Comment by schiesbn** [comment]
> Maybe have a way to pass either the source path or file id to the update method and get the list of users using that

This was also my first idea. The problem is that in case of a folder the update method first needs to collect a list of all files because we need to update the keys for each files (and the files are already at the new place). In this case the approach with the ID wouldn't really work.

**Comment by schiesbn** [comment]
@SergioBertolinSG This PR should fix it, maybe you can give it a try: https://github.com/owncloud/core/pull/16228 ? Thanks!
