### ISSUE TITLE
Don't mention the oC version number when upgrading apps

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16272]
### Env

Oc 8.0

### Steps to reproduce

1. Go to app manager
2. Enable an app which doesn't make any modification to the database
3. Go to Files

### Expected result

Nothing should happen or if you have to ask the user to upgrade for some reason, then make it clear that this is about an app.

### Actual result

The user is presented with a page telling him that his ownCloud version x.y should be upgraded to version x.y, the exact same version. It is confusing.

**Comment by RealRancor** [comment]
Probably a dup of: https://github.com/owncloud/core/issues/14977

**Comment by oparoz** [comment]
Yep, thanks for finding it for me. I only looked for manager related issues...

**Comment by RealRancor** [comment]
@oparoz 
But just noticed that it was suggested to create a new issue about this at https://github.com/owncloud/core/issues/14977#issuecomment-84012612

**Comment by oparoz** [comment]
@RealRancor - Thanks!

**Comment by PVince81** [comment]
This should be an easy fix.
The code that populates the update page template should check if `needsUpdate()` is true because of version difference of core or apps.
See the two blocks here https://github.com/owncloud/core/blob/master/lib/private/util.php#L1435

**Comment by oparoz** [comment]
Yes, that's the code which mixes everything together:
https://github.com/owncloud/core/blob/1769de0a6d6fcdfe2bb17d5dea42693055ed8a83/lib/base.php#L345

using this template
https://github.com/owncloud/core/blob/1769de0a6d6fcdfe2bb17d5dea42693055ed8a83/core/templates/update.admin.php

**Comment by PVince81** [comment]
This update step is not triggered by DB updates directly, it's whenever the version specified in the code for an app differs from the version we have in the database. The update step would not only run DB upgrades, if any, but also run the app's "update.php".

Now one possibility would be to try and make this more intelligent and be able to detect in advance whether DB updates are required, and whether the app provides a "appinfo/update.php" file. If none apply, then simply increase the version in the DB.
Detecting that no DB changes are required at this time would need to diff the DB schemas.

For now in 8.2 let's just fix the UI to tell that it's about updating apps instead of core.

**Comment by oparoz** [comment]
> For now in 8.2 let's just fix the UI to tell that it's about updating apps instead of core.

Agreed. That's the confusing part for user.

**Comment by PVince81** [comment]
PR is here: https://github.com/owncloud/core/pull/17434

**Comment by PVince81** [comment]
CC @jospoortvliet if you want to add this to the dev update
