### ISSUE TITLE
Is "error" the correct message level for a cache not enabled?

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16287]
### Steps to reproduce

1. Install 8.1 
2. Check server log file for any messages

### Expected behaviour

The message level reflects the issue being reported

### Actual behaviour

Is the cache not being enabled an "error":

```
{"reqId":"prmEK\/9JlSXCTXF+drsJ","remoteAddr":"","app":"PHP","message":"xcache_clear_
cache(): Cache not exists at \/var\/www\/html\/owncloud\/lib\/private\/util.php#1338"
,"level":3,"time":"2015-05-12T15:24:35+00:00"}
```

Should this be a warning or info level message? 

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 1 (daily) Build:2015-05-12T03:08:46+00:00 20d2d8d3ddee2750343bdec69a3e7031b710039a

**Comment by LukasReschke** [comment]
This is caused by XCache at https://github.com/owncloud/core/blob/8e59d4c64b48ed7daeebb714e11213f7a22b5740/lib/private/util.php#L1276 where we are trying to reset the opcode cache with `XC_TYPE_PHP`.

I suspect that while XCache is installed its opcode component is not used. Unfortunately, the XCache API is not really properly documented and thus I don't know what API we would have to call to check whether the `XC_TYPE_PHP` cache is populated. In fact, there is an [open XCache bug](http://xcache.lighttpd.net/ticket/176) since 7 years that discusses this problem and is likely to never get fixed since XCache is abandonware.

Regarding the log level: This is actually a PHP error and thus will always get logged with a level of 3 per default. As a workaround for now I consider adding a `@` in front of it as legitim. I have done this with https://github.com/owncloud/core/pull/16293
