### ISSUE TITLE
External Storage: Using Mobile Apps and Sync Clients

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16306]
User Sync Client / Mobile Client
As an ownCloud user, I want to be able to sync my external storage files to my desktop and access them from my mobile phone, so that I can have my files at my fingertips - regardless of where they are stored.

Acceptance Criteria:
- The external storage directories work as any ordinary secondary storage, syncing and updating with the desktop as per the client configuration and the select folders
- Files updated directly in the external storage directories are updated in ownCloud
- When the password expires on the backend, the files are retained in the sync client and not deleted, until the user has an opportunity to log into the web interface and update their backend credentials.
- When the admin removes the SharePoint mount, the files and all access is deleted immediately from the user's account

**Comment by PVince81** [comment]
This already works right now.

The only missing part is about retaining files when password expired or the storage is temporarily unavailable. (we might want to reword the requirement or make a sub-ticket for this)

Regarding storage availability, all backends need to be adapted to properly detect such situations: https://github.com/owncloud/core/issues/11792

Additional work might be needed to also detect the "invalid password" situation and throw an appropriate exception, in a way that temporarily disables the storage (StorageNotAvailableException) so that the sync client ignores it.
In that specific case, we need to find a way to notify the client the reason of unavailability (ex: temporarily gone or password is invalid)

**Comment by davivel** [comment]
For the mobile clients, this will require to implement the "remote wipe" feature.

**Comment by DeepDiver1975** [comment]
@MTRichards @cmonteroluque 9.0 ???

**Comment by MTRichards** [comment]
I think it has to be, but we also have bugs like the timeout for external storage on large files, so we will need to think real hard about this one - for performance and architecture.

**Comment by cmonteroluque** [comment]
I thought large files on external was being addressed by @jmaciasportela. You have code for that already, in testing?

**Comment by PVince81** [comment]
Feature didn't make it into 9.1, also wasn't on the plan. Moving to 9.2

@DeepDiver1975 @dragotin

**Comment by PVince81** [comment]
@pmaier1 I'd move to backlog for now but add to the "stuff to make the feature more round" list

**Comment by pmaier1** [comment]
> @pmaier1 I'd move to backlog for now but add to the "stuff to make the feature more round" list
Fine!
