### ISSUE TITLE
Exception logger should sanitize potential sensitive data such as passwords

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#16318]
The exception logger should sanitize potential sensitive data such as the parameters passed to `OC_Login` and other functions.

In my opinion the best approach would be to go with a blacklist of functions and sanitize all parameters given to it. – We need however also apps to specify their own blacklisted function names as things might fail there as well :see_no_evil:

Thing is we simply don't know the user password and storing this in the PHP session is also a no-go from my opinion.

Excerpt from an affected log in the JSON error log.

```
OC\\\\User\\\\Session->login('test', 't3st')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(978): OC_User::login('test', 't3st')\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(878): OC::tryFormLogin()\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(840): OC::handleLogin()\\n#16 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115
```

Tentatively assigning 8.1, if the required change set is too big I will move this over to 8.2

Alternative proposals? @DeepDiver1975, @MorrisJobke, @PVince81, others?

**Comment by PVince81** [comment]
I wasn't aware that PHP would also add function parameter values in stack traces.

Now a little crazy idea: what if we store passwords inside a container class ?
```php
$password = new Password('tehpassword');
the_function_that_needs_id($uid, $password);
```

If the class is not serializable or has no toString() (is that a thing in PHP I guess?) its value would appear as "[Object]" or something in the log instead of the password.

But that might be a bit overengineered...

**Comment by LukasReschke** [comment]
> If the class is not serializable or has no toString() (is that a thing in PHP I guess?) its value would appear as "[Object]" or something in the log instead of the password.

Question if the call to `new Password('tehpassword')` would get logged then – I guess there are cases were it would. Though we would only have to sanitize one thing then :see_no_evil:

**Comment by PVince81** [comment]
Well that call would only be logged if this constructor throws an exception, which shouldn't be the case for a simple variable assignment.

Bonus feature: store the password with ROT13 or another symmetric encryption algo, so that it doesn't appear directly in plain text in memory. Then with a getter getValue() it would get converted back. Probably snake oil though ? :wink:

**Comment by DeepDiver1975** [comment]
@LukasReschke anything in the pipe for 8.1? otherwise let's move this to 8.2

**Comment by LukasReschke** [comment]
8.2

**Comment by MorrisJobke** [comment]
To trigger this just throw an exception before the return statement here: https://github.com/owncloud/core/blob/74237a9c44192fb98944ea7f3c14fa6f22c0814b/lib/private/user.php#L250-250

**Comment by DeepDiver1975** [comment]
@LukasReschke solution in the pipe? THX

**Comment by LukasReschke** [comment]
> @LukasReschke solution in the pipe? THX

@MorrisJobke ^?

**Comment by MorrisJobke** [comment]
I will try to propose something.

**Comment by MorrisJobke** [comment]
Possible short-term solution #19346
