### ISSUE TITLE
Deleting a shared folder removes the original folder

### ISSUE THREAD

**Issue by olunet** [owncloud/core#16313]
Environment -- owncloud server 8.1

Expected behaviour:
* user A shares a folder with user B
* user B unshares this folder and it disappears from his/her web-interface
* the original folder is still present in the A's web-interface

Real behaviour:
* user A shares a folder with user B
* user B unshares this folder and it disappears from his/her web-interface
* the original folder disappears from the A's web-interface, but can be found in the deleted files
* trying to restore the folder results in an empty folder without any files in it

The issue might be related to many other open/closed issues. I could find exactly the same problem with OC5 in closed issues: https://github.com/owncloud/core/issues/5044.

**Comment by MorrisJobke** [comment]
@PVince81 Didn't you tested exactly this?

**Comment by PVince81** [comment]
I tried the following:
1. Login as "root" (the admin)
2. Create a user "user1"
3. Create a folder "abc"
4. Share "abc" with "user1"
5. Login as "user1"
6. Delete the folder "abc"
7. Login as "root"
8. See that the folder is still there.

Works for me with 8.1 beta1 and master (dc362823e0d30b80be1ead90ef6d4ddb76fd1929)
Also works if I delete the folder through WebDAV instead of web UI with user1.

@olunet can you give more info which beta you are using ? How was the folder shared ? With group ? Reshared ?

**Comment by olunet** [comment]
To PVince81,
thank you for the testing. I repeated exactly what you did and it worked as expected with freshly created folders.
So, for some reasons, the same manipulations with the folder created before the update result in a different behaviour. Note, there are a number of specific details about my case: the folders were shared via groups; the OC instance has been recently moved to another server; then the sharing links broke and I had to reshared the folders; unfortunately, dublicates appeared (https://forum.owncloud.org/viewtopic.php?f=26&t=19541); removing the dublicates lead to removal of both shared and original folders. Facepalm.
I believe you could close this issue -- I shall contact the admins.

**Comment by PVince81** [comment]
Ok thanks. Seems like you might have bumped into the legacy storage issue: https://github.com/owncloud/core/issues/13980 which can be triggered when moving the data folder while the database still had old hard-coded absolute paths.
