### ISSUE TITLE
Adding Optional Key Store Locations and SSO Support with Encryption

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16341]
As an admin, I want to be able to store keys in a location other than on the ownCloud server so that I can use my enterprise key store, and use ownCloud SSO with encryption:

Acceptance Criteria:
- Admin can specify a key storage location in the control panel where the keys will be stored and managed by ownCloud
- The key store is used to provide keys to the ownCloud server so that we don't have to rely on the user's password to unlock their keys
- Keys should be stored encrypted (a system key on the ownCloud server)
- Key store server should somehow authenticate that the ownCloud server is talking to it (cert - or something?)
- Need instructions on how to securely connect to the external storage for the key store
- Two configuration parameters needed: 1) turn password encryption of keys on / off, and 2) turn key storage to another location on / off (to change the root of the key storage).
- Need a migration path for systems running today with local encryption that are moving paths

@schiesbn for your info, I took a stab above

**Comment by DeepDiver1975** [comment]
regarding SSO support: what about popping up a dialog where the use has to enter the password?
For both scenarios: initial key generation and decryption

**Comment by schiesbn** [comment]
> regarding SSO support: what about popping up a dialog where the use has to enter the password?
For both scenarios: initial key generation and decryption

This was also my "solution" in suggested in the past. It was rejected because it would add the need again to enter a password (also on desktop/mobile clients) which somehow is against the idea of SSO where we want to get rid if the burden to enter a password. I can see the point, still if you want to be really secure you need some interaction from the user to prove that the current user really is allowed to access the files. So that's a trade-off here and the idea of a key server can provide some more convenience even if it will most likely reduce the security level.

**Comment by MTRichards** [comment]
Adding two new acceptance criteria above (the last bullet).

**Comment by schiesbn** [comment]
The easy solution here is to allow the user to change the root of the key storage provided by core and add a setting to the encryption app to disable password protection of the private key and define the root of the key storage.

**Comment by schiesbn** [comment]
Here I implemented the option to change the root of the key storage: https://github.com/owncloud/core/pull/17899

Something you should know and where I maybe diverge a bit from the original requirement cc @MTRichards :

- The root always need to be in the data folder. So you either need to mount the new root directly to a folder in data/ or create a link to it. Reason: Keys needs to stay in data/ in order to use our OC\Filesystem operations to manipulate the keys

- Key root is not configurable in the admin panel but as a config.php option. You also need to migrate the keys from one root to the new one with a occ script. That's the more secure way and I would like to avoid that people see this as a simple option like every other option and change it all the time. This should be a well informed decision. I also documented it in the config.sample.php: https://github.com/owncloud/core/pull/17899/files#diff-2f769bc01ffefdf14eb04404218e7582R947
