### ISSUE TITLE
Alphabetize the shortcut links in the left panel on the admin page

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16362]
### Steps to reproduce

1. Install 8.1 
2. Navigate to the admin page

### Expected behaviour

The shortcut links in the left panel are in alphabetical order

### Actual behaviour

The shortcut links in the left panel are in not alphabetical order

![p346](https://cloud.githubusercontent.com/assets/8480343/7640128/5391f310-fa4f-11e4-8eb7-2f38aaa1fa99.PNG)

### Server 1 Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 1 (daily) Build:2015-05-13T03:08:44+00:00 b626de0b9f135e2993496a8d18f3200dfab72337

**Comment by nickvergessen** [comment]
### Actual
The entries are sorted in the order of appearance on the actual page.

@jancborchardt I htink alphabetic also makes a bit of sence, but I have no really preference.

**Comment by nickvergessen** [comment]
What might be a bit confusing is, that admin is then sorted alphabetically and all others are sorted by appearance. sometimes ordering alphabetically makes no sense.

**Comment by jancborchardt** [comment]
They are not sorted alphabetically because alphabetic sorting makes no sense in this context. »Security & setup warnings« for example should always be at the top of the page.

They are sorted by importance, that is sharing and encryption up top and everything else below. At some point they are sorted alphabetically, but alphabetically by app name. The display name unfortunately varies, also for different languages. So this is not really something we can solve since otherwise the order would be different for everyone.

@jnfrmarks does that work for you as explanation?

**Comment by jnfrmarks** [comment]
@jancborchardt 

works for me.
