### ISSUE TITLE
Add Ability to Disable Download of Entire Folders

### ISSUE THREAD

**Issue by vseven** [owncloud/core#16370]
There used to be a option that disabled ZIP downloads but it was removed.  I would like to see that added back in so a user cannot download a entire directory that may contain thousands of files as a zip file.  Please see forum post https://forum.owncloud.org/viewtopic.php?f=29&t=28031&sid=d1e238840c5b3a661da801a12c83126b&p=87274#p86121 for more information.

**Comment by verfolger82** [comment]
I second this.

There is a typical situation, when I need to allow users access any of the files, but prevent them from grabbing all the files at once. I used ownCloud as a solution before v7. I could disable zip download at all, and there was even a flexible mechanic to limit maximum zip size to something small, so copying all the 10GB library of 10 thousand files would be rather a tedious process, not a few clicks.

AFAIK, all these limiters were created to manage CPU load and bandwidth before zipstreamer was implemented in v.7. But they worked perfectly as a security solution.

Bring them back please! :) "allow .zip download" checkbox in folder access rights would be perfect. Removal of "Download" button for all the folders would also suffice.

**Comment by PVince81** [comment]
The reason why the limit existed was because before OC 7 ZIP files were created into a temporary directory. In such cases, it could happen that there isn't enough space in the temporary directory so admins could choose to disable or limit this feature.

Since OC 7 ZIP files are created on the fly, so no temp space is needed any more. So there was no more use for that limitation. It shouldn't cause any performance issue.

Now the case you are mentioning is a different use case. I wouldn't really call it "security" solution because a clever user could still grab all download links with a script, or use WebDAV to download/sync the whole folder. It's a bit like websites trying to block right click to prevent people from saving pictures with "Save as link".

I'll tag this as enhancement for now.

**Comment by verfolger82** [comment]
I disagree.
How many users can write scripts and use DAV? 1 out of 10? Or out of 1000?
You cannot create protection from clever users. But protecting it from most of the users actually solves most of security issues :) "use of WebDAV extensions or sctipting required to copy the base" is acceptably secure, "1 click required" is not.

**Comment by RealRancor** [comment]
A user can simply use the sync client to download all files without any knowledge about WebDAV.

**Comment by verfolger82** [comment]
In my network users cannot install software on their own )
And they mostly don't even understand what owncloud is and how powerful it is :) But allowing admin to disable sync for all the storage (or only allow it for selected folders) would also be nice. 
Like i said, mass copying must not always be allowed. There must be a possibility to make copying everything either boring or demanding some knowledge.

**Comment by mmccarn** [comment]
+1 for this enhancement.

My first test user decided she needed to 'download' the entire corporate network...

A config option to disable folder downloads from a browser would be very helpful; failing that, a warning message to the user would be better than nothing ('You're attempting to download a folder containing x files and y MB.  Are you sure you mean to do this?')

**Comment by PVince81** [comment]
A warning sounds like a sensible option. The good part is that the UI already knows how much data there is, so if someone attempts to download a folder containing more than 100 MB they could get a warning. Which sizes would make the most sense ?

**Comment by macdabby** [comment]
I see this was closed but I didn't see any final resolution.

Another great reason to disable zips is that I have directories with tens of gigs of video files that I send to clients. They all want to press the download folder button which tries to zip them all. This results in connection timeouts and high CPU load that's really unnecessary since putting 2 files at 5gigs each into a 10 gig file doesn't save any space or time.

This is a security issue as multiple users trying to do the same could spawn multiple zip threads all competing for system resources, and users retrying because it failed the first time could spawn even more threads compressing the same files.

**Comment by RealRancor** [comment]
@macdabby This issue is still open. Only a referenced issue one above your post is closed. :-)

**Comment by Stewalker1985** [comment]
Hi everyone. 
I have a similar issue to this and implementation of disable full folder download is greatly needed. I have a large library of manuals and software which I originally shared with other users via box.com. This became to large and costly so decided to host myself using owncloud. Issue I have is when using box I had the option to allow individual users individual rights in individual folders. For example a user could freely download any files in one folder but could view only in another folder and this was perfect. It prevented all data being downloaded in a single click. Since running owncloud I've learned this runs differently and is more of a solution to allow users access to create and store files themselves and not a sharing solution as such. I don't really need users to have there own storage capacity I need to simply share my own data but with access limitations so perhaps owncloud isn't the solution for me. As of now I've been unable to fully open up owncloud to all users I previously had on box as I'm certain serval of these User will attempt to download the whole directory. If I could set limitations for users then I could open this up to all users to hoping this can be put in place. 
That said this is a very powerful piece of software with great features for the target is made for.

**Comment by dnviti** [comment]
As i read this in 2017, we need the implementation too.
We need to grant user access or download to external smb folders, preventing users to download hundreds of gigabytes of data...
And also for security reasons particular users should not be allowed to download some kind of data if not authorized to.
Please think about this possible implementation, it is almost the only reason we need owncloud for: using it only as "cloud" to share data between users is quite limiting...

**Comment by vseven** [comment]
Gave up on this and switched to Pydio as it had this as a simple option.  Closing my issue.

**Comment by phil-davis** [comment]
I can think of a few use cases for disabling the zip download feature:

- my 80+ year old mother, I share some videos in a folder to my family members. Really I want them click on individual videos to download the ones they want. My mum has no idea what a zip file is, or how to unpack it or... (this really happened to me)
- the office workers who also have no idea what a zip file is, and really are intended to be just working in real-time with the documents (discussed above)

The "problem" is that there will be all sorts of ways to specify the matrix of cases when zip download should be disabled:

- by user - have a user attribute "no UI zip download" (that would cover my 2 use cases above)
- system wide - but maybe nobody would actually want/use a system-wide disabling
- by folder - have a folder meta-data attribute "no UI zip download" (covers use cases for folders that are really big with just a few video files, and you do not want people accidentally starting 20GB zip file downloads...)
- specify a max zip download size (folders bigger than that would have the zip download disabled automatically)
- 100 other fun ways to specify rules to decide if zip download should be disabled (this is the problem part - people will come up with all sorts of interesting ways to specify it, resulting in settings checkbox bloat)

Note: mentions of "security" above are not relevant. This is not a security feature, it is just a convenience to avoid accidental use of zip download in certain cases.

**Comment by PVince81** [comment]
@phil-davis great examples.

I think easiest would be to specify a max folder size for which the button simply disappears. I wouldn't bother to block the ZIP download URL as it's only protecting against accidental downloads.
The web UI already has access to the current folder size in the folder PROPFIND, so this could work.

Note: need special care for the case where some subfolders haven't been scanned yet (size=-1) in which case we cannot anticipate the current folder size.

Estimate: 0.5-1md for this.

cc @pmaier1

**Comment by CRCinAU** [comment]
Yeah - so this should be a standard option. I have a public folder which I throw random firmware in for stuff - and people hit the download as zip button all the time - which starts archiving up about 1-2Gb of firmware...

Best part is that I can't stop people... They end up DoS'ing the server as it takes ages, so they click it again. and again. and again.

Its got to be one of the dumbest features I've seen in ownCloud...

**Comment by mmccarn** [comment]
It would be a crude but we could configure the web server to block all access to URLs that contain "files/ajax/download.php?dir=".  I'll test this out over the weekend and post some code for Ubuntu/Apache and/or .htaccess

**Comment by CRCinAU** [comment]
I'd even be happy with an option to disable folder downloads for public folders...

**Comment by mmccarn** [comment]
Note: this technique was tested on Nextcloud 12 / Ubuntu 16.04 / Apache 2, but should also work on Owncloud

Adding these two lines to <OC>/.htaccess inside <IfModule mod_rewerite.c>...</IfModule mod_rewrite.c> turns the 'download' link for folders into a shortcut back to the user's root:

```
<IfModule mod_rewrite.c>
  RewriteEngine on
  ...
  RewriteCond %{THE_REQUEST} ^.*/files/ajax/download.php\?dir\=.*\&downloadStartSecret.* [NC]
  RewriteRule ^(.*)$ / [R=301,L]
</IfModule>
```

File downloads do not show "download.php" in THE_REQUEST -- they use "webdav" instead -- so individual files are still downloadable.

Admin users will see a file integrity error about ".htaccess" after making this change, and the edit will need to be applied after every update.

**Comment by PVince81** [comment]
If you're anyway trying to hack around with htaccess and get integrity check errors, you could simply go to the web UI and hide the button. Or hide it with CSS in a theme.

A proper fix could have a new setting stored in "oc_appconfig" and switch the visibility of the button according to the setting. For extra hardening, the setting would also need to throw a 403 forbidden error in the backend endpoint.
