### ISSUE TITLE
Encryption "on" and password reset makes all files ureadable

### ISSUE THREAD

**Issue by VincentvgNn** [owncloud/core#16388]
### Description
When the encryption app is on and a user resets his password, all files cannot be red anymore.
The system does not ask for the recovery password that has been set before.
Login with the new password works, but it looks as if all files did not get the right updated keys.

### Steps to reproduce
1. Let the Admin enable the encryption app and enable/set the password for the recovery.
2. Create a new user and enable the the password recovery there as well. 
3. Drag a simple test file into the WebUI of the new user. The test file will be encrypted and can be opened or downloaded again. So far all OK.
4. Log off the new user, login with a bad password and ask for an email for the password reset. 
5. Use the email's link to open a new window. A warning about the risk of the password reset follows. Check "I know what Im doing", enter the new password and press "Reset password".
6. Log in using the new password. --> Files are unreadable and cannot be opened or downloaded anymore!
 
### Expected behavior
At a reset the system should ask for the recovery password and create  the right new encryption for all files.

### Client configuration
n.a.

### Server configuration
ownCloud version: 8.0.3 (stable)
List of activated apps: default apps + encryption
External storage: no
Encryption: yes

OC server installed at a web-hosting company. 4-5 GB storage.
Control via DirectAdmin and installation by using Installatron.
Own (non-shared) IP and using https.
Operating system: Linux Hosting Package
Web server: Apache
Database: MySQL
PHP version: 5.5.21

**Comment by PVince81** [comment]
@schiesbn @th3fallen

**Comment by VincentvgNn** [comment]
This bug could be the result of the latest decision at #11395

**Comment by schiesbn** [comment]
> When the encryption app is on and a user resets his password, all files cannot be red anymore.
The system does not ask for the recovery password that has been set before.
Login with the new password works, but it looks as if all files did not get the right updated keys.

That's by purpose because you, the user, typically don't know the recovery password but only the admin. So it doesn't make sense to ask for the recovery key password on the "reset password" page. What the admin needs to do in order to recover the users files:

- go to the user management
- enter the recovery key
- change the password of the user who lost his password.

-> the user should be able to login with the new password and access his files again
