### ISSUE TITLE
Content Security Policy error! 

### ISSUE THREAD

**Issue by birdsystem** [owncloud/core#16449]
### Steps to reproduce
1.Go to my repository and download conferencia app 
2.Enter the Conferencia APP 
3.go to your browser's javascript console
4.see the error! 

### Expected behaviour
There is a folder in / templates where there is a working script, the normal behavior would generate a token so that the page was loaded when you click the button to start the conference, it needs to request access the webcam and start broadcasting

### Actual behaviour
the token is not generated and the console shows errors in the "Content Security Policy"

### Server configuration
Linux Debian Wheezy 7

**Web server:**
Apache2
**Database:**
Mysql
**PHP version:**
PHP5
**ownCloud version:** (see ownCloud admin page)
8.0.1

#### Browser log

a) The javascript console log
Refused to frame 'https://cdn.webrtc-experiment.com/getIceServers/' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by DeepDiver1975** [comment]
@LukasReschke can you help out here? THX

**Comment by DeepDiver1975** [comment]
@birdsystem basically you are trying to iframe an external resource - we disallow this for security reasons. But there are ways around this. @LukasReschke knows the magic ...

**Comment by birdsystem** [comment]
Thx @DeepDiver1975

@LukasReschke Can you help me with this? rs

**Comment by LukasReschke** [comment]
ownCloud uses a secure by default security model and thus employs security measures such as the Content-Security-Policy (CSP), in this case this is exactly what is causing problems.

In a nutshell: CSP is a header that allows instructing any modern decent browser (which as usual excludes Internet Explorer :see_no_evil:) to not load specific resources or forbid potential dangerous actions. Especially we forbid the loading of any remote JavaScript resource and inline JS to forbid Cross-Site-Scripting attacks.

Your application is loading external JS and CSS and trying to execute this, this is forbidden by default as it makes CSP pretty useless from a security point of view. (it does not mean your app is necessarily insecure, CSP is just an additional layer of defense, though a very good one because even if you do mistakes it prevents actual exploitation.)

You can change this by setting a custom content security policy. Please note that this is a 8.1 (aka master) feature only and not available in older releases. In such cases you can manually adjust the CSP policy in config.php (see config.sample.php for details) though I'd *highly* recommend against this and wait for 8.1 when deploying this application:

```php
public function index() {
	$params = ['user' => $this->userId];

	// Custom Policy that allows all kind of stuff
	$policy = new ContentSecurityPolicy();
	$policy->addAllowedFrameDomain('*');
	$policy->addAllowedStyleDomain('*');
	$policy->addAllowedScriptDomain('*');
	$policy->allowInlineScript(true);

	$response = new TemplateResponse('conferencia', 'main', $params);  // templates/main.php
	$response->setContentSecurityPolicy($policy);

	return $response;
}
```

We have documented this behaviour also at in our [documentation](https://doc.owncloud.org/server/8.1/developer_manual/app/controllers.html?highlight=csp#modifying-the-content-securicy-policy) – please notice that this is not the final documentation and it still requires some quirks from me as the noted default permissions are not correct. But you should get what it does. 
Please also read https://statuscode.ch/2015/04/content-security-policy-and-ownCloud/ for more details.

**Comment by LukasReschke** [comment]
`*` acts as a wildcard, specifying specific domains would be better but I don't know what your code has to connect to etc…

**Comment by birdsystem** [comment]
I got it!
I entered the contentsecuritypolicy.php and added the exceptions in variables

Thank you very much for your help!

PS: There is some content about sharing this page to another User? the script that I have created that it was a public page so when a second User want to enter the conference with the generated token, he could do that!

thanks again
