### ISSUE TITLE
Undefine variable OC_Channel

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#16574]
@VicDeo please fix - thx

![bildschirmfoto von 2015-05-27 10 21 16](https://cloud.githubusercontent.com/assets/1005065/7831792/27abba64-045a-11e5-900f-c40227721570.png)

**Comment by LukasReschke** [comment]
That is black magic we have since ages :see_no_evil:  – Stumbled upon this as well in the past but was :see_no_evil: ;-)

It includes version.php at https://github.com/owncloud/core/blob/3babcd034438476aa87c1b970d6cfa98f2ded625/lib/private/util.php#L378 which has this variable https://github.com/owncloud/core/blob/3abc6e6c44cae59ced68e7e498d78debd74f3534/version.php#L32

Ideas how to change this?

**Comment by VicDeo** [comment]
@DeepDiver1975 
it's defined and loaded from version.php like 
`$OC_Version`, `$OC_VersionString`, `$OC_Build`

**Comment by DeepDiver1975** [comment]
> it's defined and loaded from version.php like
> $OC_Version, $OC_VersionString, $OC_Build

yes - but the ide is still crying for OC_Channel - where as it's not crying for OC_Build ...

**Comment by VicDeo** [comment]
@DeepDiver1975 I guess  `/** @var $OC_Channel string */` should be enough, will check it.

**Comment by DeepDiver1975** [comment]
> That is black magic we have since ages :see_no_evil: – Stumbled upon this as well in the past but was :see_no_evil: ;-)

I know - we shall fix this some day ...

**Comment by VicDeo** [comment]
@DeepDiver1975 
>yes - but the ide is still crying for OC_Channel - where as it's not crying for OC_Build

Let's start an IDE war
Netbeans crying for both ;)

**Comment by MorrisJobke** [comment]
Fixed with #16592
