### ISSUE TITLE
Changing share permissions should trigger an etag change

### ISSUE THREAD

**Issue by ckamm** [owncloud/core#16587]
As discussed with @guruz @ogoffart @PVince81: Whenever file metadata (mtime, permissions, ...) changes, the parent folder's etag should change. That notifies sync clients and allows them to check for changes.

The particular issue here is that changing the permissions of a share (readonly<->readwrite) does not trigger an etag change. Therefore the sync client does not notice that the permissions of the shared files have changed.

Required for owncloud/client#3244

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/16589 for the other metadata/properties

**Comment by PVince81** [comment]
@DeepDiver1975 @karlitschek @cmonteroluque scheduling for 8.2.
Please adjust tags if necessary.

**Comment by PVince81** [comment]
CC @icewind1991 FYI

**Comment by cmonteroluque** [comment]
Dependency for owncloud/client#3244 as reason to fix in 8.1

**Comment by DeepDiver1975** [comment]
> Dependency for owncloud/client#3244 as reason to fix in 8.1

This would require to change which might have a too big impact on the overall system.
@PVince81 was absolutely right to schedule this for 8.2

Furthermore @dragotin and myself had a discussion recently if we should introduce a second etag which changes only on meta data modifications - where as the original etag is only to be used for content changes.

Topic to be discussed -> 8,2

**Comment by guruz** [comment]
> Furthermore @dragotin and myself had a discussion recently if we should introduce a second etag which changes only on meta data modifications - where as the original etag is only to be used for content changes.

No need to do that, just change the directory etag (up to the root as usual) and the sync client can re-PROPFIND the directory to get the meta data of each file in a dir.

**Comment by PVince81** [comment]
@icewind1991 can you evaluate the complexity and impact ? Thanks

**Comment by DeepDiver1975** [comment]
> No need to do that, just change the directory etag (up to the root as usual) and the sync client could re-PROPFIND the directory to get the meta data of each file in a dir.

I had a different impression on this while talking to @dragotin - anyway nothing to think about right now.

**Comment by DeepDiver1975** [comment]
@cmonteroluque please move to 8.2 - THX

**Comment by dragotin** [comment]
@guruz I am not sure that changing the ETag of directories is enough. Do you mean that only the ETag of the directory and **not** the one of the individual file should be changed? That could work, but we have to double check if the client updates the changed meta data on its side, if no individual file ETag has changed.

Otherwise, if the ETag of the individual file that has a changed permission would change, the client would redownload the file, even though that is not needed. That is why I thought of a kind of "meta-data ETag".

**Comment by guruz** [comment]
@dragotin No it does not :) We'll need an ```UpdateEtagJob``` in the client for the behaviour that @ckamm @ogoffart and me had discussed. @ckamm Did you create a client-side issue for this?

@dragotin Changing the ETag of the file when the permissions/metadata changed would be the simple behaviour that always works (also currently) but however would get the client to re-download possibly a lot of things.

**Comment by ogoffart** [comment]
Changing the etag of the parent directory is enough.
When the etag of the parent directory changes, the client will do an PROFPFIND with depth 1 on the directory and that will fetch all the metadata of every file in that directory.  Then if the permissions or other metadata changed (but not the etag) the flag `should_update_etag` is set which means we will re-write the entry into the database.

And we should not change the etag of the file when the permissions changes otherwise we would need to download it again and that is not good.

**Comment by dragotin** [comment]
ok, thanks @ogoffart, that's a clear explanation.

**Comment by PVince81** [comment]
Do will still want this addition for 8.2 ? Is there an agreement to implement this on the server already ?

@DeepDiver1975 @icewind1991 @cmonteroluque

**Comment by cmonteroluque** [comment]
@PVince81 yes, we do want it.

**Comment by PVince81** [comment]
I guess we'll need a new sharing hook "post_changesharepermission". Then hook it up with Shared_Updater like the other hooks and trigger `correctUsersFolder()` for each recipient which will update the etag of every parent. Not sure about nested reshares though. @icewind1991 

Another tricky piece is to detect that only the permissions of a share has changed (and nothing else) inside the share.php jungle. @rullzer @schiesbn

**Comment by icewind1991** [comment]
We could maybe trigger the same etag propagation for shares which is used for writes

**Comment by DeepDiver1975** [comment]
@icewind1991 can I ask you to come up with a PR on this? THX

**Comment by icewind1991** [comment]
Will look into it

**Comment by icewind1991** [comment]
PR is here: #19511
