### ISSUE TITLE
PHP Problem: always_populate_raw_post_data

### ISSUE THREAD

**Issue by bigtreiber** [owncloud/core#16614]
I'm running Owncloud 8.0.3 and always get the error message:
Cronjob encountered misconfiguration

It was not possible to execute the cronjob via CLI. The following technical errors have appeared:	
PHP is configured to populate raw post data. Since PHP 5.6 this will lead to PHP throwing notices for perfectly valid code.
To fix this issue set <code>always_populate_raw_post_data</code> to <code>-1</code> in your php.ini

### Server configuration
**Operating system**:
Debian Jessie

**Web server:**
Apache 2.4.10

**Database:**
mysql 5.5.43

**PHP version:**
5.6.7-1

**ownCloud version:** (see ownCloud admin page)
8.0.3

**Updated from an older ownCloud or fresh install:**
updated from 7

**List of activated apps:**
Activity
Bookmarks
Deleted Files
File Locking
First Run Wizard
Mail Template Editor
PDF Viewer
Pictures
Provisioning API
Share Files
Text Editor
Versiond
Video Viewer

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'ocyho5hmixd6',
  'passwordsalt' => 'salt',
  'secret' => 'secret',
  'trusted_domains' =>
  array (
    0 => 'thorin',
    1 => 'www.sascha-kissner.de',
  ),
  'datadirectory' => '/mnt/daten/owncloud',
  'overwrite.cli.url' => 'http://thorin/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => yyy',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'sascha.kissner',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'gmx.net',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome 43

**Operating system:**
Windows 7

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
Doesn't seem to work ... last logfile is from 2/26/2015

{"reqId":"484aa3179874cd8562403c1a56ca52ac","remoteAddr":"192.168.2.10","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#168","level":3,"time":"2015-02-26T21:20:12+00:00"}

**Comment by LukasReschke** [comment]
Mhm. Probably for CLI we can avoid this check. Will dig into this…

**Comment by RealRancor** [comment]
@LukasReschke I'm not sure if this is the same problem/user but there was a user reporting that this message is show even if apache and cli was configured correctly:

https://forum.owncloud.org/viewtopic.php?f=31&t=26352#p88294

**Comment by bigtreiber** [comment]
@RealRancor Yes, that's me, same user. I shoul add that i checke with phpinfo that the option "always_populate ..." = -1 is set correctly for both php and /php/cli

**Comment by cluelessperson** [comment]
Server configuration

Operating system:
Ubuntu 14.04.2 LTC

Web server:
Apache 2.4.7

Database:
mysql 5.6.19

PHP version:
5.6.9-1

ownCloud version: (see ownCloud admin page)
8.0.3 (stable)

Updated from an older ownCloud or fresh install:
Updated PHP to 5.6, Owncloud from 8.0.2 to 8.0.3

List of activated apps:
Activity
Deleted Files
Disable Remember Login
Documents
External Storage Support
External User Support
File Locking
First Run Wizard
Imprint
Mail Template Editor
PDF Viewer
Provisioning API
Rainloop (encrypted email)
Share Files
Text Editor
Updater
User OTP Extension
Versions
Video Viewer

The content of config/config.php:

<?php
$CONFIG = array (
  'instanceid' => 'something',
  'passwordsalt' => 'SECRET_SAUCE',
  'secret' => 'SECRET_RECIPE',
  'trusted_domains' =>
  array (
    0 => 'cluelessperson.com',
    1 => '192.168.0.251',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://cluelessperson.com/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '64CHAR_PASSWORD',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'loglevel' => 4,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'cluelessperson.com',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '25',
  'theme' => '',
  'maintenance' => false,
);


Are you using external storage, if yes which one: local/smb/sftp/...
No, although the App Enabled.

Are you using encryption: yes/no
Yes.  SSL/TLS 1.2

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
no  Mysql

Client configuration

Browser:
Chrome 43

Operating system:
Windows 7x64

Logs

Web server error log

Insert your webserver log here
ownCloud log (data/owncloud.log)

/var/log/owncloud.log is blank.

Admin owncloud log is showing countless errors by webdav, but I think those are regarding a full hard drive.

OCC RESPONSE
sudo -u www-data php occ upgrade
PHP is configured to populate raw post data. Since PHP 5.6 this will lead to PHP throwing notices for perfectly valid code.  To fix this issue set always_populate_raw_post_data to -1 in your php.ini

.....

While typing this up... it suddenly went away.  I have no issue anymore...

**Comment by LukasReschke** [comment]
Will be fixed with 8.0.4 due to https://github.com/owncloud/core/pull/16102

**Comment by bigtreiber** [comment]
The issue still exists in Version 8.1.0 stable

**Comment by Xenopathic** [comment]
@bigtreiber The code that causes this warning does not exist in ownCloud any more, please check you cleared your opcache/restarted PHP after updating.

**Comment by bigtreiber** [comment]
I just rebooted my machine, the problem still exists :-(

**Comment by bigtreiber** [comment]
Any suggestions? How do I clear my opcache?

**Comment by bigtreiber** [comment]
The Problem still exists with 8.1.3 ... what can I do?

**Comment by moritzha** [comment]
I'm getting the same error while running 8.2.1

PHP	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0

**Comment by RealRancor** [comment]
Have you followed the message and updated your PHP environment accordingly?

Btw. thats a deprecation warning, no error :-)

**Comment by moritzha** [comment]
I set always_populate_raw_post_data to -1 as suggested and checked it with phpinfo.
I'm still getting this deprecation warning with php-version 5.6.15.

Any advice? It's a shared-hosting environment so I'm limited in configuration options.

**Comment by RealRancor** [comment]
@moritzha Depending on your environment you also need to set this within the php.ini of the CLI version of PHP (On debian/ubuntu something like /etc/php5/cli/php.ini). This is then only checkable from commandline with:

```
php -i | grep always_populate
```

Btw. mine is set to 0 instead of -1 and i don't get this warnings. If its on a shared hosting you also might want to contact the support of your hoster.

**Comment by moritzha** [comment]
@RealRancor Strange thing is accessing $HTTP_RAW_POST_DATA on a test-file is throwing an undefined-error, meaning -1 is working but owncloud is managing to get php throwing those depraced-warnings. I'm trying to get a specific pointer on this warning.

**Comment by Christoph-Wagner** [comment]
Both cli and apache2 have the proper value of -1
Version is 8.2.2 on Debian.
The warning still appears
"PHP is configured to populate raw post data. Since PHP 5.6 this will lead to PHP throwing notices for perfectly valid code. To fix this issue set <code>always_populate_raw_post_data</code> to <code>-1</code> in your php.ini"
