### ISSUE TITLE
[concurrency] Access newly shared encrypted folder before all keys are ready

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16621]
### Steps to reproduce:
1. Enable encryption + default encryption module
1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create a folder "enc"
1. Create three files "enc/a.txt", "enc/b.txt", "enc/c.txt" with some random text inside
1. Add `sleep(30);` here https://github.com/owncloud/core/blob/master/lib/private/encryption/update.php#L179 to slow down key updates on share
1. Share "enc" with "user2"
1. Login as "user2"
1. Try downloading the files in "enc"

### Expected result
Either "enc" doesn't appear until the keys are generated, or the files are locked on download.

### Actual result
Exception: cannot decrypt this file.

### Versions
Tested on the file-locking branch: https://github.com/owncloud/core/pull/16237 which is based on ownCloud 8.1 git master.

@icewind1991 we might want to acquireLock also on share/unshare of a folder ?

CC @schiesbn FYI

**Comment by schiesbn** [comment]
locking could be one approach. Because this is not only a encryption issue. Same could happen for any other post-hook which took some time.

Just because you might ask why we don't generate the keys in the pre-hook. But...
... we can't re-calculate the new shares before they exists (well, probably we could with enough overhead)
... it would leave us with wrong share keys if the share operation after the pre-hook fails

**Comment by PVince81** [comment]
My point here was mostly to find a good test case that illustrates the need to start the lock before the prehook and release it after posthook :smile:

**Comment by schiesbn** [comment]
I removed the encryption label, while the problem was demonstrated with encryption it is not a encryption bug but a general problem which will be addressed with files locking.

**Comment by PVince81** [comment]
This should be fixable with https://github.com/owncloud/core/issues/17243.
Closing as duplicate
