### ISSUE TITLE
Experimental file locking and redis packaging

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16728]
@jnfrmarks @jnweiger 

So far on 8.1 the experimental file locking is still experimental and disabled by default.

At some point if it works as intended, if we decide to enable it by default, it means that the packages might need to require php5-redis and redis.

CC @karlitschek @icewind1991

**Comment by PVince81** [comment]
CC @MTRichards 

Maybe it should be enabled in appliances, for testing ?

**Comment by MTRichards** [comment]
This is the file locking app introduced in oC 6, right?
@jnfrmarks how are we on testing coverage and feeling that this is not going to break if we turn it on in the appliance by default?

**Comment by PVince81** [comment]
No, nothing to do with the file locking app.

This is high-level file locking #11804, the new experimental locking on a different level. This is disabled by default.

**Comment by PVince81** [comment]
We should probably look for a more catchy name for "experimental file locking" or "high-level file locking" to avoid confusion. How about Locky ? :wink:

**Comment by DeepDiver1975** [comment]
> At some point if it works as intended, if we decide to enable it by default, it means that the packages might need to require php5-redis and redis.

I'd really leave this to the admin to install this manually if required.
Furthermore I assume we will support some more key-value-stores in the future.

**Comment by jnweiger** [comment]
Added a note to https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.1:testing/owncloud/README.packaging?expand=1 as hint to the admin.
I am not directly pulling redis dependencies for now.

**Comment by DeepDiver1975** [comment]
@PVince81 if you agree I'd like to close this issue then - THX

**Comment by PVince81** [comment]
I raised this because it was a concern of @jnfrmarks.
So I'll let her decide :smile:

**Comment by jnweiger** [comment]
@MTRichards @jnfrmarks If it makes sense to pull in redis into the appliance, please let me know. The redis binding for php that I see in openSUSE looks strange to me. I'll have to investigate before we can add it to the appliance.

**Comment by MTRichards** [comment]
I understand, thanks @PVince81 
Since this is the all new file locking core, I would prefer not to have our customer's first demo of the product produce an experimental disaster in the appliance. If we are going to push all this out with 8.1, then yes - we should build an appliance of it for testing, but not replace the website appliance yet. That can't happen until 8.1 subscriptions are launched.

If the appliance will require redis once 8.1 here, we will need to make an appliance with redis, sure - and test that. Then we will replace the current website appliance with the new appliance at the launch of 8.1 Subscriptions in August. oC server launch does not replace the current appliance, since customers can't buy anything yet (equal to old community edition launch). Until we are ready to support the product capabilities in 8.1 subscriptions (formerly enterprise edition), we keep the appliance as it is.

**Comment by SergioBertolinSG** [comment]
Please note that installing php5-redis in ubuntu 14.04 is not enough for using redis in owncloud since it needs a version >2.2.5 and it provides 2.2.4. 

So manual upgrade is required following this steps:

Upgrade to version 2.2.5+  from http://stackoverflow.com/a/30490869/2085469

Download the 2.2.7 package here: http://pecl.php.net/package/redis
```
 php -i | grep Redis >>>> Redis Support => enabled Redis Version => 2.2.4
```
```
 phpize
 ./configure [--enable-redis-igbinary] 
 make
 sudo make install
```
Create a symlink for command line cli package: 
``` 
cd /etc/php5/cli/conf.d && sudo ln -s ../../mods-available/redis.ini 20-redis.ini
```
```
 php -i | grep Redis >>>> Redis Support => enabled Redis Version => 2.2.7
```

**Comment by DeepDiver1975** [comment]
THX for the info @SergioBertolinSG

**Comment by DeepDiver1975** [comment]
I will anyhow close this issue because there is nothing to do for us for 8.1
