### ISSUE TITLE
Able to delete folder when file locking is enabled

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16769]
### Steps to reproduce

1. Install 8.1 
2. Enable and configure file locking in config.php
3. In browser 1, create a folder "abc" and upload a 4gb file into the folder
4. In brwoser 2, log in as the same user and delete the folder

### Expected behaviour

User gets a message that the folder is locked and the folder is not deleted

### Actual behaviour

The folder is deleted.

Scrubbed config.php:

```
<?php
$CONFIG = array (
  'supportedDatabases' =>
  array (
    0 => 'mysql',
    1 => 'pgsql',
    2 => 'oci',
    3 => 'mssql',
  ),
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'x.x.x.x',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://localhost',
  0 => 'x.x.x.x',
  'dbtype' => 'mysql',
  'version' => '8.1.0.6',
  'dbname' => 'owncloud',
  'dbhost' => 'x.x.x.x',
  'dbtableprefix' => '',
  'dbuser' => 'oc_at_admin',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => '',
  'license-key' => '',
  'filelocking.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '127.0.0.1',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'loglevel' => 0,
  'ldapIgnoreNamingRules' => false,
);


```

### Server 1 Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-03T03:09:05+00:00 1cccb227c398d3c5428672aaf9cf6b14e248e5f7

**Comment by PVince81** [comment]
To clarify, @jnfrmarks uploaded the 4gb file with the web UI. @jnfrmarks please always clarify in such cases, because the code path for WebDAV (which uses PUT) and the web UI are very different. You might want to try again using cadaver + put of the same file.

I think the reason for this is because while the huge file is being uploaded, PHP hasn't passed it yet to ownCloud's PHP code. The locking will only kick in at the time the temporary file starts to be copied to the actual storage.

I wonder if there is really anything we can do about this. Maybe switching from POST to PUT in the web UI would make it stream the data directly into a part file instead of going the temp file route ?

There's also the general question whether it's a good idea to lock a folder during upload or whether we should only do so at the very end of the transfer, whenever the part file is going to be renamed to the final file.

@icewind1991 @DeepDiver1975

**Comment by DeepDiver1975** [comment]
What might make sense from a testing pov: ability to enabled WebDAV locking verbs?

Furthermore I guess there isn't really much we can do at the moment. because of:



> I think the reason for this is because while the huge file is being uploaded, PHP hasn't passed it yet to ownCloud's PHP code. The locking will only kick in at the time the temporary file starts to be copied to the actual storage.

Moving the upload via webui to webdav will just solve another issue as it seems .....

**Comment by DeepDiver1975** [comment]
> Moving the upload via webui to webdav will just solve another issue as it seems .....

Therefore moving this to 8.2 - in addition no sev1

**Comment by PVince81** [comment]
Related ticket: use PUT instead of POST on upload: https://github.com/owncloud/core/issues/4380

**Comment by PVince81** [comment]
This should work when using webdav upload instead of web UI upload.
Since web UI upload is another issue, closing this one here.
