### ISSUE TITLE
Files scroll bar not prominent and immediately adjacent to trash can

### ISSUE THREAD

**Issue by blutz221** [owncloud/core#16834]
The minimal scroll bar on the browser interface for viewing file folders is immediately adjacent to the 'delete' trash can icon resulting in many unintentional file deletions (several each day among 6 users).  A more prominent scroll bar and/or relocation of the trash can icon and/or 'confirm delete' pop-up would be extremely beneficial and would save me from trolling the deleted files every day and calling  the other users to confirm they intended to delete particular files.

I am using a Windows 7 SP1 laptop, Chrome browser v43.0.2357.81 m, and ownCloud is running on an aws bitnami image with ownCloud 8.0.3.

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by jancborchardt** [comment]
This will be fixed by moving the file actions to a dropdown: #12081 – let’s continue there.

As an intermediate fix, the delete action was moved a bit away from the scrollbar. Unintentional file deletions which still occur will be dealt with the addition of undo: https://github.com/owncloud/core/pull/15002

**Comment by blutz221** [comment]
Much appreciated.  Great application - really nice work.

Bob Lutz
Lutz Engineering, Inc.
(302) 898-2077 mobile
(302) 479-9017 x102 office
