### ISSUE TITLE
[7.0.5] LDAP user can not be undeleted.

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#16835]
### Expected behavior:
Erase LDAP user by mistake and give a command to undelete.

### Actual behavior:
Erase LDAP user by mistake and can't undelete.

@MorrisJobke

00002761

**Comment by MorrisJobke** [comment]
cc @MTRichards

**Comment by MTRichards** [comment]
Well, can we get some more description? When you delete a local user, you can undelete, right? And how did they delete the user - in the web UI?

When a user is accidentally deleted, they can log in again and sync all over, but that is a waste for an accidental delete. 

Urgency?

**Comment by MorrisJobke** [comment]
> Well, can we get some more description? When you delete a local user, you can undelete, right? And how did they delete the user - in the web UI?

In the WebUI there is the undo button available.

This is about the command line tool:

```
./occ user:delete <username>
```

**Comment by MTRichards** [comment]
And for complete documentation, there is no such capability at the command line for ownCloud internal users either, so this would have to be across all users - some sort of an undelete for all users in ownCloud when using the command line. And, the behavior needs to be normalized across the API too.

I don't think we can accept this request. Command lines the world over do not have undo capabilities. That is by design, and a well understood meme. Linux in particular has no undo capability, and such a capability really plays havoc with API calls. Adding such a capability goes against the standard accepted practice, and will have unintended consequences.

**Comment by DeepDiver1975** [comment]
> I don't think we can accept this request.

:+1:

**Comment by MorrisJobke** [comment]
@cdamken Maybe you're looking for deactivating users.

**Comment by cdamken** [comment]
Here's what I'm hoping to do to completely purge a users account:

1. Remove the user from the OwnCloud LDAP Group (Which is the OwnCloud user base). At this point, the user account is effectively "deleted", or does not exist in LDAP, as far as OwnCloud can see.
2. user cleanup utility should, after some time, pick up that there is a user account in the OwnCloud DB that does not exist in LDAP, and should be marked as a remnant when performing the ldap:show-remnants command. (This is where I'm having problems, and what the topic of this trouble ticket is. Some accounts show up as remnants, some don't, when taking the same action on the LDAP account.)
3. Once the show-remants command shows the target user, and the ldap cleanup utility is run, the user should be completely deleted from the OwnCloud database.
4. I then hope to add the original LDAP user back to the OwnCloud LDAP group, and he/she should then be able to log in to OwnCloud as if it is the first login.

If the above method of completely purging a users account in OwnCloud is not viable, please provide support for a method that will work.

**Comment by MorrisJobke** [comment]
But this is not an "undelete" but rather a proper delete, because it sounds like not all is purged from the database (your 4. point). As it is the first logi means: nothing from the old account is left in the ownCloud. If this is the case: please create a ticket with "delete command doesn't delete the user properly - some data is left in database/data dir"
