### ISSUE TITLE
Folder drag from Windows Explorer to browser window does not copy empty sub-folders

### ISSUE THREAD

**Issue by blutz221** [owncloud/core#16831]
With Windows 7 OS and Chrome v43.0.2357.81 m. When the Chrome window is 'restored down' (i.e. not occupying the full active area of the monitor) and the browser is open to ownCloud files view, when a folder with many empty subfolders (which we use as project folder templates) is dragged onto the browser windo, only folders with documents in them are copied.  The only way to copy empty folders that we've found is to use the sync tool.  

Instead, I would expect all empty files to be created within ownCloud as well as populated folders.

ownCloud 8.0.3 is running on an aws bitnami image and is accessed via an SSL connection.

**Comment by PVince81** [comment]
Checked with a debugger, it looks like this is not fixable because Chrome doesn't actually send any folder information to ownCloud. It only ever sends file information when there's a file, and with the file it sends the relative path. So if there is no file, there is no folder either.

Maybe with your use case you could add a hidden file ".projecttemplate" inside your subdirs to force Chrome to upload them.

Closing as not fixable.
