### ISSUE TITLE
Allow global CSP modification

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#16927]

**Comment by sualko** [comment]
:+1: for users of [jsxc](https://www.jsxc.org). Currently avatars, which are included via data, are hidden on pages which uses the app framework. Also cross side requests to bosh servers are no longer possible with 8.1.

**Comment by anonimal** [comment]
The new 8.1 CSP was an unpleasant surprise after updating to the latest jsxc.owncloud (no errors reported in logs, but jsxc.owncloud was obviously not working). I hope that a new CSP mod feature will make it into 8.2!

**Comment by z000ao8q** [comment]
any update???

**Comment by buggy82** [comment]
Firefox 42.0 still complains 4 times on each request to the file app about a CSP violation because of an onchange event on a <div> element:

"csp-report":  [...]
"script-sample":"onchange attribute on DIV element",
"source-file":"DOMAIN/index.php/apps/files",
"violated-directive":"script-src DOMAIN 'unsafe-eval'"

Solution: add 'unsafe-inline' to script-src Attribute of CSP header in /lib/private/response.php lines 246ff.

Owncloud 8.2.1
Enabled:
  - activity: 2.1.3
  - announcementcenter: 1.0.0
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - direct_menu: 0.5
  - external: 1.2
  - files: 1.2.0
  - files_external: 0.3.0
  - files_mv: 0.8.1a
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - search_lucene: 0.6.0
  - storagecharts2: 2.6.1
  - tasks: 0.8.1
  - updater: 0.6
Disabled:
  - documents-8.2
  - encryption
  - files_antivirus
  - files_mv-newer
  - files_texteditor
  - ownnote
  - provisioning_api
  - templateeditor
  - user_external
  - user_ldap

Kind Regards

**Comment by LukasReschke** [comment]
I'm wondering about the API design here. From what I see this would require some global singleton probably in `app.php`. This already smells bad :speak_no_evil: 

Thing is, if we want to do it then technically a dynamic way such as via `app.php` is better as some config entry as developers may want to adjust stuff very specific.

But something like this feels soooooo hacky :hankey: 

```php
$policy = new ContentSecurityPolicy();
$policy->addAllowedChildSrcDomain('*');
\OC::$server->setAdjustedContentSecurityPolicy($policy);
```

@BernhardPosselt @DeepDiver1975 @owncloud/appframework Any suggestions? I'd like to avoid introducing too many anti-patterns :see_no_evil: :smile:

**Comment by LukasReschke** [comment]
Mhm… We might also be able to introduce something to `\OCP\AppFramework\App` so that it would then happen in `application.php`…?

**Comment by BernhardPosselt** [comment]
Actually very simple: inject the CSP object rather than instantiating it in your controller method directly

**Comment by BernhardPosselt** [comment]
Another better solution: use the afterController hook in the SecurityMiddleware. No app modifications and CSP values are always overwritten

**Comment by LukasReschke** [comment]
> Another better solution: use the afterController hook in the SecurityMiddleware. No app modifications and CSP values are always overwritten

Nice idea! :rocket: :+1: 

I'll open a PR later so we can continue discussing there, thanks @BernhardPosselt!

**Comment by bboule** [comment]
@gig13 you made this a Blue Ticket do you have what you need?

**Comment by gig13** [comment]
@bboule 
Milestone expectations are set and will track the progress accordingly every couple weeks via SF Tasks.

**Comment by MorrisJobke** [comment]
@bboule Don't randomly close tickets just because you don't need them anymore. This is not developed yet -> reopening (just remove the blue label is fine.

**Comment by LukasReschke** [comment]
Thanks @MorrisJobke.

**Comment by bboule** [comment]
Not intentional....

**Comment by MorrisJobke** [comment]
> Not intentional....

okay ;)

**Comment by gig13** [comment]
@bboule Does this need to be assigned? Has it been approved?
SF 3966

**Comment by sualko** [comment]
@LukasReschke Can you tell us a little bit more about this issue and the time table? Because this is really needed for [owncloud/jsxc.chat](https://github.com/owncloud/jsxc.chat) (https://github.com/jsxc/jsxc/issues/201). From every oc version to every oc version the csp gets more restrictive. Currently (oc 9) video calls are not working, because streams are blocked. Key generation in background (web worker) is not working, because it is blocked.

What is there against to set the default policy to self (<code>default self;</code>)? I think if you have evil scripts on your server you got other problems.

**Comment by BernhardPosselt** [comment]
> What is there against to set the default policy to self (default self;)? 
By default it should be maximum restrictive, it's up to the app dev to relax it if needed. Basic security concept.

> I think if you have evil scripts on your server you got other problems.
CSP is not about evil scripts on your server ;) it's about XSS mostly

Furthermore it's the app's job to set a looser policy and should not affect a user at all https://github.com/owncloud/news/blob/master/controller/pagecontroller.php#L78

Your issue seems to be that your app seems to hook itself into other apps which might cause unpredicted behavior anyways. Solving this by relaxing every app's CSP seems like a non solution.

I think the solution to your problem is to rethink this approach and create a separate chat app window that you can window tile somewhere on the screen. Basically do the same like every other messenger does ;)

PS: the proposed solution will just change the defaults so apps that actively change the CSP will overwrite it. Basically this won't fix your issue.

**Comment by sualko** [comment]
> By default it should be maximum restrictive

I agree, but sometimes you have to make a compromise (as you already did with e.g. <code>img-src: self</code>). In my opinion also the securest policy should be default and not the most restrictive one.

> I think the solution to your problem is to rethink this approach and create a separate chat app window that you can window tile somewhere on the screen. Basically do the same like every other messenger does ;)

In my opinion two windows or even more are not very user friendly. @jancborchardt What do you think?

> the proposed solution will just change the defaults so apps that actively change the CSP will overwrite it

I thought this would be a method to set default values for every policy, as I would change the properties in [contentsecuritypolicy.php#L50](https://github.com/owncloud/core/blob/master/lib/public/appframework/http/contentsecuritypolicy.php#L50)

Nevertheless we need a solution for this issue, because @Ledfan wrote, in consultation with @karlitschek and @jancborchardt, a backend which allows now every administrator to use this app even if he has no xmpp server.

**Comment by LukasReschke** [comment]
>I agree, but sometimes you have to make a compromise (as you already did with e.g. img-src: self). In my opinion also the securest policy should be default and not the most restrictive one.

Considering that `self` is usually pretty trusted for images and not really usable for information exfiltration I'd not compare it like that.

But yeah, my approach _should_ work for you as well. Let me prepare a PR later.

> In my opinion two windows or even more are not very user friendly. @jancborchardt What do you think?

Technically it should be possible to iframe your app and give the iframe higher permissions. That way you would have the complete control.

**Comment by jancborchardt** [comment]
>> I think the solution to your problem is to rethink this approach and create a separate chat app window that you can window tile somewhere on the screen. Basically do the same like every other messenger does ;)
>
> In my opinion two windows or even more are not very user friendly. @jancborchardt What do you think?

Exactly, big fat nope to that. @BernhardPosselt what do you exactly mean by »every other messenger«? Facebook for example certainly doesn’t do that. ;)

**Comment by LukasReschke** [comment]
There we go: https://github.com/owncloud/core/pull/21989
