### ISSUE TITLE
Proposal: Different data folders user or group related

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/core#17005]
My idea is to have different data folder locations (mount points) which can be defined directly in the user profile or set via group settings. 

A little bit like a distributed file system.

The background is that a company with affiliates in different countries can store their data locally but have all the same webserver entry point for the clients.

From a regulatory point of view this is a feature which no other cloud-sync solution has currently so an extrem benefit ;-)

@MTRichards @karlitschek

**Comment by MTRichards** [comment]
Can you say more about how this works?
For example, how would external storage in different physical locations work?
This might be similar to the "Corporate Share" concept we had where a folder is created and "owned" by the server, rather than by any one user. That way the files and folders are essentially permanent in ownCloud, as people come and go, and has a quota all its own.
Perhaps these two are closely related. Not sure about that yet.

**Comment by pierrejochem** [comment]
The Affiliates are connected via VPN (IPSec) and the storages could be local mounted (smb or other storage types which are possible) on the cloud (web) server.

Maybe it is similar to the "Corporated Share" but is there a way to control the quota for this? Can you search for all users in 10 different domains without adding all users via the special share link (url).

I hope that is no brain fuck :smile: and I need to study the "Corporate Share" more in detail I think.

**Comment by PVince81** [comment]
related https://github.com/owncloud/core/issues/18029
