### ISSUE TITLE
Missing translation of App Categories

### ISSUE THREAD

**Issue by vidaren** [owncloud/core#17036]
Categories fetched by ocsClient->GetCategories() are not translatable. Only [hard-coded "Enabled" and "Not enabled"](https://github.com/owncloud/core/blob/829f6474ff4cd4e39647bcb5b68b5e5c0fb1b483/settings/controller/appsettingscontroller.php#L124) at the top are translatable in Transifex. This is the Norwegian translation serving as an example:

![owncloud-apps-categories](https://cloud.githubusercontent.com/assets/4960432/8242472/c86e7c4a-160f-11e5-9abb-b2b0b387936c.png)

**Comment by LukasReschke** [comment]
@karlitschek Do these category name not change anymore? – If so we can add some L10N magic but that will obviously break as soon as a category gets renamed or added :)

**Comment by karlitschek** [comment]
Well we could hack something ad add hard coded translation for them. But honestly I don=t see why. The app names and descriptions will always be in english. We can=t change this because it is user generated.
I think someone who browses for new apps and tries to find the right one has to understand english in ownCloud. Same if you want to install a wordpress plugin or theme or drupal extension.

**Comment by RealRancor** [comment]
@karlitschek 
I think the request is not about App Names where it doesn't make sense but about the App Categories where it could make sense to translate them.
