### ISSUE TITLE
OCS Share API incorrect output when getting files shared with user if a file is shared witht that user and group of that user

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#17102]
1. User A shares a files with user B
2. User A shares a files with a group and user B is in that group.
3. User B retrieves via OCS the list of shares with the flag shared_with_me

The output is wrong. It should just list 2 shares. It does list the 2 shares but in a very weird way. (see output).

````
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <element>
   <id>112</id>
   <item_type>file</item_type>
   <item_source>3</item_source>
   <item_target>/3</item_target>
   <parent/>
   <share_type>0</share_type>
   <share_with>test</share_with>
   <uid_owner>roeland</uid_owner>
   <file_source>3</file_source>
   <path>files/z.txt</path>
   <file_target>/z.txt</file_target>
   <permissions>19</permissions>
   <stime>1435058818</stime>
   <expiration/>
   <token/>
   <storage>1</storage>
   <mail_send>0</mail_send>
   <storage_id>home::roeland</storage_id>
   <share_with_displayname>test</share_with_displayname>
   <displayname_owner>roeland</displayname_owner>
   <grouped>
    <element>
     <id>112</id>
     <item_type>file</item_type>
     <item_source>3</item_source>
     <item_target>/3</item_target>
     <parent/>
     <share_type>0</share_type>
     <share_with>test</share_with>
     <uid_owner>roeland</uid_owner>
     <file_source>3</file_source>
     <path>files/z.txt</path>
     <file_target>/z.txt</file_target>
     <permissions>19</permissions>
     <stime>1435058818</stime>
     <expiration/>
     <token/>
     <storage>1</storage>
     <mail_send>0</mail_send>
     <storage_id>home::roeland</storage_id>
     <share_with_displayname>test</share_with_displayname>
     <displayname_owner>roeland</displayname_owner>
    </element>
    <element>
     <id>113</id>
     <item_type>file</item_type>
     <item_source>3</item_source>
     <item_target>/3</item_target>
     <parent/>
     <share_type>1</share_type>
     <share_with>test</share_with>
     <uid_owner>roeland</uid_owner>
     <file_source>3</file_source>
     <path>files/z.txt</path>
     <file_target>/z.txt</file_target>
     <permissions>19</permissions>
     <stime>1435058831</stime>
     <expiration/>
     <token/>
     <storage>1</storage>
     <mail_send>0</mail_send>
     <storage_id>home::roeland</storage_id>
     <share_with_displayname>test</share_with_displayname>
     <displayname_owner>roeland</displayname_owner>
    </element>
   </grouped>
   <mimetype>text/plain</mimetype>
   <isPreviewAvailable>1</isPreviewAvailable>
  </element>
 </data>
</ocs>
````

**Comment by rullzer** [comment]
Ah so this is actually explicitly done in the code. In the groupItems function.

@schiesbn why do we do this?

**Comment by schiesbn** [comment]
If the same file is shared with you twice, once as a group share and once as a user share you should only see one share in your files list because it is the same file. That's why we group them.

The only shares every app cares about are the top level shares (directly under ````<data><element>````). Under ````<grouped>```` we just list the shares which are grouped under this one share. This is needed for various internal operations. E.g. if the recipient renames the mount point we need to take care to rename the mount point of all shares.

Not a bug -> closed

**Comment by rullzer** [comment]
Ok I see.
Still would be good if this was documented.

**Comment by schiesbn** [comment]
> Still would be good if this was documented.

I agree. This grouping was mainly introduced for the web view but of course the ocs calls will get the same updated result. That's not a problem from a API point of view, because nothing changed here, the shares only have a new poperty ("grouped" which the list of grouped shares).

Would be great to have a update for the documentation. Do you want to prepare a pull request in the documentation repository?
