### ISSUE TITLE
External storage: put storage chooser first

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#17198]
Currently, the »Folder name« input field is first and the storage chooser dropdown is second.

For an easier flow, the storage chooser dropdown should be to the left because that is usually what is chosen first. It also prefills the folder name input field with a sensible default name.

(Carried over from https://github.com/owncloud/apps/issues/1389, cc @nickvergessen @Xenopathic @bantu)

**Comment by Xenopathic** [comment]
The only problem is, we want to keep interface consistency between existing external storages (which *should* be name first, since that is effectively the ID of the storage) and the line to create new storages. If we make the dropdown appear before the folder name on the new storage configuration line, then it will look out of place with existing storages, and if we move everything so the storage type is first before the storage name, then that is weird IMHO :smile:

**Comment by jancborchardt** [comment]
Ok – nevermind in that case. I’ll just close it and we never speak of it again. :D
