### ISSUE TITLE
When admin shares Textfile sharee can edit name and delete without rights!

### ISSUE THREAD

**Issue by farson2003** [owncloud/core#17216]
To reproduce: ownCloud 8.0.4 (stable) 
-Admin creates a TXT file via Owncloud interface.-
-Admin then shares file to a user without giving him right to delete, edit and so on.

-When user logs on he can still edit the filename and/or delete it on his interface, even though he has no right to do edit

That does not make sense. The sharee should only be able to "unshare" it, but not to edit file characteristics such as filenames, as he has no right to do so.

**Comment by LukasReschke** [comment]
This is the expected behaviour. The file will only get renamed for the recipient of the share and no other person.

**Comment by farson2003** [comment]
@LukasReschke 
Hmmm... that's down to you. 

Why should the recipient be able to change the file name (even if only to himself) if the sharer does not allow editing?!

This is contradictory at first, and that might equally not be obvious to understand to other endusers.

It might also be counterproductive, if suddenly many users have the same file with different filenames and can lead to confusion.

Please reconsider that behaviour!

**Comment by aidanamavi** [comment]
"Such behaviour can also be very counterproductive, if suddenly many sharees have the same file with different filenames. This leads to confusion." I can see this being a problem, especially for novice users. In a collaborative environment, it'd be nice to say, "Go to file XYZ," and not have to worry about the user guessing what he may have renamed the file to.

**Comment by jancborchardt** [comment]
We do exactly the same for folder sharing: Everyone can rename the folder how they like because they might want a different name for it.

I do however get the confusion in the case of single file shares and renaming. Folders are just a container, but filenames directly belong to the file. @owncloud/designers @MTRichards what do you think – should we disallow renaming of single file shares by sharees (even just for themselves)?

**Comment by nickvergessen** [comment]
Well since if multiple people share a "share-with-user-test.txt" with you (being test), it is helpful for you to be able to rename them into something like "shared-by-user-admin.txt" (admin being the sharer). It will be tough, to remember whether:

* share-with-user-test.txt
* share-with-user-test (1).txt
* share-with-user-test (2).txt or ...

was from admin, mate, or whatever.

I really don't think we should prevent renaming share-mount-points...

**Comment by LukasReschke** [comment]
> I really don't think we should prevent renaming share-mount-points...

Yes. But we could somehow show the old file name somewhere.

**Comment by MTRichards** [comment]
The simplest (nod to Jan) way to handle is to either allow or not allow renaming of files. Folder renaming makes sense to me it is just a container, but files...if you are sharing a file, you want that filename to be what you shared.
"Hey, Jan, take a look at latestdesignideas.odt" which doesn't work if the filename can be changed to "badideasfromjan.odt".
What file am I talking about?
As a recipient of the share, the idea that 4 different people share the same filename with me and it has different contents is less likely, but still a problem. In that case, can we append the username to the filename?
Such as "share-with-user-test_from_Jan.txt? 
That is simple, easy to understand, and solve the filename collision problem. BUT, we don't allow renaming.
@nickvergessen @jancborchardt thoughts on that concept?

**Comment by LukasReschke** [comment]
> As a recipient of the share, the idea that 4 different people share the same filename with me and it has different contents is less likely, but still a problem. In that case, can we append the username to the filename?
> Such as "share-with-user-test_from_Jan.txt? 

Will be huge fun with LDAP identifiers and other stuff. Also a step backwards from my opinion.

**Comment by nickvergessen** [comment]
@MTRichards not sufficent, I can share development/ideas.txt and company/ideas.txt with you. How are you going to identify which ideas.txt is which? I really think that allowing to rename mount points should be okay. Since you can also move them into folders this is all mostly irrelevant anyway...

"Hey, Jan, take a look at latestdesignideas.odt" doesn't work for folders as well, and people mostly remember when they changed the name of a share they got.

The problem you describe is part of https://github.com/owncloud/core/issues/11732 ( @PVince81 ).

**Comment by aidanamavi** [comment]
> But we could somehow show the old file name somewhere.

This would be great, if the file was also able to be searched by it's original name. Best of both worlds.

**Comment by jancborchardt** [comment]
Phew, I’d say we simply need to make the decision to either/or:
* keep it like it is now, allow renaming on a per-user basis
* prevent renaming unless the person has edit rights. Then it’s confusing with folders though – since folders should most probably rename-able in either case. And that introduces a whole new level of confusion then.

Anything beyond that is really overkill. And regarding the options and drawbacks I’d say the best solution is to keep it like it is now. Has any bigger deployment ever complained about that? cc @MTRichards @Gomez

**Comment by MTRichards** [comment]
yep. Let's leave it as it is, I have not had complaints at this time. What we have seems to work MOST of the time.

**Comment by MTRichards** [comment]
Also tested it against dropbox, this is the same behavior.
