### ISSUE TITLE
Group disappears from dropdown when repeatedly setting and unsetting

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17336]
### Steps to reproduce
1. Go to the admin page
2. Create a user "user1" (don't set a group yet)
3. Add user "user1" in a new group "group1"
4. Refresh the page
5. Remove "user1" from group "group1" and click outside (do not refresh the page!)
6. Open the dropdown again and add "user1" to group "group1"
7. Repeat steps 5 and 6 very quickly

### Expected result
"group1" checkbox is always in the dropdown

### Actual result
If you're fast enough, the "group1" checkbox will completely disappear from the dropdown.
You have to refresh the page to make it appear again.

### Versions
ownCloud 8.1 RC 2

I suspect this might be due to reopening the dropdown quickly before the previous one didn't finish closing. Or maybe reopening the checkbox before the server request for setting the group finished.

Hopefully we can at some point replace that dropdown with select2 and improve the general workflow.

@blizzz @LukasReschke @jvillafanez

**Comment by jvillafanez** [comment]
I confirm the issue. I'd say that clicking the checkbox fast enough makes the issue happen.

Disabling the checkbox while the ajax request is being performed should be enough to prevent the issue.

My guess: there is "something" that deletes the group when there are no members. By clicking fast, you force a race condition. Instead of delete - add - delete - add, it goes to delete - delete - add - add, so delete is done twice in a row, the group doesn't have enough members and it's deleted

**Comment by PVince81** [comment]
Grrr race conditions...

**Comment by PVince81** [comment]
I can't reproduce this on 8.2.0. I even tried adding `sleep(5)` in togglegroups.php, but in all cases, even when switching/toggling fast, the group entry is still in the dropdown.
