### ISSUE TITLE
Profile image in top right is blurry

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#17390]
You can see this when zooming or on a smartphone / tablet / any screen with high resolution:
![capture du 2015-07-04 00-27-42](https://cloud.githubusercontent.com/assets/925062/8505351/938314c0-21e3-11e5-89fb-552487f6afdb.png)

@georgehrke @schiesbn

**Comment by rullzer** [comment]
well we just request the 32x32 avatar... So if you zoom in to much it will get blurry yeah.. Probably it then also appears blurry in the sharing dialog since we request the same avatar there...

**Comment by jancborchardt** [comment]
Yeah – important thing is that it’s not only about zooming but also about High-DPI displays, as in almost all smartphones and tablets nowadays. We need to request double the size for any bitmap we show.

**Comment by DeepDiver1975** [comment]
@georgehrke @oparoz some image kung-fu mastery is required - THX

**Comment by oparoz** [comment]
It's probably missing something like this:

https://github.com/owncloud/core/blob/master/apps/files/js/filelist.js#L1212-L1215
```
urlSpec.x *= window.devicePixelRatio;
urlSpec.y *= window.devicePixelRatio;
urlSpec.x = Math.floor(urlSpec.x);
urlSpec.y = Math.floor(urlSpec.y);
```

**Comment by rullzer** [comment]
@oparoz that would be https://github.com/owncloud/core/blob/master/core/js/jquery.avatar.js

**Comment by oparoz** [comment]
@rullzer Thanks :)
I can see that you're already requesting the image with the correct devicePixelRatio
https://github.com/owncloud/core/blob/master/core/js/jquery.avatar.js#L80

1. I don't understand which size is the default 
64x64 https://github.com/owncloud/core/blob/master/core/js/jquery.avatar.js#L57
32x32 https://github.com/owncloud/core/blob/master/settings/js/personal.js#L99
128x128 https://github.com/owncloud/core/blob/master/settings/js/personal.js#L103

2. The minimum size should be something like 5 x desired_size, so that people on various screens always get the best picture. So if the avatar is sometimes shown at 128x128, then the minimum size should be 640x640. It shouldn't be a hard limit, but there should be a warning somewhere that a small avatar can be uploaded, but won't look good on all devices.

@jancborchardt Thoughts?

**Comment by jancborchardt** [comment]
Well the px size we display there in the top right is 32px. So the image which is shown there should be at least 64*64 pixels.

**Comment by rullzer** [comment]
PR coming soon :)

**Comment by oparoz** [comment]
@jancborchardt The "personal" section shows it at 128x128 and we already have devices with a ratio of 3, so in order to be a little bit future proof, we should really ask users to upload pics of 500x500.

devicePixelRatio will then work its magic and always display a crisp image everywhere.

**Comment by rullzer** [comment]
PR in #17998
