### ISSUE TITLE
8.0.5 --> 8.1.0 Encryption migration problem.

### ISSUE THREAD

**Issue by AlphaBootis** [owncloud/core#17482]
I manage two owncloud installations that both use encryption as the files are on a remote host that I do not manage.
Updating the software itself was quite iffy on one installation that had a lot of apps that subsequently failed to re-activate and then it presented me again with the post-installation upgrade button. After that repeated itself a couple of times I could re-enabled all the plugins I use. 

Subsequently it complained about the encryption keys beeing outdated and I had to run some command. This was new to me but after some quick googling I realized this was sudo -u www-data php occ encryption:migrate.

When I ran this command first time around it spawned some php error that I failed to copy. Then I read in a different GIT threat I should disable the deleted files plugin. Now running the sudo -u www-data php occ encryption:migrate command spawns a bunch of SQL related errors:

[Doctrine\DBAL\Exception\UniqueConstraintViolationException]
  An exception occurred while executing 'UPDATE `oc_appconfig` SET `appid` =
  ? WHERE `appid` = ?' with params ["encryption", "files_encryption"]:
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'encr
  yption-publicShareKeyId' for key 'PRIMARY'

[Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'encr
  yption-publicShareKeyId' for key 'PRIMARY'

 [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'encr
  yption-publicShareKeyId' for key 'PRIMARY'

I tried the same procedure on the second owncloud installation but disabling the deleted files plugin before I did anything and it immediately spawns the same errors.
Now I've got two broken Owncloud installations.

First of all i'd like to be assured wether or not the sync app will sync these now broken files back to my pc destroying my data, and secondly obviously some tips on how to fix this problem would be greatly appreciated.

**Comment by karlitschek** [comment]
@schiesbn os this a duplicate?

**Comment by conloos** [comment]
I have exactly the same error on my instance.

Thanks Frank

**Comment by schiesbn** [comment]
@AlphaBootis the issue was already discussed here https://github.com/owncloud/core/issues/16928. You describe the exact same problem, afaik you where also involved in the other issue so no need to open a new one.

Here you can find a summary of the latests state:
https://github.com/owncloud/core/issues/16928#issuecomment-119537807

To make sure that your sync client doesn't sync any files I would recommend to stay in singleuser mode as suggested here: https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/encryption_configuration.html#upgrading-from-owncloud-8-0
