### ISSUE TITLE
Unable to update software on Qnap. TS420

### ISSUE THREAD

**Issue by nitrofx** [owncloud/core#17695]
when loading the main page for owncloud an update request appears. when the upgrade version is selected there is an error coming up:

"Updates between multiple major versions are unsupported." the system is no maintenance mode.

**Comment by RealRancor** [comment]
Hi,

this is an issue because Qnap is providing packages directly from 7.0.x to 8.1.x which is not supported:

https://github.com/owncloud/core/issues/17650#issuecomment-121499118

There you can find a forum link providing some steps to fix that.

Overall please contact the Qnap support and make them aware of the problem with their packages.

**Comment by RealRancor** [comment]
See also http://forum.qnap.com/viewtopic.php?f=32&t=112047
