### ISSUE TITLE
Invalid private key for Encryption App

### ISSUE THREAD

**Issue by R3s1stanc3** [owncloud/core#17729]
Hi
I had a few issues with the owncloud 8.1
Using this thread (https://github.com/owncloud/core/issues/17574) i got it running but now I've got the following error when logging in to any user account:
"Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files"
When I try to update the key (the passwords never changed), it just says
"Saving..." and nothing happenes

**Comment by RealRancor** [comment]
Anything in your logfiles like asked here:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version
(Should be filled out in general)

**Comment by R3s1stanc3** [comment]
No entry in the log file
The Server is running Debian stretch
uname -a
Linux ns331546.ip-37-187-122.eu 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
mysql --version
mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3
php --version
PHP 5.6.9-1 (cli) (built: May 22 2015 10:48:57) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
nginx -v
nginx version: nginx/1.9.2

Apps:
Enabled:
 - activity: 2.0.1
 - admin_dependencies_chk: 0.02
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - documents: 0.8.2
 - encryption: 1.0.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - news: 4.0.2
 - tasks: 0.6.0
 - templateeditor: 0.1
Disabled:
 - bookmarks
 - external
 - files_external
 - news.old
 - provisioning_api
 - search_lucene
 - user_external
 - user_ldap
 - user_webdavauth

sudo -u www-data php occ encryption:status
 - enabled: true
 - defaultModule: OC_DEFAULT_MODULE

I upgraded from an existing owncloud installation and tried to update my encryption password in 2 different browsers to be sure, it is not a browser problem

Here is my oc config.php:
<?php
$CONFIG = array (
  'instanceid' => '*',
  'passwordsalt' => '*',
  'trusted_domains' => 
  array (
    0 => '*',
  ),
  'datadirectory' => '/home/owncloud',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '*',
  'dbtype' => 'mysql',
  'dbname' => '*',
  'dbuser' => '*',
  'dbpassword' => '*',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'version' => '8.1.0.8',
  'installed' => true,
  'check_for_working_webdav' => false,
  'logtimezone' => 'Europe/Berlin',
  'log_type' => 'syslog',
  'log_authfailip' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => '*',
  'forcessl' => true,
  'asset-pipeline.enabled' => true,
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => '*',
  'loglevel' => 0,
);

**Comment by RealRancor** [comment]
Anything in the browers console when clicking "save"? Have seen a similar behavior with the e-mail address where the webserver was blocking a needed method.

**Comment by R3s1stanc3** [comment]
"14:22:06.637 SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data1 d76aa4fc61294494c0c326a01599ad56.js:2542:578"

**Comment by LukasReschke** [comment]
@schiesbn

**Comment by R3s1stanc3** [comment]
No ideas? Thats pretty sad... Do I have to create a new user and reupload all my files?

**Comment by schiesbn** [comment]
One of the upgrade issues could also break the private key. Compare the private key stored in ````data/<user>/files_encryption/OC_DEFAULT_MODULE/<user>.privateKey```` with the key in ````data/<user>/encryption_migration_backup_<oldest_timestamp_from_the_first_time_you_run_migration>/<user>-privateKey````. Are they exactly the same? You could try to copy the key over from the backup to the new location.

**Comment by R3s1stanc3** [comment]
data/<user>/files_encryption/OC_DEFAULT_MODULE/<user>.privateKey does not exist, but
data/<user>/files_encryption/<user>.privateKey does.
data/<user>/files_encryption/<user>.privateKey and data/<user>/encryption_migration_backup_<oldest_timestamp_from_the_first_time_you_run_migration>/<user>-privateKey are the same file (same md5 hash)

**Comment by schiesbn** [comment]
This looks like the migration wasn't completed successfully for this user. Did you saw any errors during migration? You could try to restore the backup from the user and then run ````./occ encryption:migrate <user>````. Make sure to enable maintenance mode before you perform this steps to avoid that this user uploads files at the same time.

Because the other migration was already executed you probably need to move the public key manually after you run the occ command succesfully. The users public key can be found in ````data/encryption_migration_backup_<oldest_timestamp_from_the_first_time_you_run_migration>/public-keys```` (again, chose the oldest backup), just copy it to ````data/<user>/files_encryption/OC_DEFAULT_MODULE/<user>.publicKey````

**Comment by R3s1stanc3** [comment]
I didn't get an error while migrating. Also this error appears for the admin and for my "normal" user.
But I will try to run the migration another time

**Comment by R3s1stanc3** [comment]
Doing another migration and copying the public key didn't help eighter.
I really don't know what else to do and I don't want to reinstall oc because I would lose all my files. That's really fucked up how bad the update routine works...

**Comment by schiesbn** [comment]
@R3s1stanc3 where is is the private key located after the new run? Again in ````data/<user>/files_encryption/<user>.privateKey```` ? The only way this could happen is if ````\OCA\Encryption\Crypto\Encryption::ID```` is empty, the ID should be defined here: https://github.com/owncloud/core/blob/master/apps/encryption/lib/crypto/encryption.php#L41

If the private key is still on the wrong place you could edit the apps/encryption/lib/migration.php and add following:

add here: https://github.com/owncloud/core/blob/master/apps/encryption/lib/migration.php#L55
````
error_log("module ID: " . $this->moduleId);
````

add here: https://github.com/owncloud/core/blob/master/apps/encryption/lib/migration.php#L242
````
error_log("old private key location: " . $oldPrivateKey);
````

add here:  https://github.com/owncloud/core/blob/master/apps/encryption/lib/migration.php#L244
````
error_log("move private key from " . $oldPrivateKey . " to " . $newPrivateKey);
````

Then restore again the oldest backup and run the migration again. What do you see in your apache error log?

**Comment by R3s1stanc3** [comment]
My output:
module ID: OC_DEFAULT_MODULE
old private key location: user/files_encryption/user.privateKey
move private key from user/files_encryption/user.privateKey to user/files_encryption/OC_DEFAULT_MODULE/user.privateKey

but user/files_encryption/OC_DEFAULT_MODULE doesn't exist. The files are in user/files_encryption

**Comment by linoskoczek** [comment]
Same problem here.

<code>Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files.</code>

In all the backups I have such files & dirs:
* Directories:
  * keyfiles
  * share-keys
* Files:
  * user.private.key

I copied *user.private.key* to *owncloud/data/user/files_encryption/OC_DEFAULT_MODULE/*, but still no effect. 

In *encryption.php*:
<code>const ID = 'OC_DEFAULT_MODULE';</code>

I cannot do what you asked here https://github.com/owncloud/core/issues/17729#issuecomment-125516001 because my migration.php is different according to your guide from https://github.com/owncloud/core/issues/17574. When I change the file content to the one which is in your link, I get 
<code>PHP Fatal error:  Call to a member function info() on a non-object in /var/www/owncloud/apps/encryption/lib/migration.php on line 240</code>

**Comment by oparoz** [comment]
@schiesbn - I just want to add that this also happens without an upgrade.
I was testing an app with and without encryption and it's possible to completely break encryption if one is not careful.

1) Set-up encryption
```
# occ app:enable encryption
encryption enabled
```
2) Disable it via occ
```
# occ app:disable encryption
encryption disabled
```
3) Check status
```
occ encryption:status
  - enabled: true
  - defaultModule: OC_DEFAULT_MODULE
```
This may be intended because some files are still encrypted? But I think this behaviour breaks things, see next step
4) Check which module is installed
```
occ encryption:list-modules

```
Yes, it's empty and files are not accessible because of that. There is an exception thrown about the module not being loaded, but it doesn't make sense because the encryption app is disabled.

At this stage, turning encryption back on doesn't seem to work.
> Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files.

And resetting the password doesn't work either
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

That's because I'm not getting a JSON object back, but an HTML page which says

> Private Key missing for user:XYZ

**Comment by oparoz** [comment]
@schiesbn - My previous notes were not taking into consideration the wiped data folder. Here are updated ones.

### Disabling the encryption app

1) Set-up encryption
```
# occ app:enable encryption
encryption enabled
```
2) Disable it via occ
```
# occ app:disable encryption
encryption disabled
```
3) Check status
```
occ encryption:status
  - enabled: true
  - defaultModule: OC_DEFAULT_MODULE
```
Encryption is still **enabled**. This may be intended because some files are still encrypted?
4) Check which module is installed
```
occ encryption:list-modules

```
The list is empty

### Re-enabling encryption after having wiped data

It doesn't create new keys. We're forced to re-create the user. Not much harm in doing this at this stage since the data folder has been wiped, but would be nice if this could be avoided.

### Wrong data type returned when keys are missing

When the user has lost his keys, he's shown this message

> Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files.

But resetting the password doesn't work 
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

That's because I'm not getting a JSON object back, but an HTML page which says

> Private Key missing for user:XYZ

**Comment by PVince81** [comment]
@R3s1stanc3 @oparoz is this still an issue in 9.0.2 or later ?

**Comment by PVince81** [comment]
Feel free to reopen if the problem pesists with 9.0.5 or 9.1.1
