### ISSUE TITLE
No more webdav file locking => read only with Mac OS X

### ISSUE THREAD

**Issue by turb** [owncloud/core#17732]
Reading #10474 (and some others), I understand that webdav file locking has been removed from Owncloud 8.1, because it was known to be broken in a shared environnement.

Problem: Mac OS X Finder, based on Sabre, mounts webdav with RW mode [**only** if file locking is supported] (http://sabre.io/dav/clients/finder/). It means that if you have a Mac, you can no longer write to owncloud through webdav, starting with 8.1.

Should it be possible to have webdav file locking back for non-shared directories, or back as optional?

**Comment by lzs** [comment]
I use OS X Finder to access ownCloud WebDAV too, and would love to have this issue resolved too.

**Comment by derkostka** [comment]
I second this. Does the experimental locking based in redis help here?

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by oliverkoester** [comment]
@derkostka unfortunately this doesn't seem to help. I don't know any workaround. If someone know. let me know because currently all our mac users don't have full access to our OC installations.

**Comment by DeepDiver1975** [comment]
Grrr - what a mess ..... let me see what we can do.

**Comment by q1x** [comment]
I'm facing the same issue, I can't upload files from my Mac Finder anymore. I diverted to Cyberduck as a workaround, but that seems to keep crashing with Owncloud 8.1.

**Comment by PVince81** [comment]
@DeepDiver1975 I checked the provided backends by Sabre. One stores the locks in a file and another one uses PDO: https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Locks/Backend/PDO.php

But the main problem is about shared files. Maybe could implement a variation of the PDO backend that uses file id instead of paths ?

**Comment by derkostka** [comment]
I volunteer to test if you got something. I would love to use owncloud via webdav on the mac as integration in the finder seems to be well so far... (didn´t check performance, but i hope apple did well here)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I checked the provided backends by Sabre. One stores the locks in a file and another one uses PDO: https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Locks/Backend/PDO.php
> 
> But the main problem is about shared files. Maybe could implement a variation of the PDO backend that uses file id instead of paths ?

I already had an experimental implementation - but it would have required some more time to test and implement and therefore we decided to completely drop dav locking - not knowning about this impact \o/

May approach would be to bring webdav locking together with our own locking - because from my pov the the lock status should be consistent

**Comment by derkostka** [comment]
As Feature freeze ia about to arrive, is a solution planned ?

**Comment by jerrac** [comment]
I just ran into this issue for one of my users as well. Will the fix be in the next 8.1.x release? Or the first 8.2 release?

**Comment by dubcanada** [comment]
Any ideas on a solution? Ran into this issue today.

**Comment by icewind1991** [comment]
I've looked into this some more, we cant easily use our transactional locking since any request made after a client getting a lock would fail with the target of the request being locked.

We would need to add logic to our locking to associate it with the dav lock token so we can allow requests coming from the client who holds the lock.

Adding a new locking system based on fileids also wont be simple since dav locks need to support depth.

**Comment by DeepDiver1975** [comment]
Another opportunity would be to a fake dav locking module - if I remember correctly @evert was suggesting something like this some time ago

**Comment by DeepDiver1975** [comment]
> Another opportunity would be to a fake dav locking module - if I remember correctly @evert was suggesting something like this some time ago

I did quickly play with that ... this will not work out because we need to keep a state - even for the fake implementation - otherwise the locking behavior will not be compliant to the specs.



> We would need to add logic to our locking to associate it with the dav lock token so we can allow requests coming from the client who holds the lock.

@icewind1991 can we have an estimation on that? time and risk please. THX

**Comment by icewind1991** [comment]
Rough guess would be about a week of work to extend our locking with all the info needed for dav locks and adjust dav to use it.

Risk shouldn't be to large.

**Comment by DeepDiver1975** [comment]
THX @icewind1991 

@cmonteroluque something we should take into consideration for 9.0 with backport option to 8.2.1

**Comment by icewind1991** [comment]
Not sure about backportability since it requires db changes

**Comment by DeepDiver1975** [comment]
> Not sure about backportability since it requires db changes

ouch :bomb:

**Comment by icewind1991** [comment]
> I did quickly play with that ... this will not work out because we need to keep a state - even for the fake implementation - otherwise the locking behavior will not be compliant to the specs.

We might be able to make it work by always accepting a lock token as valid, not spec compliant but should make davfs/mac happy

**Comment by DeepDiver1975** [comment]
Well - as soon as we add a locking module the server will expose this capability and clients will rely on it's behavior. Finally litmus will trigger it's locking tests and it will break apart badly.

**Comment by cmonteroluque** [comment]
@icewind1991 @DeepDiver1975 8.2.1 perhaps? RC1 is 3 November, we could fit in a week's worth of development in there.

**Comment by DeepDiver1975** [comment]
> 8.2.1 perhaps?

Not given the fact that there is a database change required - no db changes on minor releases :dancers:

**Comment by karlitschek** [comment]
we have to discuss. i'm still question if this fits into the scope of ownCloud

**Comment by DeepDiver1975** [comment]
> we have to discuss. i'm still question if this fits into the scope of ownCloud

well - mac users should be capable to mount ownCloud via webdav - right?

**Comment by karlitschek** [comment]
@DeepDiver1975 not sure actually. We have to decide if this is something that we need to support.

**Comment by karlitschek** [comment]
@MTRichards

**Comment by johansolve** [comment]
This is a showstopper for us. Otherwise we'll have to find other file server solution. 
So a strong vote to get proper support for writable webdav on Mac.

**Comment by jerrac** [comment]
I found this issue because I had users complaining with their webdav mounts stopped working. So it's a feature people use and rely on. It also is something that used to work, so aren't you already supporting it? 

Also, I would imagine users would find it pretty odd that mounting on Windows and Linux works, but not on OSX. 

Anyway, those are my thoughts in support of continuing support for OSX mounts.

**Comment by MTRichards** [comment]
Got it, thanks @karlitschek . We did offer WebDAV mounts as a solution for some customers, but if it requires full locking...I don't want to be pulled into "file is locked in edit by *user1*" just yet, but I want to fix the webdav mount on  Mac. options?

**Comment by DeepDiver1975** [comment]
> options?

writable mounts on mac require webdav locking (to which extent is unclear) - I see no other solution.

**Comment by MTRichards** [comment]
And the more I think about it, if two people edit the same file at the same time, without locking, it can corrupt the files on the server. So not sure if I can have what I want.

**Comment by MTRichards** [comment]
So, this means we have to take on the file locking issue to fix this.

**Comment by icewind1991** [comment]
> It can corrupt the files on the server.

We already have the locking in place to prevent it, just not in a way where the webdav client is aware of it

**Comment by johansolve** [comment]
As an interim solution, how about adding an option to allow write access for Finder Webdav, as it used to work? (pre 8 was it?) In our scenario, conflicts are highly unlikely so we prefer having writable access with a slight risk rather than read only.

**Comment by karlitschek** [comment]
This is a huge topic with a lot of things to consider. Definitely something for 9.0 or later

**Comment by evert** [comment]
> And the more I think about it, if two people edit the same file at the same time, without locking, it can corrupt the files on the server.

This is not really correct, because a server should not allow files to be changed by two different clients at the same time. Any operation should be atomic and idempotent. Owncloud might have already done this correctly though, which negates the need for file locks.

I think locks *are* useful for ensuring consistency of a complete directory though. I've always been hesitant syncing critical stuff such as versioned resources/databases on sync solutions that don't do directory-level locking ;)

But clients such as OS X use locking for this purpose. Perhaps they assume that servers don't always implement multiple clients writing to the same resource well, so they require locking, because it's their way to ensure that files don't corrupt. The locks are very short-lived. They lock before a `PUT` and unlock right after it.

**Comment by icewind1991** [comment]
> Owncloud might have already done this correctly though, which negates the need for file locks.

We do

**Comment by AndiSHFR** [comment]
Is there a way to disable ownclouds internal webdav implementation in favor for the apache webdav module (to support file locking at htis time)? Would this be possible as a short-time solution until oc gets the locking code implemented?

**Comment by icewind1991** [comment]
No, since apache's webdav doesn't know about sharing, trashbin, external storage, etc

**Comment by PVince81** [comment]
and also apache's webdav is unlikely to propagate etags, so the sync client will not be able to detect changes

**Comment by ronnyegner** [comment]
I also want to second that this is most likely a "critical" feature. I mean Owncloud is mainly for storing files, isn´t it (amon other things of course)? And a not working mac webdav is therefore critical.

Maybe it would be a good idea to bring back the old locking mechanism that can be enabled with a appropriate warning?

**Comment by DeepDiver1975** [comment]
> Maybe it would be a good idea to bring back the old locking mechanism that can be enabled with a appropriate warning?

No - the old locking mechanism was a stupid fake. This will not happen - sorry

**Comment by ronnyegner** [comment]
@DeepDiver1975  OK. Any other suggestions for a writeable WebDav on MAC OS?

**Comment by johansolve** [comment]
@ronnyegner Some third party webdav client like WebDrive or ExpanDrive for instance. They also mount webdav as a network volume but not as seamless as native Finder. On the other hand they provide caching and better performance. 
I think I've tested WebDrive also with OX 8.1+ and it worked fine to write files, but I can't verify that now.

**Comment by ryannix123** [comment]
So it sounds like the definitive answer on read/write mounts to ownCloud using WebDAV in OS X is "It is not working at present time in the 8.x branch, but may work again in the future." Is this correct?

**Comment by ryannix123** [comment]
The reason we need WebDAV working for OS X clients is that we have users with video files over 16 GBs, which, unless I'm mistaken, is the limit in Apache/PHP. In the past WebDAV helped us get around this limit in the browser.

**Comment by DeepDiver1975** [comment]
> The reason we need WebDAV working for OS X clients is that we have users with video files over 16 GBs, which, unless I'm mistaken, is the limit in Apache/PHP. In the past WebDAV helped us get around this limit in the browser.

uploading 16GB via WebDAV is no fun either :speak_no_evil: - did you consider using the desktop client?

**Comment by ryannix123** [comment]
I have, and the sync client works just fine. However, it is the cumulative amount of data that makes syncing untenable, even if they just selectively sync through the client.

**Comment by jerrac** [comment]
Could webdav functionality be added to the owncloud client? 

I would imagine that there are a lot of people who might have the cumulative amount of data issue. Selective sync, plus built in webdav client might cover that.

Just a thought. I'm sure it'd be a lot of work for the developers...

**Comment by evert** [comment]
Just use something like Cyberduck. No need to reinvent that again =)

**Comment by jerrac** [comment]
One of my users did use Cyberduck as a work around to this issue. From what he said, Cyberduck isn't smart enough to only upload the changed files. So he had to constantly upload all of his files every time he made a change, or else navigate to the specific file in his file structure that changed. 

I'm not a mac user, so I have no idea how Cyberduck works. But that sounds like Cyberduck is a really bad webdav client. Either due to missing functionality, or bad UI. So, perhaps OwnCloud could do better. 

Anyway, like I said, it was just a thought.

**Comment by lightonflux** [comment]
BTW: The team of Cyberduck are working on a program called Mountain Duck which integrates the shares (ftp, sftp, webdav, …) in  Mac OS X Finder App and Microsoft Windows Explorer. This would temporarily fix the integration issues with Mac OS X' and Windows WebDAV implementations. 

At the moment the program is in closed Beta and is a bit unstable. But you will probably get an invite and can test your setup so when the app releases you can rollout immediately and don't have to wait for OC 9. (*If the launch of the app is not delayed*).

**Comment by mbardelmeijer** [comment]
Any update on this issue?

**Comment by LukasReschke** [comment]
@mbardelmeijer This is targeted for 9.0 or a later release as stated by the milestone.

**Comment by cdamken** [comment]
@MorrisJobke 

00004106

**Comment by MorrisJobke** [comment]
@cdamken I just discussed this with @DeepDiver1975 on IRC: The way to mount ownCloud webdav read-write on OS X would be to use a 3rd party tool.

**Comment by DeepDiver1975** [comment]
> Just use something like Cyberduck. No need to reinvent that again =)

@cdamken ^ this is one suggestion

**Comment by DeepDiver1975** [comment]
> Definitely something for 9.0 or later

@karlitschek @MTRichards @cmonteroluque @PVince81 I honestly don't see this for 9.0 since we lack a solution path at the moment.

**Comment by MTRichards** [comment]
Much as I would like to punt, this is an issue that needs a resolution. It is a feature people value in ownCloud. While not the top priority, we should discuss what is possible for 9 to at least get mounted files working in 9 for Mac.

**Comment by karlitschek** [comment]
O.K. Sooner or later we need to do this. But please _after_ the other 9 features are done :-) 
And the architecture needs to be discussed so that we don't introduce a performance penalty here.

**Comment by MTRichards** [comment]
Agreed @karlitschek .

**Comment by DeepDiver1975** [comment]
Well - as discussed in this issue long-ish: we don't need the dav lock mechanism given our current scenarios. We ensure atomicity within the operations itself by now (since 8.2).

With respect to MAC integration there are 3rdparty tools which help out as pointed out by @evert 

So I question the real criticality

**Comment by karlitschek** [comment]
@DeepDiver1975 What? You asked for that forever and now that @MTRichards and I are finally convinced you say that it is not critical?  ;-) ;-) ;-)

**Comment by DeepDiver1975** [comment]
> You asked for that forever and now that @MTRichards and I are finally convinced you say that it is not critical? ;-) ;-) ;-)

hehe - well you finally convinced me as well :wink:

**Comment by DeepDiver1975** [comment]
to be serious (any also to clarify my statement): I'm talking about the criticality of this explicit issue - since there is a workaround in place and with respect to this specific issue there is no need for us to provide locking.

**Comment by LukasReschke** [comment]
From @jerrac as I locked this issue and he does not have contributor rights I'm proxying this through:

> From the sounds of the latest comments, the devs are not going to fix 
this bug. Or at least they want to put it on a really low priority. 
> 
> I'm not sure I agree with that. At least not without solid evidence 
that there are few people effected by the issue. 
> 
> If I'm a user, and OwnCloud says it supports webdav, then I'm going to 
assume it supports Finder integration. When Finder mounts as 
read-only, I'm going to assume OwnCloud is broken. Which is true. I'll 
then either quit using OwnCloud, or start up support issues. Those 
issues will end up on admins (like me) desks. Or, if the user knows 
about GitHub, OwnCloud's issue queues. 
> 
> So, to avoid those support requests wasting all of our time, can the 
devs either fix Finder integration, or make it explicitly clear to 
end-users that Finder is no longer supported? 
>
> Like a note next to the webdav info on the web ui. 
>
> A third option would be to post enough details on how the issue needs 
to be fixed that someone could create a pull request that fixed it. 

Thoughts?

**Comment by cmonteroluque** [comment]
I think the idea of having this as targeted for 9.0 makes sense, to be reviewed as we go through the higher priorities. @PVince81 heads up

**Comment by cdamken** [comment]
@cmonteroluque  I have some customers that need a solution about this sooner as 9.0 because its part of their core features.

**Comment by DeepDiver1975** [comment]
@cdamken please propose 3rdparty tools like cyberduck

**Comment by bboule** [comment]
Hey guys IMHO we need to do better here... lets review the customer experience here one day they are chugging along and using WebDav (as it is something that is used for more security focused users), then they upgrade it does not work, then we are going to tell them to go get cyber duck and use that until we short this out in ownCloud 9 then they should switch back again?  This is fine for the one person install, this is NOT a solution for larger scale installs where deploying software and pulling it back again is no easy task...  Is there some middle ground here?  Is 9 the absolute best we can do?  Perhaps we have to have the customer roll back to something prior to 8.1 in order to be able to use WebDav on Mac? thoughts?

**Comment by DeepDiver1975** [comment]
@karlitschek lets chat tomorrow what we can do

**Comment by karlitschek** [comment]
@DeepDiver1975 agreed

**Comment by cdamken** [comment]
@karlitschek @cmonteroluque @DeepDiver1975 @bboule  Any news?

**Comment by karlitschek** [comment]
@DeepDiver1975 @LukasReschke and me discussed this tonight. There is probably an option to simulate webdav lock for the OS X Finder user-agent only. If this works then this could be relatively easily backported to the next release. But some more testing tomorrow is needed before this is 100% sure.

**Comment by cdamken** [comment]
Thanks a lot @karlitschek !

**Comment by LukasReschke** [comment]
PR for master is at https://github.com/owncloud/core/pull/20505

**Comment by MorrisJobke** [comment]
@bboule Just to inform you: The backport to 8.2.2 is merged ;)
