### ISSUE TITLE
HTTP Basic auth broken

### ISSUE THREAD

**Issue by Dreamsorcerer** [owncloud/core#17760]
Following patch #17743, it seems ownCloud still doesn't respond with the WWW-Authenticate header when giving the 401 error.

https://mail.gnome.org/archives/libsoup-list/2015-July/msg00010.html

**Comment by LukasReschke** [comment]
Technically speaking would it be possible that libsoup does not resend the cookies? This error should not appear then at all.

**Comment by LukasReschke** [comment]
As in: If the application just sends Basic Auth without Cookies it _should_ work just fine.

**Comment by danwinship** [comment]
It is not sending Basic Auth, because ownCloud didn't ask it to (by including an appropriate WWW-Authenticate header). [RFC 7235](https://tools.ietf.org/html/rfc7235) says "The server generating a 401 response MUST send a WWW-Authenticate header field (Section 4.1) containing at least one challenge applicable to the target resource."

(I'm not sure why this used to work for the reporter and now it doesn't. And it's supposed to be possible to force libsoup to send auth even if the server didn't ask for it, but that's not working for him either.)

**Comment by Dreamsorcerer** [comment]
Having retested with GNOME 3.10, it isn't working there either anymore. So, maybe it was just the case that ownCloud used to send the correct response on an older version, around OC 6/7 maybe.

**Comment by Dreamsorcerer** [comment]
Considering this is a regression of a feature that worked perfectly fine in previous versions, is there a chance we can get this fixed? My extension was syncing notes with OC perfectly in older versions, it is now completely incapable of syncing.

**Comment by KnooL** [comment]
ownCloud is my daily driver yet it is not functioning as it should. I'd really appreciate if the bug gets any attention to getting fixed. Thanks...

**Comment by dustigroove** [comment]
I use Sticky Notes View in GNOME and would like to see this fixed as OC syncing fails.

**Comment by PVince81** [comment]
Is this still happening with 8.2.2 or 9.0 RC 1 ?

If yes, would be good to have more detailed steps about how to reproduce this.
Without being able to reproduce the problem it will be difficult to provide a fix.

Thanks.
