### ISSUE TITLE
Feature request: paste images

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#17794]
It would be nice to paste images to ownCloud like: http://snag.gy/
snaggy includes HTML5 and a Java applet also.

**Comment by szepeviktor** [comment]
Also: http://ctrlv.in/

**Comment by oparoz** [comment]
How is this different than a simple drag and drop?

**Comment by szepeviktor** [comment]
You have to save a screenshot etc. to drag&drop.

**Comment by oparoz** [comment]
> You have to save a screenshot etc. to a file to be able to drag&drop.

You mean instead of doing a "print screen" and then ctrl +v?

**Comment by szepeviktor** [comment]
Yes.

**Comment by oparoz** [comment]
Got it.

**Comment by szepeviktor** [comment]
[pasteboard](https://github.com/JoelBesada/pasteboard) is open-source.

**Comment by oparoz** [comment]
Yes, but most of it is not needed. The main problem is that it doesn't work on IE, so there is very little chance of it getting integrated (personal opinion).
http://caniuse.com/#feat=clipboard

**Comment by szepeviktor** [comment]
:(

**Comment by szepeviktor** [comment]
Works for me on Win7/IE11
![IE11 paste](http://i.snag.gy/G45RO.jpg)

**Comment by szepeviktor** [comment]
But this is a Java applet that is not open-source.

**Comment by oparoz** [comment]
> But this is a Java applet on snaggy that is not open-source.

Yep, 2 problems.
You don't need the applet if pasting text I think, but that's not really useful in a files sharing app.

**Comment by szepeviktor** [comment]
May there are non-IE users out there.

**Comment by oparoz** [comment]
Maybe it can be introduced as a feature for non-IE users only. You'll have to wait for other people to voice in their opinion :)

**Comment by jzee** [comment]
:+1: I believe it would be a huge usability plus!

**Comment by oparoz** [comment]
@jancborchardt Huge usability plus?

**Comment by Xenopathic** [comment]
If anything, this should be implemented as an app.

**Comment by jancborchardt** [comment]
> The main problem is that it doesn't work on IE, so there is very little chance of it getting integrated

Stuff like this is ok as enhancement since it’s not a core feature at all.

Regarding the thing itself: Nice addition – not sure if it’s a »huge usability plus« though. If someone wants to have a go at it they can. I’d not say this is something for a separate app since it should be present in files, related to the drag&drop area: https://github.com/owncloud/core/pull/10470

**Comment by szepeviktor** [comment]
> most folks don’t really use/know Ctrl+V

That is shocking for me. It is most basic key combination on all PC-s.

Please consider an UI which emphasis Ctrl-V, see: https://github.com/owncloud/core/issues/17794#issuecomment-123504113

**Comment by jancborchardt** [comment]
> > most folks don’t really use/know Ctrl+V
> 
> That is shocking for me.

Well, [90% of American internet users don’t know about Ctrl-F (2010)](http://searchresearch1.blogspot.de/2010/02/why-control-f-is-single-most-important.html). Remember that we discussing on issue trackers are a technical minority.

**Comment by jzee** [comment]
Are you designing a system for 90% of American internet users in 2010? :)

**Comment by jancborchardt** [comment]
@jzee not sure how the remark is relevant. What I meant was that this is certainly a feature low in priority since for the majority of people it’s basically invisible. @szepeviktor @jzee you are very welcome to take a stab at it and submit a pull request.

**Comment by jzee** [comment]
@jancborchardt that was a joking attempt at pointing out that the facts you were pulling are out of date and that I question whether that's true. and that just because it might have been true 5 years ago, it would still be a huge usability plus for me. 

Having said that, I just learned that you seem to be responsible for usability at OC, so have it your way. 

My 2c are that any site with a good reputation for usability does have proper keyboard shortcuts. 

Trello https://trello.com/shortcuts
Twitter https://twitter.com/perform/status/350980645872345088
GMail https://support.google.com/mail/answer/6594?hl=en
Facebook https://www.facebook.com/help/156151771119453
Instagram https://help.instagram.com/help/www/147441522071668
Outlook Webapp https://support.office.com/en-sg/article/Keyboard-shortcuts-in-Outlook-Web-App-63df572e-1078-4562-b45e-b93e07a76ffb

etc.

**Comment by szepeviktor** [comment]
> Well, 90% of American internet users don’t know about Ctrl-F (2010).

That make a developer refrain from coding.

**Comment by jancborchardt** [comment]
@jzee as said: pull requests are very welcome. :) I’m just saying that if you’re »asking« for the feature and want to wait for »us« to implement, then it will take some time.

**Comment by oparoz** [comment]
@jzee - Lots of the site you've mentioned allows shortcuts, yes, put not many offer ctrl+v to paste images.

**Comment by jzee** [comment]
@oparoz - oh yeah. I was arguing for the usefulness of proper keyboard shortcuts as my impression had been that jcb dismissed them as "low priority". 

I believe that they differentiate well-designed systems from systems that appear to be stitched together. And I personally know how much pain it can mean to add hotkeys late in a system design instead of including them systematically early on.

**Comment by jancborchardt** [comment]
> I was arguing for the usefulness of proper keyboard shortcuts as my impression had been that jcb dismissed them as "low priority".

@jzee no. I was just referring to the topic of this specific issue, the ability to paste stuff using Ctrl-V. Unlike simpler keyboard shortcuts this probably takes a significant amount of code.

**Comment by jzee** [comment]
@jancborchardt - for the sake of argument and tongue-in-cheek: is that so? :)

http://stackoverflow.com/a/6338207

Anyway, I don't want to go out on that limb too far and I need to say that I respect the work that you guys are doing to make OC work so well on different browsers and platforms so once again thanks for your good work!

**Comment by szepeviktor** [comment]
> this probably takes a significant amount of code.

Which is already in production. See pasteboard above.

**Comment by jancborchardt** [comment]
@jzee @szepeviktor cool that you already found the relevant code. :) Now it’s only a small step for you to implement it and submit a pull request.

**Comment by PVince81** [comment]
Shouldn't this rather be implemented as a separate app ?
Or is this an extension for the files app ?

**Comment by jancborchardt** [comment]
Depends on how much code this is. Because this is just a small feature and not really an app, people are unlikely to install this – however it might be useful & nice for more experienced folks.
