### ISSUE TITLE
ownCloud instances could violate the EU's privacy directive (2002/58/EC)

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17808]
AFAIK, ownCloud never shows a note to users about how cookies are used, but it is a requirement in the EU.

http://www.cookielaw.org/the-cookie-law/

**Comment by MorrisJobke** [comment]
cc @karlitschek

**Comment by karlitschek** [comment]
Hmmmmmm. @hodyroff what do yo think?

**Comment by oparoz** [comment]
I guess you could say that whoever gives access to his ownCloud via the Internet is responsible for displaying that message, but many won't know how to do that and that puts them at risk of breaking the law.

**Comment by LukasReschke** [comment]
Not a lawyer but had to deal with this thing already from other businesses…

Cookies as uses by ownCloud are subject to Criterion A and B as per [Opinion 04/2012 on Cookie Consent Exemption - WP 29](http://ec.europa.eu/justice/data-protection/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf) which per Article 5.3 of Directive 2002/58/EC is exempted from user consent.

While the "remember me" functionality as per "3.2. Authentication cookies" shall annotate "uses cookies", this is only because:

> … Persistent login cookies which store an authentication token across browser sessions are not
exempted under CRITERION B. This is an important distinction because the user may not be
immediately aware of the fact that closing the browser will not clear their authentication
settings. They may return to the website under the assumption that they are anonymous whilst
in fact they are still logged in to the service. …

This is not really applicable to ownCloud as well since every view where an authentication state makes a difference a the UI clear distinction whether a user is logged-in or not.

This whole cookie law thing is just a huge red herring misinterpreted by a lot of people… That a website from "Cookie Collective is a privacy centric technology business" states a lot of things to make you pay for consulting pretty much sums it up.

See also "[EU legislation on cookies](http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm#section_2)":

> However, some cookies are exempt from this requirement. Consent is not required if the cookie is:
- used for the sole purpose of carrying out the transmission of a communication, and
- strictly necessary in order for the provider of an information society service explicitly required by the user to provide that service.

> Cookies clearly exempt from consent according to the EU advisory body on data protection- WP29pdf include:
- user‑input cookies (session-id) such as first‑party cookies to keep track of the user's input when filling online forms, shopping carts, etc., for the duration of a session or persistent cookies limited to a few hours in some cases
- authentication cookies, to identify the user once he has logged in, for the duration of a session
- user‑centric security cookies, used to detect authentication abuses, for a limited persistent duration
multimedia content player cookies, used to store technical data to play back video or audio content, for the duration of a session
- load‑balancing cookies, for the duration of session
- user‑interface customisation cookies such as language or font preferences, for the duration of a session (or slightly longer)
- third‑party social plug‑in content‑sharing cookies, for logged‑in members of a social network.

**Comment by LukasReschke** [comment]
That said there is also an official "[Cookie Consent Kit](http://webtools.ec.europa.eu/cookie-consent/documentation/)" using plain JS which could also get implemented as application if somebody really wants to go this way :speak_no_evil:

**Comment by karlitschek** [comment]
Very well explained for someone who is ""not a lawyer"  ;-)
I agree. Maybe we should leave this to a 3rd party app.

**Comment by hodyroff** [comment]
Consent with Lukas, there is no legal requirement as ownCloud will typically be used as a service where users are logged in and express consent that way (as part of the rules for users of such service).
What about anonymous download/upload? 
Are those functions using cookies, maybe after password entry?

**Comment by LukasReschke** [comment]
> What about anonymous download/upload? 
> Are those functions using cookies, maybe after password entry?

Generally speaking as soon as you open ownCloud a session cookie is set already due to the way the code is structured. This is something we need to tackle anyways at a point since there are cases where cookies are contra-productive from a performance and security PoV and will get addressed "at some point in the future" anyways.

That session cookie contains a random string and the actual values of the cookie are stored on the server. – So a cookie can point to a lot of different datasets and is also used quite differently in deployments. In fact this is described as "Multipurpose cookie" within WP-29.

This cookie can arguably be described as "user centric security cookie" and/or "UI Customization Cookies" and/or "Load Balancing Session Cookie"; in fact, it is used for quite some purposes including these but no tracking. These would from my opinion also fall under Criterion A or B as per 3.3, 3.5 and 3.6. Please note that the law as well as all these guidelines from the EC have been intentionally written very unspecific. In the end there are a lot of things open to interpretation… *sigh* – a final ruling would thus be only possible by an actual law court…

From my experience unless you really do advertising and/or tracking you're fine to go without such a hint.

> …
> 3.3 User centric security cookies
> The exemption that applies to authentication cookies under CRITERION B (as previously
described) can be extended to other cookies set for the specific task of increasing the security
of the service that has been explicitly requested by the user. This is the case for example for
cookies used to detect repeated failed login attempts on a website, or other similar
mechanisms designed to protect the login system from abuses (though this may be a weak
safeguard in practice). This exemption would not however cover the use of cookies that relate
to the security of websites or third party services that have not been explicitly requested by
the user. 
> …
> 3.5 Load balancing session cookies
Load balancing is a technique that allows distributing the processing of web server requests
over a pool of machines instead of just one. One of the techniques that are used to achieve
load balancing is based on a “load balancer”: web requests from the users are directed to a
load balancing gateway which forwards the request to one of the available internal servers in
the pool. In some cases, this redirection needs to be persistent during a session: all requests
originating from a specific user must always be forwarded to the same server in the pool to
maintain the consistency of the processing. Among several techniques, a cookie may be used
to identify the server in the pool in order for the load balancer to redirect the requests
appropriately. These are session cookies.
> …
> 3.6 UI customization cookies
> User interface customization cookies are used to store a user’s preference regarding a service
across web pages and not linked to other persistent identifiers such as a username. They are
only set if the user has explicitly requested the service to remember a certain piece of
information, for example, by clicking on a button or ticking a box. They may be session
cookies or have a lifespan counted in weeks or months, depending on their purpose.
Typical examples of customization cookies are:
- Language preference cookies that are used to remember the language selected by a
user on a multilingual website (e.g. by clicking on a “flag”).
- Result display preference cookies that are used to remember the user’s preference
regarding online search queries (e.g. by selecting the number of results per page).
These customization functionalities are thus explicitly enabled by the user of an information
society service (e.g. by clicking on button or ticking a box) although in the absence of
additional information the intention of the user could not be interpreted as a preference to
remember that choice for longer than a browser session (or no more than a few additional
hours). As such only session (or short term) cookies storing such information are exempted
under CRITERION B. The addition of additional information in a prominent location (e.g.
“uses cookies” written next to the flag) would constitute sufficient information for valid
consent to remember the user’s preference for a longer duration, negating the requirement to
apply an exemption in this case. 
> …

**Comment by oparoz** [comment]
@hodyroff http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm

"authentication cookies, to identify the user once he has logged in, for the duration of a session" is exempt, so I guess the public page is safe.

I should have used that page to look for info instead of the other one since it didn't mention any exceptions.

**Comment by oparoz** [comment]
I'll also add that the law is under review and that things will change in 2016.

**Comment by LukasReschke** [comment]
> I should have used that page to look for info instead of the other one since it didn't mention any exceptions.

Hehe - lots of people actually are making quite some $$$ with offering consulting about this :speak_no_evil:

**Comment by danimo** [comment]
> I should have used that page to look for info instead of the other one since it didn't mention any exceptions.

@oparoz Of course not, it's a scare site (despite the .org domain) that tries to sell you compliance consultancy. Why would they mention nitty-gritties like that? :)

**Comment by oparoz** [comment]
But hold on, I think there is a distinction between notifying and getting consent.

I think you don't need to get the user's consent to use session cookies, but you're still required to notify them that you're using cookies.

**Comment by oparoz** [comment]
There are clearly 2 steps

Gain consent
> Before storing cookies, gain consent from the users (if required) by implementing the Cookie Consent Kit in all the pages of any website using cookies that require informed consent.

Inform users
> Inform users about the use of cookies in plain, jargon‑free language in a dedicated "cookie notice" page linked from the service toolbar of the standard templates. 
...
the types of cookies used (e.g. session or permanent, first or third‑party)
...

**Comment by LukasReschke** [comment]
Users only need to be informed if no informed consent is required:

> Before storing cookies, gain consent from the users (if required) by implementing the Cookie Consent Kit in all the pages of any website **using cookies that require informed consent**.

Article 5.3 basically allows cookies to be exempted from the requirement of informed consent if they fall under Criterion A or B.

**Comment by LukasReschke** [comment]
Note that "Use on EUROPA" only refers to "europa.eu" websites, they do quite some more things such as even having a disclaimer if a site has no cookies etc. – They are basically the only persons in the world implementing this at all :speak_no_evil:

**Comment by oparoz** [comment]
Yes, but the law is clear:

> Where such devices, for instance cookies, are intended for a legitimate purpose, such as to facilitate the provision of information society services, their use should be allowed on condition that users are provided with clear and precise information in accordance with Directive 95/46/EC about the purposes of cookies or similar devices so as to ensure that users are made aware of information being placed on the terminal equipment they are using

**Comment by oparoz** [comment]
Looking at the cookies I get on the public page, it's going to be tricky to implement something because any app can add their cookies and they do and it's not only for the session. Admins will not know they're not compliant unless told.

For standard users, people who offer public registration will have to include ToS, PP, cookie consent, etc., but that's out of scope for core.

**Comment by LukasReschke** [comment]
> Looking at the cookies I get on the public page, it's going to be tricky to implement something because any app can add their cookies and they do and it's not only for the session. Admins will not know they're not compliant unless told.

That's an argument that I'm going to accept as valid. – Yes, especially third-party apps may make do all kind of shenanigans including tracking which without doubt is not covered by any exemption. Which however then come down again to the fact that these cookies should be able to opt-out etc.
(Did I mention that this whole law is completely questionable?)

With that regards what would make sense is:

1. In the login page a small link to a disclaimer including the note that cookies used by ownCloud are used solely for the purpose of authentication etc. (as per http://ec.europa.eu/ipg/design/templates/index_en.htm)
2. A small public API that allows developers to add custom text / sections to that page. - A somewhat vague title such as "Legal notices" may make this also reusable for https://apps.owncloud.com/content/show.php/Imprint?content=153220. Which unfortunately is unmaintained but used by quite some persons.

Makes sense? Though nothing to backport from my PoV and technically this will likely only be about a few new lines of PHP code.

**Comment by oparoz** [comment]
Yes, I think if that "legal notice" title could appear on public pages and devs could add to it, ownCloud would have a good solution to that problem.

I've also suggested making changes to the app store: https://github.com/owncloud/appstore-issues/issues/29

**Comment by PVince81** [comment]
What's the next step here ?

**Comment by DeepDiver1975** [comment]
> What's the next step here ?

Continue discussion in the scope of 9.0 :see_no_evil:

**Comment by PVince81** [comment]
This could be implemented as an app that shows a banner once on the login page and also on public pages. The app could then be enabled only on instances that really require it.

Move to backlog ?

**Comment by PVince81** [comment]
cc @pmaier1 @felixboehm

**Comment by DeepDiver1975** [comment]
close - I see no reason to keep this open.

noone will ever look at this issue and say: cool - I'll implement that
