### ISSUE TITLE
Request: Security and Setup Alerts

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#17875]
I think it would be much better, if you can color the "optional" Alerts yellow istead of red.
Things like "SQLite" or "PHP Memory Cache" are not any kind of error. But user could think that, when they see an "red" (error) message.

**Comment by karlitschek** [comment]
good idea. @jancborchardt What do you think?

**Comment by RealRancor** [comment]
Completely agree with that. We had already a lot of forum users stating "i'm getting an error about memory cache". They didn't understand that this is just an suggestion and not an error.

**Comment by jancborchardt** [comment]
Well if it’s optional we shouldn’t color them at all. Yellow will also suggest some kind of warning.

@karlitschek @DeepDiver1975 in the past you said it should be colored red because things like the usage of SQLite belong in the »Security & setup warnings« section, which is supposed to be all red. We can of course have some of the things be warnings and some just suggestions (non-colored) cc @LukasReschke

**Comment by karlitschek** [comment]
I think there are 2 different kind of messages that we show here.
The red ones are fatal. Something that means that your ownCloud is completely broken or your data is exposed to the internet because of configuration problems. This should be red.

And then we have messages that suggest that people should do this to improve the user experience. This are sqlite or memory cache. This should be yellow or non-colored.

**Comment by aspdye** [comment]
What about making them like in the owncloud log. (Selecting in a dropdown-menu):

-All (all errors, notices)
-Fatal (should also popup when you login as an admin)
-Performance (Mem Cache; SQLite; Old PHP Version!!!)
-Security + Privacy (SSL, Force-SSL, Encrypt (ext. Storage))
-Hidden

You should also be able to select "Do not show again" (then, the notice is stored in "Hidden" Section) 

Another feature would be a "solve" button. SQLite etc. are easy to fix. We could link to an step-by-step guide on the OwnCloud Website.

**Comment by aspdye** [comment]
Here is a litte concept: 
![oc1](https://cloud.githubusercontent.com/assets/12893462/8910524/9a92148a-3487-11e5-9cc3-3d75241979e3.PNG)

**Comment by oparoz** [comment]
First step is to implement this: https://github.com/owncloud/core/issues/17109

**Comment by jancborchardt** [comment]
Having a level for this would be going over the top. We should decide which messages are important and which are not. The non-critical ones could go into the »Server status« section on the bottom.

**Comment by jancborchardt** [comment]
This was solved. As for the ones which show up, we’re sticking with red because it’s more easily readable than yellow. cc @LukasReschke
