### ISSUE TITLE
Migrate keys from 8.1.0 to 8.1.1 (stable8.1) causes errors downloading files

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#17983]
### Steps to reproduce
1. Install OC 8.1.0 and enable encryption
2. Upload a file (in /foolder/foo.txt)
3. Share the file with another user and by link  (probably not required)
4. Upgrade OC to 8.1.1 (currently this day stable8.1)
5. Re-enable encryption from command-line  (probably not required)
6. Migrate the keys `occ encryption:migrate`
7. Download the file uploaded in step 2

### Expected behaviour
Either the key migration is prevented, or the file is downloaded properly

### Actual behaviour
Migration shows success:
```
Reorganize system folder structure
Migrating keys for users on backend Database
   admin
   foo_user
   user
```
However, the file isn't downloaded. This is from an automatic failed script, so no much more info. Either the file download get an error or the download is empty.

Without migrating the keys, the download is fine

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** stable8.1

**Updated from an older ownCloud or fresh install:** update from 8.1.0

**Comment by DeepDiver1975** [comment]
@schiesbn mind having a look? THX

**Comment by schiesbn** [comment]
You don't need to perform step 5 and 6, although of course it shouldn't break anything. I will try if I can reproduce it.

**Comment by schiesbn** [comment]
ok, seems like the migrate script kills the keys... I will look into it. If you just update from 8.1.0 to 8.1.1 (without re-enablling encryption (should still be enabled) and without running the migration script) everything works fine.

**Comment by schiesbn** [comment]
@jvillafanez the pull request above should fix it. I will prepare a backport PR so that you can test it against 8.1

**Comment by schiesbn** [comment]
@jvillafanez here is the stable8.1 backport: https://github.com/owncloud/core/pull/17990
Now you can call ````occ encryption:migrate```` how often you want and it shouldn't break :wink:

**Comment by jvillafanez** [comment]
Checked the stable8.1 backport :+1: 

The migration stills shows success, as if there was a migration. Is it possible to change the message?

**Comment by schiesbn** [comment]
@jvillafanez hm, the "problem" is that you can run the migration multiple times. E.g. if you just want to migrate specific users, if you want to run it again because you restored a backup from a user from before the migration, etc. So I think it is hard to distinguish this cases and for the admin the important notice is "it was executed without a error", if something was done or not doesn't really matter. 

The key message is that everything is migrated without a error. So I would keep it this way. Anyway it is a corner case because we only tell people in the 8.0 to 8.1 migration documentation to run the script. Most user will not run it for any other update. 
Still it is good that you found the error and that we fixed it. Of course we shouldn't break ownCloud just because someone runs a script again.

**Comment by schiesbn** [comment]
@jvillafanez most important: Thanks for testing it once more and verify that it works!
