### ISSUE TITLE
Upgrade of an application really slow

### ISSUE THREAD

**Issue by lparmentier-quatral** [owncloud/core#18017]
I've upgrade from OC6 to OC 8.0.4 everything is done, and working.

But i've some trouble when i'm doing an upgrade when i change the file
'version' of any custom application (so no core apps), it took something
like 30minutes...

Why is it so long ? i've just change a number in file of a custom
application. Nothing else (no update of OC, not update of core apps, no
change of databse).

For example:
~/public_html$ php console.php upgrade
Turned on maintenance mode
Checked database schema update # take 20 minutes
Checked database schema update for apps
Updated database
Updated <my_custom_app> to 0.1.1 # the file 'version' that change, few
second for update
Turned off maintenance mode
Update successful

Why schema update for each change take something like 20 minutes ?

Note: I've a huge database (2GB with ~1GB for oc_filecache, and ~1GB for oc_activity)

**Comment by karlitschek** [comment]
Not sure this is an ownCloud but. seems to be more like a questin. please ask this question on the owncloud forum or mailinglist. thanks

**Comment by lparmentier-quatral** [comment]
This is an owncloud core problem ^^... probably link with an 'ALTER TABLE' of table which is done on every upgrade, and should be done only once !

This could also link with the fact that we use InnoDB as engine ?

**Comment by karlitschek** [comment]
O.K. Then we need a full bug report using the issue template as seen when open an issue including a way to reproduce this. This problem wasn't reported by anyone else yet and can=t be repdoduced by me. So it is likely that it has something to do with your db setup or config.

**Comment by Yetangitu** [comment]
I don't have the time to make a full bug report at the moment but I can confirm this issue. Even when running the upgrade with the '--skip-migration-test' option it takes close to half an hour to run, even when only a single app needs updating. Most of that time is spent by the database server (tested with both mysql and postgres) reading (...and reading, and reading...) the database. In my case the database measures in at ~7GB, most of which is taken by the filecache due to the inclusion of a large externally mounted reference library. That 7GB database explodes to ca. 700GB of disk reads (tested with postgres and atop, average disk read rate of ~80 MB/s) during an upgrade with '--skip-migration-test'.

**Comment by Yetangitu** [comment]
I enabled query logging in postgres and forced an upgrade by manually lowering the version number of an installed app (files_opds, 0.6.8 is installed, manually edited the value of the installed version in oc_appconfig to 0.6.7). The query log clearly shows where the slowdown occurs:

```sql
2015-08-15 17:40:36 CEST [5223-2927] user@hostname LOG:  execute <unnamed>: 
				UPDATE "oc_filecache"
				SET "mimetype" = $1
				WHERE "mimetype" <> $2 AND "name" ILIKE $3
			
2015-08-15 17:40:36 CEST [5223-2928] user@hostname DETAIL:  parameters: $1 = '17', $2 = '17', $3 = '%.something'
2015-08-15 17:41:30 CEST [5223-2929] user@hostname LOG:  duration: 53949.963 ms
```

This code sequence - which runs for about 54 seconds - is repeated for a host of mimetypes from . The actual code which causes the slowdown lives in `lib/repair/repairmimetypes.php` in `updateByNameStmt()`:

```php
        private static function updateByNameStmt() {
                return \OC_DB::prepare('
                        UPDATE `*PREFIX*filecache`
                        SET `mimetype` = ?
                        WHERE `mimetype` <> ? AND `name` ILIKE ?
                ');
        }
```

The slowdown is caused by the use of 'ILIKE' causing a sequential scan of the database:
```sql
database=> explain analyze UPDATE "oc_filecache" SET "mimetype" = '17' WHERE "mimetype" <> '17' AND "name" ILIKE '%.pfb';
                                                          QUERY PLAN                                                          
------------------------------------------------------------------------------------------------------------------------------
 Update on oc_filecache  (cost=0.00..770745.74 rows=867 width=388) (actual time=54247.628..54247.628 rows=0 loops=1)
   ->  Seq Scan on oc_filecache  (cost=0.00..770745.74 rows=867 width=388) (actual time=6027.367..53998.979 rows=128 loops=1)
         Filter: ((mimetype <> 17) AND ((name)::text ~~* '%.pfb'::text))
         Rows Removed by Filter: 10920187
 Planning time: 1.199 ms
 Execution time: 54247.689 ms
(6 rows)
```

There are several ways this can be speeded up, but they tend to be database-specific. Postgres (as of 9.1) can do indexed searches on non-left-anchored patterns using the `pg_tgrm` extension, this changes the picture radically:

```sql
database=> explain analyze UPDATE "oc_filecache" SET "mimetype" = '17' WHERE "mimetype" <> '17' AND "name" ILIKE '%.pfb';
                                                                    QUERY PLAN                                                                    
--------------------------------------------------------------------------------------------------------------------------------------------------
 Update on oc_filecache  (cost=58.57..3371.48 rows=831 width=388) (actual time=7.141..7.141 rows=0 loops=1)
   ->  Bitmap Heap Scan on oc_filecache  (cost=58.57..3371.48 rows=831 width=388) (actual time=7.138..7.138 rows=0 loops=1)
         Recheck Cond: ((name)::text ~~* '%.pfb'::text)
         Filter: (mimetype <> 17)
         Rows Removed by Filter: 128
         Heap Blocks: exact=8
         ->  Bitmap Index Scan on oc_filecache_name_gin_trgm_idx  (cost=0.00..58.37 rows=849 width=0) (actual time=6.780..6.780 rows=128 loops=1)
               Index Cond: ((name)::text ~~* '%.pfb'::text)
 Planning time: 15.851 ms
 Execution time: 7.321 ms
(10 rows)
```
The execution time went down from 55 seconds to 7 ms... Creating and maintaining this index does incur a cost, so it is debatable whether this is worth the effort just to speed up this single case.

If you run postgres and you want to try this method, enable pg_tgrm for your database and create an index on *DBPREFIX*_filecache.name using GIN or GiST by logging in as administrator, connecting to your OC database and running the following:
```sql
database=# create extension pg_trgm;
CREATE EXTENSION
database=# CREATE INDEX oc_filecache_name_gin_trgm_idx on oc_filecache USING gin(name gin_trgm_ops);
CREATE INDEX
```
I'll run a test instance with this index for a while to see whether it causes performance problems elsewhere, if it doesn't it is probably worth it for those who use Postgres. As to a solution for MySQL I don't know yet (I'm gradually phasing out MySQL so don't hold your breath...).

**Comment by Yetangitu** [comment]
In retrospect, the best solution to this problem is probably to move the mime checks to a separate upgrade command, to be executed at will or possibly as a (nightly) cron job. Alternatively, an option could be added to skip these checks (`--skip-mime-repair`) during upgrade.

**Comment by Xenopathic** [comment]
@Yetangitu wow, that's quite an analysis you've got there!

cc @rullzer RE: the mimetype stuff

**Comment by Yetangitu** [comment]
I added that 'skip-mime-repair' option to the occ upgrade command. The next step is to create a separate mime-repair command, easy enough but I have not done so yet...

https://github.com/Yetangitu/core/commit/2ca0c9ab1d5aa9724727e0058c6ddb9bba8e450a

**Comment by Yetangitu** [comment]
Looking a bit deeper into the available occ commands it seems to me that occ maintenance:repair already fulfills the need for a 'separate mime-repair command'. In other words, adding the `--skip-mime-repair` option should be enough to create the flexibility needed to run fast non-core upgrades. Maybe the upgrade routine should be smart enough to know when to run the mime repair functions...

**Comment by PVince81** [comment]
The mime repair is supposed to happen only once for a specific version of OC.
Not sure why it's still running now.

**Comment by PVince81** [comment]
I suggest to add an OC version check every time new mimetypes repair steps are introduced.
For now we could add a "if ownCloud version < 8.2.0" then run them all.
Starting with 8.2.0 they won't run.

But if someone introduces a new mime type repair for 9.0, they'd need to add another check "if ownCloud version < 9.0" then run that extra check.

@oparoz @Yetangitu what do you think ?

**Comment by Yetangitu** [comment]
A (working) version check sounds like a good plan, preferably one which happens without the need for developer intervention. Maybe by generating a hash of the mime mangling code, storing that hash in the database and checking it on every update? If the hash in the database is different from the one calculated from the code base, execute the mime repair code...

As to how to generate that hash I have not spent any cycles yet. Someone who has a good overview of the way mime types are handled should be able to come up with a simple scheme I'd say?

**Comment by PVince81** [comment]
Computing a hash sounds a bit over-engineered for such a small part.
Also many other update routines rely on version numbers, so I think it might be better to use that approach instead.

**Comment by PVince81** [comment]
Fix is here with a version check: https://github.com/owncloud/core/pull/18548

**Comment by cmonteroluque** [comment]
@PVince81 not sure whether we've decided the fix is thorough enough. It's unclear whether we're good enough to review/merge/close or the solution is too partial

**Comment by PVince81** [comment]
My fix is only for one of the several potential slow factors, one of the obvious ones.
So even if we merge the PR we could keep this ticket open to track other potential slow factors. (step by step)

**Comment by ferdiga** [comment]
after updating from 8.0.3 to 8.1.1 I enabled documents and calendar again and this caused a timely very expensive Repair Mime Types run AGAIN - 
IMO this should be automated as mentioned  in https://github.com/owncloud/core/issues/18548

**Comment by PVince81** [comment]
The version check has been added in 8.2. So upgrading from 8.1.x to 8.2.x should be the last time the repair will happen for the same already repaired/known mime types.

**Comment by ferdiga** [comment]
Yes, but it will run on all mime types for upgrade
I suggest to check only NEW mime types during upgrade

**Comment by ferdiga** [comment]
apparently 
AND `name` COLLATE utf8_general_ci LIKE '%.arw' 
is expensive as COLLATE uses a full table scan.

probably it could be a performance improvement if only mimetypes are checked which exists -
for example here I do not have '%.arw' files

**Comment by PVince81** [comment]
@ferdiga strange, it should not try to update mime types that don't exist in your database. Before doing a repair it first does a SELECT here https://github.com/owncloud/core/blob/v8.2.0/lib/repair/repairmimetypes.php#L106 to find out if the mime type to repair exists.

If you ever had "arw" files in the past and do not have now, then it is likely that the "oc_mimetypes" table did contain an entry for these.

**Comment by ferdiga** [comment]
MariaDB [owncloud]> select * from oc_mimetypes where mimetype like '%arw%';
Empty set (0.01 sec)

probably it does only so if the previous version >= 8.2

**Comment by butonic** [comment]
@PVince81 @MorrisJobke this does impact larger installations where a full table scan of the filecache can take up to a minute. With 35 mimetypes that are updated (or inserted) a migration takes at least 30 min because there is no index that can be used. Be aware of that on big installations.

To complete the upgrade, is it safe to comment the mimetype repair und schedule it for a later execution? AFAIR it was only a problem for preview icons?

**Comment by butonic** [comment]
@PVince81 Hm it might make more sense to use one expensive select that lists all files that end in a problematic extension, iterate over them in php and do the updates sequentially. Or collect fileids and do `update ... where in (...)` queries.

Should i create a new ticked or do we reuse this one since the analysis in https://github.com/owncloud/core/issues/18017#issuecomment-131400367 is on the spot.

**Comment by butonic** [comment]
It would also allow us to log which files were affected.

**Comment by PVince81** [comment]
Let's make a new more explicit ticket with the title "Improve mimetype repair performance".
Thanks.

**Comment by butonic** [comment]
ref https://github.com/owncloud/core/issues/21974

**Comment by butonic** [comment]
@PVince81 will do
