### ISSUE TITLE
Create database as last step of setup procedure

### ISSUE THREAD

**Issue by b2ag** [owncloud/core#18179]
I disabled my .htaccess for OC to hunt down a Redirect-Issue. Then I reinstalled by clearing config.php, database and data directory. Setup failed because of the htaccess-issue and forced me to clear the database again.

**Comment by DeepDiver1975** [comment]
While I understand that this was quite annoying for you I have slightly different view on this topic:
The setup procedure was working this way for a very long time almost unchanged (with respect to the order of operations) and we never had bigger issues.

I honestly would simply not change this "just" because of this one time annoyance. Thanks a lot!
