### ISSUE TITLE
8.1.1 Enabling an app always triggers core update

### ISSUE THREAD

**Issue by Aesculapius** [owncloud/core#18235]
After enabling an app from the built-in appstore, I can always just enable one app at a time. Clicking a second app to enabled, turns that one into a red 'failed'. Also, going back to files view, the update screen is triggered, telling me to upgrade (again) to 8.1.1. I'm forced to update at that point. After updating, the app appears to be installed correctly though.

Expected behavior: 
- I'd expect the app to be enabled instantly without an intervening update process.
- Also I'd expect to be able to enable more apps at once, rather than moving to files app and back.

OC 8.1.1 running under Ubuntu 14.04 and PHP 5.5.9-1 with APCu enabled.

**Comment by karlitschek** [comment]
@DeepDiver1975 Can you check this one? I know that you looked into that a while ago.

**Comment by PVince81** [comment]
Third party apps get disabled during an update, so they don't get updated during that process (or maybe just the code but not the DB?)
When you reenable the app afterwards, its database needs to be updated. This is what triggers this update screen. The text is wrong, it should say "updating app" instead of core.

Here is work in progress to make this clearer: https://github.com/owncloud/core/pull/17434

Let's keep this ticket here to discuss ways to make the experience smoother in the future.
Like you said, ideal would be the ability to reenable all apps on the fly and upgrade them at the same time.

**Comment by RealRancor** [comment]
@PVince81 isn't the confusing message already tracked at https://github.com/owncloud/core/issues/16272

**Comment by PVince81** [comment]
@RealRancor yes, thanks. Then let's close this as duplicate.
