### ISSUE TITLE
Allow deleting encrypted files with missing keys

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18270]
Sometimes it happens that files might have missing keys, for example when switching external storages or using older external storages. As a user, I would still like to be able to delete the broken files from the web UI.

### Steps to reproduce

1. Setup OC 8.2 (master)
1. Enable encryption
1. Mount SFTP external storage as "/sftp"
1. Upload a file "test.jpg" into "/sftp/test.jpg"
1. Reset ownCloud (or setup another instance)
1. Enable encryption
1. Mount the same SFTP external storage as "/sftp"
1. Delete "/sftp/test.jpg" (knowing it's broken, just want to get rid of it)

### Expected result
File can be deleted

### Actual result
File stays, UI says "Could not delete file"
```
{"reqId":"lRnLhcE3N0ZEmDYuBO1F","remoteAddr":"127.0.0.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2015-08-13T10:40:33+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2Fsftp%2Ftest.jpg&c=55cc74216a1c8&x=36&y=36&forceIcon=0"}
{"reqId":"4wXi6dOnfIxQel+jto6T","remoteAddr":"127.0.0.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2015-08-13T10:40:36+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
```

It also happens if I **don't** enable encryption the second time.

@schiesbn

**Comment by schiesbn** [comment]
Problem is that we perform a stream copy to the trashbin which of course fails if we can't decrypt the source.

I don't see what we can do here. We could try to catch the error and perform the move without the encryption wrapper if the source or target starts with ````files_trashbin/...```` But this would be a really ugly fix and would maybe even hide issues when something is wrong on the system.

I think it is a fair assumption that if ownCloud move encrypted files all keys need to be available otherwise we fail to prevent that we completely mix up the system. -> close @PVince81 if you disagree re-open and suggest a feasible solution.
