### ISSUE TITLE
admin.js Uncaught TypeError: OC.SetupChecks.checkGeneric is not a function

### ISSUE THREAD

**Issue by exemmer** [owncloud/core#18289]
/index.php/settings/admin

Spinner appears and under "Security & setup warnings" and does nothing.  Further investigation in Chrome shows

"Uncaught TypeError: OC.SetupChecks.checkGeneric is not a function" admin.js:174

![image](https://cloud.githubusercontent.com/assets/9574727/9253684/14083a0e-41d7-11e5-948a-78ae954b85f6.png)

Owncloud, however, seems to be running fine!
v 8.1.1 (stable)
PHP Version 5.5.9-1ubuntu4.11

**Comment by karlitschek** [comment]
@LukasReschke any idea?

**Comment by LukasReschke** [comment]
Please be a bit more precise. Which chrome version? Did you clear your cache? Any chance to get access to that instance on my own so I can double-check?

**Comment by exemmer** [comment]
Sorry!  the never ending spinner is not only in Chrome, but also in IE. It's also on two different OC servers, running two different Linuxes, and two different PHP versions - but both servers were upgraded to 8.1.1. upgraded today)  Tried on multiple clients PCs with multiple browsers.

**Comment by LukasReschke** [comment]
Can you fill out the information from https://github.com/owncloud/core/blob/master/CONTRIBUTING.md? Thanks!

**Comment by PVince81** [comment]
This error message is very strange.

First, from here we can see that `checkGeneric` is called as the third argument: https://github.com/owncloud/core/blob/v8.1.1/settings/js/admin.js#L167
This means that the class `OC.Settings` exists since it was able to run the two previous arguments.

If the class `OC.SetupChecksexists`, then `OC.SetupChecks.checkGeneric` should be a proper function. Its definition is here: https://github.com/owncloud/core/blob/v8.1.1/core/js/setupchecks.js#L95

Maybe there's a third party app overwriting the OC.SetupChecks namespace instead of extending it ?

@exemmer you could also try typing the following on the JS console:
```
OC.SetupChecks
OC.SetupChecks.checkGeneric
OC.SetupChecks.checkWebDAV
```

It should return something like this:
![js-setupchecks](https://cloud.githubusercontent.com/assets/277525/9404514/9adb7770-47f0-11e5-9aa1-32ba8019b0e6.png)

**Comment by MorrisJobke** [comment]
@exemmer Can you please provide the information? We cannot reproduce your issue and therefore are unable to fix it. Feel free to comment in here and I will reopen the issue then. So far I will close this for now due to inactivity.
