### ISSUE TITLE
Previews of text files not working in trashbin

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#18516]
### Steps to reproduce
1. Upload an image and a text file
2. Delete both files
3. Go to trashbin

### Expected
Both rows have a preview

### Actual
The image has a preview
The text has the mimetype icon

@oparoz @georgehrke @PVince81

**Comment by PVince81** [comment]
@schiesbn I thought previews never worked in trashbin ?

**Comment by georgehrke** [comment]
previews are supposed to work in trash bin.
Quite interesting, that images work, but txt files don't :confused:

**Comment by rullzer** [comment]
It is because of https://github.com/owncloud/core/blob/master/apps/files_trashbin/ajax/preview.php#L66 but we really should get rid of that ajax endpoint :P

**Comment by georgehrke** [comment]
> It is because of https://github.com/owncloud/core/blob/master/apps/files_trashbin/ajax/preview.php#L66

The answer ain't that simple. ;)

The problem is, that [inside Helper::formatFileInfos](https://github.com/owncloud/core/blob/bbd1e996050fee80795d0e656da98b6451232c6c/apps/files_trashbin/lib/helper.php#L113) `$i['path']` equals `/admin/files_trashbin/files//welcome.txt`, but the actual file is `/admin/files_trashbin/files/welcome.txt.d1442741096`.

A preview for a text file is only available if it's not empty because we don't want to show just a blank preview. As `/admin/files_trashbin/files//welcome.txt` doesn't exist, the size is zero and therefore a preview is not available.

@schiesbn Is `$i['path']` meant to be `/admin/files_trashbin/files//welcome.txt` or is that a bug?
If it's intended, is there a way to get the real path?

**Comment by schiesbn** [comment]
fix is above, please review, thanks.

A general question

> A preview for a text file is only available if it's not empty because we don't want to show just a blank preview.

@georgehrke why do we have this special behavior for text files only? I can guess why, because you can create empty text files in the files app. But users could also upload a empty image or any other empty file. Shouldn't we check if for all files or for none, just to be consistent?

**Comment by georgehrke** [comment]
> I can guess why, because you can create empty text files in the files app.

Exactly.

> But users could also upload a empty image 

What do you mean by empty images. jpg or png files with a size of 0 or all-transparent?

If you upload a 0 zero byte image imagegd can't read it and it falls back to the mimetype-icon.
If you upload an all-transparent image, it's actually just a white preview.
Maybe we should add a [checked background](http://i.stack.imgur.com/TMCfE.png). What do you think @jancborchardt?

> any other empty file. 

As long as it is not a text file, it'll just fall back to the default mime-type icon.
