### ISSUE TITLE
[db-locking] warnings about lock aquisition within transaction

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#18584]
@icewind1991 looks like there are cases where the lock is acquired within a transaction.

Please have a look! THX

This happened during unit test execution.

````
{"reqId":"kNsihqnPnqxAZ61XPM1N","remoteAddr":"","app":"no app in context","message":"Trying to acquire a lock for 'files\/27859b501316c7e0d812f1ebaa2e7a1c' while inside a transition","level":2,"time":"2015-08-26T13:10:32+00:00"}
{"reqId":"kNsihqnPnqxAZ61XPM1N","remoteAddr":"","app":"no app in context","message":"Trying to acquire a lock for 'files\/85091565d033538a39eaeb824a3e1398' while inside a transition","level":2,"time":"2015-08-26T13:10:32+00:00"}
{"reqId":"kNsihqnPnqxAZ61XPM1N","remoteAddr":"","app":"no app in context","message":"Trying to acquire a lock for 'files\/9f6090f3105d52dc9f7f7cb9bf4ea606' while inside a transition","level":2,"time":"2015-08-26T13:10:32+00:00"}

**Comment by Xenopathic** [comment]
This occurs because scanChildren() uses transactions, but also tries to lock files while scanning them (which also uses transactions). Namely here: https://github.com/owncloud/core/blob/master/lib/private/files/cache/scanner.php#L337

If we merge #18993, can we drop the use of transactions in the DB locking provider? I think that the approach in #18993 won't even work with transactions, since it checks the result of the insertIfNotExists() to determine whether to do an update. So that could be the solution.

**Comment by individual-it** [comment]
#18993 should work fine with transactions
http://www.mysqltutorial.org/mysql-transaction.aspx
you easily can do: 
````
START TRANSACTION;
# MySQL returned an empty result set (i.e. zero rows). 

SELECT * FROM `oc_file_locks` WHERE `lock` >= 1;
# Rows: 9 

INSERT INTO `oc_file_locks`(`lock`, `key`, `ttl`) VALUES (1,"sssssssss",0);
# 1 row affected.

UPDATE `oc_file_locks` SET `lock`=0 WHERE 1;
# 9 rows affected. 

ROLLBACK;
# MySQL returned an empty result set (i.e. zero rows). 
````

So if PHP checks in between the number of affected rows by INSERT or the return of the SELECT it should not be a problem.

I actually think if we use transactions in acquireLock() we should also roll back.
Check the discussion in #18918

This log message comes from https://github.com/owncloud/core/blob/master/lib/private/lock/dblockingprovider.php#L79
It is checked if the connection is in transaction but it does not have any consequences. The code could wait till the transaction is finished. Or throwing a LockedException similar to my proposed solution in https://github.com/owncloud/core/issues/18918#issuecomment-139479777

**Comment by icewind1991** [comment]
The problem with transactions is that any lock set while within a transaction would not be visible for other processes/threads until the transaction is committed.

If trying to start a transaction while another process already has a transaction open on the db causes db exceptions (see #18918) then it wouldn't be a problem though (as long as we convert the db transaction in a locked exception where needed) since we would still be protected from 2 processes trying to get a lock at the same time

**Comment by PVince81** [comment]
In the light of the recently merged PR https://github.com/owncloud/core/pull/19098, is there any follow up on this discussion ?

**Comment by individual-it** [comment]
As stated here https://github.com/owncloud/core/pull/19098#issuecomment-141092798 and discussed in IRC I would rather throw an exception than filling the log.
Cannot see what the log entry helps.
If other also think throwing an exception is a good way, I can make a PR

**Comment by nickvergessen** [comment]
@icewind1991 this is still spamed in smashbox, any update? Is intended, should be removed, needs fixing somehow?

**Comment by icewind1991** [comment]
I think we can remove the warning now that locking no longer uses transactions itself

**Comment by icewind1991** [comment]
cc @DeepDiver1975

**Comment by karlitschek** [comment]
I agree. Nothing for the user or admin to do here anyway

**Comment by icewind1991** [comment]
#19367

**Comment by DeepDiver1975** [comment]
> #19367

merged -> close
