### ISSUE TITLE
Creating a new file/folder opens the search bar

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#18674]
Tested on master:

Create a new file or folder by:

- clicking on "New"
- select "Text file" (or "Folder")
- chose a name
- press enter

-> file/folder will be created and the search bar at the top right gets opened and we put the focus on it.

cc @PVince81 probably some js issue, can you have a look? Thanks!

**Comment by PVince81** [comment]
Yes. Should be tackled through #18238 / the "Details" file actions.

@jancborchardt we need a decision there

**Comment by raghunayyar** [comment]
I am closing this issue as a duplicate in that case.

**Comment by jancborchardt** [comment]
This is not a duplicate of that at all? I agree with @schiesbn on this specific case.

**Comment by PVince81** [comment]
We can keep it open but the problem will disappear once we have the "Details" item.
The sidebar will either stay closed or opened depending on its last state.

**Comment by jancborchardt** [comment]
I kind of fail to see how the new files dialog and the search bar relate to the details item in the actions menu. ;D

**Comment by PVince81** [comment]
Currently on master the sidebar opens and closes based on whichever file is focussed.
In that PR that brings the new "Details" menu, the sidebar behavior is changed: the sidebar always stays in its last state.

This ticket here is about the create action toggling the sidebar by mistake, probably because the focus is moved on the new file. In that PR, setting the focus on the new file would not change the sidebar's state due to the new behavior, so doesn't need a specific fix.

**Comment by PVince81** [comment]
I'm ok with keeping this ticket open until the other PR is merged, then we can double check that it indeed fixed this issue too.

**Comment by schiesbn** [comment]
There seems to be a misunderstanding. I'm talking about the **search**bar at the top, not the **side**bar.

Anyway, I just tried it on master and it seems to be fixed, maybe because of the new "New"-Button...

**Comment by PVince81** [comment]
@schiesbn ah yes, there was some weird workaround that told it to focus on the first field it found on the page. I removed that in the "New" new button. :wink:
