### ISSUE TITLE
Confusing error when trying to share unavailable external storage

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#18720]
### Steps to reproduce:
1. Create external storage
2. Access external storage that the filecache table is filled
3. Break the external storage, e.g. new SFTP ciphers that phpseclib doesn't support (yet) https://github.com/owncloud/core/issues/16133
4. You can still browse the folder due to the filecache, but on the personal page, the status is red
5. Try to share the folder

### Expected behaviour:
Error like "External storage is currently not available and can't be shared".

### Actual behaviour:
You are not allowed to share folder

The current message is quite confusing, I only got the real error because I found the error-message on the SFTP server (https://github.com/owncloud/core/issues/18717).
OC version: 8.0.6

**Comment by Xenopathic** [comment]
This is likely fixed with the new storage availability logic, which marks a storage as unavailable as soon as a request fails. It does require cooperation from the storage backend though, so few storage backends actually work like this. But when SFTP exceptions are properly handled, this will work.

The workflow will be something like this: external storage fails for some reason, you try accessing it in the web UI, it gets marked as unavailable and stops showing in the web UI immediately.
