### ISSUE TITLE
update fail

### ISSUE THREAD

**Issue by tuxrouge** [owncloud/core#18826]
Last update fail on my server (ubuntu-server)

Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM `oc_queuedtasks` WHERE `app`=?' with params ["search_lucene"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_queuedtasks' doesn't exist

**Comment by tuxrouge** [comment]
without Lucene it's working fine

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/search_lucene/issues/90, https://github.com/owncloud/core/issues/18327, https://github.com/owncloud/core/issues/18247, https://github.com/owncloud/core/issues/18712 and already fixed in the search_lucene app with https://github.com/owncloud/search_lucene/pull/101

Should be fixed with the upcoming oC 8.1.2 according to the backport in https://github.com/owncloud/search_lucene/pull/102
