### ISSUE TITLE
Reopening of unsolved issue:   When Owncloud update is available Owncloud instance should send an email to the admin #18696 

### ISSUE THREAD

**Issue by farson2003** [owncloud/core#18847]
Reopening of 

When Owncloud update is available Owncloud instance should send an email to the admin #18696 
https://github.com/owncloud/core/issues/18696

Reason: 

@aspdye @DeepDiver1975 Please reopen.

I was not suggesting a weekly statistic email (which might be another reasonable idea), but just a simple email notification for admins when an update for a running Owncloud instance becomes available. - Not every admin wants weekly emails.

**Comment by hitam4450** [comment]
I certainly agree and support the argument!

regards, hitam4450

**Comment by Xenopathic** [comment]
Does the Announcement mailing list not provide the features you require? Using the mailing list directly will also take the ownCloud instance out of the equation - imagine if there's a bug in the announcement code that is fixed in a later update? If the admin relies on the email to do an update they will never do so...

**Comment by DeepDiver1975** [comment]
Releases are announced on the ml. No need to add yet another feature to owmcloud.

**Comment by aspdye** [comment]
There are many other ways for staying up to Date:

-Twitter (@ownclouders)
-Facebook (ownClouders)
-RSS Feed of the Websites Blog (ownCloud.org)

and as @deepdiver1975 already said: the Mailing List 😉
