### ISSUE TITLE
customize port is not working as before

### ISSUE THREAD

**Issue by joyhope** [owncloud/core#18865]
I use https://xxx:yyy/owncloud.  It is working in previous version (8.0.2.0)

In the latest 8.1.1 it does not work again.  In the logout, it is always jump to 

https://xxx/owncloud

**Comment by karlitschek** [comment]
Can you please post a full bug report using the issue template? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
@LukasReschke Do you know what has changed here?

**Comment by LukasReschke** [comment]
Works fine here. Please use the issue template. THX.

**Comment by joyhope** [comment]
**Operating system**:
ubuntu 14.04

**Web server:**
nginx 1.4.6

**Database:**
mysql

**PHP version:**
php 5.5.9-1ubuntu4

**ownCloud version:** (see ownCloud admin page)
fresh install: 8.1.1

**List of activated apps:**
default

config.php
##
<?php
$CONFIG = array (
  'instanceid' => 'ocboa6or9gkc',
  'passwordsalt' => 'oWDerl3lIG7oLLEm+IfD7Safhb0s2a',
  'secret' => 'NNlsnpXX0AobWrttcmzN+GNSjTOgzAuLjnTCOmM68F23kQJ0',
  'trusted_domains' =>
  array (
    0 => '192.168.31.228',
    1 => 'yyy.zzz.xxx:28084',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'https://192.168.31.228/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud_admin',
  'dbpassword' => 'owncloud_admin_password',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local'=>'\OC\Memcache\APCu',
);

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/9.0/developer_manual/). :)

Thank you!
