### ISSUE TITLE
Catch CTRL+F and focus search input

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/core#18897]
For better UX we could react on CTRL+F and focus the search input if available.

@jancborchardt @PVince81 @MorrisJobke

**Comment by jancborchardt** [comment]
Yup, we should do that. Of course only when the current app exposes the search.

**Comment by Henni** [comment]
I think this leads to issues because the browser search feature solves a different problem than the owncloud search.
The owncloud search input is app wide while the browser search just applies for the current page.
For example a notes app could implement the search feature to search for notes including a specific phrase while Ctrl+F just searches the current note.

Maybe we could solve this differently.
Github for example introduces shortcuts like `s` to jump to the search.

**Comment by jancborchardt** [comment]
The Notes app is actually the only example as well where I could come up with a conflict. For things like Contacts, Calendar, Files etc – Ctrl+F jumping to the search box is fine.

**Comment by Henni** [comment]
@jancborchardt How do we solve it generically so that it fits for all apps?

**Comment by MorrisJobke** [comment]
> @jancborchardt How do we solve it generically so that it fits for all apps?

I would also don't overwrite the browser shortcuts.

**Comment by Henni** [comment]
I would propose `Ctrl+Shift+F`.
What do you guys think?

**Comment by jancborchardt** [comment]
Hm, the whole purpose of this is to supercharge a shortcut which for a web _app_ like ownCloud is useless otherwise.

For web _sites_ which predominantly are text (like Wikipedia, blog posts etc), the browser behavior of Ctrl+F is fine. But for ownCloud, generally Ctrl+F is useless.

I’d say we hijack the shortcut. And for the case of Notes, the search should work inside the current note (highlighting words) and also search in other notes.

**Comment by nickvergessen** [comment]
:-1: I disagree.

We have quite some pages that have a lot of text, e.g. personal/admin settings. Preventing the page search there sounds like an overkill to me.

If we do this at all, it should only be done on apps, that register a search backend.
And even then I think there should be a shortcut possible for the browser search?

**Comment by Henni** [comment]
@nickvergessen the shortcut is only registered for apps which registered a search backend.
But I see your point and am not completely happy with the current solution.

**Comment by jancborchardt** [comment]
@nickvergessen Personal and Admin do not have search, so this is a non-issue.

Actually we should have search there, see https://github.com/owncloud/core/issues/16875
And when there is search there, it should work exactly like Chrome settings search, making it way better than Ctrl+F itself.

**Comment by MorrisJobke** [comment]
Just today I again used Ctrl+F in my browser to search the file list, because the built in version in owncloud is very slow and the search result (for me images) didn't show the context and the gallery didn't worked there. Until this is fixed I'm against this, because it doesn't really allow to use the workaround approach.

**Comment by jancborchardt** [comment]
@MorrisJobke it’s called dogfooding …

**Comment by LukasReschke** [comment]
> @MorrisJobke it’s called dogfooding …

https://github.com/owncloud/core/pull/19212#issuecomment-142300153
