### ISSUE TITLE
Confusing behaviour when disabling encryption app via occ

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18932]
```
# occ app:disable encryption
encryption disabled

# occ encryption:status
  - enabled: true
  - defaultModule: OC_DEFAULT_MODULE
```

Looks like a bug to me, but maybe there is a reason for it?

@schiesbn

**Comment by PVince81** [comment]
As far as I understand, the "encryption" app is now only the default module.
It says "enabled: true" because encryption is enabled in core.
But then I'd expect it to say "defaultModule: none" since the app was disabled.

@schiesbn any clue ?

**Comment by schiesbn** [comment]
It is a bit confusing because we have the "core encryption feature" and the app "encryption" which is the default module. Sadly we didn't discover the naming issue initially and now it is not that easy to change it.

What you disabled was the encryption app, if you login and open the Apps-Menu you should see that the "Default encryption module" is now disabled.

"occ encryption:status" shows you the status of the core server-side-encryption-feature. This is still enabled and can't be disable. "OC_DEFAULT_MODULE" is still set because it is the last one the user has chosen. So everything is fine, expect that the naming is a bit confusing because both is called just "encryption".
