### ISSUE TITLE
Never show a empty sidebar

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#19120]
New ticket so that this doesn't get lost: https://github.com/owncloud/core/pull/18273#issuecomment-140036095

If the sidebar is open and the user click on a empty space below the files list the preview icon and file name is gone but the "versions" and "sharing" tabs are still there which looks quite strange. Either we should close the side bar in this case or keep the last selected file selected until you chose a different file.

cc @PVince81 @jancborchardt

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by schiesbn** [comment]
Maybe the best solution would be to always select a file. This means that if you click at the empty space we don't change the selected file at all. If you move into a sub-folder we automatically select the first file in the list.

**Comment by jancborchardt** [comment]
@schiesbn yep, I agree with your proposal. Both for clicking empty spaces and for navigating into empty subfolders.

**Comment by jancborchardt** [comment]
Similar issue:

1. in the open sidebar, click an image to view it big
2. close that slideshow view again
3. filelist refreshes and sidebar stays empty

**Comment by PVince81** [comment]
@jancborchardt it's probably a different issue. The file list should not refresh when closing the slideshow. If it does, maybe the slideshow is changing the URL which causes a "onhashchange" event and makes the file list think that the URL/path changes.

**Comment by PVince81** [comment]
I'll have to double check how the file list reacts on hash change, it shouldn't force-reload the content if the path is the same.

**Comment by oparoz** [comment]
@PVince81 - The file list is refreshed because Files still needs to support IE8 https://github.com/owncloud/core/issues/14828

**Comment by oparoz** [comment]
And I think it's a bad idea to keep the sidebar open when changing folder because it hides the scrollbar (https://github.com/owncloud/core/issues/18990) and the only way to get rid of it would be to click on the first file, which makes no sense.

Clicking anywhere outside the sidebar should hide it and reset the state of all selected files. That's the standard files manager model and ownCloud should not try to alienate its users :)

**Comment by oparoz** [comment]
An alternative idea for the sidebar if you don't want to hide it: show folder stats. That would work when changing folder as well and could be very useful.

**Comment by PVince81** [comment]
Folder stats would need to design and implement the specific GUI for it, might not have time for this.

And showing the current folder (the parent one) is not possible either because that information is not available and there is no API to retrieve this information directly. The only way would be to retrieve all files from the parent folder and filter that info. But in the future when we have Webdav and PROPFIND, it will be possible to get the info of a single file/folder :smile:

**Comment by PVince81** [comment]
I'm ok with auto-closing the sidebar when switching folders. @jancborchardt ?

**Comment by oparoz** [comment]
Maybe we don't have the same definition of folder stats. We could start by showing what's already shown in various locations in the UI.
* Folder name
* Number of files
* Folder size
* modified time

**Comment by oparoz** [comment]
Also maybe activities for the whole folder? @nickvergessen

**Comment by PVince81** [comment]
@oparoz currently not possible due to technical limitations, but something for another time: https://github.com/owncloud/activity/issues/396

**Comment by oparoz** [comment]
@PVince81 Thanks!

**Comment by jancborchardt** [comment]
Yeah, as I said, closing sidebar when switching folder is OK.

**Comment by jancborchardt** [comment]
@oparoz the correct issue @PVince81 was referring to is https://github.com/owncloud/activity/issues/380

**Comment by oparoz** [comment]
Thanks!

**Comment by MorrisJobke** [comment]
> I'm ok with auto-closing the sidebar when switching folders. @jancborchardt ?

Yep. I would also do this.

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/18238 which also mentions auto-closing the sidebar when switching folders.
