### ISSUE TITLE
System Wide Notify (e.g. admin to user messages)

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#19152]
Push System Notifications: As an admin, I want to be able to send out notifications of system wide messages from the ownCloud admin window, so that I can inform users of this information
Acceptance Criteria
-	Notifications are shown in the top of the web interface until user clicks ok button
-	If a response is required, (future versions) the buttons appear for a response
-	In the future, apps can be written to tabulate and track responses to notifications
-	Notifications should appear in the desktop and mobile clients as well, with the same accept (and in the future yes/no) functionality
-	an API is needed to send notifications to (and receive responses from)clients

Much of this should be in 8.2, but this may require a little polish to get it working (?).

**Comment by PVince81** [comment]
@nickvergessen @cmonteroluque

**Comment by MTRichards** [comment]
To clear up a few things:
- Changed title to reflect not a push, it isn't really a push, it is a pull.
- The acceptance criteria was modified to have notifications and responses both for 9.0.

Add to acceptance criteria:
- Every use has their own notification list - from one user to one user; apps implement this
- Admin notification can be done one to many, but is essentially flattened to one to one
- Need to migrate API to the OCS API in the app
- Need to add a sequence ID
- There is no expiration or state for notifications
- Can't do mobile or desktop until OCS API is needed
- Callback URLs are used for the client/mobile responses
- Tracking and tabulation or action based on the result of a notification must be done on an app by app basis (for example, accepting a share would use a callback URL that accepted the share, but that is handled in the sharing app)

**Comment by PVince81** [comment]
Okay, so this one is for system-wide messages, and I just found this other ticket https://github.com/owncloud/core/issues/16772 for user messages

**Comment by nickvergessen** [comment]
> - Notifications are shown in the top of the web interface until user clicks ok button
- If a response is required, (future versions) the buttons appear for a response
- Notifications should appear in the desktop and mobile clients as well, with the same accept (and in the future yes/no) functionality
- an API is needed to send notifications to (and receive responses from)clients
- Every use has their own notification list - from one user to one user; apps implement this
- Need to migrate API to the OCS API in the app
- It is an app, it can be disabled - if it is disabled, notifications don't work, but the system still functions
- Need to add a sequence ID to the API for getting a result => only required for syncing, different approach is implemented.
- There is no expiration or state for notifications

Done with notifications app

> - Admin notification can be done one to many, but is essentially flattened to one to one

There is an community app for this: https://github.com/nickv-oc/announcementcenter

> - In the future, apps can be written to tabulate and track responses to notifications
- Callback URLs are used for the client/mobile responses
- Tracking and tabulation or action based on the result of a notification must be done on an app by app basis (for example, accepting a share would use a callback URL that accepted the share, but that is handled in the sharing app)

This is the task of each app adding a notification.

Therefore I'd say this issue is "completed" and can be closed?
@MTRichards @DeepDiver1975 @PVince81

**Comment by PVince81** [comment]
We need a decision regarding the community app from @nickvergessen that fulfils the requirements @cmonteroluque @karlitschek @MTRichards.

**Comment by karlitschek** [comment]
So what exactly do we need to decide? :-)
It is super AWESOME that @nickvergessen did this app. And I think it does what we want.
Moving it into the owncloud github organisation would be nice but this is the decision of @nickvergessen of course.
So what exactly is the question? ;-)

**Comment by PVince81** [comment]
The question is whether we want to bundle this app (and then move it or fork it into the orga repo) or whether we tell people to go to the app store and install it themselves.

@MTRichards @karlitschek

**Comment by cmonteroluque** [comment]
@PVince81 @karlitschek @MTRichards @nickvergessen This is in the roadmap and the plan for 9.0. The decision to bundle it, I thought, was already done when we added it to the release (yes, we do), or I thought so!

**Comment by MTRichards** [comment]
Concur @cmonteroluque Bundle it.

**Comment by nickvergessen** [comment]
I'm fine with bundling the app from my repo

**Comment by karlitschek** [comment]
That's not so easy guys. EE vs. community. Also the strategic decission to not make our releases bigger but distribute apps via app store. We have to talk about this.

**Comment by MTRichards** [comment]
Perhaps we need to clarify what we mean by bundling. 

I was thinking we treat it like the anti-virus app, which is in the app store for CE, and in the package for EE.

**Comment by karlitschek** [comment]
Yes. We should do it like that. separate repo in the ownCloud organization. Releases as app on app store for server. Include it into the EE packages same as antivirus.

**Comment by cmonteroluque** [comment]
OK, that makes sense to me. I thought it would be included into at least the EE.

**Comment by PVince81** [comment]
From what I see the repo has been created here: https://github.com/owncloud/announcementcenter

The response part is a separate ticket https://github.com/owncloud/announcementcenter/issues/9 and as I understand was specified as "future", so something for 9.1 ?
This is likely non-trivial because it needs a DB table or such to keep track of user responses.

- [ ] make sure the app is bundled in CE/EE (?)

**Comment by MTRichards** [comment]
Responses are a future (so the 2-way communication is future) but the 1 way push of a message to desktop clients, that is intended for 9.0.

**Comment by PVince81** [comment]
@nickvergessen can you link the ticket about the OCS Notification API (if applicable), I can't seem to find it. Or is the API ready already ? (can't remember, sorry)

**Comment by nickvergessen** [comment]
Ita ready since early november

**Comment by nickvergessen** [comment]
And by that I mean, the server part. Desktop and mobile clients don't check the endpoint yet, from my understanding.

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/enterprise/issues/1090 for bundling
