### ISSUE TITLE
Research: Listening for external storage changes

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19166]
It looks like the SMB protocol might support notifying updates, see https://msdn.microsoft.com/en-us/library/JJ216044.aspx

Not sure if libsmbclient supports this ? @icewind1991 

@Xenopathic pointed out that we would need a daemon with a persistent connection to be able to receive these updates.

@DeepDiver1975 @butonic

**Comment by Xenopathic** [comment]
A daemon would be necessary for anything that detects external updates. E.g. epoll on Linux, this SMB Notify thing, any sort of push notifications etc. A critical thing is that the daemon must be optional, and ownCloud will continue to work to the best of its ability without it, just certain mechanisms like detecting external storage changes won't work.

Ideally the daemon will be written in PHP to use our codebase, but that might not be feasible...

**Comment by PVince81** [comment]
The exception is for services that would support pinging a remote URL. But from what I see that's not possible with SMB.

**Comment by Xenopathic** [comment]
@PVince81 even that isn't ideal. If ownCloud can detect that a change has happened since it last looked, it still has to rescan everything which is slow. A update detection daemon on the other hand acts similarly to the etag propagation, only updating the actual file/folder that was changed.

**Comment by icewind1991** [comment]
The notify seems promising but it looks like it requires us to have an open connecting to the samba server for every user, probably not to scalable

**Comment by Xenopathic** [comment]
@icewind1991 It would be no different to having each storage mounted via the system (mount.cifs), since that keeps a connection open per-storage. I suspect in our current implementation it's the repeated connection-disconnection that makes external storages less scalable, not having huge numbers of connections. In fact, if this daemon could proxy the requests to external storages, so one connection remains open for the user and never gets closed, that would improve performance even more.

**Comment by PVince81** [comment]
I also found this: inotify support in Samba 3 ? but possibly only for Linux server ?
http://superuser.com/questions/592546/watching-a-samba-share-for-modifications-from-linux
