### ISSUE TITLE
Sharing folder of encrypted repository

### ISSUE THREAD

**Issue by kaplandani** [owncloud/core#19200]
Hi, 
The site enables you creating a public share of an encrypted folder. 
basically - the share shows the file, but of-course no one can actually open them. 
usless - you should either issue a warning or not allow creation of shares of encrypted repositories.

**Comment by LukasReschke** [comment]
Can you please be a little bit more specific? What does not work for you?

**Comment by LukasReschke** [comment]
Also can you fill out the issue template? THX.

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/9.0/developer_manual/). :)

Thank you!
