### ISSUE TITLE
Stop disabling the theme on app updates!

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19271]
Every time you update an app, you lose the theme. That key needs to be protected when updating apps.
### Steps to reproduce
1. Install your theme
2. Update app
3. Look at your new login page
### Actual result

Theme is gone ;(
### Expected result

Login page looks just like you've designed it.

**Comment by PVince81** [comment]
Makes sense

**Comment by DeepDiver1975** [comment]
Well - we disable the theme because it can break the installation.

Which can also happen with an app upgrade because the theming capabilities allow to overwrite templates of an app.

This is a tricky beast.

**Comment by DeepDiver1975** [comment]
in addition this is related to upgrade which will be a major topic for 9.0 -> moving ...

**Comment by oparoz** [comment]
OK. I think the least the updater could do is to offer to turn on the theme at the end. If it breaks then, the admin can remove it from the config to fix things.

**Comment by deMattin** [comment]
The problem might be, that your theme breaks or simply only changes something, you don't see at first view.
My theme fixes some issues (or things, that only I see as an issue like linespacing in files app) and it is always a good idea, to go through all apps thoroughly with original theme first, to see, how it looks like now and THEN activate your personal theme.
Only this way you recognise, if your theming does only those things, you want to be done.

It's the more important to do it like this, the more and complex the theming is, you use.
If you only change some grafics or the simple login screen, it maybe(?) doesn't matter. But it's different, if you also (have to) theme "active" files like js files.

If upgrade won't reset theme, it would be harder to live this good practise some users even will do without knowing a reason for this - only because they check oc after upgrade and later after that activate their theme.

Best way to solve this would be, to only reset theming, if the update/upgrade changed something in the files you themed.
But for this it would be some coding neccessary and core work to be done. I think actually everything is deleted and newly uploaded during an upgrade independend of the fact, a file has changed or not.

So in my point of view, an upgrade should reset the theme, if only because it is to remind you, that you use one and have to check everything VERY well after update/upgrade.

**Comment by oparoz** [comment]
> Best way to solve this would be, to only reset theming, if the update/upgrade changed something in the files you themed.

I think this would be too hard to implement, but I don't know if we can theme specific apps directly from `core` if we can then the theme should definitely not be disabled if an un-themed app is updated.

> it is always a good idea, to go through all apps thoroughly with original theme first, to see, how it looks like now and THEN activate your personal theme.

Yes, but you can do this on the dev instance and then you should be able to update the production one without having to edit the config afterwards.

**Comment by jancborchardt** [comment]
So what’s the call on this @PVince81 @DeepDiver1975?

**Comment by PVince81** [comment]
@phisch likely obsolete.

What happens on update when a theme app is enabled ? I guess it stays enabled and is also able to style the update page ?

**Comment by phisch** [comment]
@PVince81 The theme app is not loaded during the update screen. Also it is disabled after an update, and must be enabled manually again. Should we improve this?

**Comment by PVince81** [comment]
Is it disabled as part of the "disable third party apps" logic I guess ?

In this case I'd leave this as part of https://github.com/owncloud/core/issues/14754#issuecomment-292254125 or other topics related to apps and updates.

**Comment by phisch** [comment]
@PVince81 AFAIK the theme should get disabled after an update, since themes can overwrite templates, and an update could provide new functionality which would be missing if the theme was still enabled.

I personally think that the theme should stay active. The owncloud admin should know what he has overwritten in a theme. Also overwriting templates should be rare for a theme.

**Comment by PVince81** [comment]
I'd expect new functionaly only on major versions, not minor.

That's why in that linked ticket I suggested to only disable apps on major updates.
