### ISSUE TITLE
[Activities] Editing a fed.shared file, the user name is not shown 

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19298]
### Steps to reproduce
1. Federate share a file
2. Edit the file in server B
3. Go to activities tab in server A

### Expected behaviour
The username that had edited the file should be shown in the activities tab

### Actual behaviour
The username is not shown, instead of it it is shown 'remote-user'

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

![remoteuser](https://cloud.githubusercontent.com/assets/10596560/10043911/d70f3860-61f6-11e5-85fc-fa4c07c543a6.png)

**Comment by PVince81** [comment]
I believe this is a classic known issue, isn't it @nickvergessen ?

**Comment by nickvergessen** [comment]
Yes, in the hook the user is only known as `''` (empty string).
So the activity app has currently no chance to identify the user.

I'd really like to see this fixed one day, but it will be a quite huge story:
we need to identify remote user's via the token, but even then if two users mount the same public link manually, they can not be distinguished.
But for intentional federated sharing, it should be possible.

So mostlikely not even 9.0

@cmonteroluque please reschedule (out of 8.2.1)

**Comment by nickvergessen** [comment]
PS, finally found it: https://github.com/owncloud/core/issues/13739

**Comment by cmonteroluque** [comment]
@nickvergessen ok
