### ISSUE TITLE
Sharing sidebar does not show "Shared with you by ..." for remote shares

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#19376]
1. Login as userA
2. Share a folder `foo` remotely from to userB
3. Login as userB
4. Accept the share
5. Open the sharing sidebar for `foo`

You would expect to see the same message as for local shares above the input field. So "share with you by userA@..." but instead there is no text.

CC: @PVince81 @blizzz

**Comment by PVince81** [comment]
@rullzer did it work in 8.1 ? Did the share dropdown show it ?

**Comment by rullzer** [comment]
@PVince81 no it doesn't... I was under the impression it did... but nope... so no regression...

**Comment by rullzer** [comment]
Once we move more of the federated sharing handling over to the federate share provider. And move over the v2 of the OCS Share API we could get this info nicely via one endpoint to the user. CC: @schiesbn 

@PVince81 @cmonteroluque something for 9.1 maybe

**Comment by cmonteroluque** [comment]
since it's a but, let's see how good we feel for 9.0.1, for now

**Comment by PVince81** [comment]
In some scenarios, a remote share was accepted but somehow it cannot be scanned for whatever reason (firewall, broken server, etc). In these situations where the initial scan could not happen, the mount point cannot appear in the web UI because there is no matching filecache entry and also no metadata about whether it's a folder, file (mime type), etc.

These kind of shares are impossible to remove without going to the database. So I think these should still be displayed under "Shared with you" to allow the user to delete them. If no metadata is available, use a generic or "broken" icon instead to signify a broken remote share. (which might or might not repair itself if the remote server would become available again)

**Comment by cdamken** [comment]
@PVince81 @carlaschroder Is there any way to document this?, for troubleshooting information?

**Comment by carlaschroder** [comment]
@cdamken I'll cobble up something.

**Comment by PVince81** [comment]
We won't have time for this, I'd like to move this to 10.1.

**Comment by PVince81** [comment]
Works in 9.1.4, I think someone added this recently.
