### ISSUE TITLE
CSP for images for legacy apps doesn't match the one in AppFramework

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19425]
https://github.com/owncloud/core/blob/d1f0ff372e8c05ced760d4e21060e8d8db9c1963/lib/private/response.php#L250

```
'img-src *; '
```

https://github.com/owncloud/core/blob/d1f0ff372e8c05ced760d4e21060e8d8db9c1963/lib/private/response.php#L250

```
private $allowedImageDomains = [
	'\'self\'',
	'data:',
];
```

@LukasReschke

**Comment by oparoz** [comment]
Fix is in https://github.com/owncloud/core/pull/19426

**Comment by LukasReschke** [comment]
I don't think this is a bug. See https://github.com/owncloud/core/pull/19426#issuecomment-143875214

The policy is as such employed since 2013. If apps do not comply with that I consider this more a bug within the app.

That said, that there is a difference is indeed wanted as the default policy for the App Framework is more strict. `*` will allow loading content from all other domains.

**Comment by LukasReschke** [comment]
That said adjust https://github.com/owncloud/core/pull/19426/files#r40606049 and this is fine for me.

**Comment by oparoz** [comment]
>  If apps do not comply with that I consider this more a bug within the app

I thought you meant apps like Firefox, but if you mean ownCloud app, they can't override what Files is setting afaik.

**Comment by LukasReschke** [comment]
> I thought you meant apps like Firefox, but if you mean ownCloud apps, they can't override what Files is setting afaik.

Ah. Injecting JS in files. Evil @oparoz.

Well then :seat: :speak_no_evil: :see_no_evil: :+1:

**Comment by oparoz** [comment]
Well, it's the only way to have a slideshow :P and if I want to sanitize SVGs, I need to base64 encode them afterwards and need the data scheme :)
