### ISSUE TITLE
Federation autocompletion NG

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#19566]
# federation - autocompletion NG

A user wants to share with people on remote servers. In the sharing dialog, and maybe other places in the future, users of remote server should be offered to autocomplete.
So it is necessary to query other servers for available users. Only specific server should be queried for privacy reasons. This servers are called trusted server and can be configured on the admin page.

Work packages:
- list of trusted servers on admin page (autocomplete servers)
- add and remove buttons
- query this servers in the sharing dialog.
- Extend the current user OCS API to accept federation sharing token for authentication.
- privacy settings:
	- checkbox [ ] automatically add servers with active shares to list of trusted servers.
	- select box. allow user queries from remote servers: (none, trusted servers, all)

# Addressbook sync between servers

ToDos:
- [x] Create system addressbook which holds all system users - https://github.com/owncloud/core/pull/20719
      - [x] migration step required to get initial load - https://github.com/owncloud/core/pull/20719
      - [x] use hooks to add newly created users and delete
      - [ ] add hook triggers to shibboleth
- [x] Find a CardDAV php client which supports sync - sabre client?
- [x] Create a synced addressbook for each trusted server
     - [x] add cron job to sync
     - [x] make use of webdav sync collection 
- [x] Add system addressbook to OCP\contacts manager - https://github.com/owncloud/core/pull/20696

**Comment by karlitschek** [comment]
@schiesbn @cmonteroluque @MTRichards FYI

**Comment by DeepDiver1975** [comment]
@karlitschek so we can close https://github.com/owncloud/core/issues/17888 ???

**Comment by schiesbn** [comment]
Sounds good. But maybe instead of "query this servers in the sharing dialog" it would be better if the trusted servers exchange there list of users in the background so that we don't have to query multiple servers for auto-complete but have a local list of users and servers.

**Comment by oparoz** [comment]
> Sounds good. But maybe instead of "query this servers in the sharing dialog" it would be better if the trusted servers exchange there list of users in the background so that we don't have to query multiple servers for auto-complete but have a local list of users and servers.

Yes, caching + etag check.

**Comment by karlitschek** [comment]
@DeepDiver1975 yes.

**Comment by karlitschek** [comment]
@schiesbn hmm. yes. not sure if it's worth the additional work. but yes!

**Comment by cmonteroluque** [comment]
@karlitschek thanks!

**Comment by jancborchardt** [comment]
Profile pictures and full names should also be exposed. Maybe even ability to search by email address, even if that’s just in the background, and could be restricted by privacy settings. But that way we could have a function to automatically query everyone from your Contacts – like most other proprietary apps do as well.

**Comment by schiesbn** [comment]
@jancborchardt I agree. We can decide at the end which data the ownCloud server should exchange. But I agree that at least the cloud id, display name (= full name) should be exchanged. Other stuff like avatar could make sense too. But in case of avatars we need to make sure that we don't fill up the disk space with thousands of avatars from remote servers. Afaik, @rullzer already implemented a API which fetch them on demand, that's probably enough.

**Comment by rullzer** [comment]
@schiesbn remote avatars will be part of 9.0 most likely. Fetching them on demand probably makes the most sense.

**Comment by DeepDiver1975** [comment]
Idea: leverage 9.0 caldav/carddav interface to sync these contacts :question:

**Comment by schiesbn** [comment]
> Idea: leverage 9.0 caldav/carddav interface to sync these contacts

This sounds promising. I almost finish the first part: Manage the list of trusted ownCloud. I just need to add some unit tests.

I'm still not 100% sure how to exchange the data.

Not sure if it can be a getUsers() request from one ownCloud to the other one. This could probably take to long if the ownCloud needs to assemble the list on-demand and send it back as response.

Probably it is better if the ownCloud assembles the list of users and then pushes it to the other server. Can this still be done via webdav?

Other option: We assemble the list of all users in the background and store it somewhere. Maybe as a "system address book in the new carddav backend" of course we would need to keep this up-to-date? Then we could return it easily on a getUsers() request.

Btw: does we also get notified if a new user appears/disappears on a LDAP server or if something like display name changes? -> @blizzz? Because we need a way to keep the trusted ownClouds up-to-date.

Maybe we can discuss this in more detail in Stuttgart all together...

**Comment by jancborchardt** [comment]
> We assemble the list of all users in the background and store it somewhere. Maybe as a "system address book" in the new carddav backend?

Yeah, I noted this in the past (long long time ago) that we should treat the Users and Contacts on the same level, similar to how Google Apps does it.

**Comment by karlitschek** [comment]
Yes. This should leverage the 9 contacts store.
Don't we have an API to pull users from other servers already? I remember something.

**Comment by blizzz** [comment]
> Btw: does we also get notified if a new user appears/disappears on a LDAP server or if something like display name changes? -> @blizzz? Because we need a way to keep the trusted ownClouds up-to-date.

Appearing users → yes, because a new mapping entry will be created. I just need to notify or emit something. 

Disappearing users → yes, with the cleanup (if enabled, yes by default) we will find LDAP users that are not available on LDAP anymore. However, this is not a delete operation, this would be a manual step. In this delete case postDelete should be emitted already. Is this sufficient?

Changing displaynames → we don't look for changes, but keep the display name stored in user preferences (was also introduced with the clean up feature). We can add detection here and emit a thing as well.

**Comment by DeepDiver1975** [comment]
> Other option: We assemble the list of all users in the background and store it somewhere. Maybe as a "system address book" in the new carddav backend? of course we would need to keep this up-to-date! Then we could return it easily on a getUsers() request.

How is authentication/authorisation working on the remote server?

We cannot allow enumeration of user information unauthenticated-

@LukasReschke idea?

**Comment by DeepDiver1975** [comment]
Once the authentication is clearified we can do the following:
- add a system addressbook which exposes the instance users.
- maybe even the pure principals resource can be enough???
- additional information like email, displayname and avatar are part of the addressbook/principal data
- regarding performance of user listing - this is once more my cry for a central user accounts table
(I will now finally come up with a PR for this ....)

**Comment by schiesbn** [comment]
> How is authentication/authorisation working on the remote server?

Userlist exchange happens if both server trust each other. If I send a user list to DeepDiverCloud over https nobody should be able to intercept it and you will accept the users because you told your system that you trust my ownCloud... ok the sender address could be faked, right? So someone could send you the wrong users, but this would be useless.

**Comment by schiesbn** [comment]
@blizzz thanks for your answers, I think this should work

**Comment by LukasReschke** [comment]
> Userlist exchange happens if both server trust each other. If I send a user list to DeepDiverCloud over https nobody should be able to intercept it and you will accept the users because you told your system that you trust my ownCloud... ok the sender address could be faked, right? So someone could send you the wrong users, but this would be useless.

What defines trust? How is this boundary ensured? How does server A know that server B is really Server B and not somebody else claiming to server B? 

We need to some kind of shared secret here. Some secure way here would be [JSON Web Tokens](http://jwt.io/introduction/), which is what I'd recommend. :)

**Comment by schiesbn** [comment]
> What defines trust?

The admin. If we know each others ownCloud servers we can say that we trust each other and allow our ownClouds to exchange the users.

> How does server A know that server B is really Server B and not somebody else claiming to server B? 

If I can create a valid https connection to server B I can be reasonable sure that I'm talking to the right server, right?

> We need to some kind of shared secret here. Some secure way here would be JSON Web Tokens

How do you make sure that you receive the correct token? How can I check the signature if the signature is valid?

Let's discuss this next week in Stuttgart.

**Comment by LukasReschke** [comment]
> If I can create a valid https connection to server B I can be reasonable sure that I'm talking to the right server, right?

Yes. Absolutely A can be sure that he connected to B. But how can B be sure that it REALLY is A that requested the information? You need some kind of shared secret for that.

**Comment by schiesbn** [comment]
A doesn't ask for information, A sends you information (the user list). At the moment I tend to implement it as a "push" and not a "fetch" operation. This allows us to assemble the list of users in the background, no matter how long it takes and push it over to the other server once we are done. That's why I said above " ok the sender address could be faked, right? So someone could send you the wrong users, but this would be useless." But of course it would be good if we could prevent this too.

**Comment by LukasReschke** [comment]
>  So someone could send you the wrong users, but this would be useless." But of course it would be good if we could prevent this too.

Let's please go with JWT or some other kind of authentication instead of some random push stuff which is kinda fragile and can be spammed with ton of information. 

Especially when we want to update users etc.  Simple three-way handshake here would make this so much more tamper proof.

**Comment by schiesbn** [comment]
> Let's please go with JWT or some other kind of authentication instead of some random push stuff which is kinda fragile and can be spammed with ton of information. 

No objections. Let's discuss the details next week. :smile:

**Comment by PVince81** [comment]
@DeepDiver1975 as discussed, this is done ?
Can you verify and tick the checkboxes in the first post ?

- QA ticket: https://github.com/owncloud/QA/issues/22
- documentation @carlaschroder 

CC @jospoortvliet

**Comment by schiesbn** [comment]
Everything should be done from my point if view. But can't answer the question regarding shibboleth...  @DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
Shibboleth is still open - I need to get a dev system up and running ...

**Comment by PVince81** [comment]
Doc ticket ref: https://github.com/owncloud/documentation/issues/2107

**Comment by DeepDiver1975** [comment]
> Shibboleth is still open - I need to get a dev system up and running ...

here we go .... https://github.com/owncloud/user_shibboleth/pull/121

**Comment by MorrisJobke** [comment]
> here we go .... owncloud/user_shibboleth#121

So this is then the last open item. @DeepDiver1975 I guess this now can be closed.
