### ISSUE TITLE
Let the user specify public link share token names

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19562]
Just like you can replace the random shortcode with a custom one in URL shortening services, it should be possible to pick an easy to remember URI when sharing a link.

`index.php/s/yourproject`

@rullzer

**Comment by LukasReschke** [comment]
Not too happy about this as it can easily be abused into some social engineering alike approaches. That's the reason why Google or Dropbox doesn't offer this too ;-)

**Comment by rullzer** [comment]
Well not even that. People will most likely use it so on an instance it is not unlikely to get `index.php/s/photos` which people other people then know exists since they can't create that link anymnore.

So I'm also not very fond of the idea.

**Comment by oparoz** [comment]
>  That's the reason why Google or Dropbox doesn't offer this too ;-)

Are you sure it's not because they want to sell those custom IDs at a premium rate? ;)

> People will most likely use it so on an instance it is not unlikely to get index.php/s/photos which people other people then know exists since they can't create that link anymnore.

True... The system is shared, so there is only one possible `/photos` folder which makes it unfair on a large instance, but some home users might appreciate to be able to share their memories via memorable links.

@jospoortvliet ?

**Comment by manngo** [comment]
Is this what they call “security through obscurity”?

I disagree with the logic here. Surely it is up to the administrator to make a decision about security, such as requiring passwords on shared folders.

I can’t see why a simplified version such as `owncloud.example.com/user/shared-folder` should be out of the question. This would also get around the issue of multiple users wanting to use the same share name.

**Comment by jospoortvliet** [comment]
I don't think anybody would assume that his private shared link named "myserver.com/owncloud/photos" is as private and secret as "myserver.com/owncloud/aD34!fSd3" and we could even point this out in the UI for making this shared link, recommending setting a password.

Seems a valid request to me, thus. Of course, I can't judge if it is possible and how hard it is - but that's a technical decision and up to whoever wants to work on this.

**Comment by julpec** [comment]
For me it's a missing feature of OC or at least an app the administrator could activate.

For example, I work in a high school and I would be glad if the teachers could easily give a short memorable URL like `https://public.domain.org/my-link` (with a pen on a whiteboard !!)

I add some code in last version of OC in order to make it working with an external shortening service like yourls. After clicking in the public sharing checkbox, users can create a keyword for the external shortening service called by API. Behind this, the native public URL of OC still exist and is still displayed but users have, in addition, the possibility to create external short links.
I'm not a developper, so I'm not aware of the security problems but it's the only solution I've found and the code is very different in OC8 and my DIY is not working anymore :(
I would really like to see this type of app in OC !

So, for me, it seems a valid request too.

**Comment by ronnystandtke** [comment]
I just run into the same issue. I have to share a link for a course and would like to present the participants a simple link URL. I run my own owncloud instance so the chance of namespace fights with other users is zero.
Now the participants (unknown in advance, so no chance of mailing the link) have to start the day with reading and typing in 15 random letters and numbers...

**Comment by manngo** [comment]
I have added a question at:

[https://central.owncloud.org/t/customised-share-tokens/13309](https://central.owncloud.org/t/customised-share-tokens/13309)

The technique is to make changes to the `oc_share` table as follows:

	update oc_share set token='…' where id=…;

My question was whether this is a stable thing to do, but, so far I have had no replies.
