### ISSUE TITLE
File download fails in Firefox earlier than 38 and Android Client 1.7 and 1.8 (bad file size)

### ISSUE THREAD

**Issue by ElAutoestopista** [owncloud/core#19667]
### Steps to reproduce

1.Install Owncloud 8.1.3
2.Enable Encryption
3.Upload a bunch of files
4.Try to download with Firefox earlier than 38 and Android client from 1.7 and 1.8

### Expected behaviour

File successfully downloaded

### Actual behaviour

In Firefox, after several seconds the download is marked as failed and the file not saved
Android client says "Download Failed" at 74% (everytime is 74%).
Using Firefox prior to version 39 (actually 38), or Internet Explorer 9, results on valid download of a correct file.

### Question

I've seen this: https://support.mozilla.org/es/questions/1073548.
It seems that versions of Firefox 39 and early complain about the download file size if it's not the same as the server informed, ant treats it as corrupted.
I've seen that the file size in web interface is different of one of the downloaded file. 
It's possible that the file size informed is the encrypted one instead of the unencrypted files (which are in fact downloaded)?

### Server configuration

**Operating system:** openSUSE 13.2 x86_64

**Web server:** Apache 2.4.10

**Database:** MySQL 5.6.26

**PHP version:** 5.6.1

**ownCloud version:** 8.1.3

**Updated from an older ownCloud or fresh install:** Fresh install

### List of activated apps:

**Enabled:**
* activity: 2.0.2
* contacts: 0.4.0.0
* calendar: 0.7.3
* files: 1.1.9
* encryption: 1.0.0
* files_pdfviewer: 0.7
* files_sharing: 0.6.2
* files_texteditor: 0.4
* files_trashbin: 0.6.3
* files_versions: 1.0.6
* files_videoviewer: 0.1.3
* firstrunwizard: 1.1
* gallery: 0.6.0
* templateeditor: 0.1
* updater: 0.6

**Disabled:**

* external
* files_external
* files_locking
* provisioning_api
* user_external
* user_webdavauth
* user_ldap

### Are you using external storage:
No

### Are you using encryption:
yes

**Comment by MorrisJobke** [comment]
> Android client says "Download Failed" at 74% (everytime is 74%).

@schiesbn This sounds like wrong filesize (encrypted one) is provided to the client.

**Comment by xn--nding-jua** [comment]
Hi, the problem is well known. Here is my raised issue: https://github.com/owncloud/core/issues/17594. PVince81 and schiesbn have fixed the origin of the problem already.

Here I've proposed a repair-script for damaged DB-entries. Maybe you can use this script to repair your database, too: https://github.com/owncloud/core/issues/18225

The reason for the 74%: the database should contain the UNencrypted filesize but due to a bug sometimes the encrypted filesize (which is around 25% larger) is stored within oc_filecache. So the client/firefox is trying to download 1,25MB but the decrypted file is only 1MB. So the download will fail.

**Comment by MorrisJobke** [comment]
So the cause is fixed and the remaining wrong DB entries are covered by #18225

**Comment by ElAutoestopista** [comment]
Hi all,
@xn--nding-jua, your script did the trick in my tests. Now file sizes are correct and Android client works ok.
Thank you all very much!!
