### ISSUE TITLE
[8.2] Side-menu doesn't support multi-select

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#19693]
### Steps to reproduce
1. Select multiple files/folders in file view
   2.
   3.
   ![ow-br](https://cloud.githubusercontent.com/assets/8111200/10417589/8001dfe2-7041-11e5-85ef-51629172ee2c.png)
### Expected behaviour

Shows details of the selection in the sidebar, e.g. number of files, total size, ...
Enable sharing for all selected objects
### Actual behaviour

Only shows the properties of the last selected object.
### Server configuration

**ownCloud version:** ownCloud 8.2 RC1 (daily) Build:2015-10-11T03:37:52+00:00 188acd5e4e4bf9e35e327ecf8389c75ead744732

**Comment by MorrisJobke** [comment]
cc @blizzz @PVince81

**Comment by PVince81** [comment]
This is by design for now, for 8.2.

@owncloud/designers any ideas to make it better in 9.0 ?

**Comment by jancborchardt** [comment]
@PVince81 unless we support sharing multiple folders/files at once, or showing the consolidated activity of multiple items, I would not show the sidebar at all as soon as multiselect is entered.

Also, see the multiselect bar overlap bug again?

**Comment by PVince81** [comment]
@jancborchardt the overlap issue will be fixed in RC2. @tflidd is still on RC1.

We don't support bulk sharing and also cannot easily retrieve and combine the share info from multiple files.

Auto-closing the sidebar will once again cause annoying UI flickering: select one file, sidebar opens. Select a second file, sidebar closes. Deselect second file: sidebar opens again.

It used to behave that way before we made the last changes for #18238 and it was annoying.

**Comment by jancborchardt** [comment]
> Deselect second file: sidebar opens again.

This should probably not happen then. At least if you switch out of multiselect to single-select, the sidebar should not magically appear again.

**Comment by PVince81** [comment]
The weird behavior should be fixed in the upcoming 8.2.3 and 9.0 RC1.

Let's keep this ticket as feature request for bulk selection + sidebar.

**Comment by sxdxfan** [comment]
Hello! Is there any progress on the multi-select sidebar actions? We need to tag multiple files at once really bad
