### ISSUE TITLE
More precise timestamps on previous versions

### ISSUE THREAD

**Issue by blanik** [owncloud/core#19716]
Server version 8.1.1.

Web interface 

When I request previous versions of a file I am shown a list which says
12 hours
1 day
1 day
2 days
3 days
1 week
1 week
1 week

But it is difficult to know the exactly which version to restore without trial and error ( especially the multiple 1 week ones ).

If would be more useful to show the exact timestamp date and time of each previous version, rather then the fairly course relative time - with multiple files having the same value.

**Comment by karlitschek** [comment]
True. @schiesbn @jancborchardt

**Comment by jancborchardt** [comment]
When there are multiple similar dates, we could add the time, and the exact date, like this:
* 12 hours ago
* 1 day ago, 16:20
* 1 day ago, 9:23
* 2 days ago
* 3 days ago
* 1 week ago, Saturday
* 1 week ago, Friday
* 1 week ago, Wednesday

@blanik because I assume the time of day will help you to decide which version to take, or what exactly is it? Do you need a preview, what file type is it? You also do know that you can hover the date for the exact timestamp, cc @schiesbn

**Comment by blanik** [comment]
Yes - esp for 1 week old day of week would help me to decide which version
of the file would be the best to restore, based on what changes I think
might have happened on various days that I want to undo.

Hovering over gives me exactly what I need - I didn't know that!
But I still think it would be more useful to show the timestamp - "1 jan
201610:01" in the first place.

**Comment by PVince81** [comment]
In the sidebar of 8.2.2, you can hover on the entries to get the exact timestamp.

It might not be as convenient though, you'd need to hover over many entries until you find the right one.
Keeping this open for now to improve timestamps ?

**Comment by jancborchardt** [comment]
Yeah, with 8.2 and the ability to hover and see the exact timestamp this should be fixed.
