### ISSUE TITLE
[8.2 regression] LDAP: Having memberOf enabled breaks nested groups

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19816]
See https://github.com/owncloud/core/issues/17759#issuecomment-148320869

@MorrisJobke @davitol @cmonteroluque 

so this is broken again in 8.2

**Comment by PVince81** [comment]
@blizzz

**Comment by PVince81** [comment]
@davitol bisected it, see result here https://github.com/owncloud/core/issues/17759#issuecomment-148334763

**Comment by PVince81** [comment]
All the three commits were introduced by this PR: https://github.com/owncloud/core/pull/18469
Unfortunately I don't think we'll be able to revert it as it fixes a blue ticket.

**Comment by PVince81** [comment]
@GreenArchon would you be able to help with this as you fixed the issue back then in 8.1 ?
Unfortunately @blizzz is sick this week. :frowning: 

This is the PR that breaks it https://github.com/owncloud/core/pull/18469, it seems to have touched something with "memberOf" (I don't understand much of LDAP)

Thanks

**Comment by GreenArchon** [comment]
I'll try to check it out.

**Comment by GreenArchon** [comment]
Yup, it's 845485cfe637c3a7fdb72a110cb68c769b2f8d4b

Basically, it's this check that is wrong: 
<pre>if(!$user instanceof User) {
	return array();
}</pre>
Since when we're recursing (ie. looking for memberOf in groups the user's memberOf), $user is actually a group, but on purpose.

Since the _getGroupDNsFromMemberOf() is only called from the getUserGroups($uid) function, I'm guessing the check is superfluous anyways and I'll post a PR that just removes it, but checking if we're recursing or not to decide wether to do that test or not would also be a possibility (I'd like @blizzz 's opinion on that when he'll be back).

**Comment by cmonteroluque** [comment]
he may not be back on time for 8.2, I'd go for the less harmful fix now and check again with @blizz after 8.2 ships

**Comment by GreenArchon** [comment]
Finally after re-looking at the code I think it might be better to just revert the whole commit: using
_$user = $this->access->userManager->get($DN)_ to get a group's info is a recipe for another regression when userManager changes to return an error if the DN isn't a user's...

PR is here #19818 (even if it's just a revert)

**Comment by PVince81** [comment]
(@cmonteroluque blizzz with three "z"'s, I edited your comment accordingly :wink:)
