### ISSUE TITLE
Right sidebar takes whole viewport on small screens

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#19915]
Where did that change come from @owncloud/designers @PVince81 @MorrisJobke? Do we really want to do hat? It looks really quite strange on tablets especially.

**Comment by PVince81** [comment]
Looks like it was added by Arthur in 5af59c68712032ef387ccd4410eb4b8b04c27df9.
I thought it was you since you're usually the one fiddling with mobile.css.

Also I seem to remember that it was said that the sidebar should be shown full screen on mobile, but I might be mistaken. What behavior did you originally intend for mobile ?

**Comment by PVince81** [comment]
here https://github.com/owncloud/core/commit/5af59c68712032ef387ccd4410eb4b8b04c27df9#diff-20c51c7c5f7dd8f4af89e49c10626726R111 (CC @blizzz)

**Comment by PVince81** [comment]
This is not a regression as there was no sidebar pre 8.2.

**Comment by MorrisJobke** [comment]
> Do we really want to do hat? It looks really quite strange on tablets especially.

Definitely better than the tiny right side bar if it is not full screen. It maybe needs some tweaking.

**Comment by PVince81** [comment]
What's the decision on this ? When should the sidebar be fullscreen if at all ?

**Comment by jancborchardt** [comment]
It should never be fullscreen as it is a strange change of focus. Should be 90% width so that the file list still shows on the left, as feedback of where one is. Self-assigning.

**Comment by PVince81** [comment]
Ah yes, 90%. That's almost fullscreen, but makes sense :smile:
