### ISSUE TITLE
Large images in share pages could do with lightbox/zoom

### ISSUE THREAD

**Issue by Azelphur** [owncloud/core#19986]
ownCloud shares kinda suck for large images, this results in issues like #8180 where users want direct links. As you can see from that issue we can't have direct links because of security issues.

However, looking at how other services handle this, they seem to use some lightboxy-type thing with zoom controls.

To demonstrate this issue, here's how ownCloud handles a screenshot of my desktop (11520x2160)

![2015-10-22-194311_1919x1079_scrot](https://cloud.githubusercontent.com/assets/280694/10674892/43336e16-78f5-11e5-813f-5b6a04b1e948.png)

It's not good, because the image is scaled down so much that you can't really see anything, and the only option you have is to download the file and open it outside ownCloud

Dropbox handles it similarly
![2015-10-22-194359_1909x1084_scrot](https://cloud.githubusercontent.com/assets/280694/10674922/5ceade20-78f5-11e5-919d-f96edac5e39c.png)

However when you click on the image, you get this lightbox-type thing with zoom support.

![2015-10-22-194808_3840x2160_scrot](https://cloud.githubusercontent.com/assets/280694/10675063/147ab470-78f6-11e5-980c-b75eb638360b.png)

Which can make the image shares a lot more useful. I'd love to see something similar in ownCloud so that we can share large photos/images without having to download them.

For reference, here is the dropbox link for the large image, https://www.dropbox.com/s/m833psn61o61y8w/u2kZN3H.jpg.png?dl=0
and the ownCloud link, for the same large image. https://owncloud.azelphur.com/index.php/s/g77eqDqgoEiRSrj

**Comment by LukasReschke** [comment]
@jancborchardt FYI

**Comment by LukasReschke** [comment]
@oparoz FYI as well :)

**Comment by oparoz** [comment]
I think it's a good idea to have a lightbox. I don't think we can re-use the slideshow from Gallery, because fileActions are not available in those preview pages if I'm not mistaken @PVince81? So the only solution seems to write something in the Files app.

@Azelphur if you need to share direct image links, you can use https://apps.owncloud.com/content/show.php/ShareLinks?content=170527
It's not available on 8.2 yet though.

**Comment by jancborchardt** [comment]
@Azelphur good point!

@oparoz @owncloud/designers as a first pass we can show the lightbox on click of the image, right?

**Comment by oparoz** [comment]
There is now a PR by @MonsterKiller: #23606. Looking at the way this works, this could also be used in Gallery in order to get the same kind of rendering. Gallery might move to something with more features in the future, but that should work quite well in the mean time. I like the PiP and zooming works on more platforms.
