### ISSUE TITLE
WebInterface - Shared link page text of link too small

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/core#20050]
In teh webinterface of an shared link the display of the Link is too small:

http://i.imgur.com/416krNx.png

The field thoud have a much bigger size. Should be possible to have teh filed longer depending on teh available size

**Comment by kavishdahekar** [comment]
Hello all, GSoC 2016 paticipant here.

Since the share links are always of the form : `https://domain/owncloud/index.php/s/UNIQUE_HASH/download`
can we assume that the link will never be arbitrarily very long?

In that case simply increasing the width of ".directLink input" to 500px in "public.css" should suffice?

Please advise.

**Comment by Kawohl** [comment]
I think looks good. Please mak a pull request.
