### ISSUE TITLE
Submit button on password-protected link page should be disabled until something is put in

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#20177]
Because I assume there can not be empty passwords anyway? @DeepDiver1975 @PVince81 @MorrisJobke

**Comment by gmurayama** [comment]
I can work on this since it is quite simpleand only require some javascript, but I don't quite understand how the javascript files are loaded. I already identify the template used to authenticate the password to the user be able to download the file, but I don't think use javascript there would be correct.

I intend to create a separated file to load and block the button if there's nothing in password's field.

**Comment by jancborchardt** [comment]
@PVince81 @MorrisJobke can you help @gmurayama here?

**Comment by PVince81** [comment]
@gmurayama the template is here: https://github.com/owncloud/core/blob/v8.2.1/apps/files_sharing/templates/authenticate.php

There is currently no JS file for this page, please create one in "files_sharing/js/authenticate.js" then add `script('files_sharing', 'authenticate');` at the top of the template file.

**Comment by prastut** [comment]
I went through all of the PR's and this bug seems to be fixed?

**Comment by MorrisJobke** [comment]
> I went through all of the PR's and this bug seems to be fixed? If it's not, it would be wonderful if anybody from the community could tell me how to go about this issue. :D

The button itself is clickable when nothing is typed in. Best way would be to disable the button when the password field is empty and then enable it once it is filled.
