### ISSUE TITLE
File Comments Web Client Representation

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#20267]
Contributes to #16328 

* [ ] will be part of Timeline tab (https://github.com/owncloud/core/issues/20259)
* [x] flat list first, but hierarchy will be kept to be able to change this
* [x] plain text only (in the future, nudging users via @-notation should be possible with this)
* [x] after loading, unread comments should be marked as read
* [x] not shown on public page

@nickvergessen @blizzz @DeepDiver1975 @jancborchardt

**Comment by nickvergessen** [comment]
> flat list first, but hierarchy will be kept to be able to change this

had a short discussion in the office here. This will be a nightmare on sorting. Get the last 3 comments, what happens when the parent does not exist in this set of 3 items, how do we display them? What happens when the number of parents is 1000 (all nested), etc....

Just skip it for now.

> not shown on public page

Also applies to federated shares then?

**Comment by blizzz** [comment]
>> not shown on public page

> Also applies to federated shares then?

Federated shares are not public per se. If we can get it working without much trouble I think it is worth to show them in this case as well. Other opinions?

**Comment by nickvergessen** [comment]
Well we have a different set of user's.
I see `@mentions` flying to randomly and wrong users and also the current user is empty and unidentifyable: https://github.com/owncloud/core/issues/13739

**Comment by jancborchardt** [comment]
Federated shares are comparable more to internal shares than public shares I’d say. For federated shares I’d definitely expect the comments to show.

Not necessarily something for the first step of course – but from a product design standpoint I’m always wary of introducing features which don’t work everywhere as expected (on mobile as well for example). Since we advertise federated sharing, and will advertise comments as well, comments should work for federated shares.

**Comment by PVince81** [comment]
@blizzz have a look at system tags implementation to see how to define Webdav-compatible backbone collections: https://github.com/owncloud/core/blob/6cb95f4e42028f0959d4139593a16decbbc4b053/core/js/systemtags/systemtagscollection.js#L27

The dav properties mapping is done inside the model: https://github.com/owncloud/core/blob/6cb95f4e42028f0959d4139593a16decbbc4b053/core/js/systemtags/systemtagmodel.js#L29 (if you want it, it's more convenient)

Also: need to figure out how to make it easier to do a Webdav REPORT call from JS. (I'll have a look at this)

**Comment by PVince81** [comment]
Comments have been implemented.
