### ISSUE TITLE
Support for dynamic LDAP groups

### ISSUE THREAD

**Issue by alexweirig** [owncloud/core#20405]
Hello,

we're using dynamic LDAP groups, i.e. rather than manually adding users to a given group, we specify an LDAP filter (memberURL) to retrieve the users belonging to this group.

E.g. of a group definition:
# ens-ressort-1, groups, accounts, technolink.lu
dn: cn=ens-ressort-1,cn=groups,cn=accounts,dc=technolink,dc=lu
memberURL: ldap:///cn=users,cn=accounts,dc=technolink,dc=lu??one?(o=Ressort-1)
cn: ens-ressort-1
objectClass: apple-group
objectClass: ipaobject
objectClass: extensibleObject
objectClass: ipausergroup
objectClass: posixgroup
objectClass: kolabgroupofuniquenames
objectClass: groupofnames
objectClass: nestedgroup
objectClass: groupofurls
objectClass: top
mail: ens-ressort-1@technolink.lu
ipaUniqueID: d6cd7f5a-77b9-11e5-8d65-0050568b72e4
gidNumber: 1503200038

We are able to see the list of our groups in owncloud but when we try to share a file with the group, the users that based on the filter should belong to this group can't see the shared file.

Are there any plans to support this kind of LDAP groups in owncloud.

As a workaround, I tried to define a group in owncloud and set a user as group admin. Unfortunately as a group admin this user doesn't see the other LDAP users in his Users view, so he can't add new users to the "his" group. Is this the expected behaviour?

Many thanks in advance

Alex

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
There are currently no plans to add support for this. However, we'd take contributions ;)

> As a workaround, I tried to define a group in owncloud and set a user as group admin. Unfortunately as a group admin this user doesn't see the other LDAP users in his Users view, so he can't add new users to the "his" group. Is this the expected behaviour?

Yes, group admins cannot add **existing** users to their groups, only create new ones, see https://doc.owncloud.org/server/8.2/admin_manual/configuration_user/user_configuration.html#granting-administrator-privileges-to-a-user

**Comment by alexweirig** [comment]
Hi, 

sure I'd like to contribute this feature to owncloud but my knowledge of php ends with the popular hello world. So I'd have to hire somebody to implement this feature.

Is there a documentation available about the APIs and internal processes required to implement this feature. I see the following needs:
1) When you click on such a dynamic group in the groups list, we must query the LDAP with the group's filter, retrieve the list of the users and display this list. So there must be an API to add users to the list displayed on screen
2) When we share a file/folder with such a dynamic group, we must retrieve the users again from LDAP and then share with these users as if they were in a static group (same APIs I suppose).

We'd have to decide what happens in the following scenario:

at moment T we have user A, B and C in group G.
we share a file with this group, thus users A, B and C can access the file
at moment T+1 we move user C from the group

Will user C still be able to access the file that was shared when she was member of the group and now no longer is?

I see if and where I can find a PHP developer and get this implemented. I keep you updated.

Regards,

Alex

**Comment by blizzz** [comment]
> 1) When you click on such a dynamic group in the groups list, we must query the LDAP with the group's filter, retrieve the list of the users and display this list. So there must be an API to add users to the list displayed on screen

User and Group backends implement an interface and are being requested on demand. That's the same for local users as well as LDAP or any other you could implement.

User Interface: https://github.com/owncloud/core/blob/master/lib/public/userinterface.php
Group Interface: https://github.com/owncloud/core/blob/master/lib/public/groupinterface.php

Regarding group memberships there are the methods usersInGroup() and getUserGroups(). The implementations in the LDAP Backend: https://github.com/owncloud/core/blob/master/apps/user_ldap/group_ldap.php#L513 and https://github.com/owncloud/core/blob/master/apps/user_ldap/group_ldap.php#L391

Instead of adding a new group backend, enhancing the exisiting LDAP group backend is favorable.

> When we share a file/folder with such a dynamic group, we must retrieve the users again from LDAP and then share with these users as if they were in a static group (same APIs I suppose).

You would constantly need to which these dynamic groups and emit events that report addition or removal of users to this group (e.g. as in https://github.com/owncloud/core/blob/master/lib/private/group/group.php#L145). 

Easier, more reliable and I suppose just as possible is to treat the dynamic group just like any other and share directly to this group. Memberships will be determined on demand and you don't run into the issue of permanently watching the memberships.

> at moment T we have user A, B and C in group G.
we share a file with this group, thus users A, B and C can access the file
at moment T+1 we move user C from the group
>
> Will user C still be able to access the file that was shared when she was member of the group and now no longer is?

With normal group shares this is possible. Mind, that in LDAP we use a cache to avoid too frequent requests to the server, so a small delay may happen. This is configurable however.

**Comment by alexweirig** [comment]
Thanks for all these information and links.

**Comment by alexweirig** [comment]
Hi blizz,

just wanted to let you know that we have started working on the implementation. We've hired a PHP developer and he started yesterday.

Is there a procedure we have to follow to contribute the code back to owncloud once we've got it working?

Cheers,

Alex

**Comment by blizzz** [comment]
> Is there a procedure we have to follow to contribute the code back to owncloud once we've got it working?

For getting a patch into ownCloud a Pull Request should be done here in Github against master. Actually, this can happen already while work is in progress, for instance to collect feedback or ask question, or just have some eyes on the code if anything is unclear.

When the pull request is considered ready, we (as in ownCloud community) will review and test the patch. It's required to have at least two OKs (in form of :+1:), one of them from feature maintainer (which is me). Also, unit tests need to pass, obviously, but they will fire automatically (at least when within the ownCloud organisation here, if not I'll take care of it).

If all is good, one of the gatekeepers will press the merge button.

One important requirement legal-wise: either the [Contributor Agreement](https://owncloud.org/contribute/agreement/) needs to be signed, or you declare the patch to be MIT licensed.

We also have [Coding Style Guidelines](https://doc.owncloud.org/server/8.2/developer_manual/general/codingguidelines.html) that should be followed when writing the code.

**Comment by blizzz** [comment]
fyi @MTRichards @cmonteroluque

**Comment by alexweirig** [comment]
Hi,

regarding the group admin and the restriction to only allow him to 
create new users and not allow him to access existing users, is this a 
restriction you want to stick to or would you consider allowing group 
admins to add existing users to a group?

Personally I think that it would be a useful feature. Let me explain our 
situation:

We are managing a school network with some 60 school building and some 
800 teachers. The teachers within the schools want to share files with 
colleagues based on different conditions (team teaching, same class 
level, etc etc). All our teachers a referenced in our LDAP.

As the owncloud admin, I don't want to manage all these "local group" 
and spend my time adding and removing people from these groups based on 
some school internal reorganization. Therefore my idea to just create 
the empty group and let the group admin add the users he wants to this 
group. If he now has to create new users for each teacher in that group, 
the these teachers will end up with a whole bunch of logins to access 
the different files ... but that doesn't make sense in our setup.

Maybe we could introduce an option that specifies whether the group 
admin has access to the global users or not and then based on this 
option either show the users or not show them...

Again, we'd be contributing this.

Schéin Gréiss, Mit freundlichen Grüßen, Meilleures salutations, Kind 
regards,

Alex Weirig
Responsable Technique

Ville de Luxembourg - Centre Technolink 2, rue Charles de Tornaco L - 
2623 LUXEMBOURG alex.weirig@technolink.lu 
<mailto:alex.weirig@technolink.lu> Tel: +352 4796 - 6127 Fax: +352 42 88 
81 www.technolink.lu <http://www.technolink.lu>

**Comment by cmonteroluque** [comment]
I think it's a good suggestion. @MTRichards let's talk about whether to add this to the 9.0 timeline as a community contribution

**Comment by MTRichards** [comment]
>regarding the group admin and the restriction to only allow him to create new users and not allow him to access existing users, is this a restriction you want to stick to or would you consider allowing group admins to add existing users to a group?

This is something I would like to address. The Group Admin in general is very limited in scope today, by design. The use case was very narrow at the time, and we would like group admins to be able to add users from the system to their group, and then remove them from their group - without deleting them from the system (or, deleting the user from the system if appropriate).

Now that we are beyond the basic narrow use case, we have additional requirements such as these that are interesting and need to be addressed. This could be considered for 9.1.

**Comment by alexweirig** [comment]
Hello,

thanks for the feedback on the group admin feature. Looking forward to see what your plans are.

---

The code to support dynamic LDAP groups is ready and deployed on our production system.

We'll commit the code to github on Wednesday. We've implemented the LDAP logic and also updated the LDAP configuration wizard to enable (disabled by default) this feature and to provide the LDAP attribute used to express the filters for the dynamic groups. Our code will be contributed as MIT licensed.

While adding the code we noticed some "strange" behaviour when retrieving LDAP users and we've documented this scenario. I'll open a different ticket for this problem.

Regards,

Alex

**Comment by alexweirig** [comment]
Hello,

I've create a pull request for the code changes made. I hope this request matches your requirements.

Regards,

Alex

**Comment by blizzz** [comment]
@alexweirig thank you for the PR, I am going to review it today or tomorrow.

> I'll open a different ticket for this problem.

When you opened it, could you post the link?

**Comment by alexweirig** [comment]
@blizzz : I've created the ticket with #21223

**Comment by blizzz** [comment]
thanks!

**Comment by alexweirig** [comment]
@blizzz did you have a chance to look at the latest code we submitted in the PR in order to support the dynamic groups?

**Comment by blizzz** [comment]
@alexweirig No, not yet, unfortunately, mostly because I have been on vacation. But I am going to take care of it today or tomorrow.

**Comment by alexweirig** [comment]
@blizzz 
Hi, the PHP developer is coming today to fix the issues you identified on our last pull request.
Should we still work on that PR or should we rebase our code on a newer branch or even master?
I would like to make sure we get the contribution right this time and that we can close this project with the developer.
Many thanks for your help and patience

**Comment by blizzz** [comment]
Sorry for the late reply, I was sick since Wed. It's too late I guess, but for the record the answers: The pull request should be on a branch based on master. You can just continue to work on the branch you have and rebase to master. This would require to use the force flag with the push. 

In general, we use to work with  the same pull request and just update it during the process as needed. At some point the different commits are squashed into one before merging.

**Comment by blizzz** [comment]
implemented with https://github.com/owncloud/core/pull/22025
