### ISSUE TITLE
Fatal webdav error

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/core#20423]
Everyday i get several fatal errors in the log like this one:
`Exception: {"Message":"HTTP\/1.1 400 expected filesize 1110016 got 1081344","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/directory.php(113): OC\\Connector\\Sabre\\File->put(Resource id #28)\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('foldersync_auto...', Resource id #28)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('autobackup\/fold...', Resource id #28, NULL)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#9 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":144}`

Apparently this is trigerred when my foldersync app try to sync files with owncloud using webdav protocol. The files appears to be correctly synchronized, so i post here because i dont know what this fatal error really means.

Debian Jessie
Owncloud 8.1.4-12.1
php 5.6.14+dfsg-0+deb8u1
apache 2.4.10-10+deb8u3

**Comment by MorrisJobke** [comment]
@icewind1991 @PVince81 You said, that this can be ignored :see_no_evil:

**Comment by PVince81** [comment]
This can happen if something got wrong on the network during the chunk transfer (unstable network, slow network+timeout, etc). The sync client will resume the transfer after such error and properly finish uploading the file.

You can ignore this issue.

I wonder if we should move the log level of these to debug ?

**Comment by jsalatiel** [comment]
As a final user i think it would be nice move to debug since it is not really FATAL for the server itself, just for the connection.

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/blob/283798a2204bd19319d9ad07f9ff2e3d301a9f4a/apps/dav/lib/connector/sabre/file.php#L139 this is where the issues is thrown, but how to not log this that verbose.

**Comment by robin24** [comment]
I'm getting this issue ever since I upgraded to Owncloud 8.2.1 (stable). Nothing has changed with the installation except for the upgrade and I can safely say that the issue has started to appear directly after upgrading. Prior to this upgrade, I've never noticed this issue. The exact error I am getting looks as follows:
Exception: {"Message":"HTTP\/1.1 400 expected filesize 5242880 got 0","Exception":"Sabre\\DAV\\Exception\\BadRequest","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php(101): OC\\Connector\\Sabre\\File->createFileChunked(Resource id #35)\n#1 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/directory.php(115): OC\\Connector\\Sabre\\File->put(Resource id #35)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile(’Synch Testfile.mp3’, Resource id #35)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('Private\/Clibs\/S...', Resource id #35, NULL)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#7 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#9 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#10 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":361}
The difference is that after this error, the file synch is actually aborted, tested under Mac OS using ownCloud-2.1.0.2890beta1 as well as ownCloud-2.0.2.2818. In addition to the QT client I also tried synching with the owncloudcmd command line client, which would give the same error and then refrain from synching that file. This was tested using my home DSL connection as well as using the internet access of my university, same result with both connections (both of which are very stable).
Server OS: Debian 8.2
Web server: Apache
Server version: Apache/2.4.10 (Debian)

**Comment by kapcom01** [comment]
Just adding my experience.
Today, owncloud client started downloading and uploading of already synced old files on a shared folder. I looked at the Log and saw many similar errors. Everything seems to work fine now.

**Comment by PVince81** [comment]
This https://github.com/owncloud/core/issues/24653#issuecomment-220017778 should help make such errors disappear.

**Comment by PVince81** [comment]
the message has also been improved in recent versions and should tell more about the problem
