### ISSUE TITLE
Sharing API: Sharing reports

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#20492]
As an admin, I would like to be able to report on the sharing activity of users on the ownCloud system so that I can oversee and control files properly

Acceptance Criteria:
- API can be queried by authenticated admin and return share information so that a report can be built either inside ownCloud by an app, or externally by a 
- API can report on sharing by:
  - user (show me all shares for this user in order of "shared" volume, by type (share link, internal share)
  - file/folder (show me how many people are sharing this file/folder)
  - most shared folder/file (show me files that are shared in order of most shared)
  - type of share (show me share link shares in order of share link volume, then mod time)
- All responses provide file name, owner, file path in owner directory, share type, share info requests (like volume of shares)

Eventually it would be good to also be able to stop a share that looks vulnerable from the report, but this is for the app that implements such a report, not the API

**Comment by rullzer** [comment]
What do you mean by volume? The amount of data in the share? Since the shareAPI does not care about that kind of stuff.

But queries like "give me all shares for user X" or "give me all share of type Y" and "give me all shares for the file with id Z" will all be part of the stuff that we can ask the sharemanager. 

But generally speaking I don't think this stuff should be part of core. If we want reporting on shares we should write an app. That app can then use the sharemanager to get share info and maybe enrich this data by itself by quering the filesystem for info etc. 

This would allow for a clear separation of concerns. The sharemanager does what it should (since correctly sharing is already complex enough). And an app can then do all the complex reporting and calculating it want on that data.

**Comment by PVince81** [comment]
Feature didn't make it into 9.1 but also wasn't really on the plan, moving to 9.2 for now to reconsider.

@dragotin @DeepDiver1975

**Comment by PVince81** [comment]
@pmaier1 move to backlog ? Not on the plan AFAIK.

This is not a trivial feature, needs new APIs, UI, etc.

**Comment by pmaier1** [comment]
Yes, backlog for now.
