### ISSUE TITLE
Exception: Please upload the ca-bundle.crt file into the 'config' directory.

### ISSUE THREAD

**Issue by acritely** [owncloud/core#20548]
Encountered whilst upgrading from 8.1.4 to 8.2 using Updater app.

**Comment by RealRancor** [comment]
Hi,

how did you upgrade from 8.1.4 to 8.2.0 via updater app? This version is not available via the updater app.

**Comment by acritely** [comment]
Apologies, I was upgrading from 8.1.3 to 8.1.4. I saw the Updater notification and ran the update script. Now my oc is displaying the upgrade screen at login and is down. I would prefer to cancel the update and do a clean install of a higher version later. If you have any advice, I would appreciate it. Otherwise I'll find it. Thanks

**Comment by RealRancor** [comment]
@acritely Mhhh, strange. Normally that shouldn't happen between 8.1.3 to 8.1.4, only from 8.0.x to 8.1.x: https://github.com/owncloud/updater/issues/164

Maybe you missed the file in the past. You can get that file from:

https://raw.githubusercontent.com/owncloud/core/v8.1.4/config/ca-bundle.crt

and place it as described in the message into your config dir.

**Comment by acritely** [comment]
Here is the log from when I tried to update:
[17-Nov-2015 03:32:54 UTC] PHP Fatal error:  Call to undefined function OCA\Updater\Location\first() in /home/mydomain/public_html/owncloud/apps/updater/lib/location/apps.php on line 44
[17-Nov-2015 03:32:54 UTC] PHP Fatal error:  Cannot redeclare class OC\Security\SecureRandom in /home/mydomain/public_html/owncloud/lib/private/security/securerandom.php on line 38

**Comment by acritely** [comment]
@RealRancor I added the missing ca-bundle.crt file and the update page reports the following:
"Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database"

The owncloud homepage stayed at the maintenance mode page for more than 3 hrs. I checked the error_log file and found this new error:

PHP Fatal error:  Class 'OC_FileProxy' not found in /home/mydomain/public_html/owncloud/apps/files_sharing/appinfo/app.php on line 28

I think this might be my fault for not turning off all the apps before trying the update. I was only running the calendar app, however. Any thoughts?

**Comment by tessus** [comment]
@RealRancor actually, I just saw in the admin page of my oc 8.1.4 the following:

<img width="287" alt="screen shot 2015-11-19 at 22 59 49" src="https://cloud.githubusercontent.com/assets/223439/11291697/49df4c6c-8f11-11e5-9778-a6bbf667df5a.png">

This tells me that the updater app obviously allows me to update from 8.1.4 to 8.2.1.
Does this really mean that I could just click `Update` and be done with it?

**Comment by acritely** [comment]
I think the issue was cause by me not turning off some apps before trying to update. I have reinstalled my oc instance. I'm closing the issue.

**Comment by RealRancor** [comment]
@tessus Please ask such questions within the forums or the users mailinglist as this is unrelated to this issue.

**Comment by tessus** [comment]
@RealRancor sure, it's just that the question was rather secondary.

As you mentioned in https://github.com/owncloud/core/issues/20548#issuecomment-157285741, the update should not be possible. My screenshot is evidence to the contrary. Therefore I wanted a clarification of your statement (with reference to the correct behavior).

There are several options:
* updater app cannot update from minor to major version (but I don't think so, because the docs do not say so)
* update from 8.1.4 to 8.2.0 is not possible, but update from 8.1.4 to 8.2.1 is possible. in this case: why?
* you made a mistake
* my oc 8.1.4 only shows the update button, but when clicking it, the system won't actually be updated

In any case, I spotted an inconsistenciy which usually raises a red flag (for me). You know the code and I don't, so I hoped that you could clarify this situation. Since I didn't want to write all the stuff I just wrote, I asked one question that pretty much narrows down the above list. :-)

**Comment by RealRancor** [comment]
@tessus Such questions just doesn't belongs in here, especially as those are not related to this issue here.

**Comment by tessus** [comment]
@RealRancor I don't understand. you made a statement in https://github.com/owncloud/core/issues/20548#issuecomment-157285741 , which was false. how can asking about it be wrong?

**Comment by RealRancor** [comment]
It was not wrong at that time because 8.2.1was not available three days ago... Shouldn't be hard to understand that...

**Comment by tessus** [comment]
but 8.2.0 was. and you mentioned 8.2.0.

**Comment by RealRancor** [comment]
Which was also not availablevia updater app at that time. But honestly, this discussion makesno sense. Have a nice evening and use the forum or mailinglist if you need discussions about this.
