### ISSUE TITLE
"Fix scrollbars in public template" shows white box below PDF

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#20557]
There is now this white box shown:

![2015-11-17_13-27-24](https://cloud.githubusercontent.com/assets/878997/11211348/01c86316-8d2f-11e5-9789-7beafc40c7d4.png)
![2015-11-17_13-28-00](https://cloud.githubusercontent.com/assets/878997/11211350/0a6611c6-8d2f-11e5-8cb8-39376de8904d.png)

This is caused by the change in public.css at https://github.com/owncloud/core/commit/c1a5e9643589233e0e4e131f1b2808c40370cec9. Merged with https://github.com/owncloud/core/pull/19611

@Henni Ideas? THX

**Comment by oparoz** [comment]
Who's responsible for the PDF app? It can probably be fixed there

**Comment by LukasReschke** [comment]
> Who's responsible for the PDF app? 

That would likely be me.

> It can probably be fixed there

That would require that I'd have a deeper understanding about our CSS and CSS in general :speak_no_evil:

**Comment by oparoz** [comment]
> That would require that I'd have a deeper understanding about our CSS and CSS in general

Yeah, I have the same problem and thus the reason I let @henni make the changes in core...

**Comment by Henni** [comment]
I'll take a look.

**Comment by PVince81** [comment]
@Henni getting close to release, any chance to get this in by the end of next week ?

**Comment by Henni** [comment]
@PVince81 should be possible. I know what the problem is, I just have to figure out the best way to fix it.

**Comment by PVince81** [comment]
@Henni any update ? Or should I take over ? Mind sharing your thought process if you had any useful insights ?

**Comment by Henni** [comment]
current thoughts:
* There is a table hack to solve variable footer height as we have it here. But this may break other stuff, because `#content-wrapper` is used in a lot of templates. (We could only apply this hack on public pages but this may still lead to problems with apps)
https://stackoverflow.com/questions/9126777/keep-footer-with-variable-height-on-bottom
* A solution with flexbox would be simple and pretty but only supported by IE11 onwards.
* The last alternative I've come up with is just fixing this for the `files_pdfviewer` app, by overwriting the css value in the app stylesheet.

I believe 'fixing' this via javascript isn't a real solution, as it would be *very* ugly.

@PVince81 @owncloud/designers what do you think?

**Comment by jancborchardt** [comment]
> just fixing this for the files_pdfviewer app, by overwriting the css value in the app stylesheet.

@Henni even though very specific, it fixes a very specific problem with little probable side effects.
