### ISSUE TITLE
User list unresponsible

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#20644]
> :-1:  Pretty slow for me, mainly with default system avatars which takes ages to load. Takes over a minute, with LDAP running on the same machine.
>
![before2](https://cloud.githubusercontent.com/assets/2184312/10791740/fe3fd4f4-7d89-11e5-80d4-3a7a2cc6bf1b.png)

From https://github.com/owncloud/core/pull/20108#issuecomment-151866829

cc @butonic @blizzz

**Comment by MorrisJobke** [comment]
Afterwards this should be backported together with #20108

**Comment by PVince81** [comment]
@rullzer any idea how to accelerate avatars ?

**Comment by rullzer** [comment]
Mmmm, so the rendering needs to happy anyway. No real way around that.

But! The first time is can be slow. Since we then resize avatars etc. So requests after that *should* be faster.

Also, I think the current HTTP headers are such that not all browsers cache avatars.

Last, we could make it so that the placeholder is no longer based on a hash of the displayname (which we do now) but just on the username. We know that already (since we use it in the request). That way we can always show something. Which feels better I think

**Comment by rullzer** [comment]
>Last, we could make it so that the placeholder is no longer based on a hash of the displayname (which we do now) but just on the username. We know that already (since we use it in the request). That way we can always show something. Which feels better I think

This is actually already happening in the user list

**Comment by rullzer** [comment]
So currently we do not cache any avatars at all..Which is well. subobtimal. But we can't cache them on the current endpoint. Since that is also used by your private avatar.

This will then break updating your avatar.

A solution around this might be to have a different endpoint for personal avatars. That is uncached. And all the other avatars are cached by default for 15 minutes or so?

**Comment by rullzer** [comment]
Also I'm observing very weir behaviour in the user page. I hope somebody can verify?

1. Create a new OC instance (I tested on master)
2. Create a new user (user1)
3. Login as that user and set the avatar
4. Login as admin
5. Go to the user page and observer network traffic

I see 2 requests to the `avatar/user1/32` location. Which does not make any sense.

Can anybody verify?

**Comment by rullzer** [comment]
Aaah yes as expected late last night (and now verified) it is because of the way we do fetching of the image... we first fetch the image in the ajax call. Which then tells us there is an image. Now after that we set the `<img src='<AVATARLINL>'>` which will go fetch the image again because we do not do any caching.

**Comment by rullzer** [comment]
First improvement which should reduce the load significantly when a lot of users have avatars in #20943

**Comment by rullzer** [comment]
In #20954 we make sure to only load the avatar if it is available.

I can't think of any more things to do to increase the avatar performance on the user page at the moment.
