### ISSUE TITLE
Files are deleted from the server suddenly

### ISSUE THREAD

**Issue by Biopticon** [owncloud/core#20668]
This happened for me the second time. For no apparent reason, all of a sudden, I realized that all the files are being deleted on the client (while watching the activity window).  Why?  I had to stop client immediately to avoid a disaster. The server (v8.1) is running on a Raspberry-2, the client (latest) on a Win 7 computer. This is a very scary behavior and it happened twice for me. I can provide the relevant log files to diagnose the problem. I stopped using OwnCloud until the matter is resolved. When resolved I will upgrade to 8.02. 

Any help will be greatly appreciated.

**Comment by karlitschek** [comment]
I'm very sorry to hear about your problem. We at ownCloud take the security of the dat very seriously.
At the moment we are not aware of a bug like the one you described. It is always strongly recommended to upgrade to the latest version of course because many bugs are fixed. And unfortunately it is not possible to reproduce with the limited information you provided. So please got to owncloud.org/support and maybe the forum. I hope someone can help you to solve this problem.
