### ISSUE TITLE
File/Folder shared via link cannot be accepted using Safari as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20681]
### Steps to reproduce

1.Create a file/folder using Firefox
2. Share via llink this file/folder with another user
3. Paste the link in Safari browser
4. Write down your server address in 'Add to your owncloud' textbox
5. Log in your server in order to accept the file/folder shared

### Expected behaviour

The file/folder should appear in user2 account

### Actual behaviour

There is any advice about the file/folder shared

Note: It works fine in Mozilla/Chrome. 
It fails in Safari 8.0.8 and also in the Safari for iOS8

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 8.2.1 (stable)

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari

**Comment by rullzer** [comment]
Mmmm so only safari? @LukasReschke @MorrisJobke could one of you have a look?

**Comment by MorrisJobke** [comment]
I tested this with Safari 9.0.1 and current master and stable8.2. Both versions work just fine. Can you provide a broken instance?

**Comment by davitol** [comment]
As I said I tested with Safari 8.0.8. If I have the chance i'll try again with Safari 9 version.

**Comment by davitol** [comment]
I tested this with Safari 9.0.1 with stable 8.1.4 and it didn't work for me :(

**Comment by MorrisJobke** [comment]
> I tested this again with Safari 9.0.1 with stable 8.1.4 and it didn't work for me :(

Anything in the webdev console?

**Comment by PVince81** [comment]
@tomneedham which Safari version do you have ? Can you have a look ?

@davitol any JS error ?

**Comment by tomneedham** [comment]
So I seem to get asked for credentials when just loading the share link using safari, I don't even get the chance to login @davitol is this the issue you were having?

<img width="613" alt="screen shot 2015-12-09 at 16 19 44" src="https://cloud.githubusercontent.com/assets/660805/11690950/d7177814-9e90-11e5-9018-f9b5f201ef61.png">

Chrome / Firefox shows the file list, and works when entering in the server address and accepting the share.

**Comment by PVince81** [comment]
@tomneedham did you test on 8.2.1 ?

**Comment by tomneedham** [comment]
> @tomneedham did you test on 8.2.1 ?

Nope, sorry! Just did, and cannot reproduce. Everything worked as planned.

**Comment by PVince81** [comment]
The 9.0 one is suspicious though, could be due to the switch to webdav (make sure to have submodules properly updated). If you still see it, separate ticket ?

**Comment by PVince81** [comment]
I sent a patch for @davitol to test. The patch adds logging statements in files_sharing/js/external.js.
Strangely his Safari version did not log anything.

So maybe there is another unrelated piece of JS code that is run earlier and that has errors and prevents further code execution, which explains why the dialog does not appear at all.

Debugging this will be a PITA, maybe even worse than IE8...
Maybe adding `console.log('...')` statements in all javascript files and then compare the log from chrome with the one from safari to see which files weren't executed properly.

**Comment by PVince81** [comment]
@davitol please retest the patch but make sure to have `'debug' => true` in config.php. I realized that even `console.error()` is blocked in non-debug mode.

**Comment by PVince81** [comment]
patch here: https://github.com/owncloud/core/compare/stable8.2...stable8.2-debug-externaljs.patch

**Comment by davitol** [comment]
[Warning] Invalid CSS property declaration at: ; (styles.css, line 17)
[Warning] Deprecation warning: tipsy is deprecated. Use tooltip instead. (js.js, line 1984)
[Error] BEFORE AJAX
	processSharesToConfirm (external.js, line 124)
	attach (external.js, line 75)
	attach (js.js, line 720)
	initialize (app.js, line 83)
	(anonymous function) (app.js, line 228)
	(anonymous function) (underscore.js, line 768)
[Error] AFTER AJAX, go shares 
	(anonymous function) (external.js, line 128)
	c (jquery.min.js, line 4)
	fireWith (jquery.min.js, line 4)
	k (jquery.min.js, line 6)
	r (jquery.min.js, line 6)
[Log] scanning files for pepe (files.js, line 347)
[Log] done after 0 files (files.js, line 341)

**Comment by PVince81** [comment]
Ok, so it does load the shares but for some reason doesn't log anything? There should be an array of shares. Ok, maybe Safari is too lazy. I'll change the patch to make it more verbose.

**Comment by PVince81** [comment]
@davitol can you try with the updated patch ? https://github.com/owncloud/core/compare/stable8.2...stable8.2-debug-externaljs.patch

**Comment by SergioBertolinSG** [comment]
Not working with https://github.com/owncloud/core/issues/20681#issuecomment-163936186 patch either.

**Comment by SergioBertolinSG** [comment]
Logs:
![screen shot 2015-12-14 at 16 16 39](https://cloud.githubusercontent.com/assets/9048796/11784725/3efc16ec-a27e-11e5-95a6-6a19fc3a70d7.png)

**Comment by PVince81** [comment]
Thanks. When using "add to ownCloud" it uses a hash in the URL: "#".
But for some reason it seems Safari doesn't parse it.

@SergioBertolinSG can you try again with the latest patch ? (just pull that branch)

**Comment by SergioBertolinSG** [comment]
New logs
![screen shot 2015-12-14 at 16 33 36](https://cloud.githubusercontent.com/assets/9048796/11785146/8f322492-a280-11e5-9801-bd20f83f9cbc.png)

**Comment by PVince81** [comment]
Okay... so the URL hash is empty, that's not good.

On IRC @SergioBertolinSG told me that after entering the URL in "Add to ownCloud" the user had to login. @SergioBertolinSG @davitol can you try again with a user who is already logged in?
Also, when the login prompt appears, what URL is displayed ? Does it contain a "#" part ?

I suspect that the redirect might be discarding the hash.

**Comment by PVince81** [comment]
@SergioBertolinSG @davitol do you observe the same problem with IE8 and IE9 when the login redirect happens ? I have the feeling that all these browsers are discarding the hash part in the login redirect, so we lose information...

**Comment by PVince81** [comment]
Hah... I knew it... Same problem with IE9.
The important part is that the user must NOT be logged in to trigger the login redirection.

**Comment by PVince81** [comment]
One possible solution for this would be to change the way how we pass the arguments.
For example we could serialize them to JSON and then cram them into a single real URL parameter "incomingshare=$theCrammedData" instead of using a hash at all.

But then we got the following problem: how to discard it from the URL after processing to make sure a page reload won't retrigger it ? In proper browsers it is possible to rewrite the URL by using `window.history.replace(...)`. BUT it turns out that IE8/IE9 don't support this API either... so they need a URL hash as workaround... back to square one :frowning: 

Or instead of going to the files app's URL, go to another PHP URL, for example "index.php/files_sharing/ajax/incomingshare" and then have that one automatically add the share into the remote shares queue (like it is done for shares created over the share dialog). Then that one redirects to the files app.

So, proposed workflow:

1. "Add to ownCloud" builds the URL "$targetUrl/index.php/files_sharing/ajax/incomingshares"
1. The incoming shares controller adds the incoming share to the list of pending shares in the database (if valid), then redirects to the files app
1. Files app, through external.js, will check if there are pending shares and show the appropriate dialog.

The advantage of this is that we can discard all the JS code related to processing the hash, and also have a clean URL when coming back.

What do you think @rullzer @schiesbn ?

This is nothing for a bugfix release though, more an enhancement.

**Comment by PVince81** [comment]
@davitol @SergioBertolinSG can you test if it works when the receiving user is already logged in ? If it does it will confirm my theory. And for that there is no possible quickfix in the scope of a maintenance release.

**Comment by SergioBertolinSG** [comment]
@PVince81 Yes, you were right, being logged in it works correctly. (Safari 7)

**Comment by PVince81** [comment]
@cmonteroluque there is no possible quickfix for 8.2.2. See https://github.com/owncloud/core/issues/20681#issuecomment-164497262

The problem is an old problem that has only been discovered now: IE8, IE9 and Safari <= 8 automatically removes the hash part of the URL # on redirect. Redirect happens whenever the user needs to login (redirect to login page) before accepting the share. A possible rework has been proposed here https://github.com/owncloud/core/issues/20681#issuecomment-164497262 to use a different approach that doesn't require hash URLs.

The workaround for such users is to make sure they are logged in before clicking "Add to ownCloud" in IE8, IE9 and Safari <= 8

I'm moving this ticket to 9.0 to investigate the alternative but more intrusive approach: https://github.com/owncloud/core/issues/20681#issuecomment-164497262

**Comment by cmonteroluque** [comment]
@PVince81 makes sense. Thanks!

**Comment by PVince81** [comment]
To be honest I don't think it's really worth the effort. Some of these browsers won't be supported any more in 9.1.

**Comment by cmonteroluque** [comment]
won't fix
