### ISSUE TITLE
Feature request: A container for each user when using an object store as primary storage backend.

### ISSUE THREAD

**Issue by rontrompert** [owncloud/core#20735]
Recently I have been playing around with Openstack swift as primary storage backend for Owncloud.

I have seen that Owncloud puts all data from all users in one single container. This does not look OK to us since the SWIFT storage nodes use sqlite (on every node) for their metadata. One sqlite database is created for every container. This means that in the Onwcloud case this database can become really big. Now sqlite supports databases upto 140TB if I am correct, so that is a limit you don't run easily into but having a single database, the tables can become really large and the
performance of sqlite decreases with an increasing size of the tables. So here is a potential performance bottleneck for large installations.

Therefore we would like to have a container for each user.

**Comment by michaelstingl** [comment]
@MorrisJobke @MTRichards related to https://github.com/owncloud/core/issues/9299

**Comment by MTRichards** [comment]
Also related to 00004263

**Comment by MorrisJobke** [comment]
Wasn't there a similar ticket somewhere?I can't find it anymore, but I remind some calculations of how many users fit into one container when using what amount of data/files. Maybe @butonic finds it.

**Comment by MTRichards** [comment]
As an admin, I want to be able to configure ownCloud S3 and Swift object storage to use multiple buckets so that I don't see hotspots and bottlenecks in my instance as ownCloud scales.

Acceptance Criteria:
- admins must be able to configure ownCloud to use multiple buckets (by user is one potential approach)
- admins must be able to migrate from using a Posix filesystem to using an object store and back, so that they are not locked into a storage vendor or deployment scenario
- migration should happen online and not take the system down (e.g. put all new files in the new storage while slowly moving old files over to the new storage over time in the backgound)
- admins can configure the storage in the config file in some way to set up the new storage and start the migration

**Comment by PVince81** [comment]
- [ ] requires: per user home storage: https://github.com/owncloud/core/issues/23824

**Comment by rontrompert** [comment]
Since there is multibucket support now for S3 this issue is solved I would say. Thnx.
