### ISSUE TITLE
Header from files list should not move when scrolling down

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20827]
### Steps to reproduce

1. In files view create some files/folders
2. Scroll down files/folders view

### Expected behaviour

Header of the list should not move

### Actual behaviour

Header moves and dissapears when scrolling down the list of files

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2015-11-24T04:39:16+00:00 2bffeefee1d366a82eda66b9bd8a04f04bacab77

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
 Firefox.

![scrolldis](https://cloud.githubusercontent.com/assets/10596560/11471077/f7a7c488-9762-11e5-8728-b7078f99b662.gif)

**Comment by jancborchardt** [comment]
This is by design to make more space for the file list.

What we could do is show the header immediately when you scroll up a bit, no matter where you are in the file list. That’s something we might also do for the main header in mobile already though, so let’s continue there: https://github.com/owncloud/core/issues/7826
