### ISSUE TITLE
Feature Request: Add file locking (check-in, check-out)

### ISSUE THREAD

**Issue by xylo** [owncloud/core#20983]
OwnCloud has many advantages over classical file servers or other cloud systems.  However, a big and important feature is still missing:  File locking.

I know this has been discussed already 2 years ago (https://github.com/owncloud/core/issues/5267) and rejected for owncloud 5 and 6.

However, in our company it's still a big issue and it would be great if the ownCloud client and the webinterface would support it.

ATM we use the Workin2gether addon (https://apps.owncloud.com/content/show.php/Workin2gether+%28Lock+files+in+WebUI%29?content=164016). However, this is time consuming and error-prone.  An automatic solution based on filesystem locks would be much better.

**Comment by DeepDiver1975** [comment]
> However, in our company it's still a big issue and it would be great if the ownCloud client and the webinterface would support it.

Can you please elaborate what exactly the issues are that you are facing? THX

**Comment by xylo** [comment]
### Problem description

Let's assume the ownCloud server hosts a file called *test.xls* and two users (*A* and *B*) have synchronized this file with their local PC using the ownCloud Windows client.

If user *A* opens the file locally with Excel the file gets locked on the local filesystem which prevents other software from accessing/manipulating it.  Now it would be great if the ownCloud client could synchronize this lock with the ownCloud server (and other ownCloud clients) so that if another user (*B*) tries to open the file he gets the message that the file is locked and cannot be opened right now.
At least that's how it works with shared directories in Windows. Moreover the lock message tells *B* that the file is locked by *A*.

**Comment by DeepDiver1975** [comment]
> Seemingly the feature was present in ownCloud 5 (see #5267) but got unfortunately dropped. :-(

While the name suggests - your scenario was never addresses by owncloud up to now

**Comment by shaneonabike** [comment]
I agree I think this would be awesome especially with the integration of redis now. It must be some additional call from the actual app on each computer to lock this file. Presently, one of my clients is also have some issues because they have multiple users modifying files and things. The only solution was for me to enable the app suggested at teh top, but then requires that they log in :/

BUT I have to say that the file locking addition of Redis has really sped up the server quite a bit so I really appreciate all the improvements thus far!!

**Comment by nikosnikos** [comment]
It would be very helpful to us too. Some groups of our users work on the same document for a period of time and it would be very useful to have a file locking mechanism.

**Comment by toshko4** [comment]
I assumed since there is group functionality, there will be no missing file changes and overwritten works. In my point of view, this is a big drawback and a constant point of frustration for every group of people sharing files.
Now I'm forced to install Samba for group folders and use Owncloud only for personal files.
Otherwise, thanks for your good work! I hope I could ditch Samba for Owncloud in the future. :)

**Comment by PVince81** [comment]
Prerequisite is have a permanent locking mechanism in the backend @DeepDiver1975

**Comment by DeepDiver1975** [comment]
will be addressed with #31651
