### ISSUE TITLE
Files uploaded via sftp, ftp, smb not visible over webif

### ISSUE THREAD

**Issue by cybero2912** [owncloud/core#21122]
Files uploaded via sftp, ftp, smb not seen on the webif
see also forum thread:
https://forum.owncloud.org/viewtopic.php?f=36&t=31610

**Comment by RealRancor** [comment]
> The data directory on the server is exclusive to ownCloud and must not be modified manually.

https://doc.owncloud.org/server/8.1/admin_manual/issues/index.html#debugging-sync-issues
https://doc.owncloud.org/desktop/2.0/troubleshooting.html#isolating-other-issues

**Comment by cybero2912** [comment]
maybe - but it has been working since the beginning.
therefore something has been changed in 8.2.x which has caused this horrible behavior.

I never use the webif for mass file uploads - only sometimes for downloading or uploading single files.
The webif is only used by my users for up and downloads.
For me ownCloud is nearly useless if it is no longer possible to upload files not using the webinterface
I am using ownCloud since many years and it has been working fine since my first ownCloud installation.
It stopped working since I upgraded from 8.1.4 to 8.2.1

**Comment by MorrisJobke** [comment]
> therefore something has been changed in 8.2.x which has caused this horrible behavior.

Wasn't the auto scanning disabled and only enabled for external storages? cc @icewind1991 @PVince81 - see https://github.com/owncloud/core/pull/17950

**Comment by PVince81** [comment]
If you're talking about uploading files outside of ownCloud to a remote storage, then it has never worked accurately, see https://github.com/owncloud/core/issues/11797

One way to trigger update detection was usually to navigate into the folder in the web UI to make ownCloud do a discovery check. Another is to have a cron job that does `occ files:scan userx` to periodically rescan the remote storage.

Now if you say that navigating into the folder in the web UI does not work anymore, then that might be a regression.

"check for changes" is enabled by default for external storages, see the mount options (cog icon in the external storage page). It's only for the home storage that detection was disabled since 8.2 with `filesystem_check_changes` config.php option. This doesn't affect external storages as they are configured with their own mount options (cog icon)

**Comment by RealRancor** [comment]
@PVince81 The OP is uploading files via FTP to the oC data dir so no external storage in place here.

**Comment by PVince81** [comment]
Ok, usually it's best to never to never touch the data directory directly because if you rename files, ownCloud will not be able to know what files were renamed, so you'll lose attached information like shares.

But if you still want to use it this way, then make sure that "filesystem_check_changes" is set to 1 in config.php.

**Comment by cybero2912** [comment]
'filesystem_check_changes' => 1, in config.php did the trick
many thx to PVince81
