### ISSUE TITLE
More verbose occ files:scan - what has it changed

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#21147]
I notice  that the file:scan fixed the problems, but I would like to have at the end a resume: which files where added/removed, folders or storages where added/removed/not reachable. etc. and probably error from the app (kind of log file).

Related to the case: https://github.com/owncloud/enterprise/issues/954#issuecomment-163904898

@cdamken  @MTRichards @PVince81

cc @icewind1991

**Comment by mmattel** [comment]
@MorrisJobke FYI: I have started to improve files:scan a bit by showing statistics, see #19717
A documentation PR is also present for.
Note: At least where I tested the statistics PR, the hooks for files/directories showed the need to be improved because directories were additionally counted as files which IMHO should not be. Not really related to the PR but over all the numbers should be right.
