### ISSUE TITLE
Allow downloading of files unzipped from share link

### ISSUE THREAD

**Issue by godfuture** [owncloud/core#21170]
Zipped downloads are not common for mobile useres. Users do not know (and do not want) to handle zipped files on their phone.

I would be happy, if files could be downloaded as single file.

**Comment by PVince81** [comment]
This is not technically possible because browsers don't support delivering more than one file on download. So the server can only deliver single files for downloads, so to be able to download a folder it has to be zipped/tarred.

Well, in theory a download could be triggered for every file inside the folder, but then the user will receive the dialog "save as" for EVERY file. Imagine getting this dialog for 100 files.

Some users might have configured a default save location, so it might be fine for them. But for those who didn't, they'll get the dialog. There is no way to detect this from Javascript, so cannot switch the logic from there.

Closing as not feasible.
