### ISSUE TITLE
Feature Request: BackBlaze B2 External Storage

### ISSUE THREAD

**Issue by benmaynard11** [owncloud/core#21304]
I know that there are already a wide range of supported External Storage Services, however BackBlaze B2 is now available to the public and is really cheap for storage.

Would be great to see this implemented into OwnCloud.

https://www.backblaze.com/b2/cloud-storage.html

It has a set of API's, so should be fairly easy to implement?

**Comment by aspdye** [comment]
Sounds principle not bad. 
Unfortunately B2 supports apparently not the API's of S3 or any other backend we have already integrated in app:files_external (SFTP, WebDAV, SMB ...) :(

... so would have to be built here a separate backend into the app:files_external. Of this I advise currently off because Blaze Black B2 is still in public beta, and there may still be changes in the service (and its API).

**Comment by Xenopathic** [comment]
This should be implemented as an app that implements the required storage interface for ownCloud. You might want to look for a PHP library if you are looking to implement it.

**Comment by harveydobson** [comment]
Where would I need to start to look at implementing this into the core files_external app? 

I notice that in master the AmazonS3.php file has been.... moved?
