### ISSUE TITLE
Rebrand Suggestion

### ISSUE THREAD

**Issue by tinobedi** [owncloud/core#21394]
Hello everyone,
I like to propose a new logo, I'm attempt to make the logo a bit more self explanatory. Here's something I came up but take note that the COLOR IS NOT FINAL. I'm not sure what color it should be, I would love some input and suggestions. 

<img width="859" alt="screen shot 2015-12-29 at 2 54 53 pm" src="https://cloud.githubusercontent.com/assets/16480577/12041178/f2093e80-ae3c-11e5-9231-da214fa16cf2.png">

@jancborchardt

**Comment by aspdye** [comment]
First: You are able to rebrand your ownCloud Instance how you want. :) You can do this with the Themes.
Second: I think there is no need for a new Logo. The current Logo explains itself (in my opinion), and does this more than your Commit (again - my opinion). 

If you are an Designer, you are welcome at the IRC #owncloud-designers

Thank you for you work :) But in the Future: Ask, before you are investing so much Time in things that are not needed :smiley:

**Comment by raghunayyar** [comment]
I am closing this one.

**Comment by jancborchardt** [comment]
Hey @tinobedi – when you mentioned you’re interested in working on design & UX improvements, I was under the impression you’d like to work on the interface. ;) In any case, here’s some more specific feedback:

- Most importantly: What exactly is the reasoning behind your logo proposal? You didn’t write anything about that so it’s difficult to understand the motivation. For design changes or proposals there need to be proper arguments on why it’s an improvement.
- Due to the complex nature of your logo, it will not really work well in small sizes like the favicon. We do have the same problem with the current logo.
- The color red is very strange in connection with a cloud. Especially with the grey background, both colors fight and are a very uncomfortable contrast.
- The typeface is nice and simple and I also experimented with similar approaches. However it being slanted makes it look skewed and unstable.
- In general (also since it’s in such wide use already) we are quite unlikely to change the branding. Especially to something so completely different.

I’d suggest you check out the [Design page](https://owncloud.org/contribute/design/) to see how you can get involved, and recommend looking at the Design junior jobs of the web interface as starting tasks. :)

**Comment by tinobedi** [comment]
Thanks for your input @jancborchardt, @aspdye :)

The proposal is simple. OwnCloud brand isn't as mature as it's product version, we're almost on version 9 and Own Cloud has been developed for years now. Own Cloud logo doesn't speak for itself and that's not an opinion @aspdye. I've tested it with IT & tech-savvy individual, majority of people who hadn't heard of own cloud did not understand and some did not find the logo pleasant to look at. Individuals that did recognize Own Cloud brand also correlated it to Microsoft Paint.

We have a great program and the logo has fallen behind. Even though the logo has been widely used already but we should reconsider a new brand for the following reasons (in order). 

1. self-speaking
2. more recognizable 
3. sizable (favicon, etc) 
4. as mature as the product
5. appealing


Also @jancborchardt, the colors are not final. Favicon works quite well with tiny bits of tweaking and we can avoid the skewing to make it stable. :)

**Comment by aspdye** [comment]
Thank you @tinobedi for your (again it **is** an) opinion, and for your time investing in your research. 
Let's assume that what you say about the current logo is true. I do not understand how your proposal should change that. There are no plans to change anything with the ownCloud-Logo and I think there is no need. Thereby we would weaken the awareness of our brand "ownCloud" rather than strengthen.

To sum up, I think @jancborchardt and the whole ownCloud Design Team can judge best, and I trust him/them to design for a new logo (should this be necessary - what is not as @jancborchardt said above).

Lastly, I would like to note that ownCloud has quite a high level of awareness among IT professionals and administrators, and even if this would be not, I hardly think that would have nothing to do with the logo.

**Comment by tinobedi** [comment]
Again, thanks for replying @aspdye. we both would like to see Own Cloud develop more. We're both offering our skills and my skills are within branding and ux. Now what I am not saying is that we should adopt my concept because it makes things better. What I am asking @jancborchardt and the design team to do is take a second look at the brand. It has room for improvement and I like to see that discussion flush out as we get closer to a new milestone release (v9).

Also I don't depend on the design team to tackle all the problems by themselves. It's an open source project and I like to contribute too.


Lastly, the brand has a lot to do with how people feel about a product. The logo has somewhat on how people feel about a product but I reason with you that it may not be obvious.

**Comment by aspdye** [comment]
Hey tinobedi, 

You are welcome to contribute. A Tip from me: If your Skills are branding and ux you can look at open Label:Design Issues and fix them if you can :) 

I just want to add, that ownCloud is Open Source but I think we cannot change the Branding (Logo) out of the Community, because the guys from the ownCloud Inc. are also using it in a variant. For this and many other reasons this would be maybe not as easy as you think, and definitly not something getting aproved in an GitHub Issue. 

But again: Better help to improve the current Branding instead of completly creating a new one.

**Comment by jancborchardt** [comment]
First off cc @karlitschek @jospoortvliet FYI

@tinobedi I'm also aware that our logo can be better. However for reasons stated above, changing it should not be taken lightly. And as you can see from my comment above as well, I see some problems with your proposal too.

Hence, since you are interested in UX, I recommend you get involved in fixing design issues within the ownCloud interface first. That will get you accustomed to the community, the open source design process, and how ownCloud works. Then later we can talk about higher-level stuff lile branding. Ok?

**Comment by karlitschek** [comment]
I agree with @jancborchardt We might redesign the logo at some point in the future. But this will be definitely a longer running and more complex process. 
But thanks for you suggestion.
It would be great if you would get involved in the ongoing UX/Design work in ownCloud because there is a los to do.
Thanks :-)
