### ISSUE TITLE
styles="*  to move all in the css files for better creating themes

### ISSUE THREAD

**Issue by blackcrack** [owncloud/core#21411]
Hi,

i have try last year ?? ... btw, happy new Year !

Try last year to build a themefolder for OC and have massive 
troubles, because in the php-code and java exist stylescodes and not
by all exist clean classes or id's for customizing the owncloud via a own style file.

there for should all style commands in the owncloud code into the style/s.css file/s move
for have a clean possible to customizing and build up OwnCloud Themes/-Folders.

thank you for programming OwnCloud for the Community...
i love it.. !

best regards
Blacky.

blackysgate.net/owncloud

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by blackcrack** [comment]
thank you ! :)  (btw, because the icons for filextensions/mimetypes, have linked something, maybe can you use and modification it..)

**Comment by jancborchardt** [comment]
I don’t really get the problem, or fail to fully understand your post. Theming is easily done as described in the themes folder: https://github.com/owncloud/core/tree/master/themes – CSS files are simply added, and properties can be overridden.

**Comment by blackcrack** [comment]
the problem it is, in the sources be some style="blabla" and not at all can changed, because the style commands be directly in the html code and they cant be owerwriten, because it#s , if directly in the code, strictly /hard coded .. and by other parts, be not the need class or id  for create an entry .
J', maybe should you create different themes also for it by self.. with icons and css styles for see what i meant. :) I have try only play around with it .. and have work with ff (F12) and notpad2 and kwrite for editing the css file and have try for create  by classes and id's an theme and have become with to be there styles directly in the code where it changes by change the browser window not in % (percent) , more js related  and dynamic changed .. in the code . And by other hand, if you search in the templates, do you find 100% different directly style command, where make impossible to change via css in the themefile css file because, it's also "hardcoded" in the themplates.
This should should be investigated and maby need a rewrite and right named in the classes and id's,
maybe something like a clean up.. okey, have maybe many hand's working on the code and updated and pached but they have take different names or some names like they can maybe used and right appear . like the part of  : 
```
html, body, div, span, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, code, del, dfn, em, img, q, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, dialog, figure, footer, header, hgroup, nav, section {
    margin: 0px;
    padding: 0px;
    border: 0px none;
    outline: 0px none;
    font-weight: inherit;
    font-size: 100%;
    font-family: inherit;
    vertical-align: baseline;
    cursor: default;
}
```
it is one soup , all kickin' into it ! and makes particular tricky to create own themes.
because it is kickin all in one pot. and this works not for create different themes ..
I know I can be fooled ... but check it by self. and maybe... it is a small (or a big) 
cleanup in the code not bad.

best regards
Blacky

**Comment by jancborchardt** [comment]
Sorry, but our theming does not intend changing _everything_ like you apparently want to do. It’s intended to make simple adjustments like changing the logo, color, and some texts.
You can still change everything of course by just copying and overwriting the CSS. I don’t see why we should restructure the whole CSS just to accomodate that more, since it’s already quite easy if you want to do that (and it’s the first time I hear someone wants that).

To answer your specific concerns:
- I did write some themes myself of course, including the example theme: https://github.com/owncloud/core/tree/master/themes/example – that’s a good example of what theming entails.
- The big soup of code you refer to is a so-called CSS reset. It’s needed so that the following CSS has a common base across browsers since it resets all the styles which are injected by browsers themselves. Modifying that is not a good idea since it will make stuff look different in different browsers.

**Comment by blackcrack** [comment]
well, i have only get a better way.. if you.. what not use.. okey, your choice ..
and well, 2 different opinion be easy 2 different Opinions.. if you it not want.. okey..
was only a suggestion ..

best regards
Blacky

**Comment by jancborchardt** [comment]
@blackcrack well, we would have to spend time implementing it and then maintain it all. That’s not an opinion.

Also seeing what you want to do with it from the link you posted: http://www.blackysgate.net/files/upload/owncloud/ – is basically changing _everything_. You remove the app navigation, the file actions, the capability to use it on mobile and completely shuffle the design around. This is not something we need to optimize for, it’s easily possible with CSS. However I honestly doubt the use of it since one of our goals is to make software easily usable.

**Comment by blackcrack** [comment]
I use both ;) because both be not equal .. Both have his areas .. once for all share/mirroring the files in case Webserver to user's Browser (for Webspaceowner and hobby Homepagebuilder for distributing/gifting (verteilen von) files in a save way and strict way handleable by Admin) .... and once for Groups and more hidden and the private files and software .. 
PHP-Filemirror did i write/developed and it is a possible to share file as administrator with many possible tricks and without any Database, handleable with ssh and/or ftp alone ! , PHPcode and html only, without Java/JS, really old school buddy ;) hihi i use OwnCloud for my Android Handys and my Galaxy 10.1 for syncing all like calendar and contacts , i love Owncloud also ! But for Family and or Groups ... with phpfm can i have .hidden folders or htaccess for play around, or i use not an index.php i can use an index.html or an index.htm as html-displayer or i can implement in the mimetypes.php javascript (why i have build mimetypes.php also) for displaying movies or different pictures without download and so on.. easy a file-mirroring from the webserver to the User's Browser and have fully control about, as administrator.. try it easy out. and maybe do you have an bit fun with it and maybe some new ideas what can you implement in Owncloud. Maybe it is PHPFileMirror an inspiration for you :) Sometimes it is more easy,  makes more easy as complicated ;) becase on this can you build on it ;) Like a Tree.. an OOld tree ... like a Dos tree .. ;)

best regards
Blacky
