### ISSUE TITLE
Changing a master key

### ISSUE THREAD

**Issue by GitHubUser4234** [owncloud/core#21434]
Hello,

It seems that when the master key feature is enabled for encryption in ownCloud, and the master keys have been compromised, there is no easy way to change the keys? How would you do it? And any hope it will be easier in future versions?

Thanks.

(ownCloud version 8.2.1)

**Comment by LukasReschke** [comment]
@schiesbn Is there already a feature request for this?

**Comment by schiesbn** [comment]
Right, there is no way to replace the master key at the moment.

Replacing the master key also means that we would need to re-encrypt all files with the new key. This can be really expensive. Alternatively we could place the new key next to the old one and only encrypt new and updated files with the new key, if this would be acceptable security wise.

Another open question is how the key was compromised? If the attacker got the password it wouldn't be enough to generate a new key, because the password would be the same and the attacker could easily access the new key again.

So, some open question. But definitely something we should think about.

@LukasReschke no feature request for this, so lets keep this one.

**Comment by GitHubUser4234** [comment]
Thanks @schiesbn for the reply.

Using old and new key next to each other wouldn't really be an option when old sensitive data would still be vulnerable to unauthorized access.

One case would be when someone with internal access is suspected to have compromised the keys and to play safe, keys need to be replaced immediately. Or keys might be replaced on a regular basis as a security measure (scheduled downtime until all files are re-encrypted). 

The password for master keys is the same as the one for the first admin account?

Would it be possible to give a hint on how to write a key replacement script by ourselves?

Having the option to replace the keys in the future would give peace of mind to quite a number of professional companies who would like to use ownCloud with SSO and encryption.

Thanks a lot.

**Comment by LukasReschke** [comment]
> I believe having the option to replace the keys in the future would give peace of mind to quite a number of professional companies who would like to use ownCloud with SSO and encryption.

Please note that it is also possible to influence the ownCloud roadmap by being a paying customer of ownCloud Inc.: https://owncloud.org/support/

**Comment by schiesbn** [comment]
As said on IRC, the master key is encrypted with the secret stored in config.php. You can't change this secret easily because it is also used in other places. So if we want to be able to replace the master key with a new one and also with a new password we need to introduce a new config.php option to store the master key password. If it is set we use this password, if not we fall back to the "secret" for backward compatibility.

The though part of replacing the master key is not to generate a new one and set a new password somehow but to re-encrypt all files with the new key! Therefore we would need a occ call similar to "encrypt-/decrypt-all" and some extended logic to place a "read-key" and a "write-key" in the session. By the default this are the same keys. But in case of a "change master key call" we could add the old key as "read-key" and the new key as "write-key" and then read all existing files and writing them to new ones. So this involved quite some work as you can see if you look at the encrypt-all and decrypt-all commands.

**Comment by PVince81** [comment]
@MTRichards

**Comment by MTRichards** [comment]
Got it, thank you. This is indeed something we need to consider.

**Comment by GitHubUser4234** [comment]
We switched to nextcloud, so I'm closing this, thanks~

**Comment by PVince81** [comment]
Reopening as this is still a valid feature request for other users

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/28145

**Comment by PVince81** [comment]
Similar to https://github.com/owncloud/core/issues/27427, we need to find a way to pass extra values in the encryption storage wrapper architecture / storage wrapper architecture which is currently tricky.

Moving to "planned" to continue researching in the next release.

**Comment by PVince81** [comment]
@sharidas what was the latest state ? As I remember you cleant up the architecture problem a bit.

**Comment by sharidas** [comment]
@PVince81 So here is a quick test I did with core ( master branch + https://github.com/owncloud/encryption/pull/12 )
- [x] Enable master key. Create a file as admin user. Try to edit ( so that multiple versions can be there )
- [x] Recreate master key. Relogin back to admin user. The files can be opened with master key.
- [x] Create user `user2`.  As admin user create a folder `1` and create a file inside `1`. Now try to transfer the folder from admin user to `user`. 
- [x] Recreate master key. Both admin as well as `user1` files can be opened using master key.

**Comment by sharidas** [comment]
Backport to stable10 branch: https://github.com/owncloud/core/pull/29260

**Comment by PVince81** [comment]
@sharidas doc ticket please

**Comment by sharidas** [comment]
Created the ticket: https://github.com/owncloud/documentation/issues/3482

**Comment by PVince81** [comment]
new command present since 10.0.4beta2
