### ISSUE TITLE
Remove unsupported preview providers from core

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#21484]
We're sending mixed signals to admins by saying most [preview providers are unsupported and may put their instance at risk](https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/previews_configuration.html) while at the same time keeping them in core.

Now that providers can exist in apps, all these "unsafe" providers (PDF, SVG, Office, etc.) should be removed and users should seek alternative ways to generate their previews.

@LukasReschke @karlitschek @DeepDiver1975 @MorrisJobke @rullzer

**Comment by karlitschek** [comment]
I agree. This is not good. Where exactly do we say that they are unsupported and insecure?

**Comment by LukasReschke** [comment]
Basically those are the one in https://github.com/owncloud/core/blob/12b0e9e3bdd6de2d35165a52072d534c7c2f5fc2/config/config.sample.php#L746-L761 that we disabled long ago since they allow an user to do all kind of shenanigan  on the server. Leading to reading arbitrary files or sometimes even a remote code execution.

Moving them to an app makes sense. Yes. So something could download from the AppStore some App like "Office File Preview" and the disclaimer would say there: Only use if you trust your users and so on. Trade-offs are always dependent on the type of setup.

**Comment by LukasReschke** [comment]
(Note that it should technically already be possible to create preview providers within an App.)

**Comment by karlitschek** [comment]
This is not the answer to my question. Where do we say that they are insecure an not maintained?

**Comment by oparoz** [comment]
> I agree. This is not good. Where exactly do we say that they are unsupported and insecure?

In the link I provided, in the note box

**Comment by oparoz** [comment]
> (Note that it should technically already be possible to create preview providers within an App.)

Yes, it works

**Comment by karlitschek** [comment]
But it doesn't say that they are unmaintained. This would to totally stupid to ship something and say in the documentation that it is unmaintained. Of course they are maintained because they are part of a release.
It also says that they are disabled by default and should only be enabled if the admin knows what they are doing. This is a fair statement in my opinion. 
So what do I miss?

**Comment by oparoz** [comment]
*"considered unsupported" "we discourage enabling them" "not documented"*. That doesn't sound like something which is maintained to me. As an admin, it makes me think that if a problem is reported, it can stay untouched for years because that piece of code is not supported. Add to that the mention that there are security concerns and I wouldn't feel comfortable using the code.

**Comment by danimo** [comment]
While I acknowledge that there is a semantic difference, I fail to see the effective difference between unsupported and unmaintained from an admin POV. Because effectively for me as a responsible admin it means "don't use it". Why do we keep a discouraged offer, even so in our main package? Plus we were talking "unsupported" all the time, not "unmaintained".

**Comment by danimo** [comment]
Oh, @oparoz was faster :)

**Comment by karlitschek** [comment]
So unmaintained and unsupported is different in my opinion. Unmaintained means that no developer cares. Which is not true. We care because it is part of the release. And if there are obvious bugs and problems then we fix it. Supported mean that we actively help people with debugging their specific issues. This is something that we don't do. This is best effort only.

**Comment by oparoz** [comment]
Hmmm.... But isn't the whole distribution supposed to be unsupported unless you buy a support contract? That statement might make sense for those who have bought one, but I don't think it does for admins of the OSS version.

**Comment by karlitschek** [comment]
O.K. Interesting question. :-) 
We usually have enterprise supported and community supported. 
Enterprise supported is a completely different question. Honestly I don't even know how they handle this.
But we also have something like 'community supported' This usually means that people who ask questions on the forum or irc and mailing lists usually get reasonable answers. But this is not guaranteed of course because this is all community volunteers.

**Comment by oparoz** [comment]
Thanks for the clarification :)
So maybe make @LukasReschke cry by keeping everything as-is and reword that sentence to say that these preview providers will not be developed further or something and that it's advised to rely on apps if admins require more features, etc.
