### ISSUE TITLE
Support for S3 IAM Roles

### ISSUE THREAD

**Issue by jzonthemtn** [owncloud/core#21490]
First, nice product!

Second, a feature request to enable the use of S3 buckets without an access key. Our ownCloud runs on an AWS instance under an IAM role that has permissions to our S3 buckets. It would be nice if ownCloud did not make the access/secret key fields mandatory and if left blank ownCloud would get the temporary keys from the AWS instance metadata. We try to limit the number of AWS keys floating around to simplify things.

Thanks!

**Comment by PVince81** [comment]
@jzonthemtn If you'd like to try it yourself, here is the code that defines the parameters: https://github.com/owncloud/core/blob/v8.2.2/apps/files_external/lib/auth/amazons3/accesskey.php#L41
And here how the parameters are used: https://github.com/owncloud/core/blob/v8.2.2/apps/files_external/lib/amazons3.php#L116

With a bit of luck it might just be a matter of removing the required flag ?

@Xenopathic does auth scheme support optional parameters to ?

**Comment by Xenopathic** [comment]
Personally, I'd be more comfortable with creating a new authentication mechanism that doesn't take the access key and secret key parameters (aka an empty mechanism that just provides the necessary UX). It doesn't really make sense for an 'Access Key' authentication mechanism to not *require* an access key. And tbh we can remove the parameter checks from the storage class itself (AmazonS3 in this case) since the Backend and AuthMechanism do the checks for parameters themselves. But we still need to check if the access key/secret key is provided, and if not, don't try to use them to construct an S3Client.

**Comment by jzonthemtn** [comment]
Agree about the key fields being present but not being required. Maybe a checkbox that says "Use IAM Role" that toggles whether or not the key fields are enabled or visible would work.

**Comment by PVince81** [comment]
There are no plans to implement this soon. PRs welcome,see https://github.com/owncloud/core/issues/21490#issuecomment-169769966

**Comment by DeepDiver1975** [comment]
Secondary s3 storage integration just got move over to https://github.com/owncloud/files_external_s3.

Unfortunately GitHub does not allow to move issues. Please reopen the issue at https://github.com/owncloud/files_external_s3/issues
