### ISSUE TITLE
An exception log message is shown in owncloud.log file when login with an Active Directory user.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21656]
### Steps to reproduce

1. As admin user, configure a Active directory 
2. Log in oC with one user of the AD
3. Check owncloud.log file

### Expected behaviour
No log should be shown loging in oC.

### Actual behaviour

The following log is shown in owncloud.log after log in with a LDAP user, but the user can log in.

```
{"reqId":"7EpRJ71jG5XnXR6BNnBs","remoteAddr":"82.159.139.58","app":"user_ldap","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"No user available for the given login name.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(119): OCA\\\\user_ldap\\\\USER_LDAP->getLDAPUserByLoginName('SNagata')\\n#1 [internal function]: OCA\\\\user_ldap\\\\USER_LDAP->checkPassword(*** username and password replaced ***)\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/user_proxy.php(68): call_user_func_array(Array, Array)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/proxy.php(137): OCA\\\\user_ldap\\\\User_Proxy->walkBackends('SNagata', 'checkPassword', Array)\\n#4 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/user_proxy.php(183): OCA\\\\user_ldap\\\\lib\\\\Proxy->handleRequest('SNagata', 'checkPassword', Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/user\\\/manager.php(179): OCA\\\\user_ldap\\\\User_Proxy->checkPassword(*** username and password replaced ***)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(218): OC\\\\User\\\\Manager->checkPassword(*** username and password replaced ***)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/user.php(165): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/base.php(1064): OC_User::login(*** username and password replaced ***)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/base.php(960): OC::tryFormLogin()\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/base.php(922): OC::handleLogin()\\n#11 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Line\":104}","level":3,"time":"2016-01-12T15:10:24+00:00"}
```

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-12T04:19:25+00:00 373776b8d84bece3df4a06b157bbe41f51ef511d

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; dropbox.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Comment by davitol** [comment]
@blizzz Not sure if it is a bug or not

**Comment by nickvergessen** [comment]
Removing "needs info" because that makes developers ignore the ticket, because the label means that the author of the issue needs to post more details.

**Comment by blizzz** [comment]
Cannot reproduce with one AD.

But I think I know what is going on. You have more than one active LDAP configuration. The provided data is passed to the first LDAP server, to which the user attempting to login does not belong. So looking for the user will not return any result. This results in an exception which is being logged. So the login is attempted against the next LDAP server, to which the user belongs and which succeeds.

Logging the exception was added in this commit: https://github.com/owncloud/core/commit/553a981980571930a935a2e85895396f2813ae44

In most cases the exception will be logged because of type on the loginname, or when more than one LDAP servers are configured. These are uncritical cases.

@MorrisJobke  are you okay with changing this to info or debug level?

**Comment by davitol** [comment]
> But I think I know what is going on. You have more than one active LDAP configuration.

@blizzz  Yes, you are right, there's an LDAP and a AD configured in oC server.

**Comment by nickvergessen** [comment]
> are you okay with changing this to info or debug level?

Sounds good, unluckily the `logException()` method does not allow that, maybe we can add that.

**Comment by MorrisJobke** [comment]
@blizzz I added this to allow the admin to detect such cases. Putting it in debug will again make such issues hard to detect :( On the one hand for this backup setup it would be useful to hide it, but for another setup where the LDAP connection is broken or the user is simply wrong, it is maybe useful to have it available in the logs.

**Comment by blizzz** [comment]
@MorrisJobke

> this backup setup

fwiw, it's not a backup setup, these are two LDAP servers used in parallel.

It will probably cause some confusion when admins look into their logs and see those messages, which in plenty cases are due to typos by the user who attempts to login. I would not mind to leave it like this, but I'd expect admins coming up with complaints and bug reports.

**Comment by blizzz** [comment]
@MorrisJobke maybe we just add the LDAP host to the log message, so it might be more clear for admins.

**Comment by MorrisJobke** [comment]
> @MorrisJobke maybe we just add the LDAP host to the log message, so it might be more clear for admins.

Sounds good

**Comment by blizzz** [comment]
"Fixed" by improving log message, since we do want to keep the log output.
