### ISSUE TITLE
different packages for different php-versions on centOS 7

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#21780]
Steps to reproduce:

Fresh Install of php56 via scl packages on centOS7.
Install owncloud packages for centOS7 from:
https://download.owncloud.org/download/repositories/stable/owncloud/

Expected behaviour: owncloud installs alongside to php.56 and pulls php56 dependencies.

Actual behaviour: the owncloud package pulls in php54-packages as dependencies.

![bildschirmfoto 2016-01-18 um 16 06 38](https://cloud.githubusercontent.com/assets/12275313/12394687/b8711ba4-bdfd-11e5-8278-9e169a3d2932.png)

@felixboehm

**Comment by Kawohl** [comment]
@jnweiger

**Comment by karlitschek** [comment]
@dragotin FYI

**Comment by jnweiger** [comment]
The issue is within RPM. It does not allow choice in its dependencies. DEB does, as we can name a list of alternatives seperated with '|'.

In the past I created special case packages for several systems, but this always led to confusion, as customers often picked the wrong one.
I suggest a different solution for this kind of issue, involving a virtual provides.

owncloud requires 'oc-php-deps', which does not exist as a package name anywhere.
we create empty dummy packages, that do nothing except they all provide 'oc-php-deps' and each one of them depends on an existing specific php configuration.

In this case:

<pre>
%package: oc-php-deps-centos7-scl-php56
%provides: oc-php-deps
%requires: php56-base, ....
</pre>

Easier to maintain on our side (obsoletes the horrible if elsif else constucts on the spec file).
No more SCL specific instructions needed for end users.
oc-php-deps can be built and provided independently. Even as a hot-fix response.

@Kawohl do you get the idea?

**Comment by felixboehm** [comment]
Sounds got for me.

**Comment by jnweiger** [comment]
The original solution was to build multiple packages, one for each php version.This is what we currently have for centos6. It comes with a significant maintenance overhead and is always a source of confusion on the customer side.

The above idea simplifies both, packaging and installation instructions.

**Comment by PVince81** [comment]
Any update ?

**Comment by jnweiger** [comment]
The generic owncloud-files package from https://download.owncloud.org/download/repositories/9.0/owncloud-files/ solves this.

Discussion how to get the dependency packages like php5-libsmbclient compiled for specific systems is a documentation issue. https://github.com/owncloud/documentation/issues/2172

**Comment by PVince81** [comment]
Close then ?

**Comment by crrodriguez** [comment]
yes
