### ISSUE TITLE
System tags section in sidebar GUI impl

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21815]
- [x] base work in sidebar: https://github.com/owncloud/core/pull/20847
- [ ] remaining known issues (grabbed from https://github.com/owncloud/core/pull/20847)
    - [x] tag conflicts, see https://github.com/owncloud/core/pull/20847#issuecomment-173170615 => PR here https://github.com/owncloud/core/pull/21952
    - [ ] name tag not updated: see https://github.com/owncloud/core/pull/20847#issuecomment-173171981
    - [x] TODO: use select2's "locked" attribute for value that have userAssignable: false
    - [ ] UI glitch. Have multiple tags available. Select the top one. Everything si fine. Select the bottom one and the focus shifts to the top.
    - [ ] Tag list dropdown is only reordered on tag selection. Not deselection.
    - [ ] UI glitch: Delete a tag, close the select2, tooltip for "Delete" is still there
    - [ ] proper handling when there are more than one row of tags (auto-expand on edit?)
    - [x] bring back the pretty boxes!!! => https://github.com/owncloud/core/pull/21958
    - [x] list tags in alphabetical order
- [x] distinguish non-assignable tags when viewed as regular user
- [x] UX review @jancborchardt 

Subticket of https://github.com/owncloud/core/issues/16325

**Comment by PVince81** [comment]
The section is done apart from the bugs and UX issues.

@jancborchardt please try it out. I'd prefer to have little boxes as they'd look more like tags. (see how select2 does it by default)

**Comment by PVince81** [comment]
This is on master.

**Comment by jancborchardt** [comment]
Yup, will check it out.

**Comment by jancborchardt** [comment]
Ok, besides some UI glitches the interaction is good! :)

Two major things though:
- Do we want to enable the Tags feature by default? It seems that this should be an opt-in functionality because it sits in a major place in the interface but at the same time doesn’t seem to be as basic a feature as the rest next to it. What do you think @karlitschek @PVince81?
- The whole »(visible, assignable)« stuff behind every single tag makes it really really technical. This should only be displayed once there are actually different types of tags. And for a tag which is visible and assignable we really never need to display anything since that’s the default. There only needs to be a note if it’s »not visible« or »not assignable«.
- The wording in the box by default is »Global tags«. That’s a bit confusing. I know the reasons and all, but simply saying »Add tags …« makes it much simpler.

**Comment by karlitschek** [comment]
I think if we are able to also do integration/filtering on the left sidebar then this is a very useful feature which should be on. If not then we could debate this. But i will probably still vote for on. There are usecases where this is usefull when working in teams.

**Comment by PVince81** [comment]
@jancborchardt thanks for the feedback.
What do you think about my proposal to display the tags as boxes like select2 does by default ?

I'll remove the visibility in the default case in a follow-up PR.

**Comment by jancborchardt** [comment]
@PVince81 right, wanted to say that I agree with you: we should use the lil boxes style because it looks more like tags. :)

**Comment by PVince81** [comment]
Moved remaining issues to https://github.com/owncloud/core/issues/22329
