### ISSUE TITLE
"Add server automatically once a federated share was created successfully" - disable by default

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21883]
I'd advocate to disable the `Add server automatically once a federated share was created successfully` switch by default after installation. Admins should explicitly have to opt-in to share their instance data.

cc @MorrisJobke as discussed
cc @karlitschek @schiesbn @DeepDiver1975  Thoughts?

![2016-01-25_10-47-33](https://cloud.githubusercontent.com/assets/878997/12547478/0c57ffb4-c351-11e5-9016-1d3512e91330.png)

**Comment by karlitschek** [comment]
:-1: no. this is intentionally to build a mesh. otherwise no one will use it

**Comment by DeepDiver1975** [comment]
I was just thinking about this: So this feature will expose all user information of an instance to another instance as soon as one user accepts a fed share.

From another perspective my data might me exposed any point in time without my knowledge just because another user will share something with somebody else. (I might not even know both of them).

Do we really want this?

Especially for hosters/providers this is highly critical I guess. 

Should we implement the privacy setting on the personal user information?
We have been talking about this last week AFAIK.

**Comment by karlitschek** [comment]
Yes. There are situation where an admin might turn this of. like for example providers. But for all other users this is actually exactly what we want. The way to autocomplete other users that people don't know yet. And the creation of a federated share is enough prove that this is half trusted. and the admin can always delete the server again and maybe disable the feature. So this is actually exactly what was planed. Otherwise we can't have the network effect that we want. Please leave it as it is at the moment. @schiesbn @jancborchardt

**Comment by DeepDiver1975** [comment]
@karlitschek I fully understand the intention - I just want to do it right. 

Should we blog early and often about this?

**Comment by karlitschek** [comment]
@DeepDiver1975 Yes. definitely. 
@jospoortvliet FYI

**Comment by jancborchardt** [comment]
Yup, this definitely needs to be an opt-out setting as it is right now. Otherwise very few people will enable it.

**Comment by LukasReschke** [comment]
=> Documentation stuff then. Works for me.
