### ISSUE TITLE
[TAGS] Delete tags is not shown at the first point

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#22063]
STEPS:
1.- Access to the tags menu
2.- Display the scroll down to list all the available tags

CURRENT BEHAVIOR
The trash bin is not shown till you previously click on the "pencil" to rename te tag

EXPECTED BEHAVIOR
The delete button is not hidden :open_mouth: 

![screen shot 2016-02-02 at 9 27 47](https://cloud.githubusercontent.com/assets/1846927/12743628/4e50fa94-c98f-11e5-82f0-b391758c0392.png)

@owncloud/designers

**Comment by PVince81** [comment]
Yes, it's by design that the trashbin only appears after editing. Probably to clutter the UI less.

See @jancborchardt's comment here: https://github.com/owncloud/core/pull/20847#issuecomment-171370949 ("move the delete action into the edit interaction")

CC @SergioBertolinSG in case you had the same idea

**Comment by jancborchardt** [comment]
Yep. It is because otherwise you might click the delete icon inadvertently. Deletion is not that common that it needs to be so exposed.
