### ISSUE TITLE
Make it possible to restore individual files/folders from backup (also with encryption)

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22096]
Ref: https://github.com/owncloud/core/issues/22042#issuecomment-179148515 and 
Doc: https://github.com/owncloud/documentation/issues/2131

Steps to reproduce on v8.2.2:
1. Setup ownCloud with encryption
2. Create a user "user1"
3. Login as "user1"
4. Create a file "test.txt"
5. Back up the whole data folder
6. Delete the file "test.txt"
7. Empty trashbin
8. From the data folder backup, restore the actual file: "data/user1/files/test.txt"
9. From the data folder backup, restore the encryption keys of the file: "data/user1/files_encryption/keys/files/test.txt"  (folder)
10. Go to the web UI: no file appears
11. Run "occ files:scan user1"
12. Refresh the web UI: file appears
13. Check "oc_filecache" entry, "size" and "encrypted" flag
### Expected result

File "test.txt" restored properly
### Actual result

File "test.txt" has the wrong size in the file cache (encrypted size instead of non-encrypted size).
"encrypted" flag is still set to 0.
### Versions

ownCloud 8.2.2

One idea would be to have the file scanner be able to identify encrypted files somehow by looking at the keys folder. If keys exist, assume that the file is encrypted and compute its "unencrypted size".

I think restoring individual files/folders from backup is a valid use case for admins and should be supported properly. What do you think ? @MTRichards @karlitschek @DeepDiver1975 @cmonteroluque 

@schiesbn @icewind1991 

CC @MorrisJobke

**Comment by MorrisJobke** [comment]
@MTRichards This is the discussion about partial restore of encrypted data.

**Comment by MTRichards** [comment]
Absolutely. If this can't be worked as a bug because it requires major changes, then I would consider this something for the roadmap.
@karlitschek @schiesbn @cmonteroluque 
Any input on if this is possible, or an approach?

**Comment by PVince81** [comment]
One proposed solution is to have files:scan also recognize encrypted files, if there are keys present (assuming the keys were properly restored from the backup by the admin too, this will be documented)

Not sure how difficult this is, need input from @schiesbn.

I don't have any ideas for better approaches so far.

**Comment by cmonteroluque** [comment]
I completely agree it has to be supported. @schiesbn ping?

**Comment by schiesbn** [comment]
> One proposed solution is to have files:scan also recognize encrypted files, if there are keys present (assuming the keys were properly restored from the backup by the admin too, this will be documented)

This would work for the current encryption module. But what happens if someone writes a new encryption module which stores the keys somewhere else or doesn't use any keys at all?

The better solution would probably be to ask the encryption manager for the right encryption module and then ask the encryption module if it is a encrypted file or not. Instead of putting this logic to files:scan I would add a hook to files:scan, something like `post_file_scanned(['path' => $path, 'info' => $fileInfo])`. Then the encryption app can listen to the hook and update the file cache if needed.

**Comment by schiesbn** [comment]
This just come to my mind while debugging another issue. From ownCloud 9.0 on this will not be possible. Because the filecache entry also stores the "encryption version" of the file in order to check the signature. If the database entry is gone and you restore a file from the backup there is no way to find out what's the correct encryption version.

cc @LukasReschke just for your information, maybe you have a idea.

**Comment by RealRancor** [comment]
I think that really should be documented somehow in https://github.com/owncloud/documentation/issues/2131 as a user was hit that by that yesterday: https://github.com/owncloud/core/issues/23775

**Comment by PVince81** [comment]
This way of restoring backup is not supported and is documented now (with a warning that it's not supported)

I'm closing this.
