### ISSUE TITLE
Encrypt file names when default encryption module is used

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22105]
Preliminary targetting for 9.1 following up a discussion with @karlitschek.

**Comment by LukasReschke** [comment]
Assigning myself but probably need some decent involvement of @schiesbn as well.

**Comment by DeepDiver1975** [comment]
:see_no_evil:

**Comment by RealRancor** [comment]
Two open issues about that: https://github.com/owncloud/core/issues/16722, https://github.com/owncloud/core/issues/11814

**Comment by schiesbn** [comment]
Should this be part of the encryption app or a particular encryption module or a independent app?

If we really want this I tend to implement it independent from encryption. So you can combine it with any encryption module.

**Comment by pieterk** [comment]
Not sure if I am too late on these comments but maybe a simpler approach is UUID linking in the database rather than encrypting the file names or folder structures? (basically is encryption per se).

So simply generate a UUID of an uploaded file and this will then become the file name stored in the database store the original file name and the UUID so that the two can be linked together? This can then be a file handler plugin.

For example:

```
virtual_file_name: myfile.txt
real_file_name: 4c0a1c7e-41b8-43d8-b1c1-850c6b2166d6
```

Of course if the owncloud server is compromised you can still link the two but I suspect bigger issues then as access to the owncloud server provides access to the encryption key anyway.
