### ISSUE TITLE
Newest "Premature end of script headers" issues with opcache

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#22117]
Hi,

where getting more and more reports about ``Premature end of script headers`` messages causing 500/internal server errors here at github, at the forums and at IRC:

https://github.com/owncloud/core/issues/21876, https://github.com/owncloud/core/issues/21869
https://forum.owncloud.org/viewtopic.php?p=106269
https://forum.owncloud.org/viewtopic.php?p=106269#p106269
https://forum.owncloud.org/viewtopic.php?f=31&t=32772

Those issues are solved by disabling opcache. Could someone with deeper knowledge have a look at this? Thanks

**Comment by PVince81** [comment]
@icewind1991 @DeepDiver1975 @LukasReschke

**Comment by LukasReschke** [comment]
That really just seems to be a configuration problem on the hosting site. Especially shared hosters do enforce quite some low memory limits as they simply don't want (and often also don't allow) running software such as ownCloud. And in fact, when using my search engine of choice there are tons of other examples where PHP software does not run properly on DreamHost due to such limitations.

This error message can be caused by quite some things, mostly it boils down to not being able to assign the required amount of memory. We could probably tell me more if we get the `phpinfo()` output as well as the PHP/Apache error log as that contains such errors. (ownCloud log does not necessarily contain fatal errors as those)

**Comment by RealRancor** [comment]
Maybe @bkerensa or @stephengraf can provide this info

**Comment by stephengraf** [comment]
I was able to find a solution, please read:
[2.1.0] opcache interaction with sync client #4393
by trying the unreleased version of the sync app.
The problem was very repeatable by turning on and off opcache.

**Comment by stephengraf** [comment]
The issue was opened in the client section, not core.
[]()https://github.com/owncloud/client/issues/4393

I added logs from the client and Wireshark traces from the network. This issue is very strange.  The problem seems to come from the client as the bad packet is rejected by the web server and never makes it to the ownCloud code.  However, turning on opcache in php seems to cause the problem!

**Comment by Xenopathic** [comment]
@stephengraf Looks almost like a race condition, from your HTTP traces in the other issue. Since I can't reproduce it here, could you perform more detailed packet analysis? Ideally, a Wireshark packet dump of the entire HTTP transaction, not just a .docx print. You should be able to save a trace (make sure you have the right filters set) from the menu, in the `pcap` format.

**Comment by stephengraf** [comment]
I saved the traces. Here they are.

**Comment by stephengraf** [comment]
I don't think I can add the trace files.  They are not of the correct type seem to get dropped.

**Comment by Xenopathic** [comment]
@stephengraf You can't attach files to the GitHub emails, you need to attach them here via the web UI

**Comment by stephengraf** [comment]
The files are binary and can not be attached.
 Error Message:
Unfortunately, we don’t support that file type.  Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP

Is there another email address that I send them to you?

**Comment by stephengraf** [comment]
I can add zip files!
[wireshark_trace.zip](https://github.com/owncloud/core/files/120502/wireshark_trace.zip)

**Comment by Xenopathic** [comment]
@stephengraf It's very strange how the server seems to be sending a 401 Unauthorized before the PROPFIND actually comes through... the only way to debug this further is to see what the PHP side is doing.

**Comment by stephengraf** [comment]
I stopped looking at this when the client support team asked me to try a pre-release of 2.1.1 of the windows client.  They changed how and what the client is sending and the problem went away.

**Comment by bkerensa** [comment]
I am going to reiterate that when I ran into this I had had opcache on for over a year and it started occurring in OC 8.2.2 but did not in prior versions. I consider this to be a regression on OC's side and not a server config issue because I did not change anything on my VPS in the timeframe this started occurring the only change that occurred was a OC upgrade.

**Comment by LukasReschke** [comment]
@bkerensa Please provide the required information mentioned above. Reiterating that certainly ownCloud is to blame is not really useful to solve the problem. Thanks.

**Comment by bkerensa** [comment]
I already provided that information on the original bug which you guys closed as a invalid.

**Comment by LukasReschke** [comment]
No. The phpinfo() is for example missing in your original issue.

**Comment by blizzz** [comment]
@bkerensa could you provide the missing info?

**Comment by RealRancor** [comment]
Closing due to the lack of activity. Haven't seen any further reports of that so its probably really an environmental issue.
