### ISSUE TITLE
Sabre DAV Exception - There was no handler found for this "GET" 

### ISSUE THREAD

**Issue by kwoxer** [owncloud/core#22140]
So when I visit my website with owncloud [https://server.eu/remote.php/caldav/](https://server.eu/remote.php/caldav/) I get the login popup, but when I type in there the correct accountinfos. It always gives me a xml like this:

`<d:error><s:sabredav-version>2.1.7</s:sabredav-version><s:exception>Sabre\DAV\Exception\NotImplemented</s:exception><s:message>There was no handler found for this "GET" method</s:message></d:error>`

In the backend in the log there it says not much more:

> Exception: {"Message":"HTTP\/1.1 501 There was no handler found for this \"GET\" method","Exception":"Sabre\\DAV\\Exception\\NotImplemented","Code":0,"Trace":"#0 \/usr\/share\/nginx\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/usr\/share\/nginx\/owncloud\/apps\/calendar\/appinfo\/remote.php(60): Sabre\\DAV\\Server->exec()\n#2 \/usr\/share\/nginx\/owncloud\/remote.php(137): require_once('\/usr\/share\/ngin...')\n#3 {main}","File":"\/usr\/share\/nginx\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":472

I use Nginx, so what could I try to solve this issue. I just installed ownlcoud the first time. So I have no experience. But all the other stuff seem to work well.

ownCloud 8.2.2 (stable) 
nginx/1.4.6 
PHP 5.5.9-1ubuntu4.14 (fpm-fcgi)

**Comment by karlitschek** [comment]
@DeepDiver1975 any idea?

**Comment by kwoxer** [comment]
https://github.com/owncloud/core/issues/22017 and https://github.com/owncloud/core/issues/22017 look very close to mine and are just some days ago. Maybe it's really an issue?

**Comment by kwoxer** [comment]
Also tried to connect with Thunderbird CalDAV but there I not even get any error message. Any help is totally welcome and feel free to play with the link above.

**Comment by kwoxer** [comment]
Ok wait, just to make sure. The login is the same credentials like these in owncloud right? Or do I need to create a CalDAV account or so?

**Comment by kwoxer** [comment]
I sometimes also get the log message. But it's **Debug **und not an error:

> Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 \/usr\/share\/nginx\/owncloud\/lib\/private\/connector\/sabre\/auth.php(154): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 \/usr\/share\/nginx\/owncloud\/lib\/private\/connector\/sabre\/auth.php(127): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#2 \/usr\/share\/nginx\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/usr\/share\/nginx\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/usr\/share\/nginx\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/usr\/share\/nginx\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/usr\/share\/nginx\/owncloud\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#8 \/usr\/share\/nginx\/owncloud\/remote.php(137): require_once('\/usr\/share\/ngin...')\n#9 {main}","File":"\/usr\/share\/nginx\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70}

**Comment by kwoxer** [comment]
Alright, it seems that I was using it in a wrong way.

So https://www.ljtd.eu/remote.php/caldav/calendars/**accountname**/**calname** works as intended with Lightning.

Does this really mean that I have to create each Calendar on it's own. So there is no bulk option for adding all calendar once?

Anyway it works but for more infos you are welcome :)

**Comment by Xenopathic** [comment]
You cannot directly access the CalDAV and CardDAV URLs from a web browser (using the GET HTTP method), you must use a CalDAV/CardDAV client like Thunderbird or DAVDroid. That's why you were getting that message about the GET handler - it's just not supported for that endpoint.

Unfortunately Thunderbird + Lightning does not do auto-detection of calendars AFAIK, so you'll have to add each one individually using the full URL. That's an issue with Lightning though, ownCloud cannot do anything about it.

**Comment by kwoxer** [comment]
Okay thanks for info :)

All is working fine, also on my Android.

**Comment by boTux** [comment]
I had the same error, but even using the direct URL for my address book didn't work (https://cloud.myurl.com/remote.php/carddav/addressbooks/myuser/myaddbook).

After some trial and error, the only way to make it work for me (with davdroid) was to stop using my sub-domain cloud.myurl.com and use only myurl.com with the .htaccess edited as seen in the [Doc Service-discovery section](https://doc.owncloud.org/server/8.2/admin_manual/issues/index.html#service-discovery).

`Redirect 301 /.well-known/carddav /cloud/remote.php/carddav`
`Redirect 301 /.well-known/caldav /cloud/remote.php/caldav`

To make it work I had to create a symbolic link to my cloud directory in my domain root.

It's strange because I was using successfully the well-known on my sub-domain before...

But the official android owncloud app isn’t syncing... 
`{"reqId":"VtwMyQoAXzwAAASaO8gAAAJJ","remoteAddr":"x.163.x.x","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at /cloud\/www\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at /cloud\/www\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-03-06T10:56:09+00:00"}`
