### ISSUE TITLE
Do not automatically disable encryption when using decrypt-all

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22167]
When running the decrypt-all command for a single user, it automatically disables encryption for everybody.

What if someone just wanted to decrypt the files of a single user to back up the files but leave encryption enabled globally ?

Also, if someone intended to run decrypt-all for several users one by one, it will not work after the first one because encryption gets disabled.

It's mostly a usability issue / inconvenience because it is possible to manually reenable encryption.

@schiesbn

**Comment by chriseqipe** [comment]
I also wonder, why, while decrypting all the files is running,  maintenance:singleuser should be enabled. 
A big setup with millions of files takes hours and hours to be decrypted - meanwhile oc users get crazy waiting for the oc instance to be accessible again...
 
It would by wiser to have the decryption in background. With encryption disabled, new files or changed files will stored without encryption. That's alright to me.

**Comment by schiesbn** [comment]
@chriseqipe you can't let the user manipulate files while you decrypt all files. Think about a user upload new files or update existing files. For example decrypt all already decrypted file A and then the user uploads a modified version and the file is encrypted at all.

If you switch your system from "all enrypt -> all decrypted" or the other way around this is a change in the really basic setup of your system. Similar to changing from MySQL to PostgreSQL or the primary storage from your local hard disc to a Amazon s3 server. This is something you don't do "just for fun". We only provide this because many people requested it. But it is really meant for "emergency cases". I expect people to decide at the beginning if they want to use encryption and then stick to it the same way they chose there database, etc.

**Comment by chriseqipe** [comment]
@schiesbn thx for you reply. I thought if encryption just has been disabled a new file will be uploaded the encrypted version just gets overwritten by the not encrypted version....
But in my test I saw that only new uploaded files can be uploaded as not encrypted. Already encrypted files could not no be overwritten if encryption was disabled. After reenabling encryption it was possible to overwrite it. 
Wouldn't it be good if oc just overwrites an encrypted file by using the not encrypted version and updates the referencing data in filecache and removing referenced keys? As it is possible to access/download not encrypted files, while encryption is enabled. Just a thought...

**Comment by chriseqipe** [comment]
We just converted a an oc instance with about 246364 files in it. 
And I'd like to share my experience I made: 

First: It take hours and hours. The server environment with 16G RAM and a lot of cpu around only was able for average decryption rate about 2 files per second. For 246364 files it would take about **34 hours for decryption**.  We decided to start decryption at friday night. Then after 12 hours of decryption the cli php process run out of memory and stopped. We gave more memory to the virtual machine and started over the decrypt-all process. And suprise! All already decrypted files are going to be decrypted again. Very frustrating. Average rate still only 2 files per second. 

So we decided to try to understand the decryption process by debugging it: 
We found: 
```
protected function decryptUsersFiles($uid, ProgressBar $progress, $userCount) {

		$this->setupUserFS($uid);
		$directories = array();
		$directories[] =  '/' . $uid . '/files';

		while($root = array_pop($directories)) {
			$content = $this->rootView->getDirectoryContent($root);
			foreach ($content as $file) {
				$path = $root . '/' . $file['name'];
				if ($this->rootView->is_dir($path)) {
					$directories[] = $path;
					continue;
				} else {
					try {
						$progress->setMessage("decrypt files for user $userCount: $path");
						$progress->advance();
						if ($this->decryptFile($path) === false) {
							$progress->setMessage("decrypt files for user $userCount: $path (already decrypted)");
							$progress->advance();
						}
					} catch (\Exception $e) {
						if (isset($this->failed[$uid])) {
							$this->failed[$uid][] = $path;
						} else {
							$this->failed[$uid] = [$path];
						}
					}
				}
			}
		}
	}

```
```
if ($this->decryptFile($path) === false) {  
```
never get's false ! Even if a file was already decrypted. 
So we changed the code to: 
```
 if ($file->getData()['encrypted'] == 0) {
                            $progress->setMessage("decrypt files for user $userCount: $path (already decrypted)");
                            $progress->advance();
                        } else {
                            if ($this->decryptFile($path) === false) {
                                $progress->setMessage("decrypt files for user $userCount: $path (already decrypted)");
                                $progress->advance();
                            }
                        }
```
This way we have been able to decrypt nearly all files in time. 14 Files stayed enrypted for what ever reason. And we saw, that decryption runs for nearly every files again for every user. Imagine if we had not done the patch. Time for decrytion would have been multiplied by users....

Another thing we discoverd. While decryption is running, the jobs table get's filed by every file that has been decrypted. Over 200'000 records have been inserted. cron.php very slowly processed the job table entries, by using not clever queries like the following: 
```
-- Connection Id: 4137913
-- User: ????
-- Host: x.x.x.x:50049
-- DB: ????
-- Command: Query
-- Time: 0
-- State: updating
DELETE FROM `jobs` WHERE `class` = 'OC\\Command\\CommandJob' AND `argument` = '\"O:33:\\\"OCA\\\\Files_Versions\\\\Command\\\\Expire\\\":2:{s:43:\\\"\\u0000OCA\\\\Files_Versions\\\\Command\\\\Expire\\u0000fileName\\\";s:111:\\\"carpathia-archiv\\/Carpathia\\/Swiss_eCommerce\\/Award-Connect\\/2013\\/LaudationesSpeaches\\/130515_award_laudationes.xlsx\\\";s:39:\\\"\\u0000OCA\\\\Files_Versions\\\\Command\\\\Expire\\u0000user\\\";s:14:\\\"admin-owncloud\\\";}\"'
```
Because no index is used at all 
```
explain DELETE FROM `jobs` WHERE `class` = 'OC\\Command\\CommandJob' AND `argument` = '\"O:33:\\\"OCA\\\\Files_Versions\\\\Command\\\\Expire\\\":2:{s:43:\\\"\\u0000OCA\\\\Files_Versions\\\\Command\\\\Expire\\u0000fileName\\\";s:111:\\\"carpathia-archiv\\/Carpathia\\/Swiss_eCommerce\\/Award-Connect\\/2013\\/LaudationesSpeaches\\/130515_award_laudationes.xlsx\\\";s:39:\\\"\\u0000OCA\\\\Files_Versions\\\\Command\\\\Expire\\u0000user\\\";s:14:\\\"admin-owncloud\\\";}\"';

+------+-------------+-------+------+-----------------+------+---------+------+--------+-------------+
| id   | select_type | table | type | possible_keys   | key  | key_len | ref  | rows   | Extra       |
+------+-------------+-------+------+-----------------+------+---------+------+--------+-------------+
|    1 | SIMPLE      | jobs  | ALL  | job_class_index | NULL | NULL    | NULL | 101007 | Using where |
+------+-------------+-------+------+-----------------+------+---------+------+--------+-------------+
1 row in set (0.01 sec)
```
this query goes very slow and it takes hours for cron.php to end the work on the jobs table...
I haven't had the time to investigate cron.php, but it's seems to me as it's needs some recoding here too...

Anyway: 
You can see the patch here: 
https://github.com/chriseqipe/core/commit/ff897901bd8d87edcb55f27be0c3e480027b2b98

Chris

**Comment by PVince81** [comment]
@chriseqipe thanks a lot for your feedback.

@schiesbn would be good if we could have a look at improving decryption performance and also integrate that patch.

**Comment by PVince81** [comment]
The patch was integrated already in 9.1: https://github.com/owncloud/core/pull/24628

I had a look at the code and I don't understand why encryption is disabled globally before starting decryption. And if an error occurs, there is code that would reenable it.

Is it really required the encryption is fully disabled for the decrypt code to work ?
I'd expect to only have the "disable encryption" code once at the end.

**Comment by PVince81** [comment]
Just tired it, and it seems it doesn't correctly decrypt files if encryption is enabled. That's why it disables it globally..

So I made a PR that reenables encryption if only a single user was specified: https://github.com/owncloud/core/pull/25263
