### ISSUE TITLE
OC\Files\Filesystem::unlockFile()

### ISSUE THREAD

**Issue by musaa32** [owncloud/core#22191]
Hi, can you add the function **unlockFile()** to OC\Files\Filesystem?
Location:lib/private/files/filesystem.php
```
static public function unlockFile($path,$type) {
		return self::$defaultInstance->unlockFile($path,$type);
}
```

Need it for the App: https://apps.owncloud.com/content/show.php/files_filter?content=174667

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by DeepDiver1975** [comment]
@musaa32 please use the files view

```php
$view = new \OC\Files\View();
$view->unlockFile($path, $type);

**Comment by musaa32** [comment]
@DeepDiver1975 thx, I'll try it

**Comment by mckaygerhard** [comment]
could be pacthed my oc 6 and oc 7 installations with this to made able to backported that app to work with oc 7?

this app its unuseless due oc 8 takes too many resouces and php 5,.4 works slower rather my 5.3 and my os does not support 5.4 and i not going sustitute all the os only by a app

**Comment by RealRancor** [comment]
@mckaygerhard Please stop spreading your non-sense now also in the core-tracker

**Comment by carlospea** [comment]
i'm using OC 7 too, i'll reply in same places

**Comment by Rankgel** [comment]
why closed the replies, why dont accept the users still are in oc 7?

**Comment by MorrisJobke** [comment]
@rankgel 
Because we as owncloud developers want to move forward. We don't have unlimited resources and need to stop supporting old versions at some point in time. For version 7 this is reached at nearly 2 years of support. We will maintain newer versions of ownCloud and invest time to keep them save for usage. 

Feel free to maintain owncloud 7 yourself, but we will stop it, because we also just have 24 h a day and cannot do everything for free for everybody. We develop the current versions and need to cut the support the old versions.

**Comment by MorrisJobke** [comment]
@carlospea @mckaygerhard We highly encourage

**Comment by MorrisJobke** [comment]
@carlospea @mckaygerhard We highly encourage you to upgrade to a newer version because owncloud 6 is not supported or maintained anymore eland the same will happen to owncloud 7 in may of this year. To guarantee that your instance is safe from any know security issue you should upgrade to answer version soon. Also the newer versions contain many fixes that will provide you a more performant access to your files and we fixed many issues that make the experience with owncloud a lot better.

**Comment by RealRancor** [comment]
@MorrisJobke You don't need to discuss with that guys. They are also either one single person mckaygerhard (see https://github.com/snes9xgit/snes9x/issues/107) or otherwise related and just bumping issues of each other.
