### ISSUE TITLE
LDAP fails if //TRANSLIT isn't available in iconv

### ISSUE THREAD

**Issue by jomat** [owncloud/core#22224]
There are implementations of iconv that don't support transliteration: http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc#iconv

The php function iconv() will return an empty string here:
https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/access.php#L1109

This results in empty usernames which are, as expected, automatically appended by four random digits prepended with an underscore: https://i.imgur.com/GrZdPGD.png

Apparently those unique usernames are not used in the database:

```
owncloud=# select * from oc_ldap_user_mapping;
                   ldap_dn                    | owncloud_name | directory_uuid 
----------------------------------------------+---------------+----------------
 uid=ldaptestuser,ou=people,dc=example,dc=com |               | ldaptestuser
```

</code>

```
owncloud=# select * from oc_storages;
              id               | numeric_id | available | last_checked 
-------------------------------+------------+-----------+--------------
 home::localtestuser           |          1 |         1 |             
 local::/path/to/owncoud/data/ |          2 |         1 |             
 home::                        |          3 |         1 |             
```

No matter which LDAP user logs in, there's only one storage id for them all: "home::"
After logging in, the page stays blank and this error is logged:
"Call to a member function getFileInfo() on null at /path/to/owncloud/lib/private/files/filesystem.php#861"

**Comment by DeepDiver1975** [comment]
@blizzz mind taking a look? THX

**Comment by blizzz** [comment]
We need some stricter checks, some error logging, maybe an exception but i am not entirely convinced about this. 

Nice would be an idea about a fallback :speak_no_evil:

**Comment by jvillafanez** [comment]
As stupid as it sounds, replacing `false` string gives an empty string:
```
>>> str_replace(' ', '_', false);
=> ""
```

I guess we can check if the result from the `iconv` function is false. If we can't transliterate then we just keep going with the initial input. Invalid chars will be removed anyway, we'll just remove more chars.

@jomat could you verify what is the `iconv` function returning in your case? If it's returning false we should be able to fix it. According to the official documentation (http://php.net/manual/en/function.iconv.php) `false` should be returned if an illegal char is found since php 5.4.0

**Comment by PVince81** [comment]
Closing due to lack of feedback.

Feel free to reopen if the problem still exists with 9.0.6, 9.1.2 with PHP >= 5.6.
