### ISSUE TITLE
Encryption signature version not increased on upload

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22260]
### Steps

1. Enable encryption
1. Upload a file "test.txt"
1. Update the file "test.txt" in the web UI with the text editor, save
1. Check "encrypted" column in database
1. Update the file "test.txt" with Webdav PUT
1. Check "encrypted" column in database

### Expected result
Value of "encrypted" increases after every save

### Actual result
Value only increases when updated with the text editor, not Webdav

### Versions
9.0 git master 9ebcc4ce312db574173627488887f14db2f4bc34

@LukasReschke @schiesbn

**Comment by schiesbn** [comment]
Interesting... If the file is shared the version gets increased correctly if the recipients uploads a new copy of the file but not if the owner uploads a new copy :confused:

**Comment by schiesbn** [comment]
I think I know the problem:

if we update the shared file we do a stream copy of the part file to the original location because both are on different storages. This logic is correct. But if the owner updates the file we don't do a stream copy but just rename the .part file. So the bug seems to be in the rename logic, probably we need to add something there to increase the version as well

**Comment by schiesbn** [comment]
While looking at the code I found another potential bug:

On update we get the version here https://github.com/owncloud/core/blob/master/apps/encryption/lib/crypto/encryption.php#L375 and the we set the exact same version again here https://github.com/owncloud/core/blob/master/apps/encryption/lib/crypto/encryption.php#L396.

Either we need to increase the version here or we can remove the code completely. Generally speaking, just because we encrypt the file for some additional users we don't need to encrypt the version because the file content will stay the same. But with respect the the original issue it might be easier to just increase it in this case as well.
