### ISSUE TITLE
files_sharing is missing loadAdditionalScripts

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22328]
It's currently not possible to safely add Javascript to files_sharing as it's not dispatching the `loadAdditionalScripts` event.
Until this is fixed, `core` and any installed apps will be polluted by apps which add their scripts to app.php without making any checks to make sure they're on the page they target, leading to broken apps and `core`.

**Comment by nickvergessen** [comment]
What do you mean? it should dispatch the event on the public page?

**Comment by oparoz** [comment]
> it should dispatch the event on the public page?

Exactly, allowing apps to behave properly by only loading their scripts on pages firing the `loadAdditionalScripts` event.

**Comment by PVince81** [comment]
backlog for now, PRs welcome

**Comment by Rello** [comment]
Hello,

any plan to fix this right now?
seems was fixed in NC already. for now, the "proper" code with 

> $eventDispatcher->addListener('OCA\Files_Sharing::loadAdditionalScripts',
does not trigger in OC.

e.g. gallery has now 2 versions per cloud which could be avoided I guess?
https://github.com/owncloud/gallery/blob/master/appinfo/app.php#L61-L67

https://github.com/nextcloud/gallery/blob/master/appinfo/app.php#L77

I would like to avoid this for the Audio Player in my case

**Comment by PVince81** [comment]
I'd be fine adding this event if needed. Mind submitting a PR ?
