### ISSUE TITLE
Allow multiple link shares

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#22327]
In the current state we allow 1 link share file per user. This is somewhat problematic given our new resharing behaviour (see https://github.com/owncloud/core/issues/22295)

However even as a user I want to be able to have multiple link shares. Because in the current situation I have just 1 link share to give out. While what I actually want is create multiple link shares which I can also remove individually or expire at different dates.

@owncloud/designers maybe it is good to have a separate tab in the sidebar for link shares? To keep things a bit organized. Can you mock something up?

@owncloud/sharing Anybody sees an issue with multiple link shares per file per user?

CC: @PVince81 @DeepDiver1975 @MTRichards @schiesbn

**Comment by PVince81** [comment]
You forgot to mention the following case:
1. "user1" shares "test" with "user2"
2. "user2" reshares "test" with link

So far and in 9.0, "user1" does not know about "user2"'s link.

The question for this ticket is: do we want "user1" to also be able to know all link reshares that have been done ? From a "control my data" point of view I think it makes sense to make this visible.

But for that the UI needs to be able to accomodate for multiple link shares to appear.

**Comment by MTRichards** [comment]
Well, there is a long standing request for multiple share links in conjunction with (if emailed from ownCloud) with a list of with whom the link was shared. That list could be something like

Sharelink 1 (#)(x)
   me@me.com
   you@you.com

Sharelink 2 (#)(x)
   him@him.com

ShareLink 3 (#) (x)
   etc.

Scrollable of the bottom if the list gets too long 

And where the (x) can be clicked to remove the link, and # is the number of times a link was accessed.

**Comment by PVince81** [comment]
and the cool thing is that now the share dialog is a panel in the sidebar, where it's ok to have a scrollbar.
Back then in the tine dropdown a scrollbar would have been too much.

So there's room now :wink:

**Comment by MTRichards** [comment]
> The question for this ticket is: do we want "user1" to also be able to know all link reshares that have been done ? From a "control my data" point of view I think it makes sense to make this visible.

If we are collapsing all re-shares internally into user1's account as part of the rework, then user2 when resharing logically would have the reshare link collapse into user1's tab, but with user2 also seeing the share link.

Then, with federated sharing, it would be the same thing...right?

**Comment by rullzer** [comment]
So as it is currently done user1 sees everything. Since it is their data... user2 only sees what they have shared.

**Comment by MTRichards** [comment]
>So as it is currently done user1 sees everything. Since it is their data... user2 only sees what they have shared.

Seems to work as described, which is good...

**Comment by jancborchardt** [comment]
@rullzer what exactly is the use-case here? It seems it would nicely be covered by »Share via email« as mentioned in https://github.com/owncloud/core/issues/3224:

> - currently goes through share with link, too cumbersome
> - should be integrated in the one field on top: »Share with user or email«
> - show email in list like username matt@example.com, only action is x
> - future: generate unique link per email address so revocation on a per-person basis is possible

**Comment by rullzer** [comment]
@jancborchardt well I do not always want to share via e-mail.
But yes. This would solve that problem as well since then we just generate a unique link share per e-mail send.

**Comment by rullzer** [comment]
@MTRichards assigning to you to write the user story

**Comment by MTRichards** [comment]
As an ownCloud user, I want to be able to set up multiple links for sharing so that I can provide a unique link to the same shared directory or file to different people, and expire those links independently, and provide different privileges to each link.

Acceptance Criteria:
These are valid unless the share dialog is updated, in which case we will need to rewrite this.
- This is an extension to the existing share link options in the sidebar on the web
- This extends the existing share links options that already exist  
    - URL
    - password protect
    - allow editing
    - write only upload (new option) <--files drop functionality added here
    - email link to person
    - set expiration date
- allow editing and write only upload are mutually exclusive, so those two need to be a radio button
- once a link is emailed to someone, the email is visible next to the share link for that email
- additional emails can be sent for each share link, so more than one recipient can get the link
- the share link can be removed with an "x", which deletes the share link and all options
- once an email address is added, that email 
- a new button on the bottom allows you to add a new share link, which scrolls the sidebar and presents the same options to create a new share link
- share links allow you to set a label to name them (with a specific link description) so you can remember which link goes with what, and makes it easier to manage and remove links in the future

Note: at the same time, we should merge files_drop capabilities into this part of sharing. 

Also note we need to update the desktop and mobile apps to be able to take advantage of this new capability, so the share the sharing API also needs to work with these options.

**Comment by jancborchardt** [comment]
I would strongly suggest we combine this with my longstanding proposal to be able to share directly to email adresses, with automatically generated individual links. This will make it nicely integrated.

**Comment by rullzer** [comment]
Linking https://github.com/owncloud/core/pull/15459 here.
We might also want (with this) to have expiration of regular shares.

**Comment by rullzer** [comment]
@jancborchardt agreed. That should be easy then. And we can just add the link share to the list of link shares with a comment like. 'shared to <EMAIL>' so the owner still remembers what the link share was for.

**Comment by jancborchardt** [comment]
@rullzer it will simply appear in the list of shares. No need for a separate list of link shares.

**Comment by drzraf** [comment]
@rullzer I've a use-case where I do need to share one object using multiple share-links but I don't want to rely upon ownCloud automatic email. I need to write and send the email myself.

**Comment by canguruhh** [comment]
I also need this feature including a way to add this kind of shares via the shares api. Actually I figured out that only one share is allowed after lots of debugging on my not working share creation api requests.

**Comment by moritzha** [comment]
Is there a chance to get this feature with 10.0?
Beside multiple shares which can expire on different days, this will also give the shares names. This gives the ability to see who (which link) has uploaded or deleted a file on the server in the activity stream.
I think this will improve the work with external users and partners a lot.

**Comment by felixheidecke** [comment]
@moritzha Its a 10.0 milestone.

**Comment by PVince81** [comment]
Done in 10.0. Please try out 10.0 beta1 to see it in action.
