### ISSUE TITLE
PROPFIND answer doesn't include encoding.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22326]
### Steps to reproduce

1. Do a propfind to the oc server:

Having a file called propfind.txt like this 
```
<?xml version="1.0"?>
<a:propfind xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns">
</a:propfind>
```
and curl and xmllint installed do:

```
curl -X PROPFIND -H "Content-Type: text/xml" --data-binary "@propfind.txt"  http://USER:PASSWORD@HOST/remote.php/webdav/ | xmllint --format -
```

### Expected behaviour
The first line answered should be:
```xml
<?xml version="1.0" encoding="utf-8"?>
```

### Actual behaviour
But it is:
```xml
<?xml version="1.0"?>
````

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.10","versionstring":"9.0 pre alpha","edition":"Enterprise"}

Working correctly in 8.2.2.

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```

**Comment by PVince81** [comment]
Thanks. I've traced it back to Sabre's XML serializer update, raised here https://github.com/fruux/sabre-dav/issues/776

**Comment by PVince81** [comment]
@davivel does this break any parsers ? (Android, etc)

**Comment by davivel** [comment]
iOS at this point.

**Comment by rperezb** [comment]
JYI, fixed within the iOS app on https://github.com/owncloud/ios/tree/support_oc9_propfind

**Comment by PVince81** [comment]
According to @evert if you specify no encoding it defaults to utf-8, so should work fine.

So it turns out the problem was not encoding but the format of the PROPFIND request that was done in the iOS client: it still used multiple `a:prop` elements instead of a single one. Since 9.0 and Sabre 3.0, it only allows a single element.

The Webdav spec also states that only a single element must be used: http://www.webdav.org/specs/rfc2518.html see section 8.1.1

Not a core issue, closing

**Comment by davivel** [comment]
Thank you @PVince81
