### ISSUE TITLE
Support for string ids (file ids, etc)

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22330]
Follow up of https://github.com/owncloud/core/issues/20401 and https://github.com/owncloud/core/issues/20394 regarding string id discussion

@DeepDiver1975 @icewind1991 @karlitschek

**Comment by PVince81** [comment]
@DeepDiver1975 was there any update on this discussion ?

Moving to 9.2

**Comment by PVince81** [comment]
@DeepDiver1975 @butonic moving to backlog for now, not sure where we are with the discussion about string ids but this is still a huge task with big potential for regressions.

**Comment by butonic** [comment]
will give us headaches with functions like Cache::get() that allow int and string. Personally, I would be happy to get rid of them.

If we use strings we need to add the storage to the primary key, because with strings we no longer have an autoincrement column that we can use to spit out the next fileid. Instead we have to move that logic to the storage. a fallback might be a uuid ... but maybe there are better alternatives.

**Comment by guruz** [comment]
I would stay with string. Although one could have "Id" as string but "fileid" as numeric also in future.
