### ISSUE TITLE
Add pull_request_template.md file

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22486]
Seems that it's supposed to work, see https://github.com/dear-github/dear-github/issues/125#issuecomment-185326859

So let's use this shiny new feature :smile: 

Any suggestions what to put in ?

I'd suggest something like:

```
DESCRIPTION

Fixes BUG_NUMBER

TEST CASE LIST

Please review $REVIEWERS
```

Should we add a note about the review process or checkboxes ?
For example:
- [ ] reviewed by at least two people
- [ ] contains unit tests
- [ ] passes CI

@karlitschek @jospoortvliet @LukasReschke @oparoz @jancborchardt @DeepDiver1975 @rullzer @nickvergessen @VicDeo @icewind1991 @schiesbn

**Comment by jancborchardt** [comment]
Yep, sounds good! I would maybe add: Descriptive title, not only reference to issue ID

**Comment by LukasReschke** [comment]
:+1:

**Comment by LukasReschke** [comment]
We can also use hidden text there, see https://github.com/owncloud/core/pull/22487 for an example :smile:

**Comment by oparoz** [comment]
I don't think "passes CI" is necessary since there is a big block just for that at the end of the conversation.
Regarding tests, all PRs should include tests, so I don't think it should be mentioned.
And the "reviewed" checkbox I think is replaced by the "to release" label used as soon as the number of thumbs up has been reached.

But, a TODO section would be useful. In there, there can be a checkbox for tests, to make sure they're not forgotten.
Maybe there could also be an entry mentioning documentation. Something like "Documentation has been created or is not needed"

**Comment by nickvergessen** [comment]
Id add documentation as well to the list, either requires change, requires new documentation or nothing.
But it helps to remember the docs topic

**Comment by nickvergessen** [comment]
Btw as per help page, the files (issue_template, pull_request_template and contribution) can also be in a `.github` folder, so they don't clutter the root directory.

If we make sure packaging kills the file or folder this should be fine.

**Comment by TalAter** [comment]
This might help:
https://www.talater.com/open-source-templates/
