### ISSUE TITLE
Federated shares accepted and not displayed

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#22721]
### Steps to reproduce
1. UserA (serverA, https not trusted) shares a file with UserB (serverB, http)

### Expected behaviour
UserA can not share the file with userB, or, if UserA can, UserB accepts and views the file. 

### Actual behaviour
UserA sees the file as shared with UserB
User B can accept the file but does not see the file

### Server configuration
ServerA: {"installed":true,"maintenance":false,"version":"9.0.0.13","versionstring":"9.0.0 beta 2","edition":""}
ServerB: {"installed":true,"maintenance":false,"version":"9.0.0.13","versionstring":"9.0.0 beta 2","edition":""}

Both of them have the API Share enabled and can accept and receive federated shares.

**Comment by PVince81** [comment]
Do you mean it's missing an error message ?

**Comment by jesmrec** [comment]
I mean it is not correct that the user who shares is viewing the file as shared (all is right in his side, no errors, no negative feedback), and the sharee does not see the file. Either Both or any should view it in this case.

An error message would be right whether user2 would not view the shared file

**Comment by Gummikavalier** [comment]
I'm having this issue too. Here is my experience about the problem so far:

I have three separate ownCloud instances: two CentOS7 (PHP 5.6.19 and using LDAP) and one Ubuntu 14.04 (PHP 5.5.9, local user accounts).

Ubuntu setup works fine with federated shares.

CentOS ones have had this issue since OC 9.0.0, and now in 9.0.1 (while OC 8.2.x was fine). One of these instances is new; it was installed directly in version 8.2.2, so it hasn't been able to collect lots of cruft yet.
Users of these two CentOS instances can share files using Federated ID, but they don't see any new federated shares from CentOS or Ubuntu instance.

Receiving users get notifications via browser notifications (if allowed in browser). The information in this notification (path and filename) shows correctly, but the file does not become visible in actual browser view. The file does not sync via owncloud client either.

Thus the only indication that someone is trying to share to user using FID, is the notification via browser / operating system integrated notification system. Users do not get the normal "do you want to accept this share?" inquiry at all.

**Comment by PVince81** [comment]
Seems to work fine in 9.0.2 and 9.1.0
