### ISSUE TITLE
Make it possible to unshare all shares, or a subset, in one click

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22732]
**User type**: Logged-in

**User level**: All
### Description

From 9.0, all reshares are shown in the owner's sharing tab and there is no visual distinction between shares and reshares. Owners can only guess to which of their sharee a specific reshare belongs to (if a sharee reshares outside of the group and so on)

A, B and C belongs to group1
B and D belong to group2
C and F belong to group3

A shares with B who shares with D (group2)
A shares with C who shares with F (group3)

A now sees B, C, D and F in the list of shares, but has no idea who D and F are.
A removes share from B, but doesn't know who B has shared with, so can't decide if D and F should stay or go.
#### Proposition
1. Allow a file owner to remove all shares and reshares in one go by ticking a box. Wasn't it like that prior to 9.0?
2. Group reshares under each top share in a collapsible tree view (one level only)
3. Allow a file owner to remove one share and all its reshares (a branch of the tree) in one go by ticking a box instead of having to pick individually
### Benefit / value

Making the life of sharers easier, by grouping shares to be able to quickly identify the top shares and letting owners perform some actions in one click.

---

@rullzer @PVince81 @MorrisJobke @schiesbn @jancborchardt

**Comment by PVince81** [comment]
@owncloud/designers @MTRichards @karlitschek

**Comment by schiesbn** [comment]
> A removes share from B, but doesn't know who B has shared with, so can't decide if D and F should stay or go.

This implies that the decision if a share should stay or go depends on the re-share hierarchy. I don't see how this is the key factor. As the owner I see that my file is shared with B, C, D, F. If I decide that I no longer want to share my file with B, I remove it. The owner will decide the same regarding C, D and F. Don't see how this depends on the question who created the share in the first place.

> Allow a file owner to remove all shares and reshares in one go by ticking a box. Wasn't it like that prior to 9.0?

A "remove all shares" button sounds like a interesting idea for a large list of shares. But I have to agree with @rullzer that at the moment I don't see that the list become that large. Still we could implement the button and maybe only shows it if the list of shares is larger then X shares.

> Group reshares under each top share in a collapsible tree view (one level only)

I don't think this clutters the interface to much. But because we have the information who created the share we could show this information on hover.

> Allow a file owner to remove one share and all its reshares (a branch of the tree) in one go by ticking a box instead of having to pick individually

As said above. I think that's a to technical view. From a user point of view I don't think a decision is taken like "oh, the file was shared to user C by user B so I want to remove it, if the file would have been shared to user C by user D I would have kept it." I think the real world decision is linear like: B -> no, C->yes, D->no

**Comment by schiesbn** [comment]
> From my point of view, A should never see BB, BC or BD in his list of reshares.

Is it the case?

Yes, A will not see the shares on server B. That's because technically federated sharing works different. Once the webdav mount is established for BB there is no communication if between the servers if BB shares the file locally or not. What we might do in the future for performance reasons is:

- User A on Server A shares a file with user B on server B
- User B on Server B shares the file with user C on server C

Now we don't create a federated share between B and C but ask A to create a share directly to C so that you don't have to go through multiple servers to reach a file. In this case user A will see that the file is now also shared with user C. But that's just a idea for the future to improve performance.

**Comment by oparoz** [comment]
Thanks. I remember that direct share conversation :)

**Comment by PVince81** [comment]
backlog for now

@pmaier1
