### ISSUE TITLE
External storages will be marked unavailable until manually checked

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#22790]
With #20920 (specifically 2e3a5ccaaa1a64617980cd086a3dc13a9058892b) code was added such that any external storages that are marked as unavailable will be fake-mounted using FailedStorage, instead of the real storage. This was probably done so that the red row highlight works properly, which will trigger a storage recheck when the root files view of the web UI is loaded asynchronously through `StorageService::updateStorageStatus()`. However, that code will not run if the storage is only accessed through the DAV interface, or even if the root files view is never loaded (I think, not entirely sure on that point).

When a storage is marked as unavailable, it should still be mounted into the filesystem, so that the filesystem can decide to recheck the availability if the recheck TTL has expired. A storage should never be prevented from being mounted based on its availability.

cc @icewind1991 @PVince81

**Comment by Xenopathic** [comment]
@owncloud/qa You might be able to test this, by setting up an external storage, intentionally marking it as unavailable (with an expired TTL, or just wait 10 minutes for the TTL to expire itself) then only access the storage through the WebDAV interface. Expected behaviour is that the storage comes back online, predicted actual behaviour is the storage never comes back until the web UI is loaded.

**Comment by PVince81** [comment]
Confirmed. I had to apply https://github.com/owncloud/core/issues/22774 to make it properly transition to the unavailable state.

An easier way to reproduce this:

1. Setup a SMB storage as "/smb"
1. Change the oc_storages table and set "available" to 0 for the SMB storage
1. Do a PROPFIND on "/smb"

Expected: since the SMB storage is working and "last_checked" is NULL, it should automatically detect that it's available again and reset the flag

Actual: the PROPFIND does not make it recheck availability. One has to go through the web UI for an explicit check.

@icewind1991 please have a look.

**Comment by PVince81** [comment]
@cmonteroluque another critical regression

**Comment by PVince81** [comment]
@Xenopathic I raised a QA issue for this kind of cases: https://github.com/owncloud/QA/issues/166

**Comment by icewind1991** [comment]
Fix is here: https://github.com/owncloud/core/pull/22816
