### ISSUE TITLE
Introduce developer certificates for signing apps

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22798]
In order to sign an app today, we have to generate an app CSR, submit it to ownCloud for approval and use the returned certificate in `./occ integrity:sign-app`. See https://doc.owncloud.org/server/9.0/developer_manual/app/code_signing.html for all the details.

This is quite a limiting process as every single app has to be disclosed and submitted to ownCloud. There is also one drawback in which every single app every written by a rogue developer has to have its certificate revoked instead of just revoking the dev's certificate.

Also, in most mobile programmes, developers generate keys they can use for an unlimited number of apps. The policing happens in the app store itself.

For these reasons, I suggest either introducing or even replacing app-based certificates with developer based ones.

----
@karlitschek @DeepDiver1975 @LukasReschke @PVince81 @MorrisJobke @schiesbn @nickvergessen @BernhardPosselt

**Comment by LukasReschke** [comment]
This was actually done because of the threat model behind the code signing. Basically we wanted to ensure that even if the appstore gets hacked an adversary could not publish updates for signed applications.

With developer certificates this is pretty much not possible. We simply don't know which certificate is valid for what application and just assuming "it always will be the same" like Android does is also not super practical considering that somebody might loose access to their keys. (with the current model we can issue a new one)

While not perfect it is how it is at the moment. But since signing is optional and we're pretty fast in issuing the certificates (just post a CSR and we'll take action on this ASAP) I consider this acceptable behaviour for now… at least until we have not found a solution that would also work with an hacked appstore ;)
