### ISSUE TITLE
Missing dependency (php5-pdo) in 7.0.13RC1 CentOS 7 package.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22853]
### Observed behaviour

Installation of community package owncloud for CentOS 7 from isv:ownCloud:community:7.0:testing.repo

Server can't start due of a missing dependency.

### Server configuration
**Operating system**:
CentOS 7

**Web server:**
Apache

**Database:**
None at that point.

**PHP version:**
5.4.16

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"9.0.0.16","versionstring":"9.0.0 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
Yes in serverA.

**Logs**

```
{"app":"PHP","message":"Class 'PDO' not found at \/var\/www\/html\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DriverManager.php#148","level":3,"time":"2016-03-04T10:37:54+00:00"}
```

cc @jnweiger

**Comment by jnweiger** [comment]
Fixed in isv:ownCloud:community:7.0:testing/owncloud :

<pre>
--- owncloud.spec       (revision 21)
+++ owncloud.spec       (working copy)
@@ -83,7 +83,7 @@
 Group:          Productivity/Networking/Web/Utilities
 
 %if 0%{?fedora_version} || 0%{?rhel_version} >= 600 || 0%{?centos_version} >= 600
-Requires:       httpd sqlite php php-json php-mbstring php-process php-xml php-zip
+Requires:       httpd sqlite php php-json php-mbstring php-process php-xml php-zip php-pdo php-gd
 %if 0%{?rhel_version} > 600 || 0%{?centos_version} > 600
 # OBS for centos 6: error: unpacking of archive failed on file /var/run/httpd: cpio: mkdir failed
 BuildRequires:  httpd
</pre>

**Comment by jnweiger** [comment]
build success at https://build.opensuse.org/package/show/isv:ownCloud:community:7.0:testing/owncloud
publishing started...

**Comment by jnweiger** [comment]
Publishing finished. New versions are available at https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3A7.0%3Atesting&package=owncloud

**Comment by SergioBertolinSG** [comment]
Tested and works correct.
