### ISSUE TITLE
CalDAV for Android on 9.0 does not find any calendar

### ISSUE THREAD

**Issue by willyaranda** [owncloud/core#22891]
### Steps to reproduce
1. Update from 8.2.2 to 9.0RC1

### Expected behaviour
Calendars should work on CalDAV for Android

### Actual behaviour
Calendars are not available

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
80.28.189.65 - - [06/Mar/2016:16:38:09 +0100] "PROPFIND /.well-known/caldav HTTP/1.1" 302 154 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - - [06/Mar/2016:16:38:09 +0100] "PROPFIND /remote.php/caldav/ HTTP/1.1" 401 367 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - willyaranda [06/Mar/2016:16:38:09 +0100] "PROPFIND /remote.php/caldav/ HTTP/1.1" 207 560 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - - [06/Mar/2016:16:38:10 +0100] "PROPFIND /remote.php/caldav/principals/users/willyaranda/ HTTP/1.1" 401 367 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - willyaranda [06/Mar/2016:16:38:10 +0100] "PROPFIND /remote.php/caldav/principals/users/willyaranda/ HTTP/1.1" 404 211 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - - [06/Mar/2016:16:38:10 +0100] "PROPFIND / HTTP/1.1" 405 166 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - - [06/Mar/2016:16:38:10 +0100] "PROPFIND / HTTP/1.1" 405 166 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
```

#### ownCloud log (data/owncloud.log)
```
nothing shown
```

#### Browser log
```
20160306T153808Z I org.dmfs.caldav.autheticator.AuthenticatorActivity calendar discovery log:
20160306T153809Z V org.dmfs.dav.Dav get principal /.well-known/caldav
20160306T153809Z V org.dmfs.dav.Dav following redirect to https://cloud.pijusmagnificus.com/remote.php/caldav/
20160306T153810Z I org.dmfs.dav.Dav found principal: /remote.php/caldav/principals/users/willyaranda/
20160306T153810Z V org.dmfs.dav.CalDav get calendars https://cloud.pijusmagnificus.com/remote.php/caldav/principals/users/willyaranda/
20160306T153811Z V org.dmfs.dav.methods.DavPropFind Status: 404
20160306T153811Z V org.dmfs.dav.methods.DavPropFind <?xml version="1.0" encoding="utf-8"?>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
20160306T153811Z V org.dmfs.dav.methods.DavPropFind   <s:sabredav-version>3.0.7</s:sabredav-version>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind   <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind   <s:message>Principal with name users not found</s:message>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind </d:error>
20160306T153811Z V org.dmfs.dav.CalDav looking for calendars in 
20160306T153811Z V org.dmfs.dav.methods.DavPropFind Status: 405
20160306T153811Z V org.dmfs.dav.methods.DavPropFind <html>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind <head><title>405 Not Allowed</title></head>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind <body bgcolor="white">
20160306T153811Z V org.dmfs.dav.methods.DavPropFind <center><h1>405 Not Allowed</h1></center>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind <hr><center>nginx</center>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind </body>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind </html>
20160306T153811Z V org.dmfs.dav.CalDav additionally looking for calendar in 
20160306T153811Z V org.dmfs.dav.methods.DavPropFind Status: 405
20160306T153811Z V org.dmfs.dav.methods.DavPropFind <html>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind <head><title>405 Not Allowed</title></head>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind <body bgcolor="white">
20160306T153811Z V org.dmfs.dav.methods.DavPropFind <center><h1>405 Not Allowed</h1></center>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind <hr><center>nginx</center>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind </body>
20160306T153811Z V org.dmfs.dav.methods.DavPropFind </html>

App: org.dmfs.caldav.lib
App version: 0.4.27
OS version: 23
OS Info: oneplus/bacon/A0001:5.1.1/LMY48B/YOG4PAS1N0:user/release-keys
Manufacturer: OnePlus
Date: Sun Mar 06 16:38:14 GMT+01:00 2016
```

This happened after #22876 

@georgehrke, @DeepDiver1975, @cmonteroluque and @MorrisJobke as you commented on my other report.

**Comment by willyaranda** [comment]
(If you need more data from the server, it's on the #22876 issue, as I haven't changed anything)

**Comment by karlitschek** [comment]
@DeepDiver1975 @georgehrke

**Comment by georgehrke** [comment]
@willyaranda Did you use android as a client before the update to 9.0 or did you setup the client after the  upgrade?

**Comment by willyaranda** [comment]
@georgehrke both. I had my client set up since owncloud 6 or 7, without any problems on upgrading. When I updated on Friday, it stopped syncing and trying to select the calendars to sync shown no calendars available.

I deleted the account, try to add a new one, but that's the error that I have.

So I have tried both environments: upgrade and new setup.

**Comment by georgehrke** [comment]
Can you check if you can setup the client when you use `remote.php/dav/` instead of `remote.php/caldav/`?

**Comment by willyaranda** [comment]
@georgehrke that works, I can see my 3 calendars.

```
80.28.189.65 - - [06/Mar/2016:17:04:13 +0100] "PROPFIND /remote.php/dav/ HTTP/1.1" 401 426 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - willyaranda [06/Mar/2016:17:04:14 +0100] "PROPFIND /remote.php/dav/ HTTP/1.1" 207 632 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - - [06/Mar/2016:17:04:14 +0100] "PROPFIND /remote.php/dav/principals/users/willyaranda/ HTTP/1.1" 401 426 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - willyaranda [06/Mar/2016:17:04:14 +0100] "PROPFIND /remote.php/dav/principals/users/willyaranda/ HTTP/1.1" 207 845 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - - [06/Mar/2016:17:04:14 +0100] "PROPFIND /remote.php/dav/ HTTP/1.1" 401 426 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - willyaranda [06/Mar/2016:17:04:15 +0100] "PROPFIND /remote.php/dav/ HTTP/1.1" 207 435 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - - [06/Mar/2016:17:04:15 +0100] "PROPFIND /remote.php/dav/calendars/willyaranda/ HTTP/1.1" 401 426 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - willyaranda [06/Mar/2016:17:04:16 +0100] "PROPFIND /remote.php/dav/calendars/willyaranda/ HTTP/1.1" 207 6653 "-" "CalDAV-Sync/0.4.27 (OnePlus; bacon; Android 6.0.1; es_ES; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
80.28.189.65 - willyaranda [06/Mar/2016:17:04:23 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 386 "-" "Mozilla/5.0 (Macintosh) mirall/2.1.1"
```

**Comment by willyaranda** [comment]
I'm using nginx, and the first redirection comes from:

```
location / {
        rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

        rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
        rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;

        rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;

        try_files $uri $uri/ index.php?$args;
    }
```

**Comment by georgehrke** [comment]
```
rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;
```
should be the following for ownCloud 9.0 (cc @carlaschroder)
```
rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;
```

**Comment by willyaranda** [comment]
Yeah, I have seen this:

https://doc.owncloud.org/server/9.0/admin_manual/installation/nginx_configuration.html

But on 7.0 (for example), is different.

https://doc.owncloud.org/server/7.0/admin_manual/installation/nginx_configuration.html

**Comment by RealRancor** [comment]
@willyaranda Sure, thats why you should use the nginx config matching your oC version. :-)

**Comment by willyaranda** [comment]
@RealRancor  ok, so it should be clearly stated on the announcement blog post :) As I think people usually just updates owncloud and not updates the Apache/nginx configuration. Just my 0.02 cents.

Thanks for all guys!

**Comment by willyaranda** [comment]
(please, consider closing if nothing else is needed, all clear from my side)

**Comment by georgehrke** [comment]
Ideally we would implement a check for the admin site that checks if the redirect is correct

**Comment by RealRancor** [comment]
@willyaranda AFAIK nginx is not officially supported.

@georgehrke Such a check was implemented by @MorrisJobke in https://github.com/owncloud/core/pull/21562

@willyaranda Have you seen such an info/warning in your admin backend of oC 9?

**Comment by willyaranda** [comment]
@RealRancor no, no info/warning.

Anyway, on https://doc.owncloud.org/server/9.0/admin_manual/installation/nginx_configuration.html or older versions, it is not said that nginx is not supported. It has been correctly working for me since I started using owncloud, 3 years ago or so.

**Comment by georgehrke** [comment]
As far as I can tell from the code it only checks if there is a redirect, but not where the client is redirected to.

**Comment by karlitschek** [comment]
We should implement a check then. No one reads blogs or documentation anyways.

**Comment by RealRancor** [comment]
@willyaranda ``Web server: Apache 2`` from https://doc.owncloud.org/server/9.0/admin_manual/installation/system_requirements.html#supported-platforms

nginx is also working for me since ages, still it doesn't mean its supported. :-)

> We should implement a check then. No one reads blogs or documentation anyways. 

Yes, thats true.

**Comment by aspdye** [comment]
Oh guys ... I see lots of crying people tomorrow and in the coming weeks with calendar and contacts migration problems :fearful: :sweat_smile:

**Comment by RealRancor** [comment]
> As far as I can tell from the code it only checks if there is a redirect, but not where the client is redirected to.

> We should implement a check then. No one reads blogs or documentation anyways. 

Follow-up for this in https://github.com/owncloud/core/issues/22941

**Comment by devuan2** [comment]
Just upgraded from 8.2 to 9.0. Calendar is borked from Lightning plugin. I'm using apache and redirecting to SSL by default. No other rewrites. I'm assuming from the above that I need to add a rewrite rule in sites-enabled/default-ssl.conf to make the calendar work?

**Comment by oliv3r** [comment]
I upgraded last weekend and similar like the original bug report keep getting 405 errors.

If the orignal issue is not exactly related to this i'll open a new one, but the description and symptoms look the same.

Using cadaver I can connect to owncloud fine, but then I get 405 errors.
% cadaver http://owncloud.fdqn.tld/remote.php/dav [0]
Authentication required for sabre/dav on server `owncloud.fdqn.tld':
Username: oliver
Password:
dav:/remote.php/dav/> cd calendars 
lsdav:/remote.php/dav/calendars/> ls
Listing collection `/remote.php/dav/calendars/': failed:
405 Method Not Allowed

Both owncloud's log and apache mention this
Exception: {"Message":"HTTP\/1.1 405 Listing members of this collection is disabled","Exception":"Sabre\\DAV\\Exception\\MethodNotAllowed","Code":0,"Trace":"#0 \/var\/www\/owncloud.fqdn.tld\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(195): Sabre\\DAVACL\\AbstractPrincipalCollection->getChildren()\n#1 \/var\/www\/owncloud.fqdn.tld\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(857): Sabre\\DAV\\Tree->getChildren('calendars')\n#2 \/var\/www\/owncloud.fqdn.tld\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(911): Sabre\\DAV\\Server->addPathNodesRecursively(Array, Object(Sabre\\DAV\\PropFind))\n#3 \/var\/www\/owncloud.fqdn.tld\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(336): Sabre\\DAV\\Server->getPropertiesForPath('calendars', Array, 1)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPropFind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud.fqdn.tld\/htdocs\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/var\/www\/owncloud.fqdn.tld\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n#7 \/var\/www\/owncloud.fqdn.tld\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/var\/www\/owncloud.fqdn.tld\/htdocs\/apps\/dav\/appinfo\/v1\/caldav.php(75): Sabre\\DAV\\Server->exec()\n#9 \/var\/www\/owncloud.fqdn.tld\/htdocs\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#10 {main}","File":"\/var\/www\/owncloud.fqdn.tld\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAVACL\/AbstractPrincipalCollection.php","Line":95,"User":"oliver"}

ssl_error_log
[Thu Mar 31 08:23:55.875583 2016] [authz_core:error] [pid 8061:tid 140323518850816] [client ::1:33996] AH01630: client denied by server configuration: /var/www/owncloud.fqdn.tld/htdocs/data/.ocdata

ssl_access_log
::1 - - [31/Mar/2016:08:24:01 +0200] "PROPFIND /remote.php/dav/calendars/oliver/defaultcalendar/ HTTP/1.1" 401 355
::1 - oliver [31/Mar/2016:08:24:11 +0200] "PROPFIND /remote.php/dav/calendars/oliver/defaultcalendar/ HTTP/1.1" 401 283
.1" 401 283
::1 - oliver [31/Mar/2016:08:24:11 +0200] "PROPFIND /remote.php/dav/calendars/oliver/work/ HTTP/1.1" 401 283
::1 - oliver [31/Mar/2016:08:24:17 +0200] "PROPFIND /remote.php/dav/calendars/oliver/work/ HTTP/1.1" 401 283

data is an NFS share owned by apache:apache (the default webuser) so should be accessable just fine.
.ocdata is a 0 byte file the share: -rw-r--r-- 1 81 81 0 3 nov 17:27 .ocdata (where 81 is the other servers apache user).

Server configuration
Operating system: Gentoo
Web server: apache 2.4
Database: pgsql
PHP version: 5.6.19
ownCloud version (see ownCloud admin page): 9.0
Updated from an older ownCloud or fresh install: 8.2.2

My apache2 config is pretty 'standard' I would think and tries many combinations of settings, but my final version is from https://doc.owncloud.org/server/9.0/adm ... figuration

DocumentRoot "/var/www/owncloud.fqdn.tld/htdocs"
Alias /owncloud "/var/www/owncloud.fqdn.tld/htdocs/"
<IfModule mod_headers.c>
Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
</IfModule>
<Directory "/var/www/owncloud.fqdn.tld/htdocs">
Options +FollowSymLinks
AllowOverride All
Require all granted
<IfModule mod_dav.c>
Dav off
</IfModule>
SetEnv HOME /var/www/owncloud.fqdn.tld/htdocs"
SetEnv HTTP_HOME /var/www/owncloud.fqdn.tld/htdocs"
</Directory>

rewrite rules are from .htaccess and point the the correct remote.php/dav/ so that's not it either.

So I'm guessing I am missing some configuration bit somewhere or have something slightly wrong.
