### ISSUE TITLE
Make Tags deletable, after the last file tagged with was deleted

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#22942]
### Steps to reproduce
1. Tag files with the tag "example"
2. Remove all Files with the Tag "example"
### Expected behavior

Tag "example" should disappear in the "Select tags to filter by"-field
### Actual behavior

It does not :unamused:

**Comment by PVince81** [comment]
9.0 RC3 I guess?

**Comment by PVince81** [comment]
This could be implemented as a cleanup bkg job that deletes all tags that aren't assigned to anything.

@karlitschek

**Comment by aspdye** [comment]
enhancement or bug?

**Comment by nickvergessen** [comment]
@PVince81 you shall not delete tags in a background job, since there are apps that might depend on them!

We already discussed that in the past. While for CE and atm pruning would be fine, it would be crucial for the known cases.

Anyhow, shouldn't admins be able to delete via the dropdown, when editing a tag?
