### ISSUE TITLE
SFTP External Storage not showing all directories on slow connection

### ISSUE THREAD

**Issue by benmichael** [owncloud/core#22948]
### Affected feature
External Storage

### Expected behaviour
When I browse to sftp external storage, I should see all my directories.  If the connection is too slow, the directories may be loaded asynchronously, but then there should be a "still loading" indicator.

### Actual behaviour
I see a subset of my directories

### Steps to reproduce
1. Create SFTP external storage
2. The SFTP server/mount point directory should have at least 30 directories/files
3. The connection to the SFTP should be slow (500kbps up)
4. Browse to the SFTP external storage directory
5. Inspect for missing directories/files

### Server configuration
Operating system: Ubuntu Linux 14.04

Web server: Apache2

Database: MariaDB

PHP version: 5.5

ownCloud version: 8.1.3

**Comment by PVince81** [comment]
Maybe it already timed out and gave up scanning, and only found a subset of the remote folder.

**Comment by benmichael** [comment]
While that may be what happened, I now get the same subset of directories every time I go to the remote directory's location.

I also have no problem connecting to the box via the command line and working with it there.  I have never received a partial result or a timeout on the commandline.

If something like a timeout happens, I would want to see an error message telling me that "oops couldn't get all the directories".  Otherwise I'm going to wonder what has happened to all the missing directories.

**Comment by PVince81** [comment]
I think you indeed got a timeout. But ownCloud wrote the "storage_mtime" of the main folder.
So next time it went to the SFTP storage it believed "oh I already have the latest since the mtime did not change", but it's wrong due to the timeout.

Not sure how to solve this accurately. It also depends whether the timeout happened on SFTP side or on PHP side. Usually when PHP times out, no further code can run so it is difficult to recover.

@icewind1991 maybe we should only update the parent's "storage_mtime" at the end of the scanning process, not the beginning ? Then in case of timeout, the second scan will still explore the unscanned folder again ?

**Comment by benmichael** [comment]
I believe that you are correct..  I created a file on the server in the root directory, and reloaded the directory in ownCloud, it immediately loaded everything.

Creating files in sub-directories did not fix the problem, only creating a file in the root directory of the "mount" fixed it.

Thanks a lot, looking forward to the fix.

**Comment by PVince81** [comment]
@benmichael a workaround for you would be to do a "touch" on the folder directly on SFTP to force its mtime to change. Then ownCloud should rescan it.

Another idea: `occ files:scan $userid` on the CLI with your user might help too

**Comment by PVince81** [comment]
Please try again with 9.0.3 RC1 or 9.1.0 beta2.
In these versions the ext storage scanning has been moved to a cron job, so now the web UI only scans the folder to be displayed without recursion. So the situation with half-scanned folders shouldn't happen any more.

**Comment by AnderCrafter** [comment]
the problem still persists
