### ISSUE TITLE
[Feature] Add functionality for tagging multiple files at once

### ISSUE THREAD

**Issue by moritzheiber** [owncloud/core#22969]
I absolutely :heart: the new tagging feature. Thank you for that! However, if you're already in the possession of a lot of files and you want to get a-taggin' it'll probably take you ages until you've manually tagged all your files properly if going through them in with the current, one-by-one UI.

I therefore file the request for adding the functionality of tagging multiple files at once, possibly through a search, a selection or even filetype.

It should probably at least cover selected files.

Thanks!

**Comment by LukasReschke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
This is very related to »Side-menu doesn't support multi-select« #19693

cc @PVince81

**Comment by programster** [comment]
I realize I'm probably in a minority on this one, but I always thought the UI for "Google Circles" was brilliant, and you could use the same concept for tags. This works well because you want to drop lots of people/files into different circles/tags at once, and often people/files belong in more than one cirlce/tag at a time.

**Comment by PVince81** [comment]
reopening as this is a valid feature request

**Comment by blue-kaleidoscope** [comment]
Hi, since this topic seems to be "frozen". Any updates?
