### ISSUE TITLE
Loading WebDAV takes one minute

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22975]
Not exactly sure why yet but after @danimo has upgraded his instance to 9.0 accessing the WebDAV interface takes more than one minute: https://blackfire.io/profiles/9487027b-0a32-4ad9-a24d-b8aeb3219454/graph

From what I can see it seems like the PROPFIND is also doing a PROPFIND in all DAV mounts and somehow this takes a lot of time… Mhm…

cc @icewind1991

**Comment by PVince81** [comment]
Retry with the fix from https://github.com/owncloud/core/issues/22973 ?

**Comment by icewind1991** [comment]
This looks like a remote server being slow and not a problem on our side

**Comment by PVince81** [comment]
@LukasReschke @danimo has this improved with the recent patches ?

**Comment by PVince81** [comment]
Closing due to lack of feedback

**Comment by ZinkDifferent** [comment]
I can confirm that webDAV performance (on MacOS Finder) in Owncloud 9.1 is still slow as molasses.

Any hopes of improving this?

**Comment by PVince81** [comment]
Can you confirm that it is only slow with MacOS Finder but fast with other clients ? Because it could also be your server that is slow in general. Is it also slow for empty ownCloud accounts ?

Best would be to make a new ticket and describe your scenario in detail for the user that experiences the slowness (how many received shares ? server setup ?).

**Comment by ZinkDifferent** [comment]
Yes, Vincent, I can confirm.

When doing a webdav connection via macOS Finder, the connection is insanely slow, or times out (never completes).

When I perform the same connection with a different client (in this case, the Transmit FTP program, using webDAV connection), the connection is stable and as fast as my link allows.

On the server side, it is Ubuntu 16.04LTS and I use nginx 1.10.0, and PHP7 and I get the same behavior wether I have nginx configured for http1.1 or http2 responses (all installed via EasyEngine)

I suspect this is related to the issue that sabreDAV has observed a while back:

http://sabre.io/dav/clients/finder/ <http://sabre.io/dav/clients/finder/>

> Finder uses Transfer-Encoding: Chunked in PUT request bodies. This is a little used HTTP feature, and therefore not implemented in a bunch of webservers. The only server I've seen so far that handles this reasonably well is Apache + mod_php. Nginx and Lighttpd respond with 411 Length Required, which is completely ignored by Finder. This was seen on nginx 0.7.63. It was recently reported that a development release (1.3.8) no longer had this issue.

Apparently, this wasn’t addressed in nginx, or I am missing something else.

If you want, I can set up a VM for the purposes of testing and give you access.

**Comment by kdslkdsaldsal** [comment]
@ZinkDifferent Not quite sure if this is related to your posted quote:

IIRC this issue just has caused Finder to fail completely as the server hasn't accepted the PUT request at all (replied with the mentioned 411 Length Required instead).

**Comment by ZinkDifferent** [comment]
Yes, absolutely related.

What's odd is that Nginx used to be the only instance where this worked in the past (2-3 years ago) - though apparently something either changed with nginx or the owncloud implementation since then.

This is vexing as it, again renders it virtually useless when used for a Mac (WebDAV access is the whole point). 


__
ceci n'est pas un iPad

**Comment by kdslkdsaldsal** [comment]
> Yes, absolutely related.

Out of curiosity: How do you know? As already written if the webserver is not supporting Transfer-Encoding: Chunked in PUT request bodies the upload should fail completely instead of being slow.

**Comment by ZinkDifferent** [comment]
Good question - Nginx, allegedly, supports chunked requests. My earlier installation under ubuntu 14.04 and a manual install of Nginx did, and worked like a charm. 

In this new instance, ubuntu 16.04 and I installed Nginx using the EasyEngine tool. Makes it faster and includes php7 and Redis cache as well. 

Mind you, with all that fancy automation, it's possible that Nginx is configured differently than I had previously, or that the problem is caused by php7-fpm that it uses?

I just re-ran the same WebDAV transfers and they DO fail. They just sit there for up to 5 minutes before they fail - which I interpreted initially as awfully slow. 

Any ideas?

Mine ends with a '7'
Ceci n'est pas une pipe.

**Comment by kdslkdsaldsal** [comment]
@ZinkDifferent 

If the transfer is just failing the ticket here is probably the wrong place. I think its the best that you create a new issue and make sure that you fill out the issue template shown to provide all needed info about your environment.

Before creating such an issue you can also run litmus against the WebDAV interface of oC to make sure its not a setup / webserver / PHP issue:

https://central.owncloud.org/t/how-to-compile-and-run-litmus-on-debian-for-webdav-tests/839
