### ISSUE TITLE
Could not gather sufficient random data in random_bytes_mcrypt.php

### ISSUE THREAD

**Issue by renaudallard** [owncloud/core#22983]
PHP throws an error after upgrading to owncloud 9.0.0

### Steps to reproduce
1. Follow the steps to upgrade from latest owncloud 8 to owncloud 9.0.0
2. Try to access owncloud URL

### Expected behaviour
Owncloud should "start"

### Actual behaviour
There is a blank page and logs show:
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'Could not gather sufficient random data' in /owncloud/3rdparty/paragonie/random_compat/lib/random_bytes_mcrypt.php:69

### Server configuration
**Operating system**:
OpenBSD 5.8

**Web server:**
nginx 1.9.3

**Database:**
Mariadb 10.0.22

**PHP version:**
php-5.6.17

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Updated from an older ownCloud or fresh install:**
Upgraded from 8.2.2

**Where did you install ownCloud from:**
tar.gz archive

**Signing status (ownCloud 9.0 and above):**
N/A

**List of activated apps:**
default ones + calendar and contacts

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 44.0.2

**Operating system:**
Debian linux

#### Web server error log

FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'Could not gather sufficient random data' in /owncloud/3rdparty/paragonie/random_compat/lib/random_bytes_mcrypt.php:69

**Comment by renaudallard** [comment]
This looks like to be because that random_bytes_mcrypt.php cannot reach /dev/urandom because it runs in a chroot and even if urandom is created in the chroot, it could not be used because the mountpoint of the chroot has nodev attribute.

**Comment by LukasReschke** [comment]
This basically means that ownCloud is not able to generate secure random data and for security reason simply fails. (actually what you want is to have secure random data instead of living in a state of "generating potential insecure one")

The order behind reading random data as implemented by paragonie/random_compat in our used version 1.1.4 is:

1. fread() /dev/urandom if available
2. mcrypt_create_iv($bytes, MCRYPT_DEV_URANDOM)
3. COM('CAPICOM.Utilities.1')->GetRandom()
4. openssl_random_pseudo_bytes()

Using /dev/urandom is required for secure randomness, see also https://github.com/paragonie/random_compat/issues/91

**Comment by renaudallard** [comment]
reading random data does not seem to go further than your point 2 mcrypt_create_iv($bytes, MCRYPT_DEV_URANDOM)
I have no error using random_bytes_openssl.php for example
Using /dev/urandom is not required on every OS for secure randomness, while that might be true for linux.

**Comment by LukasReschke** [comment]
> Using /dev/urandom is not required on every OS for secure randomness, while that might be true for linux.

Filing an issue at https://github.com/paragonie/random_compat then with regard to the BSD specifics would likely be your best action point then. :wink:

**Comment by renaudallard** [comment]
Is paragonie random_compat responsible for trying all the steps you described formerly or is it owncloud choice to try in order:

1. fread() /dev/urandom if available
2. mcrypt_create_iv($bytes, MCRYPT_DEV_URANDOM)
3. COM('CAPICOM.Utilities.1')->GetRandom()
4. openssl_random_pseudo_bytes()

Because the last one should not fail.

**Comment by LukasReschke** [comment]
This is completely handled by random_compat (though in a newer version it also reads from libsodium)

Basically random_compat tries to check whether mcrypt is existent in https://github.com/paragonie/random_compat/blob/15220d8be718c3e12249c98767c00b4f92a387f0/lib/random.php#L122-L142:

```php

        /**
         * mcrypt_create_iv()
         */
        if (
            !function_exists('random_bytes')
            &&
            PHP_VERSION_ID >= 50307
            &&
            extension_loaded('mcrypt')
        ) {
            // Prevent this code from hanging indefinitely on non-Windows;
            // see https://bugs.php.net/bug.php?id=69833
            if (
                DIRECTORY_SEPARATOR !== '/' || 
                (PHP_VERSION_ID <= 50609 || PHP_VERSION_ID >= 50613)
            ) {
                // See random_bytes_mcrypt.php
                require_once $RandomCompatDIR.'/random_bytes_mcrypt.php';
            }
        }
```

From there it calls `mcrypt_create_iv($bytes, MCRYPT_DEV_URANDOM)` and since that fails the exception is thrown: https://github.com/paragonie/random_compat/blob/15220d8be718c3e12249c98767c00b4f92a387f0/lib/random_bytes_mcrypt.php#L70-L75

**Comment by renaudallard** [comment]
https://github.com/paragonie/random_compat/pull/94

**Comment by renaudallard** [comment]
Installing security/pecl-libsodium also solves the issue because random_compat does not try to use mcrypt anymore. However no such package exists for OpenBSD 5.8, so I created one here: https://arnor.org/OpenBSD/5.8/pecl-libsodium-1.0.2p1.tgz

**Comment by renaudallard** [comment]
Should be fixed here: https://github.com/paragonie/random_compat/commit/cb4b63fff6313e928556a9865ddaaf8daf0da0ec

**Comment by sbrl** [comment]
For others experiencing this issue, I found that it was the OVH / KimSufi kernel causing the issue. I've written up a quick guide on updating your kernel here:

https://starbeamrainbowlabs.com/blog/article.php?article=posts%2F221-Updating-OVH-Kernel.html
