### ISSUE TITLE
Add some Apps to the ownCloud Demo Instance 

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#23010]
I think we should put apps like "Calendar", "Contacts", "Mail" and maybe "Collabora CODE" in our demo.owncloud.org - instance to give people a good overview what ownCloud does :wink: 

cc @karlitschek

**Comment by LukasReschke** [comment]
cc @stp-ip

**Comment by stp-ip** [comment]
During the deploy I tried the reworked calendar, contacts apps and deemed them not suitable yet. As the mail app is still in beta, I haven't tried it during that deploy.
The demo had various production ready apps available before the release 7 I think.
Due to a decision from oC inc, only packaged apps were allowed on the demo. Therefore since this decision that was mostly the cause. I would have added contacts and calendar nevertheless, if they worked perfectly, but in my opinion they do not yet.

There was a plan to rework how the demo works and give each user their own instance so they can install apps from the app store, but this was deemed unimportant by oC inc. If there is more support for this, I will reiterate on the possibilities.

_Disclaimer: I am not employed by oC inc and the demo is provided by myself including all used resources and costs._
