### ISSUE TITLE
files_external: new storage created on config-path change, old one orphaned

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#23366]
### Steps to reproduce
1. Configure an external storage (e.g. local type) and enable sharing
2. Share a file on this storage
3. Edit the external storage's path
4. Open Files as sharee
### Expected behaviour

No exception appears in the log. No orphaned storage and related data is left over. Storage ID is renamed to the new path.
### Actual behaviour
1. An exception is logged (cf. https://github.com/owncloud/core/issues/22976#issuecomment-197842198)
2. Orphaned data is left in oc_share table, as well as a storage with id "local::/old/Path".
### Server configuration

**ownCloud version:** 9.0

**Comment by PVince81** [comment]
This likely happens in all ownCloud versions.

The problem is also one of semantic/intention: whenever an admin changes the path of a Local storage (or the root path of an SFTP storage), does the admin change it because it was:
1) misconfigured (maybe the admin was still typing and the storage auto-saved)
2) changed to a different storage
3) moved/renamed

I guess 1) and 3) are the most obvious ones, in which the same oc_storage entry should be reused.
And the UI must make it clear that to use a different storage one must not just change the settings but recreate a new entry.

Still tricky and risky.

**Comment by PVince81** [comment]
Some logic was added to automatically delete the most obvious cases when no `$user` variable is used.

If issue still reproducible with 10.0.4, pleses reopen.
