### ISSUE TITLE
# Files Migration

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#23562]
# ~~User~~ Files Migration
## Requirements

As an admin, I want to be able to migrate users between ownCloud servers so that employees can move between offices, retain their accounts, and still be able to use ownCloud in a reliable and performant manner.
With respect to files, shares, comments, tags, calendars and contacts any user migration can be seen as a duplication/sync from one server to another.
Give the fact that a user will be in maintenance mode during the migration time – this is a relative straight forward approach.

Feature description
Let’s implement this as a occ command for now (no timeout on execution and let effort with respect to UX and UI). 

```
./occ files:migrate-user <userid> <new-server>
```

This are the steps to be executed:
1. ask for admin credentials on the new server and verify them
2. create the new user on the new target server using provisioning api
3. set maintenance mode on the user on both systems – new oci api
4. transfer files using webdav
5. transfer shares using share api – maybe convert to fed shares
6. transfer comments and tags using webdav – unknown users for comments might appear
7. transfer calendars and contacts using webdav including shares – same issues as with file shares
8. remove maintenance mode on new server
9. optional: ask admin to kill all data of the user locally
## Open Questions
1. where do we get the password from? - since 8.2 we can reuse the hashed password
2. which auth backends do we support? - 
3. what to do with user name collision? - 
4. Consider different behavior with respect to os, database, file system – pure pain
5. public link changes on migration
6. group shares: groups are different on the other server
7. user shares: user exists? The same?
8. on calendar import we need to disable email processing
## Next Steps

Discuss scope of the feature and try to resolve open topics

**Comment by karlitschek** [comment]
please also see here for context: https://github.com/owncloud/enterprise/issues/686
Please note this this here is the authoritative ticket

**Comment by PVince81** [comment]
> transfer comments and tags using webdav – unknown users for comments might appear

If we implement comments that can be posted from fed ownClouds, then there will be the concept of "fed OC author" instead of local author. So when migrating comments, local author would become "fed OC authors".

**Comment by MTRichards** [comment]
To be created as part of the ./occ export using the APIs (for encryption and object stores)
- Tar File of the files and folders from primary storage via the API
  - Encryption exports can happen as long as the master key or recovery key is enabled
- Sharing report in two parts of two (what was shared with me, what I shared with others; internally, and as federated shares)
- External mount points listed as well

On the new server side, ./occ import using the APIs and the information from the tar file.
- Tar file is positioned on the new server, import is run on the import side
  - For encryption to work on this server too, master key must be enabled, and then it can work. Otherwise, the files are placed into the encrypted storage location as unencrypted files for that user. After the user has logged in to initialize the keys, the admin can run encrypt all for the user
- User files are imported into a separate folder in the user's new root folder, called imported files. (think also of object stores here).
- Import using files PHP API
- On import, when there is an error in the import, we need to write the broken imported files into a log file but don't stop, and then the command line can show x errors, see log file when it is complete.

NOTE: test the import of files while encryption is active without the use of encryption does not crash hard. Master should encrypt, we are talking about the case where there is no master key and files are imported unencrypted.

Limitation: We will lose activities, notifications (pending federated shares), trash bin and version information with this export. We will lose favorites, comments, tags and system tags. We lose personal settings. We lose app specific data.

App is called "Files Migration" not user migration. A command line response to this request before running the command line on an encrypted system with no master key has to indicate that the files will be stored unencrypted, that encrypt all needs to be run after the user has logged in for the first time to encrypt the files, and ask the admin if they want to continue (y/n). admin can abort.

**Comment by MTRichards** [comment]
Estimation: 1 week

**Comment by PVince81** [comment]
Feature didn't make it into 9.1, moving to 9.2 for now to reconsider.

@dragotin @DeepDiver1975

**Comment by DeepDiver1975** [comment]
Backlog from my pov

**Comment by dragotin** [comment]
Backlog. Smells like an error prone thing.... still useful. But yeah - fork - double work - half the guys.

**Comment by PVince81** [comment]
@pmaier1 @felixboehm

**Comment by PVince81** [comment]
closing in favor of the data exporter project: https://github.com/owncloud/data_exporter/
