### ISSUE TITLE
Add responsive design to the apps menu when using on low resolution displays

### ISSUE THREAD

**Issue by e-alfred** [owncloud/core#23691]
### Steps to reproduce
1. Log in to an Owncloud instance with a lot of apps/external sites installed/set up on a system with a small display (like 1366x768 which is extremely common with cheap monitors and lots of notebooks) and click on the apps menu in the left upper corner.

### Expected behaviour
The menu should change size (maybe adding more columns and less rows relative to the display size) so that all apps are seen by the user.

### Actual behaviour
The apps menu only shows a few rows with three columns. You have to zoom out to see all installed apps/external sites.

**Comment by LukasReschke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
@e-alfred not sure which version of ownCloud you are on, but there is a scrollbar in that menu since 8.2 I’m pretty sure (if not, 9.0 definitely). That makes it possible to view all the apps, because previously it was really a bug that you could not see all apps when you had a lot installed.

We shall not change the number of columns in that menu though because that results in not being able to spatially remember where an app was. For example, the Mail app is always the first entry in the second row for me. With a responsive change like the one you propose, this recognition would be way more difficult.
(This is also how mobile devices like the iPhone work and why they have specific homescreens instead of endless scrolling. You always know that a specific app is in the bottom left of the second screen, for example.)

cc @owncloud/designers

**Comment by e-alfred** [comment]
@jancborchardt Currently on 8.2.3. In 8.2, there is no scrollbar and the scroll wheel does nothing in that menu. On 9.0, I can use the scroll wheel, but no scrollbar is shown. This seems a bit unintuitive, but works.

**Comment by jancborchardt** [comment]
@e-alfred which browser do you use? Scrolling and scrollbar showing works perfectly here in 9.0 with both Chrome and Firefox.
