### ISSUE TITLE
Calendar: shared calendars have several problems after upgrade to OC 9.0.1

### ISSUE THREAD

**Issue by leez** [owncloud/core#23875]
1. Upgraded manually (from 8.2.3) to 9.0.0
2. Upgraded manually to 9.0.1

Result:
- Shared calendars not showing (in both CalDav client and Web UI) for users in groups that calendars were previously shared with.

From Admin/Calendar-Owner side:
- Share functionality not working (tried removing shared users/groups from calendars and re-sharing; can't remove or add; trash bin does nothing and no users/groups suggestions when typing in add box)
- Checkboxes to add Edit permissions are all newly unchecked, and checking them doesn't stick

3. Ran (for all users):

`sudo -u www-data php occ dav:migrate-addressbooks` and
`sudo -u www-data php occ dav:migrate-calendars`

- No apparent effect.

4. Updated oc_dav_shares table manually changing "users" to "groups" in "principaluri" field where row represents a calendar shared with a group.

- This made Shared calendars visible to users in groups that calendars were previously shared with. Yay, progress.

5. Updated oc_dav_shares table manually changing "access" field from "3" to "2"

- Users can now edit calendars. Yay, progress.

- Modifying checkboxes to add Edit permissions still doesn't stick
- Share functionality still not working; can't remove or add users/groups

### Server configuration
**Operating system**: Debian GNU/Linux 7 (wheezy)

**Web server:** Apache2

**Database:** mysql  Ver 14.14 Distrib 5.5.47

**PHP version:** PHP 5.4.45-0+deb7u2

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:** Updated from 8.2.3 to 9.0.0 to 9.0.1

**Where did you install ownCloud from:** tar.bz2 file

**Signing status (ownCloud 9.0 and above):** Verified

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**

Enabled:
  - calendar: true
  - contacts: true
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - updatenotification: 0.1.0

Disabled:
  - activity
  - comments
  - encryption
  - external
  - federation
  - files_external
  - files_pdfviewer
  - files_sharing
  - files_texteditor
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - gallery
  - notifications
  - provisioning_api
  - systemtags
  - templateeditor
  - user_external
  - user_ldap

```

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'ocd2a7ebe1d4',
  'passwordsalt' => 'REMOVED',
  'trusted_domains' => 
  array (
    0 => 'owncloud.eff.org',
  ),
  'datadirectory' => '/home/ocdata',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'ocuser',
  'dbpassword' => 'REMOVED',
  'installed' => true,
  'forcessl' => true,
  'defaultapp' => 'calendar',
  'logtimezone' => 'America/Los_Angeles',
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'secret' => 'REMOVED',
  'loglevel' => 2,

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No (not Owncloud's)

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:**

Firefox, Chrome

**Operating system:**

Ubuntu, OS X

**Comment by rocketnova** [comment]
@leez and I have made some progress on this issue. There are still problems, but the major ones seem to be resolved.

I traced the problem of being able to share calendars to a call to the `files_sharing` app. This was disabled in our install. Once I enabled and upgraded it, sharing calendars now seem to be fully functional.

Here's a summary of our issues:

- **STILL TRUE (since it's related to the upgrade process):** Shared calendars not showing (in both CalDav client and Web UI) for users in groups that calendars were previously shared with.
- **STILL TRUE (since it's related to the upgrade process):** Checkboxes to edit permissions are all unchecked after the upgrade.
- **FIXED:** Edit checkboxes are now taking effect and persisting.
- **FIXED:** Share functionality not working (tried removing shared users/groups from calendars and re-sharing; can't remove or add; trash bin does nothing and no users/groups suggestions when typing in add box)
- **NEW:** We are now getting the following log error everytime someone hits a keystroke when searching to find a person to share a calendar with:

````
{"reqId":"REMOVED","remoteAddr":"REMOVED","app":"OCP\\Share","message":"Sharing backend for principals not found","level":3,"time":"REMOVED","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=name&perPage=200&itemType=principals","user":"rocket"}
````

Is it possible that not having the files_sharing app enabled during the upgrade made it so that `sudo -u www-data php occ dav:migrate-addressbooks` and `sudo -u www-data php occ dav:migrate-calendars` had no effect?

Also, should the files_sharing app be a dependency of the calendar app?

**Comment by rocketnova** [comment]
To clarify:

The new "Sharing backend for principals not found" error log message is not preventing the calendar sharing from working. Sharing now seems fully functional, so I'm not really sure what this error message is trying to tell me. If it's helpful, the error seems to be coming from `lib/private/share/share.php`, but I'm not sure what is calling it and why it can't seem to find `core/apps/files_sharing/api/sharees.php`.

**Comment by jcharaoui** [comment]
I just upgraded from OC 8.2.3 directly to OC 9.0.1. Disabled the app before the upgrade. Downloaded it from the appstore on 9.0.1, and ran the upgrade routine. On my installation the shared calendars work fine using the web interface (including modifying a shared calendar). However, I can't access the through CalDAV at all. When I query the URL, it returns `500 Internal server error`. I also have several `Sharing backend for principals not found` errors in my logs, but I wasn't able to determine a link with this problem.

**Comment by jcharaoui** [comment]
After further investigating I found out about #23964, and fixed my problem by using the correct CalDAV URL. Sorry about the noise!

**Comment by PVince81** [comment]
@DeepDiver1975 any update ?

**Comment by DeepDiver1975** [comment]
from my pov and understanding all these issues are solved
