### ISSUE TITLE
Feature request: move ownership of calendars

### ISSUE THREAD

**Issue by koenlek** [owncloud/core#23894]
Since ownCloud 9, it is possible to transfer the ownership of files from one user to another. I would like to see something similar for calendars, to be able to fully disable an old account. It is not available in ownCloud 9.0.1. There is an occ command to migrate calendars:

```
sudo -u www-data php occ dav:migrate-calendars
```

But that is to migrate pre-owncloud 9 calendars to owncloud 9 (so from old app to new core). So that command is completely irrelevant to transferring/migrating calendars between users.

> I removed the issue template, as it seems irrelevant to this feature request.

**Comment by DeepDiver1975** [comment]
Moving the ownership will result in larger impact on any connected client because the the url will change. So I consider this rather critical.

From a technical point of view this is nothing more then changing the principalurl - https://github.com/owncloud/core/blob/master/apps/dav/appinfo/database.xml#L314
