### ISSUE TITLE
Hide security and settings warning

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/core#23957]
I'm using CloudFlare as shield for my ownCloud installation.
It only allows to set `Strict-Transport-Security` to 6 months max (15552000 seconds instead of desired 15768000). Generally I'm OK with current settings and how CloudFlare does it, but annoying warning keeps showing. I need the ability to hide it.

**Comment by MorrisJobke** [comment]
I would simply propose to lower this limit to the 6 months (30 days * 24 h * 60 minutes * 60 seconds = 15552000) instead of half a year (365 days / 2  * 24 h * 60 minutes * 60 seconds = 15768000).

@LukasReschke I think this is okay?

It's also better than introducing yet another setting. The warnings are there for a reason.

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/owncloud/core/pull/23958
