### ISSUE TITLE
CSS: 300px height of .summary makes footer of public link page look ugly

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#24235]
I've got feedback from an user:

> 300px height of .summary makes footer of public link page look ugly

<img width="845" alt="files_-_owncloud" src="https://cloud.githubusercontent.com/assets/214010/14780682/633b07a2-0ade-11e6-9fe5-4e847528786e.png">

**core/apps/files/css/[files.css](https://github.com/owncloud/core/blob/v8.2.3/apps/files/css/files.css#L658-L664):**

```
.summary {
	-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=30)";
	filter: alpha(opacity=30);
	opacity: .3;
	/* add whitespace to bottom of files list to correctly show dropdowns */
	height: 300px;
}
```

### Steps to reproduce
1. create public link for folder with many files
2. open public link in any browser
3. scroll down

### Expected behaviour
HTML layout shouldn't show unnecessary whitespace

### Actual behaviour
footer of public link page look ugly

### Server configuration
**ownCloud version:** (see ownCloud admin page)
8.2.3, 9.0.1, master

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
https://hub.docker.com/_/owncloud/

### Client configuration
**Browser:**
Chrome 50

**Operating system:**
Mac OS X 10.11.4

@jancborchardt Can you imagine a smarter solution for the future? /cc @MorrisJobke 

00005295

**Comment by PVince81** [comment]
The problem with the footer is that it required many compromises to make it work with all browsers, especially older IEs. Considering that in 9.1 we'll only support IE >= 11, then we might be able to find a more suitable and flexible solution for the footer logic.

@owncloud/designers

**Comment by PVince81** [comment]
Note that this might tie in with the scroll container discussion because they somewhat depend from each other: https://github.com/owncloud/core/issues/22347

**Comment by MorrisJobke** [comment]
mabye our frontend guys @Henni, @ErikPel or @skjnldsv wants to look into this CSS fiddling :)

**Comment by jancborchardt** [comment]
Sorry but I don’t understand the problem here.

> […] makes footer of public link page look ugly

What is meant by that? Is it too much? From the screenshot it looks fine. The whitespace is added so that even the last files are scrolled nicely into view and you don’t need to look all the way down on your monitor. Also it’s good feedback that it’s the end of the list.

**Comment by michaelstingl** [comment]
@jancborchardt 300px are not needed on the public link share page. The dropdown has only one item.

A smarter approach would be, to open the dropdown to the top if it's not enough space at the bottom.

**Comment by jancborchardt** [comment]
As said above, the dropdown is not the only reason for the whitespace.

And opening the dropdown to the top is not a smarter approach since it poses a new question: How do you sort the actions now?
- same direction top to bottom? Problem: Delete is now the first action.
- reverse direction? Problem: It’s reversed.

Neither solution is good, so always making sure that the dropdown will actually drop _down_ is the best way to do this.

**Comment by michaelstingl** [comment]
@jancborchardt Thanks!

**Comment by skjnldsv** [comment]
Drop left!!! :D 


_I see myself out_

**Comment by jancborchardt** [comment]
Ah btw, is this ok to close then @michaelstingl?

**Comment by oparoz** [comment]
@michaelstingl - If you look at older PRs, you'll find a solution with a shallow footer which grows when the dropdown is revealed.

**Comment by jancborchardt** [comment]
Which is a strange solution since either:
- it scrolls, messing with the list position and throwing one out of the flow
- or it doesn't scroll the menu into view, which necessitates manual scrolling

And then what to do when the menu collapses again, which often happens as a result of other things (like clicking elsewhere)? It's just awkward.

**Comment by oparoz** [comment]
>it scrolls, messing with the list position and throwing one out of the flow

Yes, it scrolls the window, but without messing anything up

>or it doesn't scroll the menu into view, which necessitates manual scrolling

That's what's currently in use, even with the huge gap at the end, people need to manually scroll the menu into view
