### ISSUE TITLE
sharing hotfolder

### ISSUE THREAD

**Issue by sk00lz** [owncloud/core#24382]
Hello everyone,

This is a feature request.
I often have to share files with specific clients, really often.
I like the drag and drop function in chrome to upload files an then manually enter a mail adress to share it. That's simple and comfortable. But i asked myself, whether it's possible to make it even more simple.

I thought about a sharing hotfolder:
There is a hotfolder for client A, which is linked to his mail adress (client_A@company.com).
Drag files to hotfolder for client A --> a mail with the share links to these files will automatically be send to client_A@company.com
So the only thing to do for me should be dropping the files in the hotfolder.

Is it possible to realize something like this? Maybe with an app/plugin?

**Comment by MTRichards** [comment]
Interesting feature request, making it super simple. The question is, I think, one of if you ALWAYS want this behavior, or if only sometimes. Or most of the time. If most of the time, what do you do to share when you don't want this? Maybe it is a matter of creating a rule on a directory, and any time you put a folder into the "autonotifyofsharefolderforuserA" this behavior happens.This means pre-setting up additional info for that folder in some way. All probably doable as an app, since you could see an upload to a set path and execute this in the upload sequence. I think. A little out on a limb for me to be certain.

Still, an interesting idea.

**Comment by bwhpublishing** [comment]
Hello,

perhaps there is a program that fills e.g. three hotfolders automatically with PDF-Files, each hotfolder belongs to an client.
An script fired on a cronjob, looks into the folders, grabs the files, upload it to owncloud in the same way you drag&drop it and than send an e-mail to the associated client. Regardless you can also drag files as previously via the UI.

Is that possible?
I´m very new to owncloud and have no starting point to create such an app by myself.

**Comment by MTRichards** [comment]
If this is only something used in the web interface, a cron is possible after files are uploaded, but that would not be immediate - rather it would wait until cron got to it. Depending on serer settings, it could take a while to get to it.. 

I think it would be better to take an action when the files are uploaded, since we have a mechanism for that. Then we could trigger on a specific path. However, this does mean every upload goes through this and only the ones with the proper path are triggered, potentially a performance nightmare.

**Comment by hodyroff** [comment]
We are going to solve this scenario in 10.0. Interesting additional use case above.
@pmaier1

**Comment by PVince81** [comment]
seems this didn't make it into 10.0, moving to backlog for now unless I misunderstood

**Comment by hodyroff** [comment]
I thought between guest users and share by email via multiple public links this is done.

**Comment by hodyroff** [comment]
@sk00lz please look into 10.0 Beta and let us know whats missing using the above two functions (seperate apps).

**Comment by PVince81** [comment]
maybe guest user fits the purpose somehow, yes, even though it's not really a "hot folder with automatic magic emailing to users"

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
