### ISSUE TITLE
Conflict between config.php and admin GUI filesystem_check_changes

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#24738]
The default in config.sample.php is `filesystem_check_changes' => 0,`. But the default on new external storages in the Web GUI is  `Check for changes once every direct access`, or `filesystem_check_changes' => 1,`

This makes no sense. Can someone bring enlightenment?

**Comment by Xenopathic** [comment]
The config.php parameter applies to the local storage, aka what's in the ownCloud data directory. This is by default 0, since we assume that no-one ever changes files directly in the data directory. External storages get a default of 1 for this, since it is often the case that an external storage will be accessed directly or otherwise not via ownCloud, and we need to detect changes.

**Comment by carlaschroder** [comment]
Thanks @Xenopathic. config.sample.php needs to be updated. I will open a PR.

**Comment by carlaschroder** [comment]
https://github.com/owncloud/core/pull/24788
