### ISSUE TITLE
Remember two-factor authenticated browsers for future logins

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/core#24744]
### Steps to reproduce
1. Log in to OC via 2FA
2. Log out
3. Log in again
4. See the 2FA challenge page
### Expected behaviour

2FA should be checked only once
### Actual behaviour

2FA is checked on every login

**ownCloud version:**
9.1.0.2

@LukasReschke @owncloud/security ideas on how to implement that? :cookie:?

ref https://github.com/owncloud/core/pull/24559
ref https://github.com/owncloud/core/pull/24559#issuecomment-220560620

**Comment by PVince81** [comment]
@cornelinux since you have experience with 2FA, can you comment on the need for this ? How does it work with privacyIDEA currently ?

**Comment by cornelinux** [comment]
Hi @PVince81 
first of all I only see this behaviour with Google. ebay, paypal, github do not use such a behaviour. So this is rather uncommon in the fields of two factor authentication. (till now).
So why does Google do this? I guess - since they can.
And this might be the point here. If you want to implement such a feature you must be able to identify the user and where the user comes from in a very reliable way. And who would be better in that, than Google?

Nevertheless indeed in another project we are also talking about to add such thing with privacyIDEA.
So you see: At the moment privacyIDEA does not do this.

There are two possibilities to do this:
1. The application (ownCLoud) takes case of this. In this case it would be totally transparent for the authnetication system. If ownCloud sees that the user already authenticated with two factors, then ownCLoud simply would not query for the 2FA and would not ask the 2FA server.
2. Let the 2FA server take care of this: In this case you need a hook, so that you first can query the authentication server if the user should provide a second factor. In fact the privacyIDEA ownCloud App or any other could use the method "isTwoFactorAuthenticationEnabledForUser".
But the 2FA App needs access to all the "necessary information".

# Necessary information

This is the big google question here what is the necessary information for identify, if the user already performed 2FA from a certain machine. What is this?
1. Client IP address (can be spoofed or changed with DSL or be behind NAT :-/ )
2. Browser name (can be change after an update. The Attacker can easily modify the HTTP CLient iedneitfier)
3. Additional Cookie to set in the browser, when 2FA was performed...
4. ...

...and maybe this is the reason why I personally do not like this functionality. If you are implementing such a function in ownCLoud you should implement this configurable, so that the admin can decide if to use this or not.

**Comment by PVince81** [comment]
Thanks a lot for your feedback @cornelinux. I think the idea was to store the info in a cookie. Not sure if such cookie could be spoofed but I guess the cookie would need to contain some token that is known by the server.

Maybe you're right and we shouldn't add this directly in ownCloud and leave this up to the 2FA provider to decide whether it's ok for them to remember that state. In this regard the question whether the method `isTwoFactorAuthenticationEnabledForUser` is enough for this. There is a slight risk that its result might be misinterpreted as 2FA being completely disabled. Maybe we should add a new method `isTwoFactorAuthenticationAlreadyDoneForUser` or something.

**Comment by cornelinux** [comment]
Having an additional method is fine for me. If you are not doing this in ownCloud still the question is, which information are available within the method ``is2FAAlreadyDoneForUser`` or in which way the cookie can be set and read. 

I.e. there must be a method/hook to set the cookie and also write the cookie to the authentication system. The authentication system could keep track of which cookie was issued and if it was still valid.
Also the auth system has to issue a new cookie, if the authentication was successful.
This would probably happen in ``verifyChallenge``.

**Comment by PVince81** [comment]
Moving to backlog for now
