### ISSUE TITLE
New password invlidates all device tokens

### ISSUE THREAD

**Issue by danimo** [owncloud/core#24786]
In the current design, updating the password invalidates all devices tokens. This is due to encryption and external storage, which may depend on updated user credentials.

However, this runs contrary to one aspect of why clients would want to use token based auth in the first place: to be immune towards password changes as to be able to run as a uninterrupted background service.

Usually, invalidating tokens when invalidating the login is a good idea, however, in some enterprise environments this works around artificial 30 days password renewal policies (on purpose). The question is: do we want to cater for these?

## Proposal for solving the issue (if we choose to)

Currently, passwords are encrypted with the token which itself is only stored hashed in the database and decrypted on demand. If the password is no longer valid (which is verified every 5 minutes), the session gets killed and the token is invalidated.

Instead, we could use a private/public key pair (per user) where the private key is encrypted with the token. By using this indirection, we could update all tokens once username and password have been udpated in one place.

**Comment by danimo** [comment]
//cc @PVince81 @ChristophWurst @dragotin

**Comment by PVince81** [comment]
also @MTRichards @MorrisJobke @cmonteroluque because I thought it was a requirement.

**Comment by MTRichards** [comment]
We need to have the token invalidated on password change in most cases, because IT wants this clear connection between password changes and loss of access until passwords are reset. So yes, it was a requirement because of the issue where LDAP users were still accessing ownCloud after being removed from the LDAP.

The uninterrupted background jobs are interesting, but not required right now as far as I know.

I would not cater to that use case at this time.

**Comment by cmonteroluque** [comment]
as we spoke, I agree completely
