### ISSUE TITLE
[Discussion] ownCloud Inc. status after a big employee departure in one month

### ISSUE THREAD

**Issue by HLFH** [owncloud/core#24864]
### Steps to reproduce
1. [Frank Karlitschek is leaving ownCloud Inc.](https://karlitschek.de/2016/04/big-changes-i-am-leaving-owncloud-inc-today/)
2. [Lukas Reschke is leaving ownCloud Inc.](https://statuscode.ch/2016/05/farewell-owncloud-inc/)
3. [Björn Schießle is leaving ownCloud Inc.](http://blog.schiessle.org/2016/05/26/road-ahead/)
4. [Jos Poortvliet is leaving ownCloud Inc.](http://blog.jospoortvliet.com/2016/05/moving-on-from-owncloud.html)
5. [Arthur Schiwon is leaving ownCloud Inc.](http://arthur-schiwon.de/so-long-and-thx-all-fish-leaving-owncloud-inc)
6. Did I miss someone?

### Expected behaviour
Keep on like that?

### Actual behaviour
At least, five people are leaving ownCloud Inc. 
And I believe there is a lack of explanation.

Should we still trust owncloud.com?
Should we switch to another solution?
What is the current number of ownCloud Inc. employees?
Will the departed employees be replaced?
Will ownCloud Inc. continue with less people? Should we expect an empowerment of the owncloud.org community project?

And last but not least, will ownCloud become also a social network service based at least on the Federated Cloud ID and [JSXC](https://github.com/jsxc/jsxc)? (yes, it's off-topic)

So, I'm worried.

**Comment by MTRichards** [comment]
Full disclosure, I work at ownCloud, but this also allows me to answer some questions. 
 
Employees have indeed departed, but 85%-90% of the company remains, still working on the product, supporting our community and our customers. We will backfill engineers, and intend to continue to invest and grow the community, and in turn our company. In other words, ownCloud, Inc continues on.
 
You are right, I expect more empowering of the community. We have already adopted a number of approaches to empower more ownCloud community involvement, including transparent roadmap planning (https://github.com/owncloud/core/issues/24684), more transparent development with zenhub for iOS and Android (testing this https://github.com/owncloud/ios/issues/668 ), and more to come. 
 
I cannot make a choice for you about whether you continue to use ownCloud, but I myself use ownCloud and will continue to do so. It is hands down the best option for securing your personal data, both personally and professionally.
 
>And last but not least, will ownCloud become also a social network service based at least on the Federated Cloud ID and JSXC?
 
I don’t know. Should it? Open a roadmap request and see what everyone else things at #24684
 
I am glad you asked the question.

**Comment by enoch85** [comment]
In the future, could you please employ more devs that works with the community as the number of issues just continues to increase?

The community (as I see it) is crucial to ownCloud. To decrease the community and focus more on ownCloud Inc (maybe to make more money?) is a bad decision if you ask me. Please confirm that this will not happen.

Thank you!

**Comment by cmonteroluque** [comment]
@enoch85 yes, we absolutely agree. You should see the number of open PRs down with 9.1 as we've started to take a bit of an extra focus on community-driven issues. On small areas we have successfully started to engage primarily with community input. We know there is work to do, and you should see announcements shortly (yes, from the Inc.) in that direction. Inc. needs to make money, of course, none of us get our groceries for free. But that is not, and must not be, contradictory with having a more vibrant, broader community, both in terms of users and developers. And not just as recipients of a small group's worth of decisions and code, but as active and major participants on direction and execution.

Is it specific enough? Not yet, and it's not for lack of wanting to. But let's see actions speak rather than words. Change happens, this is a transition time, we are all living it. Your voices matter in how this platform and community evolve going forward. Thank you!

**Comment by cmonteroluque** [comment]
@HLFH, thank you for the questions...

a) yes
b) no
c) much larger than the number of those who have left
d) in several ways
e) absolutely expect an empowerment of owncloud.org, independently of the size of .com. No more today about it but yes, no doubt.

on your off-topic :), @MTRichards said it right

**Comment by Boilerplate4u** [comment]
@MTRichards, thanks for the clarification regarding what is currently happening at oC INC.

**But** are there any core developers left in the company? 

I've tried to get some answers on a couple of questions regarding some core functionality but null so far. Nothing from neither devel@owncloud.org or irc #owncloud-dev@freenode.net...

Btw, I'm not sure that oc inc and the dev-community are aware it's quite hard to find out and adress the correct communication channel for the different needs? And why so many different (and old-fashioned :-) dev channels? 

Btw, are there any particular reason using mailing lists and irc rather than the existing oC forum? Imo, Github is great for specific discussions targeting PR and issue tracking but is far from being as good as a regular message board (like MyBB or phpBB). In particular when you need a sounding board to discuss ideas with experienced experts and, among other things, receive help to establishing developer environments and so on.

Mail lists and IRC are unstructured, quite hard to use and no support for discussion threads. IRC doesn't have any historical search capabilities. 

So, any plans to convince the community to facilitate for a broader base of developer  and consolidate to a single modern communication channel?

Thanks in advance!

**Comment by HLFH** [comment]
@Boilerplate4u I quite never used:
 - their IRC channel
 - their ownCloud forum
 - their mailing lists

The next-generation forum could be [Flarum](https://github.com/flarum/core).
[Ghost blogging platform](https://github.com/TryGhost/Ghost) is mainly using [Slack](https://ghost.org/fr/slack/) and the open source alternative is [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat). If you think it should be rationalized, you could create an issue and link it [here](https://github.com/owncloud/core/issues/24684).

**Comment by Boilerplate4u** [comment]
I merely wanted to point out there is a need for a more distinct **communication strategy** and didn't intend to discuss what type of forum that should be used as such.

For example one could try to consolidate as much as possible of the various channels to a single platform. I do understand if people may have opinions if such a platform should be operated (i.e. "owned") by oC Inc or independently but I personally have no opinion in that matter but is more interested to find most of the resources I need in a single place

Down below is what I found in terms of various IRC channels, mailing lists, forums, blogs and news channels. Not very easy for an outsider to decide what to choose, right?

IRC (freenode)
```
#Debian-owncloud	- ownCloud for Debian
#owncloud			- Support and discussion of ownCloud
#Owncloud-dev		- http: / / ownCloud. Org developer channel
#Owncloud-testing	- ownCloud testing framers
#Owncloud news		- ownCloud News RSS / Atom feed reader
#Owncloud-security 	- Discussion of curing and enhancements only
#Owncloud-office-Stuttgart - Stuttgart Office Communication
#Owncloud-android	- ownCloud Google Android
#Owncloud-gsoc		- ownCloud Google
#Owncloud-pi
```

https://mailman.owncloud.org/mailman/listinfo
```
Announcements		[no description available]
Appsreview			[no description available]
Devel List			for Developers of ownCloud
Events			    [no description available]
Jenkins			    [no description available]
Owncloud			[no description available]
Packaging			Discussions around packaging ownCloud
Testing-team		[no description available]
Testpilots			List for Early Test Volunteers
Translations		[no description available]
translations-french	french translations for owncloud
User				For users of ownCloud
website			    owncloud.org community website mailing list
```

Various types of forums, blogs and news channels not listed in details...
``` 
Forum.owncloud.org	A board to discuss all kind of ownCloud topics
owncloud.org/news	ownCloud Planet - contributor blog roll
owncloud.com/blog	ownCloud’s Team Blog (oC Inc only)
```

And there are of course the Github forums:
- ownCloud main repro:  https://github.com/owncloud/
- ownCloud core issues and discussions: https://github.com/owncloud/core/issues
- ownCloud Platform Planning: github.com/owncloud/core/issues/24684 (https://github.com/owncloud/core/issues/24684)

**Comment by DeepDiver1975** [comment]
Questions have been answered ->close

**Comment by clementhk** [comment]
@karlitschek @LukasReschke @schiesbn @jospoortvliet @blizzz @MorrisJobke 
Would be cool to hear from you guys.

**Comment by blizzz** [comment]
@clementhk Honestly, I do not want to add anything here. However, I guess you head the news yesterday? That'll be the statement.

**Comment by strypey** [comment]
@Boilerplate4u 
"Mail lists and IRC are unstructured, quite hard to use and no support for discussion threads. IRC doesn't have any historical search capabilities."

I'm not sure what you mean by "unstructured", but whether or not mailing lists support threading etc is depends entirely on what kind of archiving and web interface is used with the mailing list. For example:
* Modern mailing lists managers like [GroupServer](http://groupserver.org/) provide a web front-end that's just as useful as web forum software.
* Mailing list archives can be hooked up to web forum software so that people can join in the same discussions using either email or the web. For example, the [Trisquel users forum](https://trisquel.info/en/forum/trisquel-users) is actually a web front-end for a mailing list.
* [Discourse forums](http://www.discourse.org/) and [Loomio groups](http://loomio.org/) can be interacted with as if they were mailing lists.

It's true that IRC doesn't support search, but it's intended for ephemeral conversations. Anything of ongoing interest that's discussed in IRC can be summarized  on a wiki page or as an email to a mailing list. If you set out to have a discussion that you want to be archived for posterity, just don't start it on IRC. It's a matter of choosing the right tool for the communications job, rather than thinking that every comms problems is a nail just because you like using a hammer.
