### ISSUE TITLE
Feature request: Option to disable username discovery for admins and users

### ISSUE THREAD

**Issue by xshadow** [owncloud/core#24872]
### Feature Request

When you are sharing a file owncloud "leaks" all the usernames that are registered on the server.
This happens since owncloud is trying to autocomplete usernames.
This is a well-conceived and intended behavior, if you reside in an owncloud instance where the users know each other. 

If you have an account on bigger community servers, some people have reservations against this behavior, because they don't want to be found. Especially if the login is bound to an mail account. Due to this behavior a malicious user could extract all usernames and customize a bruteforce attack to the given user names. 

It would be nice to have the following features: 

1. Give the administrators the opportunity to globally disable username autocompletion on sharing (in config/config.php)
2. Give the user the possibility to decide if he/she wants to be found or not (in the user settings)

### Steps to reproduce
1. Share a file or calendar with other users 
2. Discover all usernames that have an account on the server

**Comment by nickvergessen** [comment]
There is a setting for that:
> Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered.

It's the last one in the list of the sharing app on the admin page:
![admin_-_owncloud_-_2016-05-30_14 09 17](https://cloud.githubusercontent.com/assets/213943/15649216/35721092-2670-11e6-90b2-9b27189f63f3.png)

**Comment by voundaries** [comment]
When "Allow users to send mail notification for shared files" option is enabled, it shows the email field for link sharing.

This field **_autocompletes username and email_**, defeating the purpose of the setting @nickvergessen mentioned:

"Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered"

Would suggest opening this, since @xshadow may still have a strong valid point.
