### ISSUE TITLE
[9.1 beta 1] Session manager shows multiple sessions per sync client

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#24876]
While testing 9.1, I found an interesting bug.

I set it up on the appliance (Ubuntu 14.0.4, mysql, apache) and then manually upgraded from the installed 9.0.2 to 9.1 beta 1. It worked great.

Sync client is running on Windows 10, sync client 2.1.0

Then I added a user 1. Still good.

Then I went into the personal panel and assigned a token for a client. Still good. I even logged in and it all worked. So far so good.

When I looked at the sessions, and the new ability to delete a session per device, I noticed I had 6 or 7 sessions for the sync client. The web client had 1, that worked, but the sync client had many for only 1 sync attachment.

I think the bug is either that the sync client HAS several sessions at any one time, or that the personal panel session report shows sometimes extra sessions for the sync client. Not certain which it is.

@ChristophWurst not sure if you did the session work too...

**Comment by ChristophWurst** [comment]
I think the problem here is that the we have a separation of browser sessions and devices but the sync client does something in between as it's a client that uses session. Not sure why, but I guess we start sessions for sync clients to prevent high load on the user backend as with session tokens you don't need to check the password on every request.

Multiple browser session entries *could* be generated if the client starts several requests very quickly/simultaneously, where the first request has not been finished when the others start. In that scenario the server will treat each of the request as the first one (no session cookie set) and create session tokens.

One simple solution for the problems would be to not create session tokens for DAV clients. However, we might create a huge load on the user backend which e.g. LDAP might not handle that well if I remember correctly. cc @LukasReschke

**Comment by ChristophWurst** [comment]
probably fixed by https://github.com/owncloud/core/pull/24973. Please re-open if the problem still exists.
