### ISSUE TITLE
Per user encryption and encryption without user logging in

### ISSUE THREAD

**Issue by ash663** [owncloud/core#24982]
Hi,
I'm new to ownCloud, and after installing the encryption module, the following two observations came to my mind:
1. Functionality to enable encryption for specific users, as well as specific folders for that user.
2. Functionality to start encrypting files before the user logs in.

How should I go about if I need to implement the above two features?
Feature (2) would be needed if the user has large files, as it would take time to encrypt them. One solution I read was here: https://github.com/owncloud/core/issues/10657 but it does not suggest any method for encrypting without the user logging in.

Thanks

**Comment by joeyjy** [comment]
@PVince81 If I want to disable encryption when filesize > 2GB, can I simply change some source code? if so, where can I start

**Comment by PVince81** [comment]
This will not work well not consistently because shared files would be encrypted for the owner. And users who chose to use encryption would be surprised to learn that when uploading files to other users' shares through a received share, said files are not encrypted any more.

As for encrypting without the user logging in, maybe you are referring to the initial key creation. When using user-key encryption, a user **must** login with their password because the encryption key is encrypted with the user's password.
One alternative to this is to use the "master key" encryption mode where there is only a single key. In this case, no user login is needed.
