### ISSUE TITLE
Feature Request: Offer server-side compression of files

### ISSUE THREAD

**Issue by kbcmdba** [owncloud/core#25128]
### Steps to reproduce
1. Feature request: Offer server-side compression of files
2.
3.

### Expected behaviour
Administrators should be able to tell OC to compress all files stored on the server to save space and reduce IO wait time. When selected, the administrator could determine to use gzip, bzip2 and other file compression tools.

### Actual behaviour
Files are currently stored uncompressed on the server causing it to always take more space and increase disk IO times.

### Server configuration
**Operating system**:
Any

**Web server:**
Any

**Database:**
Any

**PHP version:**
Any

**ownCloud version:** (see ownCloud admin page)
8.2.4

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
Fedora Repositories

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by nickvergessen** [comment]
with compression IO will increase, because we need to compress after upload and uncompress when generating previews, etc.

**Comment by DeepDiver1975** [comment]
I see no benefit in this as well. In addition to performance impact i question the saved space. Almost all filetypes these days are already compressed.

I'm closing this.

**Comment by kbcmdba** [comment]
@nickvergessen I disagree. Unix systems don't require additional space to do (de)compression as a part of a stream. Typically, the cost of disk I/O is much higher than the cost of streaming (de)compression, usually by a factor of 100 or more on home computers with spinning disks. If we're talking about data-center hosted servers or SSD's, that's not likely to be true. That's why I'm requesting it be an option. :-)

@DeepDiver1975  I also disagree that "almost all filetypes these days are compressed." I do agree that many formats use compression, but the formats I use most often (text files, source code, docx) can all benefit from compression. Again - I'm requesting that it be an option, not that OwnCloud simply be changed to always compress.

**Comment by boscowitch** [comment]
Actually instead of more IO there will be less IO .... if the server has an oversized CPU for all the users it servers (with owncloud often 1 or 2 or 5 family size private server) the idling cpu would be more than able to handle it. this would in fact improve IO speed since the bandiwth gets used less thanks to compression...
 so it really depends on the amount of users and available multicore cpu and implementation of compression... 

the  easiest solution would be to use transparent compression in the FS ,unfortunately there is not so much support for transparent compression on FS layer inlinux except for some more advanced FSs 

Also an intelligent feature would be able to not waste cpu on already compessed filetypes (mp3 flac jpeg ect.) and only compress the rest, this would save cpu and increase bandwith / lessen IO
