### ISSUE TITLE
Integration of Lepton

### ISSUE THREAD

**Issue by SpiGAndromeda** [owncloud/core#25498]
Hi developers

Dropbox developed an open source tool. called lepton under the Apache2 license. 
This tool is able to reduce the space requirement of jpegs by about 20%. The compression is lossless but uses an own format. 
I think this tool would be a great benefit for ownCloud, especially for users with encryption because they couldn't access theire data directly anyway.
Because of its open source character an integration shouldn't be that complicated (correct me if I am wrong). 

Lepton on GitHub: https://github.com/dropbox/lepton

Best regards 
Spigo

**Comment by DeepDiver1975** [comment]
I don't really see this in ownCloud, because of
- lepton is a command line tool and shell_exec is not available on all installations. 
- cli tool invocation has a potential sec risk - that's why we want to remove them fully in the future
- all back an forth conversion has a negative performance impact on sync
- finally we shall not modify the data as give to us (encryption is kind of an exception)

I'm closing this. Thanks for you suggestion anyway!

**Comment by SpiGAndromeda** [comment]
I agree with the last two points but my intentional idea was to bring the conversion algorithm to php and fully integrate them into the owncloud code without an external application.
