### ISSUE TITLE
OC9.1: FTP Login with email adress and session authorisation not working

### ISSUE THREAD

**Issue by htwsaaraub** [owncloud/core#25578]
### Steps to reproduce
1. Define User specific FTP Connections in Personal settings page. To connect to the Server owncloud session authentication selected. 
2. Login using E-Mail Adress
### Expected behaviour

File App should connect to FTP Storage. This connections are entries in the user personal settings page. 
### Actual behaviour

FTP Storage will not connect after loggin. Shares have a red indicator in personal settings - external mounts page.
This is because the ftp Server will not unterstant the User login in the Format: 'username@domain.de'

If the same user logs in to owncloud using the username instead of email adress the FTP Share are connected correct and can be browsed. The Indicator in personal settings page is green. 

FTP Server is based on Windows IIS. The domain for Mailadress in ldap is different to the domain the FTP Server is running on. 

In the most configurations it will be better to pass only the username to the ftp server. 
### Server configuration

**Operating system**: Debian 8

**Web server:** apache 2.4.10

**Database:** 5.5.49-0+deb8u1 - (Debian)

**PHP version:** PHP/5.6.23-0+deb8u1

**ownCloud version:** 9.1

**Updated from an older ownCloud or fresh install:** Update from 9.04

**Where did you install ownCloud from:** debian package via apt

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

Enabled:
- activity: 2.3.2
- comments: 0.3.0
- dav: 0.2.5
- external: 1.2
- federatedfilesharing: 0.3.0
- federation: 0.1.0
- files: 1.5.1
- files_antivirus: 0.9.0.0
- files_external: 0.6.0
- files_sharing: 0.10.0
- files_texteditor: 2.1
- files_trashbin: 0.9.0
- firstrunwizard: 1.1
- notifications: 0.3.0
- provisioning_api: 0.5.0
- systemtags: 0.3.0
- templateeditor: 0.1
- updatenotification: 0.2.1
- user_ldap: 0.9.0
  Disabled:
- delete_confirmation
- encryption
- files_pdfviewer
- files_versions
- files_videoplayer
- gallery
- user_external

`

```
**The content of config/config.php:**
`$CONFIG = array (
  'instanceid' => 'ocd0c770c9da',
  'trusted_domains' =>
  'skeletondirectory' => '',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => 'htwsaar',
  'maintenance' => false,
  'forcessl' => true,
  'loglevel' => '3',
  'preview_max_x' => 100,
  'preview_max_y' => 100,
  'enable_previews' => false,
  'preview_max_scale_factor' => 1,
  'log_rotate_size' => 104857600,
  'asset-pipeline.enabled' => true,
  'trashbin_retention_obligation' => '30, auto',
  'filelocking.enabled' => 'true',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'updatechecker' => false,
);
```

**Are you using external storage, if yes which one:** ftp

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

```

```
### Client configuration

**Browser:**

**Operating system:** Windows 10
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```

`{"reqId":"kZX7XnK7jiJBAvbRZ3nc","remoteAddr":"134.96.211.82","app":"PHP","message":"stat(): stat failed for ftp:\/\/xxx:xxx@X.X.X.X\/Software\/ at \/var\/www\/owncloud\/apps\/files_external\/lib\/Lib\/Storage\/StreamWrapper.php#126","level":3,"time":"2016-07-22T13:42:45+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"Sven.Schneider"}
`
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
@owncloud/qa please verify this scenario - THX

**Comment by PVince81** [comment]
Works for me in 9.1.2.

### Steps:
1. Setup a local FTP server with docker: `docker run -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 -e "PUBLICHOST=localhost" stilliard/pure-ftpd:hardened`
1. `docker exec -it ftpd_server /bin/bash`
1. inside docker: `pure-pw useradd test -u ftpuser -d /home/ftpusers/test` and set the password to "test"
1. inside docker: `pure-pw mkdb`
1. Login in OC as admin
1. Create a user "test" with password "test" and email address "test123@example.com"
1. Go to the admin page
1. Setup an external storage with mount point "/ftp", authentication "log-in credentials, save in session" and "localhost" as host
1. Log out
1. Login as "test" in OC
1. Check that "/ftp" is accessible
1. Log out
1. Login as "test123@example.com"
1. Check that "/ftp" is still accessible

This worked for me. I checked the `SessionCredentials` which intercepts the user name and even when logging in with email address, it properly receives "test" instead of "test123@example.com" and can then properly set the username for FTP.

Please try again with 9.1.2 as it is likely that such issue was already fixed.
If the problem persists in that version, feel free to reopen.
