### ISSUE TITLE
New Filesystem API: ICache

### ISSUE THREAD

**Issue by labkode** [owncloud/core#25670]
@DeepDiver1975 @PVince81 @icewind1991 @moscicki @NadirRoGue

Hi,
I have taken the latest ownCloud stable version (9.1) and started to prototyping a custom EOS cache on it. I implemented all the methods required by the new ICache interface, but when I plugged it in the current architecture some core classes rely on the method getNumericId(), see trace:

```
Type: Error
Code: 0
Message: Call to undefined method OC\Files\Cache\EosCache::getNumericId()
File: /Applications/MAMP/htdocs/owncloud/lib/private/Files/Config/LazyStorageMountInfo.php
Line: 54

Trace
#0 /Applications/MAMP/htdocs/owncloud/lib/private/Files/Config/UserMountCache.php(138): OC\Files\Config\LazyStorageMountInfo->getStorageId()
#1 /Applications/MAMP/htdocs/owncloud/lib/private/Files/Config/UserMountCache.php(124): OC\Files\Config\UserMountCache->addToCache(Object(OC\Files\Config\LazyStorageMountInfo))
#2 /Applications/MAMP/htdocs/owncloud/lib/private/Files/Config/MountProviderCollection.php(133): OC\Files\Config\UserMountCache->registerMounts(Object(OC\User\User), Array)
#3 /Applications/MAMP/htdocs/owncloud/lib/private/Files/Filesystem.php(425): OC\Files\Config\MountProviderCollection->registerMounts(Object(OC\User\User), Array)
#4 /Applications/MAMP/htdocs/owncloud/lib/private/Files/Filesystem.php(370): OC\Files\Filesystem::initMountPoints('test')
#5 /Applications/MAMP/htdocs/owncloud/lib/private/legacy/util.php(255): OC\Files\Filesystem::init('test', '/test/files')
#6 /Applications/MAMP/htdocs/owncloud/lib/base.php(890): OC_Util::setupFS()
#7 /Applications/MAMP/htdocs/owncloud/index.php(39): OC::handleRequest()
#8 {main}
```

Do we need to add the getNumericId to the ICache (and for what purpose) or can we bypass this method call from other classes ?

**Comment by icewind1991** [comment]
Do you return your cache class from `Storage->getStorageCache`?

The `StorageCache` shouldn't be required for custom cache implementation but apparently I missed a spot.

You can either implement the method, returning an integer that's unique to the storage (it's used to uniquely identify storages) or you can create a custom implementation of `\OCP\Files\Config\IUserMountCache`

A custom `IUserMountCache` might be beneficial anyway since you might be able to get the info it needs more efficiently that the generic implemention.

Currently if you want to overwrite the builtin `UserMountCache` you have to overwrite it with the private api (`OC::$server->registerService('UserMountCache', ...)`).

@DeepDiver1975 Adding the option to change it with a public api or config option shouldn't be hard, I can help you with it if you want or find some time to do it myself.

(I had a quick search and couldn't find any other place that uses the `StorageCache` that isn't already overwritable)

**Comment by labkode** [comment]
Thanks @icewind1991 
> Do you return your cache class from Storage->getStorageCache?

I do not return it as it is not specified in the IStorage interface (as far as I can see it is a method of the Common storage implementation). I just return my cache implementation in the getCache() method. What is the difference between getStorageCache and getCache ? With the UserMountCache can I avoid the use of the getStorageCache ?

As far as I can see there is still strong dependencies on private classes rather than on the interfaces.

**Comment by icewind1991** [comment]
> I do not return it as it is not specified in the IStorage interface (as far as I can see it is a method of the Common storage implementation). I just return my cache implementation in the getCache() method.

Yes, I misremembered something, `StorageCache` is not the problem here

> With the UserMountCache can I avoid the use of the getStorageCache ?

`UserMountCache` requires storage ids (as noted above `StorageCache` isn't the issue, just storage id)
Depending on the use case you might be able to get away with a dummy implementation (from a quick look the only "core" app using it atm is actvity) but for a full implementation (either a custom one just reusing the existing one) a proper "storage id" is needed

**Comment by PVince81** [comment]
@labkode is this still a problem ?

**Comment by PVince81** [comment]
Storage API to be revisited in a broader scope anyway.
