### ISSUE TITLE
Users with shared link access cant create folders

### ISSUE THREAD

**Issue by backupPG** [owncloud/core#25695]
I create a folder and shared by link with password to other user. He can open this link and upload files, but cant create folders. 

Is this feature possible? I can't see anything related to that feature on sharing options.

**Comment by RealRancor** [comment]
@backupPG It might be really useful that you fill out the shown issue template when create a new issue. Currently all basic infos about your environment (especially oC version) is missing.

Creating a new folder within a shared folder should be possible since oC 9.0: https://github.com/owncloud/core/issues/22545 which can be seen here:

https://demo.owncloud.org/index.php/s/gmZEm3i00Dx3Qyr

(as long as "allow editing" is specified if sharing a folder by link).

**Comment by backupPG** [comment]
@RealRancor I'm sorry, it was my first repot on github. I have version 8.2.7 stable, so if its available on version 9, I will update my owncloud.

Again, Im sorry and many thanks!
