### ISSUE TITLE
File has not been found

### ISSUE THREAD

**Issue by again002** [owncloud/core#25787]
Hello,
How can I solve the following problems
Error 	core 	File with id "111" has not been found. 

"app":"core","message":"File with id \"111\" has not been found.","level":3,"time":"2016-08-12T11:11:11+01:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"

owncloud 9.1.0 (fresh installation)
without encryption

Thanks

**Comment by PVince81** [comment]
This message can have many different reasons:

1) A shared file is in the trashbin so it cannot be mounted.

In this case you can simply ignore the message: https://github.com/owncloud/core/issues/25740
The message will disappear when the trashbin gets cleared and cron is run to discard orphaned shares.

2) Other sharing configurations

In this case, you should already see some crashes or users having problems with shares.
If you're on 9.1 maybe you're seeing https://github.com/owncloud/core/issues/25557 and are also getting the memory issues from time to time.

In any case, this report doesn't contain enough information to be able to find out. I suggest you check the linked tickets instead. If you think your problem is a different one, please reopen and provide more details about your setup and sharing scenario.
