### ISSUE TITLE
PDF links always downloaded instead of opened in browser

### ISSUE THREAD

**Issue by KonradHoeffner** [owncloud/core#25928]
### Steps to reproduce
1. Place mouse over a PDF
2. Second mouse button -> Copy Link Location
3. Open new tab -> paste -> enter

### Expected behaviour
The PDF should now be opened in the browser as when clicking directly on the PDF (as long as the browser is configured in this way, as it is in my case). I need this to link to specific pages with the `#page=x` parameter.

### Actual behaviour
The PDF gets downloaded instead.

### Server configuration
**ownCloud version:** 9.0

### Client configuration
**Browser: Firefox 48.0

**Operating system:**
#### Browser log

```
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead.(unknown)
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# insteadjquery.min.js:1
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://myowncloud.de 'unsafe-eval'").files
window.controllers is deprecated. Do not use it for UA detection.ace.js:1716
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.jquery.min.js:5:17117

```

**Comment by PVince81** [comment]
Yes, because this is the download URL which also happens to be the webdav URL of the file.
This URL is not intended to be used to open files to be viewed.

Direct link to file for viewing is currently not supported in ownCloud, needs this feature: https://github.com/owncloud/core/issues/13414
The purpose of that enhancement is to make it possible for any file viewer app (like the PDF viewer) to register URLs under which the viewer can be invoked directly.

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/13414
