### ISSUE TITLE
Installation page warns about SQLite while having only MySQL available.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#26147]
## **Observed:**

![screen shot 2016-09-19 at 12 33 02](https://cloud.githubusercontent.com/assets/9048796/18629552/8f96cca4-7e66-11e6-9e27-3d5f1e5d614f.png)

**Comment by IljaN** [comment]
Hi @SergioBertolinSG
 
I am only able to reproduce this by aborting the make installation-process (Ctrl+c) after Composer is finished. This results in not correctly installed js-dependencies because Bower did not finish which in turn causes JavaScript errors and  the described behaviour:

![sqlite_warn_broken_js](https://cloud.githubusercontent.com/assets/246983/19836067/7712df7e-9e96-11e6-950f-e5b59435da99.png)

When make finishes without errors in the js build-step (no js errors in the frontend) the setup screen seems to works as intended:

![sqlite_nowarn_working_js](https://cloud.githubusercontent.com/assets/246983/19836124/d568df00-9e97-11e6-8101-64279d56acab.png)

Can you verify that there are no js-errors in your case or provide additional reproduction steps?

**Comment by SergioBertolinSG** [comment]
It is working now with current master. Thanks for your analysis @IljaN .
