### ISSUE TITLE
Undefined \OC::$server->getSessionCryptoWrapper() crashes cron

### ISSUE THREAD

**Issue by giacmir** [owncloud/core#26291]
My cron job fails with this error `Call to undefined method OC\\Server::getSessionCryptoWrapper() at \/var\/www\/owncloud\/cron.php#57`

I'm using OC 9.1.1 installed from apt-get on Ubuntu 14.04

**Comment by PVince81** [comment]
The method exists in v9.1.1: https://github.com/owncloud/core/blob/v9.1.1/lib/private/Server.php#L1301

Please double check the source code. Best is to check the admin page, it might reveal integrity check failures telling you which files in the source code are corrupt.

**Comment by giacmir** [comment]
The method exists in my installation too, but during cron execution it throws that error. I don't think there is source corruption. 

It seems that the CryptoWrapper is not ready ad that time or it fails to initialize. Perhaps some php library missing from package dependencies?

**Comment by PVince81** [comment]
I don't think so, because the error message says that the method `getSessionCryptoWrapper` is missing as if it was missing in the source code.
If the crypto wrapper was not initialized it would still run that method, but that method might return `null` and the message would be different.

Try clearing APC/APCu cache which might contain old source code ?

**Comment by giacmir** [comment]
I tried purging the APC but with no success.

**Comment by midimarcus** [comment]
I can add (I'm a collegue of @giacmir ) that invoking cron.php from CLI with web server user works fine.
