### ISSUE TITLE
Cannot set a file as favorite from the star icon in the sidebar in tags menu

### ISSUE THREAD

**Issue by davitol** [owncloud/core#26437]
### Steps to reproduce
1. Set a tag to a file
2. Go to tags menu
3. Search by the tag set
4. Open the sidebar of the folder found
5. Try to set the file as favorite by clicking on the star icon
### Expected behaviour

The file should be set as favorite
### Actual behaviour

The file is downloaded to local
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"9.1.2.3","versionstring":"9.1.2 RC1","edition":""

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```

```
### Client configuration

**browser**

 Mozilla

![favtag](https://cloud.githubusercontent.com/assets/10596560/19592079/76ee5794-977a-11e6-8484-ca261473b449.gif)

**Comment by davitol** [comment]
Same behaviour in Share by Link, Share with others menu etc

**Comment by PVince81** [comment]
Ah... seems to be in all the views that don't have the favorite info inside the list

**Comment by mjobst-necls** [comment]
I found out that just adding 
- 'systemtags',
- 'shares.self',
- 'shares.others',
- 'shares.link'

to _allowedList_ in _tagsplugin.js_ makes the favorite buttons work on detail views.

The negative side of this is that the favorite button is also available in the file list then.
This seems not to be avoidable at the moment.
A possible approach is adding an options argument to the attach function of this plugin so that we can tell them not to add the favorite column to the list but we are still able to use the functionality.

What do you think?

**Comment by PVince81** [comment]
@mjobst-necls this is fine for the "systemtags" view, because the favorite information is available in the sever response (Webdav query).
However for all the "shares.*" views, a different API is used and it doesn't contain the favorite flag in the response, so the GUI cannot show the correct state for it.

Ideal solution would be to either extend the OCS Share API to also include favorite state, or to move the sharing to Webdav API (which is a huge task as we don't have a Webdav API for sharing at this point).

Another idea would be to re-fetch the file info from the server when opening the sidebar. The fetching would do a single PROPFIND for this file and could include the favorite info as needed. But this is not enough because we need the state info for the file list star already. So an additional hack here would be to hack the list (CSS?) to remove the star from the list itself.

So in the end the quickest hack I guess is to not add anything to `allowedList` but make the sidebar (aka details view) re-fetch the FileInfo if the `favorite` attribute is missing.

**Comment by PVince81** [comment]
@mjobst-necls I guess this is fixed now or did I miss something ? (can't remember the details)

**Comment by mjobst-necls** [comment]
@PVince81 Yes, this is fixed.
