### ISSUE TITLE
Share tool : users input discrepancies compared to Share link tool

### ISSUE THREAD

**Issue by ennder** [owncloud/core#26781]
Hi,

In the share resources page, the user search box has a few issues that we don't find in the one for the share by public link.
- We can't find users by typing some letters of the LASTNAME (must give the first letters of the Firstname)
- Case sensitive
- Accents not recognised
Can the search rules be the same with the Share link tool ?

Tested with Owncloud 9.0.2

**Comment by RealRancor** [comment]
> Tested with Owncloud 9.0.2

The same as in https://github.com/owncloud/core/issues/26780 is also valid here:

> As you're running an quite outdated version (9.0.6 and 9.1.2 are current) *snip*
>
> In general its also highly advised to always use a recent version before reporting any issues. This makes sure you're not reporting issues already fixed.

**Comment by ennder** [comment]
Issue stil present with 9.0.6.

We will re-check if it is still present after the update to 9.1

**Comment by ennder** [comment]
The discrepancies are still present with Owncloud 9.1.2

**Comment by RealRancor** [comment]
Might be related: https://github.com/owncloud/core/issues/26519

**Comment by PVince81** [comment]
@ennder please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md.

The search feature depends heavily on what user backend and how it is configured, especially if you're using LDAP. It is likely that the reason is the same as https://github.com/owncloud/core/issues/26519 so I'm going to close it.

If you think your issue is not related at all to https://github.com/owncloud/core/issues/26519, feel free to reopen and please fill the template. Thanks

**Comment by ennder** [comment]
adding the following two lines to **User Search Attributes** does almost the trick : 
sn
givenName
the only remaining difference with the share link tool are the accentuations (éèô...)
Thanks for your reply.
