### ISSUE TITLE
Maximal Upload-Size changed after update

### ISSUE THREAD

**Issue by davidak** [owncloud/core#2692]
before it was "2 GB", then it was 513MB (don't know if i set this in V-Host of Apache)

this schould be saved in config.php and reset after if it disappears during an update.

Ubuntu-Server 12.04

Apache2

MySQL

PHP 5.3.10-1ubuntu3.6

**Comment by geez0x1** [comment]
I can confirm this bug on upgrading within the 8.0.x releases.

**Comment by PVince81** [comment]
How did you upgrade ? Maybe the max upload was set in .htaccess and that file got overwritten by the upgrade ? (possibly by the package manager)

**Comment by geez0x1** [comment]
Yes, I can confirm the file was overwritten. I'd argue this is not a good place to store such configuration information though; from the other topic:

`Since the information is contained in the htaccess file, it would seem trivial to include a htaccess template, and during the upgrade run it through a search-and-replace to fill in any settings that should be there from the database.`

**Comment by tuxmaster** [comment]
In my case the update from 8.0 to 8.1 using the rpm repo.

**Comment by PVince81** [comment]
Max upload is obsolete in 10.0.0 where Webdav PUT is used, so there is no limit any more for web UI uploads.
