### ISSUE TITLE
Move files_external backends to separate apps

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27049]
Port all external storage backends from files_external to be separate apps:
- [ ] storage backends
    - [x] FTP: https://github.com/owncloud/files_external_ftp
    - [ ] SFTP
    - [x] Dropbox: https://github.com/owncloud/files_external_dropbox/
    - [x] GDrive: https://github.com/owncloud/files_external_gdrive and https://github.com/owncloud/core/pull/28074
    - [x] Swift => deprecate, focus on S3 now
    - [x] S3 => https://github.com/owncloud/files_external_s3
    - [ ] Local: move the backend to core as the storage class is there as well
    - [ ] SMB
    - [ ] DAV / ownCloud: separate app or move to core ?

- [ ] authentication backends
    - [ ] OAuth1: move to core or part of external app ?
    - [ ] OAuth2: move to core or part of external app ?
    - [ ] OpenStack => deprecate, focus on S3 now
    - [ ] Rackspace => deprecate, focus on S3 now
    - [ ] S3\AccessKey: make it part of the S3 app

@DeepDiver1975 FYI

**Comment by guruz** [comment]
>  OAuth2: move to core or part of external app ?
> OAuth1: move to core or part of external app ?

Note that from desktop client perspective, we'd want to possibly only support OAuth at some point. So if you have it external, you're making life harder when installing oC. Maybe not a big issue.

CC @ogoffart

**Comment by PVince81** [comment]
This is not related at all to the desktop or mobile client.

It's the oauth tokens that the OC **server** uses to connect to external storages like Dropbox, etc.

**Comment by PVince81** [comment]
and the auth backends listed here are the ones used to connect to external storages from the server.

**Comment by PVince81** [comment]
Gdrive: https://github.com/owncloud/core/pull/28074 and https://github.com/owncloud/files_external_gdrive, still work in progress as some adjustments are needed

**Comment by Hemant-Mann** [comment]
Hello @PVince81 Currently Google Drive OAuth2 Grant sends a request to ```ajax/oauth2.php``` which is hard coded for authenticating google drive only, now the new dropbox app that I am writing also need **oauth2** authorization so how to go about it?

1. Add a ```switch``` statement in the current ```ajax/oauth2.php``` to authenticate multiple backend by passing in the storage identifier like **googledrive**?
Or 
2. Modify **oauth2.js** in such a way that it will fire an event which can then be handled in the app specific ```js/somejsfile.js``` to authenticate a storage app using OAuth2

Any other thoughts @butonic ?

**Comment by PVince81** [comment]
@Hemant-Mann we should remove these files from core eventually so don't rely on them. Also in the future core (or its files_external bit) must not know about any specific storage implementation.

So I suggest you grab the oauth2.php and oauth2.js files and provide them in your app and adjust them accordingly. Note that to load a custom JS file you need `->addCustomJS(['appname', 'oauth2.js'])` (this was added recently)

**Comment by Hemant-Mann** [comment]
@PVince81 Okay I will provide customJs as mentioned by you but as of now there is no way for the **customJs** to know when the OAuth2 grant is request by the client

See this [https://github.com/owncloud/core/blob/master/apps/files_external/js/oauth2.js#L65](https://github.com/owncloud/core/blob/master/apps/files_external/js/oauth2.js#L65) **A click event** is attached on the button, and the function sends a request to backend `/apps/files_external/ajax/oauth2.php` 

So instead of hard coding what should happen when the user clicks on the button we can trigger another event on which event handlers can be attached in the **customJs** provided separately by each backend config (as you suggest **core** must **not** know about specific implementation)

After this line [https://github.com/owncloud/core/blob/master/apps/files_external/js/oauth2.js#L71](https://github.com/owncloud/core/blob/master/apps/files_external/js/oauth2.js#L71)
_Something like this_
```js
$('.configuration').trigger('oauth_step1', [{
	storage_id: tr.attr('class'),
	client_id: client_id,
	client_secret: client_secret,
	redirect: location.protocol + '//' + location.host + location.pathname + '?sectionid=storage',
	context: $(this)
}])
```

and this event can be handled in the customJS as I am doing it here [https://github.com/Hemant-Mann/files_external_dropbox/blob/dev/js/dropbox.js#L41](https://github.com/Hemant-Mann/files_external_dropbox/blob/dev/js/dropbox.js#L41)

Any thoughts @butonic ?

**Comment by PVince81** [comment]
As you like, feel free to make a PR to core

**Comment by Hemant-Mann** [comment]
PR #28179 with the proposed changes

**Comment by DeepDiver1975** [comment]
Secondary s3 storage integration just got move over to https://github.com/owncloud/files_external_s3.
