### ISSUE TITLE
[7.0.5] Duplicate directory on Firefox

### ISSUE THREAD

**Issue by glannes31** [owncloud/core#27052]
Related to issue 4893
### Steps to reproduce
1. Open Mozilla Firefox  
2. Go to the index files
3. Duplicate directory

### Expected behaviour
One directory

### Actual behaviour
Many directory with the same names

### Server configuration
**Operating system**: redhat

**Web server:** Apache

**Database:** MariaDb

**PHP version:**5.1

**ownCloud version: 7.05

### Client configuration
**Browser: Firefox 

**Operating system: Windows7

Migration in OC9  is very close but i want to know if this issue could be resolved in 7.0.5

**Comment by PVince81** [comment]
OC 7 is already dead, see https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule.

Any fixes that are made are not backported further than OC 9.0, unless critical.

Please try upgrading on a test server and see if upgrading solves the problem. Lots of issues were fixed in more recent versions.

If the problem persists with OC 9.0.7 or later, please reopen.
