### ISSUE TITLE
Feature Request: Add link from own instance

### ISSUE THREAD

**Issue by EmilObermayr** [owncloud/core#27088]
### Steps to reproduce
1. someone shares by link via email to a group of people
2. one of them is a user of the same instance
3. this person would like to "add by link"

### Expected behaviour
This should be possible

### Actual behaviour
It is rejected with a message saying you can't add by link from your own instance

copy from ...
https://central.owncloud.org/t/add-link-from-own-instance/5583
... as requested

**Comment by PVince81** [comment]
Yes, this is currently restricted because it can in some situations cause infinite recursions and kill an instance in case links are mounted in a chain.

There is another discussion here that might be relevant to achieving this: https://github.com/owncloud/core/issues/21602 and https://github.com/owncloud/core/issues/9090

**Comment by EmilObermayr** [comment]
I just re-checked after I did some clean-up in the SSL-configuration and now it works. 
Might it just be a mis-leading error-message? Maybe an incomplete certification-chain leads to such an error? If this is the case, the error message should be more specific.

**Comment by PVince81** [comment]
Could be...
