### ISSUE TITLE
Add core route for oauth callbacks

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#27543]
Idea:

Add a route in core that is used for oauth callbacks, receives the tokens and stores them using the files_external code, then redirects the user to the settings page.

Context:

https://github.com/owncloud/core/issues/27456
https://github.com/owncloud/core/pull/27487#issuecomment-290409611

**Comment by SamuAlfageme** [comment]
👍 Since the redesign of the settings pane in 10.0, personal and admin sections have different urls and therefore any application that gets authenticated from these needs explicit, multiple urls depending on which is going to access the external app. 

Now, when setting up an external storage this becomes a problem: e.g. extract from https://owncloud.org/blog/external-storage-dropbox 

> Under the section OAuth2 Redirect URIs add a new URL http://path/to/owncloud/index.php/settings/admin?sectionid=storage (Replace http://path/to/owncloud/index.php with your valid owncloud installation path) 

This won't be enough as you'll also need to add `http://path/to/owncloud/index.php/settings/`**`personal`**`?sectionid=storage` to the redirect urls in your app in order to get authenticated access the application from both sections. 

It'd be better if ownCloud exposed **an unique URL** for these kind of redirects to avoid duplication.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
