### ISSUE TITLE
Upgrade to 10.0.0: Error 500

### ISSUE THREAD

**Issue by plastikschnitzer** [owncloud/core#27553]
### Steps to reproduce
1. Perform Upgrade from OC 9.1.4 to 10.0.0
2. Copy new version to ownCloud directory
3. Go to ownCloud URL

### Expected behaviour
The Upgrade screen should show up to perform the database upgrade

### Actual behaviour
Error 500

### Server configuration
**Operating system**: 
FreeBSD 10.2

**Web server:**
Apache/2.4.18

**PHP version:**
7.0.11

#### Web server error log
  /path/to/owncloud/.htaccess: Invalid command 'php_value', perhaps misspelled or defined by a module not included in the server configuration

### My fix:

```
<IfModule mod_php7.c>
 php_value upload_max_filesize 513M
php_value post_max_size 513M
php_value memory_limit 512M
php_value mbstring.func_overload 0
php_value default_charset 'UTF-8'
php_value output_buffering 0
</IfModule>
```

**Comment by kdslkdsaldsal** [comment]
Most likely caused by https://github.com/owncloud/core/pull/26747 which shows this issue on every other php module for Apache (e.g. php-fpm, suPHP).

@plastikschnitzer You should note that ownCloud is fully untested on other webserver PHP modules then mod_php. (mod_php is the only officially supported module as seen in the [documentation](https://doc.owncloud.org/server/latest/admin_manual/installation/system_requirements.html#supported-platforms)).

There is absolutely no guarantee that oC will run at all on your environment. It might also happen that you're facing issues / problems / bugs not happening on the tested mod_php module.

**Comment by plastikschnitzer** [comment]
Hi @kdslkdsaldsal – I knew about this mod_php requirement and possible problems with other php modules, checked back my server and noticed that I have my testing server configured to run php with fcgid at the moment (ooops), switching it back to mod_php (what I use normally due to known reasons) fixed it right away. 

OC 9.x works with fcgid in my case, so I suppose if this .htaccess will make it from beta to the final release, it might result in many problems for admins who are not aware of the php environment they are running OC in.

But so far no other issues found on the first look around, so thumbs up from my side, I will keep testing.

**Comment by kdslkdsaldsal** [comment]
> so I suppose if this .htaccess will make it from beta to the final release, it might result in many problems for admins who are not aware of the php environment they are running OC in.

Yes, sure. 😃  I think it makes absolute sense to revert the changes from https://github.com/owncloud/core/pull/26747 to avoid such issues.

**Comment by PVince81** [comment]
@phisch can you verify and take care ? ^

**Comment by phisch** [comment]
The change in #26747 was just because it seemed redundant and a user asked about it. So if we can prevent some requests by reverting it, we should do that.

@plastikschnitzer can you quickly explain how your server was setup? Because i am not sure what component of your setup was reading the `.htaccess` file.

**Comment by plastikschnitzer** [comment]
Server configuration:

Operating system:
FreeBSD 10.2

Web server:
Apache/2.4.18 (FreeBSD) OpenSSL/1.0.2g mod_fcgid/2.3.9

PHP version:
7.0.11

Its the default server setting from a server provider in Germany. With mod_php, everything works well.

**Comment by kdslkdsaldsal** [comment]
In this case Apache will read the .htaccess but doesn't know the ``php_value`` as only mod_php (and not mod_fcgid) will add support or making this option known to Apache.

**Comment by magf** [comment]
`apt-get -y install libapache2-mod-php7.0`

**Comment by phisch** [comment]
Yes, as long as you are running `mod_php` you should not experience this issue. In the meanwhile, apply #27748 or wait for the next update that will include this PR.
