### ISSUE TITLE
OwnCloud How to set limit for a number of file upload to OwnCloud at a time

### ISSUE THREAD

**Issue by phantom1425** [owncloud/core#27620]
Dont Know if this is the right place to post the question but i'm stuck here , need help

I'm having a problem that how can i set a limit number for quality of file upload to OwnCloud  at a time ?
I means i'm the admin and i want to set an limit for user , they can only upload 3 file at a time in OwnCloud 
I'm using window server 2008
Sorry for my English , it's just my secondary .

Thanks so much

**Comment by kdslkdsaldsal** [comment]
> Dont Know if this is the right place to post the question but i'm stuck here , need help

Unfortunately this is the wrong place. This is a bugtracker of ownCloud. Questions like this belongs to https://central.owncloud.org/

However please note:

> I'm using window server 2008

ownCloud is unsupported on Windows since version 8.0. Please move to a linux based host before searching for issues in your current installation.
