### ISSUE TITLE
add a uid parameter to the user:sync command

### ISSUE THREAD

**Issue by butonic** [owncloud/core#27707]
We should add a uid parameter to the user:sync command, so admins may trigger individual updates by other means. I know eg, that for https://github.com/gonicus/gosa you can configure scripts that should be triggered when a user is changed in ldap.

**Comment by PVince81** [comment]
are you guys working actively on this or be committed to do this for 10.0.2 ? if not, move to triage milestone

**Comment by Peter-Prochaska** [comment]
I am busy with security issues, i don't work actively on this.

**Comment by PVince81** [comment]
wasn't this added already ? @butonic @jvillafanez

**Comment by jvillafanez** [comment]
I think the best option is to create a new command to sync just one user, to be decided on the specs (only one user or severals, how are we going to refer to the users from the outside - uid, mail, other) since they will likely depend on what information those hooks handle.

The reason to create a new command for this is that the current user:sync command can't support it in a clean way: the command is prepared to handle all the accounts at once not just a set of them, and also there are options to manage missing accounts that don't make sense if we're going to sync a small set of accounts.

**Comment by PVince81** [comment]
moving to triage for later rescheduling

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
PR is still WIP: https://github.com/owncloud/core/pull/28212
