### ISSUE TITLE
Default quota value should be set to a oC user when we choose this option

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27803]
### Steps to reproduce

1. As oC admin go to Users page
2. Set quota as default for a userA
3. Login with the userA

### Expected behaviour

Quota value should be the one that was set as default

### Actual behaviour

No quota is available even changing the default quota value in users page

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":""10.0.0.12""

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**

 Mozilla

**Comment by PVince81** [comment]
@davitol if you add labels please also ping people, especially for critical and high, else it might get unnoticed. Usually when looking at incoming tickets I look at the unlabeled ones

**Comment by PVince81** [comment]
Regression from which version ? Did it work in 9.1.5 ?

**Comment by PVince81** [comment]
Regression from 8.2.11.

Basically 8.2.11 behaves properly and 9.0.9 doesn't.

The correct behavior in 8.2.11:
When nothing was selected, the dropdown says "Default".
If you set an actual default to 1 GB and refresh the page, it stays on "Default!
Those who you set manually to "Unlimited" also stay unlimited.

The wrong behavior since 9.0.9:
When nothing is selected, the dropdown says "Unlimited".
If you set a default quota to 1 GB and refresh the page, any entry that said "Unlimited" now say "1 GB".
And those that you set on "Default" either also show 1 GB or stay "Default" depending on the version (9.0.9 vs 10.0.0).

A bisect shows that the commit 3a796d1e1533febc63a2719816815b47f2065e82 from https://github.com/owncloud/core/pull/22252 related to quota functions is what broke the behavior.

We should bring it back to how it worked before.
In 10.0.0 the code likely moved to a different location due to account table, so the fix will likely look different there.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/27895
