### ISSUE TITLE
Update data fingerprint automatically when backing up?

### ISSUE THREAD

**Issue by guruz** [owncloud/core#27852]
So that https://github.com/owncloud/documentation/issues/2360 (to be documented better) does not need to be done anymore.

FYI @ogoffart @PVince81

**Comment by PVince81** [comment]
How should OC detect that an admin made a backup ?

**Comment by guruz** [comment]
@PVince81 That I wonder too. I was thinking about ```config/``` or ```data/``` but that would be backed up too normally? 

Maybe https://dba.stackexchange.com/questions/50870/is-it-possible-to-get-the-last-restore-date-of-a-mysql-instance ?

**Comment by PVince81** [comment]
Normally an admin would manually backup the config and data folders and the database. Since this is not automatic the admin needs to run the occ command to tell OC that a backup has been made.

**Comment by guruz** [comment]
@PVince81 but it looks like with https://dba.stackexchange.com/questions/50870/is-it-possible-to-get-the-last-restore-date-of-a-mysql-instance you might not need this. You could derrive the fingerprint from CREATE_TIME

 Just an idea to make things more robust for the naive restorer (who can't be blamed because it was not easy to be found in documentation)

**Comment by PVince81** [comment]
Ah, interesting. But then it's Mysql specific. Not sure how reliable.

**Comment by PVince81** [comment]
then we could also think of other tricks like saving values outside of config.php and outside of the DB and have the same value in the DB. If the value is different then it means the DB has been restored or so.

**Comment by guruz** [comment]
Related https://github.com/owncloud/client/issues/2325#issuecomment-306383147

**Comment by thetrial** [comment]
Can’t OC simply check any attributes of files inside its stock against files laying outise to sync? Especially Raspberry Pis are backed up with dd I guess. So it’s a snapshot of the whole SD-card instead of backups of directories. I miss this checkup in OC after a replay (and rewind!), that OC checks its stock against the situation on clients. This could also concern caldav and maybe carddav. I see that e. g. iCal (OSX) does not delete new(er) events, but it seems the sync of these new or changed instances are not synced correctly. If one (re)opens such an event, it gets deleted.

So let's say there exists fileA.abc, fileB.abc and fileC.abc. Today, on clients and on the server. Now the server has to be rolled back to the situation a week before. A week before fileA.abc was the same. fileB.abc did not exist and fileC.abc had been in an older state.

What happens? fileA stays, fileB.abc now is synced to the server (in OC 9 it was deleted from the clients!) and fileC.abc triggers a conflictfile. Instead the newer fileC.abc from the client should be synced to the server, I think. To reach an older version should either be realized via versions (I don't use that) or via the onboard tools of the machines that are synced (desktops, laptops, not handhelds). OSX has time machine, Windows had shadow copies, I guess.

**Comment by PVince81** [comment]
@thetrial this would require OC to have a duplicate of the oc_filecache table stored in a different database/location to be able to check against an older state.

Another problem is that a backup is not only about files. Some people use OC mostly for calendar and don't use the file feature much, so while all files from the reference table might be the same, other tables would be different. And duplicating the whole database for every access sounds a bit too much, especially for big setups.

**Comment by thetrial** [comment]
Well, I'm a bit irritated that it is not possible to rely on a checkup by a restored server. Data (files) *is* on the clients, it has attributes. Data is also in calendars or address books, they should have attributes and time stamps. If someone replays an older image to a Raspberry Pi or VM, Owncloud is not reliable anymore. Data is missing, dates are missing. This is quite strange. Why the stock of the database is not checked against the data of clients? If there is something (files, dates, appointments etc.) on clients dating to 1.6.17 and the replayed Owncloud was from the 15.5.17, I'd await that the system »understands« those files and dates must be »newer« – so they *must* be synced towards the server instead getting deleted or forgotten by the server. IMHO.

**Comment by guruz** [comment]
ownCloud sync algorithmn is not based on dates. Maybe this talk helps to understand (i think i haven't watched it though..) https://cds.cern.ch/record/1970463?ln=de

**Comment by PVince81** [comment]
Not technically possible without an external system. External system would add another dependency for running ownCloud. Closing, unless there are better ideas.

**Comment by guruz** [comment]
I re-open this because I still think a solution that is good a lot of use cases is https://github.com/owncloud/core/issues/27852#issuecomment-301720228
