### ISSUE TITLE
Feature Request: Warning before deleting user

### ISSUE THREAD

**Issue by cornelinux** [owncloud/core#28084]
### Steps to reproduce
1. Delete a user
2. All user data is gone

### Expected behaviour
I was expecting that the data would not be deleted.
So I would like some kind of warning message like:

> If you delete this users, all the user's data will also be deleted. 
> Do you want to delete the user and all his data?

(I was blindly deleting a user due to #28083.)

### Actual behaviour
The data of the user was deleted without asking.

### Server configuration
**ownCloud version:** 10.0.2

**Comment by kdslkdsaldsal** [comment]
Ref to a previous request about that: https://github.com/owncloud/core/issues/8347

There have been a few additional requests like this but most where just rejected because of "There is the undo function, just click that if you have accidentally deleted a user.

**Comment by cornelinux** [comment]
OK, I see this, https://forum.owncloud.org/viewtopic.php?t=32047
you can undo that.
But till I realized, that the data was deleted, it was gone!
And if you are not aware of the data being deleted, then there is no need to undo. Because in fact I *wanted* to delete the user. Not the data.

**Comment by kdslkdsaldsal** [comment]
According to the documentation this is the expected behavior:

https://doc.owncloud.org/server/10.0/admin_manual/configuration_user/user_configuration.html#deleting-users

At some point in time someone (i think they moved to nextcloud now) decided that the "undo user" functionality like explained in the link should be implemented. IIRC all requests for a warning / checkbox for the user deletion (like yours) where closed with the explanation that the undo functionality is a better user experience then the confirmation warning.

But IMHO your request makes absolutely sense and something like github is doing for the deletion of a user / repository would prevent such issues.

**Comment by PVince81** [comment]
Yes... old design decision. For stuff as critical as deleting users we might want something different.

@felixheidecke thoughts ?

**Comment by hajika** [comment]
we could do something like in the calendar app where your have to wait for a 3 seconds countdown first before your can push the final delete button. That is effective against mistakes and a nice interface option. But still the undo option should stay.

![cloud cal delete](https://user-images.githubusercontent.com/27491258/30341999-b345d190-97e7-11e7-9013-286a27d94571.png)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
Yeah, something as critical as deleting a user should rather have a confirmation dialog I think.

For files it's a different story as long as trashbin is enabled.

@felixheidecke thoughts on this ? If we agree on the dialog, someone could submit a PR that calls `OC.dialogs.confirm()`
