### ISSUE TITLE
[FR] Add version number to owncloud folder in owncloud-X.X.X.tar.gz

### ISSUE THREAD

**Issue by haukman** [owncloud/core#28097]
If you download the tar file from owncloud.org/download and unpack it, the folder is always called "owncloud" regardless the version. 

This led to issues at several users/customers during an upgrade, e.g.:

During the install of ownCloud 9.1.5 the admin downloaded the tar file to /home/admin and unzips it. This created a folder called "owncloud". A few month later this admin wants to upgrades his ownCloud to 10.0.2 and downloads the new tarfile also to /home/admin and unzips it without deleting the old "owncloud" folder. The admin assumes that they old content was overwritten during the extraction of the newer ownCloud tar file and tries to do the upgrade. This upgrade will fail with strange errors and the admin will waste a lot of time until he understands that he created a faulty owncloud folder.

Solution: Add the version number to the owncloud folder inside the tar file like owncloud-10.0.2.tar.gz - this will prevent things like this to happen.

@butonic @pmaier1

**Comment by butonic** [comment]
👍

**Comment by danimo** [comment]
The desktop client does it correctly:

1. The directory in the tarball is named `<application>-<version>`. If you want to tar over your existing installation, you do `cd owncloud; tar --strip-components=1 -xf owncloud-<ver>.tar.gz`

2. The root directory carries a [`.tag`](https://github.com/owncloud/client/blob/master/.tag) file which gets substituted with the current sha by `git archive` with a hint by [`.git-attributes`](https://github.com/owncloud/client/blob/master/.gitattributes). There might even be a way to ensure that for tags, it writes the tag instead of the commit id. The same can be done for apps.

Just please do not try to be clever and come up with something entirely different. Also, make sure that the resulting files are not accessible from the web.

**Comment by butonic** [comment]
@danimo Nooooooooo, don't explain to people how to untar the contents into an existing folder. That is the root of hard to debug problems ;)

**Comment by danimo** [comment]
That was the original reason why the folder did not carry a version. One argument less then for not having it :-)

**Comment by Helios07** [comment]
Since the first thing I do after unpacking the source code is to rename it to contain the version number, I would really appreciate this proposal.

**Comment by PVince81** [comment]
I'd suggest changing this in the next major release to avoid surprises, especially for people running automated scripts that download the tarball that might suddenly get "surprised" that the extracted folder is different.

**Comment by PVince81** [comment]
@patrickjahns for the future build system

**Comment by PVince81** [comment]
we could consider that for ownCloud 11, might break most of automated scripts out there though

**Comment by patrickjahns** [comment]
@PVince81 - might be superseeded with the new build system already
