### ISSUE TITLE
Uploading same file twice to a public shared folder without listing doesn't show its real name.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#28132]
### Steps to reproduce

1. Create a folder 'shared'.
2. Share by link 'shared' folder. Enable "Allow editing" and disable "Show file listing".
3. Open the shared link.
4. Upload a file 'file.txt'.
5. Upload 'file.txt' again.

### Expected behaviour
In the uploaded list appears 'file.txt' and 'file (2).txt'.

### Actual behaviour
'file.txt' appears twice. Like if it was updated. But it wasn't because it was renamed adding a 2.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2.1","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Chrome

**Logs**
```
```

cc @PVince81

**Comment by PVince81** [comment]
This is by design because: we don't want any users who upload files there to be able to guess that a file already exists and might have been uploaded already by another user.

Example:

1. Link is sent to user1 and user2
1. user2 is malicious and knows that user1 will upload a file "secret.txt" at some point
1. user1 uploads "secret.txt"
1. user2 uploads another "secret.txt". At this point, if the file comes back as "secret (2).txt" then user2 will know that user1 has already uploaded said file. If the file comes back as "secret.txt" then user2 can wait a bit longer.

At least this is how I thought this makes sense. @Peter-Prochaska thoughts ?

**Comment by PVince81** [comment]
basically you could "scan" the folder by uploading all possible file names and checking whether they receive a "(2)" to know that such file exists, which defeats the purpose of hiding the file listing.

**Comment by PVince81** [comment]
also if two completely different users happen to upload a file with the same name, you don't want it to appear with "(2)" as it might confuse them...

the security bit above prevents us from returning any information in headers or so that would let an attacker know about the fact that the file is duplicated even if we don't show it in the UI.

we could add a dummy in the JS code that will simply append a number if the same file name is uploaded multiple times, even if it doesn't match what's on disk... in the end that one user won't be able to verify.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
Works as expected IMO

**Comment by SergioBertolinSG** [comment]
> basically you could "scan" the folder by uploading all possible file names and checking whether they receive a "(2)" to know that such file exists, which defeats the purpose of hiding the file listing.

Yes, makes sense.


Anyway the files drop view could show the already uploaded files (instead of the file names list) and detect if one of them was already uploaded, overwriting it. 

Just an idea for the next improvements on this feature.
