### ISSUE TITLE
Files Locket in Amazon S3

### ISSUE THREAD

**Issue by IceLuck** [owncloud/core#28568]
Hi There

I'm using owncloud version 9.1 on ubuntu 14 in amazon EC2.

My files stay mounted on /mnt/s3, this is a redirect amazon S3 bucket.

When I execute the command "sudo -u www-data php occ files:scan --all" ocurs this problem:

Exception during scan: "files/e8482945c9011a1fad7f0293d9760c26" is locked.

How to solve this problem?

Tks
Luciano

**Comment by hodyroff** [comment]
Are you saying that your S3 bucket is mounted using the Linux FUSE driver and you do use that as primary file system? In order to do a file scan that will not deliver sufficient performance. I am sorry, but this way will not work and is not supported. Recommend a reliable and high performance file system as primary storage, or S3 protocol directly with our Enterprise Edition which you can try via marketplace.owncloud.com - even there you will need good primary storage for trashbin and versions (this is worked on).

**Comment by kdslkdsaldsal** [comment]
Adding to this please always make sure to fill out the issue template shown when creating a new issue. This is asking you various additional info about your environment (e.g. the full / detailed ownCloud version etc.) which are currently completely missing in your report.

Adding to this general info about the "file is locked" message is available over at central: https://central.owncloud.org/t/file-is-locked-how-to-unlock/985
