### ISSUE TITLE
Delete an app should also delete the corresponding database tables the app has created

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#29059]
### Steps to reproduce
1. Download app eg Audio Player
2. Let it run and decide to disable AND delete it

### Expected behaviour
The deletion of an app should also delete the tables an app has created.
Else you get orphan database tables.

### Actual behaviour
Database tables remain and are orphand.
Unknown side effects possible.
![image](https://user-images.githubusercontent.com/3321281/30641416-3bb61146-9e07-11e7-8b9a-c191f6afba2d.png)

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** Mysql

**PHP version:** 7

**ownCloud version:** 10.0.3.3

**Updated from an older ownCloud or fresh install:** from 9.1

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

no complains

**Config Report**
[config_report_20170920.txt](https://github.com/owncloud/core/files/1317365/config_report_20170920.txt)

**Are you using external storage, if yes which one:** local, smb, ftp

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera, Safari

**Operating system:**
W7, macOS

#### ownCloud log (data/owncloud.log)
nothing related

**Comment by phil-davis** [comment]
There are plenty of tricky parts here. If the sysadmin just wants to delete the app and is about to reinstall it (because of some weird trouble they are having or...) then they likely want to "keep settings/data". For the "equivalent" thing in deleting and re-installing a program on an operating system, the program uninstaller often asks if you want to keep the settings (e.g. if you are about to re-install the same or some equivalent program).

ownCloud apps are likely to ave 3 areas of stuff in the system:
1) app settings (on-off switches in the app config...)
2) app-specific database tables that have meta-data about the app data
3) actual files that "belong" to the app, or are "playable" by the app

Usually (3) are not deleted on app deletion (that would be like if all *.odt files on your system were deleted when uninstalling LibreOffice). But (1) and (2) could be optional checkboxes on uninstall "keep app settings", "keep app meta-data" (that needs better words that a user will understand).

The there is the problem if an app is deleted while keeping (1) or (2) and never re-installed, or re-installed ages later when the app version has moved on so far and the settings/meta-data are now all wrong.

**Comment by mmattel** [comment]
For (1) are those app settings stored in tables belonging to core or are they in own app specific tables?
For (2) these are those tables containing the majority of data.
For (3) as far I remember, those files are captured by the files table - so no need to touch that.

Imho, (1) needs clarification, I have no clue about, then we could go into the next round of the discussion

**Comment by mmattel** [comment]
@PVince81 
Question: when adding an app (any you can think of), will this app run thru a process where "mandatory" settings are added into an oC core related table for parametrisation? Or is app specific parametrisation data added only into app specific/related tables?

**Comment by mmattel** [comment]
There is one table ``oc_preferences`` that contains app config data - as far as I see it.
Pls correct if something is missing.

userid | appid | configkey | configvalue 
--- | --- | --- | ---
user_x | audioplayer | category | Folder-53618 
user_x | audioplayer | navigation | true 
user_x | audioplayer | path | /iTunes_media/ 
user_x | core | lang | de_DE 
user_x | files | file_sorting | name 
user_x | files | file_sorting_direction | asc 
user_x | files_external | config_version | 0.5.0 
user_x | firstrunwizard | show | 0 
user_x | music | path | /iTunes_media/
user_x | rainloop | rainloop-autologin-password 
user_x | rainloop | rainloop-email 
user_x | rainloop | rainloop-password | kfhwaw  

Seeing that, it would be great if apps that create their own tables would write down their table names here...
As I am running 10.0.3, you see that I already have orphand rainloop entries and apps I deleted (audioplayer) have orphans too...

**Comment by PVince81** [comment]
Disabling an app should not automatically delete their tables, as disabling might happen on purpose during a failed update or incompatible update.

When uninstalling, yes, maybe. Need to detect when an app got uninstalled.

Not sure about detecting whether the app code is missing to consider it a deletion. Best would be to have an occ command to cleanly uninstall apps and run their uninstall routine. AFAIK the market app now has a command to uninstall apps.

@VicDeo @DeepDiver1975 @patrickjahns do you guys know more about this process ?

**Comment by patrickjahns** [comment]
> Not sure about detecting whether the app code is missing to consider it a deletion. Best would be to have an occ command to cleanly uninstall apps and run their uninstall routine. AFAIK the market app now has a command to uninstall apps.

Agreed on the part, that disabling should not remove anything. Only when explicitly calling an uninstall.

Maybe we should have a routine present that allows apps to hook into a "PreAppRemove" hook, so applications can clean up after them? For owncloud itself to take care of that, we would require a lot of internal knowledge of the application itself to clean up (which I don't see feasible).

**Comment by mmattel** [comment]
I was not talking about disabling only about deleting...
Agreeing that disabling should not delete tables.
Currently it seems that an app creating tables on its own does not write it down (eg in oc_preferences) which one it created so deleting an app produces orphand tables.

I do not know if this is possible, but it would be a start when an app wants to create a table, the table name is stored in oc_prefrences. (catch the create table statement). So finding tables corresponding to an app and manage it when you delete the app would become more easy.

When an app gets deleted by the user via browser or occ isn´t that a job done by core?

**Comment by PVince81** [comment]
I found this: https://github.com/owncloud/core/blob/v10.0.3/lib/private/App/InfoParser.php#L82

This means an app can provide repair steps / migration code to delete whatever tables the app has created. Not sure if this bit was tested though.

I also seem to remember that it was possible for an app to provide a file "appinfo/uninstall.php" but am not 100% sure. Grepping for "uninstall" didn't show any related code.

**Comment by phil-davis** [comment]
You really need to give the admin the choice about what to do - like most 'apps' on my laptop, when I uninstall them (FreeFileSync, XxxDownloadManager...) they will have a checkbox somewhere to "keep settings" and I can check that or not. If I am intending to reinstall the app right away (for whatever reason) and it is not because my settings are corrupt, then I choose "keep settings".

So the same goes for ownCloud apps - in the UI provide a checkbox so the admin can "keep app data and settings" or not. Then I guess the ``occ`` commands would also need to have that parameter. Then what should be the default for "keep app data and settings"? Should the checkbox be shown both when disabling the app and when uninstalling it? It needs a bit of thought...

**Comment by patrickjahns** [comment]
> I do not know if this is possible, but it would be a start when an app wants to create a table, the table name is stored in oc_prefrences. (catch the create table statement). So finding tables corresponding to an app and manage it when you delete the app would become more easy.

That assumes the application uses specific creation/migration options - but what if the create statement is simply executed as raw database statement? 
I see the responsibility here by the application - the application should know best what data it manages. (And what steps to take if the data should be removed - just imagine foreign key constraints etc.)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
