### ISSUE TITLE
Have a way for ownCloud to know if it is in a "hosted" environment

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#29106]
There are situations where [doing something|setting something up] on the webUI can be not advisable (or just a straight out bad idea) if the installation does not have command line access. e.g. enabling the encryption app and switching on encryption.

A bit of discussion here in documentation:
https://github.com/owncloud/documentation/issues/3385#issuecomment-331114266

Perhaps there could be a config setting like "hosted => true" or "no-command-line => true" or some other way for a hosting provider to be able to signal to ownCloud that the installation(s) are "knobbled" and so they do not want to let the "admin" user in the web-UI be able to do "dangerous" stuff that is subsequently going to need command line access...

Then ownCloud code could respect this and either never even let the user do some things, or at least give them a big red warning and make them click "yes" 10 times to do it.

**Comment by hodyroff** [comment]
We do have a role concept we like to adhere to. Will put the slides on slideshare or here to better discuss this. Indeed the ownCloud Admin is supposed to get the admin account and should not be able to destroy anything in the system. If we have leftovers for that option in 10.0.3 lets identify and fix them.
For anything else it should be needed for the systemadmin to first do something so that the ownCloud Admin can then do the rest.
