### ISSUE TITLE
External Sites as default APP

### ISSUE THREAD

**Issue by maesitopi** [owncloud/core#29578]
### Steps to reproduce
1.Enabling External Sites & add a Website
2.Configure external sites as default app in config.phh
3.Access nextcloud Default Page

### Expected behaviour
The External Site which has been defined should be shown at logon or by pressing the home button in nextcloud.

### Actual behaviour
Nextcloud switches to the "files" app, as it cannot access to the external sites. Surely because the external sites are seperated in numbers like:

- external/1
- external/2
- ...and so on

There has been a Pull request on owncloud for this issue: https://github.com/owncloud/core/pull/28962

Tried following config.php Settings:
defaultapp' => 'external'
'defaultapp' => 'external/1'
'defaultapp' => 'external?id=1'

### Server configuration
**Operating system**: Ubuntu 16.04

**Nextcloud version:** 12.0.3

**Comment by DeepDiver1975** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by maesitopi** [comment]
Wrong Fork. Sorry for that.
