### ISSUE TITLE
[FR] occ maintenance:bgjobs

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#29603]
This Feature Request is about the idea to have the possibility to list the backgroundjobs ownCloud is automatically running itself when eg using cron.php

``./occ maintenance:bgjobs --list`` [default: list]

Will give the admin the knowledge what oC is doing and what he needs maybe to do himself.

@PVince81

**Comment by PVince81** [comment]
I thought we had a ticket already but couldn't find it. Thanks for raising. Yes, I think it makes sense.

Would be good to have commands to do the following:
- run cron.php (yeah, instead of calling that file directly)
- list existing jobs with detailed information as in the database (last run, next schedule, etc)
- add jobs
- delete jobs
- clear all one-shot jobs (expiration jobs) and keep only app-related repeated jobs

**Comment by PVince81** [comment]
- run a specific job by id

This would be useful for automated tests!
@owncloud/qa

**Comment by PVince81** [comment]
Ah! so it was a PR, not a ticket. Thanks for the link.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @tomneedham.
