### ISSUE TITLE
LDAP - long strings instead of Username, in Users list, calendar links, maybe more..

### ISSUE THREAD

**Issue by lejeczek** [owncloud/core#29678]
hi
owncloud-mysql-9.1.5-1.el7.noarch
owncloud-httpd-9.1.5-1.el7.noarch
owncloud-9.1.5-1.el7.noarch

Having a default vanilla LDAP backed users can log in just okey but Admin shows a list of users with strings instead of real "Username".
Calendar is also affected as it uses these strings in caldav links and users cannot connect to such calendars for authentication fails, so it seems.

I there a fix/patch to 9.1. version? I'd ideally avoid forced upgrade if it was fixed, as I'm on Centos.

many thanks, L

**Comment by kdslkdsaldsal** [comment]
@lejeczek Please note that this is a bugtracker of ownCloud. Support questions like this needs to go to https://central.owncloud.org/ (you can login with your github account there).

At central you will find some experienced users which helps you to configure your LDAP connection in ownCloud correctly so it is using the Usernames/Logins instead of the UUIDs

**Comment by lejeczek** [comment]
I've just tried 9.1.7 (stable) - the same problem.
LDAP backend is pretty regular, samba uses it, if it helps I can shed more light on ldap.

**Comment by kdslkdsaldsal** [comment]
Just check central as already pointed out. See e.g. https://central.owncloud.org/t/ldap-user-created-with-uid/7969
