### ISSUE TITLE
UI tests should be skippable for specific oC versions

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#29802]
### Steps to reproduce
1. run UI tests on older versions of oC (e.g. 10.0.3)
2. tests that check for bugs that are fixed in master/stable10 branch but not in the tested release are failing

### Expected behaviour
it should be possible to skip tests that are known to fail in a specific version. e.g. `@skipBeforeOC10.0.4`

@phil-davis @patrickjahns @davitol @SergioBertolinSG comments?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

**Comment by phil-davis** [comment]
If we already had full test coverage, then this would not be an issue, because the tests included in the ``v10.0.3release`` tag would cover all the features of v10.0.3 and would pass. But it swill be useful because (both for API and UI tests) we are still extending the test coverage. So it is useful to run the latest full test suite in ``stable10`` or ``master`` against some older tarball from v10.* so as to run the extended tests, but of course it needs this issue so that tests for foxed bugs can be skipped.

**Comment by individual-it** [comment]
this is actually more difficult that I first thought. Currently I cannot see a way to do `@skipBeforeOC10.0.4`
as we cannot skip from within the PHP code the `start_ui_test.sh` script should get the current oC version and add tags to `BEHAT_TAGS`. But that would mean it would have to add any possible version. e.g. if the current version is 10.0.4 the script would have to add `@skipBeforeOC10.0.5&&~@skipBeforeOC10.0.6&&~@skipBeforeOC10.1&&~@skipBeforeOC11`etc

I think we will have to live with skipping exact versions e.g.  `@skipOnOcV10.0.4`

**Comment by individual-it** [comment]
PR in #29824
