### ISSUE TITLE
Service Architecture

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#29973]
To track technical discussion around this topic:

https://central.owncloud.org/t/service-based-app-imlpementation-to-solve-inter-app-dependencies/1615

From @patrickjahns:
>we should be very cautious with allowing/designing interapp dependencies - 1 level might be fine. ( >A depends on B ) - but what about nested dependencies ? ( C depends on A , but A depends on B ). How will this be resolved for installing owncloud? Also thinking of the delivery mechanism where >customers can click together their owncloud with the apps they want/payed for - the service then >needs to also handle this logic )

**Comment by tomneedham** [comment]
cc @PVince81

**Comment by PVince81** [comment]
Limiting to only one level sounds like a good approach.

**Comment by butonic** [comment]
@tomneedham, @patrickjahns and I were discussing splitting owncloud in base.php just before the routing is called. Up to that point the oc code sets up the sesson. Then the router takes over and calls the responsible controller (webdav is a different story, we also need a single point of entry here).
* Currently, the filesystem apps are loaded before the router is called. this needs to move to inside the app framework or whenthe user folder is loaded.
* user and session management needs to be decoupled from data storage (avatars)

The code until the router takes over is mostly legacy (user management). In order to refactor that and bring in eg a symphony kernel this is the first step.

After the routing we are in the AppFramework and code on this side is mostly a lot cleaner and better tested.

We can do the split without actually forwarding the request to a backend server via a jwt encodod session. But that might be the start for moving to a more service oriented architecture and adding a proper message bus.

Ultimately, this is the start for moving to a more service oriented architecture. The split can be used to eg redirect preview icon requests to a dedicated service. To do that a new DistributedRouter implementation could take into account the route as well as the user or the users groups to decide which backend service should handle a certain request.

Over time the upgrade focus will shift from "How do I get user A from OC version I to OC version II" towards "How do I upgrade service X for User A so that it remains compatible with service Y"

**Comment by PVince81** [comment]
moving to triage
