### ISSUE TITLE
Dedicated sharing tab for federated sharing

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#30151]
Federation is just too hard to understand for the average user. A dedicated sharing tab for federation (next to User and Group shares / Public links) could be a short-term help as it at least separates it from "local" user shares. In the end this will not be a real solution, IMO, but it would provide more clarity for users.

**Advantages**
- There is a clear separation between different types of sharing for end users.

**Disadvantages**
- The change would introduce kind of a double-feature as it's just the same as "local" sharing from a UI POV.
- Clients would need to be adapted on all platforms.
- Not future-oriented as federation has to work seamlessly to become really usable for the average user.

I think for the future of federation we have to strive for a solution that does not require the user to think about if the recipient's account is located on the same instance or another. Fed sharing needs to work seamlessly and performant for that you just share with another ownCloud user as you're used to from other services.

Putting this here for discussion. Opinions?
@PVince81 @mmattel @hodyroff @butonic @DeepDiver1975 @felixheidecke @michaelstingl

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by PVince81** [comment]
It would be good to understand the problem better maybe by observing said users.

There can be multiple aspects to the problem:
- no user creates any federated share because they don't know that it exists
- people create federated shares (maybe with an address someone gave them) but don't understand how to them or what they do (what is federation id ?)
- people did create federated shares and forgot about them and are now wondering what these weird entries are in the list
- ...

Depending on the problem we try to solve, the approach would be different.

If someone doesn't know what a federated share is, they would likely ignore the tab "Federated" if we add it. On the other hand, some curious users might click it to find out what it is but will be welcome only with another autocomplete field without further information. For that one use case we could add something like a question mark that points to help pages / video / picture that illustrates what federated sharing is in simple terms, with a diagram.

In general federated share is likely difficult to understand to someone who doesn't understand that there are actually multiple servers. Maybe we need a less technical term. Could it be a location ? A university might use the word "campus" if each campus has their own instance, so sharing with someone from a different campus is a federated share. (theming could be used to change the term if it helps)

**Comment by PVince81** [comment]
Another problem found today: 
![image](https://user-images.githubusercontent.com/277525/35042601-a4f78862-fb89-11e7-84cd-f869af02adb8.png)

The text is simply too long. Having it in a separate tab would remove the need to have that text.

However, a different approach could be used and have a special avatar for remote users, or have an overlay on top of the avatar that indicates that it's an external user.

**Comment by felixheidecke** [comment]
One of the problems surely is the federated ID syntax which is 100% similar to email addresses. That's even why we have to show _(federated)_ behind emails and federated IDs because they can't be distinguished. If we could somehow change the syntax of those ID, that could make a difference. "Regular" Users wouldn't come into contact with federated anymore and be confused about it.

**Comment by pmaier1** [comment]
I got some user feedback on this:

When users enter something in the sharing dialog the fed share option pops up earlier than user share suggestions. Users don't understand the suggestion, frequently click on that and worry why they get errors or think it's shared even though it actually failed.

Knowing this I had the idea that we could first check if the address is reachable for a fed share and only if it is we display the suggestion. Known fed share connections should be cached.

This could be win-win as we would probably not (or not that much) have to touch clients to be consistent and we would not move away from the long-term goal of just having shares where users do not have to think about where the recipient is located.

Technically feasible?

**Comment by PVince81** [comment]
> the fed share option pops up earlier than user share suggestions

That's some interesting feedback! Maybe just don't display fed shares until the whole list is loaded ?
I'm a bit surprised about this delay though as I thought the list results appears in a single shot.

> check if the address is reachable 

this means that while you are typing an address we ping all the servers from the address you didn't finish typing because you were typing.

**Comment by PVince81** [comment]
I just tested this: the federated entry does not appear *earlier* but it appears *above* the actual user entry in some cases. We could reorder those to make sure the federated entry appears always last.

**Comment by PVince81** [comment]
On the other hand I wonder: we did add some logic that if the entered user id matches a known email address, the federated entry will disappear. So maybe there was a partial match of some sorts.

**Comment by pmaier1** [comment]
More feedback:

**Issue**
Mail addresses at installations have different formats and users frequently enter the wrong ones when they actually want to create a regular user share. They then get suggested to do a federated share which confuses them and/or throws errors/doesn't work.

**Possible solutions**
1) Only display fed share suggestion if it is possible to establish a fed share
We could reduce the pinging to valid mail adresses (x@y.z). This would solve all problems presented so far.
2) Display the fed share suggestion at the bottom of the autocomplete results
This only solves the issue that when users enter mail addresses
- regular users with that mail address would be displayed first.
- a guest suggestion would be displayed first.

If a regular user exists with that mail address we would anyway not display the fed share entry, as you said. If we do 1) we don't need it at all, I guess.

Is 1) really so bad because of pinging or is there a smart solution? Do we have anything else to solve the problems presented?

**Comment by PVince81** [comment]
@pmaier1 do these people even use federated sharing at all ? If yes, would providing a blacklist of domains be a solution ? Basically blacklist some domains from showing up as federated shares like we discussed for the guests apps (https://github.com/owncloud/guests/issues/173)

**Comment by PVince81** [comment]
> We could reduce the pinging to valid mail adresses (x@y.z).

Federated shares are not mail addresses but federated user ids.

I see your point about pinging: people type from left to right so the domain name comes last, so we'd ping invalid domain names until the full domain name has been typed in. I guess that might be an ok solution. However we might need to add some API on the receiving end to be able to ask "is there a user XYZ on this server". Also, only allow pinging for trusted server to avoid hackers spamming servers or scanning for user names.

**Comment by felixheidecke** [comment]
isn't changing the syntax a feasible solution? That would solve a lot of UX and tech problems.
While I am working on the sharing-3.0 dummy … I am coming across the idea to implement public link share also into the same mechanism.

An email like input could be all of the three variations: Username, Usermail, Remote, Public Mail.

**Comment by pmaier1** [comment]
@felixheidecke I don't really understand what you wrote in https://github.com/owncloud/core/issues/30151#issuecomment-364893460. Let's chat about it.

What about the following:

- For trusted servers, user directories can be synced. With this we can only display valid recipients just like with internal sharing. Known recipients should be displayed on top (above e.g. guest suggestions)
- For unknown domains we could do a check if there's a running instance (that can receive fed shares?) behind it (doesn't matter if the user actually is available, IMO). If true we display a suggestion. 

So when users enter a "known" federated user name, they will not have to think about federation and even get a suggestion for the right recipient while there's no risk to click on the wrong entry as guest suggestion will be below and a real user name is suggested above. 

For sharing with "unknown" federated users we first validate if there's an instance available to cope for the issue when users enter wrong addresses. This will anyway only be needed for the first time when a user shares with another user on an unknown domain or not even this if administrators choose to only allow sharing with trusted instances and keep control over them.

With this we only get valid (or semi-valid) results which we can then also display as the first entry, IMO.
What do you think?
