### ISSUE TITLE
SMB domain conflicts

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30184]
### Steps
Note: I haven't actually tried this as I have no environment

1. Setup two SMB users with the same name but different domains: ex: `domain1\testuser` and `domain2\testuser`
1. Setup a SMB share "shared" where both users have access and put some data and subfolders into it
1. Make it so that "domain1\testuser" has only read-only permissions.
1. Setup OC
1. Create a user "user1" and "user2" in ownCloud
1. Let users mount their own shares
1. Login as "user1"
1. Mount SMB external storage and set the domain to "domain1" and user to "testuser".
1. Browse the share. At this point the oc_filecache has scanned it and would contain read-only permissions.
1. Login as "user2"
1. Mount SMB external storage and set the domain to "domain2" and user to "testuser".
1. Browse the share and try to upload something.

### Actual result
Now I couldn't try this hypothetical scenario, needs to be tested.
It is likely that user2 cannot upload anything because oc_filecache contains the read-only permissions as scanned from the first user.

The part that worries me is that both users will get the same oc_storages entry because we don't store the domain part of the user name there. This means that if there is any discrepancy about visible content, permissions, etc between the two users, theses will be in conflict.

### Expected result
Each user should receive their own oc_storages entries to be consistent with the current approach which already does so when the user id is different.

### Versions
ownCloud 10.0.4

@jvillafanez @butonic @tomneedham @mmattel thoughts ?

**Comment by PVince81** [comment]
From what I see the storage id is using `$this->server->getUser()` and said server is initialized with `$params['user']` which did contain the domain as a prefix.

Here https://github.com/icewind1991/SMB/blob/master/src/Server.php#L62 we see that the `Server` class actually splits out the domain (workgroup), so calling `$this->getUser()` will *not* contain the domain. We'd need to call `getWorkgroup()` to get it.

**Comment by jvillafanez** [comment]
> The part that worries me is that both users will get the same oc_storages entry because we don't store the domain part of the user name there.

I guess that if the domain is different, the windows user account is different, so will the storage.

I hope this isn't a common sceneario, but anyway this sounds bad.

**Comment by mmattel** [comment]
1. By design, in domain structures, for authentication, the combination of domain\user is unique.
2. A workgroup is like a domain.
The difference between a domain and a workgroup can be found here: https://superuser.com/questions/655761/what-are-the-difference-between-domain-and-workgroup
3. To access resources in a domain or workgroup, you need to authenticate if you are not a member of.
4. ``smbclient`` is not joining a domain but using network resources from a domain.
5. You can only access a resource by knowing it´s domain, server, share, user and password
6. Just for the record, you can have all identifyers the same but in different domains !

This means, that each mapping combination is unique by design.
This must be reflected in our database - if not, we have troubles.

https://github.com/owncloud/core/pull/30212 is at least fixing the issue with smbclient and anonymous access.

**Test scenario for a proof:** (setting up two domains might be a bigger task :smile:)

1. Create to workgroups (Notebook 1 = WG 1 and Notebook 2 = WG 2)
Windows NB preferred for ease of testing.
2. Create on each NB (WG) users with identical user and pwd
3. Create on each NB a share named identically and granting access with the user above
4. Have different data in each share to clearly differenciate later on (important)
5. Try to mount via smbclient each share and do a directory listing
6. Try to mount via owncloud each share, best in parallel, and do a directory listing
7. Try to upload different files in each mount and monitor to which NB it goes to
8. Play around eg by changing one users pwd on only one NB ect.

You can extend testing having different users.

**Comment by PVince81** [comment]
To fix this we need to:

- fix the Storage backend to also store the domain name as part of the storage id
- provide a migration for existing storage ids and prepend the domain if not exists
- both for SMB and WND

**Comment by jvillafanez** [comment]
SMB is the only affected. WND works fine.

The fix is easy, but the main problem is the migration. I'm checking options.
