### ISSUE TITLE
Tell users that shared folders can be accessed via WebDAV

### ISSUE THREAD

**Issue by Wrzlprmft** [owncloud/core#30446]
### Steps to reproduce
1. Access a public (web)link to a folder shared by somebody (federation sharing).
2. Try to find information that this can also be accessed via WebDAV.

### Expected behaviour
There should be a way to clearly see that shared folders can be accessed via WebDAV and instructions how to do so.

### Actual behaviour
There aren’t. I also cannot find any documentation of this.

### Server configuration
This is not my server, but Sciebo. However, since I cannot find this documented anywhere (and only stumbled upon it by chance), I doubt that this is a server-specific problem
**ownCloud version:** 10.0.4 (stable)

### Client configuration
**Browser:** Firefox 58.0.1 
**Operating system:** Ubuntu

**Comment by PVince81** [comment]
I think there is no documentation because this was never officially an endpoint that users are supposed to be able to mount in their favorite Webdav clients and it isn't guaranteed to work with all clients.

The way it works is as follows: you need to connect to "public.php/webdav" and use the share token as user id, and the share password as password (if any).

If we want to make this official I'd suggest to add a button somewhere on the public link page to retrieve the matching Webdav URL.

@pmaier1 thoughts ?
