### ISSUE TITLE
Add occ command to set user email and display name in accounts table

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30529]
Before OC 10, the user email was stored in oc_preferences so it was possible to set it using the command line `occ user:setting user.mail --value mail@example.org`.

Since OC 10, this user information is stored in the oc_accounts table so it is not possible to use this method any more.

We should add a new command `user:modify` that will make it possible to change the email address and display name of a user.
When run, it will call the relevant methods on `IUserManager` which will internally check whether the matching user backend supports setting email or display name. In case it's not supported, an exception will be thrown. Else the value will be set properly.

@tomneedham @pmaier1 @DeepDiver1975

**Comment by tomneedham** [comment]
> Before OC 10, the user email was stored in oc_preferences so it was possible to set it using the command line occ user:setting user.mail --value mail@example.org.
> 
> Since OC 10, this user information is stored in the oc_accounts table so it is not possible to use this method any more.

This is still true. But since we use the accounts table, we separate the concept of an identity and an account in owncloud - which is important for those instances that utilise other auth and user backends - and in fact combine them in different ways. 

Previously, ownCloud contacted backends on-demand for information. In the case of Database users this was simply the case of querying the oc_preferences table for a user to get their email. However, with the accounts table, we always query that for the metadata - since core controls when metadata is synced to be more reliable and faster.

The problem has arisen because the documentation (and tooling) guides admins to edit the oc_preferences table to change metadata. However, the occ commands should use IUserManager methods which correctly handle permissions and capabilities of user backends and can provide more accurate exceptions and messages when actions are not possible. The UserManager will also take care of re-syncing the data with the accounts table straight after it is modified.

**Comment by PVince81** [comment]
so does it mean the workaround would be to not only run `occ user:setting` but also `occ user:sync` with DB backend afterwards ?

**Comment by tomneedham** [comment]
Correct.

**Comment by tomneedham** [comment]
With 10.0.8 - we will sync metadata on login more reliably. But we should still add `user:modify` to provide a command line interface to IUserManager which brings more possibilities.

**Comment by sharidas** [comment]
Since the changes are merged into master and sable10 branch, I am closing this issue.
