### ISSUE TITLE
Querying an unregistered endpoint on OCS/v2 causes an error 500 and differs from OCS/v1

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#31357]
When comparing `v1` and `v2` routes: 

### `ocs/v1.php`: 

```
curl -u 'admin:admin' -I 'http://<server>/ocs/v1.php/apps/notifications/api/v1/notifications?format=json' -H 'OCS-APIREQUEST:true' 
HTTP/1.1 200 OK
[...]

{
   "ocs":{
      "meta":{
         "status":"failure",
         "statuscode":999,
         "message":"Invalid query, please check the syntax. API specifications are here: http:\/\/www.freedesktop.org\/wiki\/Specifications\/open-collaboration-services. DEBUG OUTPUT:\n"
      },
      "data":[

      ]
   }
}%
```

### `ocs/v2.php`: 

```
curl -u 'admin:admin' -I 'http://<server>/ocs/v2.php/apps/notifications/api/v1/notifications?format=json' -H 'OCS-APIREQUEST:true' 
HTTP/1.1 500 Internal Server Error
[...]

{
   "ocs":{
      "meta":{
         "status":"failure",
         "statuscode":500,
         "message":"Invalid query, please check the syntax. API specifications are here: http:\/\/www.freedesktop.org\/wiki\/Specifications\/open-collaboration-services. DEBUG OUTPUT:\n"
      },
      "data":[

      ]
   }
}%
```

**Comment by phil-davis** [comment]
Nothing much can be done about v1 - it is "stuck" with the fun that it is.

What should v2 do if it gets a request for a URI that does not exist, and will not exist.

404 The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible - is not appropriate because request was to a completely wrong place.

400 Bad Request ?

And what if someone queries /ocs/v42.php/teapot - just some "random" non-existent endpoint. Should the server always respond to every "wrong" endpoint with a 400-series code?

**Comment by SamuAlfageme** [comment]
See for reference the discussion about non-registered routes on https://github.com/owncloud/client/issues/6507 

> Nothing much can be done about v1 

Current behavior with v1 endpoints is actually the "expected", spec'ed logic from https://www.freedesktop.org/wiki/Specifications/open-collaboration-services/ - my issue was mostly with server replying 500 to anything.
