### ISSUE TITLE
[Feature Request] Syncing user backends ownCloud - ownCloud

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#31593]
Taking the following from the documentation:
```
ownCloud ships with an LDAP application which allows LDAP users (including Active Directory) to 
appear in your ownCloud user listings. These users will authenticate to ownCloud with their LDAP 
credentials, so you don’t have to create separate ownCloud user accounts for them. You will manage 
their ownCloud group memberships, quotas, and sharing permissions just like any other ownCloud 
user.
```
Continuing this idea, we also could use another owncloud instance to serve as user source.
Having two instances of ownCloud connected already as federated share.
Both instances (In1 and In2) have their own user database.
The idea is, that you can sync the user database so user@In1 can logon on In2 (if sync is setup in that way).

**Comment by mmattel** [comment]
This could/should be limited to users beeing in a particular group, so you can decide which are "federated" and which are local only.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @jvillafanez, @PVince81, and @tomneedham.

Possibly related issues are https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/20519 (OwnCloud Feature Request), https://github.com/owncloud/core/issues/8494 (owncloud desktop sync doesn't respect alternative user backends), and https://github.com/owncloud/core/issues/14784 (Owncloud Calendar Feature Request).

**Comment by PVince81** [comment]
also cc @DeepDiver1975

**Comment by phil-davis** [comment]
What are the realistic use cases for this?
I can think something like:
- International office has the "master" ownCloud with all the users
- Sydney/Singapore/... offices run smaller "local" ownClouds, and want to "suck" a group from the International cloud to be their local users

If these are on the public internet, then the only reason to have a "local" ownCloud is if the smaller office(s) is in a remote area that has crap internet speed - they can host something locally (but public) so that they can work with their files.

Maybe more often, if these are internal ownClouds on an intranet connected by VPNs - if the VPN speeds are not so good then "local"  ownClouds could be useful.

But actually, these type of organisations are likely to be big enough that their users are stored in LDAP  anyway?

**Comment by mmattel** [comment]
https://github.com/owncloud/documentation/issues/4288 (Document federated system addressbook sync)
https://github.com/owncloud/core/pull/20948 (Syncing system addressbooks across federated ownClouds)

**Comment by tomneedham** [comment]
Use a federated IDP ?
