### ISSUE TITLE
Different button order between the internal share and remote share notifications

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#31764]
### Steps to reproduce
1. Disable auto-accept shares for internal sharing
2. Share a file from user A to user B
3. Share a remote file from one server to the user B in step 2

### Expected behaviour
2 notifications appear to accept or decline the shares with a similar content. The button order is consistent

### Actual behaviour
The button order is switched

![screen shot 2018-06-13 at 17 52 17](https://user-images.githubusercontent.com/1477829/41362912-e638a834-6f32-11e8-9ae6-ce8ff72b0c5b.png)

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** latest master, likely present also in 10.0.9beta1

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by phil-davis** [comment]
@individual-it @paurakhsharma @davitol 
The webUI tests currently check that the expected text is shown on the UI, and they use the Accept and Decline buttons and test their behavior.
But there is a (maybe unwritten)  requirement that the buttons are displayed in some consistent order.
UI tests do not check any of those "screen layout..." "non-functional" (I don't like that term here) requirements.
At the moment it is "life". But somehow it would be nice to have some way to test "the UI layout is reasonable and consistent".

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @felixheidecke.

Possibly related issues are https://github.com/owncloud/core/issues/23438 (remote-share notification: Add size information), https://github.com/owncloud/core/issues/4499 (Shared File Notifications), https://github.com/owncloud/core/issues/12608 (Shared file notifications), https://github.com/owncloud/core/issues/11642 (Expire Internal Shares), and https://github.com/owncloud/core/issues/9098 (Display remote shares in "Shared with you" section).

**Comment by jvillafanez** [comment]
I don't think you should test the layout. That's part of the UX. You start from there and you end up testing that the color of the "accept" button is blue and the button has fixed width and so on.

**Comment by phil-davis** [comment]
For now, we do not test that. But I am just using this as an example of the things that are actually "requirements" without people being willing to admit that. It is only when someone (developer, QA, or customer) says "hey, that is wrong/broken" that everyone then admits that the UX thing is a requirement.
If it is a requirement that the button is a particular shade of blue, then so be it, and test it! Maybe that is not a requirement. But it is a requirement, for example, that the button background color and text color are not the same, and are "different enough to be readable". If someone messes with the CSS in a naughty way (e.g. make black-on-black buttons) then some test should fail. Otherwise crap like that can accidentally get released.
./endOfPhilosophyOfTesting
