### ISSUE TITLE
View who is involved on shared files/folders

### ISSUE THREAD

**Issue by macz71** [owncloud/core#32482]
Hi,

I'd like to share with you my point of view for sharing folders and files.
It's very much missing feature from productivity point of view when we migrated from Dropbox.

In my opinion when I’m file / folder owner and I enabled resharing I want to see all who’ve been reshared to with rights given to each person/file/folder.
All people should see all “members” having access to file without visibility of given permissions. It’s just not to share to the same people twice the same file/folder and make communication much easier. Currently we need to ask our colleagues if they are already sharing certain files/folders from/with somebody.

If we would like to take care on very high level about privacy maybe we should consider to add an option when sharing “publicly visible”. When checked (by default) person who you share file/folder to will be visible as person having access to file/folder to all sharers. If unchecked, nobody from sharers, excepting file/folder owner (not resharer), can see this person as shared with. This option “publicly visible” should be available only for file/folder owner.

Re-sharing to anybody should always be publicly visible.

Thanks for this discussion anyway 🙂

**Comment by PVince81** [comment]
- Owners already see all user shares since OC 9.1.
- Resharers only see their own shares and not the ones from other users, this used to be privacy related I think. Might need to rediscuss how to change this.
- Link shares are currently visible only for the share creators. Here's a ticket to make all visible to the owner (but not resharers): https://github.com/owncloud/core/issues/29519
