### ISSUE TITLE
webUILogin suite does not exist in stable10

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32894]
When the ``user_management``  app was split out into its own repo from core master, the ordinary login and reset password features that stay in core were put into an acceptance test suite called ``webUILogin``

That did not happen in core stable10. Because core stable10 has the user_management app code in it unchanged.

But it is confusing for people. So in stable we should make a wwebUILogin suite anyway.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/32603 ([stable10] does not have zsync), https://github.com/owncloud/core/pull/29866 ([stable10] Cache non-existing accounts), https://github.com/owncloud/core/pull/29719 ([stable10] Integration tests - for file exists step, throw exception if the file does not exist), https://github.com/owncloud/core/issues/3579 (Settings app does not exist because of which sharing fails), and https://github.com/owncloud/core/pull/29379 ([stable10] #27854 non existing folder skeletondirectory).

**Comment by phil-davis** [comment]
PR #32895 implements this.
