### ISSUE TITLE
Date upload (web/client/...)

### ISSUE THREAD

**Issue by antoine15** [owncloud/core#32916]
Hello,

I updated the new server 10.* and now, when user send a file, the modify date is the a really modify date  ... but i prefer had the upload date, same was with server version 9.*

Thks for your help :)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/5326 (web dav chunked upload tasks), https://github.com/owncloud/core/issues/26895 (web navigation), https://github.com/owncloud/core/issues/18166 (Upload deduplication), https://github.com/owncloud/core/issues/8105 (Enhancement: Show "time left" during upload in Web UI.), and https://github.com/owncloud/core/issues/21762 (Modified date - Uploaded date).

**Comment by antoine15** [comment]
Hello,

Thanks for your answere,
But can you more specific ?
I don't understand ... i can't modify param / conf for solved my problem ?

**Comment by IljaN** [comment]
I don't think this was ever possible see: https://github.com/owncloud/core/issues/26798

**Comment by antoine15** [comment]
Please nobody can help me ? ='(

**Comment by IljaN** [comment]
I don't think that there is a setting for this.

**Comment by Perfecticus** [comment]
I thought I'd just leave a comment here as I encountered the problem of not having the uploaded files marked with upload date in the file system, making it harder to know which files to process for generating thumbnails.

I dug into the code and found where I needed to make a change in order to have the upload time as modified date.

apps/files/js/file-upload.js

find this

>                 if (lastModified) {
>                         // preserve timestamp
>                         this.data.headers['X-OC-Mtime'] = '' + lastModified;
>                 }

and comment out the assign of data.headers like so:
// this.data.headers['X-OC-Mtime'] = '' + lastModified;
