### ISSUE TITLE
Use new webDAV path in upload to share acceptance test

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#33345]
in acceptance/features/apiSharing/uploadToShare.feature test also with new WebDAV path

from master issue #32040

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/32510 (fix API acceptance test steps, so that they really use old/new webdav path), https://github.com/owncloud/core/pull/32559 (acceptance tests - stop uploading when receiving an error), https://github.com/owncloud/core/issues/32366 (Expand webDAV API acceptance tests), https://github.com/owncloud/core/issues/32602 (Acceptance tests for webDAV Report search API), and https://github.com/owncloud/core/pull/32740 (Acceptance test steps for public link share).
