### ISSUE TITLE
Refactor acceptance test to use new webDAV path

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#33348]
make tests/acceptance/features/apiShareOperations/getWebDAVSharePermissions.feature also work with new DAV path

from master issue #32040

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/33345 (Use new webDAV path in upload to share acceptance test), and https://github.com/owncloud/core/issues/32510 (fix API acceptance test steps, so that they really use old/new webdav path).
