### ISSUE TITLE
cleanup acceptance tests WebDav trait

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#33690]
- [x] use test helpers where possible e.g. `WebDavHelper::makeDavRequest` and not `WebDav::makeDavRequest`
- [x] move helper functions into helpers
- [ ] split the whole file into multiple contexts
- [ ] sort out ``lastUploadTime`` (see https://github.com/owncloud/core/pull/33795#pullrequestreview-182540270 )
- [x] maybe do similar for delete, which also has a ``sleep(1)`` (make a ``lastDeleteTime`` property, and get rid of the special ```waits nad deletes file`` step?) #34063
- [ ]  remove logic duplication between `WebDav::findEntryFromPropfindResponse` + `SearchContext::userSearchesUsingWebDavAPI` and `WebDav::reportFolder`

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/pull/32559 (acceptance tests - stop uploading when receiving an error), and https://github.com/owncloud/core/issues/32510 (fix API acceptance test steps, so that they really use old/new webdav path).

**Comment by phil-davis** [comment]
Assigned @paurakhsharma to look into the structure and suggest a design for doing this

**Comment by paurakhsharma** [comment]
> * [ ]  use test helpers where possible e.g. `WebDavHelper::makeDavRequest` and not `WebDav::makeDavRequest`
Doesn't this make our php files longer then it is? @phil-davis @individual-it

**Comment by individual-it** [comment]
done a bit of work, there is more to do putting it back into backlog

**Comment by individual-it** [comment]
moving to next sprint for remaining work

**Comment by phil-davis** [comment]
Added to QA/CI project. First someone needs to spend a few minutes working out what is still of value to do here, and then a useful direction to go.

**Comment by dpakach** [comment]
Closing this as it is moved to new issue https://github.com/owncloud/core/issues/36770

cc @phil-davis  @individual-it
