### ISSUE TITLE
[FR] Global user and group medial search boolean option

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#33883]
we have `accounts.enable_medial_search` but we should move to one option respected globally for users, and one for groups, making the results more consistent. 

Eg: custom groups backend
Eg: local groups backend
Eg: local user backend
Eg: ldap user backend

**Comment by tomneedham** [comment]
@pmaier1 @PVince81

**Comment by pmaier1** [comment]
Maybe we should just disable medial search for groups until we have the groups table instead of adding config options?

**Comment by PVince81** [comment]
ref: https://github.com/owncloud/core/issues/27623

**Comment by PVince81** [comment]
disabling permanently could impair the UX for people to whom UX is more important than performance.

let's have this as a config.php only option

**Comment by PVince81** [comment]
@tomneedham if I understand correctly you mean we need two options:

- "accounts.enable_medial_search_users": affects local, ldap and any other user backends
- "accounts.enable_medial_search_groups": affects ldap group backend, custom groups, etc

now the groups option is not related to the "accounts" table.

what to do with the existing option, migrate it to the other two ? not possible in read-only config.php. we could state this change in release notes for admins to adjust.

**Comment by tomneedham** [comment]
Move to new config options with better naming. Don't try 'auto migrate' them. We can document in release notes and normal documentation. Side effects are minimal / not critical at all. Easily changed.

**Comment by karakayasemi** [comment]
@tomneedham @PVince81 Please, correct me if I'm wrong. I'm planning to do the followings.

- Seperate 'accounts.enable_medial_search' as  'accounts.enable_medial_search_users' and  'accounts.enable_medial_search_groups' in sample.config.php.

- Change 'accounts.enable_medial_search' usages to  'accounts.enable_medial_search_users' in all repositories. Also, there is 'user_ldap.enable_medial_search_users' option in config.apps.sample.php I will remove this option and use new 'accounts.enable_medial_search_users' option instead of this.

- Currently, the implemented group search in the core is using medial search unconditionally. I will add 'accounts.enable_medial_search_groups' check to determine search type in group search methods in here: https://github.com/owncloud/core/blob/master/lib/private/Group/Database.php#L289. Also, I will check other group backend implementations to use this new option.

**Comment by tomneedham** [comment]
>     * Seperate 'accounts.enable_medial_search' as  'accounts.enable_medial_search_users' and  'accounts.enable_medial_search_groups' in sample.config.php.

Accounts represent users from a backend. We should keep this named as this. 

>     * Change 'accounts.enable_medial_search' usages to  'accounts.enable_medial_search_users' in all repositories. Also, there is 'user_ldap.enable_medial_search' option in config.apps.sample.php I will remove this option and use new 'accounts.enable_medial_search_users' option instead of this.

The accounts.enable_medial_search is fine - group ones should be called `groups.enable_medial_search` and then when central group table is merged, we can use it there as well. 

I would need to see where this is used. The key thing should be that within ownCloud - all account searches are only hitting the database so we have control over the expectations for the search time. I would not bring LDAP into this if we can. We might be able to leave this separated for now.

**Comment by tomneedham** [comment]
@karakayasemi Do you want to have a quick call Monday morning about this? I can explain some background

**Comment by karakayasemi** [comment]
@tomneedham thank you for help. I read the Glencore patches and other issues which are related to this issue. I believe I got the idea for applying necessary patches with your last explanations.
I am planning to prepare a Pull Request at the weekend. I guess we can discuss further details on the Pull Request.

**Comment by karakayasemi** [comment]
@tommenham thank you for help, I read other related issues and patches. After your last explanations, I believe I got the idea for implementing necessities. We can move `user_ldap` part out of this issue's scope.
I am planning to open a pull request at the weekend. We can discuss further details on the PR. If we need, we can have a chat on rocket.chat or arrange a quick call.
