### ISSUE TITLE
Running phan locally analyzes other apps

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33905]
### Steps to reproduce

1. have a local git clone of core
2. clone some other apps into the ``apps`` folder to do development for them, or run local tests for them...
3. in core, try ``make test-php-phan``

### Expected behaviour
``phan`` only scans and analyzes code that is really in core.

### Actual behaviour
``phan`` scans, analyzes and reports issues in app code, as well as core code.
So, as a developer, you think that there are core problems, when there are not.

**Comment by patrickjahns** [comment]
> I probably already had other "random" extensions installed, so YMMV, but you do need to have a range of extensions installed so that phan can understand that various bits of code are OK.

These are the extensions we develop towards - so expected behavior. We would have the ability to use stubs - but I am highly against this, as the method interface might change in future versions of php and we would not catch that. 
Thus developers are required to install the extensions we develop towards

**Comment by phil-davis** [comment]
These days, apps can be cloned in the `apps-external` folder.
The code analysis tools avoid that folder.
