### ISSUE TITLE
Suggestion: Warn users of admin group if cron is not running

### ISSUE THREAD

**Issue by AlphaDE** [owncloud/core#34114]
I just came across that from was not properly executed though configured.

Other frameworks warn users of the admin group if the from service is nit running.

Owncloud could do that the same way like it warns of modified files when a user with admin privileges logs in.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/21583 (Warnings on admin page), https://github.com/owncloud/core/issues/25925 (Admin page warnings), https://github.com/owncloud/core/issues/7905 (cron: add warning if oc_jobs is getting too large or isn't being run), https://github.com/owncloud/core/issues/3232 (Group Admin Storage Selection), and https://github.com/owncloud/core/issues/21954 (Regular user is asked if she/he wants to edit setup when not being admin instead of a warning.).

**Comment by AlphaDE** [comment]
#7905 describes the same problem, but the required solution like a warning banner comparable with the "modified files" banner does not exist... although a not running cron is more serious.

**Comment by PVince81** [comment]
there is already a check on the settings page, that one could be extended somehow to run regardless of the app that is displayed and display a warning banner.
