### ISSUE TITLE
Repository not updated

### ISSUE THREAD

**Issue by PotcFdk** [owncloud/core#34428]
### Steps to reproduce
1. Try to upgrade to version 10.1.0 from packages

### Expected behaviour
10.1.0 should be in https://download.owncloud.org/download/repositories/

### Actual behaviour
10.1.0 is not in https://download.owncloud.org/download/repositories/, most up-to-date version is 10.0.10

@crrodriguez

**Comment by crrodriguez** [comment]
Packages are scheduled to be available next week. El 9 feb 2019 10:54, PotcFdk <notifications@github.com> escribió:Steps to reproduce
Try to upgrade to version 10.1.0 from packages
Expected behaviour
10.1.0 should be in https://download.owncloud.org/download/repositories/
Actual behaviour
10.1.0 is not in https://download.owncloud.org/download/repositories/, most up-to-date version is 10.0.10
@crrodriguez

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/32786 (Repository not updated), https://github.com/owncloud/core/issues/30797 (Repository not updated), https://github.com/owncloud/core/issues/32092 (Repository not updated), https://github.com/owncloud/core/issues/26636 (Official Repository's not updated (again)), and https://github.com/owncloud/core/issues/10685 (Update from Repository broken).

**Comment by GTT8** [comment]
@crrodriguez is this getting updated?

**Comment by crrodriguez** [comment]
> @crrodriguez is this getting updated?
 It is already in the fresh channel, production and stable will be seen shortly.

**Comment by davitol** [comment]
10.1 packages are here: https://download.owncloud.org/download/repositories/10.1/ so repositories are updated. Let's close the ticket and thanks @PotcFdk for reporting
