### ISSUE TITLE
Acceptance tests using pre-installed apps_paths

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#34657]
PR #30889 issue #29839 introduced `apps-external` as a second apps path on a default installation.

- [ ] review existing `appmanagement.feature` scenarios to see if they are still "a good thing"
- [ ] add scenarios to confirm the new default path works
- [ ] whatever else might be useful related to this for testing ;)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/33690 (cleanup acceptance tests WebDav trait), and https://github.com/owncloud/core/pull/31516 (Acceptance test coding standard changes).

**Comment by mmattel** [comment]
References https://github.com/owncloud/core/pull/34898 (Add the apps-external directory during setup only)

**Comment by skshetry** [comment]
@phil-davis, I added a few tests, but as the issue is more towards testing installation folder and check where the apps is written to, we need some better way to simulate an actual app install. We might need to use `core` api's and simulate/emulate installs through use of our custom api's in `testing` app. 

Needs more research.
