### ISSUE TITLE
Birthday calendar does not sync all items with Thunderbird when multiple dates are assigned to a contact

### ISSUE THREAD

**Issue by SamCoDWS** [owncloud/core#34653]
### Steps to reproduce
1. Use OwnCloud with contacts and calendars installed
2. Have one or more contacts with the birthday and date of death defined
3. Synchronize the generated birthday calendar with Thunderbird Lightning, using CalDAV

### Expected behaviour
Both date should be synced to Thunderbird via CalDAV and displayed in the birthday calendar there.

### Actual behaviour
Only the last recently edited calendar item is synced to Thunderbird and the other ones are not.

### Additional information
I have looked into the issue. It seems, that the ics files referenced by the CalDAV-stream of the calendar are using the same ID:

/owncloud/remote.php/dav/calendars/Robert/contact_birthdays/contacts-b0a2b078-d1be-4279-a857-fa2abf3ae092.vcf-death.ics
/owncloud/remote.php/dav/calendars/Robert/contact_birthdays/contacts-b0a2b078-d1be-4279-a857-fa2abf3ae092.vcf.ics

I have discussed this with the guys at Mozilla and they say that the IDs of the events described in the VCARDs are the same and since those are UIDs, both items have to be handled as one and the same (... and one is seen as an update of the other). 

They refuse to change the behaviour because they feel it is correct. Yet I do not have this issue with other CalDAV-clients. Please see the following bugzilla issue: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1517165

Therefore a possible solution solution might be to export the dates with individual UIDs. Please feel free to see the attached exports for further reference. Thank you!

[dav.txt](https://github.com/owncloud/calendar/files/2722158/dav.txt)
[contacts-b0a2b078-d1be-4279-a857-fa2abf3ae092.vcf-death.ics.txt](https://github.com/owncloud/calendar/files/2722165/contacts-b0a2b078-d1be-4279-a857-fa2abf3ae092.vcf-death.ics.txt)
[contacts-b0a2b078-d1be-4279-a857-fa2abf3ae092.vcf.ics.txt](https://github.com/owncloud/calendar/files/2722166/contacts-b0a2b078-d1be-4279-a857-fa2abf3ae092.vcf.ics.txt)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @DeepDiver1975.

Possibly related issues are https://github.com/owncloud/core/issues/23004 (Calendar doesn't support dates before Unix epoch => can't import contact birthdays), https://github.com/owncloud/core/issues/22971 (Contact birthdays of untouched contacts not displayed in calendar), https://github.com/owncloud/core/issues/30122 (Contact birthday reminders cannot be dismissed in Thunderbird because the calendar is read only), https://github.com/owncloud/core/issues/26197 (Multiple entries in the "Contact Birthdays" calendar ), and https://github.com/owncloud/core/issues/9248 (oc7 contacts: birthday date picker only future dates).

**Comment by DeepDiver1975** [comment]
A fix is in #34654

**Comment by DeepDiver1975** [comment]
> A fix is in #34654

@SamCoDWS can you test this patch? THX

**Comment by SamCoDWS** [comment]
Hi @DeepDiver1975, 

thanks for suggesting a solution to the problem! I am going to test the patch some time this week and get back to you. 

Kind regards
Robert

**Comment by SamCoDWS** [comment]
@DeepDiver1975 It works! It was necessary to recreate the contacts, though. Thank you very much :).
