### ISSUE TITLE
API or OCC command to administrate trusted federation server

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34742]
currently Trusted ownCloud Servers can only be administrated through the webUI
an occ command and/or a api would be handy (specially for acceptance tests). 
To test the functionality we currently enable "Add server automatically once a federated share was created successfully" and then create a federated share to make sure the server is in the trusted list. But then it stays there and is not cleaned up.

**Comment by davitol** [comment]
@individual-it Not sure if this what you are looking for. If not, then just ignore it 😃 

How to set Trusted ownCloud Servers in order to test Federation App

In both servers, we modify in config.php the following line

e.g 'overwrite.cli.url' => 'ownserverurl';

After editing this line, we browse into the webUI and we activate the Federation app

In admin menu, Sharing, in Federation section, we write down the url of the other server

Back to the CLI, we run the following commands in /opt/owncloud

```sudo -u www-data php cron.php (on server1, server2, server1, server2)```

```sudo -u www-data ./occ dav:sync-system-addressbook (on server1 a server2)```

```sudo -u www-data ./occ federation:sync-addressbooks (on server1, server2)```

After that the address books should be synced and auto complete should work
