### ISSUE TITLE
Issue updating owncloud

### ISSUE THREAD

**Issue by lothar-lothar** [owncloud/core#35293]
The update to 10.0.10 failed.

Firstly, the mainenance mode was not finished after 1 hour.
After changing maintenance => true to false in the config.php, the page changed from maintenance to the message "App update necessary" (see below).

__________________________________________________________
App-Update notwendig
Stellen Sie vor dem Fortsetzen bitte sicher, dass die Datenbank, der Konfigurationsordner und der Datenordner gesichert wurden.
Zur Vermeidung von Zeitüberschreitungen bei größeren Installationen können Sie stattdessen den folgenden Befehl in Ihrem Installationsverzeichnis ausführen:
./occ upgrade
__________________________________________________________

After starting the update, the following message appeared.

_________________________________________________________
Aktualisierung auf 10.0.10
OC\RepairException: Upgrade is not possible

Reperaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reperaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable customgroups occ app:disable guests
Reperaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps
Detaillierte Fehlermeldungen 
Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die ownCloud Community.
_________________________________________________________

Are there any suggestions what to do?

P. S.: I'm working on a hosted server and all the command-line commands are not working.

### Server configuration
**Operating system**: LINUX

**Web server:**  Apache2

**Database:**  SQL

**PHP version:**  7.2

**ownCloud version:** (see ownCloud admin page)  -- not shown, no access

**Updated from an older ownCloud or fresh install:** Update from 10.0.4

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```

**Comment by linkp** [comment]
The information you shared indicates that your Guests app is the source of your troubles. You need to disable it like the error indicates in order to complete your upgrade.

Are you running the CLI commands as the user who owns the files in your owncloud directories? (e.g sudo -u www-data ./occ app:disable guests) (Please note that while user www-data is a likely candidate to be the owner on Debian and Ubuntu Linux, it may not be the case. You will want to check file ownership using ls.)

Is your CLI PHP the same version as your HTTP PHP?

If you cannot disable the guests app from the CLI or the web interface, you can always move the guests folder from the apps folder for safekeeping while you complete your upgrade.

Note that you may not be able to use the guests app until you upgrade your ownCloud to a higher version than 10.0.10. The most recent version currently in the Marketplace (0.8.1) requires ownCloud 10.1 and the master branch in their Gituhub requires ownCloud 10.2

**Comment by lothar-lothar** [comment]
Thank you very much.
Had done this in the meantime and it worked. There are some other errors now but that is another story, resulting from the web-provider.
So I'll close this issue.
