### ISSUE TITLE
10.2.1. RC1 - smoke test results

### ISSUE THREAD

**Issue by davitol** [owncloud/core#35653]
# Smoke test

## Previous requirements

Prepare two servers with ssl activated and trusted certificates.

Enable LDAP and external storage apps.

Have a LDAP server ready to be used with owncloud.

Have ready two external storages of your choice SMB, SFTP, Dropbox, Google Drive, FTP, S3, ownCloud, local.

Scenarios to consider:
- [x] OAuth2 and sync + mobile clients ( can be deployed remotely ) @davitol 
- [x] LDAP @davitol 
- [x] Shibboleth
- [x] Windows Network Drive (also use it as sync target ) @davitol 
- [x] Guests @davitol
- [x] Impersonate @davitol 
- [x] Login with App Token Login @davitol
- [x] TOTP @davitol 

## Testing setup

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Enable encryption app and encryption default module | Encryption is enabled correctly |  :heavy_check_mark:  |
2 | Populate owncloud server with users and groups | Users and groups are correctly created | :heavy_check_mark:    |
3 | Share a folder remotely using federated sharing with admin user of the other server. | folder can be opened in recipient server without problems | :heavy_check_mark:    | issue (no regression) #35042
4 | Set up LDAP, as admin check users. log in with a LDAP user, if possible one with an avatar. | Users are loaded. LDAP user logs in without problems. Avatar is shown if it exists.  | :heavy_check_mark:   |
5 | Set up two external storages different, disable encryption in one of them.| No errors in this process | :heavy_check_mark:   |

## Testing functionality

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Share a file using federated sharing from an external unencrypted external storage in server #1 using a LDAP user to the admin user in server #2. | Admin user in server #2 can see the file. | :heavy_check_mark: |
2 | Open internet explorer or edge and upload a new avatar for a regular user not LDAP | Interface can be used, avatar is uploaded, check that personal page has a scroll bar and scrolls fine. | :heavy_check_mark: |
3 | Upload several files and folders inside external storages, open some. | No problems uploading, files can be downloaded and opened. | ❌  | To be investigated. WebDAV storage seems to not work https://github.com/owncloud/core/issues/35660
4 | Delete files inside both external storages. Recover some after from the trashbin. |  Files are correctly deleted and restored. |:heavy_check_mark:   |
5 | Using webdav upload a 100MiB file.| No errors in this process |:heavy_check_mark: |

**Comment by davitol** [comment]
- [ ] ownCloud User Manual pdf shows Master version instead of 10.2.1 in the RC1 tarball
![Screen Shot 2019-06-25 at 12 29 05](https://user-images.githubusercontent.com/10596560/60093121-ed870880-9748-11e9-873f-f221f83ed513.png) (cc @settermjd )

**Comment by davitol** [comment]
## Issues found while testing 10.2.1 RC1

- [ ] Saving admin Password in Browser. Cannot use feature create users via email when we have active the PP rule "At least 8 characters are required." https://github.com/owncloud/password_policy/issues/228

**Comment by jesmrec** [comment]
### Mobile smoke tests over 10.2.1

On first instance, sharing was tested a bit deeper, since the stuff included is affecting directly such feature:

**iOS Device: iPhone 6Plus v12 
Android device: Nexus 5X v8**

| Test Case| Android | iOS | Related Comment | 
| :-------- | :----: | :-: |:--------------- | 
|**Private Share**||||||
| Share file with a user | :white_check_mark: | :white_check_mark: |  |  |
| Share folder with a user | :white_check_mark: | :white_check_mark: |  |  |
| Share with a group | :white_check_mark: | :white_check_mark: |  |  |
| Share file with only edit | :white_check_mark: | :white_check_mark: |  |  |
| Share file with only share | :white_check_mark: | :white_check_mark: |  |  |
| Share file with no permissions | :white_check_mark: | :white_check_mark: |  |  |
| Edit share permissions file | :white_check_mark: | :white_check_mark: |  |  |
| Remove share| :white_check_mark: | :white_check_mark: |  |  |
| Resharing |  :white_check_mark: | :white_check_mark: |  |  |
| Resharing no permissions | :white_check_mark: | :white_check_mark: | Check error message in new arch Android |  |
|**Public Share**||||||
| Name | :white_check_mark: | :white_check_mark: |  |  |
| Down / view perm | :white_check_mark: | :white_check_mark: |  |  |
| Down / view / edit perm |  :white_check_mark:| :white_check_mark: |  |  |
| upload only perm | :white_check_mark: | :white_check_mark: |  |  |
| Password | :white_check_mark:  |:white_check_mark:  |  |  |
| Expiration date | :white_check_mark:  | :white_check_mark: |  |  |
| Password enforced | :white_check_mark:  | :white_check_mark: |  |  |
| Expiration date default | :white_check_mark:  | :white_check_mark: |  |  |
| Expiration date enforced | :white_check_mark:  | :white_check_mark: |  |  |
| Passw & Expiration date enforced | :white_check_mark:  | :white_check_mark: |  |  |
| Remove public link | :white_check_mark: | :white_check_mark: |  |  |
| PaswdPolicy Passw | :white_check_mark: | :white_check_mark: |  |  |
| PaswdPolicy No Passw | :white_check_mark: | :white_check_mark: |  |  |
|**Issues**||||||
| https://github.com/owncloud/core/issues/35541 | :white_check_mark: | :white_check_mark: |  |  |
| https://github.com/owncloud/core/issues/35550 | :white_check_mark: | :white_check_mark: |  |  |
| https://github.com/owncloud/enterprise/issues/3364 | :white_check_mark: | :white_check_mark: | Check error message in new arch Android |  |

Also, smoke test over basic funcionality:

Device & iOS version: iPhone 6 Plus v12
iOS app version: 1.0.1
Device & Android version: Android 5X v8
Android app version: 2.11.1

### Login

Test Case | Expected Result | Result | Related Comment
| :------- | :---------------: | :------ | :-----------------: | 
Login with one account (HTTP)  | It is possible to access  | :white_check_mark: iOS<br>:white_check_mark: Android<br> |
Login with one account (special characters) | It is possible to access  | :white_check_mark: iOS<br>:white_check_mark: Android<br> |

### Folders

TestID | Test Case | Steps | Expected Result | Result | Related Comment
------------ | ------------- | ----------- | -------------- | ----- | ------
1 | Create a new folder  | 1. Tap on create a new folder |The folder is created| :white_check_mark: iOS<br>:white_check_mark: Android<br> |
2 | Create a folder with special character | 1. Tap on create a new folder <br> 2. Use a name with special characters (e.g $%&¨)| The folder is created with special character  | :white_check_mark: iOS<br>:white_check_mark: Android<br> |
3 | Rename a folder | 1. Create a new folder<br> 2. Rename the folder|  Folder is renamed| :white_check_mark: iOS<br>:white_check_mark: Android<br>
4 | Move a folder | 1. Create a new folder <br> 2. Move the folder| Folder is moved to the specifield location | :white_check_mark: iOS<br>:white_check_mark: Android<br>
5 | Upload a file into a folder | 1. Create a new folder <br> 2. Upload a file| File is uploaded into the folder | :white_check_mark: iOS<br>:white_check_mark: Android<br>
6 | Delete a folder  | 1. Access to a folder, the folder has deep structure inside <br> 2. Download some files <br>3. Select delete that folder  | 2. The files are downloaded<br>3. The folder is removed| :white_check_mark: iOS<br>:white_check_mark: Android<br>
7| Copy Folder | 1. Long press to copy a folder <br> 2. Select a location to paste | The folder and all its content is copied in the location, and remains too in the original| :white_check_mark: iOS<br>:white_check_mark: Android<br> 
8| Av Offline file | 1. Long press to set as av offline a file | The file is downloaded and set as av off with the yellow arrow |:white_check_mark: Android<br>
9| Not Av Offline file | 1. Long press to set as no av offline a file | The file has no more the yellow arrow |:white_check_mark: Android<br

### File

TestID | Test Case | Steps | Expected Result | Result | Related Comment
------------ | ------------- | ------------- | -------------- | ----- | ------
1 | Upload a new file  | 1. Upload a new file | The file is uploaded | :white_check_mark: iOS<br>:white_check_mark: Android<br>
2 | Upload a file with special character | 1. Upload a new file (e.g f%&¨)| The file is uploaded | :white_check_mark: iOS<br>:white_check_mark: Android<br>
3 | Rename a file | 1. Create a new file <br> 2. Rename the file | The file is renamed |:white_check_mark: iOS<br>:white_check_mark: Android<br>
4 | Move a file | 1. Create a new file <br> 2. Move the file | The file is renamed |:white_check_mark: iOS<br>:white_check_mark: Android<br>
5 | Copy a file  | 1. Create a new file <br> 2. Copy the file | The file is copied to the selected location | :white_check_mark: iOS<br>:white_check_mark: Android<br>
6 | Delete a file  | 1. Create a new file <br> 2. Delete the file | The file is deleted |:white_check_mark: iOS<br>:white_check_mark: Android<br>
7| Download a file| 1. Tap to download a file | The file is downloaded and marked with green tick|:white_check_mark: iOS<br>:white_check_mark: Android<br>
8| Av Offline file | 1. Long press to set as av offline a file | The file is downloaded and set as av off with the yellow arrow |:white_check_mark: Android<br>
9| Not Av Offline file | 1. Long press to set as no av offline a file | The file has no more the yellow arrow |:white_check_mark: Android<br>

please let me know if you miss something.

**Comment by jnweiger** [comment]
desktop client smoke testing is missing here.

**Comment by patrickjahns** [comment]
# CI Test Results for 10.2.1RC1

## Upgrade Testing
✅ https://drone.owncloud.com/owncloud/update-testing/475

## Smashbox Testing
✅https://drone.owncloud.com/owncloud/smashbox-testing/676

**Comment by HanaGemela** [comment]
## Testing
Desktop client: 2.5.4 (build 11456)
Server: 10.2.1RC3 (testing)

### Update the version 

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Login with one account (HTTPS)  | It is possible to access |  :construction: |
2 | Login with one account (HTTP)  | It is possible to access  |:white_check_mark:|

### New installation

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Login with one account (HTTPS)  | It is posible to access | :construction: |
2 | Login with one account (HTTP)  | It is posible to access | :construction: |

### Folder

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Create a new folder  | The folder is created| :white_check_mark: |
2 | Create a folder with special character | The folder is created with special character (e.g $%&¨) | :white_check_mark: |
3 | Rename a folder | 1. Create a new folder 2. Rename the folder| :white_check_mark: |
4 | Move a folder | 1. Create a new folder 2. Move the folder| :white_check_mark: |
5 | Delete a folder  | 1. Access to a folder, the folder has a 5 level folders inside 2. Upload some files 3. Download some files 4. Select delete that folder (The folder is removed) | :white_check_mark: |
6 | Share the folder by link | 1. Create a new folder 2. Right click in the folder 3. Click on Share 4. Check the option "Share" -> Public link 5. Create new link 6. Introduce a password 7. (The folder link is generated) | :white_check_mark: |
7 | Unshare the folder by link | 1. Create a new folder 2. Right click in the folder 3. Click on Share with oC 4. Uncheck the option "Share link" | Retired |
8 | Share the folder with users or groups| 1. Create a new folder 2. Right click in the folder 3. Click on Share 4. Introduce one user/group on the option Share with users or groups (The folder is Share with user/group) | :white_check_mark: |
9 | Unshare the folder with users or groups| 1. Delete the entry in Users and Groups share (The folder is not Share with user/group) | :white_check_mark: |
10 | share the folder with users or groups (Federated sharing)| 1. Create a new folder 2. Right click on the folder 3. Click on Share with oC 4. Introduce one user/group on the option Share with users or groups (The folder is Share with user/group) | :white_check_mark: |
11 | Unshare the folder with users or groups (Federated sharing)| 1. Click on Delete (The folder is not Share with user/group) | :white_check_mark: |

### File

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Create a new file  | The file is created |:construction: |
2 | Create a file with special character | The file is created with special character (e.g f%&¨)|:construction:|
3 | Rename a file | 1. Create a new file 2. Rename the file | :construction: |
4 | Move a file | 1. Create a new file 2. Move the file | :construction: |
5 | Delete a file  | 1. Create a new file 2. Delete the file | :construction: |
6 | Share the file by link | 1. Create a file 2. Right click on the file 3. Click on Share with oC 4. Check the option "Share link" 5. Check the option "Password protect" 6. Introduce a password 7. Press Enter (The file link is generated) | :construction:|
7 | Unshare the file by link | 1. Create a file 2. Right click in the file 3. Click on Share with oC 4. Uncheck the option "Share link" | :construction: |
8 | Share the file with users or groups| 1. Create a file 2. Right click on the file 3. Click on Share with oC 4. Introduce one user/group on the option Share with users or groups (The file is Share with user/group) | :construction: |
9 | Unshare the file with users or groups| 1. Create a file 2. Right click on the file 3. Click on Share with oC 4. Introduce one user/group on the option Share with users or groups 5. Click on Delete (The file is not Share with user/group) | :construction: |
10 | Share the file with users or groups (Federated sharing)| 1. Create a new folder 2. Right click on the folder 3. Click on Share with oC 4. Introduce one user/group on the option Share with users or groups (The folder is Share with user/group) | :construction: |
11 | Unshare the file with users or groups (Federated sharing)| 1. Create a new folder 2. Right click on the folder 3. Click on Share with oC 4. Introduce one user/group on the option Share with users or groups 5. Click on Delete (The folder is not Share with user/group) | :construction: |

### Overlay_icons

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | If the system is offlline, there are no overlay icons present | 1. Lauch the Desktop 2. The overlay icons are not shown 3. Quit the Desktop (The overlay icons are not shown)|:construction: |  |
2 | When you pause the sync, the overlay icons are still shown | 1. Lauch the Desktop 2. The overlay icons are shown 3. Click on Pause (The overlay icons are still shown)|:construction: |  |
3 | Green check (All files within the folder (all the way down the tree) are sync with the server, and there are no problems to report) | 1. The account is sync | The green check is shown in all the folders/files|:construction: |  |
4 | Blue spinning icon (Some or all files/folders in the directory are waiting to sync or are actively sync) | 1. The account is sync | The files/folder that are waiting to sync have the blue icon|:construction: |  |
5 | Yellow warning triangle (There is an error in sync somewhere in the directory such as a path longer than 255 characters or a bad character in a name o a file firewall problem) | 1. The account is sync |The files that are not sync because they have a problem... Have a yellow warning triangle |:construction: |  |
6 | Red error Icon (There is a fatal problem in the sync process that can't be resolved) | 1. The account is sync | The files/folders that are not sync because have a problem... Have a red error icon|:construction: |  |

**Comment by davitol** [comment]
✅  webUI Updater from 10.2.0 to 10.2.1 via beta channel
