### ISSUE TITLE
Cannot open a hidden text file restored from the Trashbin

### ISSUE THREAD

**Issue by davitol** [owncloud/core#36233]
### Steps to reproduce
1. In settings, set Show hidden files
2. create a .txt with TextEditor
3. Rename the file and hide it (dot at the beginning of the filename)
4. Check TextEditor can open the file
5. Delete the file
6. Restore the file from the trashbin

### Expected behaviour

TextEditor should be able to open the file

### Actual behaviour

Only download option is possible. TextEditor is not able to open the file. Thumbnail/Preview of the file is not available.

Note: Same behavior happens with richDocuments.

**Database:**
MySQL

**ownCloud version:** (see ownCloud admin page)

oC 10 10.3.0RC1

**Before deleting the file**
<img width="651" alt="Screen Shot 2019-10-02 at 09 33 11" src="https://user-images.githubusercontent.com/10596560/66026940-309c0900-e4fa-11e9-8b26-26ecb836b6bf.png">

**After restoring the file from the Trashbin**
<img width="1270" alt="Screen Shot 2019-10-02 at 09 33 53" src="https://user-images.githubusercontent.com/10596560/66026896-15c99480-e4fa-11e9-858e-9f2e428672aa.png">

**Comment by micbar** [comment]
@davitol Is this a regression in 10.3.0?

**Comment by davitol** [comment]
> @davitol Is this a regression in 10.3.0?

No regression. At least with latest version already released 10.2.1 it is also reproducible

**Comment by phil-davis** [comment]
For me the problem is worse.
1) Make sure "Show hidden files" is selected in settings.
1) In the UI, press `+` and select "Text File" and create a hidden file, e.g. `.hidden.txt`
2) The editor comes up - good. Type some text and close the editor.
3) The file is listed - good.
4) Click the file name - it downloads instead of opening in the editor - bad.
5) Rename the file to something "not hidden" e.g. `nothidden.txt`
6) Click on the file name - it still downloads instead of opening in the editor - bad.

If I do the reverse - create a "normal"  text file first, then rename it to a hidden file, I can edit the hidden file. If I then delete and restore the hidden file, then I cannot edit it any more.

Note: files like this, that cannot be opened in the editor, also do not have a proper thumbnail preview. So that might be a hint - something in the backend code is also not generating the thumbnail preview for files that start out as hidden files (or are restored from trashbin as hidden files)

**Comment by phil-davis** [comment]
I can "get back editing" of a hidden file by:
1) rename to a not-hidden name
2) delete the file
3) restore from trashbin
4) rename the file back to its hidden name

**Comment by phil-davis** [comment]
I removed server QA team assignment - there are some acceptance test scenarios added in PR https://github.com/owncloud/files_texteditor/pull/318 and my descriptions of other scenarios above. That should be enough for a developer to reproduce while fixing.
