### ISSUE TITLE
[QA] mysql is forgiving per default; postgres is strict

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#36305]
E.g. in oc_filecache we have several columns with a NOT_NULL constraint.

```
MariaDB [owncloud]> show columns from oc_filecache;
+------------------+---------------+------+-----+---------+----------------+
| Field            | Type          | Null | Key | Default | Extra          |
+------------------+---------------+------+-----+---------+----------------+
| fileid           | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| storage          | int(11)       | NO   | MUL | 0       |                |
| path             | varchar(4000) | YES  |     | NULL    |                |
| path_hash        | varchar(32)   | NO   |     |         |                |
| parent           | bigint(20)    | NO   | MUL | 0       |                |
| name             | varchar(250)  | YES  |     | NULL    |                |
| mimetype         | int(11)       | NO   |     | 0       |                |
| mimepart         | int(11)       | NO   |     | 0       |                |
| size             | bigint(20)    | NO   |     | 0       |                |
| mtime            | bigint(20)    | NO   |     | 0       |                |
| storage_mtime    | bigint(20)    | NO   |     | 0       |                |
| encrypted        | int(11)       | NO   |     | 0       |                |
| unencrypted_size | bigint(20)    | NO   |     | 0       |                |
| etag             | varchar(40)   | YES  |     | NULL    |                |
| permissions      | int(11)       | YES  |     | 0       |                |
| checksum         | varchar(255)  | YES  |     | NULL    |                |
+------------------+---------------+------+-----+---------+----------------+
16 rows in set (0.00 sec)
```

mysql per default accepts e.g. 

```
MariaDB [owncloud]> update oc_filecache set parent = NULL where fileid = 8963;
Query OK, 1 row affected (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 0

MariaDB [owncloud]> show warnings;
+---------+------+--------------------------------+
| Level   | Code | Message                        |
+---------+------+--------------------------------+
| Warning | 1048 | Column 'parent' cannot be null |
+---------+------+--------------------------------+
1 row in set (0.00 sec)
```

With only a warning. It effectively writes `0` into the parent column. This is bad for two reasons:

* We normally use parent = `-1` to indicated that there is no parent. Not `0`. 

* Postgresql throws an error when we try to assign NULL to a NOT-NULL column.

Expected behavour:

* mysql should also throw an error in this case.
  Run mysql with `SET sql_mode = 'STRICT_TRANS_TABLES'` to convert all warnings to errors. 

* We eventually get our apps fixed to not try assigning NULL to NOT-NULL columns.

**Comment by jvillafanez** [comment]
What's the action to take here? Note that, as far as I know, ownCloud wasn't designed for this case.

> We normally use parent = -1 to indicated that there is no parent. Not 0.

I think parent = -1 also means that the folder is the root of the storage (because it doesn't have a parent). This is (probably not) reserved to the `''` folder which is the one acting as root of the storage, and where the rest of the files and folders (in that storage) hang.
Using a parent = -1 under different conditions will likely break things.

> We eventually get our apps fixed to not try assigning NULL to NOT-NULL columns.

I think this is handled by core, trying to get the fileid of the parent folder. The problem is that we can't access to the parent folder, so we can't even fill the DB entry to get the fileid. Under these conditions, it doesn't seem possible to get a valid fileid for the parent folder.
We'll have to investigate the consequences of using a fake fileid (-1, -2, 0, etc), but this is a new special case where ownCloud wasn't designed to work in. Without any information, I think this is a high risk and it will require a lot of time to investigate and a lot of time to test.

So, assuming that faking the fileid will do more harm than good, will have to decide how we'll deal with this exception.
Easiest solution would be to swallow the exception somewhere. We'll have to check exactly where we should swallow it.
