### ISSUE TITLE
Moving Files with delete restriction

### ISSUE THREAD

**Issue by Romoroni** [owncloud/core#36350]
### Steps to reproduce
1. Share a folder with delete restriction
2. Try to move a file with the share client, in Windows 

### Expected behaviour
It should move the file

### Actual behaviour
Error, server says forbidden to Move, and try again

Server configuration
Operating system:
Ubuntu 18.04
Web server:
Apache 2
Database:
MySQL
PHP version:
7.3
ownCloud version: (see ownCloud admin page)
10.3.0 (git) / 10.3.0
Updated from an older ownCloud or fresh install:
fresh
Where did you install ownCloud from:
git / download page

**Comment by karakayasemi** [comment]
I could not produce the scenario in web UI. Please, try the scenario with web UI, if it also works for you, this means the issue related to Desktop client. 
Recently, several issues fixed in both server and desktop client about share permissions like https://github.com/owncloud/client/issues/7422 .Please also test the scenario with the latest desktop client release I guess,(2.6.0 rc4 is out). If the issue still exists, you can open an issue in the client repo. Thanks for reporting.
