### ISSUE TITLE
Check that files can be used properly after trashbin restore

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36363]
Issue https://github.com/owncloud/core/issues/36233 notes a problem with a hidden file after restore from trashbin.

Review the trashbin restore API test scenarios:

- [x] enhance them to check more things about the file that has been restored #38357 
- [x] make sure to cover hidden files and other unusual files/folders (e.g. with spaces in the name, Unicode...) https://github.com/owncloud/core/pull/37065
- [x] try restoring a file that was deleted, but a new file of the same name has since been uploaded https://github.com/owncloud/core/pull/37065

and anything else "special" that might be done by users ;)

**Comment by Talank** [comment]
@phil-davis  I think the the test for `try restoring a file that was deleted, but a new file of the same name has since been uploaded` is already covered in this scenario !!
https://github.com/owncloud/core/blob/5ee9d5ae4bbb1819a92f0708ae1ed428b0168906/tests/acceptance/features/apiTrashbin/trashbinRestore.feature#L119

However, I am adding the test for hidden file for the same scenario.

**Comment by phil-davis** [comment]
PR #38357 finishes this issue
