### ISSUE TITLE
What to do about settings/help

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36381]
### Steps to reproduce
1. have community edition installed
2. browse to `http://172.17.0.1:8080/index.php/settings/admin` or `http://172.17.0.1:8080/index.php/settings/personal` - that works
3. browse to `http://172.17.0.1:8080/index.php/settings/help`

### Expected behaviour
Some help links in https://github.com/owncloud/core/blob/master/settings/templates/help.php will be displayed.

### Actual behaviour
I am redirected to the files page.

**Comment by phil-davis** [comment]
Access to `settings/help` seems to have been removed in PR #34612

But the `help.php`  content was updated in PR #34586 so that it points to various online resources (rather than to previously-bundled docs)

This seems to have happened around about core version 10.2

What is the requirement?

- `settings/help` should be available with links to online resources, or;
- `settings/help`  should be gone (i.e. the "currently dead" `settings/templates/help.php` could be deleted in GitHub)

**Comment by cortho** [comment]
Related but not the same: https://github.com/owncloud/core/issues/36238

**Comment by phil-davis** [comment]
@davitol do you know about the requirements and history of the help links?

**Comment by davitol** [comment]
@phil-davis All I can tell you:

In 10.1.0 There were a section with help in the settings dropdown that was no longer present in the EE tarball version. That section  looked like this:

https://github.com/owncloud/core/issues/34510#issuecomment-465181270

So the decision was to remove it and make it consistent with the Enterprise Edition. That was done with the PR https://github.com/owncloud/core/pull/34612

That bundled docs need to be removed from the community edition. Because in the enterprise edition were no longer there. So it was a case of consistency.

idk if this info is worthy or it was already known by you but thats all I can tell tell you.



http://localhost/testing5/index.php/settings/help
