### ISSUE TITLE
Review acceptance test code of PR 36673

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36684]
PR #36673 fixed some issues for app acceptance tests that were calling core steps but failing the core validation of tables in the steps.
````````````````````````````````````````````````````````
See comments:
https://github.com/owncloud/core/pull/36673/files#r362306744 - what are the "standard" column names to use in the table for the function `assertNotificationsOnWebUI` ?

https://github.com/owncloud/core/pull/36673/files#r362306808 - how can the core validation come to know about the extra permissions that an app defines?

**Comment by dpakach** [comment]
@phil-davis 
I reviewed those cases  and seems like in the notifications issue (https://github.com/owncloud/core/pull/36673/files#r362306744) the `content` header is not used anywhere so we can just get rid of it.
As for the other one I can not think of any way to pass the validating arguments from the app. Since the apps use core code it has to be done in the core unless we make a interface in between those two.

**Comment by phil-davis** [comment]
That's fine. If/when we get other apps that add their own permissions, then we can think again abut how to make it flexible.
