### ISSUE TITLE
daily-master-qa tarball is out of date

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#37223]
### Steps to reproduce
1. download https://download.owncloud.org/community/daily/owncloud-daily-master-qa.tar.bz2
2. open the tarball
3. look in owncloud/version.php

### Expected behaviour
The date is recent (should be from last night)

### Actual behaviour
```
$OC_Build = '2020-03-31T20:00:42+00:00 6b6e6b7dc5bd7fc3455ff768997c91623575e4cb';
```

The tarball has not been rebuilt (or at least it did not make it to the download servers) in April.

**Comment by phil-davis** [comment]
@micbar @HanaGemela or whoever looks after the nightly tarball build.

**Comment by jnweiger** [comment]
Fixed in https://github.com/owncloud/administration-internal/commit/76ae11a7ca6ac586029894b10eb8892766c30eb5

The trick goes like this: Since 1st of April, release.php uses a calens docker image to update the CHANGELOG.md when making a tar. That is a good thing per se, but has a side-effect.
The dailies are built by the same release.php but the makedailyrelease.sh wrapper runs everything inside a docker-release:7.1 image, where calls to docker (dind) are not supported.

The fix simply skips calling the calens docker image, when release.php is run inside docker. That should be fine now.
