### ISSUE TITLE
GDrive fix duplicated file names to take the latest based on the timestamp

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#37352]
### Steps to reproduce
1. using gdrive
2. overwriting a file creates at the google drive backend a new file with the same name
3. owcloud can´t handle identical filenames and rejects the file(s) completely.

### Expected behaviour
The duplicate file with the same name but latest timestamp should be used for owncloud.

Referencing the PR updating the gdrive library #37265

The question I am asking, is there a possibility for duplicate files at gdrive, that only the latest can be taken. This would change the behaviour from "gone from owncloud" to "latest taken and visible".

@phil-davis @jvillafanez your input is welcomed :smile:

### Actual behaviour
Duplicate files cant be seen anymore.

**Comment by jvillafanez** [comment]
There is no real guarantee that the file is the same, from a broader point of view, just because the name of the file is the same. It could be a completely different file. If the file I synced a while ago is about science and somehow the file that syncs later is about politics, the first thing I'd think is that something went wrong.

The use case about reuploading a file should be fixed (not nicely) in the referenced PR

**Comment by mmattel** [comment]
The example described is also true for owncloud. I can reuse the same name with different content and it is up to the originator doing this - therefore outside of any storage system or middleware in the world.

The question I asked is differnt.
Could it be achieved, in the special case of GD, to only use the latest version of multiple occurences of the same filename?
