### ISSUE TITLE
Core 10.5.0-beta 2 occ upgrade errors

### ISSUE THREAD

**Issue by SeeJayEmm** [owncloud/core#37514]
### Steps to reproduce
1. ./occ upgrade

### Expected behaviour
Upgrade completes without error.

### Actual behaviour
Error:`` Class 'Doctrine\DBAL\Types\Types' not found in /web/owncloud/apps/files_sharing/appinfo/Migrations/Version20200504211654.php:21

I fixed the above by fixing 
use Doctrine\DBAL\Types\Types;
...to read...
use Doctrine\DBAL\Types\Type;

Ran again and got the following error:
Error: Class 'OCA\Files_Sharing\Migrations\Types' not found in /web/owncloud/apps/files_sharing/appinfo/Migrations/Version20200504211654.php:21

I fixed this by changing 
                                        Types::BIGINT,
...to...
                                        Type::BIGINT,
  
### Server configuration
**Operating system**: 
Ubuntu 20.04

**Web server:**
2.4.41-4ubuntu3

**Database:**
8.0.20-0ubuntu0.20.04.1

**PHP version:**
7.4.3-4ubuntu2.2

**ownCloud version:** (see ownCloud admin page)
10.5.0-Beta2

**Updated from an older ownCloud or fresh install:**
Update

**Where did you install ownCloud from:**
GitHub release

**Signing status (ownCloud 9.0 and above):**

**Comment by phil-davis** [comment]
`doctrine/DBAL` `2.10` introduced `Types.php` instead of `Type.php` https://github.com/doctrine/dbal/commit/4d40444b5c9d2dedb9b029fe62d25d9b375b368d 

And ownCloud10 moved to `doctrine/DBAL` `2.10` in PR https://github.com/owncloud/core/pull/37100 when PHP  7.1 support was dropped.

I am guessing that somehow `lib/composer/doctrine/dbal` did not have the up-to-date version `2.10` in it.

**Comment by SeeJayEmm** [comment]
@phil-davis 10.4.1. This could be my fault as I extracted the zip over top of my old installation. I see now that was not the correct process.

I can roll back to my pre-upgrade backup and try again.

**Comment by SeeJayEmm** [comment]
Should I need to build the beta2 as if I was pulling from the git repo?

**Comment by SeeJayEmm** [comment]
Once I was able to get the build environment setup and run "make" I was able to run "php occ upgrade" successfully without the errors listed above.

I apologize for taking up your time.

**Comment by phil-davis** [comment]
If you remove the 10.4.1 code, and then unpack the 10.5.0Beta2 tarball then there should be no need to use `make` to install/update dependencies etc. The correct dependencies should come already in the tarball. 

I guess you got into a situation where `make` (`composer install`) helped by fetching/correcting the dependency code.

No problem about the time - it is good to understand problems in the beta stage rather than with the official release!

**Comment by SeeJayEmm** [comment]
No. I downloaded the beta2 zip clean and occ required me to make it.

**Comment by VicDeo** [comment]
"extracted the zip over top of my old installation" is not  a right way to go. 
Only 3rd party apps should be kept and everything else should be replaced. I guess there were some leftovers causing this behavior.
I'm closing this issue but you are welcome to reopen it if you have an update.
