### ISSUE TITLE
Default Expiration Date for federation share is shown with incorrect date

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/core#37595]
### Steps to reproduce
1. Set default expiration date for remote shares using webui 
![Screenshot from 2020-06-25 14-28-24](https://user-images.githubusercontent.com/34328907/85687090-4557a700-b6f0-11ea-8eff-2c7cca04cdf1.png)
2. Now create a federated share
3. Check the share expiration date of the share in sharing dialog
![Screenshot from 2020-06-25 14-30-09](https://user-images.githubusercontent.com/34328907/85687229-691aed00-b6f0-11ea-9241-9e07293ae707.png)

Here, the displayed date is wrong

### Expected behaviour
1. Let's set default expiration date for remote share and user share
![Screenshot from 2020-06-25 14-33-27](https://user-images.githubusercontent.com/34328907/85687843-f3635100-b6f0-11ea-89d1-575e7bf27e60.png)

2. Now create a federated share, and share with a local user
3. Check the date of both federated share and local user share
![Screenshot from 2020-06-25 14-35-41](https://user-images.githubusercontent.com/34328907/85688111-2efe1b00-b6f1-11ea-974d-d33dbff2d126.png)

### Actual behaviour
Expiration Date is displayed wrong. As you can see in above screenshot, the expiration date for federated share is incorrect

**Comment by jvillafanez** [comment]
Works for me with firefox. Could you recheck? Maybe the bug is browser-dependant

**Comment by HariBhandari07** [comment]
@jvillafanez  for local user and group sharing, when `Set default expiration date for user shares` is enabled, the default value for expiration date is 7 days. But for remote share, there's no default value. 
![Screenshot from 2020-06-25 15-47-30](https://user-images.githubusercontent.com/34328907/85699640-6b367900-b6fb-11ea-8038-0b3015b86c91.png)

As you can see, the placeholder for remote share is 7, but there's no value.

**Comment by jvillafanez** [comment]
The only way I can think of to have something similar to that behaviour is by removing the value from the textbox.
If the value is removed, an empty string is being set instead of removing the configuration. Since there is still a value set, we don't use the "default" default value.
Basically, by removing the value from the textbox, you're setting a value of 0 days (we might need to double check because we aren't being strict with the data types), instead of what you could expect (7 days, which is the default if no value is provided).

Taking into account that there is a "7" as placeholder, it could be easy to get confused and consider it as a real value instead of just a placeholder.
As far as I know, the behaviour should be similar with the rest of the user and group expiration because the code is mostly copied from there.
