### ISSUE TITLE
Lock owner has extra brackets at end

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#37878]
### Steps to reproduce
1. As Alice, set your full name to "This is my full name"
2. As Alice, do not set an email address
3. Lock a file using the webUI manual locking
4. View the lock details

### Expected behaviour
Lock information has:
`This is my full name has locked this resource via /IM-6553-D13_1pdf`

(i.e. without the empty `()`)

### Actual behaviour
Lock information has:
`This is my full name () has locked this resource via /IM-6553-D13_1pdf`

### Server configuration
Current core master.

**Comment by phil-davis** [comment]
Also note: If Alice changes her full name to something else, then the lock information still has the old "full name". The lock data stored in the database seems to record the full name and email address at the time that the lock is taken out.

Maybe the userid should be stored, and the current full name, email address etc can be looked up when the lock information request-response is being constructed.

**Comment by DeepDiver1975** [comment]
The lock information field is per specs a plain text field holding any informational data for whomever receives a lock.
This data can used to get in touch with the lock owner to resolve the lock situation in a inter-human-communication.

Any dav client who locks a resource can put any information about the user in this field.
Lock owner information can contain e.g. email, phone number or what soever.

Because the lock anyhow has a limited life time changes of the user personal data is not necessarily to be propagated in here. An edge case from my pov.

:+1: for getting rid of the ()
:-1: for putting any magic in dynamically creating the lock owner information
