### ISSUE TITLE
Favorites in 'shared by you' causes CSRF error

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#37925]
When visiting the "shared by me" view, there is a column for favorites.
When clicking on one of the stars in that column, a CSRF error occurs.

![image](https://user-images.githubusercontent.com/1108546/93824213-58cccc80-fc63-11ea-8805-9e43353712b3.png)

Expected behaviour: favorites can be set or removed by clicking a star (or the column is simply not there).

damkencloud is at 10.5.0

**Comment by phil-davis** [comment]
Note: In English the view is called "Shared with others"

The problem does not happen for me on a local test system, which I guess is expected since the whole webUI client and the server are on localhost.

The "Shared with you" view does not have a column for "favorite". But the "Shared with others" view does have the "favorite" column. I wonder why there is this UI difference?

**Comment by jnweiger** [comment]
Confirmed fixed in 10.11.0
