### ISSUE TITLE
"server reported no size" error for Google Drive docs in desktop client sync

### ISSUE THREAD

**Issue by curiousercreative** [owncloud/core#37977]
### Steps to reproduce
1. Connect to Google Drive storage
2. Add Google Doc or spreadsheet into Google Drive connected storage
3. In desktop client, login to account with connected Google Drive

### Expected behaviour
Google Doc should sync without error

### Actual behaviour
Client reports sync error for every Google Doc file "server reported no size"

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4

**Database:** MySQL 5.7

**PHP version:** 7.2

**ownCloud version:** 10.5

**Updated from an older ownCloud or fresh install:** updated from 10.3.2 > 10.4.1 > 10.5 using updater found in admin web app.

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):** `No errors have been found.`

**Are you using external storage, if yes which one:** Google Drive

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Safari 14.0

**Operating system:** macOS 10.14.6

**Comment by curiousercreative** [comment]
These are new errors since updating from 10.3.2, so likely a regression.

**Comment by curiousercreative** [comment]
If we set the size to `0` instead of this constant (that evaluates to `-2`), then we sync just fine: https://github.com/owncloud/core/blob/master/apps/files_external/lib/Lib/Storage/Google.php#L375

**Comment by curiousercreative** [comment]
Also of interest, this appears to be where the error is thrown in desktop client application: https://github.com/owncloud/client/blame/master/src/libsync/discovery.cpp#L400

**Comment by curiousercreative** [comment]
Still haven't pinpointed the exact cause of this regression. Best I can tell, server response and client handling of response haven't changed recently. Good news though, a possible fix exists since we've recently updated updated from [v2](https://developers.google.com/drive/api/v2/reference/files#fileSize) to [v3](https://developers.google.com/drive/api/v3/reference/files#size) of Drive API. Google didn't call this out explicitly in changelogs (other than to say that `File.fileSize` is now `File.size`) but the API reference documentation for that attribute has been updated and now longer includes the disclaimer about size not being available for Google Docs.

Edit: using their API Explorer, I can see that `size` attribute is not present in response for Google Docs :(

**Comment by jvillafanez** [comment]
Main problem here is that Google reports 0 bytes as the size of ANY google doc file. Furthermore, in order to download the file, you have to export it to a different format (I think we're exporting to ".odt" and similar formats), so we won't know the size before exporting it.

By using 0 as file size, the webdav interface will send a 0 byte file to the clients. Basically, instead of downloading an exported google doc file, you'll download an empty file (after spending time converting, transferring, and processing the file in ownCloud).
As said in your PR, that was fixed with https://github.com/owncloud/core/pull/37265/commits/9728492618550b62863fe5d57d837296a1bbea2f , but caused the current problem.

Note that the webdav interface will consider any negative size value as 0 when the file is downloaded.

I don't know if the desktop and mobile clients can handle this problem on their own, but if not I think we should consider to completely ignore google docs files.

Pinging @michaelstingl to check if clients can do something about this.
From the server side, I think the only option is to patch the SabreDav library to allow negative size values and stream the file instead of consider it as 0 size file. (also pinging @DeepDiver1975 to check if patching the SabreDav library makes sense for this)

**Comment by curiousercreative** [comment]
@jvillafanez I responded to the PR just now and would like to focus on this idea:
>I don't know if the desktop and mobile clients can handle this problem on their own, but if not I think we should consider to completely ignore google docs files.
I agree, I thought this must be a client issue and perhaps that's where a fix will go. I similarly thought that perhaps we should ignore Google Docs, but I came up with this use case to consider:

1. Given a Google Drive folder (with Google Docs) synced to a desktop folder
  then Google Docs are not present in desktop folder since they are ignored
1. Given desktop user moves all files from one directory to another directory
  and deletes original directory
  then ignored Google Docs go where? trash most likely
1. Given desktop user moves/renames a directory that includes ignored Google Docs
  then Google Docs should remain in moved/renamed directory

I personally do not edit these Google Docs outside of the Google Drive/Docs web interface. I do however appreciate having the exports for archival purposes. Perhaps this should be a client preference (assuming we solve for use case #2 above).

Perhaps of interest, the Google desktop syncing client (haven't used most recently since switching to OC) handles this by using placeholder files. It has the name of the Google Doc and file attributes (other than size and related attributes I imagine), it can be renamed/moved and the file contents are simply the URL to the Google Doc. The Google syncing application handles these file extensions and appropriately opens in web interface. To me, an ideal solution would be an OC client preference between placeholder files like this and the various export options.
