### ISSUE TITLE
[QA] admin GUI cannot change log level

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38220]
Tested with docker run --rm -ti -v data:/mnt/data -p8080:8080 owncloud/server:10.6.0-rc3

* In the admin gui, the log level is set to 'Warnings, errors and fatal issues' per default
* admin user can change it there to e.G. 'Everything (fatal issues, errors, warnings, info, debug)'
* no confirmation message appears. BAD
* there is no save button on the admin page. OKayish?
* when navigating away, and returning to the admin page, the setting is back at 'Warnings, errors and fatal issues' BAD

Expected behaviour: the settings are saved automagically. User gets a confirmation message about the save.
  E.g. when changing the Update channel. the user gets a confirmation message in green:
![image](https://user-images.githubusercontent.com/1108546/102348780-a7f47600-3fa2-11eb-9ca9-d0e3cad938a7.png)

**Comment by DeepDiver1975** [comment]
>     * admin user can change it there to e.G. 'Everything (fatal issues, errors, warnings, info, debug)'

plz double check the browser console and the network tab and give devs more information - this helps in triaging - THX

**Comment by JanAckermann** [comment]
>no confirmation message appears. BAD

Addressed: https://github.com/owncloud/core/pull/38340

> there is no save button on the admin page. OKayish?

This is how mostly UI settings in OC works, designed this way

> when navigating away, and returning to the admin page, the setting is back at 'Warnings, errors and fatal issues' BAD
Yes weird, this should change a system value but is not working

**Comment by JanAckermann** [comment]
@jnweiger @DeepDiver1975 
This is more related to our docker setup instead of owncloud.

Why this happens:
* We have a overwrite.config.php in the docker setup which takes values from the env
* In ower docker setup we set the env OWNCLOUD_LOG_LEVEL to 2 (https://github.com/owncloud-docker/base)
* Changing the log level via WebUI or even occ command will change the config.php but doesn't have any effect on the env var

In order to fix this, we need a decision here @jnweiger i would suggest not setting a default var for OWNCLOUD_LOG_LEVEL
