### ISSUE TITLE
Upgrading forces Apps-External folder

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#38297]
### Steps to reproduce
1. Install ownCloud 10.5.0 via tarballs
2. upgrade to 10.6.0 via tarballs
3. run the upgrade command from cmd `occ upgrade -vvv`

### Expected
upgrade should be successful 

### Actual
upgrade stops with the message that you have to create the apps-external dir or change the config.php

**Comment by JanAckermann** [comment]
Why this happens:
* Download and install an ownCloud will copy the config.sample.php to config.php where the apps-external folder is listed, the apps-external folder will be installed via the installation routine
* Upgrading to a new owncloud will fail because there is no apps-external folder in the new tar-ball (sure, only gets created while the installation routine)

Ways to solve this:
* Add a empty folder apps-external with a .gitkeep file in it to the core (my preferred way)
* Update the docs, with a note: "If apps-external is in settings, you need to create the folder" (hard to understand by users)
* Remove the apps-external entry from config.sample.php

**Comment by JanAckermann** [comment]
Documentation will be enhanced by https://github.com/owncloud/docs/pull/3040

**Comment by mmattel** [comment]
@JanAckermann 
The apps-external folder contains all apps that are not delivered in the tar file when installing or upgrading. All apps downloaded from marketplace or elsewhere are therefore further located in apps-external. It is necessary to have that from the beginning to have a clear destinction betwee the both. When upgrading, for security reasons, you usually do "soft" upgrade which means, you rename the original owncloud folder and replace it with the new files while keeping /data and /apps-external as links. Having that, makes your upgrade easiest as possible because you do not move data around and ypou do not mixup things. The documentation already has an installation / upgrading script which completely takes care of that. It is by nature, that when you do all steps manually, you need ot remember about the prerequisites - the PR you made in docs supports that. Else no change is necessary. You can ping me on talk and I can give you more background details if you want.

**Comment by voroyam** [comment]
I just lost my entire data folder including all the files of my users because of this.

**Comment by micbar** [comment]
How? IMO that is an unrelated error.

**Comment by voroyam** [comment]
The error I got during the upgrade was pretty clear about it:

```
App directory "/var/www/owncloud/apps-external" not found! Please put the ownCloud apps folder in the ownCloud folder or the folder above. You can also configure the location in the config.php file.
```
