### ISSUE TITLE
create a middleware for tests to be able to reuse some of the test-steps in other parts of the eco-system

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#38421]
We have API & UI tests written in PHP & JS (web & sdk) in future we want to test additionally the desktop client (tests written in python see https://github.com/owncloud/client/pull/8287), the iOS app and the Android app. 
Certain steps are same or very similar on all platforms. This are mainly `Given` steps to setup the backend system (create/delete user/group, upload files via webdav, ...) and some `Then` steps (is the file created on the backend? does the folder exist for user X)

We should have some proxy/middleware to reuse ether the JS code from web or the PHP code from core.
This could be ether a gRPC architecture or a REST API.

**Comment by phil-davis** [comment]
Note: with the PHP dev server it is easy to start-up and get it to run a specific PHP file to process requests. For example:
`php -S localhost:8042 tests/acceptance/middleware.php`

That sort of thing can easily be run in a clone of core, and then requests sent to `localhost:8042` get processed by `tests/acceptance/middleware.php` rather than the oC10 `index.php` getting in the way. And then `tests/acceptance/middleware.php` has easy access to all the acceptance test code in core. Maybe that is a simple way to provide an API to access existing core acceptance test steps?

**Comment by dpakach** [comment]
Created in https://github.com/owncloud/owncloud-test-middleware
@individual-it  can we close this?

**Comment by individual-it** [comment]
yes, this issue is done, I've created follow up issues in https://github.com/owncloud/owncloud-test-middleware
