### ISSUE TITLE
I cant disable encryption

### ISSUE THREAD

**Issue by joancefet** [owncloud/core#38590]
![image](https://user-images.githubusercontent.com/669549/112722242-11135000-8ee7-11eb-804f-d52ef09de4b1.png)

### Steps to reproduce
sudo -u www-data php occ maintenance:singleuser --on
sudo -u www-data php occ encryption:decrypt-all
sudo -u www-data php occ encryption:disable

### Expected behaviour
Disable Encryption

### Actual behaviour
The system still have encrypted files. Please decrypt them all before disabling encryption.

### Server configuration
**Operating system**:
Ubuntu 20.04.2 LTS

**Web server:**
Apache 2.4.41

**Database:**
10.3.25-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04

**PHP version:**
7.4.3

**ownCloud version:** (see ownCloud admin page)
version | 10.6.0.5
versionstring | 10.6.0
edition | Community

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- nordestao
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\MissingSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [nordestao] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\MissingSignatureException
                    [message] => Signature data not found.
                )

        )

)

**Comment by joancefet** [comment]
any help?

**Comment by dotlineX** [comment]
Gonna sound stupid but did you try rebooting the server?

**Comment by joancefet** [comment]
> Gonna sound stupid but did you try rebooting the server?

Hi, Thanks for your answer!

Do you speak the operating system or just the apache/owncload server?

I have restarted apache/owncload several times, but the OS has not yet, I will try this.

**Comment by joancefet** [comment]
The OS has been restarted, but the problem persists.

**Comment by dotlineX** [comment]
Didn't expect much, but hey you tried. Did you check if everything was indeed decrypted? Maybe the server has some part where it gets stuck and spits out this error. Don't know really I'm not a programmer.

**Comment by karakayasemi** [comment]
@joancefet could you share owncloud.log file after running decrypt-all command?

**Comment by joancefet** [comment]
> @joancefet could you share owncloud.log file after running decrypt-all command?

Yes sure. Thank you for your help.

[owncloudprincipals.log](https://github.com/owncloud/core/files/6329474/owncloudprincipals.log)

**Comment by karakayasemi** [comment]
Sorry, could not see any error log about encryption.

**Comment by JanAckermann** [comment]
Closing for now, If this is still an issue, please reopen

**Comment by jank04** [comment]
Version: 10.9.1.2 - Problem still exists. Encryption can not be turned off.

all files could be decrypted successfully!

and then:

The system still has encrypted files. Please decrypt them all before disabling encryption.

[Screenshot 1](https://jan-home.de/public/bilder/oc_encryption_bug1.png)
[Screenshot 2](https://jan-home.de/public/bilder/oc_encryption_bug2.png)

**Comment by Simi5599** [comment]
> Version: 10.9.1.2 - Problem still exists. Encryption can not be turned off.
> 
> all files could be decrypted successfully!
> 
> and then:
> 
> The system still has encrypted files. Please decrypt them all before disabling encryption.
> 
> [Screenshot 1](https://jan-home.de/public/bilder/oc_encryption_bug1.png) [Screenshot 2](https://jan-home.de/public/bilder/oc_encryption_bug2.png)

Version: 10.9.1.2 - I had the same problem with my ownCloud instance.

I found a tricky solution that could be useful for you.

Prerequisite: 

1. Access to occ via terminal 
2. Recovery key or every user password for each account (if user-key is used)
3. (OPTIONAL BUT RECOMMENDED) Make a backup of your owncloud DB and data directory

If you meet the prerequisites, follow the following steps:

1. Put the server in single user mode in order to prevent user to access their files using `sudo -u www-data php occ maintenance:singleuser --on`
2. Launch `sudo -u www-data php occ encryption:decrypt-all username` for EVERY user in your ownCloud instance (where username is the username of the user to decrypt)
4. Make sure that all user had their files decrypted (maybe via manual inspection or something else)
5. Now the tricky part, since `sudo -u www-data php occ encryption:disable` does not work, launch `sudo -u www-data php occ encryption-decrypt all`
6. Reach the point where the server asks for the first user password and then do **CTRL+C** to terminate the command
7. The encryption will be disabled

Bonus part:
Since encryption is now disabled you need to clean the file-system and the DB from the old encryption data.

Connect to your DB and launch the following query into your owncloud DB: `DELETE FROM oc_appconfig WHERE appid LIKE 'encryption'`

Now reach your ownCloud data dir and delete the **files_encryption** folder and repeat this process for every user sub-folder.

Success! You have disabled encryption successfully!

Tested on my owncloud instance without problems.

**Comment by Simi5599** [comment]
You don't have to so `sudo -u www-data php occ encryption:disable` because it is already disabled.
To check this you can do `sudo -u www-data php occ encryption:status`.
Keep in mind that this is a work-around.

**Comment by jank04** [comment]
Okey, but sadly this workaround is not working for me.

```
root@www /var/www/owncloud # sudo -u www-data php occ encryption:decrypt all
Disable server side encryption... done.


You are about to start to decrypt all files stored in all's account.
It will depend on the encryption module and your setup if this is possible.
Depending on the number and size of your files this can take some time
Please make sure that no user accesses their files during this process!

Do you really want to continue? (y/n) ^C
root@www /var/www/owncloud #  sudo -u www-data php occ encryption:status
  - enabled: true
  - defaultModule: OC_DEFAULT_MODULE
root@www /var/www/owncloud #
```

**Comment by Simi5599** [comment]
Try by typing 'y' and doing crtl+c after while decrypting (you shouldn't lose any files because they are already decrypted but make a backup copy first).
Sadly i used user-key encryption so this work-aroung worked for me

**Comment by MrRojano97** [comment]
> I finally got it! I am on version 10.10.0.3 now.
> 
> At first, make sure that there are indeed no more encrypted files! Even though all files in the browser, the OC client and on the server itself were accessable (unencrypted) there were some more hidden. Some were in the trashbin and even in the file versions! But these files were not identified by the encryption:decrypt-all output.
> 
> I was able to determine the files by querying the databse with `SELECT * FROM `oc_filecache`WHERE`encrypted` = '1';` There I found out, that there were some files left in trashbin and file-versions. I cleared the trashbin via webpage and the file versions with `sudo -u www-data ./occ versions:cleanup`.
> 
> I also deleted the `files_encryption` folders from every user folder in /data.
> 
> After that and `sudo -u www-data php ./occ encryption:disable` I got
> 
> ```
> root@www /var/www/owncloud #  sudo -u www-data php ./occ encryption:status
>   - enabled: false
>   - defaultModule: OC_DEFAULT_MODULE
> ```
> 
> I checked it also on the admin webpage, and indeed encryption is now disabled. Hope it helps.
> 
> I took a snapshot before I did this, might be useful, if you delete some files unintended. A backup is also never a bad idea.

Solved the issue! I used these commands after doing ./occ encryption:decrypt-all:
./occ versions:cleanup
./occ trashbin:cleanup

then:

./occ encryption:disable

And finally encryption has been disabled
