### ISSUE TITLE
New doctrine/dbal 2.11.0 to 2.13.1 fails CI

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38681]
We currently run `doctrine/dbal` 2.10.3. 2.11.0 was released some time ago, but they tagged it as required PHP 7.3 so we have not updated yet.

2.13.0 was released with support for PHP 7.2 put back. Shortly after that, 2.13.1 was released with the same support for PHP 7.2 upwards. Because of the PHP 7.2 support, dependabot made PR #38647 to bump `doctrine/dbal` to 2.13.1

But it fails CI (and also does not work!). The first problem is that the oC10 install command fails. See https://github.com/owncloud/core/pull/38604#issuecomment-810669301

I tried some demonstration of the problem in PR #38674 - see the comment https://github.com/owncloud/core/pull/38674#issuecomment-831102175 - the replacement of `*PREFIX*` with `oc_` at the start of table names is not working any more. I have done enough to demonstrate the problem.

It needs someone to investigate and discover if there is a fix in oC10 code, or if something needs to be fixed upstream in `doctrine/dbal`

It would be nice to sort this out, then we will get the benefit of any bug-fixes that come in `doctrine/dbal` 2.11 2.12 and 2.13.

**Comment by JammingBen** [comment]
Result of a quick debugging session:

Prior to version 2.11, the `execute()` methods eventually calls `executeUpdate()`: https://github.com/doctrine/dbal/blob/2.10.3/lib/Doctrine/DBAL/Query/QueryBuilder.php#L210. OC overwrites this method and replaces the table prefix (see https://github.com/owncloud/core/blob/master/lib/private/DB/Connection.php#L204). Since version 2.11, `executeStatement()` is called instead, as `executeUpdate()` is deprecated (see https://github.com/doctrine/dbal/blob/2.13.x/lib/Doctrine/DBAL/Query/QueryBuilder.php#L208).

We could add a `executeStatement()` method on our own which then calls our `executeUpdate()` to keep at least some backwards compatibility. The interface still needs to be changed though, so we have a breaking change. I will follow up on this. Maybe there is a more subtle solution 🤔
