### ISSUE TITLE
create acceptance tests for `occ` migrations commands

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/core#39197]
From https://github.com/owncloud/core/issues/33051

- I'm actually not sure whether we can add acceptance tests for this command
- If not the issue can be closed
- if yes, please share some ideas

Ref:
[migration commands docs](https://doc.owncloud.com/server/10.8/admin_manual/configuration/server/occ_command.html#migration-steps-command)

**Comment by phil-davis** [comment]
`migrations:generate` is a developer tool to help create new "migration" code templates.
`migrations:execute` and `migrations:migrate` are special commands. Normally a production system will never use there. `occ upgrade` will run all relevant migrations anyway. I guess these special commands allow developers to run a new migration individually, or re-run a migration in a "controlled" way on a production system.
I don't think it will be so easy to make sensible tests for those.

`migrations:status` is a helpful utility to see which migrations have been run. I just noticed a problem with it - issue https://github.com/owncloud/core/issues/40084 and fixed by PR https://github.com/owncloud/core/pull/40085

It would be good to have a test for `migrations:status` - just do ``migrations:status core` and check that all the output data items exist and have "reasonable" values.

**Comment by phil-davis** [comment]
I put this into the current sprint, because it would be nice to have test coverage related to PR #40085 
But no problem if it moves into the next QA sprint.
