### ISSUE TITLE
Cannot view who shares the file/folder before accepting the share in mobile view. Test fails.

### ISSUE THREAD

**Issue by sakshamgurung** [owncloud/core#39222]
### Steps to reproduce
1. Go to `shared with you` view
2. Resize the browser to mobile size (eg: 375 width by 812 height)
3. Cannot view who shares the file and folder.
4. Cannot view share details before accepting the share.
### Expected behaviour
Should be able to see who shares the file/folder either from listed shares or by selecting the share details before accepting the share itself in mobile view of webUI.

### Actual behaviour
1. Sharer display name is not shown
2. Cannot see share details before accepting the share itself
![Screenshot from 2021-09-13 17-40-53](https://user-images.githubusercontent.com/41365307/133079276-83169f4b-a3b1-465a-bee3-63dcd5f09fdb.png)

### Server configuration
**Operating system**:
Ubuntu 20.04.3 LTS
**Web server:**
Apache
**Database:**
mysql  Ver 8.0.26-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
**PHP version:**
PHP 7.4.3
**ownCloud version:** (see ownCloud admin page)
Latest master branch from github repo
**Updated from an older ownCloud or fresh install:**
Fresh install
**Where did you install ownCloud from:**
Github

**Comment by JanAckermann** [comment]
@pmaier1 With PR #39224 we added more space and could also show the sharer now, but this might also cause problems if the share owner name or resource name is too long.
Should we actually show the share owner name ?

**Comment by pmaier1** [comment]
Show it with trimming? Please decide what you think fits best.

**Comment by phil-davis** [comment]
Note: this issue was noticed because of PR #39161 issue #38759 - we are starting to run the webUI smoke tests with a smaller browser window because PR #38748 adjusted some things related to a smaller screen. We want to know that we don't get regressions of that sort of stuff.

So there are a couple of things that have been "noticed" by the tests - this is one of them.

**Comment by JanAckermann** [comment]
Note: 
PR #39224  will give us more space in the recent view and solves the problem with the not fully visible State Column.

With PR  #38748 the sharee info text has been removed intentionally from mobile view and I am not quite sure if we should re-introduce it
as we giving up a lot of space again, which might also result in other problems (glitch with too name username or also folder name).

What do you think @phil-davis is this an info I can't live without on a mobile view?

**Comment by phil-davis** [comment]
> What do you think @phil-davis is this an info I can't live without on a mobile view?

With a not-narrow browser:
![Accept-Decline-shown](https://user-images.githubusercontent.com/1535615/133219959-0a07c669-065e-4a34-9881-9b216b9966c3.png)

With a narrow browser the various texts (sharer name, Accept, Decline) are not shown:

![Accept-Decline-not-shown](https://user-images.githubusercontent.com/1535615/133220364-646109c6-aa16-48ec-ab0a-0183dc1e3a55.png)

But there is a notification that shows the sharer username:
![Accept-Decline-Notification](https://user-images.githubusercontent.com/1535615/133220457-92340bf6-8c2f-4fff-965e-9a9ed7419992.png)

IMO that is OK. A user in a browser on mobile still has the chance to look at the notification and see the sharer.

@sakshamgurung the various icons are all still displayed. Which test failed? (Maybe we can adjust the test so that it has a different expectation when the browser is mobile-size?)

@pmaier1 opinion please?

**Comment by sakshamgurung** [comment]
> But there is a notification that shows the sharer username:
> ![Accept-Decline-Notification](https://user-images.githubusercontent.com/1535615/133220457-92340bf6-8c2f-4fff-965e-9a9ed7419992.png)
> 
> IMO that is OK. A user in a browser on mobile still has the chance to look at the notification and see the sharer.

@phil-davis I have successfully perform accepting/declining share from notification. But it will only work for scenario where we either accepts or declines the share once. It will not work for scenario where we accept then decline the same share or vice-versa because notification will lost after the first accept or decline action. Should I skip mobile test for such scenario and close this issue? or Keep it under expected failure and let this issue open?

**Comment by phil-davis** [comment]
@sakshamgurung the "tick" and "cross" buttons are still visible in the ordinary file list. So the tests should be able to find those and click them. (Just because the text element is not there, the tests should still be "smart" enough to find the icon and click it)

I don't think that we need to bother with special tests that click the notification and use those accept/decline options. (I think we might have some already, but maybe they are not tagged smokeTest) - but if you already have a working scenario then good - it only needs to try the first accept or decline action.

**Comment by sakshamgurung** [comment]
Sharer name is extracted from inner HTML although it is hidden in mobile resolution and "tick"/"cross" icon are used. Closing the issue.
