### ISSUE TITLE
Unable to batch delete files and folders in mobile view. Test fails.

### ISSUE THREAD

**Issue by sakshamgurung** [owncloud/core#39221]
### Steps to reproduce
1. Go to `files` view
2. Resize the browser to mobile size (eg: 375 width by 812 height)
3. Batch select multiple files and folder
4. Only batch download is available no delete option

### Expected behaviour
After selecting multiple files and folder, delete option should be displayed in mobile view of webUI

### Actual behaviour
Only batch download option is shown in mobile view of webUI
![Screenshot from 2021-09-13 17-21-22](https://user-images.githubusercontent.com/41365307/133076822-54d6f622-e237-4395-85c2-ad1519109bf5.png)

### Server configuration
**Operating system**:
Ubuntu 20.04.3 LTS
**Web server:**
Apache
**Database:**
mysql  Ver 8.0.26-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
**PHP version:**
PHP 7.4.3
**ownCloud version:** (see ownCloud admin page)
Latest master branch from github repo
**Updated from an older ownCloud or fresh install:**
Fresh install
**Where did you install ownCloud from:**
Github

**Comment by phil-davis** [comment]
Note: this issue was noticed because of PR #39161 issue #38759 - we are starting to run the webUI smoke tests with a smaller browser window because PR #38748 adjusted some things related to a smaller screen. We want to know that we don't get regressions of that sort of stuff.

So there are a couple of things that have been "noticed" by the tests - this is one of them.

**Comment by JanAckermann** [comment]
This delete button is actually in th headerDate, I am falling from grace :face_with_thermometer:
