### ISSUE TITLE
Refactor API tests that drill down into XML or JSON structures

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39796]
There are test scenarios like:
```
  Scenario: getting default capabilities with admin user with new values
    When the administrator retrieves the capabilities using the capabilities API
    Then the capabilities should contain
      | capability    | path_to_element                                          | value             |
      | files_sharing | user@@@expire_date@@@enabled                             | EMPTY             |
      | files_sharing | group@@@expire_date@@@enabled                            | EMPTY             |
      | files_sharing | providers_capabilities@@@ocinternal@@@user@@@element[0]  | shareExpiration   |
      | files_sharing | providers_capabilities@@@ocinternal@@@group@@@element[0] | shareExpiration   |
      | files_sharing | providers_capabilities@@@ocinternal@@@link@@@element[0]  | shareExpiration   |
      | files_sharing | providers_capabilities@@@ocinternal@@@link@@@element[1]  | passwordProtected |
```
https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiCapabilities/capabilities.feature

The `path_to_element` has dependency on referencing explicit numeric array indices `[0]` `[1]` etc. And the "@@@" separator is not very nice to read.

1) refactor the code so that it can look for and find the data anywhere in the numeric-indexed arrays

2) implement a nicer way of referring to the nested array structure than having those "@@@" in the scenario steps.

Related issue in oCIS: https://github.com/owncloud/ocis/issues/3179

The solution should be similar in both repos, so that scenarios will read consistently.

**Comment by SagarGi** [comment]
TODO:

- [ ] apiCapabilities https://github.com/owncloud/core/pull/40619

similar to the above PR. Search `@@@` in tests of core repo and refactor it as above PR.

**Comment by saw-jan** [comment]
>similar to the above PR. Search `@@@` in tests of core repo and refactor it as above PR.

I see that only this [adminSharingSettings.feature](https://github.com/owncloud/core/blob/master/tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature) feature has `@@@` and that is used to check only single configuration value that is set using webUI.

IMO, we don't have to implement json assertion steps there because they are webUI tests and we are only confirming the webUI action using some api requests (that can be requests to production endpoints or testing endpoints). I see no value in implementing response json-assertion in those scenarios. So I can only suggest two things:
1. Leave them as it is
2. Rename then steps so that they don't use `@@@`

CC @SagarGi @SwikritiT @grgprarup @PrajwolAmatya @nirajacharya2 @phil-davis @individual-it

**Comment by SwikritiT** [comment]
I really don't mind `@@@`, I think we can leave them as they are for this case

**Comment by individual-it** [comment]
I still would change it and delete all the code that does the `@@@` magic. It's extra hidden knowledge that needs to be explained to every new person.

**Comment by grgprarup** [comment]
All the refactoring has been done. As we discussed, refactoring in webUI tests is not needed. So closing this.
