### ISSUE TITLE
Run acceptance tests with different databases

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39881]
We want to run the acceptance tests with the common supported databases to verify that all is well:

mysql 8.0 #39877 - passed

mariadb 10.2 - that is the default already run in regular CI

mariadb 10.3 #39882 - passed

mariadb 10.4 #39883 - passed

mariadb 10.5 #39884 - passed

mariadb 10.6 #39876 - passed

pgsql 9.4 #39875 - passed

pgsql 10.20 #39874 - passed

oracle #39885 - all scenarios that fail have related issues (see comments in the PR)

**Comment by kiranparajuli589** [comment]
running acceptance tests with this big set of databases in every PR will certainly take much time. @phil-davis is it that crucial to run acceptance tests with all DBs in every build(which targets running acceptance test)? otherwise, how about we run acceptance tests only for `full-ci` or some special text in the pr-title or in nightly builds.

**Comment by phil-davis** [comment]
This issue was just to run CI one-time for each database, to verify that they all currently pass. Sorry for the misunderstanding.

Oracle has some fails - I need to check those and see if there are already issues for those.

**Comment by phil-davis** [comment]
The Oracle fails already have issues raised and are tagged in the scenarios. Everything else passes - good.

**Comment by phil-davis** [comment]
Note: I tried newer MariaDb today:
Mariadb 10.7 #40206 
Mariadb 10.8 #40207
