### ISSUE TITLE
Please keep documention urla alive

### ISSUE THREAD

**Issue by hannesa2** [owncloud/core#39958]
My ownCloud delivers suddenly this
<img width="725" alt="image" src="https://user-images.githubusercontent.com/3314607/161939668-6579d121-bd0a-4250-a001-83e6eb677fdf.png">

Burt the solution url https://doc.owncloud.org/server/10.5/go.php?to=admin-dir_permissions points to nothing

Remove this is not smart, this causes only pointless afford for nothing

**Comment by kulmann** [comment]
Hey @hannesa2 let me transfer your issue to the `core` repo and ping @mmattel for documentation related issues

**Comment by hannesa2** [comment]
But it's more then a documentation related issues. 
I can't remember any step from my side, expect an automatic `sudo apt-get update && sudo apt-get dist-upgrade`

The main questions are: 

- Why does this happen ?
- And how to solve it ?

**Comment by mmattel** [comment]
Hello @hannesa2 thanks for getting in touch, some questions:
* What is the ownCloud server version you are using
* As you say ...suddenly..., means this is not an attempt of a fresh install but an instance that is already productive for a while and reported at one time the error message you describe - or?

**Comment by phil-davis** [comment]
@mmattel it looks a lot like 10.5:
https://doc.owncloud.org/server/10.5/go.php?to=admin-dir_permissions

Any browsing to https://doc.owncloud.org/server/whatever ends up directing to https://doc.owncloud.com/docs/next/ and does not attempt to find/guess its way into the relevant doc page in the current documentation. IMO that is a limitation of the switch to the new documentation publishing - links into old versions of the documentation no longer go direct to the related page.

**Comment by hannesa2** [comment]
Btw, the primary problem is gone. I made it work with a simple reboot

**Comment by hannesa2** [comment]
> Second problem solve by not use EOL version from ownCloud?

Please read the headline of this ticket

**Comment by ho4ho** [comment]
Why waste time to EOL things only run by handful people if upgradiation is solution existing?

**Comment by hannesa2** [comment]
There are more guys then me, who want to use it and **not** maintain it. I only do something, when I'm forced to do so. Ubuntu LTS triggers me and the last time the update of OC was a nightmare.

Ok, let's start ...

## 1: I use
<img width="497" alt="image" src="https://user-images.githubusercontent.com/3314607/162394117-5d43b872-2368-4361-901a-76873fc77ce0.png">

##  2: There is a update button, promissing !
<img width="599" alt="image" src="https://user-images.githubusercontent.com/3314607/162393324-01e6d48c-34b2-453f-a84c-f6df4489ee70.png">

## 3: lets' click
<img width="829" alt="image" src="https://user-images.githubusercontent.com/3314607/162393724-5c78fc64-3dcf-4a7e-8fd6-cfd5d7536949.png">

## 4: I'm done

I've the fear that a manual process has the same quality
The last update I complete forgot how I did it, because it costs me more then one weekend of my live and I faded it out of my brain.

But you can help me. Is there a docker image which easy migrates a non-docker installation ?

**Comment by hannesa2** [comment]
> Why waste time to EOL things only run by handful people ..

Why destroy things which are still working ?

**Comment by iasdeoupxe** [comment]
Just arrived here because the title was updated recently so just my 2 cents:

From my PoV as a user it is fully understandable that a project is removing outdated documentation for EOL versions, i have seen other projects doing the very same.

A project always needs to consider various things like e.g.:

- keeping a documentation for such a EOL version online which usually requires putting additional maintenance effort into it. And at some point you need to cut-off maintenance effort
- removing documentation to avoid that users are arriving to these docs via e.g. Google and using wrong / outdated info (e.g. a 10.13.x user arriving at a 10.5.x docs and just using that info without checking the actual version which will definitely happen)

With the background that version 10.5.0 had been releases nearly 2 years ago at the time this issues was created (now it's 3+years) and really shouldn't be used in production it is IMHO fully understandable that the ownCloud team dropped the documentation for it.

If you disagree you probably would need to start a discussion with the ownCloud documentation team over at https://github.com/owncloud/docs-server/issues as AFAICT the core repo is not the place for documentation topics.
