### ISSUE TITLE
files_trashbin should not be able to be disabled for guest users

### ISSUE THREAD

**Issue by GeraldLeikam** [owncloud/core#40367]
If the admin removes the files_trashbin app from the app whitelist, guest users can delete files directly without them being moved to the owner's tashbin.

Scenario:

1. The admin deletes files_trashbin from the app whitelist for guest users.

2. User A creates a share with a guest user with full rights (share, edit, create, change, delete)

3. The guest user logs in and deletes a file

4. User A no longer finds this file (not even in the Trashbin) and cannot restore it either, since it is deleted directly without being moved to the Trashbin.
 

Therefore, deactivating the trashbin for guest users should be deactivated or have no effect on the app itself. The Trashbin mechanism should always run in the background to avoid data loss.

**Comment by phil-davis** [comment]
There might be 2 parts to this:
1) User A needs to be able to see deleted file in the trashbin and recover them as they want
2) Guest sees the Trashbin in the UI and can work with it (restore files, completely delete files...)

Probably item (1) functionality needs to happen all the time (whenever the files_trashbin is enabled)

And item (2) would only be available if files_trashbin is in the guests whitelist.

A similar thing might happen with files_versions - I suspect that when guests edit a file that is shared with them, that the share owner will want the versions caused by the guest to be created in the versions list. But if `files_versions` is not in the guest whitelist, then the guest should not see the UI of the `files_versions` app.

**Comment by phil-davis** [comment]
For other "file meta-data" apps it is not really a problem:
comments - the guest will not be able to make comments
favorites - the guest cannot favorite a file

**Comment by phil-davis** [comment]
Still needs to be looked at and decided.
