### ISSUE TITLE
[QA] when re-uploading the same file, the quota limit should not apply

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#40737]
Seen with 10.12.1 RC3

* set up user bob with 2.5 GB quota.
* upload a 1GB file into folders Photos and Documents. The quota usage now shows 2 GB of 2.5 GB.
* try upload another copy into the main folder. It fails with not enough free space. OK.
* try re-upload the 1 GB file into folder Photos. It fails with not enough free space. BAD. 
![grafik](https://user-images.githubusercontent.com/1108546/232010403-e63175e9-cbc8-49f6-89b8-c3480d09b4eb.png)

Expected behaviour:
* The overwrite dialog appears, and the file can be uploaded inplace, if the difference between old size and new size fits into the quota.

![grafik](https://user-images.githubusercontent.com/1108546/232010522-70bcf1b4-6af1-4ee4-846a-0d9867f99d14.png)
![grafik](https://user-images.githubusercontent.com/1108546/232010547-b3c0cb85-52c6-461c-a286-6e785ec64034.png)

**Comment by phil-davis** [comment]
"upload a 1GB file into folders Photos and Documents. The quota usage now shows 2 GB of 2.5 GB."

This does not make sense to me - why does the quota usage say 2GB at this point?

**Comment by jnweiger** [comment]
I meant to say, 1GB, into each of the twofolders. 2 GB in total.

Am 16. April 2023 13:36:33 MESZ schrieb Phil Davis ***@***.***>:
>"upload a 1GB file into folders Photos and Documents. The quota usage now shows 2 GB of 2.5 GB."
>
>This does not make sense to me - why does the quota usage say 2GB at this point?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/core/issues/40737#issuecomment-1510313227
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jvillafanez** [comment]
I'm tempted for a "won't fix" because this is a predictable behavior: although some of the files could be overwritten, you still need enough free space to upload them all at once.

To properly fix this issue there are several considerations:
* Multiple files can be uploaded at the same time, not just one by one.
* Some of the files (maybe not all) might get overwritten. The available free space should be adjusted according to those files.
* We need to get the size of all the files that will be overwritten (not sure if this is done already, but it might not be in a good place)
* The conflict dialog will also be important in the calculations:
  * If the user chooses to overwrite the file, the size of the overwritten file should count to the free space
  * If the user chooses to keep both files, it should keep the current behavior (it should be considered as a new file that won't be overwritten).
  * The conflict dialog is per file (I think). The user can overwrite just a couple of the conflicts, but not all.

In addition, I don't think it's a good idea to remove the check because we want to prevent the user from uploading a 10GB files when he doesn't have enough space.

**Comment by santanair** [comment]
won't fix. 
need to document behaviour @mmattel
