### ISSUE TITLE
Hook fileUpdate is not sent when file gets changed, if encryption is enabled

### ISSUE THREAD

**Issue by alexanderonlyoffice** [owncloud/core#40746]
Hello everyone. If one enables encryption in ownCloud 10, hook mentioned under this link https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/master/lib/hooks.php#L48 is not sent when the file is changed. If you have any questions or need more details, please let me know.

**Comment by jvillafanez** [comment]
I think I'll need steps to reproduce, without the onlyoffice app if possible.

The event should be triggered in https://github.com/owncloud/core/blob/c4f8cd14fb2761cca93fba53199a7595cdb80e70/lib/private/Files/View.php#L660 . The view should be in top of the storage and storage wrappers, so it should trigger regardless of encryption.
There are conditions that could prevent the event from triggering, mostly if the file is a part file or it's outside of the user's directory.

Other than that, there could be some errors happening before the event is triggered.

In any case, you need to fill the issue template so we can get more information about the environment, such as ownCloud version and log files. You can click on the "new issue" button and copy the template here.

**Comment by Misokados** [comment]
Hello @jvillafanez 
If you don't mind I will join this thread.
The ONLYOFFICE app is subscribed to the **write** event:
https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/2afca075249f24d857f0b3097d565f5129e88d17/lib/hooks.php#L48

The file is saved using the method:
**$file->putContent**:
https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/2afca075249f24d857f0b3097d565f5129e88d17/controller/callbackcontroller.php#L547
which in turn calls the method  **view->file_put_contents** and after that **basicOperation('file_put_contents', ...**  with the hook **write**: https://github.com/owncloud/core/blob/97d0995390cd4cbbe9a7862a53157d64dcaf91a8/lib/private/Files/View.php#L752

The hook is called in the **runHooks** method:
https://github.com/owncloud/core/blob/97d0995390cd4cbbe9a7862a53157d64dcaf91a8/lib/private/Files/View.php#L1214
But when master encryption is enabled, the **shouldEmitHooks** check fails
https://github.com/owncloud/core/blob/97d0995390cd4cbbe9a7862a53157d64dcaf91a8/lib/private/Files/View.php#LL1335C14-L1335C29
Because of that condition:
 **Filesystem::$loaded**:
https://github.com/owncloud/core/blob/97d0995390cd4cbbe9a7862a53157d64dcaf91a8/lib/private/Files/View.php#L1303

Please let us know if you can fix this situation.

**Comment by jvillafanez** [comment]
It seems the ownCloud's FS isn't initialized somehow.... The FS is usually initialized with the `setupFS` (https://github.com/owncloud/core/blob/add4323a37b421af289059900f84bed7c4ae8413/lib/private/legacy/util.php#LL132C27-L132C27) so maybe that call is missing.

I might need a stacktrace when you get the `return false` in https://github.com/owncloud/core/blob/97d0995390cd4cbbe9a7862a53157d64dcaf91a8/lib/private/Files/View.php#LL1302C8-L1302C27 to get an idea of where the code is going through.

In order to confirm that a `setupFS` call is missing, you could try adding it in your controller. This is just for verification purposes, I don't think you'd need to do call it yourself.

**Comment by jvillafanez** [comment]
@Misokados I'm pretty sure the problem is a missing `setupFS` call.
Usually, if the user is logged in, the `setupFS` is called in https://github.com/owncloud/core/blob/f4f8977c630d49c9bd27a5993111300e2dc5d6d4/lib/private/User/Session.php#L454-L460 so you don't need to do anything out of the ordinary.

However, in your case, the `track` method of your controller is marked as a public page, so I guess there is no login being done in any way. If it's a callback coming from the onlyoffice document server, it's very likely that you don't have a user logged in (unauthenticated call, and no cookie session).
Going down a bit, in https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/2afca075249f24d857f0b3097d565f5129e88d17/controller/callbackcontroller.php#L499-L503 you setup the FS only if there is no encryption.

I think the options you have are:
* Make an authenticated call somehow so ownCloud can setup the FS for the authenticated user. This could be difficult taking into account the multiple authentication options, so probably not recommended.
* Handle authentication on your own. You could send the ownCloud's id with a custom one-time token to your onlyoffice document server and then make the request back from the document server with those 2 parameters. The one-time token is just for security purposes, so you can use any other mechanism to ensure it's a legitimate call from the document server. Once you know the call is from a legitimate user, you can setup the FS for that user.

**Comment by Misokados** [comment]
@jvillafanez 
Thank you for the provided details. We need some time to check out the possibility of implementing the mentioned scenario.
