### ISSUE TITLE
[tests-only] publicWebDAVAPIVersion not used in acceptance test publicLocksFileLastSharedFolder

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#40756]
In `tests/acceptance/features/bootstrap/WebDavLockingContext.php` the function `publicLocksFileLastSharedFolder` takes parameter `$publicWebDAVAPIVersion` but the parameter is not used anywhere.

Test scenarios that use this code, and think that they are testing both public webDAV API end-points are not actually doing that.

Needs investigation and correction.

After fixing in core, also check if this code is also in the ocis API acceptance tests, and fix it there also.

**Comment by KarunAtreya** [comment]
@phil-davis In tests/acceptance/features/bootstrap/WebDavLockingContext.php the function publicLocksFileLastSharedFolder is not used anywhere on ocis because there is no locking feature in ocis https://github.com/owncloud/ocis/issues/1284#issuecomment-1238336767
So am i required to fix this issue in core only?

**Comment by phil-davis** [comment]
@KarunAtreya fix it in core, then also apply the same fix in the ocis code.
The code was copied from core to ocis a while ago, to make it easier to manage the test development for ocis. But when there are test code issues/bugs we should apply fixes to both places.

**Comment by phil-davis** [comment]
Test code was fixed in #40883

**Comment by phil-davis** [comment]
A server issue #40882 was found. That needs separate action - see the issue.
