### ISSUE TITLE
[QA] Upgrade disables index.php-less setup

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#40813]
Seen with 10.10.0 upgrading to 10.12.1

* Install 10.10.0 with
* Switch to index.php-less setup:
   - `occ config:system:set htaccess.RewriteBase --value "/"`
   - `occ maintenance:update:htaccess`
* Visit the /settings/admin?sectionid=general, 
   check if an update is available. Click.

* The update succeeds, when the browser refreshes, an error is shown:

![grafik](https://github.com/owncloud/core/assets/1108546/d8aae1ab-fee2-486b-ac50-8cc1df3ac74e)

* Check the command line, to see, the rewriteBase:
  ```
  occ config:system:get htaccess.RewriteBase
  /
  ```

----

* Insert  `/index.php/` into the URL. it works again.
![grafik](https://github.com/owncloud/core/assets/1108546/cf83ccd8-20fb-498e-abbd-9a9a4c4ffdfd)

Expected behaviour:
* The index.php-less setup is still active after the upgrade.
* htaccess.RewriteBase and .htaccess should remain consistent after upgrade.
* https://doc.owncloud.com/server/next/admin_manual/maintenance/upgrading/package_upgrade.html#upgrade-steps - it should mention `occ maintenance:update:htaccess` near the end.
* https://doc.owncloud.com/server/next/admin_manual/maintenance/upgrading/update.html same ...
* https://doc.owncloud.com/server/next/admin_manual/installation/manual_installation/script_guided_install.html same ...

Workaound
* manually run `occ maintenance:update:htaccess`
* Now we are back with the expected index.php-less setup.

**Comment by jnweiger** [comment]
@mmattel @pako81 is this something, we should  fix in code, or in documentation?

**Comment by pako81** [comment]
I think this is expected behaviour as the .htaccess file gets replaced upon an an upgrade so the previously applied manual changes have to be reapplied.

In case of the "Scripts for the Script-Guided Installation" page, this is documented here https://doc.owncloud.com/server/next/admin_manual/installation/manual_installation/script_guided_install.html#usage and here https://doc.owncloud.com/server/next/admin_manual/installation/manual_installation/script_guided_install.html#final-steps.

While the manual upgrade procedure has a reference here https://doc.owncloud.com/server/10.11/admin_manual/maintenance/upgrading/manual_upgrade.html#backup-manual-changes-in-htaccess.

**Comment by mmattel** [comment]
Let me assume the following: when changing to index.php less setup, you must run:
```
occ config:system:set htaccess.RewriteBase --value "/"
occ maintenance:update:htaccess
```
where the maintenance command is mandatory (for apache) to fix the rewrite rule. The maintenance command itself gets its data from the database where the rewrite rule is stored.

Now, when one updates his instance, this changes back the content of htaccess to the delivered default which does by design not include the index.php less rewrite rule.

If this is correct, we have two choices:

* When upgrading a system, let the process internally run `maintenance:update:htaccess`.
Having that, one can apply all manually added changes as described. IMHO, this is the correct way as the change for index.php less setup was part of the config and should not trigger additional steps - even after upgrades.
* We add a special note to the upgrade process (script/page) that one must rund the occ command when formerly changed to a index.php less setup.

The challenge is, that one interprets _manually added_ in a way he did it explicit, not via command that affects the htaccess rule. This situation makes the current behaviour questionable.
