### ISSUE TITLE
Sendfile support dropped and file lock logic

### ISSUE THREAD

**Issue by yevon** [owncloud/core#40887]
It seems thant sendFile Apache / Nginx compatibility was dropped in the past because of compatibility concerns with the file-locking functionality.

https://github.com/owncloud/core/issues/39547

This lack of sendFile support seems to affect heavily to downlaod performance, and even with a pretty big machine with 10gb ethernet and nvme drives you cannot get much better download speeds. It is specially noticeable when you enable ssl support.

It was deleted in the past due to concerns with the file-locking system, because if you delegate downloads to apache, you could not unlock the file once download finishes. Related issue: https://github.com/owncloud/core/issues/39547.

If the main concern is about how to make it to work with file-locking, wouldn't this work? (I might get wrong, as I don't really know how current lock system works).

1. If someone wants to change a file, make a temporary copy of it and allow to modify that copy. You will lock that copy for the given USER1 instead of the original file in the database, so nobody else could edit the file apart from USER1. This fixes the issue of having to make a temporary copy of the big original file for downloads with sendFile support, as it won't be needed.
2. File downloads / reads won't be blocked in any way, they could access to the original file as long as they want until USER1 finishes its modifications. If someone tries to upload a new version of the file while the USER1 is still editing it, they will receive a notification saying that it is blocked by USER1.
3. When USER1 saves, or uploads a new version of the file, the system would lock the file read and write access to everybody, including USER1, until it is successfully replaced with the modified file. The system will perform polling for checking it there are any pending downloads of the original file, and when not it would replace it. No new downloads would occur as it is locked, you just have to wait to all current downloads to end. It seems that there are ways to achieve it, but is OS dependant. In linux could be with something like this to check if the file is used by any other process: https://nerdia.net/2011/01/17/check-if-a-file-is-open-by-another-process-in-php-linuxunix/

**Comment by DeepDiver1975** [comment]
The overall reasoning was in depth discussed in https://github.com/owncloud/core/issues/39547 - there is nothing more to add from my pov.

Never the less:
- temporary copy will not work because (thinking about bigger installations) you will need tons of storage on each web server node
- temporary copy will require copying tons of data from storage to web server
- in case of e.g. encryption: it is php which is decrypting the files - you will save nothing with sendfile
- ....


Finally: please note that owncloud php code base has reached end of life - the future is within ocis. We will not add any new feature to the php code base.
