### ISSUE TITLE
[QA] login fails with IE11, syntax error in sharedialogview.js

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#40932]
Seen with 10.13.0-rc.1 and Internet Explorer 11 (Microsoft Windows version 1809)

When trying to log in, at the web UI, the login is denied with the message
"You took too long to log in, please try again now"

This error message is wrong. I can type very fast, it always occurs.
The real problem seems to be with javascript syntax. The browser console shows:
![image](https://github.com/owncloud/core/assets/1108546/138ffd07-7e62-4499-866c-2ebccf78c95d)

`occ app:disable files_mediaviewer` removes the second error, but login still fails the same.

**Comment by jnweiger** [comment]
workaround: use edge (on the same old win10)

**Comment by jnweiger** [comment]
This seems to be a regression. With 10.12.2 the login works:
![image](https://github.com/owncloud/core/assets/1108546/f9f18974-7431-4b63-bd90-9075ece12200)

**Comment by hodyroff** [comment]
We didn't deprecate IE support. We wanted to maintain it, can we do a fix? Propably coming from the JS fixes?
@fschade or delegate

**Comment by jnweiger** [comment]
Ah, more details:
* with a freshly booted windows, the login works.
* when the user clicks the share icon of a file or folder, the sharing sidebar opens blank.
* thereafter the user is being kicked out, and can no longer log in with the above message.

**Comment by fschade** [comment]
@grimmoc, if i remember right you have a windows installation, can you have a look?

**Comment by JammingBen** [comment]
The error seems to be in `sharedialogview.js`. Since this was working in `10.12.2`, it must have been due to some recent changes. I stumbled upon this commit: https://github.com/owncloud/core/pull/40886/files#diff-32a9288d49d563b83dd8bab064e9aa35a9f3c8f0aa0321bf1b61089d9c82ea5a. It doesn't change much in that file, but it includes this:

```
let showIcon = false;
let iconClass = ""
```

I remember having some compatibility issues when using `let` or `const` in oC10. I guess this is the problem and we need to use `var` instead. I can't get IE running on my Mac though. @grimmoc I could help you with setting up oC10 to check.

**Comment by grimmoc** [comment]
Yes, IE11 doesn't support ES2015, which includes support for `let` and `const`. `var` must be used instead. On my Win 10 machine I cannot open a regular IE11 any more since it will always redirect to MS Edge instead. There's a IE legacy mode in Edge which however seems to implement support for ES2015. I ran a test file "test.html" containing `const a = 'hello'; alert(a);` and it would show a message box containing "hello" as (not) expected. I think a Windows version prior to 20H2 must be used to get access to the old IE. I mean, seriously, who is still using that tho?

**Comment by jnweiger** [comment]
Do you also have a cure for the problem with files_mediaviewer_init.js ?

**Comment by JammingBen** [comment]
> Do you also have a cure for the problem with files_mediaviewer_init.js ?

I feel like that needs some debugging. After a first glance at the code: is this a new problem? It looks to me as if the app has never been compatible with IE. Last change to `src` has been made over 2 years ago... or did some dependency bump cause this?!

**Comment by jnweiger** [comment]
Ah, nevermind, this is a known issue: https://github.com/owncloud/files_mediaviewer/issues/355

**Comment by JammingBen** [comment]
Then I'm closing here since https://github.com/owncloud/core/pull/40934 has been merged.
