### ISSUE TITLE
External Storage Support SMB / CIFS - SAMBA

### ISSUE THREAD

**Issue by kenrmayfield** [owncloud/core#40940]
I am using Owncloud Community Version 10.12.2.1.

**Why is SMB / CIFS missing from the External Storage Drop Down List?**

**It has been in Previous Versions.**   

**Do you have to Buy a Commercial License just to use SMB(SAMBA)?**

![image](https://github.com/owncloud/core/assets/89940641/e29ce6c8-5abc-4d04-a8ef-3bded0a963db)

**Comment by jnweiger** [comment]
No that is not a licensing issue. SMB should be there.
I am running
* `docker run --rm -ti -p 6662:8080 -d owncloud/server:10.12.2`
* `docker run --rm -ti -p 6660:8080 -d owncloud/server:10.13.0-rc.2`

And I see it on both:
![grafik](https://github.com/owncloud/core/assets/1108546/b90078b9-8700-4b38-8555-059329f2e8fd)

**Comment by kenrmayfield** [comment]
@jnweiger 
@phil-davis
@DeepDiver1975



Just letting you know I am not using OwnCloud for Docker however I am using Owncloud Version 10.12.2.1 running on CentOS 8 Stream.  
I downloaded OwnCloud 10.12.2 from:
https://download.owncloud.org/community/owncloud-10.12.2.zip

**Why do you think the Option for SMB(SAMBA) is not Listed?**

![image](https://github.com/owncloud/core/assets/89940641/e29ce6c8-5abc-4d04-a8ef-3bded0a963db)

**Comment by DeepDiver1975** [comment]
There is a message: smbclient not installed.
Do so and it will work

**Comment by kenrmayfield** [comment]
@DeepDiver1975 

Thank You.   I installed smbclient CentOS 8 Stream and SMB Personal worked with my Shares.

For the SMB Collabortive do you have too Purchase a License since it is asking for a Account and Code?

I was trying to find the Cost but had no luck.

**Comment by cortho** [comment]
Since documentation is very poor on this topic - see https://github.com/owncloud/docs/issues/3520 - I'll answer here
Both SMB Personal (unique file IDs) and  SMB Collaborative (shared file IDs) come with the files_external app which does not require a license.
TBH I don't really know what the windows_network_drive app is actually doing.

Since this is an issue tracker plus the ticket is already closed please follow up to the ownCloud forum at  https://central.owncloud.org/ if there are any more questions

**Comment by kenrmayfield** [comment]
@DeepDiver1975

Thank You. I installed smbclient on CentOS 8 Stream and SMB Personal worked with my Shares.

For the SMB Collabortive do you have too Purchase a License since it is asking for a Account and Code?

I was trying to find the Cost but had no luck.
