### ISSUE TITLE
Update ownCloud with Updater app don't works

### ISSUE THREAD

**Issue by hannesa2** [owncloud/core#41145]
I try to update my installation (here you see my setup ##39256) with this promising button.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/3314607/134292432-df5ac9d2-bf7b-4a75-9389-f39c6ff074e4.png">

but I run into

![image](https://github.com/owncloud/core/assets/3314607/31df9083-48a5-4951-b766-2e941c38658c)

Client error response [url] https://localhost/owncloud/index.php/occ/config:list [status code] 404 [reason phrase] Not Found

**Comment by iasdeoupxe** [comment]
Seems the issue tracker for the updater is over there:

https://github.com/owncloud/updater/issues

This specific case looks more like a web server misconfiguration, the "Client error response" to "/owncloud/index.php/occ/config:list" from the screenshot (usually it's better to not use screenshots for error message so that other user can find them but also can copy them for further search) with a 404 status (Not Found) shows that the web server seems to not provide ownCloud on the "localhost" domain which looks like that is mandatory.

But the updater seems to be not the recommended update method anyway:

> This is not the recommended upgrade procedure

-> https://doc.owncloud.com/server/10.13/admin_manual/maintenance/upgrading/upgrade.html

**Comment by hannesa2** [comment]
> This specific case looks more like a web server misconfiguration, the "Client error response" to "/owncloud/index.php/occ/config:list" from the screenshot

Sure, what how to solve this misconfiguration ?

> usually it's better to not use screenshots for error message so that other user can find them but also can copy them for further search

Ok, I added the plaintext as well

**Comment by hannesa2** [comment]
How to solve this misconfiguration ?

my `config.php` looks like

```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'ocr8mbf8x3zx',
  'passwordsalt' => 't2xxxxx',
  'secret' => 'xxxxxx',
  'trusted_domains' =>
  array (
    0 => 'www.mxxxxx.info',
  ),
  'datadirectory' => '/daten/owncloud/data',
  'overwrite.cli.url' => 'https://www.mxxxxxx.info/owncloud',
  'dbtype' => 'pgsql',
  'version' => '10.5.0.10',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'ha',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'google.com',
  'loglevel' => 2,
  'maintenance' => false,
  'theme' => '',
  'updater.secret' => '$2xxxxxxxxxxxx',
);
```

**Comment by iasdeoupxe** [comment]
Now that there is #729 the one here could be closed. :-)
