### ISSUE TITLE
Feature Request - support for aliasing/shortcuts/links

### ISSUE THREAD

**Issue by andrewbutterfield** [owncloud/core#4269]
It would be nice to be able to create alias/shortcut/link in ownCloud and have them work when viewed from the relevant platforms Mac OS X/Windows/Unix. Currently such objects seem to be invisible in the web interface or in mobile clients. 

In Mac OS X Finder in the ownCloud window  I can create one  that works,
as is also the case using the ownCloud window in Windows Explorer. But these
aliases/shortcuts are not visible in the web interface or in other ownCloud windows.

**Comment by Enoch247** [comment]
I think it would be useful. I have a templates folder which I would like sync between home and work. some of my template files are work related (ex: company letterhead and powerpoint templates) the rest are common which I have made many years ago, and use at work and home (template.c template.java, etc). It would be nice to have work and home versions of the folder with common files linked rather than copied between them.

**Comment by wintifrosch** [comment]
This request should be re-opened IMHO. 

Necessities: 
-> to allow access from different contextes (=folders)
-> to avoid duplicate files
-> to avoid that only some of the copies will be updated if required

Could be boiled down to a .uri file type (MIME type text/uri-list according to RFC 2483, see https://tools.ietf.org/html/rfc2483#section-5). This file type is presented as a file or folder in ownCloud [1], but is just a common link: If such an object is clicked, the client treats this as a simple link by opening the URL given inside the file [2]. 

Maybe this requires adaptions in ownCloud, in addition to just processing .uri files:
->To create such a file, the user may click on the [+] icon in the breadcrumbs line. At the bottom of the dropdown list, there's a new option "create shortcut link". In a dialog box, the user may choose to either paste a hyperlink or to browse an object in his file structure. In the latter case, the url will point to an absolute object ID, since the same file may have another path for another user.
-> If a user opens such a file (by clicking on the object in the file list) [3], the client must be able to resolve the absolute object ID mentioned above and see whether he has access to that file. If he has access and the target is a file, the client can open that file (as usual), but if the target is a folder, the client must open that folder. 

[1] probably, there are 5 presentations (icons) to be implemented: for files and folders and for other hyperlinks. Some files and folders may show a locked-icon, if the client has no access to this file.
[2] A text/uri-list file may contain more than one URI. Maybe owncloud will only process the first URI or will ask back if it's ok to create multiple tabs/windows -- and at least state the number of URIs contained.
[3] While there's a RFC standard for .uri files and owncloud may learn how to process those files in the browser, there's IMHO no standard across all browsers and platforms how to treat those files if the files are accessed over webDAV.

**Comment by Fabi12345** [comment]
No necessity?
I don't wanna copy the file 999999 times and put it into 999999 folders, damn what a question, of course its important and a necessity!

**Comment by Marx1st** [comment]
I second this feature request!

**Comment by EdwardEisenhauer** [comment]
I was looking for this feature too. I have many PDFs which I would like to access from different directories' structures. E.g. I would like to have "Datasheets" directory where all of my data-sheets would be stored and have symlinks/shortcuts to them in the projects' directories where I am using them.

**Comment by micbar** [comment]
I personally think this very hard to display in the UI and create a good user experience.

The share permissions of the destination could be different than storage permissions of the source. That could break the expected behavior inside a shared tree and would make it very confusing for the users. That finally would create a lot of helpdesk and support requests.

From a PO perspective i would deny this.
