### ISSUE TITLE
File upload in browser - use PUT if possible

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#4380]
Our file upload javascript component is capable of using PUT for file upload
https://github.com/blueimp/jQuery-File-Upload/wiki/Options

Using PUT has some advantages over the existing POST:
The PHP code will be trigger as soon as the first few kbs arrived th server.
In contrary in case of POST the web server will first receive the whole file and trigger the PHP code after the upload has been finished.

Why is this a better approach:
- quota and other checks can be performed right in the beginning
- follow up processing can benefit from stream e.g. push data to external file systems, encrypt on the fly (?)

From my understanding this is why WebDAV uses PUT for file upload as well.

@karlitschek @danimo @dragotin @icewind1991 @butonic @blizzz @schiesbn @bartv2 @bantu @ringmaster 

I'm summoning you all because I'd like to know any impact on any component you are working on if you see any issues with this approach.

THX

**Comment by DeepDiver1975** [comment]
this will be implemented once we move over to use webdav in the files apps #12353

**Comment by PVince81** [comment]
I suggest we keep this ticket as a subticket of https://github.com/owncloud/core/issues/12353.

Implementing PUT is already a challenging task, especially in regards to cross-browser compatibility. So it makes sense to have this implemented in its own PR.

**Comment by PVince81** [comment]
Moving to Webdav for uploads is scheduled for 9.0, adjusting milestone.

**Comment by PVince81** [comment]
CC @cmonteroluque

**Comment by cmonteroluque** [comment]
nod

**Comment by PVince81** [comment]
Hint: this is still open. Maybe we can have a look at this https://github.com/23/resumable.js which seems to allow for chunking

**Comment by PVince81** [comment]
The toughest part here is making file conflict detection work with our conflict dialog, for BOTH the webdav approach (using precondition + 412 status) AND also for the IE8 workaround that uses ajax/upload.php... I'll see if I can bring their behavior / responses as close as possible.

**Comment by PVince81** [comment]
"tough" as in: lots of refactoring and rearranging response formats. The file-upload.js is a bit messy :smile:

**Comment by PVince81** [comment]
- [ ] make sure that folder upload still works (might need client control, MKCOL, etc)
- [ ] conflict dialog

**Comment by PVince81** [comment]
WIP PR here https://github.com/owncloud/core/pull/21237

**Comment by butonic** [comment]
I'll keep an eye on the tough part to educate myself on clean js code. Boy this has been a long time ago. And I still remember what the code looked like before ...  ;)

**Comment by PVince81** [comment]
Interesting, the blueimp uploader would POST to this URL with the IE iframe fallback:
```
192.168.56.102 - - [17/Dec/2015:18:17:06 +0100] "POST /owncloud/remote.php/webdav/modern.IE.1024x768.jpg?_method=PUT HTTP/1.1" 501 247 "http://192.168.56.1/owncloud/index.php/apps/files/" "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)"
```
This means that in theory instead of keeping "ajax/upload.php" we could simply write a Sabre plugin that processes this POST and internally plugs with the PUT logic. :smile:

**Comment by PVince81** [comment]
Still needs a bit more work for the PR https://github.com/owncloud/core/pull/21237, moving to 9.1

**Comment by MTRichards** [comment]
Estimation: 1 week

**Comment by PVince81** [comment]
Someone raised a ticket for PUT chunking. Since we didn't have a dedicated ticket, let's use this one https://github.com/owncloud/core/issues/25181

**Comment by PVince81** [comment]
Hmm, but when overwriting a file we are using POST on collection with "Add-Member" here https://tools.ietf.org/html/rfc5995#page-5 here https://github.com/owncloud/core/blob/master/apps/dav/lib/Connector/Sabre/FilesPlugin.php#L440.
This is used when the conflict dialog appears and the user wants to keep old files, so we use "Add-Member" to suggest a name for the server. The server then append "(2)", "(3)" or whatever depending on existing files.

Drawback is that we still use POST and would suffer from limitations.
Reopening to reconsider this.

Also this approach is not compatible with new chunking, so might still need a client-side only approach that looks like this:

1. PUT file "test.dat"
1. Server answers with 409 conflict
1. User resolves conflict in dialog by ticking both "New files" and "Already existing file"
1. Client checks current file list (which might not be up to date) to add a "(2)" in the name: "test (2).dat"
1. Client uploads "test (2).dat"
1. Server answers with 409 conflict again because someone concurrently created "test (2).dat"
1. Client tries again with next "test (3).dat", etc.

**Comment by PVince81** [comment]
Fix for autorename is here: https://github.com/owncloud/core/pull/26078
This removes POST completely for uploads.
