### ISSUE TITLE
Trashbin on external storage

### ISSUE THREAD

**Issue by oktawave-code** [owncloud/core#4389]
Hi,
we use external storage (via swift) to keep all files. The problem is that the trashbin works independently, and stores files locally. This cause several issues:
- data must travel form external storage to local storage and vice versa when deleted/undeleted
- our local storage is much smaller than dedicated external storage, so the local storage is insufficient to keep all trashed files
- we need to have at least 2 webservers that will serve owncloud web interface, the http traffic will be balanced between them. So we want to avoid keeping any local files on webservers, all data (users files) must be stored externally

My question is: will the trashbin support external storage just like other parts of owncloud in the nearest future? Is there a simple way to add a support for external  storage in current oc version?

Best Regards,
Tom

**Comment by tibmanus** [comment]
I think this would be the right issue to express my confusion about the space management.
The documentation tells me the following: "Deleted files that are still in the trash bin do not count against quotas. The trash bin is set at 50% of quota." But what is the quota, what if I don't use a quota for my users?

Here is an example about my confusion:
I have the server application installed on a disk with limited capacity, so I mount up locally a very large drive as an external storage and I only keep my files here. When I delete files, all these files are copied back to the trans on the local storage and I see that my total available space has reduced. I can keep doing this until I reach 0byte availability. What happens then? Why the versioning/trash didn't get automatically emptied? How should I read the "50% of quota" in this case?

**Comment by PVince81** [comment]
You're right, it's not very clear. The quota value is the one of the home storage and doesn't account for any external storages. Making the quota count external storages is tricky because it would be different depending on the folders.
Also the trashbin + versions information (the deleted files and version files) are stored in the "data" folder, which isn't currently on external storage.

This is why it was suggested to have trashbin and version stored on the respective external storages. The expiration logic could then be run for every storage separately based on the space available on each storage.

Hope that makes sense.

**Comment by PVince81** [comment]
So in your case if your "data" folder doesn't have a lot of space, then versions and trash might expire very often.

**Comment by tibmanus** [comment]
So reaching 0bytes will still give me a working cloud, but without version/trash?

**Comment by PVince81** [comment]
Yes, without versions and trash.

**Comment by SergioBertolinSG** [comment]
I find this very interesting to have since currently in 8.2beta1 it isn't possible to delete a group of files in external storage => annoying.

**Comment by PVince81** [comment]
> currently in 8.2beta1 it isn't possible to delete a group of files in external storage => annoying.

@SergioBertolinSG can you elaborate ? Maybe you mean https://github.com/owncloud/core/issues/16533 ?

**Comment by SergioBertolinSG** [comment]
Yes, exactly that thanks.

**Comment by PVince81** [comment]
If you want to test deletion, you can create a subdir. That problem only exists for files directly under the mount point.

**Comment by PatelParas** [comment]
I use AWS S3 as primary storage and implemented .files_trashbin and .files_versions folder inside root space of bucket similar to .Trash-oc-<username>  you discussed previously but problem is that in case of AWS-S3 they don't have object rename method or API officially because its object storage or business policy of AWS so in order to rename or Delete object(move to trashbin) i need to pass following steps 
1) Copy object from orignal into (.files_trashbin/filename.dtimestamp) 
2) Delete orignal file

Step 1 in case of big size like 1 GB++ and if files have some versions also then move everything to .files_trashbin and .files_trashbin/version folder it takes long time to copy. and i can't imagine scenario incase of large object 8 GB ++. better to provide software level object rename or maping (DB:files_cache) table need to include object mapping column. so we don't need to move or rename object on storage just update object name in SQL DB. I know this steps can increase complexity in user's quota space count method.

Reference of rename method in AWS S3 : https://github.com/owncloud/core/blob/master/apps/files_external/lib/amazons3.php#L514

**Comment by nicoolas** [comment]
Any news on this topic ?
Using version 9.1, I just deleted a large amount of data from an external storage, that ended up downloaded on my server, and filling up disk space.

Otherwise, anyone knows if trash can be disabled altogether for external storage ?

Thanks

**Comment by plastikschnitzer** [comment]
If you delete files directly on the external storage aside ownCloud, it won't fill up your ownCloud trashbin. 

For some users this might be desired behavior, for others not …

**Comment by nicoolas** [comment]
It sure could be a desired behavior; 
However, I think that an option to disable the trash bin for external storage would be appreciated - simply because external storages are quite often setup to limit server disk usage.

**Comment by RedKage** [comment]
Hello. Any news on this? I stumbled on this issue because of an error when I was trying to delete files from my G Drive. Possibly, this issue here is related.
/subscribed
