### ISSUE TITLE
Owncloud should show system disk quota if set

### ISSUE THREAD

**Issue by novij** [owncloud/core#5352]
If no user quota is set within owncloud it shows the free space of the whole disk, even if there is a disk quota set for the user.

In this case Owncloud should exec('quota -w') and use the values reported from this tool.

**Comment by dotnull** [comment]
I ran into the same problems and simplified it for my needs by making the use of a system config value.
I edited the file __lib/private/files/storage/local.php__ to use *max_sys_free_space* from config instead of *disk_free_space* (if it exits):

```php
public function free_space($path) {
  $space = \OC::$server->getConfig()->getSystemValue('max_sys_free_space', @disk_free_space($this->getSourcePath($path)));
  return (((int)$space === 0) ? \OCP\Files\FileInfo::SPACE_UNKNOWN : $space);
}
```

This is quite enough for me and my needs... As config.php itself is a PHP some might want to use exec quota-w there if really needed. Others can type in max free space as int like me. Or am i wrong?

**Comment by VicDeo** [comment]
>If the system runs out of quota (or gets within 10% of quota) the system needs to throw a warning of some kind. And again at 5%.

THIS needs to be figured out
https://github.com/owncloud/core/issues/16301#issuecomment-111153907

**Comment by PVince81** [comment]
It should already be possible to write hoster specific apps which provide a storage wrapper which overrides the `free_space` method and use whatever API the hoster provides to check quota.

There is nothing generic that can be added in core that would work for all hosters.
