### ISSUE TITLE
ldap paged search support should be reworked

### ISSUE THREAD

**Issue by leo-b** [owncloud/core#6311]
Paging support currently is a mess...

The break condition while doing a paged search is an empty cookie: The server returns a cookie of "" on the last page of the search.[1]

However, empty cookies are not stored in the cookie cache and thus owncloud will not handle search requests that have no more results correctly.
Currently the search for a cookie will fail after the last page and the code for retrying the search will be executed. This second search also won't handle the empty cookie correctly, so the results will be an unnecessary search and a "Paged search failed :(" error.

[1] http://www.ietf.org/rfc/rfc2696

**Comment by PVince81** [comment]
@jvillafanez your thoughts on this ?

**Comment by PVince81** [comment]
Moving to backlog.

@jvillafanez please provide an estimate for this big rework to be able to schedule this properly.

**Comment by jvillafanez** [comment]
Too big to estimate. It could take several months: this needs a full rewrite of the basic functionality of the app (2-3 weeks dedicated, which will likely be extended due to other issues to attend during this time), recheck and fix any possible issue with the connection with ownCloud (1 day if there are no problems, but it will likely take 1 week). We also need to test carefully the behaviour with each LDAP provider (3 days per provider for testing, probably more if we need to test in depth, without including the time we need to fix any possible issue).

In addition, there might be code tightly coupled all over the app that will need to be changed, and it will add more time.

There are architectural changes that we should do within the app.
* The "one connector does everything" approach doesn't seem a good idea taking into account the differences between the LDAP providers. We might use some features for a specific provider that aren't in others.
* There are some LDAP features that might not be covered by the PHP code.

**Comment by PVince81** [comment]
> one connector does everything

Maybe core needs to be able to support multiple instances of the same user/group backend ?
That ideally with a nice GUI where you can configure them. Each backend can then be pointed at a different LDAP server. So your config could look like this:

```
Configured backend list
- local DB backend
- LDAP backend 1: ldap://server1
- LDAP backend 2: ldap://server2
```

**Comment by jvillafanez** [comment]
My point was that the same code is used to connect to openLDAP, AD, or any other LDAP provider. Unless we stick with the oficial RFCs ignoring whatever is outside of them, I don't think it's a good idea. There might be options that could be used for one provider but not others, or fixes for one but not the rest.

**Comment by butonic** [comment]
With the introduction of the account table we have all users in the db and search in for users operates on the db. The sync command can be used to periodically update the user metadata. It uses a single search and uses paging without caching anything. Furthermore, a login updates the metadata as well.

I will close this, even though I would like to add more testing for different LDAP servers. @leo-b open a new issue in user_ldap if things don't work as expected.
