### ISSUE TITLE
[FEATURE RQST] Offload file/directory deletion from webserver to background task

### ISSUE THREAD

**Issue by ser72** [owncloud/core#6963]
**BACKGROUND**
Having a directory within ownCloud which contains many subfolders and files (in the test scenario I utilized 1 folder with subfolders containing 2 versions of oC code -- 28,000 files total)

Upon deleting the folder within ownCloud, the wheel spins and ownCloud is "unusable" until the folder is deleted (which took upwards of 5 minutes in my scenario).  In certain scenarios, where there are timeouts within the network, an 504 Gateway timeout occurs, and it appears that ownCloud "fails".

**REQUEST**
Offload the deletion of files/folders to a background process rather than having the web server performing such tasks.  This will free up the web server to continue to perform other ownCloud tasks for the users.

@MTRichards @karlitschek

**Comment by Xenopathic** [comment]
A pure deletions will be very fast on all storages, while with the files_trashbin app files are now moved instead of copied, so that is also fast. Only copying files from an external storage to the trashbin is slow, but the alternative is possible data loss, so a slow request is perfectly acceptable IMHO (although we should really keep the trashbin on the external storage itself)
