### ISSUE TITLE
Wrong folder date when syncing

### ISSUE THREAD

**Issue by solopa** [owncloud/core#7009]
First, I'm not sure if this is a core problem or a client (Windows) problem. I put it here since it's the same problem as issue #1897 (closed because it needed info).

### Expected behaviour
The creation date of a folder should be the same in every computer after syncing.

### Actual behaviour
After syncing, the date of a folder is different in each computer.

### Steps to reproduce
1. Create a new folder in a computer (let's say at 9:00). Sync ownCloud.
2. Later, in another computer, sync ownCloud. It will create the folder of step 1 but it won't set its creation date to be the same as that folder. I'd expect it to be 9:00, but it will have the current time.

### Server configuration
Raspberry Pi running ownCloud with "version":"6.0.0.16" and "versionstring":"6.0.1".
Database: SQlite.
PHP version: 5.4.4
Updated from an older ownCloud or fresh install: fresh install

### Client configuration
One computer: Windows 7 64 bits
Another one: Windows XP 32 bits (problem happens with both of them).
Client: ownCloud for Windows (obviously :)) v.1.5.0 (build 1913).

Hope you can have a look at this, at least to see if it's reproduceable. Thanks for your time!

**Comment by enoch85** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/8.0/developer_manual/). :)

Thank you!

**Comment by Morganlej** [comment]
Well it is still valid, but probably enough to have #14008 , #1566 open.
So this is intended, by design, and no plans to change?
As it is against users expectation and normal syncing behaviour, it should be clearly noted in user documentation. (maybe it is, have not read it for a while)

**Comment by PVince81** [comment]
It is by design.

We can keep the server ticket as enhancement request though.

**Comment by Morganlej** [comment]
I agree behaviour should be kept as is.
Valid reasons are listed above.
However it should be a FAQ somewhere, and in manual (i do not know the status there)

**Comment by PVince81** [comment]
@carlaschroder is there any doc about the fact that folder mtimes are not synced ?

**Comment by carlaschroder** [comment]
@PVince81 There is not. Yet.

**Comment by toddpfaff** [comment]
This problem still exists in owncloud-8.2.1.

This is a show-stopping problem for some of our owncloud users.  We may have to look at other solutions if this behaviour isn't changed in owncloud.  Since we also have a seafile deployment I'll be testing for this problem on that platform.  I'd hate to have to move our users from owncloud to seafile because of this one problem that seems like it should be quite trivial to solve, but that may be the result.

I understand the "by design" arguments above, but if possible I'd like to see this as a configurable option, if not always on.  That is, for people who want to save sync time and bandwidth, they can disable directory mod time syncing.  For all others, directory time mod syncing is on by default.

**Comment by toddpfaff** [comment]
I'm following up on what I said in my previous post about testing for this problem in seafile.  I've tested for this directory modification time issue in owncloud-8.2.2, seafile-5.0.4, and dropbox.  It seems that at this time seafile is the only one of the three that properly preserves directory modification times.
seafile had a similar problem back in 2013 but they have since changed the behaviour:
https://groups.google.com/forum/#!topic/seafile/D0CwrDH5PBU

**Comment by herrep** [comment]
What about synchronizing the creation and modification date of directories only upon an initial sync, i.e. when creating the directory on the client for the first time? #7119
