### ISSUE TITLE
FEATURE REQUEST: Login using SSL Certificate

### ISSUE THREAD

**Issue by o---** [owncloud/core#7034]
Hi, 

I would like to request a new feature - the possibility to login without password, in case a valid SSL Client certificate has been installed in browser. 

It should work as follows:

1.) Check whether enabled in Admin Menu and site is SSL
2.) Verify certificate validity (APACHE DOES IT FOR US)

``` php
    /**
     * Determines if the browser provided a valid SSL client certificate
     *
     * @return boolean True if the client cert is there and is valid
     */
    public function hasValidCert()
    {
        if (!isset($_SERVER['SSL_CLIENT_M_SERIAL'])
            || !isset($_SERVER['SSL_CLIENT_V_END'])
            || !isset($_SERVER['SSL_CLIENT_VERIFY'])
            || $_SERVER['SSL_CLIENT_VERIFY'] !== 'SUCCESS'
            || !isset($_SERVER['SSL_CLIENT_I_DN'])
        ) {
            return false;
        }
        if ($_SERVER['SSL_CLIENT_V_REMAIN'] <= 0) {
            return false;
        }
         return true;
    }
```

3.) If TRUE, take the user name from

``` php
$_SERVER['SSL_CLIENT_S_DN_Email'] 
```

and validate against user backend. 
3a.) If it exists, log the user in. 
3b.) if it does not, e(USERNAME_NOT_VALID)
4.) If FALSE display the standard login screen. 
5.) If the user cancels the Certificate selection dialog, display the standard login screen.

**Comment by jancborchardt** [comment]
@LukasReschke security feedback here please. Will we ever implement this?

**Comment by DeepDiver1975** [comment]
> Will we ever implement this?

has impact on desktop and mobile clients as well

**Comment by kdslkdsaldsal** [comment]
The desktop client is now supporting client certificates according to https://owncloud.org/blog/new-desktop-client-2-3-0-release-out-now/

> Another great security feature the release includes is support for SSL client certificates that provide an additional layer of security by empowering admins to distribute certificates to users and restrict access thereby (in addition to usual passwords).

**Comment by fjf2002** [comment]
I am currently using client cert auth with Apache and owncloud successfully.

It works well with webdav client and with owncloud server web ui.
(Since the Windows webdav client does not need to ask for a password, it even seems to circumvent some minor known issues.)

### My Apache2 config:
`# ... some other SSL server cert stuff that I omit here ...
SSLVerifyClient require
SSLVerifyDepth 2
SSLCACertificateFile "/root/ca-chain.cert.pem"
<Directory "/var/www/owncloud">
  AuthBasicFake "%{SSL_CLIENT_S_DN_CN}" "password"
</Directory>`

### My owncloud config:
Set each user's password to "password" literally (or anything that matches the `AuthBasicFake` config).

### Considerations
Since any interaction with the owncloud server goes through the apache2 web server and is client-cert authenticated. So the obviously weak "password" password won't matter.

### Questions
My question to you is:

Does my apache2 configuration work together with the owncloud server by design or by accident?

To rephrase it: Is Basic Auth supported by design or by accident?

**Comment by PVince81** [comment]
Can this be implemented as aseparate app ? There are already apps for SSO, so it would likely not be that different from SSO.
