### ISSUE TITLE
Large File Support for 32-bit servers

### ISSUE THREAD

**Issue by bantu** [owncloud/core#7138]
It seems that large file support is possible without performance degradation on 32-bit platforms if PHP is compiled with Large File Support (LFS) and the curl extension is available. 

Please see https://gist.github.com/bantu/886ac680b0aef5812f71 for the full report.

Also see https://github.com/bantu/php-large-files

@DeepDiver1975 @karlitschek @PVince81 @danimo

**Comment by derkostka** [comment]
How are your plans with that ? If you look at all those raspberry-pis and odroid arm devices ..  they perform pretty decent at low power usage.

I would support this change, if needed but i also see the Problem of having a special php5 build dependency. Is this a real Problem or not ? I mean we could force people to install the right php-build can´t we ?
Maybe @jnweiger can tell something about the large integer support on php5 for some well-known linux distributions ?

**Comment by bantu** [comment]
@derkostka A lot of issues related to large file handling have already been addressed, as witnessed by the various tickets and pull requests linking to this ticket (see above). The full report (see ticket description) contains a list of distributions providing LFS (including Raspian Wheezy).

What remains to be done is to look into further functionality that might not work due to large file handling problems, for example WebDAV. If you want to help, feel free to check this out and report back.

**Comment by karlitschek** [comment]
@derkostka It would be great if you could help to test this with ownCloud 8 and give hints what still needs to be fixed.

**Comment by derkostka** [comment]
Here is a first test:
Large File Tests

Setup

Ubuntu 14.04  - 32 Bit - on armhf (hardkernel odroid u2, 4x1,7 GHz Samsung Exynos 32 Bit CPU, 2 GB Ram)
Owncloud 8.1.0 alpha 2
Apache 2.4.7-ubuntu
PHP 5.5.9-ubuntu (lfs support is expected, because the lib folder contains the string "lfs")

Client Machine Mac OS 10.7.5, Core2Duo CPU (64 Bit supported)
Owncloud Desktop Client, 1.8.1-RC1

#1 Upload 1,1 GB File (via browser), random data
MD5 - Source:      a641ac2239747bc271de00e4c8b1a227
MD5 - in OC-Data:  a641ac2239747bc271de00e4c8b1a227
MD5 - Browser-DL:  a641ac2239747bc271de00e4c8b1a227
MD5 - Client-DL:   a641ac2239747bc271de00e4c8b1a227
MD5 - WebDav DL:   a641ac2239747bc271de00e4c8b1a227

Results:
	ALL OK !

#2 Upload a 3,3 GB File (via client, Browser is limited to 2 GB, webdav not writable?), random data
MD5 - Source:      758468161155d637dc03c54de7e5f179
MD5 - in OC-Data:  758468161155d637dc03c54de7e5f179
MD5 - Browser-DL:  758468161155d637dc03c54de7e5f179
MD5 - Client-DL:   error at 2,15 GB, client did not give an error, but the file is truncated
MD5 - WebDav DL:   error at 2,15 GB, cancelled with error
Results: 
       Issue 1: During upload, the client times out, connection breaks at 1000%, but the file is transferred and still beeing put together from the chunks in cache
       Issue 2: The Upload is triggered again by the client, so that File #1 is still copied from cache while the same File is uploaded again
       Solution: The client should complete as soon as all chunks are transmitted, The WEB GUI should show the new File, but "greyed out" somehow to indicate it is still processed

WEBDAV-DL:
Error at the 2 GB Limit :
{"reqId":"VUKoon8AAAEAAAosQ@kAAAAP","remoteAddr":"2a02:2450:102d:3ff:219:e3ff:fe04:2514","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 5242880 got 1490944\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(99): OC\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #40)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(98): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #40)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('largefile_10240...', Resource id #40)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('Attachments\\\/lar...', Resource id #40, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":311}","level":4,"time":"May 01, 2015 00:11:48"}

**Comment by hodyroff** [comment]
32bit will go away sooner or later. If this just works with a newer version of PHP: perfect, but to spend effort doesn't seem to make sense. If an implementation from community comes, we would be happy.
