### ISSUE TITLE
Switch to touch friendly interface when a touch events happens

### ISSUE THREAD

**Issue by icewind1991** [owncloud/core#7318]
For displaying a touch friendly ui, such as using a dropdown for file actions instead of the on-hover buttons, the interface should respond to whether a touch screen is used or a mouse on the fly.

When we detect the first touch event we should switch to the touch interface and when we detect a mouse move we should switch back.

cc @jancborchardt

**Comment by MTRichards** [comment]
I tested this today for ownCloud 8.0.1 pre-release on a touch screen windows 8 intel i5 from Lenovo. It turns out that you can't get the mouse over to work without the mouse, so while the interface works you can't bring up any of the mouse over file actions, such as versions..
 
I think it doesn't recognize the touch screen when the first touch interactions are set up.

Tested Firefox, Chrome and IE 11, and none of them worked.
Testedin Chrome on Android, it worked ok.

**Comment by PVince81** [comment]
Yes, this is why @jancborchardt suggested to move the file actions into a specific menu.
Hover actions are in general not recommended for touch devices.

**Comment by jancborchardt** [comment]
I’m closing this for the more relevant issue https://github.com/owncloud/core/issues/12081 – let’s continue there @MTRichards @PVince81
