### ISSUE TITLE
Backup app

### ISSUE THREAD

**Issue by DanPrs** [owncloud/core#7550]
Though we can sync calender, contacts pics and other items via WebDAV on our phones, I'd love to be able to back up the entire system. Something similar to Go Backup that offers a back up solution to popular cloud services like Dropbox and Google Drive. This is app is available in the Android App store, though I imagine our iOS friends might like a similar solution.

**Comment by Xenopathic** [comment]
-> https://github.com/pbek/ownbackup

**Comment by maystar** [comment]
This app looks nice. But as far I can see the backup and restore is done for all users. This is quite hard to use if you have several users. I'm not sure what @DanPrs expected from this issue, but for me it's not a solution. If this app solves @DanPrs's problem I will open a new issue, otherwise it would be nice to this issue be reopened again.

**Comment by Xenopathic** [comment]
@maystar Well, either way, this sort of thing is the perfect usecase of an app, not core. We always like to see new apps, if you want to try making one? :smile:

**Comment by maystar** [comment]
Sorry I don't have the time and skills to create such an app right now. But I guess it's still ok to file an issue as feature request!? Where should I create the issue if such app does not exist yet?
