### ISSUE TITLE
shared file notification email 2 different message texts when themed

### ISSUE THREAD

**Issue by turbocloud** [owncloud/core#8074]
Hi there,

The situation: 
the mail message is build by \core\templates\mail.php
my customised mail.php file with different wording is at
\themes\mytheme\core\templates\mail.php

The result and problem:
the mail message itself is build from EACH of the 2 mail.php files. 
Will mean: The mail message is send correctly as multipart/alternative . This way we have a plain text version and a html version.
the plain text version is build by \core\templates\mail.php
the html version is build by \themes\mytheme\core\templates\mail.php

This will mean, depending on the receivers choice of plain text or html message, 2 different message text versions are presented. The mail message should be build ONLY from one file.

**Comment by enoch85** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/5.0/developer_manual/). :)

Thank you!
