### ISSUE TITLE
Set default landing page per user

### ISSUE THREAD

**Issue by MU7L3Y** [owncloud/core#8160]
### Expected behaviour
With my set up I have an admin account with a bunch of folders in it. Each of those folders are shared with a different user. When the user logs in they have to go to Shared/folder1 for instance.
I would like a way to set a default location (page) after logging in. For instance, the folder1 as the page that appears after login. Or in other words, I would like a way to set a default login page for each user.

This could be done in the 'users' section of an admin account and users could also do it for themselves in the 'personal' section.

### Actual behaviour
Defaults to Files app and home directory.

### Server configuration
Operating system: Linux Hosting Package

Web server: Apache

Database: MySQL

PHP version: 5.3.27

ownCloud version: 6.0.2

### Client configuration
Browser: Chrome or IE

Operating system: Windows 7

**Comment by alfski** [comment]
I support this. I have a set of non-technical users I would like to configure to land on the 'Shared with you' page on login, rather than default 'All files' page.

So this URL  /owncloud/index.php/apps/files/?dir=%2F&view=sharingin

**Comment by tigerfoot** [comment]
Interested too. Most of my users want calendar as default after login. So easy to do.
Now 3 of them want the files as default.

**Comment by menedas** [comment]
:+1:

**Comment by zkvvoob** [comment]
Hello,

Has there been any progress on this issue? I myself would quite like to see this option in owncloud, if it's not too difficult to implement.

Thank you!

**Comment by karlitschek** [comment]
don't know if anyone works on that. feel free to send a pull request

**Comment by partyisover** [comment]
nothing new here? I'd like to add this feature on my owncloud instance too :-)

**Comment by HLFH** [comment]
Me too @karlitschek ; it's a kind of really needed feature for ownCloud 9.0 milestone.

**Comment by karlitschek** [comment]
@HLFH This needs to be implemented by someone. Either you send a pull request or you convince someone to do the work. I can't just decide that :-)

**Comment by z000ao8q** [comment]
I am interested too - but lack the expertise to do this.
do we need to put up a bounty? :-)

**Comment by bcutter** [comment]
Interested too (but no coding skills).

**Comment by HLFH** [comment]
This issue could be closed. It's available with the plugin [AppOrder](https://github.com/juliushaertl/apporder). I love using it on [Nextcloud](https://help.nextcloud.com/t/migrating-from-owncloud-to-nextcloud/551). Fully compatible with ownCloud btw.

**Comment by DeepDiver1975** [comment]
Nice!

**Comment by RealRancor** [comment]
@HLFH Do you think its a good move to link to a migration doc from oC to NC? This is completely unrelated to this discussed issue.

**Comment by HLFH** [comment]
@RealRancor Forking is sometimes a war, and you choose your side. As you asked, I have removed the unneeded link. But I would say that in 2016, we won the battle LibreOffice versus OpenOffice and I (or we) intend to win peacefully the next one for the sole purpose of having quickly again a great team on a great project. I don't like team splits because it's always a mess and I don't want mess on both sides.

**Comment by RealRancor** [comment]
@HLFH This is not about sides. That you have migrated to NC is an info which doesn't belong in here as it doesn't add value to the issue discussed here.

**Comment by HLFH** [comment]
@RealRancor It's your opinion. Everyone should migrate from OC to NC. I have to help users to follow the right track as we had done for LibreOffice or Popcorn Time. I don't know why OC is still working. It's seems redundant to me since every main dev has gone from [OC to NC](https://github.com/owncloud/core/issues/24864#issue-157003482). Frank Karlitschek and Jan-Christoph Borchardt are working in NC, not OC. So, does that add value to the open source movement to still work in OC?

**Comment by RealRancor** [comment]
Thats a discussion i won't do here... People like you are a good reason to not jump on the NC train.
