### ISSUE TITLE
link to gallery for folders

### ISSUE THREAD

**Issue by tessus** [owncloud/core#8268]
When you share a folder, the link that is shown is always in the format:
`//example.com/public.php?service=files&t=49e186e1cfe7afd7f0bfe638aa5ff16d`

If you share a folder that holds pictures, you might want to share the link to the gallery instead.

What do you think of an additional checkbox (only for folders) that allows you to share the link as:
`//example.com/public.php?service=gallery&t=49e186e1cfe7afd7f0bfe638aa5ff16d`

**Comment by oparoz** [comment]
I agree with the OP. 2 things are missing
* A way to share a public gallery, straight from the files app. It doesn't matter how many pictures there are in that folder. Having OC make an automatic decision is sure to bring pain. The sharing popup overloading is a non-issue. There is plenty of space next to "password" and "editing" to allow for something like "Start with Gallery view". I might even hack something together for the Gallery app since we're already hacking the share dialogue to substitute the default link with our own.
* A button to switch to the gallery view, just like the one available in the public view. Again, this might be doable from the Gallery app until this is sorted out in core.

**Comment by oparoz** [comment]
A possible implementation of the Gallery button
https://github.com/interfasys/galleryplus/commit/9ffac93a1609705daede7be9b98c6c82f6d6893e

**Comment by jancborchardt** [comment]
Automatically using the pictures view when there are more than 80% pictures in the folder would be good, wouldn’t it? The other files could be shown below as well. Kind of similar to the thumbnail view in the Android app https://github.com/owncloud/android/issues/239#issuecomment-55909403

**Comment by oparoz** [comment]
@jancborchardt I could see such an automatic behaviour alienating some users. Imagine you need to edit the readme in that folder. You specifically pick the Files app to be able to work on files and you're always taken to the gallery app.
Having said that, if the gallery view, **from within the Files app**, included a mix of Files and pictures, then yes, the view should definitely switch to a thumbnail arrangement, as shown on the screenshot.

**Comment by jancborchardt** [comment]
@oparoz I was just referring to how the public view is shown. That is, when you share a link to a folder which mainly contains images, it should show the image thumbnail view by default. Instead of requiring people to manually switch to that.

**Comment by oparoz** [comment]
@jancborchardt - Ah, good point. So core would add a thumbnail view of files which is separate from the Gallery app, but that wouldn't solve the OP's problem if he wants users to **really** land on the Gallery page, because it looks nicer, has more functionalities, etc.

**Comment by oparoz** [comment]
Available in Gallery+ 1.0 for ownCloud 7 (and master)
![Screenshot](https://oc7demo.interfacloud.com/public.php?service=files&t=b5a628aee0723ab20466521c8bd73eb3&download)

**Comment by tessus** [comment]
@oparoz how do I get Gallery+ and how do I get this to work on my installation? Can I assume that this patch is not in the product?
Any pointers would be appreciated.

**Comment by oparoz** [comment]
@tessus - If you're running ownCloud 7, you can simply use the releases found on here: https://github.com/interfasys/galleryplus/releases
The gallery button and link changer are included. You'll only need to patch your oC if you want improved performance + support for more media types.
You'll need to de-activate your current gallery app before activating the new one.
Also, make sure you're running a supported version of PHP (5.4+).

**Comment by tessus** [comment]
@oparoz great, thanks for the info. I hope these changes will be in oc8 as well. especially the performance changes. what happens, if I install oc8 in about a month? is there a gallery+ for oc8?

**Comment by oparoz** [comment]
@tessus - The goal is to make Gallery+ the official Gallery app at some point in the near future. That's why very little has changed in terms of the UI and its organisation, compared to what will officially launch with OC8. It's just an easier to maintain and more "legal" app (relies less on internal APIs) than what is currently available.
The performance changes won't be available in oC until 8.1, but there will be a Gallery+ available on oC8, I'm just waiting for it to launch before I package anything, so that I can make sure patches work, etc.
The Gallery button and share dropdown modifications might not make it in the official version of the app if the community doesn't approve of it, but I'll try to keep them in a separate branch for people who need it.

**Comment by oparoz** [comment]
I like how Pydio is letting the sharer pick a layout
![01-share-minisite-layout](https://cloud.githubusercontent.com/assets/323220/7242859/fa88426e-e7c6-11e4-9b14-77c3595a94f9.png)

**Comment by jancborchardt** [comment]
@oparoz why should we make it so complicated? Let’s not use other open source software as comparison, but rather more widely used stuff such as Dropbox and Google Drive. ;)

We all know open source apps like settings – but with ownCloud we aim to provide a more smooth UX than traditional open source apps.

**Comment by oparoz** [comment]
@jancborchardt - I don't find that dialogue that complicated, but even if it was, that could be the expert view. oC is missing something like that.
But that's not the point, the scary selector is convenient, because it means apps can augment it:
* Standard Files layout
* Gallery layout
* Document layout (that would be great!)
* Music layout (also great!)

And a selector could easily be replaced by buttons.

**Comment by oparoz** [comment]
@tessus, from Gallery release 12, the link chooser will only be available via an app. Use [the issue tracker](https://github.com/interfasys/sharelinks/issues) there if you have any specific requests.

**Comment by jancborchardt** [comment]
Isn’t there some way we can say that when the folder is images-only, to automatically use the gallery style layout link?

**Comment by jancborchardt** [comment]
Options on options might be interesting for the 1% of power users, but the majority of regular people just prefer good defauts to work. :)

**Comment by oparoz** [comment]
That's the reason it's convenient to now have it in an app. Power users can enable it to have direct access to the links they need.

Ideally, the Files app should provide all these different layouts. It's just a simple view change if all the information has been loaded. Switching layout by using apps is way too slow currently.

**Comment by jancborchardt** [comment]
@oparoz well – the problem still stands though: When you share a folder which is 100% images, you need to either share it from the gallery app or change the link manually. Otherwise it will show as list, whereas clearly the better layout is the gallery thumbnails.

**Comment by oparoz** [comment]
I think it wouldn't hurt to reword the title. The description needs to be rewritten anyway since it's not using proper English and is too aggressive.

**Comment by oparoz** [comment]
Well, the app let's you magically change the link, so it's very easy for users, but it's true that it's not done automatically.

Try it with the dev branch of Gallery and master of sharelinks. (When sharing a link you get a choice between the standard link and a direct download link.)

The app could pick a sane default, but the main problem is that there is no magic method which automatically selects media files, so an extra call would have to be made to the Gallery app to get a list of media type and then we'd use that to filter the files list. Not worth the extra waiting time imho.

**Comment by tessus** [comment]
@oparoz Thanks, this is great. Unfortunately I haven't installed 8.x yet, but I will as soon as 8.1 is out.
The GUI of ownCloud seems a bit sluggish at times and lacks certain functionality (even if the functionality is there, it's not very intuitive and can be cumbersome). Most of the time I use the sync client only, but I have to use the web interface for sharing, because I use PathFinder, thus no sharing context menu. :-(

**Comment by tessus** [comment]
@jancborchardt 
> Options on options might be interesting for the 1% of power users, but the majority of regular people just prefer good defauts to work. :)

I don't agree. Most people want an easy way to share links. What can be easier than choosing between 2 options: share as gallery / share as list? All the defaults and the resulting code around it makes the code more complex and slower.

**Comment by tessus** [comment]
What I find strange is the following: owncloud should be about sharing files, yet a separate app has to be written to get the functionilty that should have been included from the start. I'm grateful to @oparoz to provide the much needed (and in my opinion basic) functionality.

This is not a hate post or anything, it's just that I don't get it. Maybe I misunderstood the main reason and application for owncloud. Please let me know and correct me, if owncloud's main focus is not sharing files.

**Comment by jancborchardt** [comment]
> What can be easier than choosing between 2 options: share as gallery / share as list

Simple: the software deciding on a reasonable default automatically based on the content of what is being shared.

Yes, ownCloud’s main focus is syncing and sharing files. In an easy fashion though, which is on par with and surpassing proprietary alternatives. Not something which is riddled with settings where every little thing has to be decided by every single person using the software.

**Comment by tessus** [comment]
What, if the SW picks the wrong default? I'm sorry, but I don't like something choosing for me. I make the decision. You don't give the user a choice. IMO that's not reasonable, but cumbersome.
Anyway, now there's an app that solves the problem. 

Also, this is not a little thing. There's nothing easy - as you call it - about it, if you are in a deep folder structure and have to switch to a different app and start all over again, just to get the link you want.
We have obviously different opinions on what is easy.

**Comment by jancborchardt** [comment]
> There's nothing easy - as you call it - about it, if you are in a deep folder structure and have to switch to a different app and start all over again

The Gallery+ app easily solves that by introducing a switcher between Files and Gallery.

**Comment by oparoz** [comment]
I think the automatic choice works well if you have access to exactly the same content, but just presented differently.
If I share a folder containing designs, mockups and some specs documents, then I don't mind if the view shows thumbnails like in the Android app, because all the documents are there and if the recipient prefers to see a list view, the change would happen very quickly.
The Gallery photowall is something different and if that was automatically chosen for me for that folder content, then I wouldn't be happy about it and would be looking for a way to get the link I want.
Granted, it's a pretty specific use case and most users will probably organise their content differently (documents, photos, movies, etc.), but for web agencies, the default wouldn't work very well.

Luckily, we can add functionalities through apps and I hope @jancborchardt will help improve [its design](https://github.com/interfasys/sharelinks/issues/2) :)

**Comment by jospoortvliet** [comment]
@oparoz I kind'a like the current behavior - if you share from the gallery, you get a gallery link. If you share from the Files app, you get a Files view. And recipients can switch, of course. Isn't that good enough?

**Comment by oparoz** [comment]
@jospoortvliet - I'm not the one who made the request and based on downloads of ShareLinks, there either is a small percentage of ownCloud users who need that functionality or users don't know about the app.

I don't think it would require such a large effort to introduce and maintain an API so that apps can offer users a way to pick the kind of link they want to share and it really makes sense in a sharing solution, but I don't have the roadmap or the resources allocation table, so it's up to the core team to define the priority of this feature.

In the meantime I'll try to keep ShareLinks alive.

**Comment by tessus** [comment]
@jospoortvliet this requires you to use the gallery app to browse through folders and then share a link. This can be slow, if you have a lot of folders and files in each of the directories.
Or you could switch to the gallery view right before sharing, which might also be slow and is not a good UI design.
Thus I like to use the file sharing app to walk the directory tree and have just a button to switch between the 2 links. ShareLinks has been the best design add-on so far and hope it will be around for a long time.

**Comment by jospoortvliet** [comment]
@tessus I'm not saying it is ideal, but neither is adding options to the share dialog. The question is what is more cumbersome - crowding the share dialog more, increasing the barrier to ownCloud usage (yes, it's one button, but they add up) to save an occasional click to the 'other' view? Not sure if it is worth it. This of course gets us to the area where things become subjective, but on a whole, I think it is good that we are being conservative (if there is no great, clear need for a button, let's not add it). That is what has kept the ownCloud ui clean and usable.

I don't see a huge, pressing need if it is easy for both sender and recipient to switch and get the result they want.

**Comment by tessus** [comment]
@jospoortvliet I agree to disagree.
> That is what has kept the ownCloud ui clean and usable.

I'm sorry, but there are parts in the GUI that are everything but clean and usable. e.g. moving files, deleting users (after 10 seconds all data is lost, if you don't click undo). But that may be off topic here.

About which other things are you talking about when you say 'they add up'? What else is there? Also, there's space for at least 10 additional things in that dialog w/o getting cramped.
And if that crowded look is really a concern, how about introducing a section in the admin or user panel, where someone can decide what to show in the share dialog? Wouldn't tahat make sense?

**Comment by tessus** [comment]
After 6 years we can close this. Brilliant.
