### ISSUE TITLE
[6.0.3] Need save button on LDAP wizard

### ISSUE THREAD

**Issue by ser72** [owncloud/core#8745]
The LDAP Wizard makes all changes dynamically.  In the case of using Raw filters, if a user accidentally deletes the working filter, or accidentally types something else in the filter box, it is automatically saved and the working filter is lost.

It is requested to have a save button or require the user to select "Continue" prior to saving the changes to the filter.

**Comment by PVince81** [comment]
The new LDAP wizard since 8.1.3 has less magic and more "click button" to test. It's not a "Save" button but might still help a bit, hopefully.

**Comment by blizzz** [comment]
Exactly, we're acting smarter now and the wizard is more robust as well. Which is also the friendlier way to go. Therefore, and because save buttons are against our philosophy, I am closing this now. If there are specific issues less, we can still reopen or better open a specific report about a problem you have and we'll look for a good solution for this.
