### ISSUE TITLE
Create User when using user_webdavauth

### ISSUE THREAD

**Issue by mstinaff** [owncloud/core#8749]
When using WebDAV Auth, after a user logs in a user directory is created but the user does not appear in the user admin interface and as such cannot be assigned to groups or have the user's quota adjusted.

Similar to the following issue, could a similar solution apply?:
Changes to user_external #4567
Implement request #301: Create users when using external auth login #1579

**Comment by enoch85** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/5.0/developer_manual/). :)

Thank you!
