### ISSUE TITLE
Web Based File Upload Chunking

### ISSUE THREAD

**Issue by matart** [owncloud/core#8955]
### Steps to reproduce

Web based large file upload
### Expected behaviour

File gets chunked and multiple ajax requests send the chunks to the server for reassembly
### Actual behaviour

File is uploaded as a whole file. A single request is made
### Server configuration

**Operating system**: RHEL 6

**Web server:** NGINX

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:**  6.0.3

**Updated from an older ownCloud or fresh install:**

**List of activated apps:** Files, Activity, Contacts, Pictures

**The content of config/config.php:**

I had to remove the identifying URLs so it seems a little empty.

```
<?php
$CONFIG = array (
  'instanceid' => 'oc8fdcdb7be6',
  'passwordsalt' => '',
  'datadirectory' => '/var/www/html/macdrop_assets',
  'dbtype' => 'mysql',
  'version' => '6.0.3.1',
  'dbname' => '',
  'dbhost' => '',
  'dbtableprefix' => '',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'theme' => 'macdrop',
  'proxy' => '',
  'loglevel' => '2',
  'maxZipInputSize' => 1073741824,
  'allowZipDownload' => true,
  'mail_domain' => '',
  'mail_smtphost' => '',
  'mail_smtpname' => 'macDrop',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'url1',
    1 => 'url2',
  ),
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
### Client configuration

**Browser:** Chrome

**Operating system:** Windows
#### Browser log

This is a 1.7GB file. One request taking 3.2 minutes.
![no_chunk](https://cloud.githubusercontent.com/assets/4175158/3221505/f1a27c04-f00b-11e3-944a-3add85c7785f.png)

If this feature does not exist I am willing to look into implementing it and making a pull request.

**Comment by tylla** [comment]
Yes that app was working until OC 8.0. Now it is defunct and the maintainer has some problems fixing it.
I believe too that this functionality should be implemented as a core functionality, so someone with enough knowledge should take a look at that app's code and merge it to the core. Unfortunately I'm not that person.:(

**Comment by PVince81** [comment]
Yes, would be a nice addition.

Note that there are plans to make the web UI use WebDAV first: https://github.com/owncloud/core/issues/12353

This means it will become possible to use chunking too through the WebDAV endpoint.

**Comment by tylla** [comment]
As I found out, OC 8 uses [jQuery-File-Upload](https://github.com/blueimp/jQuery-File-Upload) and as I discovered [here](https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads) jQuery-File-Upload already supports chunked uploading. One only has to override the maxChunkSize variable with some sane value instead of the default "undefined", and after that the upload starts to send chunks with the specified size instead of whole files.
For testing I changed to
```maxChunkSize: 1000000, // 1MB```

One problem exists though. At the end of the upload there is an error message that asks whether I want to overwrite the same file with the same file. If it's gibberish what I say, there is a screenshot attached. There you can see that the already uploaded image is only the first chunk (there is some missing data from the image too) and asks me to overwrite it with the full file. But if I choose the newer or both files it just hangs after I click the Continue button. After this I can click the Cancel, but then I'm also only with the partial file.
BTW it throws a console error when I click the Continue button:
```TypeError: data.formData.push is not a function```
```    data.formData.push({name:'resolution', value:'autorename'}); //hack for ie8```
```file-upload.js?v=8ca31e8dc30c45c0bf2c0abdfb1746bd (line 155, col 42)```

Hmm, this starts to look as a bug report... maybe I should file it as such.

![owncloud_chunk_upload_error](https://cloud.githubusercontent.com/assets/4119572/7653859/31deaec8-fb19-11e4-87b0-7ad283682237.png)

**Comment by PVince81** [comment]
But also I believe that the ajax/upload.php endpoint does not support chunks, so it probably won't work.
Ideal would be to use the WebDAV endpoint instead.
Note that the WebDAV endpoint uses custom chunking (so does the sync client), so it might not work either with a "standard" solution.

Either way, it will need a bit of work to make this.

Still, any information you post here could be useful for that, so thanks :smile:

**Comment by PVince81** [comment]
I guess it asks you for overwrite because for each chunk sent to upload.php, it saves it as a new file. Because the ajax/upload.php endpoint doesn't understand chunks. And since the file exists already, it shows you that dialog. (just guessing)

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/26306

**Comment by PVince81** [comment]
new/updated PR here: https://github.com/owncloud/core/pull/28415

**Comment by PVince81** [comment]
Reopening this to address the "public page upload" which cannot use chunking currently due to API limitations: basically the chunking API only works for authenticated clients and needs to be enhanced.

**Comment by PVince81** [comment]
Requires https://github.com/owncloud/core/issues/23269 to provide a public DAV server that supports multiple subpaths like "public.php/dav/uploads".

**Comment by hodyroff** [comment]
People can use the guest app. Receiving chunked uploads via webfrontend seems not a P1 priority, adjusting. Please add your vote here if you need this.

**Comment by PVince81** [comment]
What we need to make anonymous upload support chunking:

- [ ] New Webdav endpoint for public file access: https://github.com/owncloud/core/issues/23269
- [ ] Adjust the "uploads" Webdav endpoint to also allow anonymous users to use: I suggest using the share token instead of user id. We also need to make sure that concurrent anonymous users cannot influence each other's uploads.
- [ ] Adjust public link page frontend to use the two points above for file access and uploads

**Comment by fritzmg** [comment]
I would love to see chunking implemented for public anonymous uploads. This way we can send customers or service partners simply a public link for a folder which has __Upload only (File Drop)__ enabled and they can drop in their files there, which might be several Gigabyte in size, without having to create a guest account.

**Comment by hurradieweltgehtunter** [comment]
Since we advertise no upload limits on public uploads on certain projects I wanted to raise this topic.

**Comment by butonic** [comment]
cc @C0rby

**Comment by micbar** [comment]
This is a won't fix. We may have this in ownCloud infinite scale where we us tus.io as an upload protocol.
