### ISSUE TITLE
Get rid of monster classes containing only static methods.

### ISSUE THREAD

**Issue by bantu** [owncloud/core#9078]
Examples of large classes only containing static methods that are not 
really related to each other:
https://github.com/owncloud/core/blob/master/lib/private/util.php
https://github.com/owncloud/core/blob/master/lib/private/helper.php
https://github.com/owncloud/core/blob/master/lib/base.php
This code should be in individual helper classes which are used as 
objects such that they can be easily mocked in tests.

**Comment by PVince81** [comment]
Yes, bumped into such case. It will take me much longer to write a unit test now because I need to setup the full filesystem (with a few complications) instead of being able to use a mock.

**Comment by PVince81** [comment]
It looks like it will be a lot of work to make these static classes non-static.

Here is an idea for a transitional state: how about adding static dependency injection:
```php
   public static function setView($view) { $this->view = $view; }
```

Then in the touched code (assuming someone is working on a feature that will need to be tested soon):

replace:
```php
   $view = new \OC\Files\View(...);
```
with
```php
   $view = $this->view;
   if (!$view) {
      $view = new \OC\Files\View(...);
   }
```

Then use `setView()` to inject a mock view if needed in the unit tests.

This would at least allow for partially porting classes to a proper dep injection as we touch them.
Also the test code can then use "setView()".

Once all attributes can be injected, we can then convert the class to a non-static class and move all members to be injected in the constructor.

This solution would help to move forward with fixing static classes gradually, because at the moment it feels like it's "either fix the whole class or nothing" which isn't possible in most cases and might be too risky.

If it's a function that needs to be tested anyway, it is the opportunity to fix that one.

**Comment by PVince81** [comment]
Note: if we don't strive to move forward to this, the static classes will likely be perpetuated (and the time wasted when writing unit tests (or skipped unit tests)). Whoever is adding functionality there will likely have to continue to use the same pattern as there is currently no solution in place.

**Comment by MorrisJobke** [comment]
We all know that this is the direction to go into. We will not replace all static monster classes with their proper implementation. Rather we will move this forward in small steps but continuously. I don't think that this ticket here helps to tackle this. We all know what to do and already review in the sense of this ticket. I will close this ticket because it is of no additional information for devs.
