### ISSUE TITLE
Deleting documents takes so time

### ISSUE THREAD

**Issue by vgcouso** [owncloud/core#9217]
I've more than 200.000 documents in my profile and when I want to delete one folder seems to be imposible becouse takes a lot of time (several minutes).
It's the same in folders with little documents.
This happens in the web and my version is 6.0.3
I've Xampp with Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.11 in a windows 8.1 pro and opcache enabled

**Comment by enoch85** [comment]
Any update on this?

**Comment by PVince81** [comment]
There are two tasks in progress.
1) Make trashbin expiration faster: https://github.com/owncloud/core/pull/14640 (hopefully backportable fix)
2) Move trashbin expiration to a background job (for OC 8.1): https://github.com/owncloud/core/pull/14644
3) Instead of copying file to the trash, move them: this is already in OC 8.0.0 (https://github.com/owncloud/core/pull/13377)

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/13974#issuecomment-77531761
