### ISSUE TITLE
404 not found right after installation: missing rewrite rule?

### ISSUE THREAD

**Issue by segdy** [owncloud/core#9395]
I just installed the 7.0.0beta1 via apt-get on my Debian 7 server.

I surf to https://192.168.200.121/owncloud/ and immideately get a 404.

In the error.log:

 File does not exist: /var/www/owncloud/index.php/apps/files

Obviously because index.php is a file, not a directory!

Ok, let's have a look into .htaccess:

RewriteEngine on
RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
RewriteRule ^\.well-known/carddav /remote.php/carddav/ [R]
RewriteRule ^\.well-known/caldav /remote.php/caldav/ [R]
RewriteRule ^apps/calendar/caldav\.php remote.php/caldav/ [QSA,L]
RewriteRule ^apps/contacts/carddav\.php remote.php/carddav/ [QSA,L]
RewriteRule ^remote/(.*) remote.php [QSA,L]

There is no rewrite rule for that!
How can that be?

mod_rewrite is on, I tried all kinds of URLs such as https://192.168.200.121/owncloud/index.php, https://192.168.200.121/owncloud/index.php/ or https://192.168.200.121/owncloud/index.php/apps/files.

**Comment by enoch85** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/5.0/developer_manual/). :)

Thank you!
