### ISSUE TITLE
owncloud doesn't work after update - "This ownCloud instance is currently being updated"

### ISSUE THREAD

**Issue by Nowaker** [owncloud/core#9411]
After update the app no longer works, it's stuck on the update screen. No errors in owncloud.log. No errors in nginx error.log.

```
{"reqId":"X","app":"core","message":"starting upgrade from 6.0.3.1 to 6.0.4.1","level":0,"time":"2014-07-03T11:34:38+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=Y"}
```

So generally, the app is stuck on update screen but no update is being performed. This happened for the second time for me, hence I'm reporting this bug. I don't remember what I did previously to get this working.

**Comment by Xenopathic** [comment]
@Nowaker This looks like the update procedure was interrupted, so while maintenance mode was activated ("This ownCloud instance is being updated")  the update wasn't performed and maintenance mode wasn't deactivated. However, due to the age of this bug with no progress, I'm closing this. If you discover this problem again, feel free to open a new issue.
