### ISSUE TITLE
uft-8 content-type for downloads

### ISSUE THREAD

**Issue by cabotine** [owncloud/core#9673]
Hi,
I ran into this while trying to import ics-file via public link into Google Calendar. At the moment it has difficulties with umlauts (ä,ö,).
It would be useful if the Content-type charset for text is set to utf-8
My workaround in lib/private/files.php looks like this:
if (\OC\Files\Filesystem::getMimeType($filename)== "text/calendar") {
                header('Content-Type: '.\OC\Files\Filesystem::getMimeType($filename).'; charset=utf-8'); }
                else {header('Content-Type: '.\OC\Files\Filesystem::getMimeType($filename));}

**Comment by enoch85** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/5.0/developer_manual/). :)

Thank you!
