### ISSUE TITLE
Themes enabled after upgrade [6.0.3] to [6.0.4]

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#9773]
After upgrading 6.0.3 to 6.0.4 the Themes are still enabled:

According to @karlitschek  in https://github.com/owncloud/core/issues/4403 should be disabled.

**Comment by MorrisJobke** [comment]
I guess this is caused by the new additional config files named like `my.config.php`, where the theme is specified. Then it gots overwritten, but ownCloud just writes into `config.php` which itself just got overwritten by other config files like the `my.config.php` and then the theme is still active.

As it is low prio I move it out of this milestone. Also nothing critical and there are bigger problems nowadays.

Workaround would be to remove the `theme` setting from the other `....config.php` in `config` folder.

**Comment by cdamken** [comment]
@MorrisJobke This is really old already, was it fixed? IMHO we can close it now.

**Comment by MorrisJobke** [comment]
Yes works now :+1:
