### ISSUE TITLE
After Upgrade from 6.0.4 and after new installation broken interface view 

### ISSUE THREAD

**Issue by Mikel1961** [owncloud/core#9860]
After upgrade a owncloud installation from 6.0.4 to 7 or after a complete new installation from owncloud 7 i get a broken interface view (see pictures). 
What happened here, something wrong with server adjustment, but owncloud 6 works without problems?
if someone has a tip I am grateful.
![owc7](https://cloud.githubusercontent.com/assets/1343669/3688726/4c02ab10-1339-11e4-8e9f-3c8377df0120.jpg)

**Comment by enoch85** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/8.0/developer_manual/). :)

Thank you!
