### ISSUE TITLE
[OC 7.0.0] [Regression?] DOCUMENTS do not show preview.

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/core#9873]
<img src="http://i.imgur.com/GdTWLBg.png">

I don't know, why the preview is gone. Unsure, if thre was a preview in pre-7.0.0 versions.

**Comment by PVince81** [comment]
@VicDeo what's the next step here ?

**Comment by VicDeo** [comment]
@PVince81 I use `OC.generateUrl('/core/preview.png?') + $.param(urlSpec);` there https://github.com/owncloud/documents/blob/stable7/js/documents.js#L61
the rest is done by core preview.

@Wikinaut do you have .doc previews in Files app?

**Comment by PVince81** [comment]
Any update ? Is this problem still happening in 7.0.7 or 8.0.5 ?

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/8.1/developer_manual/). :)

Thank you!
