### ISSUE TITLE
Not updated .htaccess file causing broken layout in OC7

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#9937]
Hi,

recently we have a lot of reports at the forums:

https://forum.owncloud.org/viewtopic.php?f=29&t=22483
https://forum.owncloud.org/viewtopic.php?f=29&t=22536
https://forum.owncloud.org/viewtopic.php?f=29&t=22570

and also at the issue tracker here: https://github.com/owncloud/core/issues/9522 about broken layout after upgrading to OC7.

Those are caused by a not updated .htaccess file from OC 6.0.x which contains this additional line:

https://github.com/owncloud/core/blob/v6.0.1/.htaccess#L29
https://github.com/owncloud/core/blob/v6.0.4/.htaccess#L29

Don't know if it could be useful to detect this and show a warning to the user to update the .htaccess file?

**Comment by MorrisJobke** [comment]
@LukasReschke What is the state of this?

**Comment by LukasReschke** [comment]
See my PR - solution was apparently not maintainable enough => Not merged ;-)

Whoever has another idea: feel free to do it. In the worst case scenario we would need to have to grep the .htaccess file for some known old entries. But that would be a major hack that I would like to avoid.

**Comment by ubuntuaddicted** [comment]
What exactly does this mean if anyone can explain please. In using Owncloud
for my small business, I added it via some PPA if I recall and I can't even
bring up my owncloud home page but my issue may be related to a host name
change on the server which screws up the database. I'm in testing now, so
it's no big deal to start a fresh SQLite database.

**Comment by MorrisJobke** [comment]
@ubuntuaddicted please don't use PPAs as they aren't the official packages we support. We have our build infrastructure on OBS which also contains repos for all current ubuntu versions:

http://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud simply click on the ubuntu icon there and the instructions will appear.

Is your issue then gone? This issue shouldn't arise if you use our official packages.

**Comment by DeepDiver1975** [comment]
I vote for closing this - if (due to what ever reason) not all files are updated during an update mechanism there is not much we can do. Using proper packages and reading docs really helps.

@carlaschroder for the sake of it - can you please add a sentence about copying hidden files during upgrade? THX

**Comment by karlitschek** [comment]
I general I agree. And there is definitely no real bug on our side. 
On the other hand this often creates unhappy users and a bad reputation independently whos fault it is and if it is documented or not.
Maybe we should go back to the suggestion of @LukasReschke and somehow detect if the .htaccess that is there is the right version?
Just to guide our users into a better direction

What do you think?

**Comment by ubuntuaddicted** [comment]
i was already running owncloud from the location you linked, i misspoke earlier when I said i was running it from a ppa. Here's the exact error now that I'm at my server console. 
An exception occurred while executing 'SELECT "configvalue", "appid" FROM "oc_appconfig" WHERE "configkey" = ?' with params ["enabled"]: SQLSTATE[HY000]: General error: 1 no such table: oc_appconfig

any help would be appreciated and i am not adverse to just restarting as I think i messed it up my self because I attempted to move the data folder for a user because I ran out of storage where i originally put ownload data which was the default location

**Comment by RealRancor** [comment]
@ubuntuaddicted 
Such SQL errors are not related to this issue

@karlitschek 

:+1: for your posted suggestion.

**Comment by ubuntuaddicted** [comment]
ok, sorry about that and thanks for the pointer. i figured it was a mysql due to me changing my hostname on my server. ;)  @RealRancor i also concur, this can be closed. awesome work from all the dev's by the way! THANKS for being awesome

**Comment by MorrisJobke** [comment]
@karlitschek Then I would vote for the version somehow placed in the htaccess. Yes it is more maintenance for the release, but something has to be done and I don't see a way (except copying the htaccess to properly be able to diff the file, which would be overkill from my pov) to do this in another way. Opinions?

**Comment by LukasReschke** [comment]
Before somebody starts reimplementing stuff: https://github.com/owncloud/core/pull/11114 ;-)

**Comment by karlitschek** [comment]
Thanks @LukasReschke 
This old approach is not super elegant but maybe the best we can do.
I would vote for that.
