### ISSUE TITLE
Allow each user to decide if they want encryption or not?

### ISSUE THREAD

**Issue by hynese** [owncloud/core#9967]
Hi,

We're considering deploying an owncloud.

The encryption feature is great.

However, not all our users want this. Can an individual user disable encryption?

**Comment by PVince81** [comment]
@schiesbn

**Comment by PVince81** [comment]
Not possible with the current encryption system because shared files might or might not be encrypted depending which user chose to encrypt or not.

**Comment by PVince81** [comment]
This would now be possible when using the master key, assuming that the decision whether to encrypt or not is based on the owner of files in sharing scenarios.

**Comment by PVince81** [comment]
The problem with having partial encryption is that it gives some users a false sense of security: files encrypted for one user but not for received shares since the other user did not enable encryption.

The encryption API allows for third party encryption modules so if someone does want to implement this it can be done as a separate app.

cc @pmaier1
